### ISSUE TITLE
VP abnormally high

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#10]
Created: 2014-12-03
Migrated from https://sourceforge.net/p/mars-sim/tickets/20/ 

Screenshot from 3.07 r3012 (all the new food items have VPs starting r3012 that patched GoodsManager.java)

Some construction amount resource such as Calcium Carbonate, Lime, Cement and Polyester Resin
and item resources such as Aluminum sheet and steel sheet often have unusually high VPs most of the time. It seems artificial. In real life, it won't go up this much.

Does the algorithm needs tweaking ?

Should the "RAW MATERIAL" cost less than their resulting/assembled items or equipment ?

Should we "cap" the growth of VPs on them ?

**Comment by larsnaesbye** [comment]
![some vps abnormally high](https://cloud.githubusercontent.com/assets/7767079/22947027/c428e81e-f2f9-11e6-8c1c-cb168e4e0111.png)

**Comment by mokun** [comment]
This anomaly has been addressed by Scott a while ago on some builds that modify GoodsManager.
