### ISSUE TITLE
Build target files with correct name for release

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1007]
**Is your feature request related to a problem? Please describe.**
When doing a Maven package the file executable files (DEB & JAR) do not have the correct names for a release.
When creating a release the files need to be renamed before uploading.

**Describe the solution you desire to see**
Change the POM so the final deliverable re correctly named out of Maven. This will simplify the release procedure.

**Comment by mokun** [comment]
I suppose this involves changing the params in two plug-ins in mars-sim-main's pom.xml, 

```xml

			<plugin>
				<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-assembly-plugin 
					 https://maven.apache.org/plugins/maven-assembly-plugin/ : 235 KB 
					 For creating a self-contained Jar file containing the code from modules along with dependencies
				-->
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>						
							<mainClass>${mainClass}</mainClass>
						</manifest>
						<manifestEntries>
						    <Multi-Release>true</Multi-Release>
						</manifestEntries>						
					</archive>
				</configuration>
				<executions>
...
			<plugin>
				<!-- https://github.com/tcurdt/jdeb -->
				<!-- https://mvnrepository.com/artifact/org.vafer/jdeb : 1.8 MB -->
				<groupId>org.vafer</groupId>
				<artifactId>jdeb</artifactId>
				<version>1.10</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>jdeb</goal>
						</goals>
						<configuration>
							<dataSet>
								<data>
									<src>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</src>
									<type>file</type>
									<mapper>
										<type>perm</type>
										<prefix>/usr/share/mars-sim-main</prefix>
									</mapper>
								</data>

```

Do you mean changing this line:
> <src>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</src>

**Comment by bevans2000** [comment]
Yes but dropping the java17 component as well

**Comment by mokun** [comment]
> dropping the java17 component as well

Do you mean you want to drop the format of using the word `java17` in the filename ?

**Comment by mokun** [comment]
See this [page](https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-runnable-jar-with-dependencies-using-maven) for various plug-ins in how a jarfile name is pre-defined.

Not sure if you can define your own filename.

**Comment by bevans2000** [comment]
The final JAR file names currently don't have the name of the project embedded which is odd. This issue will update the final names to be more consistent and stable:

- Swing - base name _mars-sim_swing_X.Y.Z_
- Headless base name is _mars-sim_headless_X.Y.Z_

These will be built directly from the maven build; simplifying the release process.

This means some of the supporting docs will need to change.

**Comment by bevans2000** [comment]
Final jar files and correct name and Docker image will be created when the code is tagged/labelled automatically. Docker action can also be run manually.
