### ISSUE TITLE
Improve the format or definition of mission and science study identifier

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1015]
**Is your feature request related to a problem? Please describe.**
- Each sol, there are as many as 40 missions being proposed. 
- Sometimes over 80% mission planning proposals are being turned down.
- After a few sols, I can see the mission id could go up beyond 200.

**Describe the solution you desire to see**
- Increment the id on each mission type, instead of tallying all mission types 
- Begin that id with the mission sol, followed by the mission id.
   - For example, if the proposal is submitted on sol1, instead of calling it `Mineral Exploration #3`, shall we call it `Mineral Exploration #1-3` ?
- This change should go hand in hand with the `Mission Designation`

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/1bb51664-dd58-4d2d-bc71-abcaf9d89794)

**Stacktrace**
```
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Mission 'Ice Prospecting' score: Score:3.84 (base:1,settlementratio:1,minerals:4,leader:0.32,extrovert:1.5,goods:1,population:2)
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Mission 'Regolith Prospecting' score: Score:5.383 (base:1,settlementratio:1.4,minerals:4.005,leader:0.32,extrovert:1.5,goods:1,population:2)
01-Adir-01:000.518 (Info) Exploration : [Hong Tian] A site has an Exploration Value of 249.98.
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Mission 'Mineral Exploration' score: Score:22.8 (base:1,settlementratio:1.9,minerals:10,leader:0.32,extrovert:1.5,goods:1.25,population:2)
01-Adir-01:000.518 (Info) AbstractMission : [Hong Tian] Te Luo - Began organizing a Mineral Exploration #5 mission.
01-Adir-01:000.518 (Info) SurfaceFeatures : [Hong Tian] 20.8362 N 51.5584 W has no mineral concentrations.
01-Adir-01:000.518 (Info) AbstractVehicleMission : [Hong Tian] Te Luo - Preparing Mineral Exploration #5 using Shenzhou.
01-Adir-01:000.518 (Info) PlanMission : [Hong Tian] Te Luo - Submitted a mission plan for Mineral Exploration #5.
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Put together a mission plan for Mineral Exploration #5.
```

**Specifications  (please complete the following information):**
 - post 3.6.1 build 8591

**Comment by mokun** [comment]
@bevans2000 

I can see we need to set some limits : 
- If a person is interested in submitting a proposal, then it should have already taken him, say, 3 sols, to prepare for it. It's not just a spur of a moment that he wants to do it. 
- Similarly, if a person already submitted a proposal, he should probably pause and wait for a few sols before trying it again.

**Comment by mokun** [comment]
Also, may be we should also set up a priority queue to have player decide what types of mission he wants to have priority over.

**Comment by mokun** [comment]
Similarly, the science id needs to be incremented based on each category of science subject.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/ecb97876-fc14-48ef-bb46-1a1de97abab5)

At sol 1:438, the science study ID has already reached 81. 

We could have done it differently.

**Comment by mokun** [comment]
> At sol 1:438, the science study ID has already reached 81.

@bevans2000 @Urwumpe 

How would you like to improve on giving an unique identification id (an alphanumerical string ?) for each scientific study ?

**Comment by Urwumpe** [comment]
@mokun I would reduce it to a pure technical ID and not care much about it. Also only display this ID as needed and with low priority. For the human it gives no value, only for debugging, it could be useful. It may include some characters for settlement or primary author, but it is not needed.

For the name, this is different, there we could use some name scheme, but it must not be unique. I would prefer a faux title in quotes, like "Determining the Potassium isotope ratio in Noachian layers".

**Comment by bevans2000** [comment]
The technical I'd makes sense. The ScientificStudy could look to implement the Entity interface which has a name and integer identifier. 
But I want to limit how many studies are created per Settlement because it can get a bit too many.

**Comment by mokun** [comment]
btw, what's the definition of a technical id ?

> But I want to limit how many studies are created per Settlement because it can get a bit too many.

Yes. We can increase the # of collaborator on a study but need to reduce # of projects. 

e.g. we shouldn't have only one person doing many studies one after another, unless it's a 4-person settlement and he can't find anyone else.

> look to implement the Entity interface which has a name and integer identifier.

how ?

**Comment by mokun** [comment]
> we could use some name scheme, but it must not be unique. I would prefer a faux title in quotes, like "Determining the Potassium isotope ratio in Noachian layers".

If we want to give each study beyond just assigning a topical name, it would be hard.

We will have to hand craft each research statement that make sense on each subject. Not just if we logically piece together key words with high permutation... 

Anyway, what tools would you use to parse a verb and noun together to form a research question or a imperative statement such as  "Determining the Potassium isotope ratio in Noachian layers" ?

Any idea on how to do it ?

**Comment by Urwumpe** [comment]
Option 1: Just parrotting, tables with keywords and key verbs, and a random number generator.

Option 2: A graph made of scientific dictionary entries with some tags to decide, which role the words can play (e.g. quantity, quality, action, etc.) and links to other words or tags. Two random entries are picked: one out of the scientific field in question, another out of any field, maybe with a higher chance to also be out of the scientific field as the first word. Then, a path is searched in the graph connecting the two words. This path of dictionary entries is then ordered in a correct word order for a title.

Option 1 would be really simple, but highly repetitive with a small data tables. 
Option 2 could make better titles out of less input data, but requires much more work in implementation and defining the input data.

**Comment by mokun** [comment]
In terms of just changing the mission and science identifier string, I'll add the mission sol onto the string itself. 

At the beginning of a sol, the int identifier will go back to 1.

The mission identifier will consist the following 3 parts : 
1. The misson sol
2. The settlement code (each settlement will be given a 2-letter settlement code)
3. The initials of a mission type

**Comment by bevans2000** [comment]
We can apply the same logic to Science Studies as well

**Comment by mokun** [comment]
Done for now.

**Comment by mokun** [comment]
@bevans2000 

I'm going to make the identifier in Mission unique again so that it is consistent with how it was used elsewhere.

And I'll rename the clunky 'TypeID' to simply 'Mission String'.

The mission designation will incorporate the unique mission identifier at the end.
