### ISSUE TITLE
Let player decide how many missions are allowed; Excessive # of missions

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1021]
Q: What should be the most optimal number of people that a settlement may send out for mission ? 

- The Heritage settlement below shows that only 5 out of 36 settlers are inside the settlement. Is it too excessive to have 31 settlers on missions ?
![image](https://github.com/mars-sim/mars-sim/assets/1168584/ffb4d5f5-6543-4ccf-b844-6ff1fa70e95d)

Currently, the ability to decide how many mission types are allowed is very much mission dependent. The probability calculation is NOT unified, lacking inputs from player.

Recommendations: 
1. Let players set an upper limit of # of missions for each type of mission in each settlement in Dashboard.
2. Post the ratio between the # of indoor personnel and # of outdoor personnel and make it more consistent and transparent on how each mission uses this ratio

**Comment by bevans2000** [comment]
We can do this as part of #963. It's the same purpose.

**Comment by bevans2000** [comment]
@mokun There is already a configurable upper limit on the number of missions plus a weighting for each Mission Type. So I think it covers the above. 
I think what is needed is a ration of People OnMission/Not on Mission per Settlement?
