### ISSUE TITLE
Did not see person/robot move seamlessly from place to place

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1025]
**Describe the bug**
- Currently, person/robot appears to jump from one spot to the next within or outside settlement 

**Expected and unexpected behavior**
- The time pulse available for each frame may not have used correctly when calculating the walking distance and walking speed 

**Discuss any potential problems you have and have not ruled out**
- May assume the normal walking speed of a person as ~5 kph. 
- May assume a robot to have ~2 kph

**Java classes involved**
- All Walk-related class 

**Specifications (please complete the following information)**
- post 3.6.1 build 8612

**Additional context**
- Need to re-evaluate the role `standardPulseTime` and `MIN_PULSE_TIME` are supposed to play in available time in each frame

**Comment by mokun** [comment]
@bevans2000 

A while back, if I slow down the time ratio to 4x or 2x, I used to see a person slowly moving from place to place inside a settlement or outside on the surface of Mars.

Now, it's just `jumping` from one activity spot to another.

**Comment by bevans2000** [comment]
I found this problem as part of #1164

**Comment by mokun** [comment]
One problem in the past was that if a person walks from one building to another, he would slowly move across beds, across partitions and people and robots until he stops. This is actually bad.

To be more realistic, we will need to set up collision boundary for even beds, walls, tables, machines, furniture, person/robot, etc.

So, jumping from one activity spot to the next may actually be the preferred way since it does expose the obvious illogical movement of units inside the settlement. 

Outside the settlement, we do ensure vehicles not colliding with the other vehicles and buildings.

It's just that we need implement realistic collision inside the settlement.

Any comments on this ?

**Comment by bevans2000** [comment]
I feel implementing collisions inside a settlement is possible but a lot of work for little benefit. If you want them to appear immediately at the destination then we can remove all the internal walking logic.
I think taking the direct path across furniture is fine for now

**Comment by mokun** [comment]
Do we want furniture will serve greater purpose in near future ?

We could make use of some game engines out there for implementing each as a 'game object'. 

Also rendering each person/bot as a simple funny cartoonish object is more preferable than a dot. We'll need to face face, side face and back face when he turns around and walk.

**Comment by mokun** [comment]
Even after the commit, I don't see them moving. They are still jumping from one activity spot to another. Isn't it ?

**Comment by bevans2000** [comment]
I have sen person moving but I agree it's not often
