### ISSUE TITLE
possible to make own teams ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#103]
It would be nice if the commander could make their own team mates names at the very least. I imagine most people would love to put names to the avatars/characters which they are more familiar with perhaps.

**Comment by mokun** [comment]
Yes. I'll implement the concept of Alpha Team into the console mode. 

We can certain improve upon that and go belong.

**Comment by bevans2000** [comment]
Site Editor supports creating and sharing Crews
