### ISSUE TITLE
Use Ratings for base Task management

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1048]
Convert the TaskCache to use Ratings along with the TaskJob. This lays the foundation to later refine the MetaTask scoring to break it down into its components.

This will not actually breakdown the task scores bit change the framework so the MetaTasks can be converted at a slower pace.

**Comment by mokun** [comment]
> MetaTasks can be converted at a slower pace.

Do you mean faster ?

But how ?

**Comment by bevans2000** [comment]
We Don't want to break everything at the same time so will convert a few at a time. Need a steady conversion and not create commits that have a massive impact

**Comment by bevans2000** [comment]
@mokun I've had a bit of a lightbulb moment with the approach having a common Rating framework that can be applied to lots of areas. The current design I did for scoring MissionMeta isn't universal enough to cover all the potential cases. It was looking tricky to apply it to ```TaskJob```
I'm going to drop the concept of the ```Rateable``` and combine it with the ```Rating```. This makes sense because the 2 are always used together.
Secondly we use a Map quite a lot to hold the various scored items but we can use a List instead if we expand the score to include it's name.

**Comment by mokun** [comment]
As a sidenote, what if we do away with the recursive nature of returning time in performing Task and Mission ?

It's been difficult and costly to debug.

**Comment by bevans2000** [comment]
> As a sidenote, what if we do away with the recursive nature of returning time in performing Task and Mission ?
> 
> It's been difficult and costly to debug.

Let's do one thing at a time and not change this yet. It would be a total rewrite of the Task framework and I don't have the energy for the disruption.
