### ISSUE TITLE
Most missions are unable to proceed

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1052]
**Describe the bug**
- In 3.6.X branch, no vehicle can travel to a site. 95% of the time, it will report that a mission is en route to a site. 

**Expected and unexpected behavior**
- 3.6.1 did not have this issue. 
- The rover is able to finish the loading of cargoes. All mission members are onboard. It was about to depart the settlement when it got *stuck* somehow.
- The rover was shown still being in the settlement map. The stats show zero travelled distance and zero speed.

**Discuss any potential problems you have and have not ruled out**
- It doesn't seem to have anything to do with the pending task changes and walking related issues.

**Java classes involved**
- AbstractMission, AbstractVehicleMission, RoverMission.

**Specifications (please complete the following information)**
- 3.6.x and Master branch 

**Screenshot**

![image](https://github.com/mars-sim/mars-sim/assets/1168584/05a4e152-61b4-4758-9362-8a9d69509f34)

**Comment by mokun** [comment]
@bevans2000 

This would be the last bug I want to fix for 3.6.2. 

Unless we encounter other critical bugs, we will move onto 3.7.0. 

Can you take a look at why mission cannot proceed beyond 'en route to...' ?

**Comment by bevans2000** [comment]
Sure. I have nearly wrapped up #1048

**Comment by mokun** [comment]
@bevans2000 

#1057 is done. It was kind of related to this issue but fixing that  still won't automatically correct this issue. 

I'm down into trenches right now. It looks like either's Vehicle's setContainerUnit or setCoordinates may not have worked correctly.  See below : 

```
	/**
	 * Sets the unit's container unit.
	 *
	 * @param newContainer the unit to contain this unit.
	 */
	public boolean setContainerUnit(Unit newContainer) {
		if (newContainer != null) {
			if (newContainer.equals(getContainerUnit())) {
				return false;
			}
			// 1. Set Coordinates
			if (newContainer.getUnitType() == UnitType.MARS) {
				// Since it's on the surface of Mars,
				// First set its initial location to its old parent's location as it's leaving its parent.
				// Later it may move around and updates its coordinates by itself
				setCoordinates(getContainerUnit().getCoordinates());
			}
			else {
				setCoordinates(newContainer.getCoordinates());
			}
			// 2. Set new LocationStateType
			updateVehicleState(newContainer);
			// 3. Set containerID
			setContainerID(newContainer.getIdentifier());
			// 4. Fire the container unit event
			fireUnitUpdate(UnitEventType.CONTAINER_UNIT_EVENT, newContainer);
		}
		return true;
	}
```

**Comment by bevans2000** [comment]
Its weekend so I've found some time to look into this one.

**Comment by mokun** [comment]
That's great. 

In other threads, we have discussed that a unit's lat lon coordinates should simply be defined by its container' unit's coordinates. 

So it's NULL unless its container unit is MarsSurface. 

In that case, it can be anywhere on the surface of Mars and thus needs the lat lon coordinate that can't be derived from its container.

**Comment by bevans2000** [comment]
So the problem is still #1039. All the Crew members are stuck in an infinite Walk inside Vehicle task that never ends; same as #1039 that I found. I don't think you actually fixed the walk problem.
So what happens is the Crew never complete the current Task and never gets to execute the Mission phase and hence never get to start operating the vehicle. You can see my console output where after a long time this crew member is still stuck walking inside. The walk inside a rover need fixing; it wasn't there in 3.6.1 so must be a recent change.
I think it has nothing to do with the container.

![Screenshot 2023-09-16 205853](https://github.com/mars-sim/mars-sim/assets/20720166/c9a2880a-0fce-40e8-92a6-e5303351d53d)

**Comment by mokun** [comment]
> All the Crew members are stuck in an infinite Walk inside Vehicle task that never ends

We can check further to see how having a subtask of walking inside a vehicle would affect driving a vehicle

As a matter of fact, I can see in each mission currently, a pilot has been selected and it almost seems like he was given the task of driving a vehicle. 

So, even though he has this task, may be he wasn't operating the vehicle at all. 

Could that be the root cause of this issue ?

**Comment by mokun** [comment]
Yes. Great that you pointed out.  It seems the culprit in in the walkingPhase() in WalkRoverInterior. 
Committing the fix now.

**Comment by bevans2000** [comment]
> Yes. Great that you pointed out. It seems the culprit in in the walkingPhase() in WalkRoverInterior. Committing the fix now.

The driver is also stuck walking inside as a sub task. But sounds like you have found the problem
