### ISSUE TITLE
Fail to relocate crew members of a rover

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1057]
**Describe the bug**
-Relocating a rover from garage to outside but without bringing crew members with it

**Expected and unexpected behavior**
- When taking a rover in and out of a garage, needs to ensure crew members within (one having container unit as this rover) be relocated as well

**Java classes involved**
- Rover, RoverMission

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/04a0b6a8-5301-4e72-a103-2ccba45068a3)

![image](https://github.com/mars-sim/mars-sim/assets/1168584/540902cc-48d0-461e-8954-9b54b6a55c00)

**Stacktrace**
```
01-Adir-02:432.555 (Info) AbstractVehicleMission : [Starcity] Vega - Prepared a loading plan sourced from Starcity.
01-Adir-02:432.555 (Info) BuildingManager : [Starcity] Vega - Just stowed inside Garage 1.
01-Adir-02:432.555 (Info) AbstractMission : [Starcity] Ariane Tremblay - Assigned with 'Loading Vehicle in Garage' to replace 'Tending crops'.
01-Adir-02:434.634 (Info) AbstractMission : [Starcity] Jordan Landry - Assigned with 'Loading Vehicle in Garage' to replace 'Analyzing Map Data'.
01-Adir-02:437.697 (Warning) LoadingController : [Starcity] Vega - Ariane Tremblay item Steel Wire, 1 not loaded 
01-Adir-02:438.455 (Info) AbstractMission : [Starcity] Jesse Wright - Assigned with 'Loading Vehicle in Garage' to replace 'Relaxing'.
01-Adir-02:438.654 (Info) Walk : [Starcity - Vega] Ariane Tremblay - Entered rover Vega inside Garage 1.
01-Adir-02:439.029 (Info) Walk : [Starcity - Vega] Jesse Wright - Entered rover Vega inside Garage 1.
01-Adir-02:439.952 (Info) Walk : [Starcity - Vega] Jordan Landry - Entered rover Vega inside Garage 1.
...
01-Adir-02:444.444 (Info) Walk : [Starcity - Vega] Louis Gomez - Entered rover Vega inside Garage 1.
...
01-Adir-02:444.629 (Info) EVASuitUtil : [Starcity - Vega] Ariane Tremblay - Just fetched EVA Suit 146 from Starcity to Vega.
01-Adir-02:444.629 (Info) EVASuitUtil : [Starcity - Vega] Louis Gomez - Just fetched EVA Suit 134 from Starcity to Vega.
01-Adir-02:444.629 (Info) EVASuitUtil : [Starcity - Vega] Jordan Landry - Just fetched EVA Suit 149 from Starcity to Vega.
01-Adir-02:444.629 (Info) EVASuitUtil : [Starcity - Vega] Jesse Wright - Just fetched EVA Suit 150 from Starcity to Vega.
01-Adir-02:444.629 (Info) RoverMission : [Starcity] Vega - Just embarked from the settlement.
...
01-Adir-02:499.500 (Warning) ExploreSite : [40.0200 N 156.6500 W - Vega] Jordan Landry - No more specimen box for collecting rock samples.
01-Adir-02:499.500 (Info) AbstractMission [x2] : [40.0200 N 156.6500 W - Vega] Jordan Landry - Assigned with 'Exploring Site' to replace 'Analyzing Map Data'.
```

**Specifications (please complete the following information)**
- pre 3.6.2 build 8686

**Additional context**
- Could this be related to the existing issue of #1052 ?

**Comment by mokun** [comment]
@bevans2000 

Have you seen this ?

**Comment by bevans2000** [comment]
No I haven't but my guess I it is because we use the bad LocationState which is cached instead of using the parent containers situation. So when the Vehicle is moved the state of the crew is not updated.
We need to drop the state class and rely on the parent's situation. I'm sure there is an old existing issue describing a similar problem

**Comment by mokun** [comment]
> my guess I it is because we use the bad LocationState which is cached instead of using the parent containers situation. So when the Vehicle is moved the state of the crew is not updated.

Can we simply fix how the change of one's container unit (from settlement to vehicle) should properly trigger the change of its state enum ? 

State enum matching should be much faster than matching the object type. 

But we can add some test cases to prove if it's indeed faster and how much faster.

When they are sync-ed up, then we won't have the problem.

**Comment by bevans2000** [comment]
There will be little difference in performance. Anyway there is a lot of poorly performing code elsewhere so performance alone is not enough.
The complexity of having to cascade changes needs to be considered as well.
However it's a big change so let's not rush into it, there are a lot of open issues at the moment. Let's try to close some of them down
