### ISSUE TITLE
Limit messages on a specific settlement, game mode, RPG, personality, skill, Commander Mode

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#106]
When you are connected to a settlement, on the console you get lot of messages of other settlements as well as messages from the settlement you are connected to - 

That creates lots of unnecessary noise and doesn't do anything for the player or/and the commander. 

The only messages that should come from other settlements should be priority messages which means - 

a.  A distress signal,  some sort of disaster that a settlement has got and the commander has to make a choice between sending her/is people or not. 

b. A surplus of items produced and the other settlement wants to trade which we may or may not be interested in. 

c. Weather forecasts but this probably would be done by the hovering Space Station, maybe Mars Space Station 1 or probably some other interesting name ;)

d. Some anomaly or something interesting scientific in nature which needs studying and the other settlements consider it interesting enough to share. 

e. Messages to and from loved ones but these would be encrypted packages (video/audio streams) which just need to signed off by the commander when receiving and sending such recordings.  

f. Rotation duties to other settlements or the Orbiting Space Station if needed. Maybe the bigger settlement could be thought of as a de-stresser or shore-leave https://en.wikipedia.org/wiki/Shore_leave

One way of doing that could be using xterm-color or something similar 

https://unix.stackexchange.com/questions/148/colorizing-your-terminal-and-shell-environment

just have red for warnings, blue and green for something else.

**Comment by mokun** [comment]
> When you are connected to a settlement, on the console you get lot of messages of other settlements as well as messages from the settlement you are connected to -
> 
> That creates lots of unnecessary noise and doesn't do anything for the player or/and the commander.

So does it mean we should create a "settlement mode"-- each player owns one settlement as the commander of it and can only directs the course of this settlement, right ?

What we have so far is the "God-mode"-- it means you can oversee the progress made in several settlements and how they trade with one another.

**Comment by shirishag75** [comment]
That brings up another question, is it supposed to be a single-player game or multi-player. And if it's multiplayer I haven't seen a way, at least in console which even hints that it is multi-player. 

That being aside, for a new player, having a 'God mode' is a liability rather than an advantage. The God mode is good ONLY if you are going to be the commander of all the settlements and not just one. 

And as we see, the first time s/he is going to be the commander of Schiaparelli Point which means  s/he is not a commander of the other bases. 
`
2018-10-20T11:43:54.3 (Info) UnitManager : shirish agarwal will be assigned to Schiaparelli Point as its commander.`

**Comment by mokun** [comment]
> role-playing characteristics such as leveling up character/characters it might make for better gameplay. 

We can certainly make changes to add more role-playing elements. Currently, it's more of a colony building game, you know.

> For instance, let's say the commander has a glib tongue, dashing personality etc. and is good at persuasion than s/he might be able to invoke dialogues or missions that would otherwise be not available.

Yes. There is ~17 skill types. So you can be a technician and have a level 2 mechanical skill. But he's an engineer and already has a level 4 mechanical skill.

A higher skill level will definitely be a plus and get the job done faster and better and less prone to errors/accidents, etc.

Also, certain manufacturing tasks requires a level 4 skill.

Can you look up how personality traits and personality types are currently being defined and being used ? 

We have discussions in the past in creating emotion and mood for each individual. 

In order to model the social aspect of the everyday life in the settlement, the concept of emotion/mood is crucial.

**Comment by mokun** [comment]
I just put together two additional wiki pages [Personality](https://github.com/mars-sim/mars-sim/wiki/Personality) and [Skills](https://github.com/mars-sim/mars-sim/wiki/Skills)

**Comment by shirishag75** [comment]
Reply in-line :

> > role-playing characteristics such as leveling up character/characters it might make for better gameplay.
> 
> We can certainly make changes to add more role-playing elements. Currently, it's more of a colony building game, you know.
> 

I know . The problem with colony building sims is it gets mechanical after a while. If you have a team of 10 odd people whom you can constantly lvl up , once the colony is somewhat sustainable you can go on adventuring to find more loot or goodies or/and study anamolies or what not. The idea behind it is the ability to have a lot more replayable value. We anyways have the whole of Mars to explore. 

We could restrict ourselves by technology that we have, so how far our settlements can be or growth is defined. It could be enhancements to the EVA suits to the rovers with the shielding, the carrying capacity, how far they can go , how we can camp in the wilderness, rations etc. 

Unlike traditional rpg's we would always be limited because we can't hunt and only have rations from settlements which have space farming where we could barter our finds. The same could be true for improvements to our vehicles or tools if that is possibility. 

Another possibility of adventuring is of finding places which could be thought of as future settlement candidates which can be shared info with the existing settlements as well as the hovering space station above . 

Riskier places where life and death is a real possibility could have more loot that could be used to enrich the colony. 

Just a colony building sim would have its own share of followers while the same is true of those who play rpg's , hybrids such as how I am sharing could be the best of the both but would require much more thinking. 

> > For instance, let's say the commander has a glib tongue, dashing personality etc. and is good at persuasion than s/he might be able to invoke dialogues or missions that would otherwise be not available.
> 
> Yes. There is ~17 skill types. So you can be a technician and have a level 2 mechanical skill. But he's an engineer and already has a level 4 mechanical skill.
> 
> A higher skill level will definitely be a plus and get the job done faster and better and less prone to errors/accidents, etc.
> 
> Also, certain manufacturing tasks requires a level 4 skill.
> 
> Can you look up how personality traits and personality types are currently being defined and being used ?
> 
> We have discussions in the past in creating emotion and mood for each individual.
> 
> In order to model the social aspect of the everyday life in the settlement, the concept of emotion/mood is crucial.

that is true.

**Comment by shirishag75** [comment]
> I just put together two additional wiki pages : [Personality](https://github.com/mars-sim/mars-sim/wiki/Personality) and [Skills](https://github.com/mars-sim/mars-sim/wiki/Skills)

I especially liked the jungian model as in a way its simplistic and probably easier to model with.

**Comment by mokun** [comment]
In general, `Commander Mode` will have more role-playing styles while Sandbox Mode`  will be remained as the classic mars-sim in which resources are unlimited.

In future, we will specifically discuss how the `Commander Mode` is supposed to be different from `Sandbox Mode` in terms of the playing style and how to make it more challenging.

**Comment by shirishag75** [comment]
cool.

**Comment by mokun** [comment]
Let's discuss more specific ideas how we might implement them on a new thread. Closing this now.
