### ISSUE TITLE
Convert SettlementTasks to Rating implementation

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1060]
The ```SettlementTask``` classes shall be converted to use the new ```RatingScore``` when creating new ```SettlementTaskJob```. There are 2 aspects:

1. Convert the getPersonModifier & getRobotModifier so the individual modifiers are captured in the overall RatingScore.
2. The SettlementMetaTask subclasses create the initial tasks using Rating Score with a full composite score.

**Comment by mokun** [comment]
Can RatingScore be applied to how a process is selected in Manufacturing, FoodProduction and Resource Processing somehow ?

**Comment by mokun** [comment]
May be also good for determining which meal or dessert can be made ?

**Comment by bevans2000** [comment]
I see no reason why not. Basically it can be used to change a single double score to a composite score which allows us to understand how the score has been calculated.
Add a new todo to the project
