### ISSUE TITLE
Record what have been manufactured

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1062]
**Is your feature request related to a problem? Please describe.**
- Currently, there is no way to look back and evaluate what have been manufactured in a building with manufacturing capability or in a settlement.

**Describe the rationale**
- Player needs a more interactive interface provides more insights into understanding what the settlement is manufacturing
- Player should be given the tool to (1) go back to the history of what have been made, (2) easily formulate a manufacturing plan for way-forward, (3) see a future projection of the resources, time, labor, based on that plan.

**Describe the solution you desire to see**
- Record the input resource and output resource in Lander Hab, Workshop, Manufacturing Hab, etc. 
- Create an interface and statistic tool such as pie chart to graphically present the labor time, process time and resources that have been spent in manufacturing

**Specifications  (please complete the following information):**
 - 3.6.2 build 8698

**Comment by mokun** [comment]
@bevans2000 

Do we by any chance already have the data class to record what's been manufactured so that a log, a report or a table may be generated for players to see if they want to ?

**Comment by bevans2000** [comment]
Yes, I think we can reuse the existing ```History``` class. There may also be a ready made panel containing a table.
