### ISSUE TITLE
Clean up message.properties

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1071]
**Describe the bug**
The message.properties file has been slowly growing as new entries are added but we never take any away. This large file will consume some memory resources and make look-up sub-optimal.
Secondly; if we ever create a different language set it will be wasteful creating translations for strings that are not used.

**Expected and unexpected behavior**
The file should just contain entries referenced from the code.
I suggest we do an audit of the keys against the code base and remove those that are not used any more.
In addition, it may be possible to consolidate some of the single word entries into a single keys.

Also, to help future management it should be order alphabetically.

**Comment by mokun** [comment]
Good idea ! 

> do an audit of the keys against the code base and remove those that are not used any more.

Yes, it's difficult to maintain one big monolithic file and it can easily get out of control. 

Do we want to create a separate lookup file for each maven submodule or a few categories of lookup file in order to break it down further ? 

> we ever create a different language set it will be wasteful creating translations for strings that are not used.

To further save the effort of translations into other languages, we only need to provide translation of the lookup values to be used by the mars-sim-ui submodule.

**Comment by bevans2000** [comment]
Well...... if we want to purists in localisation then only the user facing modules should be using the message bundle. We should; not have any reference to the bundle inside the core packages since the language bindings will get save inside and save simulations. It should be possible to switch the language bindings and restart.
However, the bigger problem is we have too many and there are places where we don't use the bundle at all. 
I think small steps, first lets clean-up what we have into a more manageable state.
Then a follow on Issue is to create fully translated 2nd language to test everything is as expected.

**Comment by mokun** [comment]
> We should; not have any reference to the bundle inside the core packages since the language bindings will get save inside and save simulations.

agree. 

How would you like to handle those Msg calls in each task class ?

**Comment by Urwumpe** [comment]
> How would you like to handle those Msg calls in each task class ?

We could use an Observable design pattern and produce events for a task, that a passed as an object. A TaskLogger service could then observe the Task in the UI and translate the events into human readable texts or UI elements.

**Comment by mokun** [comment]
We have a few more: 

```
01-Adir-02:390.629 (Warning) Msg : !!RatingScore.skill??
01-Adir-02:390.629 (Warning) Msg : !!RatingScore.skill??
01-Adir-02:390.629 (Warning) Msg : !!RatingScore.skill??
01-Adir-02:390.629 (Warning) Msg : !!RatingScore.skill??
01-Adir-02:390.629 (Warning) Msg : !!RatingScore.skill??
01-Adir-02:391.098 (Warning) Msg : !!RatingScore.skill??
...
01-Adir-02:732.212 (Warning) Msg : !!Task.description.produceFood.checking??
01-Adir-02:732.212 (Warning) Msg : !!Task.description.produceFood.checking??
01-Adir-02:732.212 (Warning) Msg : !!Task.description.produceFood.checking??

```

It's also possible other RatingScore.x are missing.

**Comment by mokun** [comment]
Also, 
```
01-Adir-04:129.787 (Warning) Msg : !!HealthProblemState.DEGRADING??
01-Adir-04:129.787 (Warning) Msg : !!HealthProblemState.BEING_TREATED??
01-Adir-04:129.787 (Warning) Msg : !!HealthProblemState.RECOVERING??
01-Adir-04:129.787 (Warning) Msg : !!HealthProblemState.CURED??
01-Adir-04:129.787 (Warning) Msg : !!HealthProblemState.DEAD??

```

**Comment by mokun** [comment]
The one below is still there. Just so you know. 

```
01-Adir-07:017.020 (Severe) Msg : !! Task.description.produceFood.checking ??
01-Adir-07:017.020 (Severe) Msg : !! Task.description.produceFood.checking ??
```
