### ISSUE TITLE
Simplify Release Process

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1072]
### Discussed in https://github.com/mars-sim/mars-sim/discussions/1069

<div type='discussions-op-text'>

<sup>Originally posted by **bevans2000** September 19, 2023</sup>
The release process is quite labour intensive. We should simplify it to make it easier to run and understand for an end user. It involves creating 4 separate files as Artefacts and various change log files. I suggest we drop the DEB file and go to a single ZIP artefact that contains both JAR files and support both OS.

- _jars/mars-sim-headless-3.6.2.jar_
- _jars/mars-sim-swing-3.6.2,jar_
- bin/mars-sim-ui.bat
- bin/mars-sim-ui.sh
- bin/mars-sim-headless.bat
- bin/mars-sim-headless.sh
- readme.txt
- _changelog.txt_
- conf/jvm.options

Only the italic files would normal change for a release.

This is common pattern in lots of Java based application, Apache JMeter is a good example. This will simplify the wiki pages as well since we can describe a single execution & installation model. 
To create this we have a new Maven module that will just do the packaging.
</div>

**Comment by mokun** [comment]
@shirishag75 

We'll probably drop compiling the debian version of mars-sim. Just so you know. Any feedback for us ?

**Comment by mokun** [comment]
> simplify the wiki pages as well since we can describe a single execution & installation model. 

Do you mean generating a Release Process wiki page ?

**Comment by bevans2000** [comment]
> > simplify the wiki pages as well since we can describe a single execution & installation model.
> 
> Do you mean generating a Release Process wiki page ?

I mean the Wiki page on how to run the application.

**Comment by bevans2000** [comment]
Also I think we should combine the base, core & mapdata modules into a single core module. Having them separate causes more problems than it solves. It would make the build quicker as well.

**Comment by bevans2000** [comment]
As part of this change I want to combine the Maven modules and use a profile for Java FX

- core - Combined mapdata, core & base. There is no point keeping these separate
- ui - Existing UI
- console
- main - uses core, ui, console to create an executable
- headless - uses core, console to create an executable
- tools - Stays separate
- installation - Module that does the packaging
- libgdx & javafx - keep these but there are only built with the new javafx profile in maven, e.g. not part of the main build

**Comment by mokun** [comment]
> use a profile for Java FX

What does "For Java FX" means ?

**Comment by bevans2000** [comment]
Right this is what I'm going to do in terms of the modules. Goal is to simplify the number of modules we have and get the output ready to be directly copied into a release.

- core - Combined mapdata, cnre & base modules. There is no point keeping these separate as they are always used together
- console - Existing module unchanged
- swing - Combines main & ui modules.  Dependents upon core, console to create an executable. Drop the DEB support
- headless - Depends on core, console to create an executable. Drop the DEB support
- tools - Stays separate, unchanged
- dist- Module that does the packaging and creates a single ZIP. Has the static files that are added to all distributions
- libgdx & javafx - keep these but there are not in the default build

Maven property will have a new Profile 'javafx' that includes all the above modules including the 2 javafx modules

**Comment by mokun** [comment]
Guess changing the maven package name is going to remove all the previous revision history again.

**Comment by bevans2000** [comment]
I see no reason why that would happen. Initially I'm not changing the package names. But when I do it will be via a git mv command not using an IDE refactoring command. This will keep the files with their history.

**Comment by bevans2000** [comment]
I'm going to automate creating the GitHub Release when the code is tagged using a new GitFlow that is trigger on the creation of a tag

**Comment by mokun** [comment]
> using a new GitFlow that is trigger on the creation of a tag

Sure. Does it mean no more manually making compiled jars ?

**Comment by bevans2000** [comment]
Yes. The artifacts will be created as part of a gitflow and automatically created. The created Release will be draft so we just gave to mark it as available and potentially update the notes. I need to build the distribution as part of maven first so it is all automated.

**Comment by bevans2000** [comment]
@mokun I have managed to create a new Action so a Release is compiled, assembled and created when a tag is assigned.
Here is an example https://github.com/mars-sim/mars-sim/releases/tag/untagged-f98a227dbfab26b9e2e3
So in the release process we would create a tag and then push it and everything else is automatic. The Release is Draft so then we just need to check it and add some extra description and make it Final.
We can automatically add the changes for this release if they are in a file in the repo. The CHANGELOG.md is the complete log not just the recent release. I think we should change it so CHANGELOG.md is just those that have changed in this release.

**Comment by bevans2000** [comment]
@mokun So I've found the problem and its the opposite. The main Maven Action was the work not work correctly because it is using a cache which means it is find the parent POM. But the SonarQube does not use a cache and hence it was showing the true problem. Totally given the wrong output.
I have taken the dist module out temporarily because the issue is with it being a POM packaging and not finding the parent.
The approach is still sound but I'll have to research why this is not working for us because I've seen it work elsewhere.

**Comment by bevans2000** [comment]
It's fixed. It was simple. The version of the root POM had changed to 3.7.1 but the new dist module was still on 3.7.0.

Annoying because I spent over an hour trying to get this working on the branch this afternoon. But seems OK now.

**Comment by mokun** [comment]
Great !

I'll finish up the <building-package> work soon on settlement templates.

Currently, it didn't quite make sense to leave all the ERVs far away since they are responsible for a lot of resource processing and the chemical they produce are for manufacturing. 

So I'm relocating them near (0, 0).

Since ERV and all the Habs are supposed to have a central ladder to go and down, ERVs should be the same.

In future, we'll make ERV habitable. Settlers won't have to do EVA to get there but come through hallway and tunnel to reach each ERV for doing inspections, making adjustment, and fixing any mechanical issues resulted from all those intensive resource processes.

**Comment by bevans2000** [comment]
I'm going.to working through the 3.8 issues.

**Comment by mokun** [comment]
> I'm going.to working through the 3.8 issues.

Which one ?

**Comment by bevans2000** [comment]
Not sure but #611 or #1189 or #1118. The later has implications for #773 though
