### ISSUE TITLE
Settlers create many Vehicle Rescue Missions at once

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#108]
There is a strange loop occuring when attempting to rescue an already towed vessel. 

> 2018-10-28T08:49:22.1 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.1 (Info) [x4] Mission : [Alpha Base] Allison Nowakowski ended the Vehicle Rescue Mission mission. Reason : No reservable vehicles
> 2018-10-28T08:49:22.1 (Info) [x4] Mission : [Alpha Base] Disbanding mission member(s) : [Allison Nowakowski]
> 2018-10-28T08:49:22.2 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.2 (Severe) EnterAirlock : Dorothy Piatek doesn't have an EVA suit to put away.
> 2018-10-28T08:49:22.2 (Severe) EnterAirlock : Nathan Ellis doesn't have an EVA suit to put away.
> 2018-10-28T08:49:22.4 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.5 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.6 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.7 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.7 (Severe) EnterAirlock : Lashawn Conrow doesn't have an EVA suit to put away.
> 2018-10-28T08:49:22.8 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:22.9 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.0 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.1 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.2 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.3 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.4 (Severe) [x296] PhysicalCondition : [Dune Runner] Dushan Novakovich has insufficient oxygen.
> 2018-10-28T08:49:23.4 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.5 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.6 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.7 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.8 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:23.9 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.1 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.1 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.3 (Info) ExitAirlock : [Dune Runner] Dushan Novakovich can't find a working EVA suit and is awaiting the response for rescue.
> 2018-10-28T08:49:24.3 (Severe) RoverMission :  Dushan Novakovich requested to be rescued from Dune Runner to Garage 1.
> 2018-10-28T08:49:24.3 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.4 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.6 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.7 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.8 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 2018-10-28T08:49:24.9 (Info) Mission : [Alpha Base] Allison Nowakowski is organizing a Vehicle Rescue Mission mission.
> 

The target vessel seems to be Nomad in that case, it was towed back after an emergency, but is left behind towed right outside the base.  A single Settler is left behind inside it, who can't leave the vehicle because of a missing EVA suit. 

 Those loops appear with different settlers and different rovers, some missions seem to end early because no food is loaded. (Maybe because distance to the stranded rover is 0). 

There is no information in the log why the mission was quickly disbanded, there is only one mission appearing very briefly in the Mission tool.

For debugging the problem, it would already be helpful to always have a reason in the log why a mission is removed from the mission tool.

**Comment by mokun** [comment]
@Urwumpe , thanks for posting this.

If it said "organizing a Vehicle Rescue Mission", then this Mission is at the `APPROVAL` phase.

After the mission plan has been granted approval, that Mission will proceed to `EMBARKING' phase.

It did say ONCE on why : 

> 2018-10-28T08:49:22.1 (Info) [x4] Mission : [Alpha Base] Allison Nowakowski ended the Vehicle Rescue Mission mission. Reason : No reservable vehicles

Related class files are : `RescueSalvageVehicle`, `Mission`, `RoverMission`, `VehicleMission`, etc. They are all inside https://github.com/mars-sim/mars-sim/tree/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/mission

I'll look over the codes in detail later this evening.

Do let me know anything you discover as well.

**Comment by mokun** [comment]
That log statement is from `Mission` Line 198-199. 

So it's actually during the preparatory (unnamed) phase in which a `Staring member` is elected and he will go find out if people, vehicle, and resources are readily available for the Mission.

So it's RIGHT BEFORE the approval phase.

**Comment by mokun** [comment]
This situation should be prevented from happening again in recent build. Closed
