### ISSUE TITLE
Convert Person assignment MetaTasks to Ratings

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1084]
Convert the individual ```MetaTask``` implementations for Persons to use ```RatingScore``` instead of a simple double.
This will involve using the new common assessPersonSuitability method

**Comment by mokun** [comment]
So does it mean that meta missions will also be converted ?

**Comment by bevans2000** [comment]
Meta Missions have already been converted.

**Comment by mokun** [comment]
So how do I now convert a regular meta task to the new rating score system ?

**Comment by bevans2000** [comment]
> So how do I now convert a regular meta task to the new rating score system ?

I have a set of changes on a branch which laid down a blueprints of how the new FactoryMetaTask  can be done. I will be creating a pull request soon.

**Comment by mokun** [comment]
So, initially how many meta tasks will have rating score shown ?

**Comment by bevans2000** [comment]
> So, initially how many meta tasks will have rating score shown ?

I think about half at the moment. But the ay I have done this change is ALL MetaTask will create a RatingScore; it's just some will not have a decomposed ratings, just a single base.

**Comment by bevans2000** [comment]
> > So how do I now convert a regular meta task to the new rating score system ?
> 
> I have a set of changes on a branch which laid down a blueprints of how the new FactoryMetaTask can be done. I will be creating a pull request soon.

I was going to convert more but I will work on completing the branch as a blueprint. I've noticed that some of the MetaTask implementations do not seem very scientific when creating a score. As part of this issue we can revisit them.

**Comment by mokun** [comment]
> I've noticed that some of the MetaTask implementations do not seem very scientific when creating a score

not scientific ? Which one ?

**Comment by bevans2000** [comment]
To convert ```MetaTask``` to the Rating Score blueprint the follow changes should be done:

1. Change the signature of the ```getProbability``` method to the ```getTaskJobs``` method. 
2. If no task is suitable return ```EMPTYTASK_LIST```
3. Replace any of the get modifiers with more suitable 'assess*' methods. These methods build up the composition Rating Score.
4. The final return can provide a list of TaskJobs if that is suitable or use the ```createTaskJobs``` method which takes a RatingScore and converts it into a list of  single TaskJob.

**Comment by bevans2000** [comment]
@mokun I've decide to raise the Pull Request now; I was going to do some more testing but I think it might be better to give the changes some different usage.

**Comment by bevans2000** [comment]
@mokun  do you want to convert any of the MetaTasks? I am going to do the local digging Tasks next.

**Comment by mokun** [comment]
> do you want to convert any of the MetaTasks? 

Not yet.

But I'm planning to add a few new meta tasks. Will try to use the new format that supporting rating score.

**Comment by bevans2000** [comment]
That sounds good. The SettlementMetaTasks also support the Rating score approach.

**Comment by bevans2000** [comment]
I have been working to convert some of the MetaTasks to SettlementMetaTasks. Also trying to get the Astronomical Tasks working as they never fire currently. I've improved how these are scored and selected, just need to run some more tests.

**Comment by mokun** [comment]
>  Astronomical Tasks working as they never fire currently. 

Good observation. 

Looking at the night sky can be a great group activity. Any thoughts on how to make it happen ?

**Comment by bevans2000** [comment]
It should work now. But more likely if the observatory is connected directly to the main base due reduce the wasted time for the EVA.

**Comment by mokun** [comment]
> But more likely if the observatory is connected directly to the main base due reduce the wasted time for the EVA.

In long run, it makes sense to dig a tunnel to connect the main zone of the base to the observatory via an underground tunnel

So what if we allow the creation of *Tunnel Digging* mission ! ?

We already have tunnel for sure. However, it works no different from hallway since we haven't got to the point of modeling anything underground any different from being on the surface...

In real world, it would be interesting to see Elon Musk's Boring company create boring machines and ship them to Mars.

**Comment by bevans2000** [comment]
In the short term, why not just create a tunnel ? The problem is that it takes time to do the EVA and reach the observatory. Being able to walk there would increase the time for star gazing

**Comment by bevans2000** [comment]
This activity feels like one of those things you never wanted to start..... I'm nearly finished

**Comment by mokun** [comment]
> In the short term, why not just create a tunnel ? 

The tunnel from the nearest building to the Observatory would involves a few twist and turn. We're not able to define it in the settlement xml.

Having said that, we've been using resupply mission to send a hallway or tunnel to automatically construct a connection between two buildings. But the code is cranky and doesn't work all the time and may come up with weird connection layout.

Still need refinement to work 100% each time if the two buildings have different xloc and yloc.

Do you wanna try tweaking it ?

**Comment by mokun** [comment]
> This activity feels like one of those things you never wanted to start

which activity ?

**Comment by bevans2000** [comment]
> > This activity feels like one of those things you never wanted to start
> 
> which activity ?

The refreshing and conversion to RatingScore approach. I know it is much better and gives good visibility on why Tasks are choosen but it's proved to be a lot of work.
