### ISSUE TITLE
Settlers without mission are stuck inside rover, mission template, zero amount of food

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#109]
**Describe the bug/issue**
Settlers without mission stuck in a rover parked in front of the garage.

**Affected Area**
Likely core.person.ai, possibly how emergencies are handled. 

**Expected behaviors**
- Any mission should end with all settlers in a rover having successfully disembarked. 
- As catch-up solution should this fail: Settlers without a mission should have a task to leave a rover by EVA, if they are not assigned to a mission or loading/unloading it. Using this task should result in a warning in the log, so that the issue gets fixed in the mission.
- As goldplated solution:

- When declaring an emergency, the current mission should get replaced by a passive "ROVER EMERGENCY" mission, instead of just ending the current one. Activities of this state should include ensuring survival until rescue and properly ending the emergency state afterwards. With later communication extension, this mission could allow telling the settlement about the kind of emergency, available resources and extending rations until rendezvous. 
-  One member of the mission should have the role as Mission Commander, with the task to make sure all members have left the rover and rover has been unloaded before declaring a mission for done.  (Generally: Mission phase and state should be progressed by the mission commander, including declaring emergency)

**Actual/Observed Behaviors**
- All four settlers inside the rover have no Mission
- All four settlers are not able to leave it
- All four settlers are mostly idling in the Schedule tab
- All four settlers complain about lacking oxygen in the log

**Reproduction (optional)**
Unknown. Happened overnight, Schedule tab or log aren't providing any clues. 

**Screenshots**
DNA

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : Oracle JDK 11, OpenJFX 11
 - mars-sim build version : r4511 

**Additional context**
DNA

**Comment by mokun** [comment]
Hi @Urwumpe , thanks for filling out the issue template thoroughly.

Q1 : was it happening at the beginning of a mission before they depart OR at the very end when they just come back ?

I'll need to gain more insight on what is causing the O2 level to go low. I supposed I've seen it before.  

When it comes to how logical the flow of events are supposed to look like, it's not easy to write Test Cases via Unit Testing to test it.

I've been pondering the various ways of adding an `Expert Mode`  to recreate scenarios such as this one.

Q2 : do you have any stacktrace that you can cut and paste here ? 

Q3 :  you said "DNA" screenshots. Btw, what is "DNA" ? 

Appreciate much !

**Comment by Urwumpe** [comment]
Q1: Judging the state of the rover at the beginning of the log, I would say, it happened after the rover was towed back to Alpha Base. It is still towed after a few sols. All crewmembers had been assigned to a Areology Field mission in their schedule about 5 sols earlier.

Q2: No stacktrace, no exception. I seems to be a logical problem.

Q3: "Does Not Apply"

Unit Testing: One idea I am testing right now in a local branch is refactoring how missions are handled, by giving each MissionPhase a backlog of mission specific tasks for that phase, so that the complexity for writing unit tests can be reduced to testing tasks, ideally only atomic tasks that can make up more complex tasks in a BPML-like construction. Ideally, the template for such a mission phase could then be configured in XML, instead of hard coding them. A phase is done, when all defined tasks for that phase are done. Maybe still a bit simplistic for all kinds of missions. Try this right now in a new package "mission2", so this can be tested with simpler missions like a transport mission first. 

I feel like the current implementation of the missions is too complex and functions too often overloaded for properly testing them, except blackbox testing. For example, I still don't know precisely how a rover can embark to a mission with 0.0 kg food, when it asks for 2.5 kg at the beginning in the next phase. Happened a few times for a salvage rover mission.

Expert Mode: I also would like such a feature, maybe just for directly triggering emergencies. Or manually disconnecting a towed vehicle. Or inspiring a settler to suggest a specific scientific study. Well, what is needed for doing acceptance tests. Maybe a lot of those things could be triggered by the terminal? Like "dump oxygen to 50%" when a rover is the context.

I suspect it is some kind of combination of misfortunate events. Like an emergency cancelled the previous mission, crew not disembarking rover after being towed back, O2 not getting replenished without a mission, etc. Still I have no idea why the rover is not assigned to a new mission and why it is still towed.

**Comment by mokun** [comment]
> the template for such a mission phase could then be configured in XML, instead of hard coding them. 

Yes I'd love to make things more flexible by converting anything that's currently hard-coded to xml or json.

> current implementation of the missions is too complex and functions too often overloaded for properly testing them

So true. I don't like calling so many overloaded functions on each `Mission` and/or `Task`. Yes I do advocate adopting a simpler architecture.

> how a rover can embark to a mission with 0.0 kg food, when it asks for 2.5 kg at the beginning in the next phase. Happened a few times for a salvage rover mission.

I'll look into this and scenarios involving a towed back rover.  Thanks for pointing this out.

**Comment by mokun** [comment]
> For example, I still don't know precisely how a rover can embark to a mission with 0.0 kg food, 

This was fixed in [r4776](https://github.com/mars-sim/mars-sim/commit/f0a5069b58e4f9c7362c593a3c9d74e21d6ab1be) and [r4777](https://github.com/mars-sim/mars-sim/commit/f0a5069b58e4f9c7362c593a3c9d74e21d6ab1be)

It demanded a -ve amount of food. That's why, food can't be loaded. Also, the display of the food as an amount instance was not working in VehicleTableModel.

**Comment by mokun** [comment]
Just found another nasty bug that causes zero amount of food to be display due to switching to using the id of an amount resource for tracking resources.

**Comment by mokun** [comment]
@Urwumpe, as of r4896, setters are no longer appeared stuck inside a rover before a mission or after a mission is over. 

Having said that, what I do agree what you said that "the current implementation of the missions is too complex and functions too often overloaded for properly testing them, except blackbox testing..."

e.g. After a vehicle returns from a mission. In this `Disembarking Phase`, it involves too many steps. See this super long [method](https://github.com/mars-sim/mars-sim/blob/30156226467bd5a60bbe9d22d47687535a330c59/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/mission/RoverMission.java#L439) in `RoverMission`.

We could reorganize how this disembarking phase should be carried out and what special cases we might run into.

We could break down the whole thing into a few `Task` for each responsible party to perform, instead of having the A.I. to do a lot of things. If one thing breaks, it's very hard to debug.

**Comment by mokun** [comment]
> * When declaring an emergency, the current mission should get replaced by a passive "ROVER EMERGENCY" mission, instead of just ending the current one. Activities of this state should include ensuring survival until rescue and properly ending the emergency state afterwards. With later communication extension, this mission could allow telling the settlement about the kind of emergency, available resources and extending rations until rendezvous.

In our current implementation, a rover will have `emergency` in one of the following scenarios :  
1. having insufficient resources to continue the mission
2. settlers having medical emergency
3. unable to fix vehicle malfunctions and/or with no parts available

Any of these situations will *turn on* the `beacon` of the rover. 

As a result of that, the A.I. will trigger the settlers of its associated settlement to calculate the probability of starting a mission in [RescueSalvageVehicleMeta](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/mission/meta/RescueSalvageVehicleMeta.java). 

The most qualified person will be the `Starting Member` (he's sort of a mission commander in this case) of  this rescue operation.

The rescuing rover is supposed to locate the rover with beacon turned on, rendezvous with it, resupply the missing resources, and eventually tow it back home.

And I do suspect that there are a few situations that the current implementation fail to catch and respond correctly. 

e.g. Currently, a sick or a dead person will "magically" airlift back into the settlement when the rover is towed back home. Also, if no good EVA Suit is available, a person may get stuck inside the vehicle. 

So we will refine and improve this **mission emergency modeling**. Let's open a new thread to discuss further.

**Comment by mokun** [comment]
I've observed that if a settler ever got stuck inside because he's sick and has ZERO performance or he has no EVA Suit to leave the rover, he would be rescued.

**Comment by mokun** [comment]
This is an old thread and the issues have been worked on. Closing it. 

Open a new one if it happens again.
