### ISSUE TITLE
Consistency in maven package name and maven project group id 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1099]
**Is your feature request related to a problem? Please describe.**
- Currently, both `mars-sim-ui` and `mars-sim-core`, the package name has `mars_sim.msp.___`
- Other packages such as `mars-sim-tools`, `mars-sim-mapdata`, `mars-sim-main`, `mars-sim-headless`, and `mars-sim-console` have just been conformed to having `mars_sim.___`
- In all pom.xml, we have the following `groupId`
```xml
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.github.mars-sim</groupId>
	<artifactId>mars-sim</artifactId>
	<packaging>pom</packaging>
	<version>3.7.0</version>
	<name>mars-sim</name>
	<url>https://github.com/mars-sim/mars-sim</url>
	<inceptionYear>2009</inceptionYear>
```

**Describe the solution you desire to see**
- may make the `groupId` in pom.xml to be the same as `org.mars-sim.____`

**Describe the rationale**
- When compiling the source, the resulting directory structure is NOT consistent and it varies in the location of the content of a package. 

**Specifications  (please complete the following information):**
 - pre 3.7.0 build 8793 

**Additional context**
- See https://github.com/mars-sim/mars-sim/commit/74df1d29c6187b9e4b8770a0b5ddacd81066d5f2
- See https://github.com/mars-sim/mars-sim/commit/a482cf0acea3f3b1a698de20a1e18f986dec12d0

**Comment by mokun** [comment]
@bevans2000 

Should we change the `groupId` in pom.xml or should we replace the package path with `com.github.mars-sim.__` instead?

```xml
	<groupId>com.github.mars-sim</groupId>
```

**Comment by mokun** [comment]
By the way, we could even shorten the path from 
`org.mars_sim.main.MarsProject`
to just
`org.mars-sim-main.MarsProject`

**Comment by bevans2000** [comment]
Good practice is the names of the Maven artifact should reflect the package structure. So we have a constant root package, ```com.mars-sim``` which is the groupie. Then the rtifactid of the submodules can be named accordingly under it, e.g ```core```. No need to repeat Mars sim in the artifact name it you don't want as the artifact name is already globally unique with the group id.
Then the top level package in the module should be ```<group id>.<artifact id>```.
Generally by looking at the package name you can identify the Maven module. 
Just do all the changes you want and I will fix my branch afterwards.

**Comment by bevans2000** [comment]
I can also buy the domain name so we could redirect it to our github.io pages. We could use this for the map downloads as well.

**Comment by mokun** [comment]
Well, our site is `https://github.com/mars-sim/mars-sim/` and project webpage is `https://github.com/mars-sim/mars-sim.github.io`. The package name won't be able to match either of them.

So do we stick with using `org.mars-sim` or `com.mars-sim` in all maven package name path ?

If I understand what you're saying, it should be the same as the `groupId` in all pom.xml. 

Should it be 

```
<groupId>com.mars-sim</groupId>
```
or

```
<groupId>org.mars-sim</groupId>
```
?

**Comment by bevans2000** [comment]
Yes groupID should be com.mars-sim as this domain is available to buy. Then this should also be the root for the code packages.
Don't use 'org' because that TLD is controlled in a different way.

**Comment by bevans2000** [comment]
I now own ```com.mars-sim``` as a domain. Will wire it to use our GitHub pages later

**Comment by bevans2000** [comment]
Try this out https://mars-sim.com/
It points to what ever we have in our GitHub Pages site. Quite simple to create a Custom Domain for our pages site; all defined in the GitHub help pages.
The banner.jpg file is missing and I can't find it anywhere in the history of the pages.

**Comment by mokun** [comment]
Eclipse won't allow me renaming main package to `com.mars-sim.main`

![image](https://github.com/mars-sim/mars-sim/assets/1168584/51c8a096-6e73-4efb-a30f-a7f49d0158c6)

Looks like we can only use `com.mars_sim.main`

**Comment by mokun** [comment]
See https://blog.eisele.net/2010/09/hyphen-ussage-in-package-names.html
and
https://medium.com/kodgemisi/rationale-for-underscore-in-package-names-c3d9c8e4ce4a

**Comment by bevans2000** [comment]
I think I knew deep down that a dash isn't allowed. So the poms and code is now consistent around ```com.mars_sim``` and we just to fix Sonarqube? I'll take a look tonight after work

**Comment by bevans2000** [comment]
I've changed the project key in SonarQube so it back working. The badge on the main readme.md might need updating. I'll sort it out later

**Comment by mokun** [comment]
Yes. The last commit now shows the green check mark. It's working now.

So what have you changed ?

**Comment by bevans2000** [comment]
I changed the project key in the SonarCloud project so it matches our new groupid.

**Comment by mokun** [comment]
Question : what is causing the spurious appearance of `MEDGDR Cache hit rate 0, size=___..` ? 

```
01-Adir-01:039.570 (Info) CollectResourcesMission : Analyzing sites for Ice Prospecting #6.  Total Score: 4.07.  Best Score: 1.96
01-Adir-01:039.570 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=136
01-Adir-01:039.570 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=136
01-Adir-01:039.570 (Info) CollectResourcesMission : Analyzing sites for Ice Prospecting #6.  Total Score: 6.55.  Best Score: 2.48
01-Adir-01:039.570 (Info) CollectResourcesMission : [Arcadia] Fahrzeug - Estimating amount of Ice per site: 666 kg.
01-Adir-01:039.570 (Info) AbstractVehicleMission : [Arcadia] Lukáš Novák - Preparing Ice Prospecting #6 using Fahrzeug.
01-Adir-01:039.570 (Info) PlanMission : [Arcadia] Lukáš Novák - Submitted a mission plan for Ice Prospecting #6.
01-Adir-01:039.570 (Info) MissionManager : [Arcadia] Lukáš Novák - Put together a mission plan for Ice Prospecting #6.
01-Adir-01:040.377 (Info) MissionManager : [Schiaparelli Point] Leonardo DaVinci - Mission 'Regolith Prospecting' score: Score:1.307 (base:1,settlementratio:1.4,minerals:4.15,leader:0.075,extrovert:1,goods:1,population:3)
01-Adir-01:040.377 (Info) AbstractMission : [Schiaparelli Point] Leonardo DaVinci - Began organizing a Regolith Prospecting #7 mission.
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=137
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=145
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=146
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=148
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=150
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=150
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=150
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=152
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=154
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=154
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=158
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=159
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=160
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=163
01-Adir-01:040.377 (Info) CollectResourcesMission : Analyzing sites for Regolith Prospecting #7.  Total Score: 24.73.  Best Score: 12.37
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=165
01-Adir-01:040.377 (Info) MEGDRCachedReader : MEGDR Cache hit rate 0, size=166
```

**Comment by mokun** [comment]
Did you by any chance see them before the package name change ? 

I guess I never paid attention to any of them until now and it shows up a lot. 

It's supposed to do with caching elevation value.

One problem I don't know what that sentence is actually conveying.

**Comment by bevans2000** [comment]
I can have a look maybe tomorrow evening
