### ISSUE TITLE
OutOfMemoryError if starting 10 of MDP4 settlement

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#11]
Created: 2014-12-03
Migrated from https://sourceforge.net/p/mars-sim/tickets/21/ 

if I try to create 10 of Mars Direct Phase 4 settlement in SimulationConfig editor, msp won't start and will throw a number of "OutOfMemoryError: GC overhead limit exceeded"

See attached stack trace :
[OutOfMemoryError.txt](https://github.com/mars-sim/mars-sim/files/775209/OutOfMemoryError.txt)

**Comment by larsnaesbye** [comment]
[OutOfMemoryError.txt](https://github.com/mars-sim/mars-sim/files/775209/OutOfMemoryError.txt)

**Comment by larsnaesbye** [comment]
Scott Davis - 2014-12-05      
I got the same result when I created a new sim with 10 Alpha Base settlements. I think we've just hit a barrier with memory. This is 10 bases, 100 vehicles, and 240 people.
I doubled the max memory in my Eclipse run configuration argument from 512 Mb to 1024Mb (the -Xmx1024m argument), and it was able to create the simulation with 10 alpha base settlements. It runs quite slowly, but it seems to work.
I updated the max memory to 1024 Mb in the MarsProjectStarter class in mars-sim-main, which is used by the end users to start the simulation from the release jar file.

**Comment by larsnaesbye** [comment]
manny kung - 2014-12-05      
same with 9 settlements. 7 is fine last time.
I didn't check. what happen if it exhaust all the names given on the
people.xml?
On Thu, Dec 4, 2014 at 4:34 PM, Scott Davis scud1@users.sf.net wrote:
I got the same result when I created a new sim with 10 Alpha Base
settlements. I think we've just hit a barrier with memory. This is 10
bases, 100 vehicles, and 240 people.
I doubled the max memory in my Eclipse run configuration argument from 512
Mb to 1024Mb (the -Xmx1024m argument), and it was able to create the
simulation with 10 alpha base settlements. It runs quite slowly, but it
seems to work.
I updated the max memory to 1024 Mb in the MarsProjectStarter class in
mars-sim-main, which is used by the end users to start the simulation from
the release jar file.
[tickets:#21] http://sourceforge.net/p/mars-sim/tickets/21
OutOfMemoryError if starting 10 of MDP4 settlement*
Status: open
Milestone: 3.07
Labels: OutOfMemoryError settlements simulationconfig
Created: Wed Dec 03, 2014 08:44 PM UTC by manny kung
Last Updated: Wed Dec 03, 2014 08:44 PM UTC
Owner: nobody
if I try to create 10 of Mars Direct Phase 4 settlement in
SimulationConfig editor, msp won't start and will throw a number of
"OutOfMemoryError: GC overhead limit exceeded"
see stack trace
Sent from sourceforge.net because you indicated interest in
https://sourceforge.net/p/mars-sim/tickets/21/
To unsubscribe from further messages, please visit
https://sourceforge.net/auth/subscriptions/

**Comment by larsnaesbye** [comment]
manny kung - 2017-01-20      
Lately I've been experimenting with fine-tuning TPS and time ratio in accordance with the CPU speed and available # of cpu threads on a user's machine. We will need to discuss how this ticket may be satisfactorily resolved in near future.

**Comment by mokun** [comment]
In r3831, I scale the default time-ratio (previously at 500 by default) and time-between-updates (previously by default at 40 ms or 25 Hz) according to the number of the available threads in user's machine. 

In simulation.xml, 
> 		<time-ratio value="512" />
> 		<!-- 1. time ratio will be re-scaled according to available # of threads (not # of cpu cores). 
> 			 2. time ratio must be a multiple of 2.
> 			 3. if time ratio is 512, then 1 real second equals 512 simulation second in mars-sim  
> 			 4. Minimum is 16, maximum is 4096

In MasterClock's constructor,

```
        // Setting the initial time ratio.
        double ratio = config.getSimulationTimeRatio();
        double ms = config.getTimeBetweenUpdates();

        //TODO: should also test the CPU speed to determine the TPS
        ...
        if (Simulation.NUM_THREADS == 1) {
        	time_ratio = ratio/8D;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms*16D);
        }
        else if (Simulation.NUM_THREADS == 2) {
        	time_ratio = ratio/8D;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms*12D);
        }
        else if (Simulation.NUM_THREADS <= 3) {
        	time_ratio = ratio/4D;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms*8D);
        }
        else if (Simulation.NUM_THREADS <= 4) {
           	time_ratio = ratio/4D;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms*4D);
        }
        else if (Simulation.NUM_THREADS <= 6) {
        	time_ratio = ratio/2D;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms*2D);
        }
        else if (Simulation.NUM_THREADS <= 8) {
        	time_ratio = ratio/2D;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms);
        }
        else if (Simulation.NUM_THREADS <= 12) {
        	time_ratio = ratio;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms);
        }
        else {
        	time_ratio = ratio;
        	setTimeRatio(time_ratio);
            setTimeBetweenUpdates(ms);
        }

```


However, this method is unreliable since an 10-year-old Intel CPU may have the same # of threads as a 7th-generation Kaby Lake Intel CPU but the performance may differ significantly.

Perhaps the best way is to benchmark the performance of the user's machine.

If user thinks the default time ratio is too slow/fast. he may adjust it manually in the speed panel in the main window.
