### ISSUE TITLE
job selection and country are still not right. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#110]
**Describe the bug/issue**
 - A clear and concise description of what the bug/issue is.

`$ java -jar r4520_headless_java9.jar `

see - 

```
Job (0-15) [4]: ​

  -------------------- Job Listing --------------------
(1).  Architect         (2).  Areologist        (3).  Astronomer        
(4).  Biologist         (5).  Botanist          (6).  Chef              
(7).  Chemist           (8).  Doctor            (9).  Driver            
(10). Engineer          (11). Mathematician     (12). Meteorologist     
(13). Physicist         (14). Reporter          (15). Technician        

Job (0-15) [4]: ​15
Country (0-27) [4]: ​

  -------------------- Country Listing --------------------
(1).  China             (2).  Canada            (3).  India             
(4).  Japan             (5).  USA               (6).  Russia            
(7).  Austria           (8).  Belgium           (9).  Czech Republic    
(10). Denmark           (11). Estonia           (12). Finland           
(13). France            (14). Germany           (15). Greece            
(16). Hungary           (17). Ireland           (18). Italy             
(19). Luxembourg        (20). The Netherlands   (21). Norway            
(22). Poland            (23). Portugal          (24). Romania           
(25). Spain             (26). Sweden            (27). Switzerland       

Country (0-27) [4]: ​3

Commander's Profile: 
   First Name: shirish
   Last Name: agarwal
   Gender: M
   Age: 42
   Job: Trader
   Country: Japan
   Space Agency: JAXA
```

**Affected Area**
 - What area(s) are we dealing with ? [e.g. Construction, Mission, Resupply, Settlement Map, Mini-map, Saving/Loading Sim, System Exceptions in Command Prompt/Terminal, etc..]

**Expected behaviors**

The expected behavior was it should have taken the correct values but didn't. 

**Actual/Observed Behaviors**

- Shared above. 

**Reproduction (optional)**
 - Steps to reproduce the problem

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
e.g. Include the followings :
 a. Person Window showing various activity tabs 
 b. Settlement/Vehicle Window 
 c. Monitor Tool's showing People/Vehicle/Mission tabs  
 d. Settlement Map, etc.

```
Package: openjdk-11-jre-headless
Version: 11.0.1+13-2
Severity: normal


-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages openjdk-11-jre-headless depends on:
ii  ca-certificates-java  20180516
ii  java-common           0.70
ii  libasound2            1.1.7-1
ii  libc6                 2.27-8
ii  libcups2              2.2.8-5
ii  libfontconfig1        2.13.1-1
ii  libfreetype6          2.8.1-2
ii  libgcc1               1:8.2.0-9
ii  libjpeg62-turbo       1:1.5.2-2+b1
ii  liblcms2-2            2.9-3
ii  libnss3               2:3.39-1
ii  libpcsclite1          1.8.24-1
ii  libstdc++6            8.2.0-9
ii  libx11-6              2:1.6.7-1
ii  libxext6              2:1.3.3-1+b2
ii  libxi6                2:1.7.9-1
ii  libxrender1           1:0.9.10-1
ii  libxtst6              2:1.2.3-1
ii  util-linux            2.32.1-0.1
ii  zlib1g                1:1.2.11.dfsg-1

openjdk-11-jre-headless recommends no packages.

Versions of packages openjdk-11-jre-headless suggests:
ii  fonts-dejavu-extra    2.37-1
pn  fonts-indic           <none>
ii  fonts-ipafont-gothic  00303-18
ii  fonts-ipafont-mincho  00303-18
ii  fonts-wqy-microhei    0.2.0-beta-3
ii  libnss-mdns           0.14.1-1

-- no debconf information
```

**Additional context**
 - Add any other context about the problem here.

**Comment by mokun** [comment]
@shirishag75 
 
Seems you are running the the older builds. Please delete them. Do not place multiple builds in the same folder/directory. The classpath will not work.

Please ensure you are running r4520.

**Comment by mokun** [comment]
The correct screenshot from r4520 will show the following.

Note that the formatting is different from the one you posted. That's why i know it's not from r4520.

> 
>  ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------
> 
> 1. Commander Mode 
> 2. Sandbox Mode 
> 
> Enter your choice: ​1
> 
> Press Ctrl-O to show a list of countries.
> Press Ctrl-J to show a list of jobs.
> Press Ctrl-U to go back to the previous field.
> 
>                  First Name [dave]: ​
>                   Last Name: ​err
>               Gender (M, F): ​m
>                 Age (18-80) [30]: ​
>                  Job (1-16) [5]: ​
>     Mars Society Affiliated [y]: ​
>              Country (1-28) [5]: ​
> 
>                 * * *  COMMANDER'S PROFILE * * *
> 
>                First Name: dave
>                 Last Name: err
>                    Gender: m
>                       Age: 30
>                       Job: Botanist
>                   Country: USA
>                   Sponsor: Mars Society (MS)
> 
> 
> -------------------  C O N S O L E   M E N U  -------------------
> 
>   1: Enter the Chat Mode
>   2: Change the Simulation Speed
>   3: Save the Simulation
>   4: Exit the Simulation
>      
> Enter your choice: ​

**Comment by mokun** [comment]
Sorry I uploaded the wrong jar file. Give me a minute and I'll redo the upload.

**Comment by mokun** [comment]
Done. Please download the correct build for testing and feedback. Appreciate !

**Comment by mokun** [comment]
Note that I have NOT implemented anything for the `Commander Mode`. For now, it is no different from the `Sandbox Mode`.

**Comment by shirishag75** [comment]
> Sorry I uploaded the wrong jar file. Give me a minute and I'll redo the upload.

lol, ok ;)

**Comment by mokun** [comment]
Done. Thanks for pointing that out.
