### ISSUE TITLE
Simulation halts when reaching Sol 2

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1103]
**Describe the bug**
- Currently, the simulation would suddenly halt as soon as the Mars clock reaches Sol 2 at 000 millisols

**Discuss any potential problems you have and have not ruled out**
- It may have to do with some recent change in ClockPulse in creating newHalfSol and isHalfSol.
 
**Java classes involved**
- `ClockPulse`, `MasterClock`

**Stacktrace**
```
01-Adir-01:339.827 (Warning) SettlementTransparentPanel [x31] : [System] SettlementTransparentPanel : Sun data at 35.2300 N 163.9500 E is not available.
...
01-Adir-01:729.255 (Warning) SettlementTransparentPanel [x58] : [System] SettlementTransparentPanel : Sun data at 35.2300 N 163.9500 E is not available.
...
01-Adir-01:995.320 (Info) BotTaskManager : [Pilgrim] MakerBot 001 - Forcing to be recharged due to low power.
01-Adir-02:000.401 (Config) MasterClock :  - - - - - - - - - - - - - - Sol 2 - - - - - - - - - - - - - - 
```

**Specifications (please complete the following information)**
- pre 3.7.0 build 8812

**Additional context**
- It's unknown at some point exactly what's causing it.

**Comment by mokun** [comment]
@bevans2000 

Do you have any insights on what might have caused it ?

**Comment by bevans2000** [comment]
@mokun yes it is the time pulse method on the Population class you added. There is a loop where the condition variables are never updated so it goes into an infinite loop. I don't understand what it trying to do, checking the number if beds.

**Comment by mokun** [comment]
> There is a loop where the condition variables are never updated so it goes into an infinite loop. 

Got it. It's fixed now.

> I don't understand what it trying to do, checking the number if beds.

That loop serves to limit the increase of population if beds are not enough. 

For now, it makes sense to slow down the growth of one of the 3 types of population this way. 

e.g. if the total population is 50 and there are only 48 beds available, it makes sense to slow the growth rate of one type of pop... 

In future, it will change to become a little more realistic in modeling how launch vehicles will arrive and depart and actually ferry passengers onboard between destinations.
