### ISSUE TITLE
Strength-based calculations of AR masses too low?

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#112]
**Describe the bug/issue**

I wonder if the values calculated by the strength attribute of the Settler are lower now than they used to be in the past.

I observed multiple times already that such tasks only collect less than 2 kg of regolith, about 300g on the average. One settler had a very good strength (over 85% AFAIR), but also collected less than 100g in multiple events.

**Affected Area**
- DigLocalRegolith task
- Inventory.addGeneralCapacity()
- Inventory.getAmountResourceRemainingCapacity()
- Inventory.updateARCapacityCache()

By the task, about 20 kg on the average per millisol is used as average potential, so I suspect the limitation should be in the Inventory code.

**Expected behaviors**
I would have expected a bigger quantity collected by the task in total. About 10 kg shouldn't be impossible on Mars with lower gravity, carrying a 5 kg bag on Earth isn't a big challenge, even in a space suit.

**Actual/Observed Behaviors**

 For example:

'2018-11-07T12:50:57.1 (Info) DigLocalRegolith : [3,0° S 16,0° E] Rik Declercq collected 0.49 kg of regolith outside Schiaparelli Point'

'2018-11-07T13:15:03.9 (Info) [x24] DigLocalRegolith : [15,9° S 4,2° E] Jennifer Proctor collected 1.97 kg of regolith outside Plymouth Base'

**Reproduction (optional)**
No special steps, just simulate until such a task happens, it isn't rare.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : Oracle JRE 10
 - mars-sim build version : r4520_headless_java9

**Comment by mokun** [comment]
> 2018-11-07T13:15:03.9 (Info) [x24] DigLocalRegolith : [15,9° S 4,2° E] Jennifer Proctor collected 1.97 kg of regolith outside Plymouth Base

The way it should read is : 1.97 kg * 24 = 47.28 kg

Since the method collectIce() in DigLocalIce is being called up multiple number of times within a certain time frame (e.g. 10 seconds), in light of that, I use the following : 

```
	    LogConsolidated.log(logger, Level.INFO, 10000, sourceName, 
	    		"[" + person.getLocationTag().getQuickLocation() +  "] " +
	    		person.getName() + " collected " + Math.round(iceCollected*100D)/100D 
	    		+ " kg of ice outside " + person.getAssociatedSettlement(), null);
```

to combine the same log statement that would have appeared 24 times into just one within.

I should probably create new phase called `FINISHED` and a new method called finshed() after the `COLLECT_ICE` phase and show the combined total kg of ice collected. This should make more sense and less confusing.

**Comment by mokun** [comment]
> One settler had a very good strength (over 85% AFAIR), but also collected less than 100g in multiple events.

I just noticed that the strength attribute was NOT used when it should really have been. Will mod it.

**Comment by mokun** [comment]
The mod was done. 

Personally speaking, I dislike how easy it is currently to collect regolith and ice right outside a settlement.

The only different between a regolith/ice mission and the digging local regolith/ice is the amount. There should be more distinction. But we will need to open a new thread to discuss more. 

Closing this now.
