### ISSUE TITLE
Logic of OrbitIfno::IsSunSetting method incorrect

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1120]
**Describe the bug**
The isSunSetting method in OrbitInfo can never evulate to true because it contains conflicting conditions. No matter what value cosZenith is it never works.
````
			// See if the solar zenith angle is between 90 and (90 + the dusk angle) 
			// Note: if the sun is below the horizon, the solar zenith angle should be negative
			if (cosZenith >= 0 && cosZenith <= 0 && cosZenith > COSINE_ZENITH_ANGLE_AT_DUSK) {
				result = true;
			}
```
This is preventing any Observation Tasks taking place and also affecting the toggling of power sources.

**Expected and unexpected behavior**
- I would expect that this uses the sol time in relation to the Coordinates. The method cached the previous value but that could be for a totally different Coordinate.

**Comment by bevans2000** [comment]
@mokun You understanding how this Orbit logic work but this method is totally wrong.

**Comment by mokun** [comment]
Thanks for pointing out the logic is wrong. Correcting it now.

**Comment by mokun** [comment]
It should work well now.

The estimated values on the weather panel in settlement map are the results of data gathering. 

But we can also do use an analytical approach to find the zenith time, sunrise, sunset time, etc. via the equations in OrbitInfo.

This way, we could use both approach to derive a better estimate.

For now, the estimate is kind of okay. Sometimes, the projected sunrise and actual sunrise are off by 50 to 100 milisols.

**Comment by mokun** [comment]
The projected sunrise and sunset values are finally up to par with the reported values.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/05fed7a6-7c4e-4164-ba37-2c189c534161)

But of course, the reported values are just measured values and are dependent upon how fast the time ratio (TR) is at. 

For high TR, it will be way off the actual values.
