### ISSUE TITLE
Have an option of continuing from default.sim within the headless mode. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#113]
While I would like that we [de-serialize the .sim file](https://github.com/mars-sim/mars-sim/issues/75) so it's not so large, currently which is saved in ~/.mars-sim/saved/default.sim , it would be nice if the headless mode also had an option to continue a simulation started 

Currently we have two options in the headless .jar 
```

 ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------

1. Commander Mode 
2. Sandbox Mode 

Enter your choice: ​
```

We need to have a third option as well - 

 ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------

1. Commander Mode 
2. Sandbox Mode 
3. Continue the simulation 

Enter your choice: ​

The 3rd option will continue the simulation from where it stopped. At the same time, it should be possible to interact with the MarsNet system and be able to change the speed of the simulation.

**Comment by mokun** [comment]
The standard way of loading from a saved sim is as follows : 
> java -jar r4520_headless_java9.jar load

The `load` switch will tell mars-sim to go into the default directory to look for the saved sim called `default.sim`.

If you don't have the `new` switch, it is automatically added and assume that you are starting a new simulation.
