### ISSUE TITLE
What is an SEP event ? What to model about the lockdown of the settlement in case of SEP

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#116]
I tried to use the wiki to find out about SEP event but was unsuccessful 
`
2018-11-07T18:57:30.0 (Info) Settlement : [Plymouth Base] The detector grid forecast a SEP event is imminent.`

**Comment by shirishag75** [comment]
https://github.com/mars-sim/mars-sim/wiki/Radiation-Exposure

**Comment by mokun** [comment]
Remind me to revisit how radiation events are being forecast and strike a settlement or a person performing an EVA operation in future.

I'll need to dig up more research paper on how radiation events are detected, especially during a mission when settlers are out there somewhere on the surface of Mars, and how different types of geographical regions of Mars and any localized magnetic fields may interact with the radiation.

**Comment by mokun** [comment]
So here's the question: in the event of a severe geomagnetic storm approaching Mars,  what do we envision the mission control of a settlement would do in mars-sim ? 

What do we want to model in terms of the lockdown procedures ?

For now we have 3 types of radiation events that can occur in mars-sim, of which, Solar Energetic Particle (SEP) event is the most severe one.

**Comment by mokun** [comment]
@bevans2000 

What do you see we can plan architecturally to allow certain future events (such as an intense geomagnetic storm) to drive the whole settlement toward one goal together en mass ?

**Comment by bevans2000** [comment]
So I think the answer is to influence the Tasks selected in the PersonTaskManager as part of the rebuildCache method. This method could look at the status of other things.

**Comment by mokun** [comment]
@bevans2000 

Thanks for refactoring radiation-related codes in your recent commit at https://github.com/mars-sim/mars-sim/commit/17bf9ab5404f9a28210bbcb12bcf8225ec60d6c5

Perhaps we can go further in modeling how a settlement should alert everyone to take cover.

We may even create a radiation shelter as a standalone building for every settler to go inside when happened.

**Comment by mokun** [comment]
@shirishag75 

We may as well close this old thread now. 

Radiation exposure primarily affected people working outside in the settlement vicinity.
