### ISSUE TITLE
Use a single coordinate frame for Activity Spots

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1164]
**Is your feature request related to a problem? Please describe.**
Activity Spots are created in the coordinate frame of the Building. But Workers use the Settlement coordinate frame when moving around.
This results in a lot of conversion between the 2 frames.

**Describe the goal(s) you have in mind**
The goal is to only use the Settlement coordinate frame by creating Activity Spots with the position of the Settlement. This means an initial conversion is done when creating the Activity Spot and then no other.

In addition the ```LocalPosition``` class can be converted to use centimeters as the base unit instead of meters. This removes the need to use doubles,

This is a follow-on from #1143

**Comment by mokun** [comment]
> se centimeters as the base unit instead of meters

We will probably need to revise all the activity spots in buildings.xml to become integers, instead of doubles ? 

Or we keep the meter specification in buildings.xml. It's when loading them into respective `Function`, we auto-convert them to nearest cm.
