### ISSUE TITLE
Reserve an Activity Spot; Guest Beds

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1166]
**Is your feature request related to a problem? Please describe.**
- Currently, it's possible for a collision to occur when two persons/robots are fighting for the same activity spot to go to. 
- For instance, person A identifies a far-away activity spot in another building to go to, it would get started going in the same frame. But since walking may take more than a frame, this worker may still be on the way by the end of this frame.
- However, person B is also interested in going to the same activity spot. If this spot is in the same building he's at, it would take almost zero time for him to get there and claim the activity spot.
- As a result, when person A gets there, he finds the activity spot has already been taken.
- Both person A and person B be shown on the Settlement Map at the same spot.
- However, person B is the one who actually possesses the *title* of this activity spot.

**Describe the rationale**
- Avoid the possibility of contention 

**Describe the goal(s) you have in mind**
- A reservation system should solve this collision problem and ensure only one worker can occupy an activity spot. 

**Describe the solution you desire to see**
- Much like reserving a vehicle, an activity spot should be reserved ahead of the arrival of a worker to claim the spot, just in case that it takes more than a frame to walk there.
- When the spot is claimed, its reservation is released.
- When a spot is released, its reservation is open.

**Specifications**
- pre 3.7.0 build 9052 

**Additional context**
- This issue is in conjunction with the change implemented in https://github.com/mars-sim/mars-sim/issues/1143

**Comment by bevans2000** [comment]
Yes I've been thinking about Bed and how they could use Activity Spots. They need to register who is physically there but also they can be reserved before hand. 
Not sure yet it could be used for Vehicle but it is possible. They question is when? Now or a later release. I think we need to use Activity Spot everywhere, e.g beds etc. And use a single coordinate frame

**Comment by mokun** [comment]
>  thinking about Bed and how they could use Activity Spots. They need to register who is physically there but also they can be reserved before hand.

I suppose both registration and reservation share some similarity but they are also different.

While we want a person permanently registering a bed and set aside for his own use,  we want a person to temporarily reserve an activity spot so that he is permitted to go there.

**Comment by bevans2000** [comment]
Yes if we allow reservations that can be prevented. Beds work the same but and not unreserved when a person leaves. So reservations can be permanent or temporary.
This is all achievable and would simply a lot of the logic by standardising.

**Comment by mokun** [comment]
> lets stop changing Activity Spot in the master branch and create a branch to make these changes.

I'll offer one last commit in a moment to fix up the Charge task related issues as well as the activity spot xLoc yLoc definition in Command and Control building and Server Farm.

Then I'll let you work on it.

**Comment by bevans2000** [comment]
Ok, let's do it

**Comment by mokun** [comment]
Yes. May as well fix that in 3.7.0.

**Comment by bevans2000** [comment]
Uncovered an interesting problem. When creating walking tasks in the Task class we assign the final destination position to the Worker before they actually start the task. This is why we get random invalid start location errors. The position assigned is not part of the assigned Building and sometimes the Position is outside the bounds of the assigned Building.
When moving to a single coordinates frame the mismatch is more exaggerated.
I will fix it as part of these changes.

**Comment by mokun** [comment]
> When creating walking tasks in the Task class we assign the final destination position to the Worker before they actually start the task. This is why we get random invalid start location errors.

Awesome. Thanks for uncovering the reason. 

> I will fix it as part of these changes.

Appreciated !

**Comment by mokun** [comment]
We may even let a person reserve a resource, manufacturing, food production process ahead of time so that we don't assign too many people to start one single process.

But I believe it's been alleviated by having some randomness selection already. Yet it can still happen that two persons will pick the same manufacturing process to start. It's possible only one is needed. 

Also, I wonder if selecting the repairer would benefit from this reservation mechanism or not.

**Comment by mokun** [comment]
Let's also add the lab and admin workspace to the scenarios:

1. Bed 
2. Charging 
3. Dining 
4. Lab
5. Admin

**Comment by bevans2000** [comment]
@mokun I have added names to Activity Spots so I'm going to add them to the Settlement Map Tool. It looks liek the code has a lot of duplication and can be tidied up.

**Comment by mokun** [comment]
> added names to Activity Spots

Names ?

> add them to the Settlement Map Tool.

Do you mean a new map layer that shows the location of each activity spot ?

**Comment by bevans2000** [comment]
> > added names to Activity Spots
> 
> Names ?
> 
Check out 438e24a to see what I have done.

**Comment by bevans2000** [comment]
@mokun I have decided that to render the named Activity Spots the Settlement map needs reworking. So have a look at 7979a27.
I have made some big improvements it the map layers in terms of performance & readability.
I think the colours are not ideal for Vehicles but in the new code it is a lot easier to understand how the colours are defined.

**Comment by mokun** [comment]
@bevans2000 

How soon will you commit [this](https://github.com/mars-sim/mars-sim/commit/b1cdc3784a224794507adaae6dc66053b8064606) ?

**Comment by bevans2000** [comment]
I have it working. I want to make some ui changes, e.g add activityspots to map and replace Building coordinates in the Person location panel with the activity spot name

**Comment by mokun** [comment]
>  I want to make some ui changes, e.g add activityspots to map and replace Building coordinates in the Person location panel with the activity spot name

Will it be including `LocationTabPanel` ?

**Comment by bevans2000** [comment]
> 
> Will it be including `LocationTabPanel` ?

Yes that the one. It will be ready atthe weekend. I also gave an idea how to fix the table sorter problem as well.

**Comment by mokun** [comment]
are you making each bed reservable ?

**Comment by mokun** [comment]
Guess EVA chambers are in more urgent need to be reservable than anything else.

**Comment by bevans2000** [comment]
All activity spot are claimed when a Worker identifies them as a target. And then released when they leave.
But Beds are permanently assigned and remain assigned when a Person end a Sleep

**Comment by bevans2000** [comment]
@mokun So this change to reserved Bed is working but it's shown another problem. In large locations there is not Settlers that Beds so some people can find a bed. Now I would expect that every Settler has a permanent bed assigned so they can make it "home".
What do you want to do about it? If there isn't a free bed they could just use a random already reserved bed.

**Comment by mokun** [comment]
> . In large locations there is not Settlers that Beds so some people can find a bed

In which settlement templates you don't find every citizen a bed ?

**Comment by mokun** [comment]
> What do you want to do about it? If there isn't a free bed they could just use a random already reserved bed.

I could either
(1). add a residential quarters to that template
(2). define some *temporary* or *guest* bed activity spots for anyone to use.

Don't we already have (2) above in some buildings in buildings.xml ? 

But we can add more of those spot for emergency use.

**Comment by mokun** [comment]
See the guest tag within living-accommodations tag :
```xml
<living-accommodations capacity="11">
	<activity>
		<activity-spot xloc="2.2" yloc="3.2" />
		<activity-spot xloc="2.2" yloc="1.8" />
		<activity-spot xloc="2.2" yloc=".4" />
		<activity-spot xloc="2.2" yloc="-.6" />
		<activity-spot xloc="2.2" yloc="-2.0" />
		
		<activity-spot xloc="2.2" yloc="-3.4" />
		<activity-spot xloc="-2.2" yloc="3.2" />
		<activity-spot xloc="-2.2" yloc="1.8" />
		<activity-spot xloc="-2.2" yloc=".4" />
		<activity-spot xloc="-2.2" yloc="-.6" />
		
		<activity-spot xloc="-2.2" yloc="-2.0" />
		<activity-spot xloc="-2.2" yloc="-3.4" />
	</activity>
	<guest>
		<activity-spot xloc="0" yloc="0" />
	</guest>
</living-accommodations>

```

**Comment by mokun** [comment]
Also, it makes sense to temporarily use medical bed in the Lander Hab building: 
```xml
<!-- The building has a medical infirmary. -->
<!-- tech-level: the treatment level capability of the infirmary. (see tech_level.txt) -->
<!-- beds: the number of patients the infirmary can support. -->
<medical-care tech-level="4" bed="1">
	<activity>
		<activity-spot xloc="-2" yloc="2" />
	</activity>
	<bed>
		<bed-location xloc="-1.97" yloc="1.83" />
	</bed>
</medical-care>
```

**Comment by bevans2000** [comment]
Right, I'm thinking of short term until we sort out guest beds with Activity Spot they will randomly use "squat" on an allocated one but we should add more permanent beds so every Settler has one.
Settlement Schiaparelli Point show the problem.

**Comment by mokun** [comment]
How about we add a new table (in TabPanelCItizen or TabPanelIndoor) that will show the name of the permanent/guest bed, the building it belongs, the settlement xloc yloc and the person assigned ?

**Comment by mokun** [comment]
>  Schiaparelli Point 

If you mean the Alpha base settlement template, then that's very strange.

It has 24 population. But it has 3 lander habs and a residential hab. 

So in terms of permanent beds, it has 4 * 3 + 12 = 24.
 
It should also have 4 guest beds.

**Comment by bevans2000** [comment]
OK, let me double check. Maybe I have something wrong.
Trying to be slow and steady with the changes.

**Comment by bevans2000** [comment]
Just got the beds left to fix. But I have got the ui showing the Activity spots in the Location tab panel and the Settlement map. The latter you can select just which Functions, for example all the charging points or Exercise spots. Works really well. I've just got to plumb it into the user properties framework.
And a little more testing at weekend.

**Comment by bevans2000** [comment]
> How about we add a new table (in TabPanelCItizen or TabPanelIndoor) that will show the name of the permanent/guest bed, the building it belongs, the settlement xloc yloc and the person assigned ?

Ok. Makes sense. I might do that after it is on the master branch so you can test it out as well.

**Comment by bevans2000** [comment]
> > How about we add a new table (in TabPanelCItizen or TabPanelIndoor) that will show the name of the permanent/guest bed, the building it belongs, the settlement xloc yloc and the person assigned ?
> 
> Ok. Makes sense. I might do that after it is on the master branch so you can test it out as well.

I've had a think about this and what's the purpose of the indoor tab? The info is available on the Monitor window so we are duplicating. Let's remove this tab and replace it with a new tab about Living. Could be a list of all the beds and details on Shift patterns

**Comment by mokun** [comment]
> Let's remove this tab and replace it with a new tab about Living. 

That makes sense.

> Could be a list of all the beds and details on Shift patterns

In the long run, we need a tab for hosting info on a person's citizen registry info such as the date he arrives at this settlement and make it home (or receives citizenship). 

He may even be given political asylum or naturalized. 

It will show where he emigrated from and country on Earth in which he was borne. 

But those who are born in Mars will be shown *Born in XYZ on Mars*.

**Comment by bevans2000** [comment]
We need to compare details about a Person at the Settlement level compared to the individual level. Anything in Settlement is just a summary of Persons.

**Comment by bevans2000** [comment]
Planning to make a PR with these changes tomorrow

**Comment by mokun** [comment]
I can see in LocationTabPanel that there's a new line called *Reserved Spot: ... *.

However, For Albert Watson, he's asleep in his bed,  is *Reserved Spot* supposed to be blank ? 

What should it show ? 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/f2d0693b-ca3d-4606-8a80-d887684aab1d)

**Comment by bevans2000** [comment]
Yes I noticed this last night. When doing other task it works well but when sleeping it is blank. There must be a problem in the Sleep logic. I was going to look today.

**Comment by bevans2000** [comment]
@mokun  One thing I have noticed is that on the default Scenario many of the Settlements do not have enough beds for all the Citizens. I'm thinking how we can allow Person to "squat" on someone else's Bed.

**Comment by mokun** [comment]
> I am going to change how bed allocation is done as the current approach doesn't work well for Settlements with too few beds which I have not tested.

If there's not enough permanent beds, it's supposed to start using guest beds (may be partially implemented). If filled, then use medical bed (not implemented yet).

Also, when lodging facilities is not accessible, one can *sleeping beds* anywhere (in any activity spots).

**Comment by bevans2000** [comment]
Makes sense. What I am going to do is remove the concept of explicit guest beds, a bed is a bed no matter what. But I'm going to add the concept that a LivingAccomodation can support guests or not support guests. 
Because they now use ActivitySpots it is easy to track the permanent assignments for citizens and the temporary guest ones.
Overall I think it is making the code a lot simpler.

**Comment by bevans2000** [comment]
@mokun I have created a draft pull request with the reworking of the bed allocation. I still have one more minor thing to do but won't have time until later in the week so have a look at this version

**Comment by mokun** [comment]
We'll need to find out why they can't find a temporary bed.

```
01-Adir-03:890.915 (Warning) LivingAccommodations [x24] : [New Seoul - Lander Hab 1] Haun Rim - Could not find a temporary bed.
01-Adir-03:890.915 (Warning) LivingAccommodations [x24] : [Hong Tian - Lander Hab 1] Lanfen Zheng - Could not find a temporary bed.
01-Adir-03:890.915 (Warning) LivingAccommodations [x24] : [Tian Cheng - Lander Hab 1] Chonglin Ding - Could not find a temporary bed.
01-Adir-03:890.915 (Warning) LivingAccommodations [x24] : [Tian Cheng - Lander Hab 1] Mingyu Guo - Could not find a temporary bed.
```

**Comment by mokun** [comment]
So, it has to do with these two methods in LivingAccommodations : 

```java
	/**
	 * Registers a sleeper with a bed.
	 *
	 * @param person
	 * @param isAGuest is this person a guest (not inhabitant) of this settlement
	 * @return Successful with the registration
	 */
	public boolean registerSleeper(Person person, boolean isAGuest) {
		// Assign standard necessity
		assignStandardNecessity(person);	
		
		if (person.getBed() != null) {
			return true;
		}

		// Find a bed
		if (getNumEmptyActivitySpots() > 0) {
			LocalPosition bed = designateABed(person, isAGuest);
			if (bed != null) {
				return true;
			}
		}
		
		logger.log(building, person, Level.WARNING, 2000,
								"Could not find a temporary bed.", null);
		return false;
	}

	/**
	 * Assigns/designates an available bed to a person.
	 *
	 * @param person
	 * @return
	 */
	private LocalPosition designateABed(Person person, boolean guest) {
		LocalPosition bedLoc = null;

		int numDesignated = getNumAssignedBeds();
		if (numDesignated >= maxNumBeds) {
			return null;
		}
		
		// Note: guest beds are reserved for temporary use and 
		// are not assigned here for use here
		Set<ActivitySpot> spots = getActivitySpots();
		for (var sp : spots) {
			if (sp.isEmpty()) {
				if (!guest) {
					// Claim the bed permanently
					AllocatedSpot bed = sp.claim(person, true, building);
					person.setBed(bed);
				}
				logger.log(building, person, Level.INFO, 0, "Given a bed ("
							+ sp.getName() + ").");
				
				bedLoc = sp.getPos();
				break;
			}
		}

		return bedLoc;
	}
```

**Comment by mokun** [comment]
In settlement_phase_3-cn.xml, it has only one Residential Quarters with 12 bed and a Lander Hab with 4 beds. 

In scenario_default.xml, *Hong Tian* settlement has 16 settlers.

```xml
		<settlement name="Hong Tian" template="Phase 3-CN" persons="16" robots="8" sponsor="CNSA">
			<location longitude="50.0 W" latitude="20.0 N" />
		</settlement>
```

Somehow Lanfen was never given a bed. See below : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/9cec76a3-26dc-4e05-89ec-b551ae24973f)

**Comment by bevans2000** [comment]
My code on the branch has changed how this is done. I just need to run it in a few different scenarios

**Comment by mokun** [comment]
@bevans2000,

Rather than squating or sleeping at someone else's bed which can cause collision, it makes more sense to use Lounge as it has plenty of space for setting up temporary beds. 

Any seats in dining halls are as good as treating as temporary beds.

**Comment by bevans2000** [comment]
There is a method in LivingAccomdation for locating an Activty Spot to sleep rough so you can change that logic. It currently find the first Building with LifeSupport and a free activity spot.

**Comment by bevans2000** [comment]
I'm going to close this. There is further changes we can do but we should open new more specific issues to cover them.

**Comment by mokun** [comment]
For the activity spot layers, can we do the following 2 things to reduce the overlapping of words: 
1. Reduce fonts
2. Use one or two letter acronym for each function

**Comment by mokun** [comment]
I found one major issue with the use of Function's claimActivitySpot().

Most of the usage do not check if the claim is successful or not. 

Therefore, it makes some workers overlapping on the same spot.

I just found this out when working on https://github.com/mars-sim/mars-sim/issues/1165.

**Comment by bevans2000** [comment]
That would be a good use of the Activity Spot. We would issue the claim when the Walk task is created that ends at an Airlock. The end taks clear down would have to release it but that is a common pattern.
Create a new issue.

**Comment by mokun** [comment]
>  the claim when the Walk task is created that ends at an Airlock

After 3.10.0 release, I'll piece together the brand new EVA Port as a future drop in replacement of EVA Airlock and it will adopt your approach of claiming an activity spot.

For sure, we don't want to touch the `ExitAirlock` and `EnterAirlock` right now. 

I'm glad at least no one get stuck in the airlock anymore.
