### ISSUE TITLE
Why are meals expired are never told, preserved food vs. hot meals

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#117]
Why are meals expired is never told or shared. I looked at Food production as well as malfunctions but couldn't find the reasoning of expiry of food. Also what perk or what functionality does preserved food have is not shared ?

```
2018-11-07T18:36:09.4 (Info) Cooking : [Alpha Base] 0.155 kg kidney bean fried rice is expired and discarded at Lander Hab 2.
2018-11-07T18:36:19.0 (Info) Cooking : [Alpha Base] A meal has expired. Converting 0.155 kg kidney bean fried rice into preserved food at Lander Hab 2.
2018-11-07T18:36:28.6 (Info) Cooking : [Alpha Base] 0.155 kg kidney bean fried rice is expired and discarded at Lander Hab 2.
2018-11-07T18:41:01.1 (Info) Cooking : [Plymouth Base] A meal has expired. Converting 0.155 kg kidney bean fried rice into preserved food at Lander Hab 2.
2018-11-07T18:41:11.9 (Info) Cooking : [Plymouth Base] A meal has expired. Converting 0.155 kg kidney bean fried rice into preserved food at Lander Hab 2.
2018-11-07T18:42:15.2 (Info) Cooking : [Plymouth Base] A meal has expired. Converting 0.155 kg kidney bean fried rice into preserved food at Lander Hab 1.

```

Also when they are discarded, why they are discarded is not known, ideally if not being eaten or preserved then it should be turned into some sort of manure or something similar for agriculture. 

`
2018-11-07T19:45:28.7 (Info) Cooking : [Alpha Base] 0.155 kg cabbage carrot slaw plate is expired and discarded at Lander Hab 2.`

**Comment by mokun** [comment]
> what perk or what functionality does preserved food have is not shared ?

Preserved food is simply the type of thermo-stabilized food that you find in the ISS now. It's not that appealing but it has long shelf lives. 

> Why are meals expired

Nothing beats a hot [meals.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/meals.xml), however, it goes bad after leaving it in the air for a while. 

```
/**
 * This class represents a cooked meal from a kitchen.
 */
public class CookedMeal
implements Serializable, Cloneable {

	/** default serial id. */
	private static final long serialVersionUID = 1L;

	/** The time (millisols) between when a meal is cooked and when it expires. */
	private static final double SHELF_LIFE = 150D; // note: 100 mSol ~= 2.5 hrs

	// Data members
	private double quality;
	private MarsClock expirationTime;
	// 2014-11-28 Added name
	private String mealName;

	private String producerName;
	private String consumerName;
	private Cooking kitchen;
	private double dryMass;

```

As you can see from above in the `CookedMeal` class. The default `SHELF_LIFE` is 150 millisols, which is ~ 2.5 hours

> Also when they are discarded, why they are discarded is not known, ideally if not being eaten or preserved then it should be turned into some sort of manure or something similar for agriculture.

For now, it's just the developer choice for practice hygiene to either throw away expired meal or packed them into preserved food for portability reasons.

**Comment by mokun** [comment]
In `Cooking` class, we specify the following : 

```

                       // Check if cooked meal has gone bad and has to be thrown out.
                        double quality = meal.getQuality() / 2D + 1D;
                        double num = RandomUtil.getRandomDouble(7 * quality + 1);
                        StringBuilder log = new StringBuilder();
                		
                        if (num < 1) {
                        	if (dryMassPerServing > 0)
                        		Storage.storeAnResource(dryMassPerServing, ResourceUtil.foodWasteID, inv, "::timePassing");                     	

            				log.append("[").append(settlement.getName()).append("] ")
                            		.append(dryMassPerServing)
                            		.append(" kg ")
                            		.append(meal.getName().toLowerCase())
                            		.append(DISCARDED)
                            		.append(getBuilding().getNickName())
                            		.append(".");
            				
                            LogConsolidated.log(logger, Level.INFO, 10000, sourceName, log.toString(), null);

                        } else {
                            // Convert the meal into preserved food.
                            preserveFood();
```

Whether it turns into a preserved food or thrashed truly depends on quality of that meal.

A cook with good cooking skill and good performance level will make good quality meal.
                               		
> Note that the formula we use above to determine the is somewhat arbitrary but it works.

if the quality of the meal is not up to a certain standard (with a little bit of randomness added into it) , then it will turn into `food waste`. 

Yes `food waste` can be treated and used as fertilizer in mars-sim.

**Comment by mokun** [comment]
@shirishag75 , 

BTW, just discover there are times when a lot of people are doing EVA *prior to* the meal time. 

When that happens, the cook would make a lot of `Cooked Meal` and nobody would be eating them. 

What a waste !

So it makes sense to put in some code to track if it's close to eating meal and if it does, people should be somewhat refrained from going out doing EVA-- unless he/she is not hungry at all.

Let me know if you have other ideas and share it here.

**Comment by mokun** [comment]
Closed.
