### ISSUE TITLE
Phase 1, 2, 3 Resupply Missions not loaded by any Settlement Templates

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1172]
**Describe the bug**
- Currently, none of the Phase 1, 2, or 3 Resupply Missions are viewable in Resupply Tool
- Only BiMonthly Delivery and Food Delivery are available 

**Expected and unexpected behavior**
- Should be able to load all Phase 1,2, 3 resupply Mission for expanding the settlement

**Discuss any potential problems**
- Currently, the Phase 1,2, 3 resupply mission for each settlement template need to be customized according to the differences in the initial building layout.
- We need a more organized approach to handle the differences in phase 1,2,3 of each country/sponsor's building layout. 
- Find ways to check for collision between existing building and new incoming building. It should alert player that a site has been reserved for an incoming building, etc.

**Java classes involved**
- `ResupplyUtil`, `SupplyTableModel`, `ResupplyMissionEditingPanel`
- As shown in `setlements.xml`, so far the following settlement templates are in mars-sim: 
```xml
	<settlement-template-list>
		<!-- Settlement template for the Zubrin Mars Direct mission plan. -->
		<!-- See http://www.marssociety.org/home/about/mars-direct for more info. -->
		<!-- default-population: the default population capacity for the template. -->
		<!-- number-of-robots: the default number of robots for the template. -->
		<!-- sponsor: the name of the sponsoring organization for the template. -->
		
		<!-- 3 Phase 0 templates -->
		<template name="Phase 0-BO"/>
		<template name="Phase 0-MS"/>
		<template name="Phase 0-AE"/>
				
		<!-- 8 Phase 1 templates -->
		<template name="Phase 1-BR"/>
		<template name="Phase 1-CN"/>
		<template name="Phase 1-IN"/>
		<template name="Phase 1-MS"/>
		
		<template name="Phase 1-RU"/>
		<template name="Phase 1-SA"/>
		<template name="Phase 1-SX"/>		
		<template name="Phase 1-US"/>
		
		<!-- 9 Phase 2 templates -->		
		<template name="Phase 2-CN"/>	
		<template name="Phase 2-EU"/>
		<template name="Phase 2-IN"/>	
		
		<template name="Phase 2-JP"/>
		<template name="Phase 2-KR"/>
		<template name="Phase 2-MS"/>
		
		<template name="Phase 2-RU"/>
		<template name="Phase 2-SX"/>
		<template name="Phase 2-US"/>
		
		<!-- 6 Phase 3 templates -->	
		<template name="Phase 3-CN"/>
		<template name="Phase 3-IN"/>
		<template name="Phase 3-MS"/>
			
		<template name="Phase 3-RU"/>
		<template name="Phase 3-SX"/>
		<template name="Phase 3-US"/>
		
		<!-- 1 Phase 4 templates -->			
		<template name="Alpha Base"/>
		
		<!-- 1 hub template -->			
		<template name="Hub Base"/>
		
		<!-- 1 trading outpost template -->			
		<template name="Trading Outpost"/>
	
		<!-- 1 mining outpost template -->		
		<template name="Mining Outpost"/>	
																				
	</settlement-template-list>
```

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/27dafacc-b930-41fb-89d1-ae11e10361e0)

**Specifications**
- pre 3.7.0 build 9077

**Additional context**
- Clicking on the `New Mission` button in Resupply Tool would generate an exception in *JSpinner solsUntilCB* in ResupplyMissionEditingPanel

**Comment by mokun** [comment]
@bevans2000 

Can we abandon those pre-planned phase 1,2,3 resupply missions ? 

Also, for instance, we add the Fishery or Algae Pond to a sponsor template, then its corresponding phase 1,2,3 template would need to change.

Too much work to keep rewriting the phase 1,2,3 mission for each sponsor.

So it may actually be a good thing that we are free now to come up with a better way of expanding the settlement via construction missions.

**Comment by bevans2000** [comment]
Sure, no problem. Let's close this then.

**Comment by bevans2000** [comment]
I'm going to resolve this by taking out the Buildings from the Resupply mission; then the Settlements can still get the Equipment & Parts supplies as well as new Persons & Robots.
The principle is these mission come on bigger ships compared to the Food resupplies which might be automated.
