### ISSUE TITLE
Too many local digging tasks are created

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1189]
**Describe the bug**
Still seeing too many local digging tasks created in a Settlement. There appears to be a mixture of directly assigned plus individually chosen ones.
![Screenshot 2023-12-31 112936](https://github.com/mars-sim/mars-sim/assets/20720166/a12c0fd6-cfca-4efd-aa00-780341e782cd)
 
Secondly, the pending task is not always cleared after being assigned which means there is double assignment occurring.

**Comment by bevans2000** [comment]
I want to try and fix this by converting the 2 DigLocal Tasks to SettlementTasks and calculate the demand only once. The occurrence property would reflect how many EVA operations the current Settlement can support. This would allow a central way to ensure that not too many Persons are doing EVA. In addition drop the scheduled starting of Dig tasks.
The modifier for a Person would use a Shift percentage completed to control the rating scores, e.g. if less than X% completed a score is created.

**Comment by mokun** [comment]
We could limit a person doing Digging Local to a certain # of millisols per sol.

On top of that, we could create a param to dictate the total millisols of work per sol. 

It would vary from settlement to settlement and player should be able to change this param.

Say, for a 8-person settlement, if there's a lot of manufacturing needs or construction needs, then this settlement-wide param would go up from, say, 500 millisols to 700 millsols.

But we can first capture how much digging regolith on average is done now for each settlement template phase to gauge the initial values.

Then we go from there. Do you like this as a possible solution ?

**Comment by bevans2000** [comment]
I think it can be simpler of calculating the score of the Settlement demand for regoloth/ice. Using the quantity attribute so it accounts for how many EVA'S are in progress now. Here we define a %age of how many of the Citizens can do EVAs. This will stop everyone rushing off to Dig at the same time.
Then the Person modifer can be based to their shift and how much EVA they have done today

**Comment by mokun** [comment]
> I think it can be simpler of calculating the score of the Settlement demand for regoloth/ice

computeRegolithProbability() in Settlement calculates the so-called probability value or whatever you would like to call it.

**Comment by mokun** [comment]
> Using the quantity attribute so it accounts for how many EVA'S are in progress now. Here we define a %age of how many of the Citizens can do EVAs. This will stop everyone rushing off to Dig at the same time.

Is the goal being able to spread out people over a span of time for doing EVA, instead of having everyone to jump into it at the beginning of the sol ?

If that's the case, we only have to group them up. Let say having 4 people for each EVA team. 

We could delay the start time of each group by, say, 50 millisols, if there's only one EVA airlock.

Obviously, if there's more than one EVA airlocks, we don't need this restriction.

**Comment by bevans2000** [comment]
I am going to use a reworked generic version of the Settlement Preferences to limit the number of active Local Dig tasks.
This rework will cover #1021 and #773.

**Comment by mokun** [comment]
Sure !

I'm going to come up with an EVA Port that would allow one or two person to do ingress or egress. No more getting stuck in an airlock !

**Comment by bevans2000** [comment]
Good plan. We need to come up with a way of design Unit tests to check the logic outside the simulation. It's a big problem we have trying to fix things in a full simulation.
Eventually with the generic Preferences logic I want to expand it to replace the Person Favorite &Preferences. I want it to become a generic way a user can customise the Simulation behaviour.

**Comment by bevans2000** [comment]
My approach to this is to convert it to a ```SettlementTask``` so the demand for the Settlement is calculated once. This will be reflected in the score of the ```SettlementTask``` and the demand attribute will be the number of digs that can be supported, i.e. the value from the Parameter class minus the number currently active.
The Person refinement of the ```SettlementTask``` into a Person ```TaskJob``` will take into account how far through their Shift they are so that EVAs are done towards the start of a Shift.

**Comment by mokun** [comment]
Good idea. Yes it is a waste to have everyone calculating if he should go out... Let's implement this approach 🙂

**Comment by bevans2000** [comment]
It's my next thing on my stack. Work is taking a lot of my time currently so I'll fit it in when I can.
