### ISSUE TITLE
Excessive CPU on doAreasCollide

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1192]
**Describe the bug**
- During the day, settlers go outside. The most CPU intensive ( 47.8 + 21% ~70%) or punishing task turns out to be checking for collision when the task `WalkOutside` is enacted.  

**Expected and unexpected behavior**
- It's too expensive to check if two areas are collided when a person is walking outside. 
- It's even possible for a person to climb up a building. So collision checking is not needed.
- It only needs to look at the x/y center location of a person with other objects in the Settlement map.
- A person is a dot and occupies negligible area on the settlement map. It's not like a rover that has a much large footprint.

**Java classes involved**
- LocalAreaUtil, WalkOutside

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/d9d2f016-6b06-47c3-b97a-16cd7b02dae6)

**Specifications**
- post 3.7.0 build 9172

**Additional context**
- Add any other context about the problem here.

**Comment by mokun** [comment]
@bevans2000 

What do you make of this ? 

Can you by any chance fire up visualvm to see if there's anything out of ordinary that eat up CPU ?

**Comment by bevans2000** [comment]
Ok, probably not u til the weekend as busy with work.

**Comment by mokun** [comment]
@bevans2000 

I wonder if defining an exact spot for each settlement to dig local regolith / ice is better.

This way, we may be able to cache that spot and its results when checking for collisions by  repeatedly using the A* path planning algorithm on cached locations.

**Comment by bevans2000** [comment]
I don't think this will help this problem but from a logic prese give it make sense. 
Write some Unit tests to test the path calculations

**Comment by mokun** [comment]
`WalkOutside`, plus all other walking tasks, are called to be a subtask only.

Does a time pulse get sent to a subtask the same way as to a main task ? 

Also, it doesn't seem to see the progression of time on anything one performing a walking task in the last couple version of mars-sim anymore.

It's possible subtasks used to be handled more carefully in terms of time usage but not now.

So the question is, how do we modify `WalkOutside` to ensure that a subtask like that is being regulated by our time pulse architecture again ?

**Comment by bevans2000** [comment]
Well when I redesigned the rask execution a long time ago subtasks were treated the same and would have seen the increasing time via a pulse. But there have been other changes like the standard pulse width that you overlaid on top.

**Comment by mokun** [comment]
This seems to be how the A* pathfinding search algorithm is implemented. 

No idea how long the problem has been there since no one has touched it for a while.

To be certain, we could benchmark old version such as v3.1.0 to see if it also causes the time spile.

**Comment by mokun** [comment]
Closing this for now.

**Comment by mokun** [comment]
@bevans2000 

This issue is closely related to https://github.com/mars-sim/mars-sim/issues/1611. 

In the past, I placed a limit on the recursive call of finding non-colliding area / non-intersecting line. See https://github.com/mars-sim/mars-sim/pull/1207.

May be we can get use weighted probability instead of recursion.
