### ISSUE TITLE
Click open the population button on the Population tab for one specific settlement

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#12]
Created: 2014-12-04
Migrated from https://sourceforge.net/p/mars-sim/tickets/22/

I'm getting constant IllegalStateException Invalid index 25 for 25 rows, as well as Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException.

It began when I click on the button on the Population tab to open tab for one settlement's population in monitor tool. I rarely use this button until now. Fortunately, the code caught the exception and didn't crash.

It points to UnitTableModel.java's getUnit(int index) on line 230:

> if(index > (getRowCount()-1)) throw new IllegalStateException("Invalid index " + index + " for " + getRowCount() + " rows");

When I click the button to close this newly created tab in the monitor tool, the exception msg disappear.

**Comment by larsnaesbye** [comment]
![open tab for only one settlement s population in monitor tool](https://cloud.githubusercontent.com/assets/7767079/22947486/782d4d18-f2fb-11e6-88fd-6031eba4cd71.png)
[IllegalStateException Invalid index.txt](https://github.com/mars-sim/mars-sim/files/775213/IllegalStateException.Invalid.index.txt)

**Comment by larsnaesbye** [comment]
![two new tabs opened in monitor tool one for each settlement](https://cloud.githubusercontent.com/assets/7767079/22947500/8a5dbf54-f2fb-11e6-86a2-4024b8c7fb4b.png)

**Comment by mokun** [comment]
I recalled having fixed this issue in a commit way back though I don't remember what was done to it.

As of r3863, there is no IllegalStateException whenever I single or double click on a person or click on the person search button of the right. The Info Window of the person of interest will pop up.

**Comment by mokun** [comment]
Just tested it. As of r3863, there is no IllegalStateException whenever I single or double click on a person or click on the person search button of the right. The Info Window of the person of interest will pop up.
