### ISSUE TITLE
Error on copy-rename-maven-plugin

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1219]
**Describe the bug**
- `copy-rename-maven-plugin` is an very old maven plugin
- It throws error on line 77's <execution> tag in Eclipse IDE 2023-12 version

**Discuss any potential problems you have and have not ruled out**
- Is it an alternative plug-in ?

**Java classes involved**
- mars-sim-headless's pm.xml
- mars-sim-main's pm.xml

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/a662848d-e6e4-434a-a4f0-ff6e99099d11)

**Stacktrace**
```xml
			<!-- Rename create JAR to a constant name -->
			<plugin>
                <groupId>com.coderplus.maven.plugins</groupId>
                <artifactId>copy-rename-maven-plugin</artifactId>
                <version>1.0.1</version>
                <executions>
                    <execution>
                        <id>copy-file</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <sourceFile>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</sourceFile>
    						<destinationFile>${project.build.directory}/${target.name}.jar</destinationFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Specifications**
- post 3.7.0 build 9227

**Comment by bevans2000** [comment]
This is history in #1072

**Comment by mokun** [comment]
> This is history in https://github.com/mars-sim/mars-sim/issues/1072

But we haven't started refining it yet.

**Comment by bevans2000** [comment]
The copy will be removed in #1072
