### ISSUE TITLE
Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#122]
Comments on this can be seen on https://github.com/google/guice/issues/1133 and the latest comment indicates it solves the issue by adding couple of dependencies 

https://github.com/google/guice/issues/1133#issuecomment-436458691

I do not know whether it will be useful for us or not, hence sharing the link in the hopes that both of you comment and see if this is something desirable.

**Comment by Urwumpe** [comment]
This sounds like a JDK11 issue with a library accessing internal APIs of  module. Can you fix it by adding --add-open module:package to the java VM command line?

**Comment by mokun** [comment]
Fixed. Closing it.
