### ISSUE TITLE
The Death of Edgar Crisostomo 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#124]
First of all, IIUC the file-size was not supposed to grow over 6 mb but evidently has grown to be 23 mb big. 

See
```
~/.mars-sim/saved$ ls -lh default.sim 
-rw-r--r-- 1 shirish shirish 23M Nov  9 23:49 default.sim
```
For almost 7-8 days Edgar Crisostomo had insufficient oxygen and then died. 

Gave partial output at https://paste.debian.net/1051127/

The insufficient oxygen started at sol 44 . 

He dies on sol 51 - 
```

2018-11-09T22:37:50.4 (Severe) [x32] PhysicalCondition : [Dust Sprite] Edgar Crisostomo has insufficient oxygen.
2018-11-09T22:37:53.8 (Info) HealthProblem : Edgar Crisostomo is suffering from High Fatigue Collapse
2018-11-09T22:37:53.8 (Severe) DeathInfo : Edgar Crisostomo passed away in 0.0° N 0.0° W
2018-11-09T22:37:53.8 (Severe) PhysicalCondition :  A post-mortem examination was ordered on Edgar Crisostomo. Cause of death : high fatigue collapse
2018-11-09T22:40:15.6 (Info) Weather : [Plymouth Base] On Sol 52, Dust Devil-1 (size 9 with windspeed 11.6 m/s) was sighted.
2018-11-09T22:40:15.6 (Info) UnitManager :  - - - - - - - - - - - - Sol 52 - - - - - - - - - - - - 
```

https://anonfile.com/F1y4M3kebc/default_sim

Unfortunately, during his health problems, there is no way to know which base he was from the above. 

Fortunately was able to pinpoint the same from the roster - 

```
Connected with Alpha Base > ​people

You : Who are the settlers ? 
Alpha Base : According to the Mars Registry,

  -----------------------
          Status
  -----------------------
    Registered : 18
        Indoor : 19
       Outdoor : 0
      Deceased : 6

  -----------------------
          Roster
  -----------------------

   A. Indoor 
  -----------
 (1). Adelina Shaneyfelt     (2). Allison Nowakowski     (3). Bill Hensley
 (4). Brian Cody             (5). Don Allen              (6). Evelyn Clinton
 (7). Isabella Carrol        (8). Izu Ishizuy            (9). Jeff Teplin
(10). John McGowan          (11). Kamrabh Purati        (12). Karen Neder
(13). Kisha Gallina         (14). Lars Næsbye           (15). Loretta Thomas
(16). Manny Kung            (17). Matilde Ewton         (18). Ralph Radske
(19). Robert Laloggia

   B. Outdoor 
  ------------
    None

  C. Deceased 
  -------------
 (1). Chamal Perera          (2). Edgar Crisostomo       (3). Evelyn Garcia
 (4). Karen Neder            (5). Ray Kerchoff           (6). Sandi Russett
```

Unfortunately can't tell from the logs, and the data is incoherent to make sense as to what chain of events led to his death. 

https://paste.debian.net/1051132/

From what I could recover or sense it seems that he embarked with his crew-mates on an ill-fated aerology field trip, got caught in a dust-storm and everybody who was with him died. A rescue mission was attempted but didn't happen as the EVA suits were not good enough :(

Java 11 
Debian testing 

Mars -sim build - r4530_headless_java9

**Comment by mokun** [comment]
When it comes to documenting what happen, in GUI mode, we have what's called `Monitor Tool`. 

In `Monitor Tool`'s Event tab, it records a list of `events` ever happened and/or fixed.

There are 6 types of events : 
1. malfunctions 
2. medical
3. mission
4. task (not recorded)
5. transport
6. hazard

I suppose I can port the display of events to the console interface so that players can do their own accident investigation.

**Comment by mokun** [comment]
I just created this new [Historical Events](https://github.com/mars-sim/mars-sim/wiki/Historical-Events) wiki page.

**Comment by mokun** [comment]
> the file-size was not supposed to grow over 6 mb but evidently has grown to be 23 mb big.

On Sol 52, the file size should be about 1.6 MB in my machine.

Can you double check inside the directory `\[User]\.mars-sim\autosave\` ?

**Comment by shirishag75** [comment]
I did that, did you download and see https://anonfile.com/F1y4M3kebc/default_sim 

```
~/.mars-sim/saved$ ls -lh
total 113M
-rw-r--r-- 1 shirish shirish   0 Nov 10 00:18 default.sim
-rw-r--r-- 1 shirish shirish 24M Nov 10 00:18 previous.sim
-rw-r--r-- 1 shirish shirish 90M Nov 10 00:18 temp
```

**Comment by mokun** [comment]
how many sols did you last see on that default.sim or previous.sim ?

**Comment by mokun** [comment]
I've tried loading your default.sim but it doesn't work.

> 2018-11-09T22:59:13.0 (Info) Simulation : Attempting to load the simulation from C:\Users\mkhelios\.mars-sim\saved\default.sim
> 2018-11-09T22:59:17.1 (Severe) Simulation : Quitting mars-sim. I/O error when decompressing C:\Users\mkhelios\.mars-sim\saved\default.sim : org.mars_sim.msp.core.malfunction.MalfunctionConfig$RepairPart; local class incompatible: stream classdesc serialVersionUID = 4360723077045020292, local class serialVersionUID = 6284210254096428308
> 

It encountered an I/O error. It is so large in size. How long have you been running this simulation ?

I'll refine the loading process and display more pertinent info regarding the saved sim for debugging purposes in near future.

**Comment by mokun** [comment]
```
2018-11-10T12:52:38.3 (Info) Simulation : This sim file was made in build 4530 24.3665 MB)
2018-11-10T12:52:38.3 (Info) Simulation : Proceed to loading the saved sim.
2018-11-10T12:52:38.3 (Info) Simulation : Last Saved Martian Date/Time : 0000-501.607
```

The word `(size : ___ MB)` was incomplete.
Also, the `Last Saved Martian Date/Time : 0000-501.607` was invalid.

**Comment by mokun** [comment]
If it's an I/O error, it's very possible that one or more exception have been thrown when you are running the sim. As you try to save the sim, the `default.sim` cannot be properly formatted because some objects that was supposed to be serialized were missing. So the saved sim was corrupted.

**Comment by mokun** [comment]
I don't know why both default.sim and previous.sim were so large in size. 

It's possible that xz compression did not work.

It can typically give you a compression ratio of between 1:10 and 1:15.

**Comment by mokun** [comment]
I/O error occurs in user's machine and is highly unpredictable. 

In recent build, I've increased the compression ratio one level but at the expense of using more memory and can potentially increase the chance of file corruption. 

Once we switch over to JSON serialization, the file size should go down dramatically and resolve the concern of this thread.

**Comment by mokun** [comment]
[r4570](https://github.com/mars-sim/mars-sim/commit/224914bd5611b56b1fd7c2298e08d80ab97815c4) above remove the extra disk I/O load error when saving and loading from a saved sim. 

The XZ compression API did not come with enough Java examples but now we've finally figured out how to make the full use of the RAM to create the temp file prior to (de)serialization :D 

Closing this now.
