### ISSUE TITLE
Clean up Maven modules

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1241]
**Is your feature request related to a problem? Please describe.**
The Maven build is quite large using multiple modules and plugins. This can cause problems to IDE loading and increases the build time.

**Describe the goal(s) you have in mind**
The goals are twofold. Firstly reduced the number of Maven modules to clean-up the dependency hierarchy and simplify the build. The results will be:

- core - Combined the source from mapdata, core & tools. There is no point keeping these separate as they are always used together
- ui - Combines main & ui modules. Dependents upon core, console to create an executable.
- tools - Stays separate but now only has code for tools that are not needed for the main simulation, e.g. HTML generator
- main & mapdata are removed

The dist module will be updated to select the Swing jar file from ui instead of the main module.
The cod will not be repackaged but just moved using Git command to preserve the history.

Secondly, drop the unused plugins to make the build smaller. There is no Kotlin code anywhere so remove this plugin. Spotbugs is not needed as we already use SonarQube on key builds.

**Comment by mokun** [comment]
Will this change supports the future always online client and server architecture ?

**Comment by bevans2000** [comment]
Yes. They would become s new module
