### ISSUE TITLE
Find a html 5.1 compliant or Markdown inline browser

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1247]
**Is your feature request related to a problem? Please describe.**
- The Help Browser (based on Swing) is only html 4.2 compliant.
- The html pages lack consistent and nice formatting.

**Describe the rationale**
- Enable easy editing of html pages found in mars-sim-ui's resources folder by creating a custom template.

**Describe the goal(s) you have in mind**
- Use html templates out there to give html help pages a facelift.
- Embed pictures in those html help pages.
- Apply colors for tables in resource and manufacturing processes and food productions 
- Create custom templates.

**Describe the solution you desire to see**
- Adopt a html 5.1-compliant browser and embed pictures.
- Or switch to markdown for easy editing.

**Specifications**
- post 3.7.1 build 9320

**Comment by bevans2000** [comment]
@mokun here's an idea.Why have an inline browser at all? Why don't we just use the default browser to render the help pages?
We would need to unpack the help out of the jar into real files but that's not difficult. Also,we could generated the config help files instead of packing them in to the package.
I have been working in the styling a lot using CSS classes.

**Comment by mokun** [comment]
> Why have an inline browser at all? Why don't we just use the default browser to render the help pages?

We don't have to bundle with an *inline browser* if we don't want to give players to more than a sentence of instruction/explanation.

To me, I would like to give players *inline help* on each important UI control that needs some explanations.

**Comment by bevans2000** [comment]
So inline help is very different from a manual. I see a problem the current approach has is there are 800+ files bundled in the jar.
We could still have the current browser but extract the files to the file system. 
Also the current inline browser does not seem to support a href that references id, e.g. bookmarks.

**Comment by mokun** [comment]
> Also the current inline browser does not seem to support a href that references id, e.g. bookmarks.

Right. Swing comes with JEditorPane for viewing html. Guess it's only 3.2 html compliant.

So are we going to replace it with a better viewer under Swing ? Or switching it to JavaFX ?

https://stackoverflow.com/questions/2438201/pure-java-html-viewer-renderer-for-use-in-a-scrollable-pane

**Comment by bevans2000** [comment]
I'm not interested in JavaFX at the moment.
My next goal is to avoid bundling the generated files by extracting the to the filesystem
