### ISSUE TITLE
Severe message when running UnitTests

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1259]
**Describe the bug**
When running the UnitTests there are numerous cases of a SEVERE message relating to an unknown resource. It does not appear to impact the UnitTests.
But the message is coming when parsing the manufacturing.xml

```
Feb 17, 2024 10:07:02 AM com.mars_sim.core.manufacture.ManufactureConfig parseInputResources
SEVERE: polystryrene shows up in manufacturing.xml but doesn't exist in resources.xml.
```

**Expected and unexpected behavior**
If a named resource cannot be found in the configuration files then that that should be a fatal problem not a message. I suspect there is a try/catch in the configuration code that is trapping this problem.
Either the manufacturing or resource configuration files are incorrect.
There should be a UnitTest for ManufacuturingConfig to check for such problems.

**Comment by mokun** [comment]
Oh it's a typo. Fixing it now.
