### ISSUE TITLE
Improve the HelpGenerator

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1260]
**Is your feature request related to a problem? Please describe.**
The current help generator resides inside the UI module and depends on some UI code elements. This means it is packaged with the main deployment even though it is a development tool

The style and content of the HTML pages are hard-coded within the large complex code base of the generator making it difficult to change style of format. See #1247 

**Describe the goal(s) you have in mind**
Move the help generator to the tools module, see #1241. This would stop it being distributed and help reduce the deployment size. In addition, break the dependency with the UI code base.

The generation should be re-written to use a templating approach instead of HTMNL fragments within the code.  [Mustache](https://mustache.github.io/) would be the perfect answer. The generator would be responsible for identifying the entities to documents and run these against a specific template to generate the HTML. 
Style and layout is the responsibility of the templates and can be maintained more easily.

In addition; there can be multiple template sets for example;

- Inline help format, as is now
- Web page format that could be uploaded into the external mars-sim web site; see #834 
- MarkDown format to be uploaded into the Wiki or replace the bundled help

The generator could be used multiple times to create multiple documentation sets.

**Comment by mokun** [comment]
Yes it's simply too cumbersome to generate a new set of html pages whenever we make a small change in a process. 

Let's rework HelpGenerator using this runtime html generation approach. 

BTW, we did not include `meals.xml` previously. If we are to redo HelpGenerator, we'll need to add that.

In terms of formatting, I'd love to have a zebra table with white grid lines.

**Comment by mokun** [comment]
> My thoughts are it's still generated HTML because it makes sense that doing it at runtime

But we don't want to pre-generate them for each new release anymore, right ?

**Comment by bevans2000** [comment]
If we want to host them elsewhere like on the wiki then they have to be generated.
I've made good progress on the replacement generator and it is a lot simpler than the existing one.

**Comment by bevans2000** [comment]
@mokun during this work I've noticed that the names of the food processes have a lot of redundant words. Many are called Make X from Y or Bake A from B. 
Why not drop the verb part and focus on the ingredients and product?

**Comment by mokun** [comment]
Do we need to use a process's title to create a sentence now or in near future ?

May be the verb still has value to make it a sentence flows better. 

But if you want consistency, you can come up with a scheme of your choice.

**Comment by mokun** [comment]
Q: will it fix the need to manually copy the newly created set of html from the source folder to the target folder ?

**Comment by bevans2000** [comment]
> Q: will it fix the need to manually copy the newly created set of html from the source folder to the target folder ?

The way the system has been built means the html files have to be committed to GitHub. But we can get it to write directly into the correct location.
Then, if you want we can create a GitFlow Action to run the generator and do the commit. But it's not difficult to run the tool towards the end of the release cycle

**Comment by bevans2000** [comment]
I've realised it would be easy to make the new generator support on the fly help creation as well as static but how would you want to trigger it?

**Comment by bevans2000** [comment]
@mokun the new generator is much better than one old one. We can easily add in extra configuration item like Buildings and Settle Templates. In addition we can create other template sets to support Markdown and the website.

**Comment by mokun** [comment]
> Then, if you want we can create a GitFlow Action to run the generator and do the commit. But it's not difficult to run the tool towards the end of the release cycle

So now in conclusion, do we still need to run it manually ? In GitFlow Action ?

**Comment by mokun** [comment]
So in terms of Cargo Rover, somehow it does know removing the carriage return and tabs between in the description text of a xml ?

![image](https://github.com/mars-sim/mars-sim/assets/1168584/e49b338f-0bd6-497d-9e6c-683344c1d5b5)

But for Explorer Rover, it can remove carriage return and tabs. 

Why are the two rendered differently ?

**Comment by bevans2000** [comment]
Just use the help browser from the Swing UI and the html files are generated in a temporary directory.
Committing them to GitHub is not correct. They make the repo too large. This works, I've been using it for ages. yes there might be a few formatting issues but we can fix them.
This approach is much better and flexible. Looks how quickly I added the Complaints and Treatment pages

**Comment by mokun** [comment]
Also for Transport Rover,

![image](https://github.com/mars-sim/mars-sim/assets/1168584/49421668-f6f9-48c3-9c43-54048199fdbb)

**Comment by bevans2000** [comment]
Ok I will look into it but this approach is significantly better that what was there before

**Comment by mokun** [comment]
> Ok I will look into it but this approach is significantly better that what was there before

Agreed!
