### ISSUE TITLE
Create a seperate Settlement Template Configuration class

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1290]
**Is your feature request related to a problem? Please describe.**
SettlementConfig class play 3 roles:

1. Global configurations for Settlement, e.g. Shifts, Group Activities
2. Repository for SettlementTemplates using the existing UserConfiguration pattern
3. Holds FunctionSpec extra properties, e.g. ScienceLevel for a RESEARCH function.

This make the class very big and has a mixture of logic. Plus SettlementTemplates are transient and only needed when creating Settlements.

**Describe the goal(s) you have in mind**
Separate the Settlement template logic out into a new class called ```SettlementTemplateConfg```. This will focus solely on loading and saving Settlement Templates. 
In addition it will ensure that any FunctionSpec properties are solely within the template and not in the main SettlementConfiguration. The existing FunctionSpec will be subclassed for the Function that need extra configuration properties.

**Comment by mokun** [comment]
> Separate the Settlement template logic out into a new class called SettlementTemplateConfg. This will focus solely on loading and saving Settlement Templates.

Sure. Good idea to make it simple.

**Comment by bevans2000** [comment]
@muybien3433 this is a good one to understand how the configurations work
