### ISSUE TITLE
how to find info. about deceased ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#131]
If we have Deceased person's name, there should be some info. about them - 
```

Connected with Alpha Base > ​people

You : Who are the settlers ? 
Alpha Base : According to the Mars Registry,

  -----------------------
          Status
  -----------------------
    Registered : 23
        Indoor : 22
       Outdoor : 0
      Deceased : 1

  -----------------------
          Roster
  -----------------------

  A. Indoor 
  -----------
 (1). Anthony Holmgren       (2). Brian Cody             (3). Dan Folker
 (4). David Kern             (5). Dawn Tucker            (6). Dushan Novakovich
 (7). Eddie Hintz            (8). Ellie Rochel           (9). Elmer Brow
(10). Frank Crossman        (11). Hartmut Prochaska     (12). Izu Ishizuy
(13). Janice Garver         (14). Jennifer Hare         (15). Kendra Hensley
(16). Mike Halder           (17). Roy Sweeny            (18). Sasha Sarmini
(19). Scott Kaszuba         (20). Suzan Robideau        (21). Tracy Kilmar
(22). Troy Lane

  B. Outdoor 
  ------------
    None

  C. Deceased 
  -------------
 (1). Loretta Thomas
```

There doesn't seem to be a way to know what did Loretta Thomas die of , at least not in MarsNet . 

It would be nice to have two features - 

a. Deceased 

Just asking about Deceased should give info. about - 

a. All the deceased from all the bases and date of death . 

b. Deceased Loretta Thomas 

b. This will give the nature of the death, the cause of it, the date on which it occurred and the doctor who did the postmortem and any last-wishes, how the body was disposed e.g. cremated and ashes sent to earth or buried on Mars or used as compost. Any last wishes of the settler.

**Comment by mokun** [comment]
> This will give the nature of the death, the cause of it, the date on which it occurred and the doctor who did the postmortem and any last-wishes, 

Yes I'll make the info available in the console.

> how the body was disposed e.g. cremated and ashes sent to earth or buried on Mars or used as compost. 

For now, it's just getting buried outside the settlement. don't have the technology to be shipped back to Earth or space yet :D 

Question: what determines the wish to be buried or cremated ?

> Any last wishes of the settler.

Do you have any examples ?

**Comment by shirishag75** [comment]
we still need a way to know when a person died, what symptomatology did s/he have and did it have any similarities to others. Within a year 8 people have died on Alpha Base which is a high cost and I can't make out the reason. 

```

  E. Deceased
  -----------
 (1). Charla Padmore         (2). Colleen Lane           (3). Hizue Miyo
 (4). James Barnard          (5). Marina Plavnick        (6). Matilde Ewton
 (7). Michael Zummo          (8). Natalie Ain
```

**Comment by shirishag75** [comment]
I could not type in the name of the deceased person.

**Comment by mokun** [comment]
This [build](https://github.com/mars-sim/mars-sim/commit/178e795c8eb13fa6084728462fb9efa42837a76f) indeed added the display of a preliminary death report on a deceased person.

**Comment by shirishag75** [comment]
but how to do that ? If I cannot type the deceased person's name, I have no idea how to get that info.  Let me try a new build when you have fixed the recent bug and then I can see if it has been fixed.

**Comment by mokun** [comment]
Oh I know what happened. So far, it only returns a collection of buried people. 

If someone just died and had not gone through the postmortem exam, he cannot be buried. 

In that case, he's in a limbo and player cannot find his name in MarsNet.

Fixing it now.

**Comment by shirishag75** [comment]
Interesting, I used quit and I didn't get the message that you got with /q . I'll need to update it once again I guess.

**Comment by mokun** [comment]
>  Earth time to as well, just to know or calculate as to how many days was he alive either in Earth Days or Martian Sols

Sure. Good idea !

**Comment by shirishag75** [comment]
Somewhat of a side-note first . When a person dies, there are lot of useful nutrients released by the body.  For e.g. see  https://mosaicscience.com/story/what-happens-after-you-die/ . We could have as a rule cremate the body and use it nutrients released to grow plants thus completing the circle of life. This probably should be a rule or at least a strong opinion in any mars or any other world settlement program. 

As far as design is concerned, the best would be not to have the count at all either in outside or inside but as dead only. The reason is all the resources that would need to be made or taken would be for living people and calculations for doing those should be easier. People who are inside as well as people who are outside should be considered for everything from food, water, air, entertainment etc.  whatever else is needed to have normal functioning brain and personality.

**Comment by mokun** [comment]
@coffee

This recent [discussion](https://github.com/mars-sim/mars-sim/discussions/324) also talked about the death info.

I'll close this now. It's done.
