### ISSUE TITLE
Tissue growth never works

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1312]
**Describe the bug**
In creating the new UnitTests for ```TendGreenhouse``` it has shown that there are some problems in the existing sampling logic and how tissues are managed. Tissue samples are never added to the incubator list nor the inspection map; both are close maps that never get updated. This logic is further only enabled if the Building has a Research capability.

Secondly, all the logic of tissue growth is within the ``Research``` class but it has nothing to do with research nor the Research Tasks.  This creates the contradiction that a lab in a Vehicle can support growing tissues !!!!
In addition, someone could use a Greenhouse to do some complex scientific research in the current model.

**Solution**
The tissue culture logic should be moved to a new dedicated class and revisited. A Farming function would have an instance of the tissue  management if the Greenhouse supports it;  not be dependent upon the parent Building. This would remove the need for Greenhouse building to have a Research function.
This new tissue management class would handle the incubation and inspection of tissue samples allowing the existing code to be removed from the Research class.
The Farming function would take a new boolean property in the building.xml called 'growTissue'. If true a tissue management object is created as part of the Farming constructor and hence support the Sampling phase.

**Comment by mokun** [comment]
I assume it used to work at least in the past because I traced the log statements to ensure it did. 

However, we've made changes over time. In particular, the use of research lab to incubate the tissues is not that refined.

Also, tending the crop in greenhouse has too many subtasks now.

So it's possible that the tissue culture has since quit working the way it was supposed to.

**Comment by bevans2000** [comment]
Yes I'm sure it was working. Let's just revisit it when we get time

**Comment by mokun** [comment]
We could make tissue culture a "generic"  project task as a greenhouse research.

This way, we could add other collaborateive tasks that other researcher can do. 

For instance, genetic engineering project would certainly thrive in future Mars colonies. 

We may create models for researchers to enhance the gene of one crop by extracting the gene of another crop to  adapt better to environmental factors (such as the amount of light and moisture) to improve crop yield, etc.

**Comment by bevans2000** [comment]
I want to avoid creating a new ```Function``` for it. But we could create a - dedicated Task. Key questions are
- does it need the specialised Research
- it only works with a farming Function
- it is repeated to the Crop growing

In my opinion it is part of the Farming Function

**Comment by mokun** [comment]
> does it need the specialised Research

Yes. The researcher should be a botanist or biologist. In future, we'll appoint a "botanist assistant" to the main researcher.

However, if a settlement doesn't have a botanist/biologist, it'll ask whoever having the highest botanist score.

> it only works with a farming Function

Also, AlgaeFarming and Fishery.

And in future BeeGrowing. 

> it is repeated to the Crop growing

May be we should call it LabWork instead.

**Comment by mokun** [comment]
> We may create models for researchers to enhance the gene of one crop by extracting the gene of another crop to adapt better to environmental factors (such as the amount of light and moisture) to improve crop yield, etc.

@bevans2000 
I have in mind modeling the genetics of a crop. 

Namely, I'd like to keep track of how well each generation of a particular crop will improve or degrade. All the environmental factors could potentially steer the way the genes of the next gen will end up.

The biology and botany science research should enable certain breakthrough in tweaking the genetics of crops as well to be more adaptable to the environmental factors.

All these are a part of the future tissue culture experimentation.

**Comment by bevans2000** [comment]
Interesting idea. That's quite a detailed level of modelling.
It needs to be done on a dedicated branch as it will be a lot of change

**Comment by mokun** [comment]
@bevans2000 

We could make biology/botany lab more useful by growing : 

1. tissue culture for crops
2. nutrient for algae
3. nutrient and weed for fish

At this point, we assume (2) and (3) above are done and grown automatically.

In real world, biologists/botanists would monitor and test the quality of food for algae and fish and grow them in lab environment.

I would advocate a brand new lab task for doing any one of the 3 lab work above, instead of lumping them into the tending task.

**Comment by mokun** [comment]
It also has problem planting new seedlings after harvesting an old crop. Fixing it now.

**Comment by mokun** [comment]
Closing this.
