### ISSUE TITLE
Console timestamp not updated

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1317]
**Describe the bug**
- Console timestamp not updated if just hitting enter

**Expected and unexpected behavior**
- A new timestamp should be provided at the prompt, even if "Invalid value" is entered.

**Java classes involved**
- SwingHandler, MarsTerminal

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/efcb76ae-7b2b-43ec-b3fd-3552096e31fd)

**Specifications**
- pre-3.8.0

**Comment by bevans2000** [comment]
This is an easy fix. I can sort it
