### ISSUE TITLE
Zero work time in Science Tool and Science tab

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1318]
**Describe the bug**
- Zero value in Science Tool's work column when total work is reportedly 75% completed

**Expected and unexpected behavior**
- Work in sols should be reported in "Study Detail" panel.

**Java classes involved**
- StudyDestailPanel, ScientificStudy

**Screenshots**
If "Phase Completed" is 75%, then a lot of work should have been done by the following collaborators but no work time is reported
![image](https://github.com/mars-sim/mars-sim/assets/1168584/8fc4772f-051d-4b4a-bc88-789a1bf099a0)

Hong Kuang shows zero work in Research and Paperwork column
![image](https://github.com/mars-sim/mars-sim/assets/1168584/28c9dac8-7907-4c11-949f-172a03c671be)

**Specifications**
- pre-3.8.0

**Details**
```java
/**
 * A class representing a scientific study.
 */
public class ScientificStudy implements Entity, Temporal, Comparable<ScientificStudy> {
	// POJO holding collaborators effort
	private static final class CollaboratorStats implements Serializable {
		private static final long serialVersionUID = 1L;
		
		double acheivementEarned = 0D;
		double paperWorkTime = 0D;
		double reseachWorkTime = 0D;
		MarsTime lastContribution = null;
		ScienceType contribution;
		
		CollaboratorStats(ScienceType contribution) {
			this.contribution = contribution;
		}
	}
```
- The paperWorkTime and researchWorkTime are always zero.

**Comment by bevans2000** [comment]
I'm pretty sure Collab stats were working. I will check the UnitTests to reproduce it

**Comment by bevans2000** [comment]
@mokun This is not a bug. If you look the Study is in the Invite Collaborators phase so no one can contribute yet.
I have expanded the LabTest Unit Test to check collaborators contribution and it is working fine. I will commit this.
Having said that, there r some minor improvements we can make to the Science Study tab.

**Comment by mokun** [comment]
>  no one can contribute yet.

But why would the `Phase Completed` shows 75% ?

See the screenshot above.

**Comment by mokun** [comment]
When I look through any science studies in Science Tool, I have yet to find anyone having done non-zero work. 

What does Work mean ?

Even in Study Proposal phase, it should accumulate the work spent in sols. So far, it's always zero.

**Comment by bevans2000** [comment]
Because the Invite phase is that much completed. Each phase goes to 100% before advancing

**Comment by mokun** [comment]
Q: why is the first person's Contribution column always blank ?

**Comment by bevans2000** [comment]
No the logic has always been that work is only counted when research is actually being done via a Task
This would be a big change and definitely break the logic on

**Comment by mokun** [comment]
![image](https://github.com/mars-sim/mars-sim/assets/1168584/d4f0ac1f-797d-4407-b723-6a162e247093)

I assume the first person as the lead researcher would do research on a Subject as well, right ?

**Comment by bevans2000** [comment]
Primary researcher has to do the Science of the Study. This is a UI problem I can fix.
