### ISSUE TITLE
Mission vehicles fail to depart settlements; garage vehicle can't be displayed

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1320]
**Describe the bug**
- Vehicles can't depart their settlements for missions

**Expected and unexpected behavior**
- A clear and concise description of what you expected to happen.

**Discuss any potential problems you have and have not ruled out**
- Lately, there have been numerous issues with either a garage vehicle unable to be displayed on a Settlement map with stacktrace showing NPE and/or having excessive calling on finding a new location for the vehicle on the map right after leaving the garage.

**Java classes involved**
- VehicleMaintenance, Vehicle, etc.

**Screenshots**
Too many vehicles unable to depart.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/f69e890d-7d60-46f0-af35-600bf5dc5632)

Desert Fox always parked outside (no garage available in its settlement).
![image](https://github.com/mars-sim/mars-sim/assets/1168584/b7483ba6-9544-44a9-a73b-a87f57bde307)

It was qualified to depart on sol4:999. But it's now sol 12 and still unable to leave the 'Foundation'. 3 of the 4 people are on board.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/bba89c74-dbf6-44bc-86f9-919e6b173064)

Why garage vehicles are not shown in Settlement Map.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/bfddcde8-606a-4e96-b983-1f71cdced8ee)

Both 'Spice Trader' and 'Shooting Star' are shown to be inside the garage. However, they can't be displayed in the garage.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/87253fd1-3e77-4c87-bbba-635263f320b9)

The Unit Window of 'Garage 1' in Heritage does show the two vehicles inside the garage.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/bfe21900-f434-4376-8e8d-2d516a2c62e6)

**Stacktrace**
- None

**Specifications**
- pre-3.8.0

**Additional context**
1. We'll need unit test to verify if garage maintenance works or not
2. Find the causing of getting stuck at the departing phase
3. Why mission vehicles are invisible on the settlement map

**Comment by bevans2000** [comment]
Feels this is 2 problems. The rendering of the vehicle and it not leaving.
You got any stack trace examples?

**Comment by mokun** [comment]
Tomorrow morning I'll run a session on only one settlement and capture the stack trace.

**Comment by mokun** [comment]
I also discovered somehow a person's dot was not drawn when he's inside a vehicle that's parked outside in settlement's vicinity.

Fixing that now.

**Comment by mokun** [comment]
It still fails to depart so far. Vehicle occupants would die of shortage of food.

btw, will the new mission class be adopted soon ? If we start switching over, we don't have to keep fixing old issues having to do with those old class/methods.

**Comment by bevans2000** [comment]
No I don't have much spare time at the moment and am focussing on UnitTests and corrections for Tasks.

**Comment by mokun** [comment]
I look forward to switching over to the new project mission architecture. At least it will be easier to write unit tests under that architecture.

Currently, it doesn't seem like very hard to write a unit test to simulate how well a mission vehicle would do on a field trip. 

And I can see you created two tests (namely, MissionProjectTest and TestDriveMissionTest) so far for the new project mission architecture. 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/66f718c3-7af4-41d9-99fa-5ec080175814)

**Comment by bevans2000** [comment]
Yes these are working fine. The new approach make UnitTest easier.
But before applying further I want to change how we trigger loading and unloading a vehicle and remove the dependency on Vehicle mission. We should use a secondary status on the Vehicle to flag it needs loading or unloading. This will make the Trade and Delivery missions much easier to create, we can have new generic steps of load or unload a vehicle. Removing the current complex logic.
I thought I had already created an issue for this change but cannot find it 😕

**Comment by mokun** [comment]
May be you can find it in your [project](https://github.com/orgs/mars-sim/projects/4) ?

**Comment by mokun** [comment]
The strangest thing is that some missions can be departed while some don't. See snapshot below : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/0b3a1c57-c67e-4b68-b6a9-467810f72721)

**Comment by mokun** [comment]
And it looks like the reason a vehicle can't depart is because the crew haven't boarded the vehicle yet.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/15512fd4-811c-4c7b-b5eb-a55ede97e8d4)

**Comment by mokun** [comment]
For the two of them who were stuck at the waiting spot of the EVA airlock, the task column shows they are quickly flashing/switching between "Walk" and "Performing EVA egress".

So once again this airlock issue re-surface and it has to do with not being able to release an activity spot in front of the inner/interior door and move onto the next spot inside the airlock.

I wonder if incorporating this spot that's right outside the interior door into the EVA Airlock building activity spot would solve the problem or not.

Can you take a look ?

![image](https://github.com/mars-sim/mars-sim/assets/1168584/7aef3250-4b8b-461a-92fd-ade518b0ea11)

**Comment by mokun** [comment]
As a matter of fact, these 4 people are all claiming to be at EVA Airlock.

However, Louise and Saga are the one truly going inside an airlock chamber and preparing to egress.

Oliver and Lena are both stuck at the entrance. They will high fatigue and unable to enter in. 

But again, after the egress task were cancelled, they kept coming back to the airlock to try to egress.

So we've been having this issue for a while. 

This settlement has 12 settlers and one airlock.

When the EVA egress is not well sync-up, we will continue to have these type of issues popping up.

Now it's impacting the departure of a mission vehicle.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/fbb685a4-76be-4486-9a0e-93ce5894839d)

**Comment by mokun** [comment]
Also, if Lena is not EVA fit, it shouldn't be assigned with a "Loading Vehicle" task at all.

```
01-Adir-03:996.176 (Info) AbstractMission [x3] : [Arcadia - Inflatable Greenhouse 1] Lena Meier - Assigned with 'Loading Vehicle by EVA' to replace 'Listening to Music'.
```

**Comment by mokun** [comment]
In Rover class, we have

```java
	/* How long do Worker have to complete departure */
	private static final int DEPARTURE_DURATION = 150;
	private static final int DEPARTURE_PREPARATION = 15;
```

Do they need to change to allow more time for crew members to board ? 

Currently, it's still hard to sync up. When 150 millisols has passed, the vehicle misses the window of opportunity for departing and it's done.

I'm looking at performDepartingFromSettlementPhase(), it's quite complicated and haphazard, you know. 

```
		// Can depart if everyone is on the vehicle or time has run out
		boolean canDepart = isEveryoneInRover();
			
		if (!canDepart && (getPhaseDuration() > DEPARTURE_DURATION)) {
			// Find who has not boarded
			List<Person> ejectedMembers = new ArrayList<>();
			Rover r = getRover();
			for (Worker m : getMembers()) {
				Person p = (Person) m;
				if (!r.isCrewmember(p)) {
					ejectedMembers.add(p);
				}
			}

			// Must have the leader
			if (!ejectedMembers.contains(getStartingPerson())) {
				// Still enough members ? If so eject late arrivals
				if ((getMembers().size() - ejectedMembers.size()) >= 2) {
					for (Person ej : ejectedMembers) {
						logger.info(ej, "Missed the departure and ejected from '" + getName() + "'.");
						removeMember(ej);
						addMissionLog(ej.getName() + " evicted");
					}
					canDepart = true;
				}
			}
		}
	}
```
When a starting member hasn't boarded, what would happen to the mission ? 

It cannot eject the starting member and the departing phase will not end

**Comment by mokun** [comment]
It turns out nearly half the cases, the mission leads could not show up (59 cancelled mission out of 117 missions).

```
01-Adir-16:697.319 (Info) RoverMission : [Heritage - Residential Quarters 2] Georgios Nikolaidis - Mission Lead Georgios Nikolaidis evicted from 'Ice Prospecting 15-001' and mission cancelled.
```

![image](https://github.com/mars-sim/mars-sim/assets/1168584/83a60272-a976-41d0-86d9-1649eef14648)

**Comment by mokun** [comment]
Now, the question is, how are we going to solve this no show issue ?

**Comment by bevans2000** [comment]
I think we need to totally rewrite the airlock logic. It's very complicated and been patched and patched repeatedly.
Let's do this in 3.9

**Comment by mokun** [comment]
> I think we need to totally rewrite the airlock logic.

Agree.

Now, this morning I realize the real reason for this issue.

How do we determine the start time of a mission so far ?

Is it that as soon as the review is 100% completed, it's ready for loading cargo.

So as soon as the loading is done, it's ready for boarding and that's the start time, right ? And this is the problem.

Some settlers would have high fatigue after going in and out of EVA and carrying all those things, especially if there's no garage.

This spontaneity also makes it difficult for everyone to sync up to be ready. 

So should we program the mission start time to be a fixed time instead ?

And what do we do to help a crew member ready right before this fixed time ?

**Comment by mokun** [comment]
Also, can we create a mission schedule ?

I'd like to 'deconflict' starting two missions too closely.

if we can space out the start time between two missions, i'm sure it would help both mission crew member get ready a lot easier than now.

So you can also say that problem we have just discovered about the mission lead is no show is normal.

**Comment by mokun** [comment]
@bevans2000,

What does it take to implement a rudimentary mission schedule that won't overlap the start time of two missions ?

I'd like to 'deconflict' starting two missions too closely within the same period of time.

If we can space out the start time between two missions, it would certainly help crew members from both missions to get ready a lot easier than now as they don't have to fight over EVA egress, especially when there's only one EVA airlock.

So the problem we have just discovered above regarding the no-show mission lead is expected because of the "unscheduled" nature of mission start time.

What can we easily change to make things smoother for the mission lead ?

**Comment by bevans2000** [comment]
Ok so first question is what do we mean by "start"? My definition is once a Mission has been approved, i.e. start of the Loading phase.
So I would do this (this is just thinking, no actual facts. I would create a ScheduleFuture Event that triggers moving a waiting Mission into the LOADING phase. The MissionManager can use the scheduled events to count how many Missions are waiting to start. A new one could be queued to start at a fixed time after the last one.

The sequence would be:

1. Add a new Mission Phase which is WAITING
2. When a Mission completes planning, the MissionManager decides the new phase, e.g. Mission manager is in control of the scheduling. 

- If there is no waiting Missions at the Settlement then the next phase is LOADING
- Otherwise, the next Phase is WAITING and the MissionManager creates a ScheduledEvent for a future time at the Settlement. The created ScheduledEventHandler will directly reference the Mission

3. When the ScheduleEvent occurs, the handler makes the Mission phase set to LOADING. The event does not repeat.

4.

**Comment by mokun** [comment]
It's great to use ` ScheduleFuture Event`.

How about these phases : 

1. PLANNING : schedule the start time
2. LOADING : begin the start time 
3. BOARDING : wait for crew to board
4. DEPARTING : start the depart time

**Comment by mokun** [comment]
Can you show-tell how `Scheduled Events` can be implemented ?

**Comment by bevans2000** [comment]
Have a look at the GroupActivity class. It uses this pattern to change the state based on the time

**Comment by mokun** [comment]
In AbstractVehicleMission, we have : 

```java
	/**
	 * Calls the members to join the mission.
	 * 
	 * @param deadline How many mSols to they have to join; could be zero if no deadline
	 */
	protected void callMembersToMission(int deadline) {
	
		// Set the members' work shift to on-call to get ready
		for (Worker m : getMembers()) {
			if (m instanceof Person person) {
				// If first time this person has been called and there is a limit interrupt them
				if (!person.getShiftSlot().setOnCall(true) && (deadline > 0)) {
					// First call so 
					Task active = person.getTaskManager().getTask();
					if (active instanceof Sleep sp) {
						// Not create but the only way
						sp.setAlarm(deadline);
					}
				}
			}
		}
	}
```

What should be the value of param `deadline` above ?

**Comment by bevans2000** [comment]
Enough time for a person to wake up and get ready. 
Probably we need a logic to stop people doing the current Task as well. But that can wait. You could change it do those asleep get an alarm sooner than the deafline
