### ISSUE TITLE
Create centralised window launcher in UI

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1323]
**Is your feature request related to a problem? Please describe.**
The UnitModel and UnitModelLancher classes are used in the UI to allow double clicking on a table row to show the appropriate UnitWindow via the a facade of the Main desktop class. But the desktop supports launching of any Entity which is wider range of objects.
It would make sense to expand the launcher to cover Entity so Scientific Study and Transport etc can be covered.

**Describe the rationale**
This would centralised reusable logic instead of have a number of point solution throughout the UI code base.

**Describe the solution you have in mind**
Rename the existing classes to reflect Entity being the target. In addition add a static factory method to attach a launcher to a table or list. This would include adding an explanatory tooltip to help the user.

In addition it could replace the bespoke logic in the Monitor Tool.

**Comment by mokun** [comment]
But do we want to keep refining Swing UI ? Or move to Web UI soon ?

**Comment by bevans2000** [comment]
Web UI is a long way off. It's a massive change needing a lot of effort.

**Comment by bevans2000** [comment]
The reality is we have to build a back end server probably using GraphQL and then a web UI. My choice is ReactJS for the front end because it's what I know.
I think we focus of this transition in R4. 
In theory, it could support both webUI and Swing
