### ISSUE TITLE
Change triggering of Vehicle Loading/Unloading

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1324]
**Is your feature request related to a problem? Please describe.**
Vehicle loading & Unloading is directly triggered by a Vehicle Mission. This make the logic complicated and not easy to test in isolation.
In addition the Delivery & Trade Missions have further complication is have to perform a load/unload at the remote Settlement.

**Describe the goal(s) you have in mind**
The loading/unloading of a Vehicle is an activity specific to a vehicle and not a Mission.  It is possible in the future there maybe cases where a Vehicle needs loading outside a mission, for example training.

**Describe the solution you desire to see**
The change is to use a new Secondary Vehicle status to trigger the loading or unloading of a Vehicle. The Meta Task would look for any Vehicle parked at a Settlement that has the appropriate status instead of searching all Mission currently.
The Mission would indirectly trigger the load/unload by setting the appropriate status and wait for the status to be cleared. This significantly simplifies the Trade & Delivery Missions.

**Comment by mokun** [comment]
> possible in the future there maybe cases where a Vehicle needs loading outside a mission, for example training

I like that observation. 

I can think of driving a vehicle to a regolith bin to load and unload regolith. Currently it's difficult to do unless we work out a custom solution.

**Comment by bevans2000** [comment]
Yes good example.

**Comment by mokun** [comment]
Is this done ?
