### ISSUE TITLE
Power generated become very low

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1336]
**Describe the bug**
- There seems to be a power instability happening from time to time. The generated power remain very low. Many buildings shut off their power generation and power load. It has nothing to do with during the night when solar power is not available and battery is drained. 
- Since the generated power of some buildings go down for strange reasons, causing the whole power grid (kW Gen) to be very low. 
- The methane power generators is not intelligent enough to turn on itself to supplement the lack of power and to turn off itself when there's a surplus of power.
- The grid connected batteries are almost always nearly 99% charged up and don't go up and down much.

**Expected and unexpected behavior**
- Power Grid should make power generated (kW Gen) a little bit higher than power used (kW load).
- In case of insufficient power, Power Grid should automatically decide and prioritize which building would go to low power mode to conserve power, especially if that building is not a power producer.

**Screenshots**
- Some buildings go to `power down` mode (yellow status) without good reasons (to be changed to `low power mode` to avoid confusion)
![image](https://github.com/mars-sim/mars-sim/assets/1168584/f617b5c9-7cf3-466a-921c-2ee0b9344497)

- 3 Solar Photovoltaic Arrays go down to `no power` mode (red status) without good reasons while 3 other Solar Photovoltaic Arrays stays at `full power` mode (green status) 
- Note that the `no power` mode has ZERO power load while the `full power` mode has 0.1 kW power drain.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/f82249cf-f264-4b2c-9dc2-348cb694654c)

**Java classes involved**
- PowerGrid

**Specifications**
- pre-3.8.0

**Comment by bevans2000** [comment]
Are you creating Unit Tests for the Power sources?

**Comment by mokun** [comment]
Hmm there's a lack of unit tests for functions. Only 3 unit tests have been written up so far in `com.mars_sim.core.structure.building.function`

![image](https://github.com/mars-sim/mars-sim/assets/1168584/78fc7db0-814d-4fbe-bcd0-b493af0c83f2)

It'll take a while to come up with a unit test for the PowerGrid and each PowerSource.

**Comment by bevans2000** [comment]
It is time well spent on these components

**Comment by mokun** [comment]
Solved.
