### ISSUE TITLE
Wrong building category

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1339]
**Describe the bug**
- Currently, building such as Garage, Astronomy observatory, hallway, etc. are assigned with wrong building category

**Expected and unexpected behavior**
- BuildingConfig should intelligently find the correct category for each building, instead of having to manually assign one in buildings.xml. 

**Java classes involved**
- BuildingConfig, buildings.xml, BuildingCategory 
- In BuildingConfig,
```java
	/**
	 * Derives the category from the types of Functions.
	 * 
	 * @param functions
	 * @return
	 */
	private static BuildingCategory deriveCategory(Set<FunctionType> functions) {

		// Get a set of categories
		Set<BuildingCategory> cats = functions.stream()
						.map(f -> f.getCategory())
						.collect(Collectors.toSet());

		BuildingCategory category = BuildingCategory.CONNECTION;
		if (!cats.isEmpty()) {
			// Find the category with the lowest ordinal as that is the best to represent
			// this set of Functions
			int lowestOrdinal = 999;
			for (BuildingCategory c : cats) {
				if (c.ordinal() < lowestOrdinal) {
					lowestOrdinal = c.ordinal();
					category = c;
				}
			}
		}
		return category;
	}
```

**Screenshots**
- Garage should belong to workshop or vehicle maint category 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/b85a6224-bc31-4d78-92e5-5de6d634b0c7)

- Note that the Living Space category has already been fixed in recent commit
![image](https://github.com/mars-sim/mars-sim/assets/1168584/af1c8f47-aff8-4196-a278-905b97bd02ac)

**Specifications**
- pre-3.8.0

**Additional context**
- The use of ordinal in BuildingCategory doesn't seem to bode well.
- Workshop is NOT a laboratory. It should have a new category called workshop or something else
- In BuildingCategory,
```java
public enum BuildingCategory {

    // Note the order of these enums represent their importance
    COMMAND, 
    COMMUNICATION,
    MEDICAL,
    ERV,
    FARMING, 
    ASTRONOMY,
    LABORATORY, 
    LIVING,
    PROCESSING,
    WORKSHOP,
    VEHICLE,
    STORAGE, 
    EVA,
    CONNECTION,
    POWER;
```
- Note the attribute `category="CONNECTION"` was added recently in buildings.xml to help defining what category a hallway should belong. Before that, it was under LIVING. Now, it's CONNECTION.
```xml
	<!-- A hallway's length is variable and determined in templates or during construction. -->
	<building type="Hallway" width="2.0" length="-1.0" north-south-alignment="length" 
			construction="SEMI_SOLID" base-level="0"
			wear-lifetime="3340000" maintenance-time="20" room-temperature="20.0" base-mass="200"
			category="CONNECTION">
```

**Comment by mokun** [comment]
@bevans2000 

In Heating's constructor, I'd like to define the Server Farm building's heatGainEquipment = 1.3. The one under LABORATORY is for regular Laboratory building only. Server Farm is unique. So currently, there's no way to do that unless I use getBuildingType() to match the string name "Server Farm". 

What's the best solutions for me to look for Server Farm ? 

If I try to look for a Lander Hab, I can't do it either, Command Control building and Lander Hab would fall under COMMAND building category and I'll have to resort to convoluted ways such as using length and width to look for the exact building type ?!

- 
```java
		switch(building.getCategory()) {
			case CONNECTION:
				isConnector = true;
				heatGainEquipment = 0.0879;
				break;
			case FARMING:
				isGreenhouse = true;
				heatGainEquipment = 0.25;
				break;
			case EVA:
				isEVA = true;
				heatGainEquipment = 0.586;
				break;
			case COMMAND:
				isCommand = true;
				heatGainEquipment = 0.4;
				break;
			case COMMUNICATION:
				heatGainEquipment = 0.586;
				break;
			case WORKSHOP:
				heatGainEquipment = 0.7034;
				break;
			case LABORATORY:
				isLab = true;
				heatGainEquipment = 0.4396;
				break;
			case LIVING:
				isLodging = true;
				heatGainEquipment = 0.7034;
				break;
			case MEDICAL:
				isMedical = true;
				heatGainEquipment = 0.586;
				break;
//			case STORAGE:
//				isStorage = true;
//				heatGainEquipment = 0.0879;
//				break;
			case ERV:
				heatGainEquipment = 0.586;
				break;
			default:
				heatGainEquipment = 0.117;
				break;	
		}
```

**Comment by bevans2000** [comment]
The point is, the parameters of the Building should be governed by the Functions assigned to it. So that is the answer, if you want the heat gain to be a specific value for the Server Farm then the Functions assigned should influence the value.. 
Using the Building name is not the right way to go.

**Comment by bevans2000** [comment]
This is a very simple approach. Each Function is assigned a Category, then the Categories of all the Functions in a Building is ordered and the highest one becomes the Building Category. This will work fine.
You just need to make sure the precedence order is correct.
Putting the Category on the Building.xml is acceptable for specific Building that might be complex.
I will write a unit test to test the different scenarios but I can only check what I think is right

**Comment by mokun** [comment]
>  Categories of all the Functions in a Building is ordered and the highest one becomes the Building Category. This will work fine.

Sure.

>  make sure the precedence order is correct.

We'll need to fix this.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/61eed4c7-ff3f-4ec2-8e25-d4c2cf1aa85f)

WORKSHOP is obviously different from LABORATORY.

Garage is arguably a workshop for vehicle but we already have VEHICLE.
