### ISSUE TITLE
Drone navigation

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1353]
**Describe the bug**
- Currently, when a human pilot or a delivery bot takes a break from piloting the drone, the drone would abruptly stop and park at a location
- Drones would overshoot the destination and continue going in a straight line until it runs out of fuel. 

**Expected and unexpected behavior**
- Drones should be autopiloted. Humans or robots only need to take on a monitoring role only.
- Drone should decelerate before reaching the destination settlement.

**Java classes involved**
- DroneMission, PilotDrone, OperateVehicle

**Screenshots**
Drone 021 departed on sol 6. Now it's sol 11. It overshot the distance by 2039 km.
Drone 020 departed on sol 7. Now it's sol 11. It overshot the distance by 1486 km.
![image](https://github.com/user-attachments/assets/0a603beb-ccd0-405e-aa89-089f2ca5b74e)

Drone 020 was slightly off the course. It did not hit right on Dreamville but passed it on the side and continue on. 
![image](https://github.com/user-attachments/assets/4d4de36d-6f94-4aea-9ccd-ea3eef91503b)

Drone 021 seemed to have hit Heritage but it failed to stop and continue on. 
![image](https://github.com/user-attachments/assets/b891c13b-d85d-449e-94c7-478f4aa98284)

**Stacktrace**
```
01-Adir-07:812.977 (Info) OperateVehicle : [0.0000 N 0.0000 W] Drone 020 - Case III: Proceeding to Dreamville. dist2Dest: 1861.113 km  distanceToCover: 0.474 km  uKPH: 0.055 kph  vKPHProposed: 7.5 kph  hrsTime: 0.018 hrs  Time: 63.227 secs  maxAccel: 2.666 m/s2  skillMod: 1.0  lightMod: 0.3  terrainMod: 1.0  idealSpeedMS: 99.619 m/s  topSpeedKPH: 7.5 kph  idealSpeedKPH: 358.629 kph  nextSpeedKPH: 7.5 kph  
...
01-Adir-08:429.293 (Info) OperateVehicle [x14] : [2.9709 N 7.8865 W] Drone 020 - Case III: Proceeding to Dreamville. dist2Dest: 1362.242 km  distanceToCover: 9.631 km  uKPH: 154.054 kph  vKPHProposed: 154.49 kph  hrsTime: 0.017 hrs  Time: 62.338 secs  maxAccel: 3.671 m/s2  skillMod: 1.0  lightMod: 6.18  terrainMod: 1.0  idealSpeedMS: 108.784 m/s  topSpeedKPH: 154.49 kph  idealSpeedKPH: 391.623 kph  nextSpeedKPH: 154.49 kph  
...
01-Adir-08:570.948 (Severe) OperateVehicle : [19.7322 N 54.0277 W] Drone 020 - Case A: Out of fuel. Cannot drive.
01-Adir-08:570.948 (Info) PilotDrone : [Terminus - Residential Quarters 1] Cheryl Edwards - No longer piloting Drone 020.
...
01-Adir-08:571.652 (Warning) DroneMission : [19.7322 N 54.0277 W] Drone 020 - Out of fuel. Quit assigning the piloting task.


```

**Specifications**
- pre-3.8.0

**Additional context**
- Drone should prioritize using up the fuel first (since it takes up weight) before consuming the battery.

**Comment by mokun** [comment]
@bevans2000 

So how do we set up a task to be a *prerequisite"*of  another task ? 

Say for a delivery bot to become pilot, I want the bot to be charged up to 100% battery ahead of time.

Also, prior to going out for digging regolith or to take on a mission for for even piloting a drone, how do we make that person change his work shift so that he can sleep for 8 hours ahead of the mission ?

Is there a way to accomplish this ? 

This will be a very handy protocol to enforce.

**Comment by bevans2000** [comment]
With the next Mission approach we could have such stages as new Mission Step and add them to the Mission schedule

**Comment by mokun** [comment]
For now, 2 drones may park inside a garage as follows: 

![image](https://github.com/user-attachments/assets/a7f26f14-992d-4248-bc0d-bfda5cfbdde4)

**Comment by mokun** [comment]
@bevans2000 

I just managed to fix some driving/navigation bugs. 

Delivery drones can now complete its journey. See below. 

However, it still could not load resources at the destination settlement.

![image](https://github.com/user-attachments/assets/fff9112f-32e0-44ce-8e6c-211fa40586bf)

**Comment by mokun** [comment]
- A drone is able to reach the destination settlement.
- However, the drone is unable to be shown in settlement map.
- It's unable to replenish the fuel and oxygen and be able to fly back home.
![image](https://github.com/user-attachments/assets/ac4c9eda-9273-400e-9965-ce0694695042)

```
01-Adir-01:693.042 (Info) OperateVehicle : [10.6338 N 29.7500 W] D-Drone 005 - Case II: Slowing down. Arrive soon at Dreamville. dist2Dest: 0.224 km  dist2Cover: 0.233 km  u -> v: 32.02 -> 18.83 kph  hrsTime: 0.002 hrs  Time: 7.28 secs  maxAccel: 12.205 m/s2  skillMod: 1.0  lightMod: 0.6  terrainMod: 1.0  idealSpeedMS: 97.737 m/s  topSpeedKPH: 32.011 kph  idealSpeedKPH: 351.852 kph  nextSpeedKPH: 32.011 kph  
01-Adir-01:693.042 (Info) OperateVehicle : [10.6300 N 29.7500 W] D-Drone 005 - Case Ia: Arrived at Dreamville (dist: 0.0 km).
01-Adir-01:693.042 (Info) OperateVehicle : [10.6300 N 29.7500 W] D-Drone 005 - Halted the vehicle.
...
01-Adir-01:703.774 (Info) AbstractVehicleMission : [10.6300 N 29.7500 W] D-Drone 005 - Set return to Arcadia @ 24.3612 N 29.7837 W
```
