### ISSUE TITLE
Cause of Illness

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1354]
**Describe the bug**
- How does an illness show up when a person is asleep or when he's reading up on Psychology ?
- The Historical Event tab include medical events. However, it won't show why an illness happens. 
- `Pulled Muscle/Tendon` or `Broken Bone` should take longer than just 2 sols to get healed.
- It should show and document the method of treatment.
- It should tie to the 

**Expected and unexpected behavior**
- We should model and formulate a cause for each illness.
- For `Pulled Muscle/Tendon` medical issues, the musculoskeletal system should have very low score to begin with. Then during one of the strenuous activity such as digging regolith, an accident occurs.
- Accidents can trigger illness for sure.

**Java classes involved**
- PhysicalCondition, HealthProblem, Complaint

**Screenshots**

- `Broken Bone` and `Pulled Muscle/Tendon` occur too often during low strength activities such as sleeping, budgeting resources, etc.. 
![image](https://github.com/user-attachments/assets/166f6817-5d51-4785-8c4f-0b7763833985)

- How should the muscle health and scoreness tie to his broken bone condition ? 
- The performance level drops to 20% as a result. It's reasonable. 
![image](https://github.com/user-attachments/assets/bc67bd26-8e16-4bca-a1d7-f67597974fbf)

- We don't seem to have logics to tie Bones Loss (4.06%) to the Broken Bone condition.
- It's unclear what it means by `Recovering (3)` in the Health Problem table.
![image](https://github.com/user-attachments/assets/3bb51a2c-3212-4541-8b3c-7799551f4b76)

- Amanda recovered too quickly. Performance is already 100%. 
- Muscle Health at 88.0 is NOT bad.
![image](https://github.com/user-attachments/assets/75ba350f-8a38-4ffc-ab0f-04554d3b8517)

- The Health Problem table should provide a history of medical illness
![image](https://github.com/user-attachments/assets/f10bf9b2-f865-4ef3-b605-70cbd3b22063)

**Stacktrace**

Amanda and Bruce experienced a very speedy healing. Method of treatment is UNKNOWN.
```
01-Adir-03:893.575 (Info) PhysicalCondition : [35.1824 N 163.7953 E - Merlin] Amanda Adams - Suffering from Pulled Muscle/Tendon.
...
01-Adir-05:984.924 (Info) PhysicalCondition : [Starcity - Inflatable Greenhouse 1] Amanda Adams - Cured from Pulled Muscle/Tendon.
...
01-Adir-06:362.221 (Info) PhysicalCondition : [Heritage - EVA Airlock 1] Bruce Ramirez - Suffering from Pulled Muscle/Tendon.
...
01-Adir-08:482.771 (Info) PhysicalCondition : [22.4000 N 18.0000 W] Bruce Ramirez - Cured from Pulled Muscle/Tendon.
```

It did say *Began to receive treatment for Broken Bone*. But what medication and what treatment methods ?
```
01-Adir-10:466.865 (Info) PhysicalCondition : [Heritage - Residential Quarters 2] Máté Szabó - Suffering from Broken Bone.
...
01-Adir-10:538.201 (Info) HealthProblem : [Heritage - Central Hub A 1] Máté Szabó - Began to receive treatment for Broken Bone.
01-Adir-10:538.201 (Info) TreatHealthProblem : [Heritage - Large Greenhouse 1] Barry Evans - Treating Máté Szabó for Broken Bone

...
01-Adir-08:174.865 (Info) PhysicalCondition : [Dreamville - Lander Hab 1] Michael Rogers - Suffering from Broken Bone.
...
01-Adir-10:548.176 (Info) HealthProblem : [Dreamville - Inflatable Greenhouse 2] Michael Rogers - Began to receive treatment for Broken Bone.
01-Adir-10:548.176 (Info) TreatHealthProblem : [Dreamville - Lander Hab 1] Sarah Parker - Treating Michael Rogers for Broken Bone
```

**Specifications**
- pre-3.8.0

**Comment by mokun** [comment]
@bevans2000 

- Do we need to be so verbose in Pyotr's health status in Monitor Tool's Event tab ?
![image](https://github.com/user-attachments/assets/d8f0778d-61d1-4c7b-9a75-6f8fb75095d6)

**Comment by bevans2000** [comment]
> @bevans2000 
> 
> - Do we need to be so verbose in Pyotr's health status in Monitor Tool's Event tab ?
> ![image](https://github.com/user-attachments/assets/d8f0778d-61d1-4c7b-9a75-6f8fb75095d6)
> 
> 

Looks like the monitor table is using the output of the toString method. Just replace it with a call to the name attribute.

**Comment by mokun** [comment]
@bevans2000 

In what way would you like to limit the onset of some of those *medical-complaints* in `medical.xml` ?

```xml
		<!-- A broken bone can result in gangrene if left untreated. -->
		<medical-complaint name="Broken Bone">
			<seriousness value="60" />
			<degrade-time value="7.0" />
			<recovery-time min="14.0" />
			<probability value="5.0" />
			<performance-percent value="20.0" />
			<bed-rest-recovery value="true" />
			<treatment-type value="Plaster Cast" />
			<degrade-complaint value="Gangrene" />
			<effort-influence value="HIGH" />
		</medical-complaint>

		<!-- A pulled/muscle is a minor and common medical complaint. -->
		<!-- It affects performance but does not require medical treatment. -->
		<medical-complaint name="Pulled Muscle/Tendon">
			<seriousness value="1" />
			<recovery-time min="2.0" />
			<probability value="3.0" />
			<performance-percent value="70.0" />
			<bed-rest-recovery value="false" />
			<effort-influence value="HIGH" />
		</medical-complaint>
```

Shall we add something like a new activity attribute in each *medical-complaint* entry ?

With that, we could explicitly limit `Pulled Muscle/Tendon`, `Broken Bone`, etc. to occur only when a person engages in high impact activities such as exercising, digging resources in an EVA op.

To be reasonable, we could find a way to customize which medical complaints could not happen during certain tasks such as Sleep, Reading, Relaxing, etc..

**Comment by bevans2000** [comment]
It's already there in the effort-influence property. This ties into the effort of the Experience impact assigned to Tasks.
Don't create another attribute. 
The probability ratings need adjusting

**Comment by mokun** [comment]
The health history of a person should be crucial. 

We barely have a *healthLog* map to document the type of complaints and number of occurrences in PhysicalCondition.

```java
	/** List of medications affecting the person. */
	private List<Medication> medicationList;
	/** Injury/Illness effecting person. */
	private List<HealthProblem> problems;
	/** Record of Illness frequency. */
	private Map<ComplaintType, Integer> healthLog;

	/** Health Risk probability. */
	private Map<HealthRiskType, Double> healthRisks;

```

What data structure would be more helpful for recording and viewing a person's health info ?

**Comment by bevans2000** [comment]
I can look at this if you want. Should have time by the end of the week to commit a solution.

**Comment by mokun** [comment]
I even wanna push belong just having a health history log. 

Why can't we have an universal **Memory Data Structure** for a person ?  

For now, what do we want to record that define the uniqueness of a person ? Not just a bunch of ratings over a person's capability but the totality of his existence in terms of his experiences, his encounters, his actions and judgment, etc. ? 

In future, it would be interesting to implement some machine learning algorithm out there to create the idea of a *memory cell*, each with tunable parameters for recording events a person would encounter.

**Comment by bevans2000** [comment]
Let's just capture the medical history for now and look for a bigger change in a later release. We are too close to 3.8 to be making big changes.

**Comment by mokun** [comment]
Sure ! Please do. Not being able to recall something that happened in the past is no life at all. Having an elegant way to record life events is supposed to be fundamental for a person. 

And we may as well give robots the ability to remember relevant events that  happened in a settlement. 

I would wager that having a medic robot around can be beneficial in storing privacy information such as a personal health and sickness log, teamwork performance and relationship conflict database, not the least including those he has treated illnesses and progress of recovery.

To stretch a little more on this, a future detective on Mars may one day query on a robot to replay records of past events that happened , what this robot sees and hears and who he interacted with, to find forensic evidence...

**Comment by bevans2000** [comment]
I also now know how a Broken bone can happened when sleeping. I'll fix it
