### ISSUE TITLE
Change in Settlement Preference results in no mission generated

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1355]
**Describe the bug**
- After making a change of *mission limit* or *mission weight* in Settlement Preference tab, no more mission can be generated.

**Expected and unexpected behavior**
- Even after changing it back to its default setting, no mission will start.

**Java classes involved**
- PreferenceTableModel, ParameterManager

**Specifications**
- pre-3.8.0

**Additional context**
- Can unit tests be used to prove that the change of mission priority work as expected ?

**Comment by mokun** [comment]
@bevans2000 

I only tested by changing the mission limits and mission weights of Ice/Regolith Prospecting.

I also added Delivery weights.

That's when I found out the preference is not working properly.

**Comment by bevans2000** [comment]
I can have a look but the manager was previously working fine

**Comment by bevans2000** [comment]
Already a Unit Test for ParameterManager and it's working fine. Will investigate it

**Comment by bevans2000** [comment]
The score of the Plan Mission Settlement tasks goes up and down in response to the changes to the Total Missions value.

**Comment by mokun** [comment]
> The score of the Plan Mission Settlement tasks goes up and down in response to the changes to the Total Missions value.

Yes it's by design that the minimum score needed for passing the review can change over time dynamically.

**Comment by bevans2000** [comment]
I'm talking about the Rating Score of the Plan Mission Settlement Task. That changes when I move the mission total which suggests the Preferences is working as expected.

**Comment by mokun** [comment]
I see.

Preference tab is great. 

What I would like to see is the current rating score for each mission and how it results by showing the raw score and the breakdown of each modifier. This will greatly aid debugging why there are no new missions generated from time to time after sol 30.

It's like in the resource process tab, I can see the score for each process and how likely it will get picked.

In the other hand, it will be great to add players, sponsors and settlements' preference score to resource / food production / manufacturing process in near future.

**Comment by bevans2000** [comment]
The RatingScore pattern is a great base to use elsewhere. I think there is already an issue that addresses using structured scores for Missions.

**Comment by mokun** [comment]
> an issue that addresses using structured scores for Missions.

Not an issue. 

I simply want to display the components of the rating score for each type of mission of a settlement in a table in a tab panel.

**Comment by bevans2000** [comment]
We already have it covered #1179
