### ISSUE TITLE
generateWaste can't store grey water, recycling grey water, vapor pressure of water

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#138]
**Describe the bug/issue**
After 252 sols of simulation, the log file is flooded with the same error message: "GenerateWaste : (AR) No more room to store x.x kg of grey water (or storage space has not been initialized yet)." 

Since it worked before, I assume it simply ran out of capacity. 

**Affected Area**
 LivingAccommodations

**Expected behaviors**
- This log message should not appear that often, I have a full log of only this line now
- Instead, this should get reported once and a malfunction should get triggered, so a plumber can fix this.
- ( Call the super mario brothers )
- Since it is just grey water, the water should simply be wasted if it can't be stored during the malfunction. That is enough punishment on a world where water is rare 

If more greywater is produced than can be processed, a number of different mitation plans could be possible for the settlement:
- Increasing waste water processing capacity
- Use more of it for irrigation (With limitations)
- Consume grey water in manufacturing processes
- Increase waste water storage (rather bad idea, but buys time)
- Vaporize it

**Actual/Observed Behaviors**

```
2018-11-16T15:58:30.8 (Severe) [x48] Storage at LivingAccommodations::generateWaste : (AR) No more room to store 0.3 kg of grey water (or storage space has not been initialized yet).
2018-11-16T15:58:34.2 (Severe) [x36] Storage at LivingAccommodations::generateWaste : (AR) No more room to store 0.1 kg of grey water (or storage space has not been initialized yet).
2018-11-16T15:58:37.3 (Severe) [x32] Storage at LivingAccommodations::generateWaste : (AR) No more room to store 0.3 kg of grey water (or storage space has not been initialized yet).
2018-11-16T15:58:40.5 (Severe) [x34] Storage at LivingAccommodations::generateWaste : (AR) No more room to store 0.3 kg of grey water (or storage space has not been initialized yet).
2018-11-16T15:58:43.6 (Severe) [x38] Storage at LivingAccommodations::generateWaste : (AR) No more room to store 0.31 kg of grey water (or storage space has not been initialized yet).
```

**Reproduction (optional)**
Longterm simulation over 250 sols.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : JDK 10
 - mars-sim build version : r4530_headless

**Additional context**
 - Add any other context about the problem here.

**Comment by mokun** [comment]
Yes. it's quite annoying to keep receiving the same msg over and over.

> Increasing waste water processing capacity

Yes, it's supposed to trigger calling ToggleResourceProcess the ai task to make sure that any process that takes in grey water will be turned on.

> Use more of it for irrigation (With limitations)

The method computeWaterFertilizer() in Crop currently take both grey water and regular water for food crop irrigation. I'll refactor it somehow to take in more grey water.

> Consume grey water in manufacturing processes

It has been the other way around. And realistically speaking, most manufacturing process should produce dirty water, aka, grey water. See the list of processes below : 
- make pulp from cane fiber and crop waste
- do hydrogen iron reduction
- produce ethylene
- reduce gypsum to calcium carbonate with carbon
- reduce gypsum to calcium carbonate with carbon monoxide
- reduce gypsum to calcium carbonate with hydrogen
- do malachite smelting
- bake regolith brick
- bake sand brick
- bake regolith brick 
- melt and filter ice

I suppose here on Earth, we dump the water somewhere and let the nature do the job of dissociating the organic matter... :( 

The short term solution will probably drain it to a low lying crater. It should flag some sort of pollution index and invite criticism from environmentalists...

> Increase waste water storage (rather bad idea, but buys time)

Yes it should somehow trigger a notification and leave an alert notice on Commander's todo list or a flag on the settlement dashboard.

> Vaporize it

Yay. I have a chemistry question. I wonder if leaving it out in such low pressure atmosphere environment will automatically vaporize some of them and what will be the rate of vaporization ?

**Comment by mokun** [comment]
Currently, there are 3 processes from [buildings.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/buildings.xml) that manages wastes as follows : 

```
				<!-- Grey Water Recycling process for cleaning grey water. -->		
				<process name="Grey Water Processor" power-required=".32" default="on">
					<!-- Input: grey water, oxygen, chlorine  -->
					<!-- resource: the resource added to the process. -->
					<!-- See resources.xml -->
					<!-- rate: the rate (kg/sol) the resource is added -->
					<!-- ambient: true if resource is freely available from outside -->
					<!--          false if supplied from settlement's inventory. -->
					
					<input resource="grey water" rate="40.0" ambient="false" />
					<!-- input resource="oxygen" rate="1.5" ambient="false" /-->
					<input resource="chlorine" rate="0.5" ambient="false" />
					
					<!-- Output : clean water, solid waste -->
					<!-- resource: the resource resulting from the process. -->
					<!-- See resources.xml -->
					<!-- rate: the rate (kg/sol) the resource is produced -->
					<!-- ambient: true if resource is vented outside -->
					<!--          false if kept by settlement's inventory. -->
					<output resource="water" rate="38" ambient="false" />
					<output resource="solid waste" rate="2" ambient="false" />			
				</process>
		
				<process name="Black Water Processor" power-required=".315" default="on">
					<input resource="black water" rate="20" ambient="false" />
					<input resource="chlorine" rate="0.1" ambient="false" />
					<input resource="nitrospira spp" rate="0.02" ambient="false" />
					<input resource="nitrosomonas spp" rate="0.02" ambient="false" />	
					<input resource="chlorine" rate="0.5" ambient="false" />								
					<output resource="grey water" rate="17" ambient="false" />
					<output resource="toxic waste" rate="1" ambient="false" />
					<output resource="nitrogen" rate=".5" ambient="false" />
					<output resource="nitrite" rate=".5" ambient="false" />
					<output resource="nitrate" rate=".5" ambient="false" />
					<output resource="phosphorus" rate=".5" ambient="false" />					
				</process>

				<process name= "Solid Waste Management" power-required=".3" default="on">
					<input resource="toxic waste" rate="4" ambient="false" />
					<input resource="solid waste" rate="6" ambient="false" />
					<output resource="fertilizer" rate="2" ambient="false" />
					<output resource="carbon dioxide" rate="2" ambient="false" />
					<output resource="water" rate="2" ambient="false" />
					<output resource="carbon" rate="2" ambient="false" />
				</process>
```

From the standpoint of scientific realism, we don't want to change those input/output values arbitrarily because they are more or less based on principles of the existing technology that we have developed.

But I'm willing to relax this standard a little bit :) I'm thinking of connecting the scientific studies that the settlers perform to improving the quality of life on Mars somehow.

**Comment by mokun** [comment]
Great that you point out the issue with excessive grey water log.

As a matter of fact, the enum WASTE_DISPOSAL is a relatively new FunctionType added in recent years. 

We don't have any codes that takes advantage of this [Building Function](https://github.com/mars-sim/mars-sim/wiki/Building-Function) yet.

So There is no attribute tag set up for waste management in buildings.xml yet.

And [WasteDisposal](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/structure/building/function/WasteDisposal.java) is pretty much unused at this point.

**Comment by Urwumpe** [comment]
@mokun 

> Yay. I have a chemistry question. I wonder if leaving it out in such low pressure atmosphere environment will automatically vaporize some of them and what will be the rate of vaporization ?

Thats pretty easy, its just depends on the vapor pressure of water and thus on the temperature of it. The Space Shuttle used this for cooling, since vaporizing water takes away a lot of energy. It used this in the flash evaporator with excess water from the ECLSS or the fuel cells, and also had water spray boilers for cooling the hydraulic fluid with a special reserve of water. 

https://en.wikipedia.org/wiki/Vapour_pressure_of_water

So, the rate at which you can evaporate water to steam is simply a matter of how much you need to heat it. Usually you want to heat it far enough beyond the needed temperature, that it does not freeze again instantly against your steam nozzle. 

The steam pressure of water at 0° is already 611.3 Pa, which is slightly higher than the average surface pressure on Mars - that is why liquid water is so rare on Mars, but can exist as ice. At 10°C, the vapour pressure is twice the surface pressure (1228 Pa), at about room temperature, 20°C, its 2339 Pa. That could be enough for making sure the steam can float enough distance away from the nozzle before coating cold objects with ice, maybe it would even just rain down as fine snow as observed on Mars because the steam cloud raises above the settlement before cooling below freezing point again. 

But it would of course mean: Settlements create their own microclimate. Just like cities on Earth already do. The meteorologists on Mars will sure have some work there...

**Comment by shirishag75** [comment]
Guess this still needs improvement as while compiling it fails here - 

```
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.468 sec
Running org.mars_sim.msp.core.resource.TestAmountResourceStorage
Nov 18, 2018 3:34:28 AM org.mars_sim.msp.core.resource.AmountResourceStorage retrieveAmountResource
SEVERE: Amount resource carbon dioxide of amount: 101.0 needed to retrieve.  Amount stored: 100.0
Nov 18, 2018 3:34:28 AM org.mars_sim.msp.core.resource.AmountResourceStorage retrieveAmountResource
SEVERE: Amount resource carbon dioxide of amount: 100.0 needed to retrieve.  Amount stored: 0.0
Tests run: 21, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.689 sec <<< FAILURE!
testRemoveAmountResourceTypeCapacity(org.mars_sim.msp.core.resource.TestAmountResourceStorage)  Time elapsed: 0.055 sec  <<< ERROR!
java.lang.StackOverflowError
        at org.mars_sim.msp.core.resource.AmountResourceStorage.removeAmountResourceTypeCapacity(AmountResourceStorage.java:79)
        at org.mars_sim.msp.core.resource.AmountResourceStorage.removeAmountResourceTypeCapacity(AmountResourceStorage.java:79)
        at org.mars_sim.msp.core.resource.AmountResourceStorage.removeAmountResourceTypeCapacity(AmountResourceStorage.java:79)
        at org.mars_sim.msp.core.resource.AmountResourceStorage.removeAmountResourceTypeCapacity(AmountResourceStorage.java:79)
```


It just goes on and on for a while .

**Comment by mokun** [comment]
My bad. Good that maven test caught the error.

**Comment by mokun** [comment]
@Urwumpe 

Our solid or liquid wasting recycling modeling is only half done.

Obviously, it would be a lingering issue as human begins to show up on Mars.

@bevans2000 , 

If you're interested in further modeling what to do with the different type of wastes we have defined, let us know.

May be we can have them built waste storage shed to hide them.

**Comment by mokun** [comment]
Seems there are at least two issues here:

1. how to handle excessive log messages
2. Implement logical, responsible and scientific ways in managing excessive resources built-up

As of now, we have since been using grey water for irrigating the crop in greenhouses. No more wasting this potentially precious resource.

And we have also waste processing as a building function.

It's still possible for a few other excessive resources (such as carbon monoxide) to build up to the point that there is no more capacity to hold that resources and spurious log statements may be printed.

@bevans2000 do you have any inputs for us ?
