### ISSUE TITLE
Cache the a map of coordinates to speed up mineral layer rendering

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1385]
**Is your feature request related to a problem? Please describe.**
- Currently, if the mineral layer is enable in Mars Navigator, the rendering of each color dot superimposed on a surface map are very *expensive* and unnecessarily repetitive.

**Describe the rationale**
- Get rid of the need of repeatedly calling `IntegerMapData.convertRectToSpherical()` 

**Describe the goal(s) you have in mind**
- Create a cache mechanism and combine x, y and rho into an index as the **key** of a map. This map will have Coordinates as the **value**.

**Describe the solution you desire to see**
- In Coordinates class, we have
```java
	/**
	 * Converts linear rectangular XY position change to spherical coordinates with
	 * rho value for map.
	 *
	 * @param x              change in x value (# of pixels or km)
	 * @param y              change in y value (# of pixels or km)
	 * @param rho            radius (in km) or map box height divided by pi (# of pixels)
	 */
	public Coordinates convertRectToSpherical(double x, double y, double rho) {
		Point2D point = IntegerMapData.convertRectToSpherical(x, y, phi, theta, rho);
		return new Coordinates(point.getX(), point.getY());
	}

```

In MineralMapLayer, we have a double loop structure : 
```java
	/**
	 * Displays the layer on the map image.
	 * 
	 * @param mapCenter the location of the center of the map.
	 * @param baseMap   the type of map.
	 * @param g         graphics context of the map display.
	 */
	public void displayLayer(Coordinates mapCenter, Map baseMap, Graphics g) {
		
...
			for (int x = 0; x < Map.MAP_BOX_WIDTH; x = x + 2) {
				
				for (int y = 0; y < Map.MAP_BOX_HEIGHT; y = y + 2) {
						
					// Do NOT delete the following line of codes
//					if (mapCenterCache == null || rho != rhoCache || numMineralsCache != numMinerals) {
					
						java.util.Map<String, Double> mineralConcentrations = 
							mineralMap.getSomeMineralConcentrations(
										mineralsDisplaySet, 
										mapCenter.convertRectToSpherical(x - centerX, y - centerY, rho), 
										mag);
						hasMinerals = true;

```

In RandomMineralMap, the method below gets called in by that double loop. It create the fuzzy look of each mineral concentration. It has 2 while loops inside and is thus very repetitive and needs to be cached or simplified.

```java 
	/**
	 * Gets some of the mineral concentrations at a given location.
	 * 
	 * @param mineralsDisplaySet 	a set of mineral strings.
	 * @param aLocation  a coordinate
	 * @param mag		 the map magnification factor
	 * @return map of mineral types and percentage concentration (0 to 100.0)
	 */
	public Map<String, Double> getSomeMineralConcentrations(Set<String> mineralsDisplaySet, Coordinates aLocation,
			double mag) {
		
		double angle = .025 / mag;
	
		Map<String, Double> newMap = new HashMap<>();
		
		boolean emptyMap = true;
		
		if (allLocations == null) {
			allLocations = allMineralsByLoc.keySet();
		}
		
		Iterator<Coordinates> i = allLocations.iterator();
		while (i.hasNext()) {
			Coordinates c = i.next();
	
			double phi = c.getPhi();
			double theta = c.getTheta();
			double phiDiff = Math.abs(aLocation.getPhi() - phi);
			double thetaDiff = Math.abs(aLocation.getTheta() - theta);

			// Only take in what's within a certain boundary
			if (phi > LIMIT && phi < Math.PI - LIMIT
				&& phiDiff < angle && thetaDiff < angle) {
				
				Map<String, Integer> map = allMineralsByLoc.get(c);
				
				Set<String> mineralNames = updateMineralDisplay(mineralsDisplaySet, map.keySet());
				if (mineralNames.isEmpty()) {
					continue;
				}
				
				double distance = aLocation.getDistance(c);
			
				Iterator<String> j = mineralNames.iterator();
				while (j.hasNext()) {
					String mineralName = j.next();	
					
					double effect = 0;
					double conc = map.get(mineralName);	
					// Tune the fuzzyRange to respond to the map magnification and mineral concentration
					double fuzzyRange = conc;
									
					if (distance < fuzzyRange)
						effect = (1D - (distance / fuzzyRange)) * conc;				
					
					if (effect > 0D) {
						
						if (emptyMap) {
							newMap = new HashMap<>();
							emptyMap = false;
						}
						double totalConcentration = 0D;
						if (newMap.containsKey(mineralName)) {
							// Load the total concentration
							totalConcentration = newMap.get(mineralName);
						}
						
						totalConcentration += effect;
						if (totalConcentration > 100D)
							totalConcentration = 100D;
						
						newMap.put(mineralName, totalConcentration);
					}
				}
			}	
		}
		
		return newMap;
	}
```

**Specifications**
- post-3.8.0

**Additional context**
- This relates to 
1. https://github.com/mars-sim/mars-sim/issues/935
2. https://github.com/mars-sim/mars-sim/issues/942

**Comment by mokun** [comment]
@bevans2000 

Would you like to tackle on caching a map of Coordinates, just like what the way you did to cache the elevation data with an index ? 

But this time, it has an extra rho param and not just x and y.

**Comment by bevans2000** [comment]
I think the method ```getSomeMineralConcentrations``` can be significantly improved and optimised. The distance check can be done in the Coordinate frame of reference using the distanceTo method.
Caching the Coordinates has the risk of consuming a lot of memory

**Comment by mokun** [comment]
>  The distance check can be done in the Coordinate frame of reference using the distanceTo method

Do you mean replacing getDistance() with a new method ?

Is what way is creating this new distanceTo() method be any different ?

**Comment by mokun** [comment]
May be we can get rid of finding the *actual* distance between two coordinates ?! 

There should be a way to just compare how far apart between two coordinates.

Then we'll need to think of a way to create a fuzzy effect more efficiently also.

Without this fuzzy radial effect, a mineral concentration cannot be seen on the surface map.

I've tried commenting out that block of code and couldn't see any mineral color dots at all.

May be a Java2D trick can solve this but I haven't looked into it yet.

**Comment by mokun** [comment]
I just figured out how to get rid of calling the expensive method *getDistance()*.  Will commit in a moment.

It's kind of one step closer to reclaiming the speed of rendering mineral concentration.

**Comment by mokun** [comment]
The current look and feel of the faster rendering of mineral concentration : 
![image](https://github.com/user-attachments/assets/ef3508b1-bef1-417d-9125-ffe7f3eba743)

**Comment by bevans2000** [comment]
I think we need to rethink how the mineral layer is rendered. We need to drop the MapBoxArray. I think the logic should be

1. Calculate the bounding box displayed in the MapPanel in terms of Coordinates; the 4 points.
2. In the Mineral Map class use the box coordinates to find any mineral Locations within the displayed rectangle.
3. Mineral Map returns a List of the coordinates located and the various Mineral concentrations
4. The Mineral map layer then integrates through the coordinate list and each one, converts to the x,y of the map display
5. Renders the colours at the x,y

This will be less intensive that the current approach and removes the need for the expensive MapBoxArray

@mokun, thoughts?

**Comment by mokun** [comment]
> removes the need for the expensive MapBoxArray

MapBoxArray has been derived already in IntegerMapData whenever the player drags the map or zoom in and out of the map.

So it costs nothing. 

When MapBoxArray is static, the mineral layer can reuse it.

The old approach in 3.7.0 was to start from scratch to create a double array pixel to create the mineral layer. It was very inefficient.

**Comment by mokun** [comment]
> 1. Calculate the bounding box displayed in the MapPanel in terms of Coordinates; the 4 points.

Yes it's possible to use this bounding box concept to further limit the range of phi and theta to be processed. 

Note that we should pass the raw values of phi and theta (instead of the Coordinates object) since the mathematical formula for map projection works with phi and theta only, as somewhat explained in [here](https://github.com/mars-sim/mars-sim/pull/1455).

**Comment by bevans2000** [comment]
> > removes the need for the expensive MapBoxArray
> 
> MapBoxArray has been derived already in IntegerMapData whenever the player drags the map or zoom in and out of the map.
> 
> So it costs nothing.
> 
> When MapBoxArray is static, the mineral layer can reuse it.
> 
> The old approach in 3.7.0 was to start from scratch to create a double array pixel to create the mineral layer. It was very inefficient.

But it is unstable because we will always have to use IntegerMapData, it will not work for your tiles. Plus it fails when a map is loaded in the background.
You are loading a static data for an instance method.

**Comment by mokun** [comment]
I just made MapBoxArray non-static with the last commit.

> because we will always have to use IntegerMapData,

At this point, we always need IntegerMapData's gpu() or cpu0() to render a projection of image onto the globe.

Without MapBoxArray, it will be a duplicate effort in calling convertRectIntToSpherical() when rendering the mineral layer.

Other optimizations techniques may be possible, as you have suggested.

Note: we may be able to shrink the bounding box. 

Currently, it's MAP_BOX_HEIGHT * MAP_BOX_WIDTH

getMapBoxPoint(index) only calls one set of phi and theta at a time.

```java
			for (int y = 0; y < MAP_BOX_HEIGHT; y = y + 2) {
				for (int x = 0; x < MAP_BOX_WIDTH; x = x + 2) {
			
					int index = x + y * MAP_BOX_WIDTH;
					
					Point2D point = baseMap.getMapBoxPoint(index);
					if (point == null)
						continue;
					double phi = point.getX();
					double theta = point.getY();
					
					Map<String, Integer> mineralConcentrations = 
							mineralMap.getSomeMineralConcentrations(
										mineralsDisplaySet, 
										phi, 
										theta,
										mag);
									
					if (mineralConcentrations != null && !mineralConcentrations.isEmpty()) {
		
						computeColorMineralArray(mineralConcentrations, newMineralArray, x, y);
						
						hasMinerals = true;
					}
				}
			}
```


> it will not work for your tiles.

Right ! In future as we transition to loading tile maps, IntegerMapData will go through another round of significant changes in support of that approach and we'll come up with new ways of avoiding convertRectIntToSpherical().

**Comment by bevans2000** [comment]
Ok but I think it fundamentally flawed. The box array is coupled to the size of the map panel 
I think we can rework the mineral layer and remove it all together. This consumes a lot of memory

**Comment by bevans2000** [comment]
I am going to change it so we are not using Point2D and replace with our own record. This class is outside our control and it comes from the AWT package

**Comment by mokun** [comment]
> we are not using Point2D and replace with our own record.

Sure. whatever you see fit. 

btw, is Record mutable data type, right ?

**Comment by bevans2000** [comment]
> > we are not using Point2D and replace with our own record.
> 
> Sure. whatever you see fit.
> 
> btw, is Record mutable data type, right ?

Yes it's immutable. Will give us a clearer picture.

**Comment by bevans2000** [comment]
I have been thinking about the Mineral Layer map. The problem I see is we have to integrate over all mineral positions to find those that are visible. The same problem appears to Landmarks and Exploration sites as well.
What we need is a more optimal way to hold these surface features so we can do quick look up based on a region. This being a rectangular space defined by 2 Coordinates, e.g. find all Landmarks in this region. Internally we would hold these is a tree based on tooling the surface of the globe.I think would be great and much better.
The puzzle I have is how do we map the visible MapDisplay into a Region? I think one way is to partially use the Map box logic BUT use the top-left and bottom right Coordinates. Due to the curvature of the plant, the region defined in this approach would be more that the visible area on the map display. Latitude lines are convex.
But I'm not sure it would work when the map moves across the top of the planet. The Coordinates would flip over I think.

**Comment by mokun** [comment]
> more optimal way to hold these surface features so we can do quick look up based on a region

This is very true. 

It's insanity to keep creating the radial mineral concentration pattern over and over as player drag across the map.

We could simply cache those values.

**Comment by mokun** [comment]
> geo based lookups

Great. It doesn't make sense the value of rho would trigger the recalculation for the radial color pattern.

I suppose your geo based lookup would avoid that, right ?

**Comment by mokun** [comment]
Btw, can we substitute the manual calculation of generating radial color pattern based on mineral concentration with just using certain Java 2D graphic techniques ?

**Comment by bevans2000** [comment]
> 
> I suppose your geo based lookup would avoid that, right ? 
> 
Yes, I plan for it to be based on Coordinates and being absolute in terms of the planet surface

**Comment by bevans2000** [comment]
Not sure I get what you mean.

**Comment by mokun** [comment]
> Not sure I get what you mean. 

The mineral concentration was calculated initially and set in placed at the start of the sim.

I even pre-defined the color of each mineral in its XML file just recently.

However, when drawing the mineral layer, we still run into the situation that the raw concentration is just a dot and is 'not enough' to be shown up on the surface map.

Do you notice how an artificial, fuzzy radial pattern was heavily computed at each new change of center coordinate ?

This expensive computation could have been unnecessary/avoided by design if we change the approach to just using Java 2D graphic such as creating a triangular, oval, rectangular shape symbol on each original/raw mineral concentration data point.

Do you see that ?

**Comment by bevans2000** [comment]
Yes, I see. I didn't know there was some special rendering

**Comment by bevans2000** [comment]
Right, I get it now. Each point in the Mineral Concentration map is rendered as 4 dots. But it creates a brank new image and then overlays it on top. 
Yes there is a lot of excessive code here and can make large changes but how do want to render it? I would prefer to render directly to the Graphics and not create an image. The reason is we can create an ```AbstractFeatureMapLayer``` that renders features on the surface and move all the selection logic into that. This class would be applicable to Landmarks, ExploredSItes & Mineral. And potentially UnitMapLayer as well.
Most of the layers are about selected an entity by it's Coordinate according to the MapDisplay and then rendering so we can remove a lot of duplicate logic and clean it up.
Landmarks & ExploredSite has the correct way of selection using the arc angle from the center position.

**Comment by mokun** [comment]
> Each point in the Mineral Concentration map is rendered as 4 dots.

Currently, if I recall, a mineral concentration is a double percentage figure (0-100%) on a coordinate. 

Since it's just dot-sized and the "intensity" is also proportional to it peecentage, it won't be enough to show up visibly on the map even if it's 100% concentration. 

Therefore, a radial pattern (centered at its coordinate) is added to amplify its visual appearance. 

However, calculating this radial pattern is expensive and is NOT done via Java 2D graphic when it could have been.

**Comment by bevans2000** [comment]
> However, calculating this radial pattern is expensive and is NOT done via Java 2D graphic when it could have been.

For now the focus is to optimising the selection of items to display and reduce the needs to iterate the concentrations for each point. 
To do this I have a cunning plan to consolidate the layer logic into a new abstract class ```SurfaceFeatureLayer``` that works on  new interface called ```SurfaceFeature``` which just has a single Coordinate property. The logic selects visible features using the viewpoint of the map described as the center point and the arc radius. It delegates to a subclass the rendering of actual visible features.
Then rendered entities, e.g. Landmark, Explored Sites, Mineral Concentrations, will implement the SurfaceFeature and hence massively optimises &  simplifies the rendering.
To further optimise, there will be a ```SurfaceManager``` that holds SurfaceFeature instead of in a flat list. The purpose of this manager is it stores the feature as longitudal bands around the globe. Then the manager can select the appropriate bands covered by the viewpoint to search instead of the whole feature list, hence reducing the number of comparisons that have to be done.

**Comment by mokun** [comment]
> new interface called SurfaceFeature... will be a SurfaceManager that holds SurfaceFeature instead of in a flat list.

Sounds great ! Look forward to having them

> The purpose of this manager is it stores the feature as longitudal bands around the globe. Then the manager can select the appropriate bands covered by the viewpoint to search instead of the whole feature list, hence reducing the number of comparisons that have to be done.

So it goes beyond just simplifying the mineral layer but all layers, right ?

**Comment by bevans2000** [comment]
> So it goes beyond just simplifying the mineral layer but all layers, right ?
Not all but many of them, there is a lot of duplicate code. Plus each should have a set of filters not just the Mineral layer. Having in centralised means we can do something.
For example 
* Only a single unit layer but with a label filter
* Landmarks layer show different types
* Explored sites the level of exploration

**Comment by bevans2000** [comment]
@mokun have a look at 4d2985b59ccd1f7fbd42d3d42dc36fd25dc6c2ee

**Comment by bevans2000** [comment]
A further big optimisation this approach can provide relates to how we track mouse movement. Currently all Units and Landmarks are compared to the mouse position. But the as the abstract Surface feature map layer is aware of actual entities as Surface features we could hold a list of just the visible entities drawn by the layers. This list would be significantly smaller than the current list.
The action when the user clicks on a entity would be handled by the layers that drew that entity, meaning it would be easy to show popups for explored sites, landmarks, mission waypoints. 
This could be really good and quick.
First step get the suitable layers using a common approach.

**Comment by mokun** [comment]
> But the as the abstract Surface feature map layer is aware of actual entities as Surface features we could hold a list of just the visible entities drawn by the layers. This list would be significantly smaller than the current list.

Sure. If we have hundreds of landmarks, it's almost a waste to keep iterating the list at every moment at the slightest move of the mouse cursor.

**Comment by bevans2000** [comment]
Having a change of plan on this. A lot of the processing is also down in the actual mineralmap as as the layer. I have some ideas on how to improve its a bit of change.
So I'm going to finish improving and simplifying the layer logic generally before tackling the mineral layer. That means I will add the concept of generic hotspots on the map that can be used for landmarks and units

**Comment by mokun** [comment]
> the concept of generic hotspots on the map that can be used for landmarks and units

Java2D graphic faster but is also not as professional looking, as evident in the Settlement Map.

At a second thought, in near future, we'll switch to using web components, openGL, or JavaFX for our UI, right ? 

So it may or may not worth our time tweaking how Java2D should be optimized ?

**Comment by bevans2000** [comment]
What I want to do is change how we manage filters in MapLayers. Currently only Mineral supports filters and those are hardcoded in the Navigator Window.
I want to make the application of filter generic and applicable to all layers if they can support it. This could include types in the Landmark layer or Labels in the Unit layer in addition to Minerals.
Then if we do that it can support your ideal of allowing the user to change colours.

**Comment by bevans2000** [comment]
@mokun Right I've done a lot of work on the Mineral map layer now. Including reworking how the MineralMap works.
My latest version is a lot faster but I want to to take a look and give it a try if possible. It's on a branch as part of this commit 75fcf1964f96b48ce0b51d0422ea2fe741ef1d1f
The old approach is still there as well but not used. If we go with this then we can also drop the MapArray in the in the MapData as well.

**Comment by mokun** [comment]
I don't have another eclipse to try out another branch at this moment.

May as well go ahead and commit to Master.

**Comment by bevans2000** [comment]
You should have 2 local clones of the repo and then 2 workspaces. That's what I do. Allows me to have short term work and long term work.
But ok, I will tidy it up and commit it this evening
