### ISSUE TITLE
IllegalStateException. not in a valid location situation to start EVA task OUTSIDE

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#14]
Created: 2014-12-13
Migrated from https://sourceforge.net/p/mars-sim/tickets/25/

On 3.07 build r3037,
I just had an IllegalStateException:

> Allison Nowakowski not in a valid location situation to start EVA task: OUTSIDE

1. Allison was right outside Schiaparelli Pt next to Ridge Runner
2. she was having a suit tear
3. She was having a Frostnip
4. she and Anna was going to deliver emerg supplies to another stranded vehicle
5. So both Allison and Anna were quoted as member of the vehicle Ridge Runner.
6. Anna was the only person inside Schiaparelli Pt and she was still loading the trip supplies

**Comment by larsnaesbye** [comment]
![vehicles](https://cloud.githubusercontent.com/assets/7767079/22947813/a46d297e-f2fc-11e6-8235-2ccea793fc14.png)
![anna was the only person in schiaparelli pt](https://cloud.githubusercontent.com/assets/7767079/22947812/a46c655c-f2fc-11e6-9efc-7348b8d90271.png)
![anna is still loading trip supplies there are 4 associated people](https://cloud.githubusercontent.com/assets/7767079/22947810/a46ba374-f2fc-11e6-84de-a6bffee34a57.png)
![allison was right outside schiaparelli pt](https://cloud.githubusercontent.com/assets/7767079/22947811/a46bcb38-f2fc-11e6-89de-52a098e50825.png)
![allison was right outside schiaparelli pt next ro ridge runner](https://cloud.githubusercontent.com/assets/7767079/22947815/a46f8124-f2fc-11e6-9973-f809d0daf1a8.png)
![allison was delivering emerg supplies but having frostnip](https://cloud.githubusercontent.com/assets/7767079/22947814/a46efa1a-f2fc-11e6-82c7-5c89309779ce.png)
![allison having frostnip](https://cloud.githubusercontent.com/assets/7767079/22947816/a483c79c-f2fc-11e6-8a5f-f3a6e33d4c89.png)

**Comment by mokun** [comment]
Allison is currently outside and she should have started the EVA while in the vehicle's airlock before stepping outside.

Since the creation of this issue, a few commits were made to address the issues with going into an airlock or stepping outside of an airlock.

Recommends keep this issue for the time being for further observation.

**Comment by mokun** [comment]
This issue is too old and the reason for the confusion of location was unclear. Will need more to uncover real underlying issues if it happens next time. Closing it for now.
