### ISSUE TITLE
The Debian package made doesn't have any maintainer scripts. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#140]
Most Debian packages have at least four maintainer scripts, ours doesn't have even one. 

https://www.debian.org/doc/manuals/maint-guide/dother.en.html#maintscripts

https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html

These are necessary so packages are installed, purged, removed etc. 

It basically governs the whole lifecycle of a .deb package.

I also don't see place for conffiles in mars-sim-headless_3.1.0~b2_all.deb

To see the contents of a deb package it's easy with - 

`$ dpkg-deb --fsys-tarfile mars-sim-headless_3.1.0~b2_all.deb | tar tvf -`

As that is what they really are. 

And seeing if any of the maintainer scripts are there or not is just a matter of doing - 

```
$ dpkg-deb -I mars-sim-headless_3.1.0~b2_all.deb postinst
dpkg-deb: 'mars-sim-headless_3.1.0~b2_all.deb' contains no control component 'postinst'
```

As can be seen neither of the things are there :(

**Comment by mokun** [comment]
See https://github.com/mars-sim/mars-sim/issues/1072.
