### ISSUE TITLE
UnitTest failing with latest JUnit libraries

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1406]
**Describe the bug**
Maven fails to run unit tests when JUnit libraries are updated. See outcome of PR #1383 & #1381

**Discuss any potential problems you have and have not ruled out**
This is probably due to the version of JUnit being used in the test cases. This could be a big change to upgrade the test classes. 
I don't think the actual test cases will need updating.
This has to be done on a branch to avoid a partial fix breaking the master branch.
Needs some research on the internet because they cannot be an unusual problem.

**Comment by mokun** [comment]
I wonder if both are being updated at the same time, it might satisfy certain criteria from maven surefire plugin.

**Comment by bevans2000** [comment]
Good idea. We should create a branch and change both at the same time to see if it works
