### ISSUE TITLE
Design Idea: Task boards, kanban board

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#141]
For making the way how tasks are assigned a bit more transparent, what about including Kanban like task boards into the simulation? 

What I am thinking about: A settler will get three (mental) task boards

- Private: For tasks that are planned to be done in the freetime. For example if multiple settlers plan to train together in the gym at a fixed time, this could be put into the task board for all in the group. 
- Personal: All tasks of his/her work or mission, that are assigned to him, might include tasks for scientific studies. 
- Emergency: Tasks that MUST be done to save his/her life or the life of somebody nearby. 

Additionally, there will be similar (digital?) task boards for settlements and missions, just like for the jobs and roles of a settlement or mission. How the jobs of these non-personal taskboards are assigned could vary: Some roles could work better by people picking their own tasks from the boards, other more complex roles would be better organized by a supervisor dispatching the tasks.

The tasks should be saved in four lists / columns on a Kanban board:
- Backlog : possible tasks to be examined when TODO is empty
- TODO: Tasks that should be ready to be executed
- In execution: Tasks that have already started and maybe are just waiting to be resumed
- Done: Tasks that are done are remembered for at least a Sol. Maybe this list could be used to produce a daily report or diary

When an emergency is declared, only the tasks in the emergency board will be handled, all others will be paused. The scope of the emergency defines which additional task boards will be made available. 

For example: While maintaining the reactor of a base, a fire starts, badly damaging the reactor and cutting of power for all systems including life-support. In first place, the settler which was performing the maintenance will start his own (mental) emergency task board with tasks fighting the fire and alerting the rest of the base. An emergency board for the settlement will get opened and filled with the tasks to fix the damage ASAP, alerting all settlers in the base. At the same time, the loss of power will declare an emergency for the whole base, making all settlers stop their current actions and be ready for assisting. All settlers might also start preparing for the worst, collecting EVA suits, etc. The commander will start assessing the warnings that caused the emergency, and decides to assign an objective to the task board of all Electrical power subsystem specialists of the settlement to restore power ASAP and a task to all life support specialists to set up emergency systems. All other settlers might get tasked to shutdown all non-essential power consumers by the commander and EPS specialists. While the fire is getting fought, the EPS specialists will look for alternative power sources. Maybe we could allow them to use rovers as emergency generators in that situation (And teach some of them this concept). Maybe there are enough EPS specialists around that one or two of them will already start thinking about how to restore the reactor again (lower priority tasks) while the fire is still there, brainstorming solutions, developing with different plans, etc...

All a bit more intelligent than possible right now, but I think it shows well why such a system of tasks boards might be a useful addition to the simulation core. Right now, the system how the next task is defined is a bit intransparent, with task boards it could be easy to show even in headless mode what settlers will do and have done, maybe by using the keyword "tasks" or even "personal tasks"/"private tasks"

**Comment by Urwumpe** [comment]
Well, its less about privacy there than about making sure that the right person gets the right task. of course, privacy and intrigues might make MSP more like a "Red Mars" simulator. But right now, its hard enough to make sure the settlers are no longer dying stoically from stupid errors.

**Comment by mokun** [comment]
So far, we use [MetaTaskUtil](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/meta/MetaTaskUtil.java) to create 3 separate lists of meta tasks based upon the work schedule of a person : 

3 Categories of Meta Tasks : 
- Work Hours
- Non-Work Hours
- Any Hours

Note that they are non-overlapping.

As you know, each Meta Task is mapped to a Task. Meta Task is a class that set up preconditions and filters  for calculating the probability or likelihood of selecting the corresponding Task.

The way a person decides to do depends on the `Work Shift` he has. e.g. if it's during his work shift, he obviously will perform tasks that are `Work Hours` related, etc. See [Tasks](https://github.com/mars-sim/mars-sim/wiki/Tasks)

For sure, we could change this architecture to allow room to implement something like what you have suggested above.

**Comment by mokun** [comment]
> of course, privacy and intrigues might make MSP more like a "Red Mars" simulator.

Yay. When we have a kanban in place, we can let player set some sort of `polices` for tweaking how the settlement deals with sensitive issues such as privacy :) 

> But right now, its hard enough to make sure the settlers are no longer dying stoically from stupid errors.
So true. It's also for the sanity of us developers to fine tune the so-called AI algorithm. 

At some point, we may be able to make use of some deep learning algorithm out there for intelligent decision making, rather than having to hard-code every case.

**Comment by Urwumpe** [comment]
> Yay. When we have a kanban in place, we can let player set some sort of `polices` for tweaking how the settlement deals with sensitive issues such as privacy :)

Why the player? Why not let the settlers vote on their own "Constitution of Mars"? No areology without representation.  ]:->

**Comment by Urwumpe** [comment]
> 
> 
> So far, we use [MetaTaskUtil](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/meta/MetaTaskUtil.java) to create 3 separate lists of meta tasks based upon the work schedule of a person :

So, practically, it would be about having something more general than MetaTask, that does not handle probabilities, but just represents a possible task.  

And that would need to be made more specialized towards a "ManagedTask" or so, that could be finished, cancelled or paused ... or be executed by multiple settlers.

**Comment by mokun** [comment]
> Why the player? Why not let the settlers vote on their own "Constitution of Mars"? No areology without representation. ]:->

Sure! I read "Moving Mars" by Greg Bear. Ideally, it would take a hundred or so developed cities on Mars to become the rival of Earth/Moon system.

But we may need to rewrite from scratch the core engine to simulate (but not micro-manage) the urbanization of settlements vs. managing the daily tasks of the settlers in mars-sim !

**Comment by mokun** [comment]
> No areology without representation. ]:->

It dawns on me that we can come up with an `Areology` score for each settlement really easy. 

How well the scientific study done on `Areology` should be "the main course".  Every settler should be hard pressed to unlock the mystery of Mars and its natural environment, and for all we know for every future martian generations.

**Comment by Urwumpe** [comment]
> 
> It dawns on me that we can come up with an `Areology` score for each settlement really easy.
> 
> How well the scientific study done on `Areology` should be "the main course". Every settler should be hard pressed to unlock the mystery of Mars and its natural environment, and for all we know for every future martian generations.

Well, that was what got me into diving into the MSP source code again after about 6 years. I felt like areology was a too futile and underrepresented in the simulation. For example, aerology did little to discover mineral deposits that we did not yet know. 

Or find brine layers underground, that could be refined to water and salts. Or, we know now, that Mars has a liquid core inside, but we know little else about the inner structure of Mars compared to the little we know about Earth - could scientists on Mars research it?

And of course: We have no science of "aerography" yet! There should be millions of yet unnamed landmarks on Mars... and of course, how could we find good places for road and new settlements without it?

**Comment by mokun** [comment]
> Well, that was what got me into diving into the MSP source code again after about 6 years. 

So at that time what did you recall about MSP that you were interested in working on ? 

To me, I myself started contributing in the summer of 2014. I guess I was hearing the news about MarsOne and got fascinated about the possibility of settling on Mars. 

> I felt like areology was a too futile and underrepresented in the simulation. For example, aerology did little to discover mineral deposits that we did not yet know.

What's your definition of Areology ? Is it just the geology ?

I hope to give more value to the idea of Scientific Study in mars-sim but is running out of idea at this moment. May be using it to improve the settlement's prestige and what else ?

Personally, I don't like the old idea of Tech Tree in Colony Building games. 

We have a `social` score already for ranking settlement. Now I'll add the `science` score to the bucket list.

**Comment by Urwumpe** [comment]
> 
> So at that time what did you recall about MSP that you were interested in working on ?
> 

I remember that I wanted to split rovers into components back then and allow customizing rovers. But I had really bad Java skills at that time and still a lot to learn. 

> 
> What's your definition of Areology ? Is it just the geology ?

Yes. The other field is areography, as counterpart to geography.

> 
> Personally, I don't like the old idea of Tech Tree in Colony Building games.

Same here. It always limits research for open-end games and it is pretty inflexible. I prefer systems that are about constant small evolutions.

**Comment by shirishag75** [comment]
when you say 250 millisols do you mean https://answers.yahoo.com/question/index?qid=20100305224705AA22Ol1 x 250 . If that is going to be the thing, it will too long for any commander to make his or her mark. In fact then why do we have a commander at all. If it's 250 days, then it makes more sense. Although, it would be nice if there are only few tasks that are open to him to take decision on, the ones who are probably at a more mature age so that can be accelerated. We could also let him or her track some of the activities he would like to have more hands-on decision making and let him or her stay engaged with the system till s/he is able to take decisions on. It will help in the engagement factor perhaps ? I do not know whether we want to have a hands-on or hands-off or do it either way.

**Comment by mokun** [comment]
*Sol* is a day on Mars.

Each meter has 1000 millimeters

Similarly, one *sol* has 1000 *millisols*

**Comment by shirishag75** [comment]
so 4 times a day, probably would work but then he needs to have all the info. and couple of competing decisions on which he can rule though. We could use both her/is decisions and the area in which the decision is made add a sort of skill point or some other sort of incentive or expertise so he gets more information and becomes better over time over decision-making on particular subjects and leaves other decisions to other experts. I mean this is what would be best in an ideal environment. 

Another question which I have been thinking about is deaths, back to earth could and would lead to institutional memory loss, have we thought how to compensate to that. https://www.higheredjobs.com/articles/articleDisplay.cfm?ID=468 

I don't know if there is a way for the captain when he is going to be rotated to earth or has shore live but guess they need to be thought of separately.

**Comment by mokun** [comment]
At a second thought,  if the player is in *Commander Mode*, it would actually make more sense to pause the simulation at the beginning of the commander's *work shift*.

When pause, then he can look at how the settlement is doing in detail.

**Comment by mokun** [comment]
> I don't know if there is a way for the captain when he is going to be rotated to earth or has shore live

@shirishag75 ,

That's an interesting idea to have people go on a shore leave on elsewhere such as the Moon village or a L5 space station or even back to Earth.

Remind us again when we are progressing toward implementing some more codes for launching the *Earth Return Vehicle* (ERV)  for a return mission.

**Comment by Urwumpe** [comment]
> Remind us again when we are progressing toward implementing some more codes for launching the _Earth Return Vehicle_ (ERV) for a return mission.

Can't we make this "Launching" capability a generic "function" of a "building" for allowing also other vehicles like the SpaceX starship type vessels? 

Or do a full overhaul there and treat the spacecraft like a special kind of Rover... or have a common super class with the rover for any mobile entity also appearing on the settlement map. The rovers would then be surface bound, the spacecraft would be orbital when moving.

**Comment by mokun** [comment]
@Urwumpe @shirishag75 

see https://github.com/YJPL/personal-kanban

May be we can make use of some markdown editor API out there to create kanban task lists or notes in mars-sim

**Comment by mokun** [comment]
@Urwumpe 

btw, your task board idea is still a pretty cool added-on to beef up the Task system.

May be each division (8 of them) can post needed tasks up there. Tasks can be picked based on specific roles or jobs.

We'll need to think how to incorporate assigning these outstanding tasks in Mind class or TaskManager class. 

A task board would certainly make what tasks need to be done more predictable and less spontaneous by settlers.

**Comment by Urwumpe** [comment]
Well, what kind of MetaTasks would we need to working with such a taskboard?

We could maybe use multiple sources for generating the task items in such a board, but we would still need some task available to the AI to pick the next suitable task (that can be finished by the Settler) from the board. 

Will robots pick their own tasks there? Or should robots get their own list of tasks assigned to them by a settler?

**Comment by mokun** [comment]
Let's see if we can flush out the conceptual design more. 

This could be seen as a task demand and supply system. 

First, we need to create a task generation system in place for each settlement to identify what tasks are needed. 

Each outstanding task will come with at least a goal or some goals, requirements, a posting date, a deadline, a start time and finish time set up.

For now, in terms of tending greenhouse, we have the method getCropsNeedingTending() in Settlement that we run everytime in TendGreenhouseMeta.

If a task has been posted for a while and doesn't get picked up for, say 10 sols, then the player know there's not enough resources to handle the work of the settlement. 

This could drive the settlement A.I. to suggest recruiting more players or do the recruiting itself if it's a A.I. settlement.

I would definitely like the idea of an task that has a clearly expressed purpose and responsibility involved, such as "Take care of the welfare of the Cabbage crop until it's being harvested", rather than just telling a person to go tend the crop for 20 msols.

I know this would require some overhaul of what each task is supposed to do currently but it's worth pursuing, at least in making each task more meaningful and self-contained.

**Comment by Urwumpe** [comment]
I wouldn't make such Taskboards mandatory, it could be useful to also have ad-hoc tasks possible. Also, I think the Taskboards should not be limited to certain entities, but rather be some fleeting object, that can be created if a demand exists - and deleted if its no longer needed.

For example, for a department of the settlement, it could be useful to have a Taskboard for regular tasks that have to be done, or certain incidents, like repairs and maintenance. 

On the other hand, it could be useful to have special Taskboards for projects, like for scientific studies or construction. Or a mission could have its own taskboard, like having certain loading/offloading tasks already planned in advance, with the offloading waiting for a trigger event, before it is ready.

For mapping the taskboards to the settlers (so that not every Settler feels responsible for all Taskboards), we could define organisational roles. For example, a Taskboard could exist that applies to every Settler in a certain Settlement. Another exists for all Settlers working in the ECLSS department. And then one Taskboard could exist for a certain team of Settlers currently building a new water tank. 

Also, these roles could then be used to define the "access rights" to a taskboard. For example, every Settler could report a malfunction. But only a member of the responsible department is allowed to schedule a maintenance task there. A commander of a settlement could have the right to check the progress in all taskboards, but is not allowed to place tasks there himself or execute those tasks. A special quality assurance role could be assigned to a settler that is the only role allowed to mark tasks to be really done. For example, for a manufacturing task, this could be the person that ordered the product to be produced.

I think it would be good to define a common interface, that can be included in any class, that can be the context of a taskboard. A special Swing panel could be defined that provides a standard UI for the user to interact with taskboards, that accepts any object that has this interface.

**Comment by bevans2000** [comment]
Interesting discussion. If we look at how the current TaskMeta pattern works it is not far away from having a backlog of potential Tasks. Each Task meta does roughly the following steps:
1. Loosely identify relevant activities in the Settlement that need doing. Key  here this is rough and only an estimate.
2. Apply any person specific modifiers to get a final score
When reworking the Tasks recently I was tempted to work step 2 into a generic common method as it is very similiar in all cases. If we just called step 1 in isolation that would give us our board of potential Tasks, I call these ```TaskDemand```.
Then a person would just apply the more generic modifiers to a list of local TaskDemand. The latter would have to a lifespan as they will need to age out.
With such a change it's super important to a avoid a big bang. We need a gradual approach, as they say "Evolution, not Revolution"

**Comment by bevans2000** [comment]
I think we are now closer to this concept based on the #740 changes. There are a set of ```TaskJob``` (potential Tasks) that are based on the Settlement's needs, e.g. maintenance, toggling process, malfunctions etc. Each OnDuty Person (& Robot) search for these tasks every time they need new work but there presence is due tot eh Settlement and not the Person. I make the distinction here of Person Tasks like Sleep, Eat, Reading that are mainly OffDuty.

So we could calculate a "shared" list of ```TaskJob``` that are calculated solely on the Settlement, probably periodically to keep them fresh. Then when a Person wants to do some more new work they would 'bind' to the SettlementTasks to create their own work potential. The binding would take the generic score and apply any Personal modifiers according to Job/Role to create a personalized score; basically the logic that is already in MetaTask. This means that some people may result in ignoring some of the Settlement Tasks because their personalized score is too low.

This all makes sense but the big question is how much will the Settlement Task list be re-used? If a calculated Settlement list is only used by 1 Person there is no saving of processing.
Nevertheless we need to complete #740 and probably #743.

**Comment by mokun** [comment]
That's good news ! 

> Tasks are removed from the Task board and it is refreshed when the clock ticks over

We may even save cpu util later if we set a time factor that a task won't need to be recomputed for 1 millisol, etc.

**Comment by mokun** [comment]
Or once a task is executed, it will be flagged and be automatically removed from the task board.

**Comment by bevans2000** [comment]
Having a time window could give rise to stale Tasks where the situation has changed. I think we will just remove selected Tasks from the board so they do not get picked by a different Person in the same Settlement.

**Comment by mokun** [comment]
So should we wait for this settlement task board to be implemented before we release 3.4.0 ?

It's been in our mind lately what our development roadmap should look like.

I'd like post a discussion thread to specifically discuss and flush out more ideas together in what to achieve such as what should be our short term and long term goals.

**Comment by bevans2000** [comment]
Maybe we should have a couple of days of stabilising the current code base and then move onto 3.5.0 after the weekend. Just do any minor fixes/tweaks and hold off any changes.
For this change, I've got is planned now so can wait until after 3.4.0. I might start it on a branch anyway so can hold off creating a Pull Request.

**Comment by bevans2000** [comment]
@mokun I've created an initial alpha on a branch of the concept of shared Tasks for a Settlement in the last commit.

**Comment by mokun** [comment]
> an initial alpha on a branch of the concept of shared Tasks for a Settlement in the last commit.

Awesome. is it possible to include a swing panel with a JTable for visualizing those tasks ?

**Comment by bevans2000** [comment]
> > an initial alpha on a branch of the concept of shared Tasks for a Settlement in the last commit.
> 
> Awesome. is it possible to include a swing panel with a JTable for visualizing those tasks ?

Yes that next step and also to provide a Console command. There is still some tidying up to do, also need some correction in the ```MetaTask``` hierarchy. I will also convert another MetaTask to the new approach before creating a pull request.

**Comment by bevans2000** [comment]
I have  kw converted most of the applicable MetaTasks now. It has a number of effects

- The simulation has got faster as it is achieving a reuse factor of about x4. That means for each refreshing of the Settlement Task shared pool it is used 4 times, hence avoiding 3 full scans of the expensive MetaTasks.
- The tasks on the backlog get cleared pretty much instantly by calling Robots or Persons.

I need to create a Settlement template that can deliberate create a backlog like a using a large number of greenhouses compared to the number of settlements.
Secondly I've hit a problem with the Repair meta Task because it scans Vehicles a person is in as well as settlements. This breaks the pattern so I've got to think of a way round it. I'm favouring changing the intermediate abstract classes (```SettlementTask``` & ```FactoryMetaTask``` ) to interfaces. Then a MetaTask can support both models. This is a better design.

**Comment by mokun** [comment]
> * The simulation has got faster as it is achieving a reuse factor of about x4. That means for each refreshing of the Settlement Task shared pool it is used 4 times, hence avoiding 3 full scans of the expensive MetaTasks.

Wow. So in terms of the clock thread, after the change, does the TPS gets higher at all TR, compared to what was before ?

**Comment by mokun** [comment]
btw, classes such as AnalyzeMapData or any future tasks that support mining missions, etc. can potentially use the task board. 

Do you think so ?

**Comment by bevans2000** [comment]
> > * The simulation has got faster as it is achieving a reuse factor of about x4. That means for each refreshing of the Settlement Task shared pool it is used 4 times, hence avoiding 3 full scans of the expensive MetaTasks.
> 
> Wow. So in terms of the clock thread, after the change, does the TPS gets higher at all TR, compared to what was before ?

I am gauging the  improvement by a shorter time for the execution of a clock pulse, I.e it takes less time to execute the logic

**Comment by bevans2000** [comment]
> btw, classes such as AnalyzeMapData or any future tasks that support mining missions, etc. can potentially use the task board.
> 
> Do you think so ?

Yes, basically they have to have a predetermined target because the SettlementTasks have been preassigned and score instead the Worker finding the target when the corresponding Task starts. So they are well suited to Settlement orientated Tasks. I think we could change Mission Planning to the new approach. One SettlementTask per mission to review.

**Comment by bevans2000** [comment]
I've got this working now on a branch and doing some testing. But I wanted to share how the Task creation has been changed. There are more parts now but I think it is easy to understand. The sequence diagram below shows how the ```SettlementTaskManager``` maintains a fresh list of ```SettlementTask``` and creates a personalised list for each Person that asks for one. The same sequence applies to Robots as well.

![Creation sequence ](https://www.plantuml.com/plantuml/png/dLJHQjmm47pNLmpq9KVIqFRn24SI0gMbWK02XRwjvVLPd2mPQTqqVzzOLfpBsJ7NFXm7AytExCx8br4eIDTOTSSXUlT0SNTBZhOSFcvmpoAM6tQoLyVfATROSgfzzyN9W5mfvuKHpBQMDOOQ7ib9XFZ-EbelxCIGHO-Cg89l83NlqQ0WlRD-g-QPZv8KzuJ0L_E8DRwo979vBk9we4NH2NJDUfUE0bU1OutAqbQHbR6GLK8IdVM-nPMrUqotB3HeQIc8qQOb9pFdkBZ0oTNPXwkRcy_NNrROR1Ocdw0dJhnUMRr3l4YwttkwQwoX0vFm6wFlMzQ6h8bS8dQ5jXGZw942mrTvYzbno5FBA5d8sAW2InSSVfWuur9KxChqMxgMTp_QyH_k5nGPKVl085U2sjO-fOCSuCQNfZ8SZWtauCTzt_2V8EFUZ_P_H0vARxFGaxVuCyozpbyS_3WQ6YONXtTW8foNj0QZgR0CyVZfmuw38Yi3XWCs-BGGiBlW_pmzfop7SZ7KK-2Oi_SoqAQ9SkOonw7jaw-PolyHaIrhYQ0NR0f1gRo3r3aCv-gXPfTrl5mT0asISdpUAqDFgYPSytEbrvfRVdDHo6aUlvrpzoTjXWw1oqxp3JVqkXhNsnaOPQh2CPTSzeuTd1p7ayT8N8t_pNtj85ShnSTsMvfxrC-FIEcV5YxPbLrZ_m80)

**Comment by mokun** [comment]
> creates a personalised list for each Person that asks for one.

So, in keeping a personalized list of the tasks that a person signs on to do, certain settlement tasks are simply distributed or transferred from the master list kept in the settlement to that person, right ?

**Comment by bevans2000** [comment]
No SettlementTasks stay in the settlement list until the demand is met, at which point it is removed.  The personalised list is a transient list only used while the Person selects a Task. The entries in the Personalised list are "borrowed" from the settlement whilst it chooses a new one.

**Comment by bevans2000** [comment]
@mokun What this change has shown (you can see from the Task Tab in the Monitor Window) is how unbalanced the various scores are coming out of the MetaTasks. In particular the TendGreenhouse is producing very large scores.
Also we should migrate the Manufacturing Task to be a Settlement one as it is limited by the number of available manufacturing capacity in the Settlement.

**Comment by mokun** [comment]
Great job !

btw, I noticed sometimes the # of tasks at the bottom left won't get real-time updated.

![image](https://user-images.githubusercontent.com/1168584/205473481-92c585dd-d790-4625-91da-34c7eecf0e0a.png)

It happens not just in this new task tab but the Event tab also. 

I wonder why

**Comment by bevans2000** [comment]
I hadn't noticed this. Probably something in the base class

**Comment by bevans2000** [comment]
Fixed now. Had to change how the model listener worked.
