### ISSUE TITLE
Update GitHub Actions to remove deprecated actions

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1411]
**Describe the bug**
The GitHub Actions are using deprecated actions based on an old version of node.js. These need updating to keep the actions working.

Also the Java CI action is not triggering on pull request events.

**Comment by mokun** [comment]
Right ! 

If I choose a pull in https://github.com/mars-sim/mars-sim/actions, it said the followings: 

```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-java@v3. 
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default
```

**Comment by mokun** [comment]
I wonder why some pulls but not all would fail. 

For instance, this [commit](https://github.com/mars-sim/mars-sim/actions/runs/10750361331) from @muybien3433 keeps failing the 3rd time for no reasons.

**Comment by bevans2000** [comment]
> I wonder why some pulls but not all would fail.
> 
> For instance, this [commit](https://github.com/mars-sim/mars-sim/actions/runs/10750361331) from @muybien3433 keeps failing the 3rd time for no reasons.

This is because of source branch is a remote repo. This is a mistake in the action that I will fix.
The action does not have access to the secrets, the flow need changing
