### ISSUE TITLE
build 4570 doesn't follow the save file instructions every hour. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#146]
See https://paste.debian.net/1052512 

The initial save I did was done manually. I had hoped that an hour down the line it will get saved but even after 4 hours don't see it being saved. Does the hourly save has anything to do with the speed at which the simulation runs or something. My logic says it shouldn't, but don't know about the game logic :)

**Comment by mokun** [comment]
The latest build [r4571](https://github.com/mars-sim/mars-sim/commit/dda678b69082d27516065c6323bc9771852cc7cd) should fix this issue.

**Comment by shirishag75** [comment]
Nope didn't get fixed. Still no file saves unless I do a manual save :(

**Comment by shirishag75** [comment]
sorry, it took couple of minutes but did see it did save automatically, thank you.
