### ISSUE TITLE
Remove Owner property from holders

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1467]
**Describe the rationale**
There area number of holder classes, Bin holder and Resource holder, each have a owner property on type Unit. This is there to facility the context in logging.
This means the use of Unit leaks into the holders and will cause problems when simplifying the Unit class.

**Describe the goal(s) you have in mind**
Remove the owner property so the holders do not need to reference Units.

**Describe the solution you desire to see**
Change the holder classes so the implement the Entity interface which means the holders can be used directly in logging statements.
This allows the owner property to be removed.
It also allows the get owner methods to be removed from the Person and Robot classes.

**Comment by mokun** [comment]
Sure. 

btw, I'd like to retain the Bin related class. In near future, I wanna retrofit it for field replaceable equipment. For instance, it can be used as a equipment rack of some sort for housing certain building functions.

**Comment by bevans2000** [comment]
I have a branch created with the proposed changes on if you want to look. Not suggesting drop the binholder but change they interaction
