### ISSUE TITLE
walkingSettlementInterior phase and meeting others

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#147]
I am/was in log finer when I saw this over and over - 

`2018-11-21T00:48:57.7 (Finer) [x2] Walk : [Schiaparelli Point] Rik Declercq was in Lander Hab 1 (in walkingSettlementInterior phase).`

I must have seen that statement about 200 lines or so.  

From what I could conclude from the above statement, Rik Declercq was in a lander hab sometime and he is walking back  somewhere but from where to where is not known. 

Interestingly, on the beryl console I see that he is meeting with Karen Andersen, although it is not clear whether he is on way to meet her or he is meeting her ?

On the beryl console - 
```

Connected with MarsNet > ​Schiaparelli Point

System : You are now connected with Schiaparelli Point. What would like to know ?

Connected with Schiaparelli Point > ​doing

You : What is everybody doing at this moment? 
Schiaparelli Point : Here are the task rosters.

(A). Settlers

  Do Sebatier Processing
 ------------------------
  -  Leonardo DaVinci

  Meeting with Karen Andersen
 -----------------------------
  -  Rik Declercq

  Eating a Meal
 ---------------
  -  Karen Andersen
  -  Lena LaGranda


(B). Bots

 Tending Crops
 ---------------
  -  GardenBot 001

 In Sleep Mode
 ---------------
  -  MakerBot 002
```

So apparently he is either on way to meet her or Karen Andersen is doing two things at the same time, meeting Rik and eating meal at the same time. 

On the term console I still see he is still walking. 

This would be confusing to whoever is seeing the output on the beryl console and the term console. 

It probably will be far better if there was a measurable distance which reduces over time from point A to point B so the user/gamer knows what is actually happening.

**Comment by mokun** [comment]
Walk is a sub-task.

If you look at the 'WalkMeta' class. It shows that it has a probably of 0.5 if a person is inside a settlement. 

I used to ask previous developers why not setting it to ZERO. 

I was told that it was a design decision to prevent a settler from appearing as being "stuck" at a place on the settlement map for too long. 

So if a person thinks of having NOTHING to do, he will simply pick the Walk task as WalkMeta has 0.5 while all other meta tasks have zero probability of getting picked.

Anyway, a settler usually needs to go from point A to point B to perform a task because most tasks are place-specific and prefers a person to go to a certain `Activity Spot` of a building to do that task.

**Comment by mokun** [comment]
> So apparently he is either on way to meet her or Karen Andersen is doing two things at the same time, meeting Rik and eating meal at the same time.

For now, if Joe is going to perform a `MeetTogether` task, it means that he is usually a superior such as a commander or a chief and it's business-oriented.

On the other hand, in case of `HaveConversation` task, Joe will pick someone, say, Mary, whom he has good relationship to begin with and would like to see and say hi. It's just a causal action.

So if they both are in the same settlement, Joe will set up a sub-task of 'Walk` over there.

From the perspective of Mary, she has nothing to lose in that someone wants to say hi to her. 

Note that a person can do one task at a time (except the sub-task).

In that case, she is still carrying out whatever task she's been assigned to do. She doesn't need to quit any task to just to let Joe meet her.

There are collaborative tasks in that a researcher sends out an invitation to an invitee. It goes through a more formal acceptance and to commit to that task.

For now, HaveConversation and MeetingTogether tasks are sort of unfinished and it depends on what we would like to model and achieve. Programmatically speaking, things don't happen or work the way we human beings naturally do anyway :D

**Comment by mokun** [comment]
> What does in walkingSettlementInterior phase mean 

walkingSettlementInterior() is a Java method inside the `Walk' task. When it shows up, it means that the simulation at that instant is going through the codes inside that method. It's for telling the developers that the method has been called up successfully.

**Comment by mokun** [comment]
Close it now. We can discuss more on whatever we specifically want settlers to do by opening a new ticket.
