### ISSUE TITLE
Salvage process framework should use Salvagable 

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#1471]
The salvage process classes are using the ```Unit``` directly. This will cause a problem when the unit class is reduced and no longer has entity specific fields.

The processes classes should be using the ```Salvagable``` interface as much as possible. This will ensure only the correct units can be processed.

**Comment by mokun** [comment]
So it goes the same with the manufacturing process and food production process class, right ?

**Comment by bevans2000** [comment]
When I did a test on the Unit dependencies the salvage processes caused a problem. They are too coupled to units and should be using the Salvageable interface, otherwise why do we have it
