### ISSUE TITLE
feature request - could we have a way to put a file.json or file.txt which has all the credentials it needs. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#150]
Could there be some way of automating or adding an input file so all the credentials it asks for are supplied in a manner so I don't have to keep doing it manually ?

The credentials it asks for - 

Which mode 

My answer Commander Mode - 

First Name - Shirish 
Last Name - Agarwal 
Gender - M
Age - 42 
Job - 15
Mars Society Affliated - y 
Country - 3 

Bonus tier - 

Change the Autosave Timer - 60 

Change the Simulation Speed - 1 

Save the Simulation - y 

I said bonus tier because it will be a bonus if these things can also be done. I know once these are feeded, the configurations kept till they are not changed but would be nice if we could somehow automate it as we have it add the above credentials in every new build.

**Comment by mokun** [comment]
Done. Closing this now. Re-open it if you have other things in mind to add.
