### ISSUE TITLE
CLI parameter to start with a custom set of initial settlements, astrodynamics

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#152]
Hello, as derived idea from #150, I would like to have a way to configure the initial settlements of a new simulation by a custom JSON file like:

`java %OPTS% -jar r9999_marssim_headless_java9.jar -new -scenario my_scenario.json`

For example: 
```
"initial-settlement-list" : {
"Alpha Base" : {"template" : "Mars Direct Base (Phase 1)", "location": {"body": "Mars", "lat" : "0", "long" : "0"}}
},
"new-arriving-settlement-list": {
"Schiaparelli Point" : {"template": "Mars Direct Base (Phase 1)", "location" : {"body": "Mars", "long" : "16.0", "lat":"-3.0"}, "population":"4", "robots": "2", "sponsor" : "Mars Society (MS)", "arrival-window": {"two-impulse":"10.0"} }
}
```
New settlements are not a must right now, I am not sure if the core already supports it well.  Its just one idea how it could be implemented into the simulation.

`arrival-window` and `two-impulse` should be a more realistic way to define the time of a arriving settlements: 10.0 means it leaves Earth right at the tenth Hohmann transfer launch window after simulation start. A window of 9.9 would launch into an accelerated transfer, 0.1 synodic periods earlier, which means less payload but shorter travel time. Different options could be "mars-cycler", "VASIMR" or "continuous", should the simulation framework support such Mars architectures as well.  This way, the arrival would not need to be at a specific sol, but could also be delayed and the arrival times would be more realistic considering astrodynamics. 

The resupply plan could then be taken from the settlement template.

**Comment by shirishag75** [comment]
It's a good idea but all of the terms above need to be explained. As of right now I don't think we have info. on lat. long of the existing settlements . 

There also would need to be some sort of boundaries and distance between settlements. 

One addition that I would like to add to the suggestion is if it's possible then use existing bots/robots or humans to guide the spacecraft so it doesn't split open. It also would be interesting if we could have count-down and how the spacecraft is doing during descent as well on the term-console. 

I guess that may be hard as we would need x, y and z. Also dunno if we are using real martian surface data or some make-believe data. Do know that Mars has been mapped thoroughly as far as the big features are concerned. 

Unlike the soon going to be Mars lander which basically would have no idea whether it will land on a smooth surface or crash on a boulder. I do know that they have systems in place (basically radar) which they hope will work but in our scenario it should be much much smoother affair. 

https://www.space.com/42515-nasa-mars-insight-ready-to-land.html

**Comment by Urwumpe** [comment]
> 
> 
> It's a good idea but all of the terms above need to be explained. As of right now I don't think we have info. on lat. long of the existing settlements .

Thats actually how the existing settlements had been defined in [settlements.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/settlements.xml) All I added was the field "body" to describe that a settlement might eventually not be located on Mars - but could for example be on Phobos.  Or on our Moon - why not?

The terms for describing how and when it will leave Earth are fairly simple:

- Two impulse is a classic transfer as done today. If aerobraking is used, the second impulse could be replaced by this.
- Mars Cycler is a concept related to Buzz Aldrin and describes a system of multiple space stations in an elliptic orbit between Earth and Mars, see [Mars Cycler](https://en.wikipedia.org/wiki/Mars_cycler)
- VASIMR is a magnetodynamic propulsion system concept, which is a bit more powerful than electric propulsion but still very efficient. There is a study about how it could (very theoretically) reduce the flight time to Mars to 39 days - but even a 90 day trajectory would be a great improvement. See: [VASIMR](https://en.wikipedia.org/wiki/Variable_Specific_Impulse_Magnetoplasma_Rocket)
- "continuous" would apply to any system using solar-electric or similar systems running most of the time at constant thrust, spiralling up to Mars. Because it could allow relatively short travel times with low payload mass, it might be a good option for out-of-window supply missions. 

> I guess that may be hard as we would need x, y and z. Also dunno if we are using real martian surface data or some make-believe data. Do know that Mars has been mapped thoroughly as far as the big features are concerned.

Well, you can say: If it can be seen from Earth, it has been named. But for example, the next named crater from Alpha Base would be about hundred kilometers away. 
 
> Unlike the soon going to be Mars lander which basically would have no idea whether it will land on a smooth surface or crash on a boulder. I do know that they have systems in place (basically radar) which they hope will work but in our scenario it should be much much smoother affair.

Actually we know pretty well, that the landing site of Insight is pretty safe. After all, it had been mapped by MRO, so the chance of big boulders is pretty low - but non-zero.

For regular Mars landings near a base, a simple ground based navigation beacon would allow much more accurate landings without having a GPS available. Think of a TACAN there for example.

**Comment by mokun** [comment]
Sure we can give the players more flexibility to configure the initial settlements.

> arrival-window and two-impulse should be a more realistic way to define the time of a arriving settlements: 

Very interesting you pointed out we can make use of more astrodynamics 

I was gonna say that in [settlements.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/settlements.xml), we have the following as you might have noticed already :  

```
	<!-- List of initial settlements in the simulation -->
	<initial-settlement-list>

		<settlement name="Alpha Base" template="Alpha Base (Phase 4)">
			<location longitude="0.0 W" latitude="0.0 N" />
			<population number="24" />
			<number-of-robots number="12" />
			<sponsor name="National Aeronautics and Space Administration (NASA)"/>
		</settlement>

		<settlement name="Plymouth Base" template="Mars Direct Base (Phase 2)">
			<location longitude="4.2 E" latitude="15.9 S" />
			<population number="8" />
			<number-of-robots number="4" />
			<sponsor name="Mars Society (MS)"/>
		</settlement>
		
		<settlement name="Schiaparelli Point" template="Mars Direct Base (Phase 1)">
			<location longitude="16.0 E" latitude="3.0 S" />
			<population number="4" />
			<number-of-robots number="2" />
			<sponsor name="Mars Society (MS)"/>
		</settlement>

	</initial-settlement-list>
```

The order of business is that the Simulation Configuration Manager (SCM) will pretty much first load these 3 settlements from settlements.xml. 

Then the player can edit them in the SCM table. 

Personally speaking, I wish we have incorporated the whole SCM table into the Mars Globe Main Menu.

The player may also change the make-up of the so-called `alpha crew` in the `Crew Editor`. 

The `alpha crew` is based on what it said in [people.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/people.xml). For instance, in case of Rik, 

```
		<person name="Rik Declercq" crew ="alpha" gender="male" personality-type="ESTP"
			settlement="Schiaparelli Point"
			sponsor="Mars Society (MS)"
			country="USA"
			job="Areologist"
			favorite-main-dish="Salsa Potato Salad" favorite-side-dish="Miso Soup" favorite-dessert="soymilk"
			favorite-activity="Operation">
			<personality-trait-list>
				<personality-trait name = "openness"	 value = "35"/>
				<personality-trait name = "conscientiousness"	 value = "60"/>
				<personality-trait name = "extraversion" 	value = "80"/>
				<personality-trait name = "agreeableness" 	value = "55"/>
				<personality-trait name = "neuroticism" 	value = "45"/>
			</personality-trait-list>
			<skill-list>
                <skill name="Driving" level="1"/>
                <skill name="Physics" level="1"/>
                <skill name="Botany" level="1"/>
                <skill name="Mechanics" level="1"/>
                <skill name="EVA Operations" level="1"/>
                <skill name="Cooking" level="2"/>
            </skill-list>
       </person> 

```
So at some point, our plan will need to factor in how we would like to insert our crew but we will worry about that later.

**Comment by mokun** [comment]
> As of right now I don't think we have info. on lat. long of the existing settlements .

@shirishag75 , we do define the location for every `Unit` (not just the Settlements) in mars-sim with lat. and long. in the [Coordinates](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/Coordinates.java) class

**Comment by mokun** [comment]
> This way, the arrival would not need to be at a specific sol, but could also be delayed and the arrival times would be more realistic considering astrodynamics.

@Urwumpe , yes it's true that we don't always know what sol it may land. The way being done now is not elegant enough and I've loved to apply more astrodynamics

Having said that, can you take a look at the [astroarts](https://github.com/mars-sim/mars-sim/tree/master/mars-sim-ui/src/main/java/org/mars_sim/msp/ui/astroarts) package ?

I incorporated it into mars-sim 3 years ago and was gonna to use it in the Astronomy Observatory.

At that time, I have wanted to tweak it for the resupply mission but it took too long. 

At least, we don't have to type up many of those equations from scratch if they are already there.

**Comment by Urwumpe** [comment]
@mokun sorry for the very late reply, had thought I had already answered. 

I took a look at the package, for most simple things its enough, but sadly in the wrong module - it would need to be refactored to core for this. 

Also I am not sure if the more advanced formulas could be build based on it. A [Lambert's Problem](https://en.wikipedia.org/wiki/Lambert%27s_problem) solver would be needed

**Comment by mokun** [comment]
I was gonna say that there are actually two *astroart* folders, one in `mars-sim-core`. The other one that draws the the UI is in mars-sim-ui`.

**Comment by bevans2000** [comment]
I feel we have covered the basic of this in the Scenario concept recently introduced

**Comment by mokun** [comment]
> Also I am not sure if the more advanced formulas could be build based on it. A [Lambert's Problem](https://en.wikipedia.org/wiki/Lambert%27s_problem) solver would be needed

@Urwumpe 
Nice to know we can use *Lambert's problem* to solve the transfer time and distance from Earth to Mars and vice versa.

Yes we could incorporate some astrodynamics aspect of the resupply mission in near future.

I have just looked over some resupply mission related classes and methods and shifted the starting orbit from "00" to "01" here at [this](https://github.com/mars-sim/mars-sim/issues/704).

It's also very nice you already laid out 4 those methods of reaching Mars.

Can you open a brand new project for tracking and link this thread there ?
