### ISSUE TITLE
Problems with starting game in Windows 10/Java 11

### ISSUE THREAD

**Issue by cookins** [mars-sim/mars-sim#156]
Hey.
i downloaded version 3.1.0 with bat file file.
when launching bat file nothing happens - just cmd windows appears for half second and gone,
i installed fresh Java ver - 11.0.1 for x64. i edited env variables in system props window - i add JAVA_HOME to System vars and C:\Program Files\Java\jdk-11.0.1 to it. then deleted java_path in PATH and added %JAVA_HOME%;%JAVA_HOME%\bin;. Restarted. Launched game with admin rights. still same. any advices?

**Comment by Urwumpe** [comment]
Yes - don't do it. 3.1 should be incompatible to Java 11. 

 Java 11 has no JavaFX, you need to get a OpenJFX then. Also the module system of Java 11 means some command line arguments to work around. 

If you are not too sure about your Java 11 knowledge, better download a recent "headless" build from here. That doesn't need OpenJFX is runs fine on most systems. 

https://github.com/mars-sim/mars-sim/releases/tag/4600

You can find some hints about Java 11 in the Wiki here and I can assist you should you run into trouble, I also test it with Java 11 at home, but I recommend you to get the JavaFX version from this release then. Again, Java 11 is not yet fully supported here - you need workarounds. As soon as the obsolete dependencies had been replaced, it should be easy to run Java 11 with OpenJFX.

**Comment by cookins** [comment]
i downloaded it. there jar file. what to do with it?

**Comment by Urwumpe** [comment]
Ooook... you know what a jar file is? In the simplest case of them all, you just open a command line window (cmd) and type 

`java -jar r4600_headless_java9.jar` 

there.

**Comment by mokun** [comment]
@cookins , running the JavaFX under Java 11 will be more complicated. But @Urwumpe will be more capable of helping you out.

**Comment by Urwumpe** [comment]
Just one small head-up: The released headless version works fine with Windows 10 and Java 11. 

No command-line magic needed, unless you want to have more memory for the VM. Its really just needed for the JavaFX version.

**Comment by cookins** [comment]
when i typing "java" in cmd - i got:
'java' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cookins** [comment]
but i have like it installed
just changed what i typed in first message.

**Comment by Urwumpe** [comment]
No big deal - maybe you just doesn't have a JRE in your PATH environment variable. Do you know how to change an environment variable in Windows 10? Just search for "env" or "environment variable" in your start menu to get to the right tool and select "environment variables" there.

And then, just select "Path" in your user variables or the system variables and add the path to your Java installation, for example, in my case its "D:\dev\Java\jdk-11.0.1\bin"

**Comment by mokun** [comment]
if I type in `java -version` in a command prompt, I get the following : 

```
Microsoft Windows [Version 10.0.17134.407]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\mkhelios>java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

C:\Users\mkhelios>
```

**Comment by shirishag75** [comment]
Look at these two stackoverflow questions and answers - 

https://stackoverflow.com/questions/53174353/upgrade-to-java-11-on-windows-10

https://stackoverflow.com/questions/53128835/switching-to-java-11-from-java-8

Please let us know if you are still stuck although @Urwumpe and @mokun could help you quite a lot. If need be, one of my friend's/clients desktop is also a windows 10 so if needed can do the same thing and see if seeting the PATH needs any more instructions.

**Comment by mokun** [comment]
@cookins ,

The latest test build [4945](https://github.com/mars-sim/mars-sim/releases/tag/4945) was compiled under openjdk 11 and no one should have any problems running it under java 11. 

In this test build, it uses the old fashion Java Swing as the UI. Since it has no JavaFX UI in it, therefore it does't need openJFX 11. 

For me, my development platform of choice has been Windows 10.  

Let us know if you still encounter any issues.

**Comment by shirishag75** [comment]
no problems here as well - 

```
~$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1, mixed mode)
```

**Comment by mokun** [comment]
Close this thread now
