### ISSUE TITLE
java.lang.IllegalStateException: can't get new task in Mind

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#159]
See https://paste.debian.net/1054092/

**Comment by mokun** [comment]
Looks like Lena's `Mind` crashed and no longer functioning. I wonder what happened to her. The Mind class in her cannot obtain a new task because the sum of the probability of each task is zero.

What was she doing before that ?

```
2018-12-02T21:03:57.7 (Warning) Mind : Lena LaGranda could not get new
action
java.lang.IllegalStateException: Mind.getNewAction(): Lena LaGranda weight
sum: 0.0
	at org.mars_sim.msp.core.person.ai.Mind.getNewAction(Mind.java:452)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:253)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:231)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:178)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:947)
	at
org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:2092)
	at
org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1616)
	at
org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.run(MasterClock.ja
va:862)
	at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecu
tor.java:1128)
	at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExec
utor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

how come paste.debian.net does preserve the format

**Comment by shirishag75** [comment]
That is because I use the Wrap text at 78 characters see https://paste.debian.net/ 

If you are interested this is the code which powers paste.debian.net https://github.com/formorer/paste.pl/

https://anonfile.com/v8ZdA7m8bb/default_sim has the default.sim 
https://anonfile.com/75ZfA4mcba/commander_profile
https://anonfile.com/DbZfA2mfbb/Mars_json

I hope the above give you some more info.

**Comment by mokun** [comment]
That build should prevent that from happening. Closed.
