### ISSUE TITLE
IllegalStateException, exiting Opportunity II from an airlock but is not inside

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#16]
Created: 2014-12-17
Migrated from https://sourceforge.net/p/mars-sim/tickets/29/

On 3.07 build r3041,
1). Crashed caused by IllegalStateException
2). Opportunity II had a fuel leak.
3). Dan Folker was inside and got rescued. He had already exited Opportunity II and went into Alpha Base as shown in the Settlement Map Tool.
4). He's currently eating a cooked meal.

Note : the stack trace shows if Dan was still "logically" inside the Opportunity II but is not inside.

> Dec 17, 2014 1:32:11 PM INFO org.mars_sim.msp.core.person.ai.mission.RescueSalvageVehicle Windstorm starting rescue mission for Opportunity II
> Dec 17, 2014 1:32:12 PM INFO org.mars_sim.msp.core.person.ai.mission.RescueSalvageVehicle Windstorm rendezvous with Opportunity II
> Dec 17, 2014 1:32:12 PM INFO org.mars_sim.msp.core.person.ai.mission.VehicleMission Emergency beacon deactivated on Opportunity II
> Dec 17, 2014 1:38:28 PM INFO org.mars_sim.msp.core.person.ai.mission.RescueSalvageVehicle Opportunity II salvaged at Alpha Base
> Dec 17, 2014 1:38:28 PM SEVERE org.mars_sim.msp.core.person.ai.task.ExitAirlock Dan Folker ending exiting airlock task prematurely, clearing as airlock operator for Opportunity II
> Dec 17, 2014 1:38:28 PM INFO org.mars_sim.msp.core.person.ai.mission.RescueSalvageVehicle Dan Folker rescued.
> Exception in thread "Master Clock" java.lang.IllegalStateException: Error while firing clock pulse
> Caused by: java.lang.IllegalStateException: Dan Folker is exiting Opportunity II from an airlock but is not inside.

[Dan Folker ending exiting airlock task prematurely.txt](https://github.com/mars-sim/mars-sim/files/775236/Dan.Folker.ending.exiting.airlock.task.prematurely.txt)
![event log](https://cloud.githubusercontent.com/assets/7767079/22948152/c43f9b28-f2fd-11e6-878b-a0c43ef948a6.png)
![opportunity ii malfunction](https://cloud.githubusercontent.com/assets/7767079/22948153/c442c794-f2fd-11e6-9e9b-6167465fa413.png)
![dan folker eating a cooked meal](https://cloud.githubusercontent.com/assets/7767079/22948154/c4437b9e-f2fd-11e6-8957-6f9c94116d85.png)

**Comment by mokun** [comment]
Opportunity II was either parked in the settlement when the fuel leak happens OR it has just been towed back to the settlement. 

I have recently seen a similar bug in that a person is supposed to have exited the vehicle but the code is still assuming he/she was inside the vehicle.

Recommend keeping this issue under observation.

**Comment by mokun** [comment]
A few code changes have been implemented to check for the Location State of a person/bot and make the code more robust. 

No one is researching/working on this issue. Will need to capture the state of a few field variables to nail down the exact reasons. 

Closing it for now.
