### ISSUE TITLE
Why does the sponsor become ESA instead of ISRO ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#161]
I wanted to save a new commander profile . I made a new profile, saved it quit the session. When I tried a new simulation and ask for previous commander profile, it showed me the old one, not the new one which got created. There seems to be an issue here. 

I even tried to save the simulation so that the time-stamp is saved and it will get renewed. It seems the only way to remove the old profile which is through - 

~/.mars-sim/saved$ rm -rf commander.profile

Even after making a new profile. The sponsor is ESA instead of ISRO. There seems to be an issue here. 

See https://anonfile.com/EfB6J9m0b4/commander_profile

**Comment by mokun** [comment]
The mismatch issue is fixed. Thanks for pointing that out.

**Comment by mokun** [comment]
Closing this now
