### ISSUE TITLE
org.codehaus.plexus.component.repository.exception.ComponentLookupException, ConstructionSiteTest issues

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#163]
See https://paste.debian.net/1054565/ for details and lemme know what is to be done.

**Comment by mokun** [comment]
Can you detail how you can get that ? 

It's like a partial cut-and-paste. There must be something that leads to this.

It could be an outage that prevents you from connecting to a maven repo out there.

**Comment by shirishag75** [comment]
umm... that is no longer an option. Openjdk 10 was removed from Debian. I dunno if it will work or not but there were some workarounds given at https://github.com/google/guice/issues/1133 , see at the lower end of the comments, perhaps there might be something which might be useful to us there.

**Comment by mokun** [comment]
> umm... that is no longer an option. Openjdk 10 was

You can still use openjdk 11 like before. What I meant is **compiling** the source code under java 9 or 10. 

In my mars-sim's pom.xml, I set the source and target to java 9 as follows : 

```
	<modelVersion>4.0.0</modelVersion>
	<groupId>net.sf</groupId>
	<artifactId>mars-sim</artifactId>
	<packaging>pom</packaging>
	<version>3.1.0-b2</version>
	<name>mars-sim</name>
	<url>https://github.com/mars-sim/mars-sim</url>
	<inceptionYear>2009</inceptionYear>
	<properties>
		<maven.compiler.source>9</maven.compiler.source>
		<maven.compiler.target>9</maven.compiler.target>
		<project.version>3.1.0-b2</project.version>
		<junit.version>4.12</junit.version>
		<timestamp>${maven.build.timestamp}</timestamp>
		<maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
		<!-- Set file encoding to UTF-8. See http://stackoverflow.com/questions/3017695/how-to-configure-encoding-in-maven#3018152 -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<!-- springboot.version>1.3.5.RELEASE</springboot.version -->
		<!-- mapstruct.version>1.1.0.Final</mapstruct.version -->
		<!-- lwjgl.version>3.1.2</lwjgl.version -->

	</properties>
```

**Comment by shirishag75** [comment]
I did that, no change :(

https://paste.debian.net/1054739/

**Comment by mokun** [comment]
Linking this issue with what was fixed in https://github.com/mars-sim/mars-sim/issues/107.

**Comment by mokun** [comment]
The ConstructionSiteTest runs smoothly now. Case closed.
