### ISSUE TITLE
Design Idea: Console Interface

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#164]
This thread serves as a one-stop shop for discussing what features and improvements to add to the console interface introduced lately in project 10 in https://github.com/mars-sim/mars-sim/projects.

There have been numerous discussions (as in #49, #74, #88, #149, etc) on what a headless console is supposed to provide.

A recent [build](https://github.com/mars-sim/mars-sim/commit/44722f9bf4a02573285fe52548cf64c8d87af919) added the ability to save the input history from previous simulation session. 

>Note: use Ctrl+left/right arrow to see the input history. 

Do discuss what to improve in terms of the console interface.

If you would like to request a feature that requires a console interface to access it, by all means ask and discuss it it there.

**Comment by shirishag75** [comment]
just compiled and ran the most recent build r5004 , while I'm able to see the science of a settlement but not who is researching it on the beryl console. 



![beryl-console-plymouth-base](https://user-images.githubusercontent.com/727626/64125323-1c4cdb00-cd99-11e9-87e2-6a61a47cb180.png)

**Comment by shirishag75** [comment]
I tried even with r5005, same issue as above :(

**Comment by mokun** [comment]
Yes. Will definitely add more science metric soon showcasing what's done on each settlement for the console users.

There are 5 categories that we will score on : 

| Category | Score |
| --- | --- |
| Successful | 3 |
| Failed | 1 |
| Canceled | 0.5 |
| Ongoing Primary Research | vary |
| Ongoing Collaborative Research  | vary |

Also, for an ongoing Research, we score each phase as follows :  
| Phase | Score |
| --- | --- |
| PROPOSAL_PHASE | 0.5 |
| INVITATION_PHASE | 1.0 |
| RESEARCH_PHASE | 1.5 |
| PAPER_PHASE | 2.0 |
| PEER_REVIEW_PHASE | 2.5 |

**Comment by shirishag75** [comment]
apart from that I wasn't able to know which settler was doing the biology science. I thought the new patch you made would give that info.

**Comment by mokun** [comment]
> which settler was doing the biology science. I thought the new patch you made would give that info.

will add that next for querying that in the console. 

For now, you can see it clearly by using `Science Tool` in the GUI Edition of mars-sim :D

**Comment by mokun** [comment]
@shirishag75 , 

Currently, say a player is connected with a party in the beryl console. 

If he want to switch over to another party, he will have to type '/q' to leave and go back to MarsNet first.

In the next build, it will be possible to switch over from one party to another seamlessly.

**Comment by mokun** [comment]
@shirishag75 , as you know the log-associated commands was previously accessible in MarsNet. 

I've just managed to move them to under the console menu (see option 5 below) since you requested that in the past.

Will commit this change in a moment.

> -------------------  C O N S O L E   M E N U  -------------------
> 
>   1: Connect with MarsNet
>   2: Change Autosave Timer
>   3: Save the Simulation
>   4: Change the Simulation Speed
>   5: Set Logging Options
>   6: Exit the Simulation
>      
> Enter your choice: ​5
> 
> 
> Type 'help' for instructions. Or 'q', '/q' or 'quit' to go back to console menu.
> Note : current global logging level is set to CONFIG
> 
> Enter your log command:  ​help
> 
> (A). There are 9 logging levels as follows : 
>  1. log off     : turn off logging.
>  2. log severe  : show serious failure.
>  3. log warning : show potential problem.
>  4. log info    : show informational messages.
>  5. log config  : show static configuration messages.
>  6. log fine    : show tracing information.
>  7. log finer   : show fairly detailed tracing information.
>  8. log finest  : show highly detailed tracing information.
>  9. log all     : show all messages.
> 
>    e.g. Type 'log info' to set all loggers to INFO level
> 
> (B). Other log commands :
>  a. 'log level'              : see current log level
>  b. 'log help'               : get instructions and logging keywords
>  c. 'log timestamp'          : change the logging timestamp for the simulation
>  d. 'log rate limit'         : change the rate limit on the log statements
>  e. 'log reset'              : reset the log level back to default
>  f. 'log <Class Name> <lvl>' : set the logger of a class to a level
>  g. 'log all airlock off'    : set ALL airlock-related class to OFF level
>  h. 'log all walk off'       : set ALL walk-related class to OFF level
>  i. 'log all eva off'        : set ALL airlock-related class to OFF level
>  j. 'log all mission off'    : set ALL mission-related class to OFF level
> 
> Enter your log command:  ​

**Comment by mokun** [comment]
@shirishag75 , 

After the latest commit, the keywords are now presented in the following readable format :

```
Connected with MarsNet > ​Schiaparelli Point

Switching over to Schiaparelli Point

Schiaparelli Point : How can I help you today?

Connected with Schiaparelli Point > ​/k
You : I need a list of the keywords. Would you tell me what they are ?


    ------------------------- K E Y W O R D S ------------------------- 

  For Settlements : 

  bed
       what are the quarters arrangement in this settlement

  carbon dioxide
       how is the carbon dioxide production and consumption

  dashboard
       what is on the settlement dashboard

  eva suit
       what is the level of the EVA Suit related effort

  job demand
       what are the job demand, positions filled and the deficits

  job prospect
       what are the job prospects of a particular job 

  job roster
       what job does each settler have

  maintenance
       what is the level of the maintenance effort

  mission now
       what are the currently on-going missions

  mission plan
       a list of proposed mission plans

  objective
       what is the settlement's objective

  oxygen
       how is the oxgyen production and consumption

  people
       who are associated with this settlement

  proposal
       what proposal have been represented

  repair
       what is the level of the repair effort

  researchers
       who are conducting reseach in this settlement

  robot
       what robots have been assigned to this settlement

  role
       what kind of roles are there in this settlement

  science
       how is the science score in this settlement

  social
       how is this settlement doing socially

  task
       what are the on-going tasks

  vehicle range
       what are the range of the vehicles we have

  water
       how is the water production and consumption

  weather
       the meteorological data from the weather station



  For all Parties : 

  date
       what date is it

  time
       what time is it

  where
       what is your location
```

**Comment by mokun** [comment]
@shirishag75 , I'm adding the `health` keyword. It will display the health indicators and their scores on a settler.

**Comment by mokun** [comment]
@bevans2000 , 

Thanks for your latest [commit](https://github.com/mars-sim/mars-sim/commit/29d6e24d5968745657d1174d803a18730ac5f67a)

Feel free to discuss the text-io console here.

@shirishag75 would be interested in knowing.

**Comment by bevans2000** [comment]
For me the `Console` represents a text based way to interact with the simulation. So having a UI panel on the console wouldn't be correct.
I see that a headless instance could ruin as a Docker image (I've started playing with this) inside a cloud container, e.g. AWS ECS and a remote connection could be established to manage & monitor the progress. The connection could easily just reuse existing SSH protocol. So on the client you could use a standard Putty or OpenSSH client to get the Console working there.
The new Chat framework I committed would work in this model by having a different implementation of the `UserChannel`.
In my mind a headless run should not need any GUI.
