### ISSUE TITLE
Are people going from place to place, Simulation hang, EVA, Partial pressure of O2, Reset clock thread

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#165]
This is from https://github.com/mars-sim/mars-sim/issues/107#issuecomment-445437439

I had to remove Settlement.java because of some changes I wasn't able to merge or update to the newest version. I again redid the changes as shared in https://github.com/mars-sim/mars-sim/issues/107#issuecomment-445433032 and was able to build/compile it as shared in https://github.com/mars-sim/mars-sim/issues/107#issuecomment-445433627

Now as far as people going from place to place is concerned, all I see are various people are either stuck in the airlock or getting into the airlock. I don't see statements of people actually going somewhere. This might be due to UnitManager or something else which I have no clue about. 

I am getting statements such as these - 

```
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [0.0° N 0.0° W] Jeff Teplin was waiting inside airlock. 
2018-12-09T21:34:01.8 (Finer) Airlock : The airlock in Lander Hab 3 in Alpha Base was pressurized
2018-12-09T21:34:01.8 (Finer) Airlock : [0.0° N 0.0° W] Jeff Teplin reported that the airlock in Lander Hab 3 had been pressurized.
2018-12-09T21:34:01.8 (Finer) BuildingAirlock : [0.0° N 0.0° W] The airlock had been pressurized and is ready to open the inner door to release Jeff Teplin.
2018-12-09T21:34:01.8 (Finer) BuildingAirlock : [0.0° N 0.0° W] Jeff Teplin was about to leave the airlock in Lander Hab 3 to go inside Alpha Base.
2018-12-09T21:34:01.8 (Finer) BuildingAirlock : [Alpha Base] Jeff Teplin had just exited the airlock at Lander Hab 3 and went inside Alpha Base.
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin was waiting inside airlock. 
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin was in Lander Hab 3 and somehow was not inside its airlock.
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin was trying to exit an airlock in exitingAirlockPhase().
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin was walking from Lander Hab 3 to an airlock at Lander Hab 3
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin was trying to exit an airlock in exitingAirlockPhase().
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin had exited the airlock and going to store the EVA suit
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin was going to retrieve the O2 and H2O in EVA Suit 015
2018-12-09T21:34:01.8 (Finer) EnterAirlock : [Alpha Base] Jeff Teplin in Lander Hab 3 had just stowed away EVA Suit 015.
2018-12-09T21:34:01.8 (Finer) Walk::enteringAirlockPhase : [Alpha Base] Jeff Teplin was in Lander Hab 3..
```

This is using `log finer` though but doesn't seem to make a lot of sense of what is going on. I will keep an eye out on it.

**Comment by mokun** [comment]
My concern is if the simulation hangs when your computer recovers from power saving. 

If the threads that runs in MasterClock die and the program could not detect it to restart the threads, then the simulation would hang.

One way to find out if the simulation is running or not is to observe if the settlers are doing different things when you check on them **twice** and compare the results. 

I use the keyword `task` to see what they are doing. A few seconds later, I check on them again.

```
Connected with Alpha Base > ​task

You : What is everybody doing at this moment? 
Alpha Base : Here are the task rosters.

(A). Settlers

  Cooking Midnight Meal
 -----------------------
  -  Evelyn Clinton

  Sleeping
 ----------
  -  Suzan Robideau
  -  Craig Jeffords
  -  Charlie Elston
  -  Steve Marley
  -  Victor Plantico
  -  Michael Sobecke
  -  Nathan Ellis
  -  Mikaela Backman
  -  Salvatorie Schifano
  -  Daniel Frankowiak
  -  Trati Tamtani
  -  Mary Carlson
  -  Douglas McMartin
  -  Jill Anglin
  -  Alene Spagnola
  -  James Barnard
  -  Heidi Hensley
  -  Michael Zummo
  -  Frank Krawczyk
  -  Criselda Kendzierski

  Eating Packaged Food
 ----------------------
  -  Ralph Radske

  Exercising
 ------------
  -  Shiromu Sae
  -  Patrick O'Hara


(B). Bots

 Tending Crops
 ---------------
  -  GardenBot 003
  -  GardenBot 0012
  -  GardenBot 0013

 Performing Maintenance On Hallway 8
 -------------------------------------
  -  RepairBot 0014

 Cooking Midnight Meal
 -----------------------
  -  ChefBot 006

 Package Wheat Into Granola Bar
 --------------------------------
  -  MakerBot 004
  -  MakerBot 0010
  -  MakerBot 0011

 Performing Maintenance On Hallway 2
 -------------------------------------
  -  RepairBot 005

 In Sleep Mode
 ---------------
  -  MedicBot 007
  -  ConstructionBot 008
  -  DeliveryBot 009


Connected with Alpha Base > ​task

You : What is everybody doing at this moment? 
Alpha Base : Here are the task rosters.

(A). Settlers

  Tending Crops
 ---------------
  -  Nathan Ellis
  -  Mikaela Backman
  -  Trati Tamtani
  -  Heidi Hensley
  -  Patrick O'Hara

  Teaching Manufacturing to Michael Sobecke
 -------------------------------------------
  -  Ralph Radske

  Reading
 ---------
  -  Frank Krawczyk

  Driving Dust Sprite
 ---------------------
  -  Jill Anglin

  Relaxing
 ----------
  -  Suzan Robideau
  -  Charlie Elston
  -  Salvatorie Schifano

  Sleeping
 ----------
  -  Evelyn Clinton

  Do Sebatier Processing
 ------------------------
  -  Craig Jeffords
  -  Mary Carlson

  Eating Packaged Food
 ----------------------
  -  Victor Plantico
  -  Daniel Frankowiak

  Manufacturing
 ---------------
  -  Michael Sobecke

  Teaching Cooking to Michael Zummo
 -----------------------------------
  -  James Barnard

  Exercising
 ------------
  -  Shiromu Sae
  -  Douglas McMartin
  -  Alene Spagnola
  -  Michael Zummo
  -  Criselda Kendzierski

  Eating a Meal
 ---------------
  -  Steve Marley


(B). Bots

 Tending Crops
 ---------------
  -  GardenBot 003
  -  GardenBot 0012
  -  GardenBot 0013

 Performing Maintenance On Infirmary 1
 ---------------------------------------
  -  RepairBot 0014

 Package Roast Peanuts Into Dry Food 
 --------------------------------------
  -  MakerBot 004
  -  ChefBot 006
  -  MakerBot 0010
  -  MakerBot 0011

 Performing Maintenance On Inflatable Greenhouse 2
 ---------------------------------------------------
  -  RepairBot 005

 In Sleep Mode
 ---------------
  -  MedicBot 007
  -  ConstructionBot 008
  -  DeliveryBot 009

Connected with Alpha Base > ​
```

**Comment by mokun** [comment]
> Now as far as people going from place to place is concerned, all I see are various people are either stuck in the airlock or getting into the airlock. I don't see statements of people actually going somewhere. 

They go from place to place to perform tasks.

Many tasks are **place**-specific. 

If you look at [buildings.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/buildings.xml).

```
			<administration population-support="2">
				<activity>
					<!-- temporarily using two of the activity-spots/chairs in the dining space for now -->
					<activity-spot xloc="-0.3" yloc="-3.15" />
					<activity-spot xloc="-1.1" yloc="-2.98" />
				</activity>
			</administration>

			<!-- The building has communication capabilities. -->
			<communication>
				<activity>
					<activity-spot xloc="-0.8" yloc="-2.4" />
				</activity>
			</communication>

			<!-- The building has facilities for cooking/preparing meals. -->
			<cooking capacity="2">
				<activity>
					<activity-spot xloc="3.13" yloc="-1.02" />
					<activity-spot xloc="2.8" yloc="-1.35" />
				</activity>
			</cooking>

			<!-- The building has facilities for eating meals. -->
			<dining capacity="4">
				<activity>
					<activity-spot xloc="1.54" yloc="-2.34" />
					<activity-spot xloc="0.55" yloc="-2.34" />
					<activity-spot xloc="1.54" yloc="-3.18" />
					<activity-spot xloc="0.55" yloc="-3.18" />
				</activity>
			</dining>

```

**Comment by mokun** [comment]
Let's filter off those movement related logs that are at `finer` and use `log fine` to highlight activities at the `fine` level. 

Granted, we'll need to go back to each task class to add in more code to generate logs at the `fine` level.

**Comment by shirishag75** [comment]
> Let's filter off those movement related logs that are at the `finer` level.
> 
> Let's use `log fine` to highlight those activities at the `fine` level.
> 
> Granted, we'll need to go back to each task class to add in more code to generate logs at the `fine` level.

True, but it will also make it easier to figure out stuff and that is what we want at the end.

**Comment by mokun** [comment]
> all I see are various people are either stuck in the airlock or getting into the airlock.

Currently, the astronauts in  ISS would spend something like 6 hours outside the space station to do work. 

For sure, prior to each EVA, a lot of preparation and tons of **planning** work would go in it from those in the ground mission control as well as those on-board the station.

In light of that, I would contest that the current design of mars-sim does NOT mimic reality. 

Any task involving EVA is more or less initiated by whatever the settlement needs **at the moment's notice**. 

Therefore, you may have noticed that there's such an unusual amount of activity through the airlock and wonder if it's a bug. 

Since each `Lander Hab` has an airlock, it actually helps relieving the egress and ingress **traffic**.

 > easier to figure out stuff and that is what we want at the end.

Yes I agree we're going to provide goals for players to achieve and our interface should at least support them to achieve those goals.

**Comment by Urwumpe** [comment]
Don't we already use a 100% oxygen atmosphere at reduced pressure in MSP right now? In that case a lot of the necessary preparations for EVA of the ISS is not necessary. The ISS astronauts require a 12h camp-out, because the ISS atmosphere is at Earth surface pressure with 70-80% nitrogen.

**Comment by mokun** [comment]
> Don't we already use a 100% oxygen atmosphere at reduced pressure in MSP right now?

Currently, the air composition is 58.8% oxygen under the low pressure atmosphere of 34 kPa. 

58.8% is used because it achieves **the same** partial pressure inside our lung as in 20.9% oxygen environment at the Earth's sea level.

**Comment by mokun** [comment]
> NASA does just not use 100% oxygen anymore because of the fire risk during launch and reentry.

was it how the Mercury capsule astronauts got killed ?

**Comment by mokun** [comment]
Btw, I do want to model the partial pressure of gases inside EVA suit. 

As you know, we only track the amount of O<sub>2</sub> and H<sub>2</sub>O and the temperature inside in the suit nothing else.

As a side note, I read that pneumatic spacesuits use gas to pressurize our body to at least `3 psi` or `20.7 kPa` to prevent our blood from boiling when being outside.

**Comment by Urwumpe** [comment]
I wish this boiling blood thing would never have been invented its absolutely wrong, since our blood vessels are pressurized anyway - they can't boil. You could have decompression sickness though, by nitrogen bubbling out.

20.7 kPa @ 100% oxygen is exactly the partial pressure of oxygen in the standard air.

> 
> 
> > NASA does just not use 100% oxygen anymore because of the fire risk during launch and reentry.
> 
> was it how the Mercury capsule astronauts got killed ?

Apollo 1, yes. Somebody smart decided to use 115 kPa of 100% oxygen to simulate the pressure difference in space (The astronauts used 100% oxygen at 21 kPa while wearing suits). Afterwards, they used 80% nitrogen at lift-off and vented the overpressure overboard during ascent, until they reached a 100% oxygen atmosphere at 21 kPa pressure.  During landing, they equalized pressure by letting ambient air inside.

**Comment by mokun** [comment]
btw, now we can use the following 3 keywords in MarsNet under the Expert Mode (type `/e`) in console.

If the simulation hangs, try `reset clock pulse` first.

If it doesn't work, then try ` reset clock listener`.

If it still doesn't work, try `reset clock thread`.

Meanwhile, use `log finer` to see if the settlers are moving around doing things.

**Comment by mokun** [comment]
@shirishag75 , 

There are still situations when my computer comes back from the power saving and the simulation hangs. 

In that case, I manually use `reset clock listener` to fix the problem without abandoning the simulation. 

This is just a temporary solution. Once I find out why it hangs and under exactly what situations it happens, we'll implement the automatic clock reset.

**Comment by mokun** [comment]
@shirishag75 and @Urwumpe, I've since experienced no more simulation hang. 

We can certainly open a new thread for discussing better atmospheric modeling inside EVA suit,e etc. 

Closing this now.

**Comment by mokun** [comment]
I just committed a [fix](https://github.com/mars-sim/mars-sim/commit/53ed2966b85a0436bfb885a99570210ffeaa8c83) yesterday on a major walking bug in that settlers coming back from an EVA would be frozen in the EVA Airlock in some situation. You may have seen it.
