### ISSUE TITLE
Boris Debic is exiting Osprey from an airlock but is not inside.

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#17]
Created: 2014-12-18
Migrated from https://sourceforge.net/p/mars-sim/tickets/30/

On r3041
1. Three vehicles namely Fire Star, Osprey, Dust Storm were malfunctioned
2. Janice and Jarred are on Fire Star which has comm sys failure
3. Dust Storm is having fuel leak.
4. Boris is at Schiaparelli Point. He is quoted "exiting Osprey from an airlock but is not inside." when MSP crashed
5. In the settlement map, Boris Debic was in the garage next to Opportunity II.
6. Osprey was parked outside. Boris already exited the vehicle and went inside the settlement.
7. Four EVA suits are on Fire Star.
8. Also Boris has a EVA suit.

Question 1 : how come they cannot get out and repair the vehicle?

I'm having a lot of 

> cannot walk to outside site from the occupants of Fire Star...

Q2 : The comm is down on Fire Star, can its emergency beacon be turned?

Q3 : how come it is NOT on? see pic

![why boris debic was in the garage next to opportunity ii jennifer blocking the way](https://cloud.githubusercontent.com/assets/7767079/22948282/2415084e-f2fe-11e6-94af-bada90847a8e.png)
![emer beacon off on fire star](https://cloud.githubusercontent.com/assets/7767079/22948277/240751ea-f2fe-11e6-8ddf-acfa0f9f2d2f.png)
![comm failure and fuel leak](https://cloud.githubusercontent.com/assets/7767079/22948278/240b3576-f2fe-11e6-8ae5-9924fc227bab.png)
![jarred on fire star cannot walk to outside site](https://cloud.githubusercontent.com/assets/7767079/22948279/240b16d6-f2fe-11e6-98e3-7cc6306756bb.png)
[cannot walk to outside site.txt](https://github.com/mars-sim/mars-sim/files/775243/cannot.walk.to.outside.site.txt)
![fire star osprey dust storm malfunction](https://cloud.githubusercontent.com/assets/7767079/22948280/240cdf8e-f2fe-11e6-9826-143345066d05.png)
![4 eva suits on fire star also boris has a eva suit](https://cloud.githubusercontent.com/assets/7767079/22948283/2421fdc4-f2fe-11e6-8da6-984274b9b419.png)

**Comment by mokun** [comment]
Changes have been made to ensure the Location State of a person is logically sound. Closing this issue.
