### ISSUE TITLE
[WARNING] The POM for net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 is missing, no dependency information available

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#171]
I was trying to compile mars-sims-ui, just by itself - 

While downloading the various assets I get the following warning - 

`[WARNING] The POM for net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 is missing, no dependency information available`

Why is it looking at sourceforge.net for it when I already have the required jar in mars-sim-headless/target/

It should instead be pointing at 

```
~/games/mars-sim/mars-sim-headless/target$ ls *.jar 
mars-sim-headless-3.1.0-b2.jar  mars-sim-headless-3.1.0-b2-jar-with-dependencies.jar
```

or better yet use relative paths, see https://stackoverflow.com/questions/11621639/how-to-expand-relative-paths-in-shell-script as an example of what I mean.

**Comment by mokun** [comment]
The `mars-sim-core` package is considered **the core engine**. 

So, when you compile the headless edition in maven, it will generate the mars-sim-core-[VERSION].jar and other jar files.

> [WARNING] The POM for net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 is missing, no dependency information available

It's just a warning. no big deal. I disable something so that it will no longer waste the time uploading to the sourceforge repo :D

**Comment by mokun** [comment]
Alright. I believe we're dealing with a few different issues.

`net.sf.mars-sim` is just how a package is named in the programming world (C++, C# and Java and others). It can be `com.github.marssim`

> [WARNING] The POM for net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2 is missing, no dependency information available

Also, this warning is to help the developer in case he forgets to add the dependency info on a package. That's all. 

The person who develops that particular maven plug-in won't know every situation. So a warning is given just in case.

Somewhere else in pom.xml for that package, it certainly specify where to look for that jar file or else we won't be able to put together all the jar files into one big jar file at all.

**Comment by mokun** [comment]
Closed.
