### ISSUE TITLE
get springboot to version 2.0 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#174]
we use an ancient version of spring boot which may have security issues or something like that. . It might be better to get more of an updated version, at least version 2.0.0 

https://spring.io/projects/spring-boot

**Comment by mokun** [comment]
We actually didn't use Spring Boot at this point. 

In the past, we experiment with Spring Boot as we were exploring the possibility of creating a front end in html5/Js/css. 

Having said that, we still have a few few left-over class files written in spring boot. We could have gotten rid of them but may be at some point in the future some developers may resurrect that project :D
