### ISSUE TITLE
Design Idea: how to model the repair work time scientifically

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#177]
How should we improve our repair work modeling ?

When a [malfunction](https://github.com/mars-sim/mars-sim/wiki/Malfunctions) occurs, we define and capture the following information :  
- the actor/witness is identified
- the place/location is identified
- an equipment (rover, EVA Suit, etc) or a building involved is identified. 
- the *scope* of the malfunction (namely, the [building function](https://github.com/mars-sim/mars-sim/wiki/Building-Function) or a system) being affected.
- the required repair work time is calculated*.

In mars-sim, we define 3 types of repair work that follows a malfunction: 

| Types of repair work|
| --- |
| General Repair|
| Emergency Repair |
| EVA Repair |

For instance, in case of the meteorite impact, from [malfunctions.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/malfunctions.xml)

```
	<!-- Meteorite Impact -->
	<malfunction name="Meteorite Impact Damage">
		<severity value="70" />
		<probability value="0.0002547" /> <!-- 0.0002547 or = 0.7% per year per sq m (assuming a 50 m^2 roof)  -->
		<repair-time value="400.0" />
		<emergency-repair-time value="100.0" />
		<eva-repair-time value="100.0" />
		<system-list>
			<system name="Building" />		
		</system-list>
		<effect-list>
			<effect type="life-support" name="Oxygen" change-rate="-.02" />
			<effect type="resource" name="Oxygen" change-rate="-.02" />
			<effect type="life-support" name="Air Pressure" change-rate="-.02" />
		</effect-list>
		<medical-complaint-list>
			<medical-complaint name="Minor Burns" probability="15.0" />
			<medical-complaint name="Laceration" probability="30.0" />
			<medical-complaint name="Broken Bone" probability="5.0" />
			<medical-complaint name="Panic Attack" probability="10.0" />
			<medical-complaint name="HeartBurn" probability="10.0" />			
		</medical-complaint-list>
		<repair-parts-list>
			<part name="fire extinguisher" number="1" probability="10" />
			<part name="airleak patch" number="5" probability="10" />
			<part name="aluminum sheet" number="2" probability="10" />
			<part name="polycarbonate roofing" number="2" probability="20" />
			<part name="plastic sheet" number="2" probability="10" />
			<part name="fiberglass" number="2" probability="5" />
			<part name="plastic pipe" number="2" probability="10" />
			<part name="valve" number="2" probability="5" />
			<part name="steel sheet" number="5" probability="10" />
			<part name="fiberglass cloth" number="5" probability="10" />
		</repair-parts-list>
	</malfunction>

```

-------- **EDITED** --------
The *repair-time* means the **General Repair** average time. 

The initial value will be randomly selected from 50 (1/8 of its max value) to 400.0 millisols (the max value. Same as for *emergency-repair-time* and *eva-repair-time*.

Note *: in [r4753](https://github.com/mars-sim/mars-sim/commit/041b57ffa8d526946eb646111fcf6de748ebd92e), we *compute* the work time on each 3 types of repair work as a malfunction occurs. The value of a repair time in the malfunctions.xml is just an average estimate. It is not the same each time. 

Q1 : Are there any *operational or empirical basis* in determining the repair time for each malfunction as seen in [malfunctions.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/conf/malfunctions.xml) ? What should be the major factors in deciding how long or how short for them ?

Also, as detail as what we have implemented, setting the maximum repair work time does not *scientifically* model the reality of our everyday life. 

Most of the time, we can estimate approximately how long a task would take, but as things unfold, it turns out it takes longer time to get it done.

Q2: instead of randomly picking the work time of each type up to the maximum allowed value, is there any mathematical relationship that we may use ? Gaussian distribution ? 

Note that there is a *triangular* conceptual relationship with [Malfunction](https://github.com/mars-sim/mars-sim/wiki/Malfunctions), [Maintenance](https://github.com/mars-sim/mars-sim/wiki/Maintenance) and [Reliability](https://github.com/mars-sim/mars-sim/wiki/Reliability) as you may have suspected.

**Comment by Urwumpe** [comment]
Q1: As about the empirical base there: I know Germany and USA have both official standard models to estimate the time needed for a task on Earth. But I don't remember the name of the US standard, I have learned it in an ergonomy lecture. Maybe I can find it again in the lecture notes. 

Q2: How accurate a time estimate is depends on how accurate you diagnosed the malfunction. Maybe it would be more realistic, if settlers would need to diagnose the extent of the damage and maybe need multiple attempts to find a small damage?

**Comment by mokun** [comment]
@Urwumpe ,

> How accurate a time estimate is depends on how accurate you diagnosed the malfunction. Maybe it would be more realistic, if settlers would need to diagnose the extent of the damage

That's good point about diagnosing a malfunction.

 We can actually create a new task called `DiagnoseRepair`. 

While the *Emergency Repair Work* need to be done ASAP, the amount of non-urgent *General Repair Work* and *EVA Repair Work* will need to be estimated ahead of time by qualified folks.

**Comment by mokun** [comment]
I'm also thinking how to make use of the failure rate/Reliability/MTBF for each part.

Right now, there is no visibility as to the overall reliability of an equipment such as *EVA Suit 13* or rover *Red Moon* is like.

To do so, we'll need to track the history of how an equipment has been used and how often and if there has been any malfunction and what parts have been replaced/repaired, etc.

Will there be something we should pursue to model ?

**Comment by Urwumpe** [comment]
At least the anomaly reports for STS are pretty detailled and also show how NASA categorized problems.

**Comment by mokun** [comment]
> At least the anomaly reports for STS are pretty detailled and also show how NASA categorized problems.

Right. They probably keep track of work time of all kind of tasks.

**Comment by Urwumpe** [comment]
> 
> 
> > At least the anomaly reports for STS are pretty detailled and also show how NASA categorized problems.
> 
> Right. They probably keep track of work time of all kind of tasks.

Not always. Its pretty hard to even find information about "true turnaround times" vs "planned turn around times".  The only coarsely defined times are during countdown, and even there, you have planned holds for including extra time needed for tasks or time for tasks that do not need to be executed in a carefully scheduled procedure.

**Comment by shirishag75** [comment]
> > > At least the anomaly reports for STS are pretty detailled and also show how NASA categorized problems.
> > 
> > 
> > Right. They probably keep track of work time of all kind of tasks.
> 
> Not always. Its pretty hard to even find information about "true turnaround times" vs "planned turn around times". The only coarsely defined times are during countdown, and even there, you have planned holds for including extra time needed for tasks or time for tasks that do not need to be executed in a carefully scheduled procedure.

I wouldn't bet againt that. NASA would have their own share of bean-counters and people who love stats. Whether they chose to disclose those stats. or not may be a different thing altogether. In fact, such record-keeping I would believe would be mandatory as it is stil relatively early days of space travel. Once it is routinized to a much larger extent than there may be laxatiy but not today.

**Comment by Urwumpe** [comment]
That they counted it and wrote a memo about it is sadly no reason that it exists in public. Especially the bookkeeping for the STS was VERY creative to conceal the true costs of each flight.

**Comment by mokun** [comment]
> Especially the bookkeeping for the STS was VERY creative to conceal the true costs of each flight.

It's hard to budget the program costs when it comes to huge program like STS. 

If they build more Space Shuttle, the cost for each would come down.

One question is did they have the technology know-how in that era to make Space Shuttle fully reusable ? 

Or is it just the thermal protection system using heat tile is never a good idea to begin with. 

I've heard that the cost of installing heat tiles is too much and also too labor intensive. 

May be it all comes down to HOW they rate the reliability of the heat tile with whatever performance testings to convince the tax payers :D 

Could be that's why SpaceX is now opting for Stainless Steel for the construction of their StarShip.

**Comment by shirishag75** [comment]
> > Especially the bookkeeping for the STS was VERY creative to conceal the true costs of each flight.
> 
> It's hard to budget the program costs when it comes to huge program like STS.
> 
> If they build more Space Shuttle, the cost for each would come down.
> 
> One question is did they have the technology know-how in that era to make Space Shuttle fully reusable ?
> 
> Or is it just the thermal protection system using heat tile is never a good idea to begin with.
> 
> I've heard that the cost of installing heat tiles is too much and also too labor intensive.
> 
> May be it all comes down to HOW they rate the reliability of the heat tile with whatever performance testings to convince the tax payers :D
> 
> Could be that's why SpaceX is now opting for Stainless Steel for the construction of their StarShip.

Is just having the technological know-how is enough ?  If you look at the movie 'Martian' you see people at NASA just trying to cover their ass. In fact, if it was real life than Matt Damon for all purposes would have been forgotten and killed. From what little I have seen, whether it is ISRO or NASA they are all beaureacracies and decisions are often made based on politics and penny-pinching rather than engineering. The most recent examples are and were the Boeing 737 and the discoveries made after that.  There is/was also the case of AF447 which also brings the idea that automation has its own issues, see https://hbr.org/2017/09/the-tragic-crash-of-flight-af447-shows-the-unlikely-but-catastrophic-consequences-of-automation  . This may also be relevant in #260 where we are talking about the single-base scenario.

**Comment by mokun** [comment]
@shirishag75 

Please see a related thread at https://github.com/mars-sim/mars-sim/issues/507 on improving reliability modeling.
