### ISSUE TITLE
Too many warnings and errors after r4759

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#178]
Just to be clear, 

I ran `mvn clean` in mars-sim 

then `git pull origin master` hence was able to update to r4759

then did `mvn clean package install -DcompilerArgs` in the same directory. 

and got so many warnings and exceptions thrown I have no idea what to do. 

Edit - it was so long that paste.debian.net refused to do it and had to go to pastebin to do the same. 

In paste.debian.net I got this - 

```
Request Entity Too Large
The requested resource
/
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.
```

For the first time in my life - 

https://pastebin.com/24hCQq6U

**Comment by mokun** [comment]
You can ignore the warnings. The new maven-compiler-plugin is ultra sensitive to the use of Java generics that don't define the object type.

I'll look into the NullPointerException in ConstructionManagerTest and elsewhere.

Can you switch to openjdk 10 ?

I run Java 10 and those NullPointerExceptions don't show up somehow.

**Comment by shirishag75** [comment]
> You can ignore the warnings. The new maven-compiler-plugin is ultra sensitive to the use of Java generics that don't define the object type.
> 
> I'll look into the NullPointerException in ConstructionManagerTest and elsewhere.
> 
> Can you switch to openjdk 10 ?
> 
> I run Java 10 and those NullPointerExceptions don't show up somehow.

nope, I have access to openjdk 11, 12, 7 and 8 those are the only options I have. 10 is no longer an option. Getting back to 7 and 8 is going to a problem as it would break lot of applications which are now fine with 11. Debian buster will be released with these 4, 7 and 8 will be probably for old-timers and compatibility reasons but people all know that the best move is to be on 11 for the long haul.

**Comment by shirishag75** [comment]
there are still a bunch of warnings and too many exceptions even with r4761.

**Comment by Urwumpe** [comment]
Anyway - I don't recommend ignoring warnings. Its better to fix them because even if they are a bit pendantic sometimes, they point out possible error sources. 

I also recommend including static code testing - I found most hidden problems in my commercial work by including FindBugs in the build pipeline. Especially the database and network code profited from it.

**Comment by shirishag75** [comment]
> Anyway - I don't recommend ignoring warnings. Its better to fix them because even if they are a bit pendantic sometimes, they point out possible error sources.
> 
> I also recommend including static code testing - I found most hidden problems in my commercial work by including FindBugs in the build pipeline. Especially the database and network code profited from it.

+1 . 

I did update to r4762 and while lot of issues have gone off, the deprecation warnings mean we need to fix them - 

https://paste.debian.net/1060474/

**Comment by mokun** [comment]
To compile JavaFX edition, we'll need to switch to using `mars-sim-main` as the entry point, instead of `mars-sim-headless`

Can you go to `mars-sim-main` directory and try running maven ? 

Chances are that we'll need to add in additional switches/arguments as listed in https://github.com/mars-sim/mars-sim/issues/173#issuecomment-451683919

[EDITED]
To compile/run the headless version, we only need the following 4 modules : 

```
		<module>mars-sim-headless</module>
		<module>mars-sim-core</module>
		<module>mars-sim-mapdata</module>
```

To compile/run the JavaFx version, we'll need the above 4 plus the one below : 
```
		<module>mars-sim-main</module>
		<module>mars-sim-headless</module>
		<module>mars-sim-core</module>
		<module>mars-sim-mapdata</module>
		<module>mars-sim-ui</module>
```

**Comment by shirishag75** [comment]
> To compile JavaFX edition, we'll need to switch to using `mars-sim-main` as the entry point, instead of `mars-sim-headless`
> 
> Can you go to `mars-sim-main` directory and try running maven ?
> 
> Chances are that we'll need to add in additional switches/arguments as listed in [#173 (comment)](https://github.com/mars-sim/mars-sim/issues/173#issuecomment-451683919)
> 
> [EDITED]
> To compile/run the headless version, we only need the following 4 modules :
> 
> ```
> 		<module>mars-sim-headless</module>
> 		<module>mars-sim-core</module>
> 		<module>mars-sim-mapdata</module>
> ```
> 

I think you meant 3 and not 4 as I was able to run with three - 

```
<modules>
                <!--module>mars-sim-android</module -->
                <module>mars-sim-core</module>
                <module>mars-sim-headless</module>
                <!--module>mars-sim-main</module-->
                <module>mars-sim-mapdata</module>
                <!-- module>mars-sim-network</module-->
                <!-- module>mars-sim-service</module-->
                <!-- module>mars-sim-ui</module-->
        </modules>
```

[INFO] Reactor Summary for mars-sim 3.1.0-b2:
[INFO] 
[INFO] mars-sim ........................................... SUCCESS [  0.523 s]
[INFO] mars-sim-mapdata ................................... SUCCESS [  2.841 s]
[INFO] mars-sim-core ...................................... SUCCESS [ 22.260 s]
[INFO] mars-sim-headless .................................. SUCCESS [ 12.293 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.073 s
[INFO] Finished at: 2019-01-15T01:34:55+05:30



> To compile/run the JavaFx version, we'll need the above 3 plus 2 more below :
> 
> ```
> 		<module>mars-sim-main</module>
> 		<module>mars-sim-headless</module>
> 		<module>mars-sim-core</module>
> 		<module>mars-sim-mapdata</module>
> 		<module>mars-sim-ui</module>
> ```

**Comment by mokun** [comment]
Closed.
