### ISSUE TITLE
ArrayIndexOutOfBoundsException in UnitTableModel.java whenever the new arriving settlement

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#18]
Created: 2014-12-26
Migrated from https://sourceforge.net/p/mars-sim/tickets/32/

1. I added two new arriving settlements.
2. I got ArrayIndexOutOfBoundsException when Eden arrived
3. It didn't stop the simulation and it kept going.
4. Then I got ArrayIndexOutOfBoundsException again when Miner's Delight arrived.
5. It's having problem with UnitTableModel.java line 81-85:

```
			// Inform listeners of new row
			SwingUtilities.invokeLater(new Runnable() {
				public void run() {
					fireTableRowsInserted(getUnitNumber() - 1, getUnitNumber() - 1);
				}
			});
```
In stack trace, it said the Monitor Tool was involved:

> at org.mars_sim.msp.ui.swing.tool.monitor.TableSorter.n2sort(TableSorter.java:149)
> at org.mars_sim.msp.ui.swing.tool.monitor.TableSorter.sortModel(TableSorter.java:313)
> at org.mars_sim.msp.ui.swing.tool.monitor.TableSorter.tableChanged(TableSorter.java:112)
> 

Note that I went away from my computer as soon as adding two new settlements in the Resupply Tool and did not check the stack trace. An hour later, I came back and the simulation is actually still running.

I NEVER open the Monitor Tool the whole time. I looked up the Settlement Map Tool and everything seems normal. But AS SOON AS I hit F4 to open up the Monitor Tool, the simulation crashed (see pic)

![simulation unresponsive](https://cloud.githubusercontent.com/assets/7767079/22948395/a0d23f6e-f2fe-11e6-8f88-7fe418b105df.png)

**Comment by mokun** [comment]
I recalled fixing this issue way back.

Just tested it. As of r3864, ArrayIndexOutOfBoundsException no longer exists after adding a new settlement and hitting F4 to bring up the Monitor Tool.
