### ISSUE TITLE
Functions being deprecated in org.mars_sim.msp.core.structure at least in r4845

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#182]
See https://paste.debian.net/1062838/ . This is when I was doing -

`~/games/mars-sim/mars-sim-headless/$mvn clean package install -DcompilerArgs -X`

then I have been doing  `~/games/mars-sim/mars-sim-headless$ mvn exec:exec`

It takes quite some time (again) for the beryl console to come up .

**Comment by Urwumpe** [comment]
Yeah, but when reading the sources,  it rather looks like a bad use of `@deprecated`

` * @deprecated TODO malfunction scope strings should be internationalized. `

**Comment by mokun** [comment]
Right. scope strings actually don't need to be internationalized. Will remove the @deprecated tag

**Comment by mokun** [comment]
Closing this now..
