### ISSUE TITLE
Mission not started due to Insufficient capacity to store methane, capacity: x, attempted: y

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#19]
Created: 2015-02-11
Migrated from https://sourceforge.net/p/mars-sim/tickets/50/

Tested on 3194
From stacktrace:

> Feb 10, 2015 10:52:07 PM org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage enoughCapacityForSupplies
> INFO: Insufficient capacity to store methane, capacity: 1600.0, attempted: 1600.0000601053239

Observations:

(1). From time to time, I received similar log msg when cooking and/or when planning for an excursion.

(2). I made some mistakes here and there in the past in comparing an amount retrieved from Inventory this way:

> if (amount == 0) ...

The amount will never be exactly zero. I hope I've rectified these problematic if-else clause in Cooking.java and PreparingDessert.java already...

(3). I can see how it should be done properly using SMALL_AMOUNT_COMPARISON in storeAmountResource() and retrieveAmountResource():

In Inventory.java line 579-592:

```
           if (remainingAmount > SMALL_AMOUNT_COMPARISON) {
                throw new IllegalStateException(resource.getName()
                        + " could not be totally stored. Remaining: " + remainingAmount);
            }

            // Fire inventory event.
            if (owner != null) {
                owner.fireUnitUpdate(UnitEventType.INVENTORY_RESOURCE_EVENT, resource);
            }
        } else {
            throw new IllegalStateException("Insufficient capacity to store " + resource.getName() + 
                    ", capacity: " + getAmountResourceRemainingCapacity(resource, useContainedUnits, 
                            false) + ", attempted: " + amount);
        }

```

In line 652:

```
          if (remainingAmount > SMALL_AMOUNT_COMPARISON) {
                throw new IllegalStateException(resource.getName()
                        + " could not be totally retrieved. Remaining: " + remainingAmount);
            }

            // Update caches.
            updateAmountResourceCapacityCache(resource);
            updateAmountResourceStoredCache(resource);

            // Fire inventory event.
            if (owner != null) {
                owner.fireUnitUpdate(UnitEventType.INVENTORY_RESOURCE_EVENT, resource);
            }
        } else {
            throw new IllegalStateException("Insufficient stored amount to retrieve " + 
                    resource.getName() + ". Storage Amount : " + getAmountResourceStored(resource, false) + 
                    " kg. Attempted Amount : " + amount + " kg");
        }

```

(4). However, even with this condition:

> if (remainingAmount > SMALL_AMOUNT_COMPARISON)

We are still NOT getting we want to, namely, allow the excursion to get started by "forgetting" the small differences in the amount requested.

(5). Do we have to change each ai tasks with Math.round() or can we change the logic once and for all in Inventory.java or somewhere to "relax" a little bit to avoid the "rounding error" of this kind ?

**Comment by mokun** [comment]
Scott might have done a commit to address this issue since then.

I recall this still happen once in a long while. 

I suggest we keep watching this.

**Comment by mokun** [comment]
Change has been made. Closing this issue.
