### ISSUE TITLE
Error when opening.

### ISSUE THREAD

**Issue by biran4454** [mars-sim/mars-sim#193]
**Describe the bug/issue**
Similar to https://github.com/mars-sim/mars-sim/issues/73 except I have installed java 11 and the correct files (r4925_gui_java11). I extracted them and run the jar file, except I get the errors described in the above topic. I have tried running java -jar r4925_gui_java11.jar but it just says "Error: Unable to access jarfile r4925_gui_java11.jar". What do I need to do?

 - OS version : [Win 7.]
 - Java version : [openjdk 11]
 - mars-sim build version : [r4925_gui_java11]

**Comment by Urwumpe** [comment]
I can't reproduce it, using the 7z download archive and Oracle Java 11.01.

What does `java -version` say (the complete information please), are you also using a 64bit version?

**Comment by biran4454** [comment]
java version:
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

I am running windows 64bit.

**Comment by Urwumpe** [comment]
OK... and the jar file is intact?

**Comment by biran4454** [comment]
Yes.

**Comment by Urwumpe** [comment]
OK, let us know should you observe something to help us help you.

**Comment by biran4454** [comment]
Ok. I would try using java 10 but I can't get it anymore.

**Comment by Urwumpe** [comment]
No, Java 10 wouldn't work except with a Java 10 jar file. 

But you could try launching with 

`java -jar r4925_gui_java11.jar`

Missing the extension .jar can cause the error.

**Comment by biran4454** [comment]
Turns out it was automatically using Java 8 that I didn't realise was still on my system. I still get an error from the command line, which closes immediately, saying something like: Error: could not load main class D:\r4925_gui_java11\r4925_gui_java11 (I'm storing it in D:\ drive).

**Comment by Urwumpe** [comment]
I need the full error there, you know how to do copy and paste in a console window? 

Caused by java.lang.ClassDefNotFoundException is just the error class, the missing class is more interesting for debugging.

**Comment by biran4454** [comment]
I know how to copy in the console window, but it doesn't stay open long enough. Is there a way that I can recall the last output in cmd.exe?

**Comment by Urwumpe** [comment]
cmd.exe shouldn't close after running java. You should be able to scroll up if it fails. Or you can redirect the output into a text file by appending `> output.txt` to the java command.

Can you find the error in .mars-sim/logs?

**Comment by biran4454** [comment]
If I run the file from windows explorer, it gives the error and immediately closes. If I run it from cmd.exe using "java -jar r4925_gui_java11.jar " it just says it can't access it.

**Comment by biran4454** [comment]
Also, where is .mars-sim/logs ?

**Comment by Urwumpe** [comment]
In your user directory "C:\Users\<yourname>"

**Comment by Urwumpe** [comment]
> 
> 
> If I run the file from windows explorer, it gives the error and immediately closes. If I run it from cmd.exe using "java -jar r4925_gui_java11.jar " it just says it can't access it.

Aaaaaaaaaaah. I think I have an idea. Sorry. What is your current working directory when starting the jar file (just type CD as command)? Did you switch into the folder where you have unpacked the file?

**Comment by biran4454** [comment]
No. I didn't. Ok, I'll try that now.

**Comment by biran4454** [comment]
Brilliant! Works now. Sorry for all the trouble, my mistake!

**Comment by mokun** [comment]
@biran4454 , we'll post a new build soon, after we worked out some other bugs. Stay tune and feel free to comment and discuss whatever you have in mind by starting a new thread.

**Comment by biran4454** [comment]
Thanks @mokun,  I'll have a look around. Great simulation, by the way! Could do with a few more user controls, but still an interesting application.
