### ISSUE TITLE
Broken mission/construction interface

### ISSUE THREAD

**Issue by Paculino** [mars-sim/mars-sim#195]
**Describe the bug/issue**
Mission interface will not allow user to finalize mission (but the simulation will still create missions). Interface will allow going to page two for studies, but that page is not usable.

**Affected Area**
Mission interface

**Expected behaviors**
Mission interface to continue as in earlier version

**Actual/Observed Behaviors**
Final or next button in the interface does nothing.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : 10.0.2+ 13 amd64
 - mars-sim build version : r4925_gui_java10

**Comment by Urwumpe** [comment]
Have (hot-) fixed this in the repository, but its not in a release yet.

**Comment by Paculino** [comment]
Does this mean I should download the sourcecode and compile it myself, to include the hotfix?

**Comment by Urwumpe** [comment]
You can at least try if this fixes your problem already. I have no plans doing a release.

**Comment by mokun** [comment]
@Paculino , can you post a pic here to illustrate the situation that you run into when you are manually creating a mission ?

I wonder if (1) it has to do with a bug in the interface or (2) just that some resources may be lacking and therefore it grays out the button that prevent the creation of the mission. 

If the latter is being the case, I'll need to make things more clear for users to see.

We'll release a new test build soon for we resolve some other bugs. 

Appreciate for posting and do let us know more.

**Comment by mokun** [comment]
@Urwumpe , do you encounter similar bug already and is it what [this](https://github.com/mars-sim/mars-sim/commit/02a206edcf89e30907835fe8ad7bdf467804c7d2) is addressing ?

**Comment by Urwumpe** [comment]
@mokun  Exactly, I did not file a issue for this one first. The logic for creating the wizard tabs had been left in a WIP state, I just completed the function as far as needed.

**Comment by mokun** [comment]
@Paculino , 

There are multiple reasons as to why you can't click the `Final` button. 

We will need to communicate those reasons to users. 

One issue I can see is that the simulation game loop is running while the player is in the Mission Tool creating for a new mission. 

For example, the player selects a Explorer rover and, say, 10 seconds later, he is still selecting a site to explore. 

If that vehicle is being picked for a new mission generated by AI within the same time period, 
when the player finishes picking the site to the explored and click `Final` button to finalize the mission preparation, it will simply *throw an Exception* and won't allow the mission to be created.

We'll find a better way to handle that.

Thanks for pointing that out.

**Comment by mokun** [comment]
@Paculino , 

I've tracked down what went wrong. Players can now manually start a construction mission after the last commit.

Thanks for bringing that to our attention.

**Comment by mokun** [comment]
Closed.
