### ISSUE TITLE
Design Idea: Settlement Template

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#199]
The footprint of the first generation of settlement on Mars will probably be `cylindrical`.

This is because we have to fit the habitation, service. power or lab modules, etc.. that fit within the circular shell of a rocket. 

To build the first colony, we will need to guide these modules to arrive on a particular landing zone and link and connect them together upon arrival. 

No doubt, this `building block` construction approach is touted as being the most feasible and cost-effective. 

At some points in future as we learn to erect structures safely and efficiently on Mars, the construction of giant, semi-inflatable dome won't be far off. 

In recent years, numerous research have focused on how to 3-D print self-contained housing units on Mars that rely on in-situ material made from Mars Regolith.

In mars-sim, perhaps it's time we begin to explore on how to program different kinds of settlement layouts like the one below : 

![Mars colony layout a](https://user-images.githubusercontent.com/1168584/62668968-a3e22e00-b942-11e9-95b0-bdfaa85b85df.jpg)

Let's brainstorm ways to upgrade mars-sim's core engine so as to construct settlements to look different from the `cookie-cutter` or `modular` approach that most strategy games rely on.

Feel free to comment and provide feedback.

**Comment by Urwumpe** [comment]
Well, that looks like architecture, maybe we should treat it like that: Define rooms from basic geometric shapes, intersections and subdivisions.  For example, starting out with a basic circle and then dividing this into rooms by creating rings and replacing the rings inside the circle then by ring segment rooms... Of course, this means such a building would be that: One complex shaped building. Currently we have multiple buildings with dedicated functions.

**Comment by mokun** [comment]
> Define rooms from basic geometric shapes, intersections and subdivisions. 

Yay If we could come up with an interface for users to draw out a building with some basic shapes, it would be fun !

**Comment by Urwumpe** [comment]
Sure, but not easy. I think the modular approach is still better for getting ahead, since we would need some kind of 2D CAD tool to let players design buildings or view designs by AI.

**Comment by mokun** [comment]
Yay we'll need to first develop an layout editor in order to open up the freedom of designing the settlement layout. 

For now, we're stuck with the modular concept and there are still a lot of things that we may improve.

For instance, we have recently added a new separate building called "EVA Airlock" and removed the EVA function from the Lander Hab in [5178](https://github.com/mars-sim/mars-sim/commit/991727e60114ffc44587f447a8098a8cef4ecac6). 

The reason for this change is that we have encountered an occasional bug as settlers are inside the airlock of a Lander Hab. 

Separating the EVA into its own building/room may help isolating the root cause for future debugging.

Besides, the Lander Hab is really very very full.

No airlock room is drawn in Lander Hab. 

The location where the settlers begin to do the EVA is actually inside the gym area.

**Comment by mokun** [comment]
@Urwumpe @bevans2000 ,

I'm expanding the so-called *Settlement Template* in settlements.xml.

In reality, at least for now, there are just phases of a building a settlement, such as *Mars Direct Base (Phase 2), Alpha Base (Phase 4), etc.* .

I can see that each sponsor (or space agency) should follow its own path of development, rather than demanding them necessarily adopt the *Mars Direct Plan*.

So, I'll leave the *Mars Direct Plan*.to Mars Society's led effort.

The rest of the sponsor would be FREE to adopt their own methodology and system architecture for developing a colony on Mars.

I know this is just one small step toward the right direction in modeling since it reflects better what the reality is.

And we can readily imagine how difficult SpaceX as a business enterprise would do things very differently from a government led human settlement program on Mars.

**Comment by mokun** [comment]
With various phases of development made possible, beyond that of the Mars Direct Base plan, we could explore having totally different 
building layouts. 

Here are some of the inspirational art work.
A. Central Dome
![central dome 2](https://user-images.githubusercontent.com/1168584/121569911-2b34d880-c9d6-11eb-8fd3-f1c7a311318b.jpg)

B. Hyperloop on Mar with Cliff Dwelling 
![hyperloop on Mars and Cliff dwelling](https://user-images.githubusercontent.com/1168584/121570022-4c95c480-c9d6-11eb-94d7-0e431c14ae55.jpg)

C. Distributed Domes and Round Transportation Terminal 
![round terminal](https://user-images.githubusercontent.com/1168584/121570118-69ca9300-c9d6-11eb-81b4-fd28173a367e.jpg)
