### ISSUE TITLE
lintian issues with mars-sim-3.1.0-preview-5

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#2]
Lintian is a debian package-checker and does small checks to ensure that basic things are right. 

The following things were found to be an issue by lintian -

```
> lintian mars-sim-main-3.1.0-preview5.deb                                                                                   [95%]
W: mars-sim-main: changelog-not-compressed-with-max-compression changelog.gz
W: mars-sim-main: syntax-error-in-debian-changelog line 6 "found change data where expected next heading or eof"
W: mars-sim-main: latest-debian-changelog-entry-without-new-version
W: mars-sim-main: package-contains-timestamped-gzip usr/share/doc/mars-sim-main/changelog.gz
W: mars-sim-main: package-contains-timestamped-gzip usr/share/man/man1/mars-sim.1.gz
E: mars-sim-main: manpage-not-compressed-with-max-compression usr/share/man/man1/mars-sim.1.gz
```
 max-compression could be done by using gzip -9 

As far as time-stamping is concerned, that could be avoided by doing gzip -n when generating gzip. 

How time-stamps are bad can be known more at https://wiki.debian.org/ReproducibleBuilds 

changelog.gz itself has only old version data in it -

```
/usr/share/doc/mars-sim-main> zless changelog.gz   

mars-sim-main (3.1.0) unstable; urgency=low

  * Version 3.1.0 Debian package release.
 -- Manny Kung <mkung@users.sourceforge.net>  Wed, 21 Sep 2016 09:50:40 -0700

  * Initial debian package release.
 -- Scott Davis <scud1@users.sourceforge.net>  Wed, 31 Jul 2013 14:04:40 -0700

changelog.gz (END)
```
So at the very least, these need to be fixed.

**Comment by mokun** [comment]
Sure. I'll do a max-compression and update the timestamp before the next preview version. Thanks for pointing that out.

**Comment by mokun** [comment]
Question: is the time stamp supposed to be manually or automatically inserted ? 

I'm following the standard in [https://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog] (https://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog) when it comes to defining the time stamp.

For now, I'm rewriting the changelog as follows: 

> mars-sim-main (3.1.0-p6) unstable; Urgency : low
> 
>   * Version 3.07 debian package release.
>  -- Scott Davis <scud1@users.sourceforge.net>  Sun, 18 Jan 2015 00:00:00 -0700
> 
>   * Version 3.06 debian package release.
>  -- Scott Davis <scud1@users.sourceforge.net>  Mon, 12 May 2014 00:00:00 -0700
> 
>    * Version 3.05 debian package release.
>  -- Scott Davis <scud1@users.sourceforge.net>  Sun, 15 Sep 2013 00:00:00 -0700
> 
>   * Initial debian package release.
>  -- Scott Davis <scud1@users.sourceforge.net>  Wed, 31 Jul 2013 14:04:40 -0700
> 

When we are about to release the 3.1.0, we will update the date/time above if needed. 

I can definitely use some help from you in doing whatever deemed necessary in using Lintian according to [https://wiki.debian.org/ReproducibleBuilds/Howto](https://wiki.debian.org/ReproducibleBuilds/Howto) if you are available.

**Comment by shirishag75** [comment]
counter-question, how are you building the package ? Are you using debhelper because that should make sure that those lintian errors don't show up. 

```
[$] aptitude show debhelper                                                                                                        
Package: debhelper                       
Version: 10.2.5
State: installed
Automatically installed: no
Multi-Arch: foreign
Priority: optional
Section: devel
Maintainer: Debhelper Maintainers <debhelper-devel@lists.alioth.debian.org>
Architecture: all
Uncompressed Size: 1,483 k
Depends: autotools-dev, binutils, dh-autoreconf (>= 12~), dh-strip-nondeterminism (>= 0.028~), dpkg (>= 1.16.2), dpkg-dev (>= 1.18.2~), file (>=
         3.23), libdpkg-perl (>= 1.17.14), man-db (>= 2.5.1-1), po-debconf, perl
Suggests: dh-make
Breaks: dh-systemd (< 1.38)
Replaces: dh-systemd (< 1.38)
Provides: debhelper:i386 (= 10.2.5)
Description: helper programs for debian/rules
 A collection of programs that can be used in a debian/rules file to automate common tasks related to building Debian packages. Programs are included to install various files into your package, compress files, fix file permissions, integrate your package with the Debian menu system, debconf, doc-base, etc. Most Debian packages use debhelper as part of their build process.
```

See if that helps. I am hoping you have a full-fledged Debian Install/VM somewhere.

**Comment by mokun** [comment]
We use a maven plug-in called jdeb from in mars-sim-main's pom.xml. It's inside the <plugins> tag which in turn is inside <build> tag :

see https://github.com/tcurdt/jdeb

>           <plugin>
>             
> 				<groupId>org.vafer</groupId>
> 				<artifactId>jdeb</artifactId>
> 				<version>1.5</version>
>                 <executions>
>                     <execution>
>                         <phase>package</phase>
>                         <goals>
>                             <goal>jdeb</goal>
>                         </goals>
>                         <configuration>
>                             <dataSet>
>                                 <data>
>                                     <src>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</src>
>                                     <type>file</type>
>                                     <mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/share/mars-sim-main</prefix>
>                                     </mapper>
>                                 </data>
>                                 <data>
>                                 	<src>${project.basedir}/src/deb/mars-sim</src>
>                                 	<type>file</type>
>                                 	<mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/bin</prefix>
>                                         <filemode>755</filemode>
>                                     </mapper>
>                                 </data>
>                                 <data>
>                                 	<src>${project.basedir}/src/deb/copyright/copyright</src>
>                                 	<type>file</type>
>                                 	<mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/share/doc/mars-sim-main</prefix>
>                                     </mapper>
>                                 </data>
>                                 <data>
>                                 	<src>${project.basedir}/src/deb/changelog.gz</src>
>                                 	<type>file</type>
>                                 	<mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/share/doc/mars-sim-main</prefix>
>                                     </mapper>
>                                 </data>
>                                 <data>
>                                 	<src>${project.basedir}/src/deb/marsicon.png</src>
>                                 	<type>file</type>
>                                 	<mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/share/doc/mars-sim-main</prefix>
>                                     </mapper>
>                                 </data>
>                                 <data>
>                                 	<src>${project.basedir}/src/deb/mars-sim.desktop</src>
>                                 	<type>file</type>
>                                 	<mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/share/applications</prefix>
>                                     </mapper>
>                                 </data>
>                                 <data>
>                                 	<src>${project.basedir}/src/deb/man/mars-sim.1.gz</src>
>                                 	<type>file</type>
>                                 	<mapper>
>                                         <type>perm</type>
>                                         <prefix>/usr/share/man/man1</prefix>
>                                     </mapper>
>                                 </data>
>                             </dataSet>
>                         </configuration>
>                     </execution>
>                 </executions>
>             </plugin>
>

**Comment by shirishag75** [comment]
have filed a ticket at https://github.com/tcurdt/jdeb/issues/253

**Comment by mokun** [comment]
Can you explain what it mean by "make deb packages reproducible by NOT having gzipped time-stamp " ? Can you break down the goals into 1, 2, 3, 4... for me?  e.g. which one needs what ?

If I deleted the changelog.gz and mars-sim.1.gz from the /src/ directory, it will fail to create the debian package.

> 
> [INFO] --- jdeb:1.5:jdeb (default) @ mars-sim-main ---
> [INFO] Creating debian package: C:\mk\eclipse-SDK-4.6.0-win32-x86_64-distro-2.4.0-SNAPSHOT\eclipse\workspace\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~SNAPSHOT_all.deb
> [ERROR] Failed to create debian package C:\mk\eclipse-SDK-4.6.0-win32-x86_64-distro-2.4.0-SNAPSHOT\eclipse\workspace\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~SNAPSHOT_all.deb
> org.vafer.jdeb.PackagingException: Failed to create debian package C:\mk\eclipse-SDK-4.6.0-win32-x86_64-distro-2.4.0-SNAPSHOT\eclipse\workspace\mars-sim\mars-sim-main\target\mars-sim-main_3.1.0~SNAPSHOT_all.deb
> 	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
> 	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
> 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
> 	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
> 	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
> 	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
> 	... 14 more
> Caused by: java.io.FileNotFoundException: Data source not found : C:\mk\eclipse-SDK-4.6.0-win32-x86_64-distro-2.4.0-SNAPSHOT\eclipse\workspace\mars-sim\mars-sim-main\src\deb\changelog.gz
> 	at org.vafer.jdeb.maven.Data.produce(Data.java:189)
> 	at org.vafer.jdeb.DataBuilder.buildData(DataBuilder.java:259)
> 	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:470)
> 	... 16 more

So what happened was that in the past, I use 7zip in Windows OS to manually create changelog.gz and from changelog and mars-sim.1.gz from mars-sim.1. I do use the ultra setting when compressing it.

**Comment by mokun** [comment]
We've since been using "gzip -n ..." to compress those files as recommended. Issue closed.
