### ISSUE TITLE
should we try compiling with java 12 ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#200]
Should we try to compile it with/under java 12 or wait ?

java 12 is already in debian and in testing -

https://jdk.java.net/12/
```

$ apt-cache policy openjdk-12-jdk
openjdk-12-jdk:
  Installed: (none)
  Candidate: 12.0.2+9-1
  Version table:
     12.0.2+9-1 900
        900 http://cdn-fastly.deb.debian.org/debian testing/main amd64 Packages
        100 http://cdn-fastly.deb.debian.org/debian unstable/main amd64 Packages
```

As of right now, I haven't installed it as can be seen but it's possible that the next release of Debian would have java 12 as default. considering Debian usually likes to have even release numbers for stability and there are 2 years for the new release to come.

**Comment by Urwumpe** [comment]
I would say we should test it in a branch, maybe it isn't a big change. The latest Java versions come with smaller changes than in the past, after the changes for 9 and 11, things might calm down a bit.

**Comment by shirishag75** [comment]
I am and would be open for that.

**Comment by mokun** [comment]
but does debian support openjfx 12 ?

**Comment by Urwumpe** [comment]
Do we need it? I thought Swing and headless are the prime versions anyway now and JavaFX optional.

**Comment by shirishag75** [comment]
> but does debian support openjfx 12 ?

yeah, it does. I just would have to install it. Whatever is in testing is automatically supported by debian-java team. Also see the thread which starts at https://lists.debian.org/debian-java/2019/07/msg00012.html

**Comment by mokun** [comment]
> Do we need it? I thought Swing and headless are the prime versions anyway now and JavaFX optional.

True! We don't need openjfx right now. 

I've separated all the JavaFX contents into the `mars-sim-javafx` submodule and is not touching it for the moment.

This is because when we started transiting to JavaFX, we were using `SwingNode` to `JFXPanel` to mix the Swing and JavaFX components together and it was a mess.

For the time being, we are strictly using Swing for prototyping our UI. 

Now that [WebLAF](https://github.com/mgarin/weblaf) has just released v1.2.9, I intend to use it to custom-make a good skin for mars-sim so that it looks more attractive.

At some points, we can go back to JavaFX and rebuild everything in JavaFX if we want to, or we can switch to LibGDX or something.

**Comment by mokun** [comment]
@shirishag75 @Urwumpe ,

We're ready to supporting Java 12 now. I've just tested it this afternoon.

The good thing with Java 12 is the *ultra low-pause/ low-latency* Garbage Collector (GC) called [Shenandoah](https://jaxenter.com/java-garbage-collection-157057.html)

**Comment by shirishag75** [comment]
Umm... seems we will have all sorts of versions from java 13 to java 17 coming in Debian from time. The next LTS version of Java will be 17 which will be in 2021. See https://en.wikipedia.org/wiki/Java_version_history

I also asked and got a link of the same at https://lists.debian.org/debian-java/2019/07/msg00009.html

so yeah, while we may using java 13/14 for testing there will be breakage with existing stuff in Debian testing as well as in Debian bullseye which should be released next year. I could help with testing but will surely will break lot of stuff in the process, let me know what your thoughts are ? Both Java 13 and 14 are in sid and supposedly will remain in sid/unstable throughout this lifecycle .

**Comment by shirishag75** [comment]
Btw I was able to compile it, have not run it yet though but it compiled without an issue in java 14. Just 

`$ mvn package `

was enough to get it to do all the work :)

**Comment by mokun** [comment]
@shirishag75 

I just did a commit in support of the use of Java 14 and is aiming for the next minor release.

**Comment by shirishag75** [comment]
Debian now has java 18. Have you tried using that - 

```
$ java --version
openjdk 18.0.2-ea 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Debian-2)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Debian-2, mixed mode, sharing)
```

**Comment by bevans2000** [comment]
The latest 3.5.0 build runs on Java 20 without problem. It will be released as a JAR within a matter of days
