### ISSUE TITLE
error while trying to run r4965, no main manifest attribute

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#201]
I compiled mars-sim r4965 using the following command - 

`~/games/mars-sim$ mvn clean package install -DcompilerArgs -X`

I am just sharing the last few lines of success completion - 

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for mars-sim 3.1.0-b2:
[INFO] 
[INFO] mars-sim ........................................... SUCCESS [  0.664 s]
[INFO] mars-sim-mapdata ................................... SUCCESS [  4.656 s]
[INFO] mars-sim-core ...................................... SUCCESS [ 34.068 s]
[INFO] mars-sim-headless .................................. SUCCESS [ 18.839 s]
[INFO] mars-sim-ui ........................................ SUCCESS [ 23.486 s]
[INFO] mars-sim-main ...................................... SUCCESS [ 36.602 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:58 min
[INFO] Finished at: 2019-08-17T03:05:05+05:30
[INFO] ------------------------------------------------------------------------
```

I am using the instructions shared in https://github.com/mars-sim/mars-sim/issues/173 . 

After this I tried to run - 

```
~/games/mars-sim/mars-sim-main/target$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar 
no main manifest attribute, in mars-sim-main-3.1.0-b2-jar-with-dependencies.jar
```

Then tried to run - 

```
$ java -jar mars-sim-main-3.1.0-b2.jar
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.main.MarsProject -Xms256m -Xmx1024m -new
Exception in thread "main" java.lang.NoClassDefFoundError: org/mars_sim/headless/StreamConsumer
	at org.mars_sim.main.MarsProjectStarter.main(MarsProjectStarter.java:153)
Caused by: java.lang.ClassNotFoundException: org.mars_sim.headless.StreamConsumer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

I do get the window but its separated or detached from the console and the Exception it shares, maybe something needs to be fixed. 

I have to manually kill the session as there is no way to quit the game, at least nothing which intuitively tells you how you can quit the game. 
```

$ ps aux | grep java
shirish   6433  7.6  2.3 6678984 188452 pts/6  Sl   03:07   0:07 java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.main.MarsProject -Xms256m -Xmx1024m -new
shirish   6482  0.0  0.0   6076   888 pts/6    S+   03:09   0:00 grep java
```

`$ kill -9 6433`

**Comment by mokun** [comment]
> $ java -jar mars-sim-main-3.1.0-b2.jar

We can't run this jar because by itself, it's only one of the 4 maven submodules. It requires other dependencies.

You can see `mars-sim-main-3.1.0-b2-jar-with-dependencies.jar` being the one having the needed dependencies built in and is much bigger in size than others. 

It should have called something like `mars-sim-3.1.0-b2-jar-with-dependencies.jar` but `mars-sim-main` is where the entry main() method is located and the pom.xml where a few maven plug-ins, such as `maven-assembly-plugin`, `maven-jar-plugin`, `exec-maven-plugin`, etc are located.

One can rename this jar to, say, `r4965_swing_java11.jar` and publish it as a pre-release.

**Comment by shirishag75** [comment]
My question is, currently what is the best way forward so we have output on console as well as have the screen attached to the console output. Is there a way or is it supposed to be like this.

**Comment by Urwumpe** [comment]
Can you describe this a bit more precise? I am not sure I understand what you want to have there.

Right now we have standard logging to stdout and a swing-based terminal window. Anything else could sure be done in headless, but would require modifications, like having multiple terminal streams.

**Comment by shirishag75** [comment]
What I wanted is a behavior as an e.g. when you have gdb or firefox or any program running from the console or command prompt. Unlike say torbrowser-launcher which detaches the window and doesn't allow any sort of debugging, the command prompt allows for knowing what is happening. Something like this -

```

[New Thread 0x7fffe99bd700 (LWP 15571)]
[New Thread 0x7fffe91bc700 (LWP 15572)]
[New Thread 0x7fffe89bb700 (LWP 15573)] 
```

**Comment by shirishag75** [comment]
> > $ java -jar mars-sim-main-3.1.0-b2.jar
> 
> We can't run this jar because by itself, it's only one of the 4 maven submodules. It requires other submodules as well as dependencies.
> 
> You can see `mars-sim-main-3.1.0-b2-jar-with-dependencies.jar` being the one having all the submodules and the needed dependencies all packaged together and is much bigger in size than others.
> 
> It should have called something like `mars-sim-3.1.0-b2-jar-with-dependencies.jar` but because `mars-sim-main` is the submodule where the entry main() java method is located.
> 
> One can rename this jar to, say, `r4965_swing_java11.jar` and publish it as a pre-release.

which of the two should be renamed and would that be enough ?

**Comment by mokun** [comment]
> which of the two should be renamed and would that be enough ?

of course it's `mars-sim-3.1.0-b2-jar-with-dependencies.jar`. Can you look at how many MB this file is ?

**Comment by shirishag75** [comment]
I did the change but still get the error -

`no main manifest attribute, in r4966_swing_java11.jar`

Here are the steps I took - 

```
~/games/mars-sim/mars-sim-main/target$ ls -lh mars-sim-main*.jar
-rw-r--r-- 1 shirish shirish 16K Aug 17 23:44 mars-sim-main-3.1.0-b2.jar
-rw-r--r-- 1 shirish shirish 75M Aug 17 23:44 mars-sim-main-3.1.0-b2-jar-with-dependencies.jar
```
After this - 
`
~/games/mars-sim/mars-sim-main/target$ mv mars-sim-main-3.1.0-b2-jar-with-dependencies.jar r4966_swing_java11.jar`

And then - 

```
~/games/mars-sim/mars-sim-main/target$ java -jar r4966_swing_java11.jar 
no main manifest attribute, in r4966_swing_java11.jar
```

Can you tell me what I am doing wrong here.

**Comment by mokun** [comment]
Fixing the pom.xml in `mars-sim-main` and `mars-sim-headless` right now as we speak. 

Good catch and thanks !

**Comment by mokun** [comment]
Just fixed it.

Now you may to play with publishing the jar in https://github.com/mars-sim/mars-sim/releases as a practice. 

Just make sure the jar is renamed to include `r4969`.

**Comment by shirishag75** [comment]
what I would suggest is to have the jar renamed when it builds up. I have seen quite a few packages/applications which use either the revision number or the commit id or both to tell to users when it was packaged. Right now, there is no way for us to do that :(
