### ISSUE TITLE
noaudio doesn't seem to be respected 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#205]
I gave the following command at the prompt - 
`
~/games/mars-sim/mars-sim-main/target$$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar -load noaudio `but I still had to use CTL+M to get rid of the audio in order to understand what is happening. If no audio is not to be respected, maybe it should die. I tried both ways - 
`
~/games/mars-sim/mars-sim-main/target$$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar -load noaudio`

as well as - 
`
~/games/mars-sim/mars-sim-main/target$$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar -load -noaudio`

neither of them worked. 

although do still have the following - 

```
$ java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar -help
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.main.MarsProject -Xms256m -Xmx1024m -help
2019-08-18T04:30:51.7 (Config) MarsProject$SimulationTask : Starting Mars Simulation Project v3.1.0-b2 - Build 4969 - 64-bit 11.0.4 - 4 CPU threads
java -jar mars-sim-[$VERSION].jar
                    (Note : start a new sim)
   or

 java -jar jarfile [args...]
                   (Note : start mars-sim with arguments)

  where args include :

    new             start a new sim (by default
                    (Note : if 'load' is absent, 'new' is automatically appended.),
    headless        run in console mode without an user interface (UI)
    0               256MB Min, 1024MB Max (by default)
    1               256MB Min, 512MB Max
    2               256MB Min, 768MB Max
    3               256MB Min, 1024MB Max
    4               256MB Min, 1536MB Max
    5               256MB Min, 2048MB Max
    load            open the File Chooser at the /.mars-sim/saved/
                    and wait for user to choose a saved sim
    load 123.sim    load the sim with filename '123.sim'
                    (Note : '123.sim' must be located at the same 
                            folder as the jarfile)
    noaudio         disable background music and sound effect
    512x            set time ratio to 512x (for headless edition only)
    1024x           set time ratio to 1024x (for headless edition only
```

**Comment by mokun** [comment]
> java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar -load noaudio

You are loading a saved sim. That's different from starting a new sim. 

Let's break down what's happening.
 
Q1 : Can you use `-noaudio` argument to create a brand new simulation ? 

Q2: If we save this sim and exit and loading this saved sim back, does it have any audio ?

**Comment by mokun** [comment]
I just looked up `MarsProject.java`. 

Unlike `MarsProjectFX.java`, `MarsProject.java` contains no reference of `noaudio`. 

Adding it now.

**Comment by shirishag75** [comment]
> > java -jar mars-sim-main-3.1.0-b2-jar-with-dependencies.jar -load noaudio
> 
> You are loading a saved sim. That's different from starting a new sim.
> 
> Let's break down what's happening.
> 
> Q1 : Can you use `-noaudio` argument to create a brand new simulation ?
> 
> Q2: If we save this sim and exit and loading this saved sim back, does it have any audio ?


In answer to Q1, I can use -noaudio argument and create a brand new simulation. 

But even then I get music in the simulation. 

In answer to Q2. 

Even if we save the simulation and load the sim back, it has audio irrespective of whether I use the no audio switch or not.

**Comment by mokun** [comment]
Thanks. I got it. Committing the change soon.

**Comment by mokun** [comment]
Let me know if the noaudio works and close this issue.

**Comment by mokun** [comment]
@Urwumpe and @shirishag75 ,

I'm planning to remove all the `.ogg` *background music* files (but not the sound effect files ) from mars-sim-ui's resources folder. 

This actually skims off 24 MB of space and they don't need to be bundled with mars-sim jar.

Players will now need to download the music files separately and manually place them into /.mars-sim/music folder if he wants playing sound tracks.

This opens up the option of playing any `.ogg` background music of one's choice.

**Comment by shirishag75** [comment]
+1 to that from my end.
