### ISSUE TITLE
wikipedia page for mars-sim

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#21]
Anyone interested in adding content to this page at [https://da.wikipedia.org/wiki/Mars_Simulation_Project](https://da.wikipedia.org/wiki/Mars_Simulation_Project) in Danish ?

**Comment by larsnaesbye** [comment]
I can do it, but should we also focus on the Croatian and Serbian existing pages, as well as making an English one too?

**Comment by larsnaesbye** [comment]
I added some more text and an infobox. For now I think this is OK.
