### ISSUE TITLE
Holocene Calendar

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#23]
I was considering if it would be logical for an international Mars colony inhabited by a lot of scientists and engineers from many nations and cultures to use the Holocene Calendar instead of AD/CE.

More information here: https://en.wikipedia.org/wiki/Holocene_calendar#Motivation

**Comment by mokun** [comment]
Holocene calendar only address the year discrepancy but doesn't do anything to the archaic system of having months and days that are planet-based. 

May be we can look for a timekeeping system designed to work well for at least the whole solar system, one that's mathematically easy to convert date/time from planet to planet and/or being in a space station. What do you think ?

May be what we need is a Star Trek-like Stardate system https://en.wikipedia.org/wiki/Stardate.

**Comment by larsnaesbye** [comment]
There seems to be no 'agreed upon' Interplanetary Timekeeping System so far, sadly. Maybe that could be a subproject, or something we can ask a specialist about?

**Comment by mokun** [comment]
Sure. We do want a full-blown calendar system for mars-sim. 

For now, the problem for me is how to accurately grab the local time based on a user's system locale and set it to 2043 Sep 30 00:00:00, as discussed in issue https://github.com/mars-sim/mars-sim/issues/38

It's almost trivial except that we are relying on Java API to do the right job for us. 

According to the designer of Mars24 at https://www.giss.nasa.gov/tools/mars24/help/algorithm.html, 

> A-1. Get a starting Earth time.
> 
> Mars24 is written in Java, so we use the System.currentTimeMillis() method to find out the number of milliseconds, millis, that have elapsed since 00:00:00 on Jan. 1, 1970 (i.e., the Unix epoch).
> 
> Unfortunately, most if not all Java implementations (or the operating systems on which they run) do not keep track of leap seconds, i.e., they keep time in UT rather than UTC. Consequently, when Mars24 calls System.currentTimeMillis(), it assumes that the value returned uses UT rather than UTC.
> 
> Only A-2 in the following steps explicitly uses millis. However, there are some displays in Mars24 which also use other readings based on the value of millis, so there is a possibility that if Mars24 is used on a computer and Java implementation which do keep track of leap seconds, display errors could result.
> 

there's error involved in counting the leap seconds.

**Comment by mokun** [comment]
Also, this [page](http://ops-alaska.com/time/TimeMarsM.htm) is a treasure trove, a repository of research/writing/analysis with regard to Mars timekeeping. 

I've heard some email exchange regarding the design of [MarsClock](https://sourceforge.net/p/mars-sim/mailman/mars-sim-developers/?viewmonth=200104) in mars-sim. 

Besides [Darian Calendar]( https://en.wikipedia.org/wiki/Darian_calendar) and their variants on iOS and Android, there's Shaun Moss's [Areosynchronous Calendar(https://www.teuse.net/games/mars/mars_calendar.php) that we've since partially adopted into mars-sim. 

They both fit the bill for us.

In fact, NASA uses nothing specific. They have their own Mars mission clock.

Also, Goddard's [Mars24 sunclock]( https://www.giss.nasa.gov/tools/mars24/help/algorithm.html) proposed what's called "Mars Solar Time"

**Comment by mokun** [comment]
Major issues for a Martian calendar is explained in this [paper](https://github.com/mars-sim/mars-sim/files/894892/Issues_and_options_for_a_Martian_calendar.pdf).

**Comment by larsnaesbye** [comment]
I still think it could be interesting to assume that in the future, Holocene Calendar is the standard Earth time.

**Comment by mokun** [comment]
Sure. It'd be fun for us to become a multiplanetary species and have a new date/time system. A stardate would make sense by then !

But first, there are pertinent issues in mars-sim. 

For instance, what is the date/time of the first human landing ? Note that I know Scott said he's forgot why we set 2043 Sep 30 as 15-Adir-01 on Mars. This means Mars has gone through a total of 15 orbits (Martian years). So I suppose it's easy to back calculate this day that everyone will celebrate...

Anyway, I wanna implement scenarios in mars-sim and would definitely want to make this first Mars landing date flexible.

Meanwhile, this morning I just look up Java 8's new time API. We still use the old [GregorianCalendar] (https://docs.oracle.com/javase/7/docs/api/java/util/GregorianCalendar.html) class in mars-sim in EarthClock. 

I've been experimenting on and off with with setting the locale and time zone in mars-sim...

So the first thing I'll do is to implement [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) in simulation.xml. 

Right now, what we have is `<earth-start-date-time value="2043-09-30 00:00:00 GMT00:00 " />`

Then I'll back calculate the first Mars landing day according to mars-sim :)

**Comment by mokun** [comment]
Just found out the following : 

```
Jun 18, 2018, 12:16:06 PM (Info) ClockUtils : 0015-Adir-01 corresponds to : Wednesday, September 30, 2043 at 12:00:00 AM Coordinated Universal Time
Jun 18, 2018, 12:16:06 PM (Info) ClockUtils : 0000-Adir-01 corresponds to Tuesday, July 14, 2015 at 9:53:18 AM Coordinated Universal Time
```

I guess landing on Mars in reality will still be at least 10 years away and NOT on 2015. So what day should we assume 0000-Adir-01 to be ?

**Comment by mokun** [comment]
And why is the beginning of each simulation be at 15-Adir-01 ? What's the significance of the orbit 15 ?

**Comment by larsnaesbye** [comment]
I suppose Scott had a reason for it, but he never told me...

**Comment by larsnaesbye** [comment]
Perhaps orbit 1 is meant to be when the mission started, and orbit 15 when we enter the simulation. We start 15 orbits in since Marsfall?

**Comment by mokun** [comment]
Marsfall ?

**Comment by larsnaesbye** [comment]
Marsfall is simply when the first colonist touch down on Mars for the first time. Like PlanetFall in Alpha Centauri.

**Comment by mokun** [comment]
Currently, the MarsClock and OrbitInfo are "tied" to the start date of 2043 Sep 30 at 00:00 UTC. 

So I just pulled out an orbital mechanic textbook this morning and looked up some equations. 

I have to fully refresh myself on how one defines `L_s`, the areocentric longitude (or the orbital position of Mars).

At `L_s = 0` corresponding to Mars' Northern Spring Equinox.

At the start of the sim (2043 Sep 30 at 00:00 UTC), L_s = 252.58.

So, in order for me to make this Marsfall date flexible (we want to create various "scenarios", each with a different start date), I'll need to find a way to calculate the instantaneous `L_s` on a particular date a user selects as the date of the first landing or whatever start date dictated by a scenario. 

I'm getting close to figuring it out.

**Comment by mokun** [comment]
@larsnaesbye, this morning I was thinking about what happens when we first lands on Mars. The mission control will definitely time it to land during the day time where every earthling on the TV or internet will get to see in their own eyes. 

And it dawns on me that in mars-sim, we may or may not have aligned the earth date/time with Mars date/time correctly. 

Question : does `2043 Sep 30 at 00:00 UTC` corresponds to `0015-Adir-01 000.000" exactly at the beginning of the day on both the prime meridian on Earth and the imaginary time at 0 W 0 N at Airy's crater on Mars ?

May be this is why `2043 Sep 30 at 00:00 UTC` was chosen because of the "time" and that's why that day is special ? 

What do you think ? We'll need to prove this.

**Comment by mokun** [comment]
I just added in more equations from this [site](https://www.giss.nasa.gov/tools/mars24/help/algorithm.html) for computing the so-called `Coordinated Mars Time`, i.e., Airy Mean Time. See equation `C-2`.

It's a bit disappointing to see that neither '2043-09-30 00:00:00' nor '2015-07-14 00:00:00' have the `Coordinated Mars Time` of 00:00:00.
 
> 2018-07-05T14:13:02.2 (Info) ClockUtils : 0015-Adir-01 corresponds to Wednesday, September 30, 2043 at 12:00:00 AM Coordinated Universal Time
> 2018-07-05T14:13:02.2 (Info) ClockUtils : 0000-Adir-01 corresponds to Tuesday, July 14, 2015 at 9:53:18 AM Coordinated Universal Time
> 2018-07-05T14:13:02.2 (Info) MasterClock : millis is 2.327184E12
> 2018-07-05T14:13:02.2 (Info) MasterClock : jdut is 2467522.5
> 2018-07-05T14:13:02.2 (Info) MasterClock : T is 0.4374401095140315
> 2018-07-05T14:13:02.2 (Info) MasterClock : TT2UTC is 73.97847966488716
> 2018-07-05T14:13:02.2 (Info) MasterClock : jdtt is 2467522.5008562324
> 2018-07-05T14:13:02.2 (Info) MasterClock : j2k is 15977.500856232364
> 2018-07-05T14:13:02.2 (Info) MasterClock : M is 111.92876225850887
> 2018-07-05T14:13:02.2 (Info) MasterClock : alpha is 3.2126185387187434
> 2018-07-05T14:13:02.2 (Info) MasterClock : PBS is -0.007133978257654905
> 2018-07-05T14:13:02.2 (Info) MasterClock : EOC is 9.467471290255427
> 2018-07-05T14:13:02.2 (Info) MasterClock : v is 121.39623354876494
> 2018-07-05T14:13:02.2 (Info) MasterClock : L_s is 12.72010790886634
> 2018-07-05T14:13:02.2 (Info) MasterClock : EOTDegree is -8.331632969694333
> 2018-07-05T14:13:02.2 (Info) MasterClock : EOTHour is -0.5554421979796221
> 2018-07-05T14:13:02.2 (Info) MasterClock : EOT_Str is -00:33:019.592
> 2018-07-05T14:13:02.2 (Info) MasterClock : MTC1 is 15.144292275886983
> 2018-07-05T14:13:02.2 (Info) MasterClock : MTC_Adj is 15.144292275886983
> 2018-07-05T14:13:02.2 (Info) MasterClock : MTC_Str is 15:08:39.452
> 2018-07-05T14:13:02.2 (Info) MasterClock : LMST is 2.830825609220316
> 2018-07-05T14:13:02.2 (Info) MasterClock : LMST_Str is 02:49:50.972
> 2018-07-05T14:13:02.2 (Info) MasterClock : LTST is 2.2753834112406937
> 2018-07-05T14:13:02.2 (Info) MasterClock : LTST_Str is 02:16:31.38
> 2018-07-05T14:13:02.2 (Info) MasterClock : sl is 38.83275116861046
> 2018-07-05T14:13:02.2 (Info) MasterClock : r is 1.587624202793963

**Comment by mokun** [comment]
I just created this new wiki page [Mars Calendar](https://github.com/mars-sim/mars-sim/wiki/Mars-Calendar) with help from a html document in mars-sim.

**Comment by mokun** [comment]
@larsnaesbye, I agree to pick a date on 2028. 

Incidentally, one vernal equinox table I googled shows that on 2028-08-17, Ls will be ~0.

I run the date through a few times to pinpoint the exact hour when MTC becomes close to 00:00:00.000. 

Turns out it's at 15:23:13.740 on 2028-08-17, when MTC is at 00:00:00.016 and Ls = 0.1991. Both of them are nearly zero.

So I'm adopting "2028-08-17 15:23:13.740" as the new Earth date/timestamp in simulation.xml when starting a new simulation. The simulation will start at "0000-Adir-01:000.000" 

> 2018-07-06T15:31:01.5 (Info) ClockUtils : 0015-Adir-01 corresponds to Thursday, August 17, 2028 at 3:23:13 PM Coordinated Universal Time
> 2018-07-06T15:31:01.5 (Info) MasterClock : millis is 1.85013859374E12
> 2018-07-06T15:31:01.5 (Info) MasterClock : jdut is 2462001.14113125
> 2018-07-06T15:31:01.5 (Info) MasterClock : T is 0.28627354226557666
> 2018-07-06T15:31:01.5 (Info) MasterClock : TT2UTC is 75.19380025668994
> 2018-07-06T15:31:01.5 (Info) MasterClock : jdtt is 2462001.142001549
> 2018-07-06T15:31:01.5 (Info) MasterClock : j2k is 10456.142001548782
> 2018-07-06T15:31:01.5 (Info) MasterClock : M is 98.6222646352544
> 2018-07-06T15:31:01.5 (Info) MasterClock : alpha is 349.8080284540529
> 2018-07-06T15:31:01.5 (Info) MasterClock : PBS is 0.016357923512480065
> 2018-07-06T15:31:01.5 (Info) MasterClock : EOC is 10.363148880258173
> 2018-07-06T15:31:01.5 (Info) MasterClock : v is 108.98541351551285
> 2018-07-06T15:31:01.5 (Info) MasterClock : L_s is 0.19908984995709034
> 2018-07-06T15:31:01.5 (Info) MasterClock : EOTDegree is -10.372124012223834
> 2018-07-06T15:31:01.5 (Info) MasterClock : EOTHour is -0.6914749341482556
> 2018-07-06T15:31:01.5 (Info) MasterClock : EOT_Str is -00:41:029.31
> 2018-07-06T15:31:01.5 (Info) MasterClock : MTC0 is 6.691506132483482E-5
> 2018-07-06T15:31:01.5 (Info) MasterClock : MTC1 is 4.51505184173584E-6
> 2018-07-06T15:31:01.5 (Info) MasterClock : MTC_Str is 00:00:00.016

**Comment by mokun** [comment]
Closing this discussion for the time being.
