### ISSUE TITLE
Design idea: Notes and Plans

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#235]
After returning to an old savegame in another game after a longer pause, I realized that you can never write enough notes, comments and descriptions in a strategy game. 

I think this could also help for MSP, so my still rough suggestion:

Every unit gets a Tab "Notes" with a multiline text input that permits writing notes about the future plans with that unit. 

On a global scale, there could be a global TODO list, that allows adding user-defined and scenario tasks (similar to achievements) to it. In commander mode, this could be supplemented by a in-character TODO list (see #141 ) which can be presented as a second tab in the same child window. 

Any such global feature would not interact with the simulation entities - no other settler would read the global TODO list, it is only an aid for the (local) player.

**Comment by mokun** [comment]
Sure. We could certainly add a Notes tab to the unit window of each settler, settlement, vehicle, and equipment. 

I'm wondering what it takes to create a *task helper* that has the ability to parse through the notes to sort of pick up what the player needs. May be it can suggest and ask players for confirmation from a list of to-do items.

**Comment by Urwumpe** [comment]
Hmm... parsing lines starting with TODO when the notes are saved should not be too hard. 

Maybe it is possible to create a Metatask that could create taske for the TODO List based on a selected goal, like acquiring the required resources for crafting something.

**Comment by mokun** [comment]
> when the notes are saved

What should be the best strategy currently for saving the notes ?

So far we avoid serializing any UI components (anything in mars-sim-ui). 

In v3.07, The UIConfig class was used for saving the x, y location of the tool windows and unit windows into a xml file. But we have since pretty much comment out any lines that use it.

If we use JSON to make the notes persist through different simulation session, how should it be done ?

**Comment by Urwumpe** [comment]
Why not make this a property of any Unit in MSP? Shouldn't this already be enough?

Otherwise...what about a "NotebookCapability" interface to be implemented in anything that should support such a tab?

**Comment by mokun** [comment]
To get us started, I'll create `NotesTabPanel` to host a simple text area for players to type up some notes.

We'll discuss more on parsing through these notes in later and implementing a drag-and-drop task board like you have suggested in https://github.com/mars-sim/mars-sim/issues/141

**Comment by mokun** [comment]
See below for the draft `NotesTabPanel` : 
![NotesTabPanel](https://user-images.githubusercontent.com/1168584/68705014-2b42cd00-0542-11ea-8750-6df6c5e21329.jpg)

**Comment by Urwumpe** [comment]
Looks good that way. Precisely what I need in first place.

**Comment by mokun** [comment]
We could add some features to capture or transcribe history events and notes automatically for us in future.  But for now, I'll close it unless you have some tangible features in mind you want to see them implemented.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

Is there any other concrete things you guys can think of improving what the Notes Tab can contribute to the overall gameplay ? 

Or should we close this thread ?

**Comment by bevans2000** [comment]
I think the Notes tab does what it needs to. Let's close it

**Comment by Urwumpe** [comment]
Can be closed, it does its purpose.
