### ISSUE TITLE
Can't get Mars Simulator to even start

### ISSUE THREAD

**Issue by Trolldefender99** [mars-sim/mars-sim#237]
OS: Windows 10
Java: Tried Oracle JDK 11 and OpenJDK11

java home set to: C:\Program Files\Java\jdk-11.0.2
Path set to: %JAVA_HOME%\bin
Shows correctly in command prompt window with OpenJDK 11 showing properly when doing "java-version"

here is what it shows
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

As some history. I didn't know this github existed, so I downloaded the version off the site. I tried every single java version that is available to download, and not a single one worked. 2-3 months ago I stayed up 24 hours then spent about a dozen more hours trying to fix it. I downloaded the batch file and it would just start up and close right away doing nothing. It kept saying it can't open mars-sim-main-3.1.0-b1.jar and when I try running the batch file it just opens and closes right away, but if I drag it into command prompt window it gives that error of opening the jar file that I listed. And if I try to open mars sim main jar, it says JNI error no matter what java version I have. I then tried the jar version and it also said JNI error.

So jump to tonight. I got OpenJDK11 as said, probably what I'll stick with. And found 5162_swing_java11.jar existed, apparently more up to date than one shown on the main website. So I put it into its own folder and ran in command prompt "java -jar 5162_swing_java11.jar"

And finally! After over 50 hours of trying to get it to work, a new error has appeared!

Error: unable to access jar file

Finally something new. I'm not sure why it can't access the jar file, but at least it doesn't say it can't open some random file or JNI error.

**Comment by Trolldefender99** [comment]
Also, apparently there is something about unpacking the swing.jar file. I tried that just now not sure if supposed to or not, didn't realize one could actually unzip jar files. And...it gives same error as before. Except this time its

Error: Unable to access jarfile jars/mars-sim-headless-3.1.0-b2.jar
Exit Code = 1

So instead of mars-sim-main-3.1.0-b1.jar it just says that about headless file instead.

**Comment by mokun** [comment]
Hi @Trolldefender99 , 

Thanks for posting it and sorry about the frustration in getting mars-sim started. 

Just so you know, about 2 years ago (Jul 2017), the Java ecosystem was literally thrown into a big mess as the world was migrating from Java 8 to Java 9. 

Then again last years, compatibility issues arise in moving to Java 11.

So if you have Java 11 VM installed on your machine, it won't be able to run any previous versions of mars-sim that were compiled under Java 8 anymore.

So to us, it wasn't until 4 months ago that we worked out all the issues and migrated from Java 9 to Java 11 with [build 4945](https://github.com/mars-sim/mars-sim/releases/tag/4945).

Since then, we cleaned up a few some startup and loading/saving issues.

**Comment by mokun** [comment]
First of all, I'd like to make sure you don't put all the jar files into one directory.

There is an instruction on this at the bottom of the recent prerelease. See [this](https://github.com/mars-sim/mars-sim/releases)
> Build Management
> Make sure you DO NOT place multiple builds of binary in the same folder or directory since this could potentially cause java to look into the classpath and pick the old build to start.
> 
> Always DELETE older builds or archive each build on separate folder.
> 
> You may tell which build version you are running as shown on the title bar of the application window.

**Comment by mokun** [comment]
Do you run any other (old and new) Java apps ? 

I'd like to show you how you can track and actually keep multiple versions of Java on your machine in Windows 10.

1. Move your mouse to the magnifier icon (the 2nd icon from the left) on win 10 task bar. 
2. Type `Configure Java` 
3. Hover your mouse over that "Configure Java" app and click to start the `Java Control Panel`

![image](https://user-images.githubusercontent.com/1168584/69747855-ffa41300-10fb-11ea-90e9-d47fe1b35a18.png)

4. Click on `Java` tab on top.
5. Click on `View` button to open up another panel window.
6. Click on the checkbox on the `Enable` column to enable or disable any official Oracle versions of Java you might have installed in the past.

e.g. in my case, I have Java 1.8.0_211 and 1.10.0_1_1 and my Java 1.8 was enabled. 

If I no longer run any Java app that was compiled for 1.8, I may as well just uninstall Java 1.8 from my machine.

> Note: this Java Control Panel thing only tracks the official Oracle versions. If you install any dozens of openJDK out there, it won't know them :D

**Comment by Trolldefender99** [comment]
I have got it working doing two things. I changed the batch file from

@echo off
call java -jar /jars/mars-sim-main-3.1.0-b1.jar new
echo Exit Code = %ERRORLEVEL%
if "%ERRORLEVEL%" == "1" exit /B 1

To

@echo off
call java -jar ./jars/mars-sim-main-3.1.0-b1.jar new
echo Exit Code = %ERRORLEVEL%
if "%ERRORLEVEL%" == "1" exit /B 1

On the dwarf fortress (other games section) someone said his game wouldn't work until adding the period after call java -jar and before /jars/mars-sim. Mine is using the newest version though found on this github, version 5162 I believe it is.

I also had to install this version of java

https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html

It wouldn't work for me on any other java version, and for anyone else reading, make sure to get the .exe version as that is the only one that works for this Sim.

**Comment by mokun** [comment]
> call java -jar ./jars/mars-sim-main-3.1.0-b1.jar new

Are you running v3.1.0-b1 ?

I guess you manually unzip the 5162 jar file and have found the `mars-sim.bat` and try to run it.

SInce we no longer post the Batch Edition of mars-sim, we didn't update this batch file. 

But if we did update it, it will read as follows (with your suggestion added) : 

```
@echo off
call java -jar ./jars/mars-sim-headless-[$CURRENT_VERSION].jar new
echo Exit Code = %ERRORLEVEL%
if "%ERRORLEVEL%" == "1" exit /B 1
```

> Note: Substitute [$CURRENT_VERSION] with whatever the next official release version will be in the mars-sim-headless-[$CURRENT_VERSION].jar filename.

The thing is that you don't actually have to unzip the jar file AT ALL.

To me, I always run `java -jar 5162.jar` (say 5162.jar is the jar filename ) in a command prompt to start mars-sim so that I can have the stack trace to look at all the log statements generated.

**Comment by Trolldefender99** [comment]
I was at first using 3.1.0-b1, I deleted it and moved to 5162 since it looks like its the most recent version. 

I've got it working though. With adding the period (I placed it back into the jar file), and getting the correct java it works fine now. Its really finicky especially though with what java it works on. I dunno what java version others are running, but for me it wouldn't run on anything else but JDK 11.05 from oracle.

**Comment by mokun** [comment]
> version as that is the only one that works for this Sim. Also make sure java JDK11 is 11.05...not 11.04 or any other version. This sim is really picky with what version it wants.

True there's a big possibility that build 5162 isn't friendly with openjdk.

I was out of town when I compiled 5162 in a laptop with the initial Official version of Oracle Java 11 loaded. (it's just 11.0.0, not the latest Oracle 11.0.5)

In light of that, I'll compile a new build under the latest openJDK and post it for your review in an hour or so. Stay tune and thanks much for working through all these troubles :D

**Comment by mokun** [comment]
To run mars-sim in a command prompt/terminal, say, if `5184.jar` is the name of the compiled jar in `D:\660s\msp binaries\5184`, type `java -jar 5184.jar` and hit enter to run mars-sim as follows.

```
D:\660s\msp binaries\5184>java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

D:\660s\msp binaries\5184>java -jar 5184.jar
Command: "C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\\bin\java" -Djava.util.logging.config.file=logging.properties -cp .;*;jars\* org.mars_sim.main.MarsProject -Xms256m -Xmx1536m -new
2019-11-27T13:21:36.5 (Config) MarsProject$SimulationTask : Starting Mars Simulation Project v3.1.0 - Build 5184 - 64-bit 11.0.4 - 8 CPU threads
2019-11-27T13:21:36.5 (Config) MarsProject : handleNewSimulation() is on pool-1-thread-1
2019-11-27T13:21:36.5 (Config) MarsProject : Please proceed to selecting the type of Game Mode in the popped-up console.
2019-11-27T13:21:36.5 (Config) SimulationConfig : /xml folder already existed.
2019-11-27T13:21:36.5 (Config) SimulationConfig : Your version.txt already has the same BUILD 5184 as the core engine.
2019-11-27T13:21:37.0 (Config) SimulationConfig : Done loading all xml files.
2019-11-27T13:21:39.5 (Config) Simulation : Initiating the simulation core engine...
2019-11-27T13:21:39.8 (Config) MasterClock :    -------------------------------------------
2019-11-27T13:21:39.8 (Config) MasterClock :             Base Time Ratio (TR) : 256x
2019-11-27T13:21:39.8 (Config) MasterClock :      Base Ticks Per Second (TPS) : 9.43 Hz
2019-11-27T13:21:39.8 (Config) MasterClock :  Base Time between Updates (TBU) : 106.07 ms
2019-11-27T13:21:39.8 (Config) MasterClock :    -------------------------------------------

```

**Comment by mokun** [comment]
I just published a new build [5184](https://github.com/mars-sim/mars-sim/releases/tag/5184). 

Let me know any comments and feedback. 

Thanks!

**Comment by Urwumpe** [comment]
Important for making the jar releases work, is to ensure the current working directory is the directory in which the jar file is located. Otherwise the instance is using the wrong class path to search for the contents of the jar. This could get fixed, I am sure, to allow launching MSP from a different working directory. But placing it into the manual should be good enough.

Tested it with both Java 11 and Java 13 on Windows 10.

**Comment by mokun** [comment]
I'll close this thread since those issues should have been cleared up.
