### ISSUE TITLE
No dessert - no mission

### ISSUE THREAD

**Issue by Brytenwalda** [mars-sim/mars-sim#239]
**Describe the bug/issue**
 I cannot start a new mission as my settlement has no desserts. Note that I deleted the original three settlements and replaced them with a phase one base.

**Affected Area**
Mission menu.

**Expected behaviors**
I would expect the mission to be able to start without having any desserts.

**Actual/Observed Behaviors**
 1. In the mission wizard, it will show in red that the mission will not start because my desserts are 0.
2. It allows me to move further but it will be impossible to drag a flag to a different waypoint.

**Additional context**
 I don’t even know how to start - how can I make them make desserts? I’m not even sure if they have the necessary ingredients.

**Comment by mokun** [comment]
Hi @Brytenwalda, which version of mars-sim are you running ?

**Comment by mokun** [comment]
btw, the latest one is build 5184. See https://github.com/mars-sim/mars-sim/releases

> It allows me to move further but it will be impossible to drag a flag to a different waypoint.
I'll take a look.

> how can I make them make desserts? I’m not even sure if they have the necessary ingredients.

It would need a chef to perform a 'ProduceFood` task to make some of them.

If in a kitchen, someone would need to do `PrepareDessert` to serve the dessert.

**Comment by mokun** [comment]
As of build 5184, the following 8 types of food are considered "desserts" 

| Dessert |
|--|
| sesame milk |
| soymilk|
| sugarcane juice | 
| cranberry juice | 
| strawberry | 
| granola bar | 
| blueberry muffin |

**Comment by Brytenwalda** [comment]
I switched to the latest version and there are a few bugs already:
1) Mission menu doesn’t work. Trying to create a new mission, the mission list is all empty positions. There’s nothing I can select.
2) Opening a crew member’s career menu immediately prompts a “do you want to change to job to areologist” menu that will immediately reopen each time it’s closed, no matter what choice I make. Also, that character is already an areologist so it’s not really a change.
3) The game won’t work let me change the alpha crew’s sponsor to anyone but Mars Society and I chose NASA for my commander, meaning game won’t spawn them.

**Comment by mokun** [comment]
Thanks for posting these bugs :D 

> Trying to create a new mission, the mission list is all empty positions. There’s nothing I can select. Modify and abort mission don’t work either.

Fixing this now.

**Comment by mokun** [comment]
> Opening a crew member’s career menu immediately prompts a “do you want to change to job to areologist” menu that will immediately reopen each time it’s closed, no matter what choice I make. Also, that character is already an areologist so it’s not really a change.

I'm onto fixing this.

**Comment by mokun** [comment]
> Earth time is all over the place - changing its speed all the time and sometimes even moving backwards. 

moving backward ?

> It doesn’t seem like it’s tied to the Martian time in any way.

We made an arbitrary decision to set  the Earth timestamp to `2043-09-30T00:00:00.000Z` at the start of the simulation. It was choice among a few other candidate date. The only criteria is that the *Solar Longitude* (L_s) must be fairly close to 0 degree.

So the earth timestamp of `2043-09-30T00:00:00.000Z` is supposed to match up with the Martian timestamp at `00-Adir-01:000.000`

Now, the speed of the simulation depends on the **time ratio**. 

Depending on the # of cores/threads on your machine, it automatically computes the most optimal *time ratio* at the start of the sim.

So in my quad core machine, it starts at the *time ratio* of `256x`.

It means the speed of the simulation time is effectively 256 times the real time.

However, you can always change that ratio in the `Time Tool` by dragging the slide at the bottom. In future, we'll move the time ratio change to the main window.

> Note: if the cpu utilization is higher on your machine, the *time ratio* may reduce itself (say, from x512 to x256) so that the simulation can still be runnable.

**Comment by mokun** [comment]
> The game won’t work let me change the alpha crew’s sponsor to anyone but Mars Society and I chose NASA for my commander, meaning game won’t spawn them.

Fixing the mapping between the country and a list of possible sponsors now in `CrewEditor`.

**Comment by mokun** [comment]
@Brytenwalda , I'm closing this now. If you encounter any bugs, feel free to report. Thanks !

**Comment by mokun** [comment]
Just fixed a recent bug on eating dessert at https://github.com/mars-sim/mars-sim/commit/496ee8292f36810d720441a8add074554c983f01.
