### ISSUE TITLE
Everyday and everywhere "Kidney bean fried rice" is cooked

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#240]
Looks like some cosmic gods are torturing our settlers by making all cooking tasks produce "Kidney bean fried rice". Not sure if even the ingredients are available everywhere.

There should be more variation, perfect would be having a diet plan for the settlers defining which meals should be cooked every meal for a health nutrition. 

Tested in R5184, Java 11, Windows 10

**Comment by mokun** [comment]
Yea we can't have all. If your minions are that of high adventure types who aspire to reach Mt Everest and Mt Olympics next, they don't mind curbing their diet :D
 
According to meals.xml below,

https://github.com/mars-sim/mars-sim/blob/c19700ce0aa63aaf4d3bff0ff6822c2db85e8095/mars-sim-core/src/main/resources/xml/meals.xml#L41-L47

A settlement would need some amounts of `White Rice`, `Kidney Bean`, `Green Bell Pepper`, `Swiss Chard` to create the `Kidney Bean Fried Rice` meal.

The good news is that while they do sacrifice their choice of cuisine back on Earth, each settler gets to  elect one favorite *Main Dish* and one favorite *Side Dish* at the start of the sim.

I'll need to check if their home settlement keeps track of their favorites and would intelligently chooses to which food crops to plant :D

**Comment by Urwumpe** [comment]
Yeah - I wonder where they did get the huge amounts of Swiss chard from.  

Not sure if this is really a strange production choice or a wrong text in the log file and they actually produced something more sensible.

**Comment by mokun** [comment]
`Swiss Chard` is one of those types of food crop that have sufficiently *short* vegetation period so that they don't have to waste a long time growing them.

https://github.com/mars-sim/mars-sim/blob/c19700ce0aa63aaf4d3bff0ff6822c2db85e8095/mars-sim-core/src/main/resources/xml/crops.xml#L525-L540

Is it too big of the assumption regarding the technology of automated greenhouse farming on Mars ? 

Let's fill in the detail as to how GardenBots have been taking care of the crops, shall we ? 

These would need to be fully grown and ready for harvest before the arrival of the settlers on Mars.

**Comment by Urwumpe** [comment]
> Is it too big of the assumption regarding the technology of automated greenhouse farming on Mars ?

No, it already works on the German antarctic research station Neumeyer III with minimal human interaction.

> 
> Let's fill in the detail as to how GardenBots have been taking care of the crops, shall we ?

That could escalate, I recently did some research just on how to grow tomatoes and how you optimize the harvest towards specific targets, like maximum yield or better taste. 

> 
> Timing is everything for crops. They would need to be fully grown and ready for harvest _right before_ the arrival of the settlers on Mars :]

:D Would be great, but hard to achieve.  It would be better anyway if harvest starts a short time after the arrival, because the crew also needs some time for moving in and unloading the lander.

**Comment by mokun** [comment]
Pizza party in ISS :D

![image](https://user-images.githubusercontent.com/1168584/69911643-32d3f400-13d3-11ea-8609-dda4c74dde35.png)

**Comment by mokun** [comment]
The pic below shows that in Elon City's cafeteria, a total of 6 `Kidney Bean Fried Rice` meals were cooked on that day :D

![image](https://user-images.githubusercontent.com/1168584/70596209-218ca380-1b9a-11ea-957c-ef9d9d9adc73.png)

**Comment by bevans2000** [comment]
I found and fixed a bug for this in December. There was a coding mistake so the next meal to cook was always the first one in the list not one at random.
