### ISSUE TITLE
new default commander made but am not able to find him in any of the teams, commander profile

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#243]
I am running mars-sim headless r5222 . 

On the swing console front-end, it is difficult to know about the status of the alpha crew is. I saw the settlements and there wasn't an alpha settlement so guess there isn't. 

I made a new default commander, similar to how I shared in #218 but after checking him in all settlements didn't see him anywhere. 

Also when connecting to marsnet you do not get the hint anymore how to autocomplete words, has that feature been nerfed or something which needs to be worked upon somewhere down the line ?

So the commander is an Indian, the sponsor is India so I would have expected him to be in New Pompeii (where seems the Indian base is) but wasn't able to find him. I saw that you have added a bunch of items TBD for 3.1.0 , would this be part of 3.1.0 or something further down the line ? I am ok with either way but would like to know. And I am looking for this to be fixed in the headless mode rather than in GUI mode.

**Comment by mokun** [comment]
> So the commander is an Indian, the sponsor is India so I would have expected him to be in New Pompeii (where seems the Indian base is) but wasn't able to find him.

I'll find out why he doesn't show up in New Pompeii.

**Comment by mokun** [comment]
Meanwhile, I'll need to change the sequence of questions in setting up the commander profile in beryx console.

In the Crew Editor, the moment player changes the "country" of a settler in the *country combo box*, a list of available "sponsors" will be generated in the *sponsor combo box*. This is the right way.

However, in beryx console, it's the other way around. The player was first asked about who will sponsor the commander and then his/her country. I'll reverse that to match up with how Crew Editor currently behaves.

**Comment by mokun** [comment]
> On the swing console front-end, it is difficult to know about the status of the alpha crew is. I saw the settlements and there wasn't an alpha settlement so guess there isn't.

The alpha crew roster is currently being defined in [crew.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/xml/crew.xml)

You can customize and create your own crew.xml. 

Just be sure that after the changes, you make a backup copy of your own crew.xml.

It's accessible from the `$YOUR_HOME_FOLDER/.mars-sim/xml`

Note that since there are changes in each build, whenever you obtain the latest build in Git, the existing crew.xml (an the same for other other xml files) will be backup in a backup folder and a new version of crew.xml will be copied to `$YOUR_HOME_FOLDER/.mars-sim/xml`.

So, make sure you copy back your customized crew.xml RIGHT AFTER you update to the latest build in Git.

**Comment by mokun** [comment]
> I made a new default commander, similar to how I shared in #218 but after checking him in all settlements didn't see him anywhere.

So in my case, let say, I pick Canada as my country and CNSA as my sponsor. 

After setting up the commander profile, if you open the *site editor*, it will show the following : 
![image](https://user-images.githubusercontent.com/1168584/70881885-e667e700-1f82-11ea-9c5a-06b8dd92b985.png)

After all the initial conditions have been setup, in *New Plymouth*, it will have the following : 
![image](https://user-images.githubusercontent.com/1168584/70882097-7efe6700-1f83-11ea-98fe-d9b2e895e4ad.png)

Everything it seems to work the way it's supposed to at this point.

Can you double check ?

**Comment by shirishag75** [comment]
In my case it was giving India for both instead of giving India (for country) and ISRO (as sponsor) . I am unable to see the sponsor listing in beryx console, maybe that is something that needs to be integrated. What is the keyboard combo for seeing the sponsor listing ?

**Comment by shirishag75** [comment]
Btw is there a way to search for people within MarsNet ?  If I just give name shirish agarwal, I get the message he is occupied atm but nothing about which base he is at or anything about him. How do I get that information in the beryx console ?

**Comment by mokun** [comment]
> What is the keyboard combo for seeing the sponsor listing ?

Press `Ctrl-S` to show a list of sponsors.

**Comment by mokun** [comment]
> I get the message he is occupied atm but nothing about which base he is at or anything about him.

That means he's asleep or is handling an emergency repair :D

**Comment by mokun** [comment]
Press Ctrl-S to show a list of sponsors.


```
    ----------------------- Sponsors Listing -----------------------

 (1). China National Space Administration (CNSA)
 (2). Canadian Space Agency (CSA)
 (3). Indian Space Research Organisation (ISRO)
 (4). Japan Aerospace Exploration Agency (JAXA)
 (5). National Aeronautics and Space Administration (NASA)
 (6). Roscosmos (RKA)
 (7). European Space Agency (ESA)
 (8). Mars Society (MS)
 (9). Space Exploration Technologies (SpaceX)

```

Press Ctrl-O to show a list of countries.

```

    ---------------------- Country Listing ----------------------

 (1). China              (2). Canada             (3). India
 (4). Japan              (5). USA                (6). Russia
 (7). Austria            (8). Belgium            (9). Czech Republic
(10). Denmark           (11). Estonia           (12). Finland
(13). France            (14). Germany           (15). Greece
(16). Hungary           (17). Ireland           (18). Italy
(19). Luxembourg        (20). The Netherlands   (21). Norway
(22). Poland            (23). Portugal          (24). Romania
(25). Spain             (26). Sweden            (27). Switzerland
(28). UK
```

**Comment by mokun** [comment]
>  I am unable to see the sponsor listing in beryx console,

Can you try the latest build 5224 ? See if it's fixed for you.

**Comment by shirishag75** [comment]
yup, that fixed it for me, build 5224.

**Comment by shirishag75** [comment]
Ah, I see what the issue is happening. The commander is there for the initial run. If I run the game, stop the game, and then run the same game again, the commander disappears. He is no longer part of New Pompeii. Somehow the commander is 'lost' :(

**Comment by shirishag75** [comment]
Can somebody remind me when ~/.mars-sim/saved/default.sim and previous.sim are made. Are they made each time you save or is default.sim made at the time you end the simulation and when you start the simulation again, starting from the previous instance of the game, it just goes on. I do have a default.sim and previous.sim with 15 minutes of difference but dunno how to figure out if the previous.sim was of the old build or the new build 5224 . There is also the issue of what I was talking above as well. As the savegame is a blackhole cannot investigate :(

**Comment by mokun** [comment]
> The commander is there for the initial run. If I run the game, stop the game, and then run the same game again, the commander disappears. He is no longer part of New Pompeii. Somehow the commander is 'lost' :(

I can't duplicate it on my machine.

I save the simulation and exit and load it back a few times, the commander is still there.

I always have 8 people in that settlement.

**Comment by mokun** [comment]
The way the Command Mode` works is that the assigned commander will replace an existing member.

Q1: if the commander is gone in a 8-person settlement, did you see that the population dropped down to 7 people  ?

Q2: if there are still 8 people around, who is the one replacing the commander? 

Please provide some screen print showing that he's missing and who replace him, etc. Thanks.

Q:

**Comment by shirishag75** [comment]
This is the list of the new pompeii residents - 

![new-pompeii-residents](https://user-images.githubusercontent.com/727626/70954726-44212f80-2066-11ea-8f42-99553ab619a3.png)

Seems Neil Raje is the commander of New Pompeii. 

I also find it strange that commander.profile doesn't seem to be a format which can be viewed by featherpad which is a QT5 plain-text editor but doing cat on the file gets it. I am attaching the commander.profile. Be aware I touched it just before sharing although you get the time of creation within the file itself. I also changed it commander.profile.txt as github doesn't understand commander.profile. 

Maybe we can commander.json or something like that if that makes sense ?
[commander.profile.txt](https://github.com/mars-sim/mars-sim/files/3970840/commander.profile.txt)

**Comment by shirishag75** [comment]
It's intersting when you ask for people or even job roster it doesn't tell you who the commander, sub-commander etc. are . That probably is also something that might be needed to looked at :(

**Comment by mokun** [comment]
> I also find it strange that commander.profile doesn't seem to be a format which can be viewed by featherpad which is a QT5 plain-text editor

commander.profile is just a text file and can be viewed by any editor. The contents are as follows : 

```
#Commander's Profile
#Sun Dec 15 23:20:04 PST 2019
commander.gender=M
commander.age=30
commander.lastname=Kung
commander.job=Architect
commander.country=India
commander.sponsor=Indian Space Research Organisation (ISRO)
commander.firstname=Manny
```

It's what's called "Property File" often found to be used in Java.

see https://www.codingeek.com/java/read-and-write-properties-file-in-java-examples/

It stores a set of key-value pairs.

So `commander.age` is the key and `30` is the value of this key-value pair.

It's very simplistic and is not as versatile as a xml or JSON.

In future we will switch to JSON.

**Comment by mokun** [comment]
> even job roster it doesn't tell you who the commander, sub-commander etc. are . 

That's because in mars-sim, the `Job` of a person has nothing to do with `Role`

We have wikis written up on both topics.

The person who took up the [role](https://github.com/mars-sim/mars-sim/wiki/Role) of being a  commander still have his own job. He can have anyone of the 16 jobs, based on the result of the [Job Prospect](https://github.com/mars-sim/mars-sim/wiki/Jobs) score calculation.

**Comment by mokun** [comment]
> I also changed it commander.profile.txt as github doesn't understand commander.profile.

The thing is that `commander.profile` is just a user-generated file. 

It was created in your own home folder. 

It's never need to be uploaded to mars-sim repo in Github.

**Comment by mokun** [comment]
Since you don't like the name or extension of this file, I just change it to `commander.txt` to avoid any confusion.

**Comment by shirishag75** [comment]
> Since you don't like the name or extension of this file, I just change it to `commander.txt` to avoid any confusion.

It wasn't me who didn't like it , it was github which didn't like it. But then github doesn't even like .json files , see the barely amount of files you can upload here. Github really needs to improve it game :(

**Comment by mokun** [comment]
Yes we use .gitIgnore to remove a lot of platform-specific or IDE-specific config files from being sent upstream. 

e.g. we don't want any intelliJ or Eclipse config files in our repo.

Besides, commander.txt is not even one of those *required* config file like building.xml or settlements.xml for initializing the core engine.

Anyway, let's close this thread now unless you found any anomaly. Appreciate !

**Comment by shirishag75** [comment]
I have to reopen it again because somehow the commander-profile doesn't seem to be stuck. I dunno what you are using but it doesn't work at my end - 

![mars-sim-menu-load-save-game](https://user-images.githubusercontent.com/727626/71045682-c9bbe280-212d-11ea-925c-71a088c4afb7.png)

I am going to send you both commander-in-profile.sim and the new default.sim that it generated so you can view the results and tell me what is happening.
