### ISSUE TITLE
where is weblaf and update berylx console ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#244]
I was/am unable to find weblaf and where it is located in pom.xml in mars-main . Can you share where it is ? I even checked mars-sim-headless and even in that it isn't mentioned. 

Meanwhile the beryx console has been updated to 3.4.1 maybe you bump up the dependencies whenever you feel it's worth it. FWIW, the latest release of weblaf also seems to be a badass, look at the release notes.

https://github.com/mgarin/weblaf/releases/tag/v1.2.11 

for openjdk 12 and later support maybe we should look at - 

https://github.com/mgarin/weblaf/issues/525

Till later.

**Comment by mokun** [comment]
> I was/am unable to find weblaf and where it is located in pom.xml in mars-main . Can you share where it is ? 

The *Web Look and Feel (weblaf)* API is included in mars-sim-ui's pom.xml. 

It adds flavors to the plain-old Swing UI that is bundled with any standard Java version or any JDK.

**Comment by mokun** [comment]
> https://github.com/mgarin/weblaf/releases/tag/v1.2.11
for openjdk 12 and later support maybe we should look at -
mgarin/weblaf#525

Yes we've been running weblaf v1.2.11 and other than the following warnings, we encounter no additional issues. 

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:weblaf-core-x.x.x.jar) to method {method.name}
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

The README.md mentioned about these warnings and a temporary solution to reduce it to just one warning. 

If I recall it has to do with the xstream library. A lot of people are waiting for this library to be updated to support beyond Java 8.

**Comment by mokun** [comment]
Closing.
