### ISSUE TITLE
why do some missions get approved, some don't need approval 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#247]
See Atharva Engineer's Mineral Exploration Mission , how is he able to get the navpoints while others in other teams had to go through review of mission plans ?

[mars_simu_0.log](https://github.com/mars-sim/mars-sim/files/3966618/mars_simu_0.log)

**Comment by mokun** [comment]
> how is he able to get the navpoints while others in other teams had to go through review of mission plans ?

Say a person is organizing a mission. He would have to plan for the logistics such as looking at the terrain, determine what navpoints to route through, calculate proposed distance travelled, the duration of this mission, recruit members, reserve a vehicle, check if enough resources are available for this mission, etc.

When all these are good to go, the last thing he needs is to get his *mission plan* **approved**. 

Almost anybody within that settlement can review the mission plan and score it. 

However, it's intuitive to let the commander's score carries more weight since he's on the top of the food chain. Next is the sub-commander's, then the chiefs, then the specialists, etc..

```
00-Adir-01:080.009 (Info) Mission : [New Pompeii] Atharv Engineer began organizing a Mineral Exploration mission.
00-Adir-01:080.009 (Info) TravelMission : Atharv Engineer had put together the navpoints for the Mineral Exploration

```

**Comment by shirishag75** [comment]
right, but there is nothing to tell that why or how he got the points approved. Because he definitely is not the chief, and there is nothing to indicate why he got the job. I scoured but didn't find anything in the log I gave :(

**Comment by mokun** [comment]
> but there is nothing to tell that why or how he got the points approved. Because he definitely is not the chief,

Each time a mission plan is under review, you will see it in the stack trace.

You've probably seen it hundreds of time.

Everyone in that settlement will look at the mission plan and score it.

Each review will comprise 

See https://github.com/mars-sim/mars-sim/wiki/Missions

```
(1)          Rating : mission lead's cumulative job rating
(2)    Relationship : mission lead's relationship score with the reviewer
(3)  Qualifications : mission lead's mission qualification
(4)       Objective : does this mission fit into the settlement's overall objective
(5)       Emergency : is this a rescue or resupply mission ?
(6)           Sites : how accessible or how good are the collection rates are the sites to be visited
(7)        Distance : how many km is the proposed distance travelled
(8)      Leadership : how good is the mission lead's ability to lead			 
(9)   Reviewer Role : the weight of the role of the reviewer. (e.g. The commander as the reviewer has the highest weight)
(10)           Luck : add a little bit of randomness
```

**Comment by mokun** [comment]
```
00-Adir-01:207.895 (Info) MissionManager : Ayansh Chander's Mineral Exploration mission plan - current score : 111.9 (30.0% review completed)
00-Adir-01:207.895 (Info) ReviewMissionPlan : [New Pompeii] Nathan Srivastav graded Ayansh Chander's Mineral Exploration mission plan as follows :
00-Adir-01:207.895 (Info) ReviewMissionPlan :  ---------------------------
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (1)          Rating : 10.0
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (2)    Relationship : 12
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (3)  Qualifications : 6.25
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (4)       Objective : 0.0
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (5)       Emergency : 0
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (6)          Sites  : 0
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (7)       Distance  : 0
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (8)      Leadership : 5
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (9)   Reviewer Role : 2
00-Adir-01:207.895 (Info) ReviewMissionPlan :  (10)           Luck : 4
00-Adir-01:207.895 (Info) ReviewMissionPlan :  ----------------------------
00-Adir-01:207.895 (Info) ReviewMissionPlan :            Sub Total : 39.3
```

**Comment by mokun** [comment]
> why do some missions get approved, some don't need approval

ALL MISSIONS needs approved, namely passing the minimum score.

The minimum score is not static. It goes up or down according to the last approved mission plan.

We discuss about refining how a mission plan should be put together and scored a few times.

We also have a project setup. See https://github.com/mars-sim/mars-sim/projects/12

**Comment by shirishag75** [comment]
FWIW, https://github.com/mars-sim/mars-sim/projects/12 doesn't get me anywhere as https://github.com/mars-sim/mars-sim/projects does as it tells me what the 12th project is. I don't really know how github projects function . I am guessing it is some sort of discussion and taking steps place but till we know more about it, I dunno how much to use it. What one thing can be done is that each of the projects can be tied to an issue where it can be tracked. For e.g. 16 https://github.com/mars-sim/mars-sim/projects/16 should be tied to an issue ticket . I will ask in Debian-java team and users there is a good possibility that people may have ideas as to how it could be done. Maybe a bug similar to #75 needs to be opened so that it can be used to keep track of things.

**Comment by mokun** [comment]
@shirishag75 , please go ahead to tie a ticket/issue to a relevant project as you see fit.

**Comment by mokun** [comment]
@shirishag75 

>  there is nothing to tell that why or how he got the points approved

I just refined the Mission wiki. See [here](https://github.com/mars-sim/mars-sim/wiki/Missions) if you like my explanation.

**Comment by mokun** [comment]
Closing.
