### ISSUE TITLE
why isn't the commander.profile picked up when loading a previous game 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#249]
While in ~/.mars-sim/saved/ I see commander.profile it seems the commander.profile isn't picked up when I start load a saved game.  It seems it would make a new game as I tried to trick it by compiling the game for r5227 and then cheated the system by saying load the saved game even though there is nothing I played with the new version. It somehow makes a new game and doesn't even take the commander.profile. So seems couple of bugs are happening here - 

a. It doesn't complain or say there is no previous game for this version. 
b. It doesn't pick the commander.profile. 

So it seems I am destined to make the commander.profile each time I start the game. Doesn't seem right . I should be able to stop and start the game and have the commander with me at all times. 

Let me know what other tests you want me to do.

**Comment by mokun** [comment]
If you start a new sim, you can load the `commander.profile` by selecting "3. Load commander profile" 
in the `Crew Selection` menu as follows :

```
 ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------

                        * * *   Main Menu   * * *


0. Exit 
1. Start a new Sim
2. Load a saved Sim
3. Change screen resolution

Choose an option : ​1

Starting a new sim...

 ---------------  M A R S   S I M U L A T I O N   P R O J E C T  ---------------

                        * * *   Mode Selection   * * *


0. Exit
1. Command Mode
2. Sandbox Mode

Select the Game Mode: ​1

Go to Command Mode...


            * * *   Command Mode - Crew Selection   * * *

0. Exit
1. Enable/disable the alpha crew
2. Set up commander profile
3. Load commander profile
4. Back to previous menu

NOTE 1: By default, the alpha crew as defined in crew.xml is ENABLED unless it is changed.

Enter your choice: ​3


                * * *   Commander Profile  * * *

              First Name : M
               Last Name : K
                  Gender : M
                     Age : 30
                     Job : Architect
                 Country : India
                 Sponsor : Indian Space Research Organisation (ISRO)

Would you like to use this profile ? (Y/N) [Y]: ​y




           * * *   Command Mode - Site Selection   * * *


0. Exit
1. Open site editor
2. Proceed with default site selection

NOTE: the Console Editon does not come with the Site Editor.

Enter your choice: ​2
```

**Comment by mokun** [comment]
If you want to load a saved sim that has your assigned commander on it, it's even easier. 

There's no need to load the `commander.profile` at all.

The Person instance of the commander is already inside 'UnitManger' class.

Each simulation session must have an UnitManager instance.

So, just load that saved sim and you'll see the commander in the settlement.

**Comment by mokun** [comment]
See my snapshot below : 

![image](https://user-images.githubusercontent.com/1168584/70955519-0997a280-2026-11ea-99c7-ec05adf1b9dc.png)

**Comment by shirishag75** [comment]
> If you want to load a saved sim that has your assigned commander on it, it's even easier.
> 
> There's no need to load the `commander.profile` at all.
> 
> The Person instance of the commander is already inside 'UnitManger' class.
> 
> Each simulation session must have an UnitManager instance.
> 
> So, just load that saved sim and you'll see the commander in the settlement.

The problem is how do you know if the default.sim has your commander.profile or not. The best way I guess to do it is to go to ~/.mars-sim/saved remove all the .sim and the commander.profile, make a new game, have the commander profile made in the game and then save it. That probably is the only way to make sure the game would have the commander in it. Will try that and let you know.

**Comment by mokun** [comment]
> the problem is how do you know if the default.sim has your commander.profile or not. 

I can see why it confuses you.

The `default.sim` file itself CANNOT have `commander.profile`. The two files are **independent* from each other. 

`commander.profile` can ONLY be loaded from the beryx console when starting a **brand new* sim.

It will NEVER be used by `default.sim` at all. 

> The best way I guess to do it is to go to ~/.mars-sim/saved remove all the .sim and the commander.profile, 

There is no need to remove the `default.sim` .  

There can be **one and only one** `default.sim` in your '~/.mars-sim/saved`. 

When you manually choose to save a simulation using the default mode, the sim is saved as `default.sim`.

If you use the Swing Edition, we can click on the `Saved As` menu item and type in a filename of your own choice. e.g. `xyz.sim`, instead of `default.sim`.

**Comment by mokun** [comment]
I'm adding the option to do a "Save As" via beryx console.

**Comment by mokun** [comment]
A JFileChooser box will pop asking you to type in a new filename as follows : 

![image](https://user-images.githubusercontent.com/1168584/70962391-eaa30b80-2039-11ea-9b94-2183dddd8b75.png)

**Comment by shirishag75** [comment]
nice, this makes more sense, thank you :)

**Comment by mokun** [comment]
> I think even previous.sim would need to be fixed somehow as right now we have no indication as to what is inside of that saved.sim. Perhaps above is the answer, perhaps not.

`previous.sim` is the backup of the previous version of `default.sim`, something we mentioned in a thread in the past. It's nothing spectacular. Just a backup for the developer in case you need it.

**Comment by mokun** [comment]
> Having a unique name for the .sim would also help identify that, let me know what you think of that ?

@shirishag75 ,

Yes, you can always save it under whatever name you choose. Just choose `Save_As` in the console menu or in the `Save_As` button in the Main Window.

But if you choose `Save`, it will save it under the standard filename, namely, `default.sim`.

**Comment by mokun** [comment]
Closing.
