### ISSUE TITLE
default.sim and previous.sim and where they are should be in FAQ 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#250]
.There is no information about either default.sim and/or previous.sim. Details such what the files contain, where they can be found etc. should be in the FAQ. Also what happens if you delete previous.sim ? None of this is shared in the FAQ unfortunately or anywhere else I looked :(

**Comment by mokun** [comment]
`previous.sim` is just the previous backup of the default.sim, as the name suggested. See https://github.com/mars-sim/mars-sim/issues/125

Would you like to help writing a wiki page regarding the `default.sim` and/or `previous.sim` and `commander.txt` ? Appreciate ! You can look through existing wiki pages to get an idea of it.

**Comment by mokun** [comment]
btw, the [setup.md](https://github.com/mars-sim/mars-sim/blob/master/setup.md) does describe what `default.sim` is. But it's still good to mention it in a wiki page in future.
