### ISSUE TITLE
what do the numbers mean on the dashboard ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#255]
What do the numbers mean on the dashboard, I tried to see if there was an entry about the dashboard and the numbers on the wiki but didn't find anything which jumped out at me - 

![commander-dashboard](https://user-images.githubusercontent.com/727626/71063180-20441380-2164-11ea-87d4-3020e431acd4.png)

**Comment by mokun** [comment]
The design concept for these `level of effort` are still up in the air. 

The highest the effort level, more time and resources will be poured into a particular area.

We have a few round of discussions with @Urwumpe in some past threads regarding the prioritization of resources and objective of a settlement.

In near future, we can refine how these level concretely impact the operations of a settlement.

Perhaps we can tweak it in such a way that each division chief will pick up a category of operation.

Or we can replace this effort level concept with `project-based` type of operation.

e.g. Project Rescue : speed up the preparation of a rescue vehicle by 10%

**Comment by shirishag75** [comment]
I am ok with either way. Why I bought it to notice is that currently that the numbers by themselves make no sense or don't indicate what woud change if I change the numbers and how would that effect either the work or even people's mood. For e.g. if a commander gives more credit to safety works and repair works it should help allievate people's moods and propensity to work but that's a different thing altogether. 

Right now, just figuring out what decisions need to be made and how that decisions will affect my colony is something that needs to be established.

**Comment by mokun** [comment]
For development objective, we have this [wiki](https://github.com/mars-sim/mars-sim/wiki/Settlement-Objective). https://github.com/mars-sim/mars-sim/issues/121, 

See also *15. Settlement Development and Achievement
* in https://github.com/mars-sim/mars-sim/projects

@shirishag75, please help us link up various discussions and wikis for each project.

**Comment by shirishag75** [comment]
I am open to help but would like to narrow the scope of things a little so that chaos is contained. See #260 for what I propose. You can use the savegame, the only thing is all the other bases would have 0 or null as their answer in the default.sim or whatever unique name the .sim has.

**Comment by mokun** [comment]
@shirishag75 

Currently, there are 3 categories of operations that has a certain Level of Effort associated with it.  
1. Outstanding Repair'
2. Outstanding Maintenance
3. EVA Suit Production

At the beginning of a simulation, the level of effort of each operation is set to 1 by default.

You can change it to between 0 to 5. 

Just so you know, this value is converted to a modifier value. 

The higher the modifier value of an operation is, *more resources* will be devoted toward it 

Will do a commit to fine tune it.

**Comment by mokun** [comment]
Please help us develop better documentation and in-game help tips for the long run. Closing this.
