### ISSUE TITLE
automated saving doesn't save on unique sims or anywhere. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#257]
With unique sims, while I do get messages about saving but don't get anything about where they are saved. 

```
shirish@debian:"18 Dec 2019 12:33:41" ~/.mars-sim/saved$ ls -lh
total 1.3M
-rw-r--r-- 1 shirish shirish 1.3M Dec 18 11:01 commander-is-in.sim
-rw-r--r-- 1 shirish shirish  251 Dec 18 10:16 commander.txt
-rw-r--r-- 1 shirish shirish 1.3K Nov 21  2018 Mars.json
-rw-r--r-- 1 shirish shirish  911 Feb 11  2019 ui_settings.dtd
-rw-r--r-- 1 shirish shirish  483 Feb 11  2019 ui_settings.xml
```

AFAIR, the game saves every 30 minutes or so and if you look at the clock it hasn't saved yet after the time I saved it manually.

**Comment by mokun** [comment]
There are 3 save modes 
1. `SAVE` (by default)
2. `SAVE_AS` (choose your own filename
3. `AUTOSAVE`

`SAVE` (by default) will save the sim into `~/.mars-sim/saved/` folder only.

When choosing to do `SAVE_AS`, player can choose whichever folder to save the sim 

`AUTOSAVE` will save the simulation session into `~/.mars-sim//autosave/`
