### ISSUE TITLE
Why is Nathan Roberts unable to get into the rover 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#258]
[mars_simu_0.log](https://github.com/mars-sim/mars-sim/files/3977419/mars_simu_0.log)

`00-Adir-03:543.819 (Severe) RoverMission : [Princess of the Sands] Nathan Roberts was unable to enter rover Princess of the Sands
`This is in my log and I have no clue or idea about 2 things - 

a. Which camp does Nathan belong to ? I wish there was a way to query people at the very top when you connect to MarsNet to know what settlement he belongs to .  I think that feature was there before but got nerfed ?

b. Is there a way to know why he isn't able to get into the rover. I have seen similar situations like these and unable to know why people are unable to get into rovers. I know you have said that maybe that overpacked or something. But when you have 5-6 people signing off to your thing, you are supposed not to do such rookie mistakes. 

Also doesn't the rover have some sort of weighing thing to let Nathan or whoever know how much is the material in the rover or is that supposed to be an area of research/improvement ?

**Comment by mokun** [comment]
>  Is there a way to know why he isn't able to get into the rover.

Good catch ! 

I plow through the code and discover that the branching condition of boarding a rover in performEmbarkFromSettlementPhase() in RoverMission is bad. Will fix it soon.

In general, this log statement signifies running into some sort of pathfinding (https://en.wikipedia.org/wiki/Pathfinding) issues.

So we want the stack trace to report to the developer whenever a person fails to find a good walking route from where he was to where he wants to go.

**Comment by mokun** [comment]
@shirishag75. This was fixed a while back. Please double check.

**Comment by mokun** [comment]
@shirishag75 ,

This only happens if the condition that `Walk.canWalkAllSteps()` is false in `performEmbarkFromSettlementPhase()` in `RoverMission`. 

I haven't seen one, at least not recently.

Recommend closing this thread until it happens again.

**Comment by mokun** [comment]
@shirishag75 

I'm changing the tag of this issue as `improvement`, rather than a `bug` that we need to resolve.

> a. Which camp does Nathan belong to ? I wish there was a way to query people at the very top when you connect to MarsNet to know what settlement he belongs to

When there are multiple settlements, may be there's a better way in the log to show which settlement the person is coming from.

> b. Is there a way to know why he isn't able to get into the rover. I have seen similar situations like these and unable to know why people are unable to get into rovers.

There is a number of legit reasons as to why a person can't get into a rover. e.g. The vehicular airlock is not functioning, the vehicle is full, etc. 

But in terms of bug, bad pathfinding could be the major reason.

> Also doesn't the rover have some sort of weighing thing to let Nathan or whoever know how much is the material in the rover 

Yes each type of vehicle have standard weight. On top of that, there's a maximum capacity imposed on some of the resources. In other words, you can't put everything you want in a vehicle.

**Comment by mokun** [comment]
Massive refactoring have been done since then. Closing this issue.
