### ISSUE TITLE
why is lucy o'brien or even Amelia Smith are looked for repairs when they are doing other jobs ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#259]
See the task roster and still I am getting messages that she is supposed to fix repair the air leak or was going to. 

![task-roster-new-plymouth](https://user-images.githubusercontent.com/727626/71071568-c9930580-2174-11ea-9da8-996f37f153dc.png)
[mars_simu_0.log](https://github.com/mars-sim/mars-sim/files/3977478/mars_simu_0.log)

Maybe both of this is enough for you to make sense of what is going on.

**Comment by mokun** [comment]
Do you know there are 3 different types of repair ? 

Some malfunctions have all 3 types. Some having just 1 or 2 types.

See previous discussions at https://github.com/mars-sim/mars-sim/issues/194 and https://github.com/mars-sim/mars-sim/issues/177

I believe the core engine currently pick one chief repair for each type. But it's possible that anyone who has reasonably good *mechanical* skill should join in the repair to speed up the process.

**Comment by mokun** [comment]
```
00-Adir-01:097.980 (Info) MalfunctionManager : [New Plymouth] Lucy O'Brien was going to handle the repair due to 'Fuel Leak' on Inflatable Greenhouse 1
00-Adir-01:102.960 (Info) MalfunctionManager : [New Plymouth] Lucy O'Brien was going to handle the repair due to 'Fuel Leak' on Inflatable Greenhouse 1
00-Adir-01:108.012 (Info) MalfunctionManager : [New Plymouth] Lucy O'Brien was going to handle the repair due to 'Fuel Leak' on Inflatable Greenhouse 1
00-Adir-01:112.992 (Info) MalfunctionManager : [New Plymouth] Lucy O'Brien was going to handle the repair due to 'Fuel Leak' on Inflatable Greenhouse 1
```

Just made a change to tweak how these repetitive log statement should show up .

Let's see how well it work. We may discuss more on how to model the repair or how to bring more realism to the simulation.

**Comment by mokun** [comment]
@shirishag75 . Let me know if the repair log is good now.

**Comment by mokun** [comment]
We've since patched how malfunctions work. Close this now.
