### ISSUE TITLE
why does mars_simu_0.log keep data from old saves ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#264]
I was looking at `~/.mars-sim/logs/mars_simu_0.log` and saw it had data from almost the starting of the month i.e. December 1st, 2019 instead of now. Why is that ?

**Comment by mokun** [comment]
@shirishag75 

I'll have to find out the goals and the exact mechanics behind saving the logs as text files and why sometimes it saves but sometimes it doesn't. 

@Urwumpe 

Have you done similar things in other projects ?

**Comment by mokun** [comment]
@bevans2000 

Do you know the exact mechanics behind this log file ?

**Comment by bevans2000** [comment]
Yes I think I once looked at it. But can't remember where
