### ISSUE TITLE
cannot load a saved sim when using template

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#266]
I used r5252 and saved a game. Then logged out of the game and tried to load the save game using the 

`~/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-3.1.0-jar-with-dependencies.jar -template:1 -country:India -sponsor:ISRO`

I made the initial settlement with the same template and scenario and even had made the commander.profile. 

then tried to load the saved .sim but it didn't work, no idea why, it doesn't even produce some error saying why it doesn't work. 

![attempting-to-load-a-saved-sim](https://user-images.githubusercontent.com/727626/71553547-4c378280-2a09-11ea-99f6-a373d98612c0.png)

**Comment by mokun** [comment]
When you load a saved sim, you just have to do the following : 

> ~/games/mars-sim/mars-sim-headless/target$ java -jar mars-sim-headless-3.1.0-jar-with-dependencies.jar -load

**Comment by mokun** [comment]
Everything should work. Please verify it. Will close this soon.
