### ISSUE TITLE
ShenandoahGC is not supported by Oracle JDK, Java 12

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#267]
**Describe the bug/issue**
When starting mars simulation project using a Oracle JDK12, the start fails due to the following error:

"Option -XX:+UseShenandoahGC not supported"

**Affected Area**
 - mars-sim-main

**Expected behaviors**
The Shenandoah GC should be optional feature and only be enabled by experienced users. Oracle does not plan to support it and will likely not change their mind in a later version of the JDK.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version : Oracle JDK 12.0.1
 - mars-sim build version : r5253

**Additional context**
 - Add any other context about the problem here.

**Comment by mokun** [comment]
Done. closing this.
