### ISSUE TITLE
how to backup GitHub Wiki and Issues

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#27]
Is there a way to backup and restore a repo's Wiki and Issues ? 

With the backup, If we ever mess up the repo, we could restore them onto a new repo.

**Comment by mokun** [comment]
I found the "Clone in Desktop" button on lower right inside Wiki's page. It backup all the changes made so far in Wiki. I have no idea how to upload or sync them to any repo in the event our repo is corrupted.

No such a button in Issues' tab. It will be a lot more complicated to do so if it has pull requests embedded in some issues.

**Comment by larsnaesbye** [comment]
Yes, wikis are just like other repos in the sense that they can be cloned and written to :)

But why don't we just use the current mars-sim repo and overwrite with the changes from SVN, through clone, copy files, commit? Then we don't need to make a new one from scratch....

**Comment by mokun** [comment]
> But why don't we just use the current mars-sim repo and overwrite with the changes from SVN

I've tried a few commands to sync up the changes but nothing works. 

It may take a while to start using git to commit changes. The way I set things up in Eclipse, it's easy for me to commit changes. 

So it's actually good to figure how to sync the latest commits from svn to git while we are all getting used to using git to manage the versioning of mars-sim. I surely hope git will lower the learning curve for new developers. 

This brings up the next question : how hard is to sync git with svn BIDIRECTIONALLY ?

When we start using git to commit changes, how hard is it to sync up the changes in svn as well ?

**Comment by larsnaesbye** [comment]
Hmm... we have the SF repo and the GH repo (with older code). The GH repo has issues and wiki.
How would this work:
1. svn checkout mars-sim to /path1/to/harddrive
2. git clone mars-sim to /path2/to/harddrive
3. copy and merge (drag 'n' drop) files from the svn path to the git path
4. check that we can build fro git
4. git commit -a -m "updated"

**Comment by shirishag75** [comment]
I was able to make a local repo. of the wiki 

```
─[$] git clone https://github.com/mars-sim/mars-sim.wiki.git                                                                        [19:26:42]
Cloning into 'mars-sim.wiki'...
remote: Counting objects: 604, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 604 (delta 30), reused 0 (delta 0), pack-reused 549
Receiving objects: 100% (604/604), 1.24 MiB | 113.00 KiB/s, done.
Resolving deltas: 100% (328/328), done.
```

**Comment by mokun** [comment]
is it just backing up the wiki into your hard drive ?

I'm hoping to find a way to restore the wiki on a different repo, in case our wiki gets corrupted and we need to do that.

**Comment by larsnaesbye** [comment]
The wiki is just like any other git repo, it can be cloned/checked out and the .md files and pics stored anywhere else....

**Comment by larsnaesbye** [comment]
I'm closing this. We can backup by from one repo and restore it on another through git methods since it's an ordinary git repo.

**Comment by mokun** [comment]
Can you demo how to do it ? can you back up all our wikis now and restore it on one of our existing repo, say on /mars-sim-0, without touching or overwriting the code and issues on /mars-sim-0 ?

**Comment by larsnaesbye** [comment]
I just did - look in mars-sim0 wiki :-)

Commands:
```
git clone https://github.com/mars-sim/mars-sim.wiki.git
git clone https://github.com/mars-sim/mars-sim-0.wiki.git
rsync -av mars-sim.wiki/ mars-sim-0.wiki/ --exclude=".*"
cd mars-sim-0.wiki/
git add --all && git commit -m "backup of wiki"
git push
```

**Comment by mokun** [comment]
wow that's great. can you do the same thing for issues to see if it works similarly ?

**Comment by larsnaesbye** [comment]
Sadly not as easily, as issues are not stored in a git repo. There are tools who collect them via a REST interface, but it's a bit more hairy.

**Comment by larsnaesbye** [comment]
There is a Chrome extension which does this.... https://chrome.google.com/webstore/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf

**Comment by mokun** [comment]
awesome!
