### ISSUE TITLE
why turning processors manually off ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#270]
Am sharing the screenshot as well as the log, have no idea why they turned off the solid waste management or the black water processor off, no explanations given :(
![why-turning-processors-off](https://user-images.githubusercontent.com/727626/71637172-a8321f00-2c34-11ea-85da-ffee98595bb6.png)
[mars_simu_0.txt](https://github.com/mars-sim/mars-sim/files/4013687/mars_simu_0.txt)

**Comment by Urwumpe** [comment]
I can understand why this might make sense. But I would also like to see the actual reason for this. Much better would be some sort of production plan for the settlement. What should be produced and how much capacity should be constructed or kept in reserve for future growth?

**Comment by shirishag75** [comment]
> I can understand why this might make sense. But I would also like to see the actual reason for this. Much better would be some sort of production plan for the settlement. What should be produced and how much capacity should be constructed or kept in reserve for future growth?

I have the same thing, we can make educated guesses but guesses cannot be part of any justifiable action. For e.g. if turn the solid waste management process off, what does it mean, what implications it has to health and hygeine, the same with black water processing. This basically means reusability of water for hydroponics or any such uses. 

https://en.wikipedia.org/wiki/Blackwater_(waste)

**Comment by mokun** [comment]
Turning on waste management consumes power.

See `building.xml`
https://github.com/mars-sim/mars-sim/blob/b9b22d999195bbf01945f83952d2c82e8715ac29/mars-sim-core/src/main/resources/xml/buildings.xml#L316-L494

In case of `Solid Waste Management`, if there are no more toxic waste or solid waste, it will be turned off.

Turning on/off each process depends on its value point (VP).

If the amount of the input resources are *high*, the VP will become *high*, thus triggering the task of turning this process **on**.

If the amount of the input resources are *low* or one of the resources is *zero*, the VP will become very *low*, thus triggering the task of turning it **off**.

```
<process name= "Solid Waste Management" power-required=".3" default="on">
	<input resource="toxic waste" rate="4" ambient="false" />
	<input resource="solid waste" rate="6" ambient="false" />
	<output resource="fertilizer" rate="2" ambient="false" />
	<output resource="carbon dioxide" rate="2" ambient="false" />
	<output resource="water" rate="2" ambient="false" />
	<output resource="carbon" rate="2" ambient="false" />
</process>
```
