### ISSUE TITLE
Lot of deprecation warnings while compiling the game. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#272]
There are lot of warnings which I have shared while compiling the game. Please fix those. It does enable the compilation but I guess it would fail one way or the other while playing the game in the console mode. 
[mars-sim-issue.txt](https://github.com/mars-sim/mars-sim/files/4056867/mars-sim-issue.txt)

This is with r5256

**Comment by bevans2000** [comment]
duplicate of #278

**Comment by bevans2000** [comment]
duplicate #278
