### ISSUE TITLE
Still getting severerity and deprecation warnings in r5259 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#273]
This is while using/compiling with java 11. There are still lots of deprecation and severe warnings even after the latest updates. The package is compiled but I'm afraid to run it till the issues are not resolved. 
[mars-issue.txt](https://github.com/mars-sim/mars-sim/files/4080760/mars-issue.txt)

**Comment by mokun** [comment]
Some are just safety precaution and it doesn't affect anything.

There are a few deprecated methods from some old API in that we are using its source code. 

It's going to take a while to clear them.

**Comment by shirishag75** [comment]
> Some are just safety precaution and it doesn't affect anything.
> 
> There are a few deprecated methods from some old API in that we are using its source code.
> 
> It's going to take a while to clear them.

I compiled today again, saw the new changes, nothing much improved. Hope the deprecated methods are replaced because otherwise it's possible that something may creep in savefiles which makes it harder to fix later. Look forward to the changes soon.

**Comment by bevans2000** [comment]
Duplicates #278
