### ISSUE TITLE
cant locate JRE 12 to download...

### ISSUE THREAD

**Issue by cookins** [mars-sim/mars-sim#275]
Hello
im sorry, bu i cant find JRE 12 version... I going over oracle link, at download section, to JRE and it shows me Java 8 version to download. I was able to locate only JDK 12 version.
Can somebody provide me link to 12 version of JRE? thanks!
(im complete newb with java)

**Comment by jbosmans** [comment]
Hi, 
you'll want to go for either v11 or v14. 

v11 has long term support whereas v14 will expire in a few months, as has already happened to v12 - which is probably why you're having a hard time finding it. 

You can get both from here : https://adoptopenjdk.net/

Good luck !

**Comment by cookins** [comment]
> you'll want to go for either v11 or v14.
> You can get both from here : https://adoptopenjdk.net/

but there no JRE seems... only JDK
or its no difference?

**Comment by cookins** [comment]
thanks! hope it helps!

**Comment by jbosmans** [comment]
FYI The download pages include both JDK and JRE builds eg for v11 https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot
