### ISSUE TITLE
New game not starting...

### ISSUE THREAD

**Issue by cookins** [mars-sim/mars-sim#276]
hi
i just installed JDE 12.0.2+10 and downloaded 5273_swing_java11.jar.
After selecting new game and creating commander in so, i just getting message:
'Starting a new simulation with default site selection..."
and nothing happens.
any hints? thanks!

**Comment by mokun** [comment]
Hi @cookins, 

Can you copy and paste some screen shots for us to see here ? 

Appreciate !

**Comment by mokun** [comment]
I just did a commit that starts testing the use of Java 14 as the new JDK baseline for the next minor release. So far so good.

**Comment by cookins** [comment]
sorry for late reply -
well, im tried again once more - its seems working now. have no idea why there was issues before. thanks for help, anyway!

**Comment by mokun** [comment]
@cookins
 
no prob. Have fun !
