### ISSUE TITLE
3.1.0_console_java11.jar.7z, Doesn't open in the Windows GUI mode, JavaFX edition in only older builds

### ISSUE THREAD

**Issue by rlw9999** [mars-sim/mars-sim#277]
Mars-sim doesn't open in the Windows 10 console mode.  It only opens first from a cmd-dos window, then opens only in straight Java.  I have downloaded and installed the following Java console 'jdk-14.0.1_windows-x64_bin.exe'.  Please see the below attachments.

This is how mars-sim always opens:
![CMD and Java Console](https://user-images.githubusercontent.com/66102235/83217741-aad46a00-a129-11ea-94cc-ead5fb36eb8c.PNG)

I'm trying to find out how to open it like this:
![Windows 10 Console Mode](https://user-images.githubusercontent.com/66102235/83216376-55e32480-a126-11ea-8b63-b29d0cb0913f.PNG)

**Comment by Urwumpe** [comment]
That had been the screenshots of the JavaFX version, this one got harmed a bit because Oracle removed JavaFX from the SDK, leaving only OpenJFX behind to use. Eventually there will be a new JavaFX version of the UI, but the project went back to Swing as focus.

**Comment by mokun** [comment]
@rlw9999 , 

As @Urwumpe explained, we got rid of the use of JavaFX to focus on refining features, rather than the graphics. 

Therefore, we got rid of the *Main Menu* with that spinning Mars Globe since they require JavaFX.

For now, players do have to step through the *Console-based Main Menu* to start a sim.

In future, we will bring back a graphically driven main menu for sure.

Meanwhile, the *Crew Editor* is still available inside the *Site Editor*. 

Let us know.

**Comment by rlw9999** [comment]
So, I did see your post mokun about running a older version of mars-sim:

![4600](https://user-images.githubusercontent.com/66102235/84578237-c45bef80-ad80-11ea-8dc4-5e6b954c8387.JPG)

And I also saw this:

![46001](https://user-images.githubusercontent.com/66102235/84578249-e05f9100-ad80-11ea-80b8-69840201f4cd.JPG)

So I figured I could run that JavaFX version of mars-sim. I downloaded and installed this version of Java (as it says above):

![46004](https://user-images.githubusercontent.com/66102235/84578296-38969300-ad81-11ea-8628-33eb7a81bf59.JPG)

I have the following paths in my environment variables:

![46003](https://user-images.githubusercontent.com/66102235/84578355-a2af3800-ad81-11ea-9b5c-151ec7aa8286.JPG)



![46002](https://user-images.githubusercontent.com/66102235/84578339-8f9c6800-ad81-11ea-85c6-db6f7ec85c68.JPG)

And removed this variable: 

C:\ProgramData\Oracle\Java\javapath;

When I attempt to open:

![46005](https://user-images.githubusercontent.com/66102235/84578376-e43fe300-ad81-11ea-868a-496375b8a3ca.JPG)

Nothing ever opens.

Not sure what I'm doing wrong.  Sorry for the mess, just trying to enjoy all the hard that was put into this sim.  Thanks again..

**Comment by mokun** [comment]
> When I attempt to open

Hi @rlw9999, can you type "java -version" in the terminal or command prompt and copy and paste what you see here ?

**Comment by mokun** [comment]
@Urwumpe 
I just did a commit that starts testing the use of Java 14 as the new JDK baseline for the next minor release. So far so good.

@rlw9999 
We will fix whatever startup issue and begin working on the use of Java 14 JDK.

**Comment by mokun** [comment]
@rlw9999 , 

We've explained that while you may find the JavaFX edition of the binary in older build, it may work with Java 9 or Java 10 only, as the JDK of Java 11 decoupled itself from JavaFX API. 

In newer builds and the latest official release v3.1.1, we use Swing as GUI and won't need JavaFX, just so you know.

Let me know any issues you run into when starting the sim and close this issue when you feel you're done !
