### ISSUE TITLE
Crew suffocating while loading the rover, rover moving into garage, mission resource

### ISSUE THREAD

**Issue by Brytenwalda** [mars-sim/mars-sim#282]
**Describe the bug/issue**
In r5390 (3.1.2-snapshot), whenever I’m creating a mission, crew starts loading the rover indefinitely, at least until they suffocate. They never return back to the base, they just stand outside. They ignore orders assigned through commander’s dashboard and on the settlement map they are always outside, even if they are supposed to be doing something else according to the monitor tool.

**Affected Area**
 Settlement map

**Expected behaviors**
I would expect them to go back every once in a while to resupply.

**Comment by mokun** [comment]
@Brytenwalda
 
Yes noted.

We've recently discovered this conflicting case of an outside vehicle going inside the garage while someone was loading the vehicle outside. As a result, this person got stuck and couldn't move and couldn't stop his task of loading.

Will see if this is already fixed by the changes made between r5390 and r5428.

**Comment by mokun** [comment]
@bevans2000 ,

This bug has not been resolved. How would you resolve this ?

Say a vehicle A used to be outside when they started loading the resources.

At some point in time, a garage space was vacated by an outgoing vehicle B just embarked. 

Logically speaking, vehicle A should go into this empty garage space and resume loading resources there.

However, the settlers do have been given the tasks to load vehicle A would not know why vehicle A was gone inside.

This situation has not been accounted for, causing settlers to GET STRANDED OUTSIDE.

![image](https://user-images.githubusercontent.com/1168584/116806403-a3f46b00-aae1-11eb-9fbf-a1dda4f30a10.png)

**Comment by Urwumpe** [comment]
I suggest to simply follow RACI there. 

We need to define ONE settler who is accountable for loading the cargo and who defines where the rover is during loading. Not something implicit decided in multiple places. 

Also, this rover should be attached to the mission and nobody outside that mission should be allowed to move it. When we interrupt loading the cargo for moving the rover into the garage, this has to be decided by the "cargo master" or who else has that function for that mission. In that case, loading the rover has to stop, some settler has to enter the rover and drive it into the garage. And loading resumes as soon as the resource "rover" is ready for loading cargo again. 

So, it might make sense to model a "mission resource association" to a unit, that refers to a "mission resource" object. Such an object defines, how this resource is supposed to be used, which function it has in a mission and which state for that function it has. And when it is no longer needed for a mission, it could even be freed again before the mission is over, with the mission resource object staying with the mission as "historic evidence" that this object was once used in that mission.

**Comment by mokun** [comment]
@Urwumpe 

> We need to define ONE settler who is accountable for loading the cargo and who defines where the rover is during loading. Not something implicit decided in multiple places.

Yes. We just need to add the ability of following the chain of command in the mind of the settlers in this case, and not having a mind of their own :D
 
> Also, this rover should be attached to the mission and nobody outside that mission should be allowed to move it. When we interrupt loading the cargo for moving the rover into the garage, this has to be decided by the "cargo master" or who else has that function for that mission. 

Sure it's really great idea for having a cargo master and the rest of them would follow his lead.

> In that case, loading the rover has to stop, some settler has to enter the rover and drive it into the garage. And loading resumes as soon as the resource "rover" is ready for loading cargo again.

Right now, the Activity tab of a person's window shows the Main task, the subtask 1 and the subtask 2. It seems there have been circumstances like this one that would create a chain of subtasks.

@bevans2000 ,
Did you recall if in `Task` class, we only allow up to subtask 2, and subtask 3 is NOT allowed, right ? 

> So, it might make sense to model a "mission resource association" to a unit, that refers to a "mission resource" object. Such an object defines, how this resource is supposed to be used, which function it has in a mission and which state for that function it has. 

When you say "mission resource", do you mean, a spare tire, some amount of oxygen, etc. ?

> And when it is no longer needed for a mission, it could even be freed again before the mission is over, with the mission resource object staying with the mission as "historic evidence" that this object was once used in that mission.

How do you store this centralized object ?

Yes, we'll need to discuss further the architecture of storing these historical records and in what way they can be used. 


It's certainly more realistic to make the vehicle "remember" its history, as much as a person would recall what mission he has participated in the past, etc.

**Comment by Urwumpe** [comment]
> 
> When you say "mission resource", do you mean, a spare tire, some amount of oxygen, etc. ?

No, simply one abstract thing that is absolutely necessary for performing that mission. It could be a person, a rover, a tool, food, water, fuel, etc. Just something that is needed for acomplishing the mission. A spare tire could of course be a valid resource for the mission, if you include spares. But I really mean it as in the first sentence. 

We could create templates for such missions that just describe what kind of resource is needed - and leave it to the planning for that mission to find and reserve objects for one described function. If one selected resource (e.g. a rover) could fulfill the demands of multiple functions, we could of course allow to use one rover for multiple such functions. But we could of course, also have situations where a mission might want to use multiple rovers.

> 
> > And when it is no longer needed for a mission, it could even be freed again before the mission is over, with the mission resource object staying with the mission as "historic evidence" that this object was once used in that mission.
> 
> How do you store this centralized object ?

Must not be centralized. It should just be attached to the mission. if the missions are stored decentrally or even archived in a way, this would then also apply to the resources.

> It's certainly more realistic to make the vehicle "remember" its history, as much as a person would recall what mission he has participated in the past, etc.

At least be able to have this kind of information somewhere - must not be the vehicle. For example, it could make sense to convert the formerly dynamic mission data into constant archived mission data after the mission is completed or aborted. This data could then just be kept available in a temporary cache in simulation, whatever node we use there, while the actual data is kept on disk and can be retrieved only when needed. If we have a distributed simulation architecture, with different parts of the simulation running on different hosts, we would then need some way to fetch a clone of that data from remote hosts. But right now, this is purely hypothetically.

**Comment by mokun** [comment]
@Urwumpe , 

> We could create templates for such missions that just describe what kind of resource is needed

Yes we should further look into refining the mission planning aspects and create some kind of files for each file that's based on a standard template.  

> it could make sense to convert the formerly dynamic mission data into constant archived mission data after the mission is completed or aborted. 

Perhaps we could talk about designing and scoping out mission resource on a new thread or in the discussion page.

**Comment by mokun** [comment]
Looks like in the latest build 5780, at least we no longer encounter any settlers getting trapped and/or suffocating from loading or unloading vehicle resources. 

Will close this thread in a few days unless anyone found some related bugs.
