### ISSUE TITLE
Problem find JFreechart in clean build, Java vs. JSON serialization, concurrent thread for each settlement

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#283]
**Describe the bug/issue**
Clean mvn build fails.

**Affected Area**
Maven cannot download jfreechart from repo.maven.org. This site rejects the http protocol.

**Expected behaviors**
I think that the pom.xml of the mars-sim-ui module has an oversight in the repositories section. maven.org no longer supports http and https must be used. I changed the URL to https and it worked fine.

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version :  openjdk  Amazon Corretto-11.0.7.10.1
 - mars-sim build version : Latest on master branch

**Comment by mokun** [comment]
> I think that the pom.xml of the mars-sim-ui module has an oversight in the repositories section. maven.org no longer supports http and https must be used. I changed the URL to https and it worked fine.

That's awesome you found the reason.

Will change it. Thanks !

**Comment by mokun** [comment]
@bevans2000 

I just removed a few unused submodules recently to keep the codebase lean and mean :D 

Sorry that this includes the `mars-sim-service` that you contributed.

See [here](https://github.com/mars-sim/mars-sim/commit/2dd74470162440cfdbaa8954d9b25a2acde72745). 

It's been backup in GitHub, you can revive this project from there and don't hesitate to do so.

Just so you know.

**Comment by bevans2000** [comment]
Hay no problem.  
I still think the long term future should be a server/client based model. Reusing the existing simulation engine. To aid this moving from Java Object serialisation into a JPA approach would be good I think; writing to a proper RDBMS. Have you considered making it more concurrent? I see the main event simulation loop doing the ticks is a single thread. This could be changed to a thread per Settlement as Units between Settlement don't impact each other directly so it gives a logical partitioning. Vehicles on the move would be "owned" by their destination Settlement. Obviously the Settlement thread would be synchronised so they al process the same time period in step.
This would allow a single simulation to be running in the cloud that people could view together. Potentially users could take the Commander role of different Settlements. Essentially you can have your own Settlement that you control. 
Just some ideas I had.

**Comment by mokun** [comment]
@bevans2000 

> To aid this moving from Java Object serialisation into a JPA approach would be good I think; writing to a proper RDBMS.

Absolutely ! See project #1 in [here](https://github.com/mars-sim/mars-sim/projects).

We've said numerous occasion wanting to switch to JSON serialization or RDBMS. 



Please by all means contribute to this effort.

**Comment by mokun** [comment]
@bevans2000 

> Have you considered making it more concurrent? I see the main event simulation loop doing the ticks is a single thread. This could be changed to a thread per Settlement as Units between Settlement don't impact each other directly so it gives a logical partitioning. 

Yes. Good idea. I'll try setting up one thread per settlement or per few settlements, depending on the # of cores available in the machine where mars-sim is run.

> Vehicles on the move would be "owned" by their destination Settlement. Obviously the Settlement thread would be synchronised so they al process the same time period in step.

Right now the only contact point between two settlements is when a trader arrives at a settlement other than his home town on a trading mission. I'll see if there is any potential concurrency issue there.

**Comment by bevans2000** [comment]
I would avoid using Thread directly but use a ExecutorService.invokeAll and create a List of TickUpdater implements Callable where each new class TickUpdater represents a list of Units that exist at the same Settlement. Each TickUpdater would execute the Tick method for all Unit plus the parent Settlement. Any Unit not in a Settlement, i.e. those Units moving between Settlement go into a default TickUpdater that has no Settlement. Every simulation "Tick" would just run an InvokeAll on the list of TickUpdates.
You could configure the Executor Service to have a limit of Thread according to the number of cores or let the JVM decide.

**Comment by mokun** [comment]
> I would avoid using Thread directly but use a ExecutorService.invokeAll 

Yes for now, I'm experimenting in adopting Executor or ThreadPool for each SettlementTask

> and create a List of TickUpdater implements Callable where each new class TickUpdater represents a list of Units that exist at the same Settlement. Each TickUpdater would execute the Tick method for all Unit plus the parent Settlement. 

I don't fully understand how this will entail. 

I'll will commit my code in an hour or so. 

Can you then optimize the codes whatever way you see fit ?

**Comment by mokun** [comment]
> Any Unit not in a Settlement, i.e. those Units moving between Settlement go into a default TickUpdater that has no Settlement. Every simulation "Tick" would just run an InvokeAll on the list of TickUpdates.

We are relying on `ClockThreadTask` in `MasterClock`. Inside `ClockThreadTask`, it calls `addTime()` in every frame.  

Within `addTime()`, we have
```
// Add time to the Earth clock.
earthClock.addTime(earthMillis);
					
// Add time pulse to Mars clock.
marsClock.addTime(timePulse);
					
// Run the clock listener tasks that are in other package
fireClockPulse(timePulse);
```

How will TickUpdater be placing these method calls ?

**Comment by mokun** [comment]
> You could configure the Executor Service to have a limit of Thread according to the number of cores or let the JVM decide.

Yes, good point ! 

I've planned to put an upper limit on how many threads it will create for calling each settlement.

The `ExecutorService` will execute those `SettlementTask` inside `timePassing()` in `UnitManager` by calling `runExecutor(time)`.

**Comment by bevans2000** [comment]
I like the changes you have made to introduce the SettlementTask. Why are the ConstructionSites excluded from the Settlement.timePassing method?

**Comment by mokun** [comment]
> I like the changes you have made to introduce the SettlementTask. 

What is the best strategy for calling up static instance references such as `marsClock` in, say, `Building` ? 

I save a reference of `marsClock` in a lot of class so that I don't have to keep calling `marsClock = Simulation.instance().getMasterClock().getMarsClock()` every time I need it.

But in doing so, I litter a lot of class with these type of references.

Even though they are static reference, somehow I encounter a lot of NPE because of the threading issues since the logical partitioning of calling settlement tasks.

**Comment by mokun** [comment]
> Why are the ConstructionSites excluded from the Settlement.timePassing method?

No particular reason. 

In the next two commits or so, I'll take care of calling construction sites within each settlement by using its `ConstructionManager`

**Comment by mokun** [comment]
@bevans2000 

Also, I'd like to further bring in calling more tasks within each settlement.

Currently, I only touched the calling of units in those for loops in `UnitManager`'s `timePassing()` in and migrate them to `Settlement`'s `timePassing()`. 

I will need to restructure those managers in `clockPulse(double time)` in `Simulation`.

May be `Mars` should stay there since it deals with the global aspects of things such as weather, surface terrain, etc.

What do you see we should do to `MissionManager`, `ScientificStudyManager' and `TransportManager` and why it would make more sense to restructure in the direction that mars-sim is moving toward ?

Also, there are a few other managers instantiated in `initializeIntransientData` in Simulation. There are different in how they work. 

For example, `RelationshipManager`'s `timePassing()` is called by `Mind`'s `timePassing()` for each person.

**Comment by bevans2000** [comment]
I would think about refactoring the whole approach to modelling time and making it consistent. My idea would be to use something similar to a Command design pattern where the parameters to apply are passed into the Receiver. The Reciever in this case is anything that is advanced via a time pulse. So this would be a new Interface called 'TimeAware' for example, that has a 'timePassing' method taking a new POJO of ClockPulse. The pulse object would contain a reference to MarsClock and the existing double timePulse value.
Then everything that has to be advanced each time step can be treated the same and added to the Executor Task queue to be processed. I have a bit of spare time over the next couple of weeks as work is going through a quite period. If you want create an Issue and assign it to me and I can have a play with the ideas in my Fork.

**Comment by bevans2000** [comment]
I also ran the code through SonarQube today. https://sonarcloud.io/dashboard?id=com.github%3Amars-sim
Highlights area that should be addressed.

**Comment by mokun** [comment]
> I have a bit of spare time over the next couple of weeks as work is going through a quite period. If you want create an Issue and assign it to me and I can have a play with the ideas in my Fork.

@bevans2000, @jbosmans, @Urwumpe 

Do we all agree that the top priority project for mars-sim is adopting Jackson for JSON serialization ?

```
		<!-- https://mvnrepository.com/artifact/com.h2database/h2 : 2.2 MB -->
		<dependency>
		    <groupId>com.h2database</groupId>
		    <artifactId>h2</artifactId>
		    <version>1.4.200</version>
		</dependency> 
```

I once tried out H2 Database. See mars-sim-core's pom.xml.

But I didn't move forward setting it up running within mars-sim.
 
@bevans2000 , do you prefer implementing H2 or something else ?

I suppose if we want mars-sim to run as a massive simulation across machines, we'll eventually need Jackson to exchange data.

**Comment by bevans2000** [comment]
The point about the Serialization route whether object or JSON is the whole object model has to stay in memory and be written as one operation. This eventually limits the number of simulated objects. Alternatively consider an ORM approach and then abstract away from the actual database, H2 or whatever.

**Comment by mokun** [comment]
We've refactored the core to have everything belonging to a settlement to run on a thread. 

So this thread should be closed now. 

Will discuss about JSON serialization in another thread as we start to implement it.
