### ISSUE TITLE
Many static references to MarsClock

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#284]
**Describe the bug/issue**
There are many static variables referencing shared instances to MarsClock instance throughout the code base. This can make the code complex to trace and prone to multiple threading issues with concurrent updates. This also increase the memory consumption of objects.

**Affected Area**
The application of time within the simulation should update any attributes that are time dependent at that moment. The simulated objects should be constant to a moment in time of the last simulation pulse; not using internal copies of the MarsClock to calculate values. 

**Expected behaviors**
Proposal is to introduce a ClockPulse class that encapsulates time advancing. Then the any object which is time aware will receive an instance of this object when a pulse occurs; these can be tagged by a new Temporal interface. The changes may be small but wide reaching in terms of number of file touched. I'm proposing to do an Alpha version in a forked branch and create a Pull Request for review.

**Actual/Observed Behaviors**
Looking at the current code; the UI packages seems to use ClockListener but in a slower pulse via a second method of pulseUI. This seems a further complication that could be refactored into ClockListeners running at different rates.

**Comment by mokun** [comment]
> Looking at the current code; the UI packages seems to use ClockListener but in a slower pulse via a second method of pulseUI. This seems a further complication that could be refactored into ClockListeners running at different rates.

True. We should simplify it.  Can you revamp the architecture ?

**Comment by mokun** [comment]
> Proposal is to introduce a ClockPulse class that encapsulates time advancing. 

Sure. Now, will `ClockPulse` be a singleton class, similar to `Simulation` ? 

What if we make `MarsClock` or `MasterClock` a singleton class ?

**Comment by bevans2000** [comment]
I think the UI can be refactored to use the same listener method as the main simulation. But for those listeners instance they are not called every pulse. But that's a later phase.
Key with this is an evolution approach of gradually refactoring. Once the Unit subclasses have been converted I'll create a PullRequest. Then the private inner classes of the Unit can be addressed. I feel that it will flush old some old code that is no longer called.

**Comment by mokun** [comment]
> UI can be refactored to use the same listener method as the main simulation

But Swing has its own thread management. I've tried structuring in such a way to call the following two methods differently inside `run()` in `ClockListenerTask` within `MasterClock`

```

listener.clockPulse(time);
...

if (count > FACTOR) {
...
    listener.uiPulse(timeCache);
...
}
...

```

We call `clockPulse()` at 20 Hz and call `uiPulse()` at 5 Hz (once every 4 times of the `clockPulse()`.

**Comment by mokun** [comment]
> Once the Unit subclasses have been converted I'll create a PullRequest. 

Yes do by all means come up with a better and efficient architecture for sending out pulse and tracking the clock (`MasterClock` and `MarsClock`). Appreciate !

**Comment by bevans2000** [comment]
Found a bug in the MissionManager because it was not Thread Safe. Different Persons would be accessing the single shared probability cache. Started adding the DataLogger concept can handle recording values over a number of Sols in a common way. This will help reduce the dependency on the MarsClock.

**Comment by mokun** [comment]
@bevans2000 

That's awesome, thanks for the improvement / optimization.

Let see, on Nov 27, 2020, I did two commits. They were called r5444 and r5445 

Do you recall upon which one you created the "Updates to enable SonarQube" ?

**Comment by mokun** [comment]
@bevans2000 

How do should I choose the Pull in such a way that will incorporate all the changes made by both you and me since Nov 26 and 27 ?

**Comment by bevans2000** [comment]
@mokun This has  proved to be a hellish change recently. There is a bug somewhere concerning people leaving Airlocks. I think this existed already.
But during the investigation I found some places where the TaskManager/Mind logic could fail in edge cases. So I have some rework to only consider TaskMeta which have a positive probability score. Also converted the Mind.takeAction method to be iterative instead of recursive. Recursive can always be a problem and blow the stack space.
Close to have a PullRequest ready but it will be bigger than I intended and there maybe a few remaining problems.
But generally the simulation engine is going faster.

**Comment by mokun** [comment]
@bevans2000 

Scott said in a private email that he's been looking into the walking bugs. The codes that have to do with walking such as in `WalkSettlementInterior`. 

Let's see if you can look me up in our old sourceforge distro and send me an email. This way, I can cc you to bring you into the loop for discussing this walking bug.

**Comment by mokun** [comment]
@bevans2000 ,

> Mind.takeAction method to be iterative instead of recursive. Recursive can always be a problem and blow the stack space.

Sure we should get rid of the recursive structure in Mind and replace with an equitable architecture that preserve the unused time.

**Comment by mokun** [comment]
@bevans2000 

Another thing is about the subtasks.

Currently, it's possible to have a chain of subtasks. Each `Task` object can have one subtask, which is also a `Task` object and so on.

In Person's Window's activity tab, we have space for displaying the main task and its subtask and the 3rd subtask and that's it.

Should we limit how a subtask is created to avoid issues ?

**Comment by bevans2000** [comment]
I did fix one problem with walking. The walking speed modifier can go negative with a large inventory, then the Person gets further away. This will be in my changes. But there is definitely a Airlock bug of it not closing the outer door after it has been used, then  o one else can enter.
Also there was a problem with not randomly selecting hot meals. It always took the first meal from the list.
I feel there is something not right with people eating & drinking. They seem to not start an Eat task even though they are starving

**Comment by mokun** [comment]
> I did fix one problem with walking. The walking speed modifier can go negative with a large inventory, then the Person gets further away. T

Thanks for catching that.

> But there is definitely a Airlock bug of it not closing the outer door after it has been used, then o one else can enter.

is it when ingressing ? namely coming back from the outside EVA ?

I've seen sometimes they got stuck in one of the 4 chambers and they have already removed the EVA suit.

But somehow they are not able to finish the phase of "leaveAirlock()" in `EnterAirlock` and got stuck and unable to walk out of the EVA Airlock building.

**Comment by mokun** [comment]
> I feel there is something not right with people eating & drinking. They seem to not start an Eat task even though they are starving

It's possible that it's the same person got stuck in the airlock chamber and unable to eat.

Also, I notice people may get stuck in loading or unloading resources from a vehicle, thus unable to go eat.
