### ISSUE TITLE
MasterClock is reporting timing errors

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#287]
**Describe the bug/issue**
The MasterClock is generating a warning concerning missed frames and general slowdown.
`00-Adir-01:263.434 (Warning) MasterClock$ClockThreadTask : excess: 631 ms. currentTBU : 106 ms. executionTime : 738 ms. Recovering from a lost frame (Skips # 1).`

**Affected Area**
The masterClock slows down the simulation by reducing the timeRatio because it thinks the simulation is not keeping up. Hence it seems not possible to run the simulation for long periods in a high time ratio.

**Expected behaviors**
The MasterClock should adjust more to the users' request than "it's" opinion on how fast the simulation can go.

**Actual/Observed Behaviors**
The  root cause is likely to be the ClockListners now being synchronous so they keep all process the same time frame as a unit of work. The previous asynchronous approach would have allowed the clock pulse to follow a fire & forget pattern hence giving the impression that the simulation was running faster.

**Resolution**
 The resolution is to simplify the MasterClock so that it does not try and estimate/enforce the expected maximum frame rate according the physical characteristics of the hardware, e.g. # cores. The new approach should focus on the clock pulse being consistently fired in a regular frequency. Then using the elapsed real time between pulses to update the UpTimer. Secondly by applying the time ratio to the elapsed real time this gives increments for the EarthClock & MarsClock. 
The increment to the MarsClock should have a upper limit artificially applied; i.e. if the elapsed simulation time in this pulse is too large the simulation logic may become unrealistic. For example, 20 msols left on a Task but the pulse covers 100 msol thus the simulation time step becomes too course grained.
Here is an idea in pseudo code below. Obviously the existing addTime method would be reused.
```
lastTime = currentSystemTime();
for (simulationActive) {
   sleep(realtimeDuration);

   newTime = currentSystemTime();
   realElapsed = (newTime - lastTime);
   uptime += realElapsed;

   marsElaspsed = realElapsed * timeRatio;
   if (marsElasped > maxElapsedPerPulse) {
       marsElapsed = maxElapsedPerPulse;
       timeRatio *= 0.9; // Reduce time ratio 
   }
  else if (marsElapsed < minElapsedPerPulse) {
        marsElapsed = minElapsedPerPulse;
        timeRatio *= 1.1; // Reduce time ratio 
  }   

  addTime(marsElapsed); // Updates Clocks and fires a ClockPulse to listeners
   lastTime = newTime;
 }
```
This issue should also address a change to the `UpTimer` purpose to just record how long the simulation has been running and not monitor the periods between updates.

**Comment by mokun** [comment]
> to simplify the MasterClock so that it does not try and estimate/enforce the expected maximum frame rate according the physical characteristics of the hardware, e.g. # cores.

Sure. The current approach was that when creating the main game loop, # of cores would modify the default time ratio. The more the # of cores, the higher the initial adjusted time ratio is set to.

Recently, I've also factored in # cores in determining how many concurrent threads will be allowed to create. May be this needs to change. 

In my win 10 machine, JDK has 60+ threads running at the same time already. I've tried not to create too many threads because switching between threads can be costly.

I've seen some API that offers light weight threads that can be less costly to switch between them.

**Comment by mokun** [comment]
@bevans2000 

> The increment to the MarsClock should have a upper limit artificially applied; i.e. if the elapsed simulation time in this pulse is too large the simulation logic may become unrealistic. 

Yes that's a good idea. We should limit that. 

In the `Heating` class, setting the `time ratio` to 2048x or above is causing a lot of instability because, like you said, each step is too big. 

Because the delta time is big, the calculated heat loss or heat gain in each frame becomes very large and not fine-grained enough.

Thus the temperature calculation becomes unstable and large building having a big area such as the `Large Greenhouse` would have too much of a temperature swing. 

In that case, I've applied the use of a buffer to kind of hold off the excess heat gain or heat loss to make it more realistic. Could have used a different heat modeling approach.

**Comment by bevans2000** [comment]
@mokun  I have done an initial version of the proposed reworking in a separate branch. It feels much simpler to me.
I can't see a purpose for the base_TBU anymore as it no longer plays a part in the logic. I will remove it from the UI on the final commit.

**Comment by bevans2000** [comment]
@mokun  These changes are ready to do.  Look at the calculateSleepTime method in the MasterClock for an idea how it now works.

**Comment by mokun** [comment]
@bevans2000 

I just did a [commit](https://github.com/mars-sim/mars-sim/commit/f21994df8af307215f3d908e5c67d732b063481e) in that I commented out `logger.info("AddTime not accepted: lastPulse " + tLast)` in `MasterClock` because whenever I put the simulation on pause, this log statement keeps on printing.

```
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
00-Adir-01:727.084 (Info) MasterClock$ClockThreadTask : AddTime not accepted: lastPulse 1609290481813
```
Q: do you still need it to gauge if addTime() becomes false (when acceptablePulse is false) ?

**Comment by mokun** [comment]
In my simulation, I have `Sleep skipped: too short` from time to time. See below.

Also, I have wanted to keep track of why a person is repeated calling on a task by printing `...had been doing ...x` in Mind. It's been happening frequently since the refactoring.

Is there a better way for tracking this issue ? 

```
00-Adir-01:442.198 (Warning) Mind [x13] : Santiago Ferreira had been doing 241x 'Egressing for an EVA' without consuming any time.
00-Adir-01:461.877 (Info) DigLocalRegolith : [Schiaparelli Point] Ioannis Papadakis was checking in 0.0 kg regolith.
00-Adir-01:483.476 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:496.002 (Info) RespondToStudyInvitation : [Zvezda] Uliana Kuznetsov rejected invitation from Jakub Woźniak to collaborate on chemistry level 1
00-Adir-01:501.106 (Warning) Mind [x17] : Santiago Ferreira had been doing 321x 'Egressing for an EVA' without consuming any time.
00-Adir-01:528.871 (Info) DigLocalRegolith [x2] : [Schiaparelli Point] Emily Evans was checking in 48.8 kg regolith.
00-Adir-01:530.382 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:536.472 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:542.003 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:546.432 (Info) RespondToStudyInvitation : [New Pompeii] Riaan Ganesh accepted invitation from Jakub Woźniak to collaborate on chemistry level 1
00-Adir-01:546.432 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:551.877 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:564.836 (Warning) Mind [x18] : Santiago Ferreira had been doing 381x 'Egressing for an EVA' without consuming any time.
00-Adir-01:567.281 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:573.302 (Warning) MasterClock$ClockThreadTask : Sleep skipped: too short
00-Adir-01:628.669 (Warning) Mind [x11] : Margarita Bykovsky had been doing 531x 'Walking Settlement Interior' without consuming any time.
```

**Comment by bevans2000** [comment]
No there is no need for the AddTime info message now if the simulation is paused. The sleep skipped info can also be removed as it just shows the simulation is consuming processing resources.
The problem with the stuck Task causes the sleep skipped message as it consumes processing each pulse. I'm sure there is a bug in the airlock Egress code as these people can not enter the airlock. This should be a separate Issue.

**Comment by mokun** [comment]
How do we maintain the stability of the clock cycle ?

![image](https://user-images.githubusercontent.com/1168584/123554955-8b967a80-d737-11eb-98c1-d4451855057f.png)

In know it's machine dependent that the TPS can become very low. 

Should we impose the upper limit on how the player changes the time ratio (TR) ?

Say 
- if average TPS  is below 20, then the TR cannot be higher than 512x.
- if average TPS  is below 10, then the TR cannot be higher than 256x.
- if average TPS  is below 5, then the TR cannot be higher than 128x.  
- if average TPS  is below 2.5, then the TR cannot be higher than 64x.  

I suppose there's no way in Java to gauge how much load the cpu is experiencing and how fast or "powerful" a cpu is, as we have to develop our own benchmark to measure that.

**Comment by mokun** [comment]
@bevans2000 

I don't exactly like the slider bar for the TR.

How do you like the plus and minus button in a PC game called *Stellarius" as follows : 

![image](https://user-images.githubusercontent.com/1168584/123555297-c9949e00-d739-11eb-8a95-bf0e56ab5812.png)

This way, we don't have to change the # of ticks of a slider. 

We could compute and update the max TR that each machine would allow once in a while.

The player can still click on the plus button to increase the speed and click on the minus button to decrease the speed.

**Comment by bevans2000** [comment]
So having a fixed TPS is not that easy because the CPU time per ticks varies a lot. This all depends on what has to happen within the tick. The current logic I think is not that bad as it adjusts the sleep time at every tick. It aims to make the elapsed msols as small as possible per tick; hence giving a more accurate simulation. The "accuracy" can be adjusted in the XML files.
There IS an lower and upper limit on the elapsed MSol per tick because too small is just inefficient and too large can make it inaccurate.
The CPU used per tick is also unfortunately affected by the UI which is a design problem. #309 addresses removing the UI updating from the tick processing; this should be done. Also there is an updateUI method on the clock listener; this should also go. The UI should be responsible for updating it's own screen ONLY when there are visible. Generally I believe whatever the client is doing it should be read-only and not have any impact on the tick processing.
Don't add this close defect to the 3.2.0 release; create a new one.

**Comment by mokun** [comment]
> Generally I believe whatever the client is doing it should be read-only and not have any impact on the tick processing.

Sure. 

So currently we let player DIRECTLY change the TR. This is actually not a good thing. 

TR should be adjusted internally to meet whatever stability requirement we impose. 

We'll let player to click on this new *increase speed* button but it's no guarantee how much more of TR will increase as it hits the upper limit, the *increase speed* button won't work.

Similarly, when the player click on the new *decrease speed* button, it will decrease the TR somewhat but within the lower limit.
