### ISSUE TITLE
Console code complex

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#288]
**Describe the bug/issue**
The code in the console modules is complex with some very long methods containing multiple if conditions resulting in a very high complexity rating in static code analysis. This makes it difficult to maintenance and extend in the future.
For example, looking into add a new command to the Settlement chat was daunting.

**Proposal**
The module could be refactor to follow a Command pattern where each interaction between user and simulation would be the responsibility of a dedicated Command class, e.g. Person health, Settlement dashboard or simulation time.  Then these commands could be easily combined together via a common framework to provide the chat functionality. I have something appropriate from a previous project.

The logic for each existing command can be migrated to a dedicated new Command class to simplify the transition.

As a further change the responses needing formatting or complex output could use [Mustache Templates](https://mustache.github.io/) to separate presentation from calculation. The template could then be internationalised to provide different language bindings.

**Comment by mokun** [comment]
@bevans2000 , 

> As a further change the responses needing formatting or complex output could use Mustache Templates to separate presentation from calculation.

Yes I'd love to get rid of the use of the branch conditions in the console-related class.

Do by all means show us a small example in how to convert that.

**Comment by bevans2000** [comment]
Sure, I will create a branch and work on a prototype later in the week or next week. I will create the branch in the main repo to allow the work to be shared once a framework is in place.

**Comment by mokun** [comment]
This [commit](https://github.com/mars-sim/mars-sim/commit/2417908495ab014c8a0913ed1727814ad097808e) is awesome.

**Comment by bevans2000** [comment]
@bevans2000 Glad you like it. You can see the idea. Having it based on a Command pattern is perfect for this scenario.
Just a case of converting the old 'if' logic into individual classes. Should be done in a few days.
Also going to use the introduction to tell you some basic details when you first connect to a Unit.

**Comment by mokun** [comment]
Hi @bevans2000,

Thanks for refactoring all the console-related class. 

So if you do a pull, I can merge all your changes.

**Comment by bevans2000** [comment]
There is just a little bit of tidying up left and testing to do. I'll create a pull request when it ready. I might have time to do it tomorrow.

**Comment by mokun** [comment]
@bevans2000 ,

Can you check why the autocomplete feature for getting settlement names or other's names no longer work ?

![image](https://user-images.githubusercontent.com/1168584/104765971-9f689a00-571e-11eb-8486-98cdd834776d.png)

**Comment by bevans2000** [comment]
I think its working. The change to the connect command is the Unit name goes on the same line. I tried to remove the interactive nature of the commands if there was only one input. Thi sis make the interaction quicker with most being done via single commands.
So try

1. Try 'connect S' or '/c S' don't press enter.
'2. Hit tab, key this will present the first unit names starting with S. (S is a good example as it finds Settlements, Vehicles & Persons)
3. Continue with tab to cycle round the matches
4. Press enter when a match found
5. Or use the delete and refine the match by changing 'S' to 'Sa' for example.

You can still uses the Up & Down arrow to cycle through the command history; this is why I tried to collapse command to single entries.

**Comment by bevans2000** [comment]
@mokun did it work? I think having commands on a single line is better because they work with the up & down history. Resources and levels are other examples

**Comment by mokun** [comment]
> @mokun did it work? I think having commands on a single line is better because they work with the up & down history. Resources and levels are other examples

Yes it works. Guess this is a little different from what it used to be and it's probably better this way.

The tab key now presents all the names from settlements, vehicles, settlers, etc.

**Comment by bevans2000** [comment]
The tab key also does partial matches as well, so typing Z followed by tab will return all Units starting with a Z

**Comment by bevans2000** [comment]
The tab key also works for most arguments, e.g. connect to a Settlement and run >resources hit the tab key. This presents the various types of resources applicable.
Can we close this now?

**Comment by mokun** [comment]
> The tab key also does partial matches as well, so typing Z followed by tab will return all Units starting with a Z

Yes it works.

**Comment by mokun** [comment]
@bevans2000 ,

In MarsNet, we have the text output :

> More detailed help by using > help <long command>

What do you want to be the difference between typing in `/?` and `help` at the prompt ?

I look at `HelpCommand` class and saw

> 	public static final String HELP_LONG = "help";

**Comment by bevans2000** [comment]
The way this is approached is the `/` command is just a short cut to typing the longer command. So at the moment both point to the same `HelpCommand`. Are you saying there should  be 2 outputs from help?

**Comment by mokun** [comment]
> The way this is approached is the `/` command is just a short cut to typing the longer command. So at the moment both point to the same `HelpCommand`. Are you saying there should be 2 outputs from help?

Because you output like 
> More detailed help by using > help


I thought "More detailed" meant more comprehensive examples. 

So `>/?` is *short* help while `>help` is *long* help. Is it not ?

**Comment by bevans2000** [comment]
Hahaha Yes I can see now how the banner text could be misinterpreted. Probably needs to be changed to make it clear the short command name & long command name are actually the same command. I always use the short form but on Settlement there is a conflict with 2 Commands having the same short format name.
Generally I think the new Console framework is working well. It is much easier to add new Commands. I have added some as part of the general work. Plan to add a Livestock command to show the status of Fish & Bees.

**Comment by mokun** [comment]
> Generally I think the new Console framework is working well. It is much easier to add new Commands. 

Yes. It's extensible now and that's fabulous. Appreciate !

> Plan to add a Livestock command to show the status of Fish & Bees.

Great ! So I suppose bees can be found in regular greenhouses, right ?

**Comment by mokun** [comment]
@bevans2000 

Currently, the use of -template switch to start a settlement directly is not working in the console mode.

Can you check MarsProjectHeadless and MarsProjectHeadlessStarter ?
 
Just so you know, recently, I changed all the names of the templates. 

No more "Mars Direct Base (Phase 1)", etc.

It would just call "Phase 1-U" for a U.S. base in phase 1, or "Phase 1-X", for a SpaceX base in phase 1.

I only implemented the changes in MarsProject and MarsProjectStarter and have yet understood how to modify MarsProjectHeadless.

```
2021-06-15T13:58:31.6 (Config) MarsProjectHeadless : Starting Mars Simulation Project v3.1.2-Snapshot - Build 5817 - 64-bit Java 13.0.2 - 8 CPU threads
2021-06-15T13:58:31.6 (Config) MarsProjectHeadless$SimulationTask : List of input args : [-template:3] [-sponsor:SpaceX] [-country:USA] 
Unrecognized option: -template:3
usage: [for mars-sim headless edition]
 -datadir <path to data directory>   Path to the data directory for
                                     simulation files (defaults to
                                     user.home)
 -help                               Help of the options
 -load <path to simulation file>     Load the a previously saved sim,
                                     default is used if none specifed
 -new                                Create a new simulation if one is not
                                     present
 -remote <port number>               Run the remote console service
 -resetadmin                         Reset teh internal admin password
 -template <template sponsor>        New simulation from a template for a
                                     sponsor
 -timeratio <Ratio (power of 2)>     Define the time ratio of the
                                     simulation
```

**Comment by mokun** [comment]
btw, the letter code behind the number is as follows (found in `settlements.xml`): 

```
	<!-- List of initial settlements in the simulation -->
	<initial-settlement-list>
	<!-- For each settlement, use one of the followings as sponsors : 
		- U - National Aeronautics and Space Administration (NASA)
		- C - China National Space Administration (CNSA)
		- I - Indian Space Research Organisation (ISRO)
		- R - Roscosmos (RKA)		
		- A - Canadian Space Agency (CSA)
		- E - European Space Agency (ESA)
		- J - Japan Aerospace Exploration Agency (JAXA)
		- M - Mars Society (MS)
		- X - Space Exploration Technologies (SpaceX)
	 -->
```

**Comment by bevans2000** [comment]
Ok. So the single letter maps to a ReportingAuthorutyType?

**Comment by mokun** [comment]
> Ok. So the single letter maps to a ReportingAuthorutyType?

Not really. The single letter designation simplifies `ReportingAuthorityType` further.

It's shorter to type `1-C`, rather than `1-CNSA`

**Comment by bevans2000** [comment]
OK so I see what is going on now. A few questions because I think there can be some improvement here to improve the readability and maintainability:

1. Any Sponsor is a ReportingAuthority. Of not does it matter if it is not.
2. Why in the settlement.xml do we use the long Sponsor name and not just use the code values of the ReportingAuthorityType? It would make it easier to avoid typos.
3. The -template argument is actually taking the integer id of the template settlement in the settlement.xml? So if the order changed the id would point to a different template.
4. A real confusing one for me. Why do we have 2 entries for every ReportingAuthority in the enum type? One for the short name and one for the long. These should be combined to be one with 2 different names.

I feel there is a lot of reliance on String to drive the template & sponsor. It would be better to base it on the ReportingAuthorityType values and have that as the driver. If you agree let's create a separate 'Improvement' issue and I can work on it. It would help towards "slimming" down the `UnitManager` also.
