### ISSUE TITLE
Go haywire when returning from power saving

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#290]
**Describe the bug**
The simulation session is unable to recover from power saving in Windows 10

**To Reproduce**
1. Start the mars-sim
2. Close the lid of the laptop
3. Wait for a few seconds for win 10 OS to enter the power saving mode
4. Open the lid of the laptop and look at the mars-sim's simulation 

**Expected behavior**
The game loop in mars-sim is supposed to track and understand the passage of time in such a way that it will respond when the OS is put to sleep and when OS wakes up.

**Desktop (please complete the following information):**
 - OS: Win 10
 - r5480

**Additional context**
Recent changes in `MasterClock` and `MarsClock` may have altered the use of `UpTimer` class to partially track the passage of time.

When coming back from the power saving, the simulation is calling `ConnectWithEarth` hundreds of thousands of times. mars-sim's CPU utilization would top 95- 99%.

**Comment by mokun** [comment]
@bevans2000 ,

How do we make JVM aware of the OS power saving events so that it will respond appropriately ?

**Comment by mokun** [comment]
@bevans2000 

```
00-Adir-02:647.796 (Warning) Mind [x28] : Leonardo DaVinci had been doing 275x 'Ingressing from an EVA' (Remaining Time: 0.0; Time: 0.5).
00-Adir-02:647.796 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:648.296 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:648.796 (Warning) MasterClock : Proposed pulse 0.15391678337713158 increased to min 0.5
00-Adir-02:649.296 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:649.796 (Warning) EVASuit [x36] : [39.31° S 7.00° W] EVA Suit 045 got 0.0 kg O2 left at partial pressure of 0.0 kPa.
00-Adir-02:649.796 (Warning) MasterClock : Proposed pulse 0.1526551703986305 increased to min 0.5
00-Adir-02:650.296 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:650.796 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:651.296 (Warning) EVASuit [x72] : [39.31° S 7.00° W] EVA Suit 045 worned by Noah Shan had less than 0.1792 kg oxygen (below the safety limit).
00-Adir-02:651.296 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:651.796 (Warning) MasterClock : Proposed pulse 0.15283540082413063 increased to min 0.5
00-Adir-02:652.296 (Warning) MasterClock : Proposed pulse 0.15274528561138057 increased to min 0.5
00-Adir-02:652.796 (Warning) MasterClock : Proposed pulse 0.15283540082413063 increased to min 0.5
00-Adir-02:653.296 (Warning) MasterClock : Proposed pulse 0.15400689858988165 increased to min 0.5
00-Adir-02:653.796 (Warning) Mind [x24] : Leonardo DaVinci had been doing 287x 'null' (Remaining Time: 0.0; Time: 0.5).
00-Adir-02:653.796 (Warning) MasterClock : Proposed pulse 0.15292551603688073 increased to min 0.5
00-Adir-02:654.296 (Warning) MasterClock : Proposed pulse 0.1526551703986305 increased to min 0.5
```

When I move the time ratio slide in the Time Tool to the left, I notice that the pulse is now limited to a minimum of 0.5 millisols. 

Is there any particular reason for that ?

**Comment by bevans2000** [comment]
Yes, you can change the default minimum pulse in the XML file. I just choose 0.5 as an abartiary value. Make it smaller.
I can look into this poser issue later today.

**Comment by bevans2000** [comment]
Actually I found something similar with the Connecting to earth without a power save. It is a bug to do with someone not being able to finish their walk to find somewhere to connect. The task has a NULL phase and then it never consumes any time and goes on for ever.
