### ISSUE TITLE
Task isolation

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#297]
**Describe the bug/issue**
The TaskManager is widely used outside the Person class which is increasing the cohesion. This also exposed the Mind class to callers.
Both of these should be private implementations of the Person concept.
**Proposal**
The Person class should just expose a getTask method and the getSubTaskX & get TaskDescription should be dropped. The Task should provide a getDescription method that inteprets the Task & SubTasks. 
One problem is subtasks are not removed when they are completed; they just have their name blanked out.

**Comment by mokun** [comment]
> The TaskManager is widely used outside the Person class which is increasing the cohesion. This also exposed the Mind class to callers.

Yes. Agree.

> One problem is subtasks are not removed when they are completed; they just have their name blanked out.

I thought if a subtask is done, it's set to null and thus removed. Is it not ?

Yes, let's make sure it does !

Also, if a subtask is being removed, then we would need to make sure when the Person Window and other tools display about a person, we would need to watch for some NPE showing up and in that case, we'll need to print blank.

**Comment by bevans2000** [comment]
Started looking into this activity. I think the first step is to consolidate Robot & Person into a common `Worker` interface around which the Tasks can be based. This interface would present `SkillManager` and `AttributeManager`; the latter being a subclass of the Robot & Person types.
This `Worker` interface could be applied to Malfunctions and other places. I think it is a generalisation of the existing `MissionMember` interface.
This would remove a lot of duplicate code in the Task packages that handle Robot & Person explicitly.

**Comment by mokun** [comment]
> This would remove a lot of duplicate code in the Task packages that handle Robot & Person explicitly.

Okay. `TaskManager` and `BotTaskManager` are very similar. It was for clarity sake that I created `BotTaskManager` just for robot use.

**Comment by mokun** [comment]
@bevans2000 ,

I'm trying out a PC game called Foundation recently. Like other strategy games, it allows players to pick one job for each person at a time only. 

And this job title is associated with one and only one task.

This is a lot simpler and cleaner than what we've been doing in mars-sim.

Do you think we should return to this simple way of implementation ?

**Comment by bevans2000** [comment]
I think the current strategy is good that every Person can do any job. In a small Settlement everyone would have to be a generalised. Maybe once we simplify the Task we should look to weight the Task probabilities more to the Person's job.

**Comment by bevans2000** [comment]
> > This would remove a lot of duplicate code in the Task packages that handle Robot & Person explicitly.
> 
> Okay. `TaskManager` and `BotTaskManager` are very similar. It was for clarity sake that I created `BotTaskManager` just for robot use.

I think that's fine, we can look to consolidate any logic into a single AbstractTaskManager if possible.

**Comment by bevans2000** [comment]
Whilst working on issue #320 I discovered that creating a new `Task` involves changing a lot of classes. It would be better if the `TaskMeta` is registered once and then everything else is driven by the meta class. In particular the class names have to be declared in the Person `Preference` and `Job` classes. 
To achieve this we should added a new `TaskAbilities` and `FavourType` properties to the TaskMeta to make it generic and data drive. The latter Abilities is an enum property would reflect the type of skills needed to complete the task  It could also be used to map to Jobs to calculate the probability of starting a task. Each `Job` would state the `TaskAbilities` it prefers, e.g. Architect likes Construction. The mapping is already implied in the `Preferences.initialisePreferences` method in Part 2.
I see it as
1. TaskMeta - Favourite Type is used directly in the TaskMeta.getProbability (Note this method has a lot of duplicate logic in the subclasses)
2. TaskMeta - Favourite Type is used to calculate the individual scores in the Preference class by using the Persons NaturalAttributes
3. TaskMeta - Abilities is used to calculate the individual scores in the Preference class by using the Persons NaturalAttributes
3. TaskMeta - Abilities is used by the Job.getStartTaskProbabilityModifier method.

**Comment by bevans2000** [comment]
First step I am going to is to create a `Worker` interface that allows most of the differences between Person & Robot to be centralised. This will remove duplicate code and consolidate what there is. To support this the Attributes shall be consolidated into a single `AttributeManager` from which the `RobotAttributeManager` and `PersonAttributeManager` will be subclassed.

**Comment by bevans2000** [comment]
Next on the Task rework is do address the TaskMeta classes. Their class types are referenced in many different places in the code. This makes adding a new Task very difficult. 
I want to make the logic in Preferences and Shift Task be property driven instead of explicitly using the class names. Also, use the ClassLoader to discover the available TaskMeta subclasses instead of explicitly adding them.
The outcome will be adding new Tasks will become very easy.

**Comment by mokun** [comment]
> Next on the Task rework is do address the TaskMeta classes. Their class types are referenced in many different places in the code. This makes adding a new Task very difficult.

But wouldn't it be even better if we only have one class for a task, instead of having two ?

**Comment by bevans2000** [comment]
Possibility but at the moment it implements a class Factory pattern which is nice. Also there is a clear separation:
- TaskMeta - is not an simulation object and is essentially a Singleton per Task type. Has clearly defined responsibly of identifying workable Tasks
- Task - Simulation instance object that is "short lived". In some cases complex logic tightly coupled with the Task execution (Mind) framework.

However one important factor is not all Task have a Meta equivalent because they are explicitly created and not scored, e.g. Walk, EnterAirlock, OperateVehlcle. These have no need for a probability scoring. 
There is some shared logic for some of the Task and we need to make sure we do not copy and paste that logic but I think this is done in most cases. Maybe some method names need to change to re-enforce this point,

**Comment by bevans2000** [comment]
I have nearly completed the rework of `MetaTask`. The key goal of the changes is to reduce the coupling between the MetaTask subclasses and other core classes. The task subclasses should not be a dependency for other packages, it should be at the top of the hierarchy. This makes it easy to add new Tasks in the future.
MetaTasks are now self contained so each defines how it's selected by the TaskManager. The selection logic is no longer using explicit MetaTask classes inside the Job or Preference class.  Selection is now based on properties of the MetaTask:
- A FavouriteType to match to a Person
-- A set of `TaskTrait` that defines characteristics of a Task, e.g. agility, relaxation 
- The most suited JobType
These three together influence the probability score. The new approach should provide the same probabilities scores but will be much more maintainable.
The downside is a lot if files have had small changes

**Comment by mokun** [comment]
> I have nearly completed the rework of `MetaTask`.

Wow this involves a lot of files. 

> The task subclasses should not be a dependency for other packages, it should be at the top of the hierarchy. This makes it easy to add new Tasks in the future.

Yes the less we have to change when adding new tasks, the better !

**Comment by bevans2000** [comment]
> > I have nearly completed the rework of `MetaTask`.
> 
> Wow this involves a lot of files.
> 
Yes I was nervous with so many changes which is why I'm working on a branch. Been running long simulations recently to see if any problems come up.
The bulk of the changes are very small due to change in `Mind` to use `JobType` instead of `Job`. This makes the code more effecient using an enum also removes many cases of logic based on instance of or even equals on the Job name !!.

A further stage would be to consolidate duplicate logic in the MetaTask subclasses. Different classes use the same data slightly diferently, e.g. Job. I think this leads to the Tasks not being balanced in their probability scores, I.e. 2 tasks that have the same 'importance'are producing different probability scores. There is a base probably specific for each Task but then a common set of Person/Robot modifiers that are applicable to all Task. But the common modifier logic is embedded in each MetaTask which is not good.

> Yes the less we have to change when adding new tasks, the better !
It was quite difficult tk add the new Task for the fish tank so that is why I realised it needs to change.

**Comment by bevans2000** [comment]
Here is the output of the analysis I have done on influencers for each MetaTask. I am proposing to create some JobGroups, e.g. Scientists, to make life easier to define preferred Jobs.
[tasks.ods](https://github.com/mars-sim/mars-sim/files/6548875/tasks.ods)

**Comment by bevans2000** [comment]
Planned changes done
