### ISSUE TITLE
Subclass logic in superclasses

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#298]
**Describe the bug/issue**
There are areas where the superclasses, e.g. Unit, have logic that is specific to only subclasses. An example is Unitmanager.getAbot that related solely to Settlement objects.. This reduces the separation and increases the dependency between packages/classes.

**Proposal**
Move some methods to the appropriate location.

**Comment by bevans2000** [comment]
Coming back to the cohesion discussion. If the ultimate goal is to change how the simulation model is stored (either RDBMS or JSON) then the class structure needs refinement in my opinion. This would help reduce the dependency between the various packages and reduce the model footprint.

The Unit class and it's subclasses contain instanceof calls for the subclasses in methods like getVehicle or getSettlement. These methods can make it tricky to follow what is happening and debugging. Also good desing is that baseclasses should not know about subclasses.

I think that some of the common basic methods need to utilise the Containment hierarchy instead of using instanceof.For example the getSettlement method is implement in different Units with different logic, but Unit.getSettlement could just can container.getSettlement. The method would be overriden in Settlemetn returning this and Vehicle that looks at where it is parked. Essentially make better use of the containment concept.

Robot should move to subclassed from Unit; it would still be Salvagable.

**Comment by mokun** [comment]
Agreed. Whatever refinement you see fit.

> The Unit class and it's subclasses contain instanceof calls for the subclasses in methods like getVehicle or getSettlement. 

Can you give us a real example to illustrate that ?

> If the ultimate goal is to change how the simulation model is stored (either RDBMS or JSON) 

Yes we can aim for having both eventually.

**Comment by bevans2000** [comment]
It seems that the following areas can be simplified and pushed to the Unit Class:

- Identifier - This can be handled solely by the Unit class. Every Unit should have a unique ID.
- Name: All Units have a name property but some subclasses "hide" the name with their own private field, e.g. Settlement. Unit can be responsible for name.
- equals/hashcode - As Units can only be created via the Factory OR serialisation the identifier can be trusted as a fallback. Therefore equals/hashcode can be the responsibility of the Unit class.

**Comment by mokun** [comment]
@bevans2000 ,

When it comes to location state definition (thus relating to identifier), can you take a look at @Urwumpe's comment on https://github.com/mars-sim/mars-sim/issues/134#issuecomment-753241536 since he talks about different tree implementation ?

@Urwumpe , are you still working on that ?

**Comment by mokun** [comment]
Already removed most if not all subclass logics in classes like Unit and Airlock.
