### ISSUE TITLE
Mixed use of Unit & UnitIdentifier

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#299]
**Describe the bug/issue**
Some classes use Unit Identifier to maintain references. This requires the appropriate Unit object to be lookuped in the UnitManager to apply logic. This will be consuming some element of processing time and memory. ScientificStudy is an example of this approach.

**Proposal**
Using references directly to the Unit will provide a consistent approach without the need for extra lookups hopefully increasing efficiency.

**Comment by bevans2000** [comment]
The method `Unit.equals` is using the Unit name & baseMass in the equals logic. If the `identifier` is the same; then the objects are the same.

**Comment by bevans2000** [comment]
Airlock maintains it's own lookup map of id -> Person.  This could be simplified if it used Person directly.

**Comment by mokun** [comment]
> Airlock maintains it's own lookup map of id -> Person. This could be simplified if it used Person directly.

When I was debugging the walking bug and how and why an person can get trapped inside an airlock, it dawns on me that the object references could be the issue. 

So I went ahead to have each airlock creates its own map to keep track of who might be inside the airlock and who might be waiting to get in.

The lookup is also faster since the map entries will be extremely small. We only allow 4 persons waiting at outside the inner and outer door and 1 person inside each chamber of an airlock.

**Comment by bevans2000** [comment]
What are the thoughts on creating a dedicated `UnitIdentfier` class instead of using an Integer? This class would be a composite key composed of the UnitType & an integer identifier. The benefit would be to speed up lookup logic in `Unitmanager.getUnitByID` which is called many times. This method could use the unit type property to optimise the lookup.

**Comment by mokun** [comment]
> What are the thoughts on creating a dedicated `UnitIdentfier` class instead of using an Integer? This class would be a composite key composed of the UnitType & an integer identifier. The benefit would be to speed up lookup logic in `Unitmanager.getUnitByID` which is called many times. 

True that we can bypass the use of `UnitManager` and go with `UnitIdentfier` if it speeds things up.

But how will it affect our future plan of we *transfer* a person from, say, a simulation that runs in machine A to a simulation that runs in machine B ?

**Comment by bevans2000** [comment]
Well it actually would help because the `UnitIdentifier` could eventually hold a property identifying the controlling server. Each Unit would then have an "Owner" responsible for updates and applying time.

**Comment by bevans2000** [comment]
Duplicate of #355
