### ISSUE TITLE
Set SHA-256 keys as SHA-1 have shown to have collison 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#30]
See http://www.pcworld.com/article/3174676/security/sha-1-collision-can-break-svn-code-repositories.html and

https://www.theregister.co.uk/2017/02/23/google_first_sha1_collision/

you will probably need a way to retire old keys and have the new keys.

**Comment by mokun** [comment]
Can you show me how ?

**Comment by mokun** [comment]
@shirishag75 ,

I came across this article this morning at https://lwn.net/SubscriberLink/811068/cfeb6a67b8dfbe47/

After you back up the master branch, feel free to experiment with converting our repo to SHA-256 keys.

**Comment by shirishag75** [comment]
I dunno if you read the whole article, it would mean retooling git itself. I would rather talk with the debian git maintainer and see if it on their roadmap, if it is, then probably will do it. and report back. Thank you for sharing the link as well.
