### ISSUE TITLE
Potential deadlock in threads

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#309]
**Describe the bug/issue**
 - There is a rare edge case where a Thread deadlock situation can occur. The deadlock occurs when one of the SettlementTasks invoke an Event listener attached to the UI. If the listener updates a UI component that is blocked because of a concurrent update they can get stuck on Monitors.
 
**Affected Area**
 - Not all UI components have the problem.

**Expected behaviors**
 - The simulation Threads should be isolated from the clients. There should be a centralised dispatcher class that invokes the listeners on behalf of the Simulation objects via a dedicated ThreadExecutors pool. This would need some standardisation o fthe Listener interfaces.

**Reproduction (optional)**
 - I'm not sure how easy this is to reproduce. But it does highlight the risk with the Simulator objects directly updating UI components.

**Comment by mokun** [comment]
@bevans2000 ,

I'm referencing [this](https://github.com/mars-sim/mars-sim/issues/287) here.

Do you mean it happens all of a sudden, without doing anything ?

Any screen print or stack trace ? 

Do you mean that it happens, especially when a player moves the slider bar to increase the time ratio, etc. and the time param in the *Time Tool* starts to get weird ?

When I slide the bar all the way to the right to max out the time ratio (TR), I sometimes have negative sleep value in ms and so forth.

**Comment by bevans2000** [comment]
Negative sleep means the pulse is taking longer than the prediction so it overruns and consumes the sleep time. Essentially negative time means the simulation is struggling to meet the target time ratio with  the desired accuracy.. Currently the logic tries to adjust to meet the ratio by running pulses than cover a larger elapsed time. In  this model the time ratio is the target not the number of FPS. 
Pulses do not take a constant time to process so the logic has to adjust. I think having anything hard coded will be difficult with the difference  combinations of simulation and machine spec.

**Comment by bevans2000** [comment]
@mokun  Whilst looking at this I think there is a big problem in the UI concerning listeners. Most of the UI windows are being notified of changes even when they are not visible. This means the simulation is dispatching 1000's of events even when there is nothing on show. This is a performance load. Changing the delivery to async which is what this issue is addressing just doesn't work because the event queue is a 100+.

We need to address how the UI Windows are registering for events event when not displayed. Clearly we should be creating UI windows unless they are needed and that would significantly reduce the problem. I think this has been discussed in a previous topic. The UnitWindow and unregistered when they close now.

However the bigger question is to the listeners serve much purpose anyway? Most UI windows are not updated from the Clock via a periodic update. So we should adopt one approach or the other; clearly doing a periodic update is much simpler and just refresh what is visible.

Secondly the ```UnitManagerListener``` is redundant; the existing ```UnitListener``` can serve the same purpose.

**Comment by bevans2000** [comment]
Ok, let's have a look soon. For example I noticed last night that a Robot object have 8 listeners but not one UI wiindow was open. That seems wrong

**Comment by bevans2000** [comment]
After the recent changes to the management of listeners in the Monitor Tool the potential benefit of this change is less. Hence I want to postpone it for now

**Comment by mokun** [comment]
I still see negative sleep from time to time when I increase the time ratio beyond 2048x.

What can be done ?

**Comment by bevans2000** [comment]
Not much but it is nothing to do with this issue. It's more to do with the irracrratic behaviour of the Mars clock, #933

**Comment by mokun** [comment]
When you said the erratic behavior of Mars clock, do you mean the sudden change of length of the execution time ?

**Comment by bevans2000** [comment]
Yes the actual TR never matches the desired TR.

**Comment by bevans2000** [comment]
Actually I have just merged the master into my feature branch and am now also seeing a lot of negative sleep count. The new Task logic on master has a problem and is consuming more processing power. I think it relates to the problem with unexcitable pending tasks. Seems the TaskManager is spending a lot of time trying to execute Pending Tasks that cannot be started.

**Comment by mokun** [comment]
First, we know time ratio represents the real-world compression ratio of a real second on Earth to a virtual second on mars-sim.

> Yes the actual TR never matches the desired TR.

But I thought this simply demonstrates MasterClock's *superior* ability to adapt to how much execution time is needed, thus it adjusts accordingly to allows more or less time to run threads. 

As a result, the ideal and actual time ratio aren't always the same.

So I would argue that the actual time ratio doesn't need to be 100% the same as the ideal time ratio.

**Comment by mokun** [comment]
I can see below that the *actual* time ratio NEVER comes close to catching up the the *desired* time ratio.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/c5157990-3b63-460b-8fcf-ae1ce6aa0ef9)

I suppose that's what you meant that we need to make MasterClock intelligent enough to make that adjustment.

**Comment by mokun** [comment]
Actually, sometimes the *actual* time ratio is greater than *target* time ratio, right after I hit + to increase the time ratio. So it's not bad that it later auto adjust to match it.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/3779308d-76c0-418d-a1c8-b69dce4cfbb0)

**Comment by bevans2000** [comment]
Yes that is what I meant. 
Anyway I want to close this issue as we no longer need it and have another issue for clock discussions
