### ISSUE TITLE
MalfunctionFactory & Parts separation

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#313]
**Describe the bug/issue**
The `MalfunctionFactory` is responsible for calculating the reliability and recording failures of `Part` types. This requires the manager to maintain 2 Hashmaps keyed on Part.id. There are also methods to calculate the reliability of Parts every Sol.
This is increasing the coupling between different classes.

**Expected behaviors**
Add the concept of Failure & Reliability directly on the `Part` class.  This involve moving some methods from the manager.
This would allow the HashMaps to be removed to reduce the simulation model and help with serialisation (either object or future JSON).

**Comment by mokun** [comment]
@bevans2000 ,

Currently, the repair of a malfunction is a little finicky. 

There are 3 types of repair (general, emergency and EVA).

See the malfunction wiki at https://github.com/mars-sim/mars-sim/wiki/Malfunctions

When there's a malfunction in a building, it will look for a chief repairer and an assistant repairer. 

But the process is still broken and more than these two persons will show up and flood the scene. 

The task of repairing also seems getting interrupted midway. The probability has to be recomputed and the task keeps "blinking" in the Settlers Tab in `Monitor Tool`.

So far, Repairbots are supposed to show up and do repair and behaves better than human.

**Comment by mokun** [comment]
We have various discussions related to modeling malfunction in this thread [here](https://github.com/mars-sim/mars-sim/issues/194)

**Comment by bevans2000** [comment]
The discussion is interesting with good ideas. Initially I would like to refactor the Parts & `MalfunctionFactory` so `Part` class manages it own MTBF.
I think also the `Malfunction` class would benefit from being split into 2. At the moment it contains properties that define the problem and properties that relate to fixing the problem. The `MalfunctionConfig` should just return the definition of a problem. The `MalfunctionManager` should just instantiate a new Malfunction when it is triggered.
This would help later on having different approaches to fixing problems which could be different subclasses. How about creating a new class `MalfunctionType` that is generated from the XML via `MalfunctionConfig`. The new `Malfunction` would hold a reference to the shared type (or definition). Having a separate `MalfunctionType` will allow us to grow it into more complex descriptions.
I've realised that in the Console rework the Expert mode has got lost so I will re-instate that first but adding the ability to create a Malfunction in any `Malfunctionable`, e.g. Building, Vehicle or Robot.

**Comment by mokun** [comment]
> I think also the `Malfunction` class would benefit from being split into 2. At the moment it contains properties that define the problem and properties that relate to fixing the problem. 

So, 


> The `MalfunctionConfig` should just return the definition of a problem. The `MalfunctionManager` should just instantiate a new Malfunction when it is triggered.

Do we want to treat the MBTF & reliability statistics GLOBAL in nature ? 

In terms of recording malfunction events, we still have one GLOBAL `HistoricalEventManager` for doing the job, instead of having each settlement keeping track of their own malfunction events.

I suppose that for now, we treat all "EVA Suit" having the same quality, as if they are manufactured from the same factory.

In future, we should keep track of where they were made, since the MBTF and reliability would be conceivably different.

**Comment by bevans2000** [comment]
I think global per Part is fine for now. I have found 2 problems so far in working with Malfunctions:

1. Any malfunction is added twice to the `MalfunctionManager`. Don't know why yet but I'm going to rework the code then revisit it. There are some near duplicate methods that can be consolidated.
2. If you create a malfunction in a vehicle that needs an EVA then there is a ClassCastException in Airlock.isZone. The object is a VehicleAirlock but it is cast to a BuildingAirlock. Clearly the code has an unsafe cast but I have no idea why the vehicle airlock has no zone logic.
