### ISSUE TITLE
ScientificStudyManager thread safe issue

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#314]
**Describe the bug**
There is a rare case when the simulation is run with a high number of Simulation threads that a ConcurrentModification exception is thrown. There is a Person getting their collaborative studies in one thread and a different thread is creating a new Scientific Study. They both access the global `studies` List; one write and the other reads. 

**To Reproduce**
Need to run the simulation on high number of cores and it is quite random.

**Expected behavior**
The problem is the global `studies` list should not be used to find Person related attributes. It should be owned by the Person object reducing the need to scan the global list looking for matches.  This would be better design and follow the principle of scoping changes to the Settlement giving a better separation.

**Comment by Urwumpe** [comment]
I have a plan to create a simulated product lifecycle management system for each settlement as settlement service - could this, especially the document management system aspect, maybe help there to reduce the simultaneous accesses to certain information artifacts?

**Comment by mokun** [comment]
> The problem is the global `studies` list should not be used to find Person related attributes. It should be owned by the Person object reducing the need to scan the global list looking for matches. 

I did notice a lot of `ConcurrentModification` exceptions as soon as we start to create a separate thread for each settlement. 

When a person performs a task, at the end, it will see if he is skillful enough to avoid accidents and it will add skill experience points to that individual. Sometimes `ConcurrentModification` exceptions will happen as a result.

**Comment by bevans2000** [comment]
As expected, we just need to chase these down and convert them I to a Settlement based objects instead of global variables. This one should be easy to fix, I will have a look later this week.

**Comment by Urwumpe** [comment]
Since MSP is by heritage an agent simulation, we should maybe put the focus on letting the agents decide things locally, instead of using too many global variables and thus global decision processes. The agents should just learn how to get important "global" data into the "working memory" of each to be used by actions, and how to write back the results of such actions into a "global" datastore again.

I put "global" into quotation marks since its interplanetary actually, and by implementation, it seems to go towards settlements as scope for such data.

**Comment by bevans2000** [comment]
Yes I agree that's a good approach. For "agents" we can read any Unit. The global manager classes should be to provide a consolidated view. I have done this with ScientificStudy with the agent being the lead researcher. In #313 there is an idea to do the same for Parts to control their own MTBF and reliability.
