### ISSUE TITLE
Create a separate FishFarm Function

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#320]
**Is your feature request related to a problem? Please describe.**
Move the fish farming and bee keeping to separate Building Functions. This allows a new Building of FishFarm to be created and bees to be used in only the bigger greenhouses. 
Also this will allow the creation of new Tasks to replenish the fish and honey stocks.

**Comment by bevans2000** [comment]
As part of this work I think I've uncovered a mistake in the logic concerning `ResourceProcess`. The ResourceProcess instances are created in `BuildingConfig` and shared for the same the Building Type. The `ResourceProcessing` function class then retrieves the ResourceProcess objects according to the parent Building Type and then owners them. However if another Buliding of the same type is created; it will also use the same `ResourceProcess` instances.  This means that they both update the same set of `ResourceProcess` during the time pulse and Task work creating chaos. 
To resolve this I am going to split out the configuration properties into a new `ResourceProcessSpec` which can be shared and is immutable. The `ResourceProcess` objects will be created  and owned by the individual `ResourceProcessing` objects.

**Comment by mokun** [comment]
Link this to its [discussion](https://github.com/mars-sim/mars-sim/discussions/319)

**Comment by mokun** [comment]
> As part of this work I think I've uncovered a mistake in the logic concerning `ResourceProcess`. The ResourceProcess instances are created in `BuildingConfig` and shared for the same the Building Type. The `ResourceProcessing` function class then retrieves the ResourceProcess objects according to the parent Building Type and then owners them. However if another Buliding of the same type is created; it will also use the same `ResourceProcess` instances. This means that they both update the same set of `ResourceProcess` during the time pulse and Task work creating chaos.

Great that you caught this. 

I'm also wondering why the cpu utility spiked up since we started implementing the settlement partition in concurrent threads. Any particular reasons ?

> To resolve this I am going to split out the configuration properties into a new `ResourceProcessSpec` which can be shared and is immutable. The `ResourceProcess` objects will be created and owned by the individual `ResourceProcessing` objects.

Question, if we one day implement the object database for storing values, would we still be using these  `Inventory`-related class ?

**Comment by bevans2000** [comment]
So I've found a potentially even bigger problem but I'm not sure. The `Building` class is serialised in a simulation save but none of the `Function` objects are; they are only reference via a transient List. This means each time a simulation is reloaded the Functions are recreated, for example `Farming` will pick a new random set of `Crops`. Any state that is held in teh Function objects or their child objects is lost when a simulation is saved & reloaded.
Is this correct?

**Comment by mokun** [comment]
> So I've found a potentially even bigger problem but I'm not sure. The `Building` class is serialised in a simulation save but none of the `Function` objects are; they are only reference via a transient List. This means each time a simulation is reloaded the Functions are recreated, for example `Farming` will pick a new random set of `Crops`. Any state that is held in teh Function objects or their child objects is lost when a simulation is saved & reloaded.
> Is this correct? 

True that building functions aren't serialized. 

I wonder how it would affect the greenhouse crops since I thought the crops are serialized

**Comment by bevans2000** [comment]
I have done a couple of tests and the Crops are different after a reload. If the Crops are not referenced by a serialised object they will  not be saved. Moreover, the Farming class is rebuilt in the Building. 
On face value this is easy to fix by removing the transient from the functions property in the Building class. However this might cause problems on the reload due to the very complex reference graph. The main culprit is the large number of Collections to Person objects. The way to fix this could be to create our own PersonSet class that implements lazy loading. It stores unit identifiers when it is serialised but exposes the Person object at runtime. This pattern could be applied to all Units Collections over time. 
Nevertheless, this needs a separate issue if we are to solve it.... but I think we need to.

**Comment by mokun** [comment]
> I have done a couple of tests and the Crops are different after a reload. If the Crops are not referenced by a serialised object they will not be saved. Moreover, the Farming class is rebuilt in the Building.

I've wanted to make the `Building` objects smaller by not serializing the `Function`. The list of `Function`(s) is the same for each type of `Building`.

> On face value this is easy to fix by removing the transient from the functions property in the Building class. However this might cause problems on the reload due to the very complex reference graph. 

But I probably fail to account for how greenhouse and other functions do have persistent objects that need to be serialized. 

> The main culprit is the large number of Collections to Person objects. The way to fix this could be to create our own PersonSet class that implements lazy loading. It stores unit identifiers when it is serialised but exposes the Person object at runtime. This pattern could be applied to all Units Collections over time.

So, how or in what fashion do we organize what to be serialized ?

Java serialization has some built-in ability to simplify the serialization graph but we better not rely on it too much, since we are moving toward the JSON serialization.

From the perspective of each settlement, what minimal things does it want to be serialized through the simulation ?

From the perspective of each person, what minimal things does it want to be serialized through the simulation ?

I have wanted to work toward saving each person as a personID, and each settlement as a settlementID but haven't fully considered many factors involved. 

I suppose in future it makes sense to have flexibility in "transferring" out a person from one simulation to the other.

**Comment by bevans2000** [comment]
Functions and the objects they reference have state so they need to be saved.
Saving just the Person identifiers makes sense because it will slightly reduce the save size but the big benefit is it reduces the object references when reloading. We can hold Person collections in a dedicated new class allowing a Person reference to be held in  memory but only serialised the ids.

**Comment by mokun** [comment]
Great that you added `TendFishTank` and [TendFishTankMeta](https://github.com/mars-sim/mars-sim/commit/832f5a9ea4c10cf7f31c1971d4b68d1738ca47f2#diff-9e007cf0ab3d509a550bbe74b22073bd55eb535ad2fcacd7750ec0cf8756ccf4).

Now the Biologists/botanists have new tasks to do.

Btw, the [TendGreenhouse](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/task/TendGreenhouse.java) has issues with TaskPhase switching. It switches too fast and doesn't stay in one TaskPhase for a good duration of time.

I envision TaskPhase as just one type of minor tasks within a major task and there can be a number of minor tasks to choose from.

So, say you give me 15 millisols for `TendGreenhouse`, I may only be able to do one minor task and I choose "inspecting" in the first round.

Next time when I come back, I'll do "cleaning".

**Comment by bevans2000** [comment]
Yes the task needs some tuning. Also any fish caught are not added to the inventory yet

**Comment by mokun** [comment]
> Yes the task needs some tuning. Also any fish caught are not added to the inventory yet

@bevans2000 ,

Can you commit all the changes made so far ? 

Even though it's not 100% complete, it's better for me to start from the latest copy of mars-sim you have.

There are few things in other areas I'd like to change.

**Comment by bevans2000** [comment]
I'm pretty happy with this last commit. I have reworked the `BuildingConfig` to consolidated the numerous common attributes. This has removed a lot of duplicate code.  I will merge the changes on the branch now and then tidy up any snags.

**Comment by bevans2000** [comment]
I should have said. I haven't got the Unit Test working yet because they use a non-existent Building Type which breaks everything in the walking tests. This should be easy to fix tomorrow by making `MockBuilding` a real configured type. Also each test has  the same initialisation code so it should be using a `@Setup` method.

**Comment by mokun** [comment]
@bevans2000 , 

By the way, we may as well update our wiki on [Food Production](https://github.com/mars-sim/mars-sim/wiki/Food-Production) as we are working on getting the fishery and beehive to work.

**Comment by bevans2000** [comment]
Sure good point

**Comment by mokun** [comment]
Right now, by default we give New Pompeii a fish farm.

I was thinking of making fish farm initially available to a Japan Aerospace Exploration Agency (JAXA)'s settlement because they would love to make sushi out of the fish :D 

![image](https://user-images.githubusercontent.com/1168584/110638587-96ff6f00-8163-11eb-8f96-8934096970a6.png)

Also, see the red box in the pic above, the Tank Size should be 10000 but right next to it, there's an artifact that looks like a "|" symbol.

Q: If we allow players to tweak things in a fishery, what do you see fit that can be adjusted ? 

I know at some point in future, we would for sure have different species of fish for the player to experiment with. 

If that's the case, we may as well now think of beneficial changes to our UI that will be more intuitive and for players to change parameters in a fishery, just like in a game or in a simulation application.

**Comment by bevans2000** [comment]
> Also, see the red box in the pic above, the Tank Size should be 10000 but right next to it, there's an artifact that looks like a "|" symbol.

Hahaha. It is actually an 'l' meaning litres. Just doesn't come out very well. I'll change it to the work 'litres' to make it clearer. 

The actual number needs some adjusting. 10K was an initial guess; 10K litres would occupy a tank that is 10m2 which is probably smaller that the dedicated Fish Farm building could hold. But they can not be too high; they need a large surface area.
Also there is a ratio of 1 fish per 10 litres as the initial startup which is just a guess. This has to actually be based on the size of fish and surface area. This would give a maximum stock level so the initial starting stock should be 80% to allow some growth.

**Comment by Urwumpe** [comment]
> 
> 
> > Also, see the red box in the pic above, the Tank Size should be 10000 but right next to it, there's an artifact that looks like a "|" symbol.
> 
> Hahaha. It is actually an 'l' meaning litres. Just doesn't come out very well. I'll change it to the work 'litres' to make it clearer.
> 
> The actual number needs some adjusting. 10K was an initial guess; 10K litres would occupy a tank that is 10m2 which is probably smaller that the dedicated Fish Farm building could hold. But they can not be too high; they need a large surface area.
> Also there is a ratio of 1 fish per 10 litres as the initial startup which is just a guess. This has to actually be based on the size of fish and surface area. This would give a maximum stock level so the initial starting stock should be 80% to allow some growth.

Well, 10 cubic meters is a lot of water, if it has to be produced on Mars or be transported from Earth. If the aquaponics start with shrimp, even far less water could be enough for a small sustainable production.

**Comment by Urwumpe** [comment]
Yeah, though I think it COULD work out with vertical farming and a really huge greenhouse - and maybe a more resourceful species of bees. Sure nothing that can be constructed easily. Especially on Mars.

**Comment by mokun** [comment]
@bevans2000 , 

Can we have the algae farm ? 

Do you see that it can be modeled similarly as fish farm ?

**Comment by mokun** [comment]
we could have either algae ponds, on growing algae in rows and columns of bags

**Comment by bevans2000** [comment]
I don't see why it couldn't be modelled in a similiar fashion. It could just be a Function applied to a Building.

**Comment by mokun** [comment]
> I don't see why it couldn't be modelled in a similiar fashion. It could just be a Function applied to a Building.

Sure. does it warrant a brand new building function ? or reuse the old farming function ?

**Comment by mokun** [comment]
@bevans2000 , btw, can you add the version tag info with your name to all the new class files you have created in the last few months ? I've helped adding that back in some but not all.

**Comment by bevans2000** [comment]
Sure

**Comment by bevans2000** [comment]
> > I don't see why it couldn't be modelled in a similiar fashion. It could just be a Function applied to a Building.
> 
> Sure. does it warrant a brand new building function ? or reuse the old farming function ?

I like the idea if a new Fubction because it gives us flexibility to apply it any building, maybe a new dedicated one or existing buildings as isolation bags.

**Comment by mokun** [comment]
Even though there's 146 fish, it sounds unreasonable to have given much (namely, 869 kg) weed inside the tank.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/58c7d6c7-282f-4225-95f9-e9b3396e88f3)

**Comment by mokun** [comment]
Btw, I'm committing my algae pond in a moment.
