### ISSUE TITLE
Can't compile mars-sim.core: "jcommander-1.75.jar; invalid manifest format" and test code in production code

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#326]
**Describe the bug**
When compiling the project with a OpenJDK 11 release using Maven, the compilation fails because one dependency has a small glitch in the manifest (The lines are duplicated). Possible that other JDKs ignore the duplicates, I used the Amazon distribution there in this case.

The jcommander dependency is only used for running old AI test code. Such tests should first of all have taken place in a feature branch, not on master. Additionally such kind of test applications would be better suited in a separate acceptance test subproject, not in the production code or the unit tests.

**To Reproduce**
Checkout into a new workspace from master. Run "Maven install" on the root project.

**Expected behavior**
No problems during compilations, except minor warnings related to small differences in JDK behaviour.

No test application code in production code for a library. The AI test should either go into a new branch or be deleted completely if done. Additionally it makes more sense to be part of an acceptance test suite, like it is implemented right now.

For fixing the dependency to jcommander itself, an update to the recent version fixes it. But it shouldn't have been in mars-sim.core in first place.

**Desktop (please complete the following information):**
- Windows 10
- Amazon Corretto JDK 11
- IntelliJ IDEA Community 2021.1

**Comment by mokun** [comment]
> But it shouldn't have been in mars-sim-core in first place.

Yea we could use jcommander for more streamlining the processing of command-line input switches in future.

But for now, we don't need it and have just commented it out.

**Comment by mokun** [comment]
@Urwumpe,
My bad. jcommander is still needed for some kotlin class files during maven compile. Can't get rid of that yet.

**Comment by Urwumpe** [comment]
Yeah, but as I said, it seems to be just test code for some AI improvements, nothing critical. I just didn't want to rule over your code, but would it have been my code, I would have erased it and just kept a backup for returning to the idea later. 

A much better solution for such tests would be an application package of its own, so that the mars-sim.core world is a pure library.
