### ISSUE TITLE
Day Dreaming outside on the surface of Mars

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#330]
**Describe the bug/issue**
Can't walk and not motivated to go back in, even when hungry and thirsty

**Affected Area**
 - ExitAirlock, Ice Prospecting Mission, EVAOperation, Walking, etc.

**Expected behaviors**
 - When done with collecting ice, go inside.
 - If hungry and thirsty, go inside to eat and drink

**Actual/Observed Behaviors**
 - Seems getting stuck doing Day Dreaming only outside on the surface of Mars while being hungry and thirsty.
 
**Reproduction (optional)**
 - Looking at the Schedule Tab in a person's window, it's found on Sol 5 that the person made an EVA egress due to an Ice Prospecting Mission
 - At 362 msol, the person is still doing the EVA egress. The last Phase of the activity was "Walk to the Chamber". After that, at 392 msol, the task of "Day Dreaming" and the phase of "Doing Nothing" took over. 

**Screenshots**
 - See Person Window, Monitor Tool, Settlement Map below 

**Specifications  (please complete the following information):**
 - OS version : Windows 10
 - Java version :  openjdk 16
 - mars-sim build version : Build 5631
 
![image](https://user-images.githubusercontent.com/1168584/116831347-8831a900-ab63-11eb-88d9-64c2047a3ad6.png)

**Comment by bevans2000** [comment]
The DayDreaming Task is the default and has the lowest priority so can always be execute; basically it suggest something has gone wrong. If they are outside then cooking a meal will not be an Task option.

**Comment by bevans2000** [comment]
I think the EVA Operation in the performMappedPhase method has to check the health of the person and if unfit then force them to go back inside. The EVAOperation is the correct place for the check; then it will get applied to all EVA tasks. All EVA Task should use a common Phase for coming back inside.

Something like

```
   if (!person.isFit() && person.isOutside())
  {
      setPhase(RETURN_INSIDE); // Or whatever the constant phase is to return inside
  }
```

**Comment by mokun** [comment]
This scenario show it's Ushi Cheng is still "Day Dreaming" while being outside. She's also sick.

The other 3 outside are loading the rover but appear frozen in place and sick with high fatigue/thirst/hunger.

![image](https://user-images.githubusercontent.com/1168584/117072931-12097f80-ace6-11eb-84c4-18f04b258344.png)

**Comment by mokun** [comment]
@bevans2000 

May be we need an EVADayDream as the base level if a person is outside (or default to WalkOutside or something).

**Comment by mokun** [comment]
@bevans2000 

How do you reactivate a person up from Day Dreaming ? 

May be we can add an expert command in the console to reawake him for testing purpose ?!

**Comment by bevans2000** [comment]
Day Dreaming is just a short task; so if new Tasks become available the Person will take them on. Go to expert mode in the console and try the `work` command. It will show you the Task Porbability map for a Person.

**Comment by bevans2000** [comment]
I think this is resolved. There may still be some problems with EVA but this is not the root cause.
