### ISSUE TITLE
The person who assists researcher is sick (hungry and thirsty), stuck when exploring site / collecting resource in vehicular airlock  

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#333]
**Describe the bug/issue**
 - The person cannot quit assisting researcher so that he may properly eat/drink/sleep.
 
**Affected Area**
 - The task `AssistScientificStudyResearcher` shows up in *Monitor Tool* and the *Activity Tab* in *Person Window*. However, the task is NOT reported in *Schedule Tab* in *Person Window*. 

**Expected behaviors**
 - The person should end the task so that he can eat/drink/sleep.
 - The *Science Tool* should show the assigned study number as a column.
 - The *Science Tool* should show who is assisting which researcher.  
 
**Specifications  (please complete the following information):**
 - mars-sim build version : 5647

**Comment by mokun** [comment]
@bevans2000 

Recently, I notice that a person sometimes cannot end a task. 

I haven't seen a lot of them assisting researchers or proposing/compiling scientific study without any thoughts of going to sleep or eat/drink.

Since then I've tried adding if (!person.isFit()) or if (person.computeFitnessLevel()) to see if a person has high fatigue/hunger, etc. But somehow they don't always work.

This issue would have dated back to at least before build 5648.

Can you check to see if the duration of a task is still being checked or not ?

![image](https://user-images.githubusercontent.com/1168584/118565119-7553d280-b726-11eb-801b-ae343ef9d3e4.png)

**Comment by bevans2000** [comment]
Sure. Is the problem just with study proposals and assisted research?

**Comment by mokun** [comment]
> Sure. Is the problem just with study proposals and assisted research?

Also, exploring site and mining site and others.

**Comment by mokun** [comment]
> Sure. Is the problem just with study proposals and assisted research?

Somehow it doesn't happen all the time consistently. But when it happens, that person was locked in for that task.

**Comment by bevans2000** [comment]
> Also, exploring site and mining site and others.

Previously I had also seen this but it was due to the Vehicle Airlock problem.

**Comment by mokun** [comment]
> Previously I had also seen this but it was due to the Vehicle Airlock problem.

Ok. Then we're basically working on the separation of concern as we speak

**Comment by bevans2000** [comment]
Also I think we need to review the `endTask` methods to make sure they all tidy up correctly.

**Comment by mokun** [comment]
> Also I think we need to review the `endTask` methods to make sure they all tidy up correctly.

Yes I think so. There's a lot of `endTask` all throughout those Walk* class. 

I notice if I remove calling the `endTask` in  one or two places,  the person would freeze and has walking issues.

**Comment by mokun** [comment]
Now that we have methods for checking a person's fitness during those scientific study phases or exploring site and collecting resources phases, we no longer have the issue of not being able to stop and take a break.

Close this now.
