### ISSUE TITLE
Not capturing tasks in TaskSchedule

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#337]
**Describe the bug/issue**
 - Not all tasks are being captured by TaskSchedule.
 - Schedule Tab in Person Window fail to show some of the tasks that a person did in the past. e.g. a person did exercising but it did not get reported in the Schedule Tab.
- A tasks is NOT shown until after it is compled. It used to be shown in the Schedule Tab as soon as it was recorded in the past.

**Affected Area**
 - TaskSchedule 
 
**Expected behaviors**
 - With the exception of walking related tasks, each task must be captured.
  
**Reproduction (optional)**
 
**Specifications  (please complete the following information):**
  - mars-sim build version : 5665

It also threw IndexOutOfBoundsException in the Stack Trace : 

```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: -2, Size: 1
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.mars_sim.msp.core.UnitManager.runExecutor(UnitManager.java:2270)
	at org.mars_sim.msp.core.UnitManager.timePassing(UnitManager.java:2217)
	at org.mars_sim.msp.core.Simulation.clockPulse(Simulation.java:1797)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:672)
	at org.mars_sim.msp.core.time.MasterClock$ClockListenerTask.call(MasterClock.java:648)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IndexOutOfBoundsException: Index: -2, Size: 1
	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
	at java.base/java.util.LinkedList.get(LinkedList.java:480)
	at org.mars_sim.msp.core.data.DataLogger.getSolData(DataLogger.java:109)
	at org.mars_sim.msp.core.data.DataLogger.getYesterdayData(DataLogger.java:132)
	at org.mars_sim.msp.core.person.ai.task.utils.TaskSchedule.timePassing(TaskSchedule.java:322)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:974)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1474)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:2954)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:2936)
	... 4 more
```

**Comment by mokun** [comment]
Alice did a lot of things but somehow wasn't captured between 514 and 1000 msols.

We also need to fix the timestamp. At 1000, this person was doing EVA ingress, waiting and requesting to come in but, it said 000 msol. 

That's because 1000 msol is the same as 0 msol, numerically speaking.

But it would be too confusing. 

For schedule display, we should reserve 0 msol as the beginning of the sol. And at the end of the sol is 1000 msol. 

![image](https://user-images.githubusercontent.com/1168584/117744128-eb9f8480-b1bc-11eb-89d4-9d1e6e257c3d.png)

**Comment by mokun** [comment]
> Assign this to me. I've been working in Tasks so am famliar with the area.

Sure.

Q: how would you show the main task and the subtask in one row ?

Say, Alice wants to go to the observatory to propose an astronomy study and do some research.

So she had an EVA egress to get to that building.

Now it's a very good thing to show the EVA egress and what specific phase she's at for debugging purpose.

But, currently the Schedule Tab won't show her "true" intention of doing an EVA.

On the other hand, we don't want the EVA egress be hidden under the Proposing Astronomy Study.

So, we really NEED to see BOTH !

**Comment by mokun** [comment]
Also, it bugs me that it won't show her "current task". 

Can we change it back to recording the task name when it FIRST get started, rather than when it's done ?

**Comment by bevans2000** [comment]
I have made good progress on this issue. I have decided to move the logic of recording Tasks into the `TaskManager` from `TaskSchedule`. This fits better with the logic needed to identify subtasks. The `Task.setPhase` method is the new trigger for recording a Task since it gives a better recording of the activity.
The final point to resolve, is how to identify SubTasks since the setPhase method is called from the constructor before the Task is attached to a parent; hence it an eventual SubTask looks like a top level Task until it is attached to a parent.
The question is should we record SubTasks at all?
Currently the schedule is used to report how long a Person is in an Airlock by iterating the activities. This is flawed because Airlock Task would always be a subtask. In the short term the ability to report time in an airlock should be dropped and maybe revisited later on.  Dropping would make the code base cleaner and easier to maintain; removing the need to rely on the Task name to identify airlock activities.
Lastly after some analysis using a cache for the String properties of the `OneActivity` class actually uses more memory space than referencing the Strings directly. This is because the vast majority of the Strings are already shared because they are only create once, e.g TaskPhase or static Task name.

**Comment by mokun** [comment]
> The final point to resolve, is how to identify SubTasks since the setPhase method is called from the constructor before the Task is attached to a parent; hence it an eventual SubTask looks like a top level Task until it is attached to a parent.

How about we add an entry of subtask to each main task ?

It makes sense to show the subtask for every main task, especially those main tasks that need the sub tasks that require to complete.

Say, a person wants to load a vehicle, he would need to do a few things such as checking and retrieving the available resources. After that he may need to do a EVA egress to the vehicle to drop them off. 

So, in this case :
1. at 50 msols
- main task : Loading a vehicle. 
- sub task : retrieve resources

2. at 80 msols
- main task : loading a vehicle
- sub task : EVA egress 

3. at 100 msols
- main task : loading a vehicle
- sub task : drop off resources at vehicle.

Note : within the main task, there can be more than one phase such as: 
Main task
- phase 1 : remotely checking the status of a vehicle
- phase 2 : remotely command the vehicle to come into the garage or to position its at a specific spot

@Urwumpe , do you have examples of main tasks that depend on other tasks ?

**Comment by bevans2000** [comment]
The reality is that I have not found a top level Task that has anything other Walk sub tasks. The next level down is Airlock takes which generate a massive number of entries; I thin, too many. This is not a log, it is just a record of activities they have performed.
I have an idea to only capturing the start of an Airlock task, not the individual phase changes.

**Comment by mokun** [comment]
> It goes all the way from 000 msol to 009 msol.

There are twin tasks like this, namely two tasks are appearing one after another alternately. They both occurs at the same millisol.

**Comment by bevans2000** [comment]
Related to #888
