### ISSUE TITLE
Modeling of Airlock State and Airlock Operator's responsibility, Vehicular Airlock, Console UI freeze

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#340]
Q1: how best should we model and design the airlock operation ?

Currently, there are 4 possible airlock states operationally speaking,

| # | State | 
| --- | ---| 
|1.| De-pressurized |
|2.| De-pressurizing |
|3.| Pressurizing |
|4.| Pressurized |

The person who is in charge of when the airlock is supposed to be in what state is the *airlock operator*.

Since he's in charge, what he wants to do (namely, EVA egress or ingress) would directly affect the airlock's state.

So if he's doing EVA egress, since he's taking the lead, the airlock will have to be pressurized before he walks in.

After he has donned on the EVA suit, the airlock will need to be depressurized in such a way that he can step out onto the surface of Mars.

Right now, as of build 5678, we use the following code snippet to signify that someone is interesting in *activating* the airlock, as seen in the `requestEgress()` in `ExitAirlock`

```
			if (!airlock.isActivated()) {
				// Only the airlock operator may activate the airlock
				airlock.setActivated(true);
			}
```

Then we have `Airlock`'s `timePassing()` below to check if an airlock operator has been elected : 
```
	/**
	 * Time passing for airlock. Check for unusual situations and deal with them.
	 * Called from the unit owning the airlock.
	 * 
	 * @param time amount of time (in millisols)
	 */
	public void timePassing(double time) {
		
		if (activated) {
			
			if (!occupantIDs.isEmpty() || !awaitingInnerDoor.isEmpty() || !awaitingOuterDoor.isEmpty()) {
				// Create a new set of candidates
				checkOperatorPool();
				
				if (!operatorPool.contains(operatorID) || operatorID.equals(Integer.valueOf(-1))) {					
					// If no operator has been elected
					electAnOperator();
				}
				else if (!occupantIDs.isEmpty() && !occupantIDs.contains(operatorID)) {
					// Need to give the preference to those inside the chamber
					electAnOperator();
				}
			}
		}
	}
```

Note that the `activate` must be true in order to proceed with checking if the operator exist and elect someone if no one is the operator.

Let's the last EVA team has just left the airlock and so the airlock has been depressurized. 

Next, toward the end of the `requestEgress()` in `ExitAirlock`, we want to see this person has been elected as the operator and if he is, he has a job to do.

```
		if (!airlock.isActivated()) {
			// Only the airlock operator may activate the airlock
			airlock.setActivated(true);
		}
				
		if (airlock.isOperator(id)) {
					
			logger.log(person, Level.FINE, 4_000, "Ready to pressurize the chamber.");
					
			if (!airlock.isPressurized() || !airlock.isPressurizing()) {
				// Get ready for pressurization
				setPhase(PRESSURIZE_CHAMBER);
			}
		}

```

So the operator will call setPhase(PRESSURIZE_CHAMBER) to go to the next TaskPhase in the next cycle

In `pressurizeChamber()` method in ExitAirlock, he will proceed with the pressurization.

Note that other team members who are with him in the airlock will NOT need to go to PRESSURIZE_CHAMBER TaskPhase.

They will wait in the REQUEST_EGRESS TaskPhase. 

When the chamber has bee pressurized and ready, they will step into the ENTER_AIRLOCK TaskPhase directly.

```
	if (airlock.isPressurized() && !airlock.isInnerDoorLocked()) {
		// If airlock has already been ressurized,
		// then it's ready for entry
				
		logger.log(person, Level.INFO, 4_000,
		"Chamber already pressurized for entry in " 
		+ airlock.getEntity().toString() + ".");

		// Skip PRESSURIZE_CHAMBER phase and go to the ENTER_AIRLOCK phase
		setPhase(ENTER_AIRLOCK);
	}
```

Q2 : Is there a better architecture we may adopt that require much less branching condition. It can quickly get out of hand as since we may not have considered all situations.

**Comment by bevans2000** [comment]
My opinion is the `Airlock` should control advancing the time in the pressuring/depressuring phase. The Operator should just trigger the start of the process; advancing the time once started should not be done via a Task but by the Airlock itself.
Secondly `VehicleAirlock` will still generate a ClassCastException; when the Task code works correctly. They seem to be too different at the moment.

**Comment by mokun** [comment]
> My opinion is the `Airlock` should control advancing the time in the pressuring/depressuring phase. 

Yes. The change of the airlock state in `Airlock` class. The time It's through calling goToNextState() method by the airlock operator only and not anyone.

Also, the count down of the `remainingCycleTime` is being tracked in `Airlock`
```
	/** Amount of remaining time for the airlock cycle. (in millisols) */
	private double remainingCycleTime;

```
> The Operator should just trigger the start of the process; advancing the time once started should not be done via a Task but by the Airlock itself.

Right, the airlock operator is the lead here. When he pushes the button, an airlock will comply with the command to pressurize or depressurize.

**Comment by mokun** [comment]
> Secondly `VehicleAirlock` will still generate a ClassCastException; when the Task code works correctly. They seem to be too different at the moment.

Can you cut and paste what you see in the stack trace here ?  I haven't run into this exception yet.

**Comment by bevans2000** [comment]
> 
> Can you cut and paste what you see in the stack trace here ? I haven't run into this exception yet.

Easy to reproduce using the Console

1.  Connect to a Vehicle Parked at a Settlement
2. Create a malfunction; Communication System Failure is a good one.
3. Workers try to repair by entering the Vehicle Airlock but the logic casts the Airlock to the BuildingAirlock. Example of problem code is
```
	/**
	 * Gets a collection of occupants' ids
	 * 
	 * @return
	 */
	public List<Integer> getAllInsideOccupants() {
		return ((BuildingAirlock)this).getAllInsideOccupants();
	}
```
This pattern occurs in numerous places. Here is the Stack Trace.
```
00-Adir-01:184.903 (Info) EnterAirlock [x3] : [0.00° N 0.00° W] Anne Peeters - Requested EVA ingress in Sun Dancer.
java.lang.ClassCastException: class org.mars_sim.msp.core.vehicle.VehicleAirlock cannot be cast to class org.mars_sim.msp.core.structure.building.function.BuildingAirlock (org.mars_sim.msp.core.vehicle.VehicleAirlock and org.mars_sim.msp.core.structure.building.function.BuildingAirlock are in unnamed module of loader 'app')
	at org.mars_sim.msp.core.structure.Airlock.getAllInsideOccupants(Airlock.java:1167)
	at org.mars_sim.msp.core.structure.Airlock.noEVASuit(Airlock.java:1191)
	at org.mars_sim.msp.core.person.ai.task.EnterAirlock.depressurizeChamber(EnterAirlock.java:385)
	at org.mars_sim.msp.core.person.ai.task.EnterAirlock.performMappedPhase(EnterAirlock.java:123)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:617)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:568)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:554)
	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:554)
	at org.mars_sim.msp.core.person.ai.task.utils.TaskManager.executeTask(TaskManager.java:530)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:222)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:136)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:977)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1474)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:2954)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mokun** [comment]
> java.lang.ClassCastException: class org.mars_sim.msp.core.vehicle.VehicleAirlock cannot be cast to class org.mars_sim.msp.core.structure.building.function.BuildingAirlock 

oic. Fixing this now.

**Comment by mokun** [comment]
> > Can you cut and paste what you see in the stack trace here ? I haven't run into this exception yet.
> 
> Easy to reproduce using the Console
> 
> 1. Connect to a Vehicle Parked at a Settlement
> 2. Create a malfunction; Communication System Failure is a good one.
> 3. Workers try to repair by entering the Vehicle Airlock but the logic casts the Airlock to the BuildingAirlock. Example of problem code is
> 
> ```
> 	/**
> 	 * Gets a collection of occupants' ids
> 	 * 
> 	 * @return
> 	 */
> 	public List<Integer> getAllInsideOccupants() {
> 		return ((BuildingAirlock)this).getAllInsideOccupants();
> 	}
> ```
> 
> This pattern occurs in numerous places. Here is the Stack Trace.
> 
> ```
> 00-Adir-01:184.903 (Info) EnterAirlock [x3] : [0.00° N 0.00° W] Anne Peeters - Requested EVA ingress in Sun Dancer.
> java.lang.ClassCastException: class org.mars_sim.msp.core.vehicle.VehicleAirlock cannot be cast to class org.mars_sim.msp.core.structure.building.function.BuildingAirlock (org.mars_sim.msp.core.vehicle.VehicleAirlock and org.mars_sim.msp.core.structure.building.function.BuildingAirlock are in unnamed module of loader 'app')
> 	at org.mars_sim.msp.core.structure.Airlock.getAllInsideOccupants(Airlock.java:1167)
> 	at org.mars_sim.msp.core.structure.Airlock.noEVASuit(Airlock.java:1191)
> 	at org.mars_sim.msp.core.person.ai.task.EnterAirlock.depressurizeChamber(EnterAirlock.java:385)
> 	at org.mars_sim.msp.core.person.ai.task.EnterAirlock.performMappedPhase(EnterAirlock.java:123)
> 	at org.mars_sim.msp.core.person.ai.task.utils.Task.executeMappedPhase(Task.java:617)
> 	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:568)
> 	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:554)
> 	at org.mars_sim.msp.core.person.ai.task.utils.Task.performTask(Task.java:554)
> 	at org.mars_sim.msp.core.person.ai.task.utils.TaskManager.executeTask(TaskManager.java:530)
> 	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:222)
> 	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:136)
> 	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:977)
> 	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1474)
> 	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:2954)
> 	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```

when I type in, say, "/c Mercury", the console output nothing and frozen. Can you check ?

**Comment by mokun** [comment]
@bevans2000 
> Connect to a Vehicle Parked at a Settlement

so when I type in, say, "/c Mercury", the console output nothing and frozen. Can you check ?

**Comment by bevans2000** [comment]
> @bevans2000
> 
> > Connect to a Vehicle Parked at a Settlement
> 
> so when I type in, say, "/c Mercury", the console output nothing and frozen. Can you check ?

I have noticed something similiar. If you use the Console when the UI is constructing it freezes. I think it  just be a conflict on the AWT Event thread. I will have a look.
Wait until the UI is fully built and try.
