### ISSUE TITLE
Isolated buildings (Astronomy Observatory)

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#346]
**Feature Request**
- How is a person supposed to get services in isolated buildings such as Astronomy Observatory ?

**Describe what you like to see**
- A person may go to the observatory for the purpose of watching the night sky or proposing an astronomy study.
- A person may sleep there
- A person may eat there
- A person may study *Astronomy* and possibly other scientific subjects
- In case of emergency, a person may turn on the beacon to signify the need for rescue

**Describe what you don't like to see**
- A person should NOT do an EVA just to go to the observatory when the same service is available in the connected area of the settlement.
- A person should NOT get stranded in the EVA airlock
- A person should be able to remotely connect with others. 
- A person can go back to the connected area of the settlement when the overall task of observing the night sky is over.

**Questions to ponder**
- How do you define and programmatically tell that a building is being isolated from the rest of the settlement ?
- Should we make use of tunnels to connect underground between the main settlement and the isolated buildings such as the observatory ?

**Comment by mokun** [comment]
@bevans2000 

Have you seen anyone stranded in the observatory lately ?

**Comment by bevans2000** [comment]
No. Let's close this. We need to clean up some of the older issues anyway

**Comment by mokun** [comment]
See https://github.com/mars-sim/mars-sim/issues/1084#issuecomment-1799532421.

**Comment by mokun** [comment]
> How do you define and programmatically tell that a building is being isolated from the rest of the settlement ?

We're working on zoning in [here](https://github.com/mars-sim/mars-sim/issues/720).
