### ISSUE TITLE
No one is digging regolith/ice, No regolith found in Regolith Prospecting

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#347]
**Describe the bug**
- The DigLocalRegolith and DigLocalIce task cannot be started
- No regolith is collected in Regolith Prospecting mission

**Expected behavior**
- The settlement generates a demand for regolith and ice. This value is fed into the DigLocalRegolithMeta where the probability for selecting this task is calculated. The higher the demand, the higher the probability.

**Desktop (please complete the following information):**
 - Build 5717

**Screenshot**
![image](https://user-images.githubusercontent.com/1168584/119088128-0643db80-b9bd-11eb-97ed-36de5efa0cfa.png)

**Comment by bevans2000** [comment]
I think your problem is in the `EVAOperation.noEVAProblem method`.
```
		EVASuit suit = person.getSuit();//(EVASuit) person.getInventory().findUnitOfClass(EVASuit.class);
		if (suit == null) {
//			LogConsolidated.log(logger, Level.WARNING, 5000, sourceName, 
//					"[" + person.getLocale() + "] " + person.getName() + " ended " 
//							+ person.getTaskDescription() + " : no EVA suit is available.");
			return false;
		}
```
It return false (being there is a problem) when they have no suit. But this is called in the constructor of DigLocalRegloith before the person has started the EVA so hence they don't have a suit. I would suggest the noEVAProblem should not be called until the EVA has started, i.e. not in the constructor.
Also it should be called `isEVAProblem` since the current name is a double negative.

**Comment by mokun** [comment]
> I think your problem is in the `EVAOperation.noEVAProblem method`.

I see. Thanks for nailing it down. Fixing it now.

**Comment by mokun** [comment]
Resolved. Close this now

**Comment by mokun** [comment]
@bevans2000 

I just caught this BIG mistake in returning a random double : 

![image](https://user-images.githubusercontent.com/1168584/128991075-f53c7e00-1bc4-4405-83a7-c1caf21d4af0.png)

Guess I added this method, not knowing it can return a negative number. Just fixed it in this [commit](https://github.com/mars-sim/mars-sim/commit/1136925aff404011885d2783c25dd9adb0ca4a5a).

**Comment by bevans2000** [comment]
There are a few  cases where we call random twice and take one value from the other. SonarQube warns about these. I guess these can be replaced with a single random call. More efficient.

**Comment by mokun** [comment]
After the commit above, the Mission Tool is able to display the amount of each of 4 types of regolith being collected: 
![image](https://user-images.githubusercontent.com/1168584/143991947-c93c00d6-99ad-4e0e-9abf-16ef5ac55457.png)

**Comment by bevans2000** [comment]
> After the commit above, the Mission Tool is able to display the amount of each of 4 types of regolith being collected: ![image](https://user-images.githubusercontent.com/1168584/143991947-c93c00d6-99ad-4e0e-9abf-16ef5ac55457.png)

Nice

**Comment by mokun** [comment]
Related to https://github.com/mars-sim/mars-sim/issues/234
