### ISSUE TITLE
Cannot store previous demand Good Value, lightweight Inventory

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#348]
**Describe the bug**
- The calculated demand VP is never being cached properly. 

**Expected behavior**
- The calculated demand VP should be cached. The next demand calculation will depend on the previous demand. 

**Affected Methods/Classes**
- determineAmountResourceGoodValue() in GoodsManager, populateGoods() in GoodsUtil

**Desktop (please complete the following information):**
 - build 5721

**Additional context**

In `GoodsUtil`, why are we having brand new newList and newMap ?

```
	/**
	 * Populates the goods list with all goods.
	 */
	private static synchronized void populateGoods() {
		if (goodsList != null) {
			// Another thread has created the lists
			return;
		}
		
		// Only updated here so don't need to be thread safe
		List<Good> newList = new ArrayList<>();
		Map<Integer, Good> newMap = new HashMap<>();
		
		// Populate amount resources.
		populateAmountResources(newList, newMap);

		// Populate item resources.
		populateItemResources(newList, newMap);

		// Populate equipment.
		populateEquipment(newList, newMap);

		// Populate vehicles.
		populateVehicles(newList, newMap);

		// Sort goods by name.
		Collections.sort(newList);
		
		// Do now assign to the static until fully populated to avoid race condition ith other Threads accessing
		// the values as they are populated
		goodsList = newList;
		goodsMap = newMap;	
	}
```

**Comment by mokun** [comment]
@bevans2000 

In build 5721, I've tried printing out the supply and demand calculation of Regolith in the settlement. 

The amount resource demand value (namely, prevDemand) is always zero as follows.

```
1. Schiaparelli Point's regolith   prevDemand: 0.0   projDemand: 0.0   lsDemand: 1.0   tradeDemand: 0.0   totDemand: 1.0   totSupply: 0.0
2. Schiaparelli Point's regolith   prevDemand: 0.0   totDemand: 0.1   totSupply: 0.01   value: 10.0
```

**Comment by mokun** [comment]
@bevans2000 


Within determineAmountResourceGoodValue() in GoodsManager,

```
		// Save the goods demand
		goodsDemandCache.put(resourceGood, totalAmountDemand);
		
		amountValue = totalAmountDemand / totalAmountSupply;
```

totalAmountDemand is supposed to be stored into the map but it never does.

**Comment by mokun** [comment]
@bevans2000 ,

I did some changes to `GoodsManager` and `GoodsUtil` in an attempt to fix the supply and demand of *Regolith*.

Before, the *value* of Regolith is *1.0* at the start of the sim. 

It should have been higher, since most of manufacturing are based on things derived from the regolith.

![image](https://user-images.githubusercontent.com/1168584/119232667-e60a3e80-bada-11eb-82c0-fed41daa6b93.png)

Now, the *value* of regolith shows up higher.

![image](https://user-images.githubusercontent.com/1168584/119232762-45684e80-badb-11eb-8298-56fc30e9cefe.png)

Will still need to tweak its *price* to make it reasonable to trade.

**Comment by mokun** [comment]
@bevans2000 

For now, I modified populateGoods() in GoodsUtil as follows. 

It's probably ugly and still not optimized. Feel free to improve whatever area you see fit.

```
	/**
	 * Populates the goods list with all goods.
	 */
	private static synchronized void populateGoods() {
		if (goodsMap != null) {
			// Another thread has created the lists
			return;
		}

		Map<Integer, Good> newMap = new HashMap<>();
		
		// Populate amount resources.
		newMap = populateAmountResources(newMap);
		// Populate item resources.
		newMap = populateItemResources(newMap);
		// Populate equipment.
		newMap = populateEquipment(newMap);

		// Populate vehicles.
		newMap = populateVehicles(newMap);

		goodsMap = newMap;
	}
```

**Comment by bevans2000** [comment]
To be honest the `Inventory` class and the demand calculations are something I know little about. When I was looking at the memory analysis previously the `Inventory` objects consumed a lot of space. Every Unit get the same type of inventory but I am not sure this is optimal. For example, Building always delegates to the Settlement. Does a Bag need the same level of functionality as a Settlements Inventory.

**Comment by mokun** [comment]
> Does a Bag need the same level of functionality as a Settlements Inventory.

Yes it's true that the `Container` class doesn't serve a whole lot of purpose, other than holding gas, food, regolith, ice, minerals, etc. 

So, can we convert the Bag, Large Barge, Gas Canister, Barrel, Specimen Box, etc. to a better and more efficient architecture for storing resources ?

**Comment by mokun** [comment]
> Every Unit get the same type of inventory but I am not sure this is optimal.

@bevans2000 ,

@Urwumpe made a point about the use of flywheel pattern for these containers on this [post](
https://github.com/mars-sim/mars-sim/issues/132#issuecomment-439026998).

**Comment by bevans2000** [comment]
Yeap Flyweight pattern is always good. We use it now in the Malfunction area where the Malfunction config are shared across all the Malfunction instances.
One way to look at this is the Equipment object are good at being Units; it makes them easier to control. But the Unit class has become quite large but Equipment are generally small because there are a lot of them. I think we need 2 implementation of `Inventory`:

1. A lightweight one for Equipment that simply records what is stored. This would also only exist IF the Equipment has to store something; hence reducing the memory footprint. Maybe also Robot & Person.
2. A heavyweight Inventory that record what is held plus what the demand is, this would be the current Inventory and would be applicable to Settlements & Vehicles.. It would be created permanently when the Unit is created.

This means that the large numbers of Equipment would not consume too much resources. Also one driver would be to reduce the size of Unit and only hold properties relevant to ALL Units.

**Comment by bevans2000** [comment]
Is this assigned to me to look at ` Inventory` ? I should have some spare time later in the week.

**Comment by mokun** [comment]
> Is this assigned to me to look at ` Inventory` ? I should have some spare time later in the week.

Yes. Please do whatever needed to simplify/optimize Inventory as discussed !

**Comment by bevans2000** [comment]
Ok. I think a good step would be to identify which Units can be assigned to an `Inventory`, e.g. those that can move, Person, Robot, Equipment. It is not logical to assign a `Settlement` to an Inventory BUT it could be possible. Therefore I think we should create a new Unit subclass to represent Units that can move to complement the `Structure` class, i.e. `MobileUnit`. This would also in the future allow us to tidy up the handling of Location State & Coordinates.
This would allow us to have a specialised Inventory that supports the transfer of `MobileUnit` objects used for Settlements. But we can have a cut down Inventory that just hold Resources, i.e. most Equipment. 
I might re-parent `Robot` as well to a MobileUnit as disccused in #302 .

**Comment by bevans2000** [comment]
The other thing is the Inventory itself. It is a very complex class; way too complex. There are some big question about what role it plays:
# There are 2 ways to reference resources; either an int or an AmountResource which means there are duplicate methods all over the place. We should have a single way to reference resources throughout the code base. Clearly the `AmountResource` class would make sense as it has some attributes, e.g. name. This is a large problem for maintainability.
# Only the `GoodManager` via Settlement is using the demand aspects of the Inventory. Makes sense that we record the demand on resources at a settlement level. Settlement Inventory is essentially the root inventory.
# Equipment Inventories only store Resources; Equipment don't store other Units as they are at the bottom of the food chain.
# Inventory is responsible for updating the Coordinates of all the contained Units....... If a Unit is contained within a parent then it should inherit that Coordinate and only use it's own Coordinate when it is on the MarsSurface. This would be impacting on performance.

**Comment by mokun** [comment]
> It is not logical to assign a `Settlement` to an Inventory BUT it could be possible.

Let's add Mars, Moon, Earth as an Unit of some sorts now, rather than later. 

This would give us the provision in near future to send human or cargo between these planetary bodies easily.

**Comment by mokun** [comment]
> 4\. If a Unit is contained within a parent then it should inherit that Coordinate and only use it's own Coordinate when it is on the MarsSurface.

Yes `MarsSurface` can be a misnower. I know it's not logically possible to define the coordinates of a `MarsSurface`, unlike a `Settlement` or any other units that has a set of coordinates in x and y (or phi and theta)

But at some point in future, we may divide the surface of Mars into zones. In one thread, @Urwumpe talked about North and South hemisphere, etc.. 

It would be handy if mars-sim grows to the point of becoming distributed and running in multiple machines. 

I'm evening thinking `MarsSurface` (or rather `Mars`), `Phobos`, `Eros` or `Moon`, or `Earth` should be some kind of super top containers that has a special space coordinates or something that define their position in mars-sim.

**Comment by mokun** [comment]
> 1. There are 2 ways to reference resources; either an int or an AmountResource which means there are duplicate methods all over the place. We should have a single way to reference resources throughout the code base. Clearly the `AmountResource` class would make sense as it has some attributes, e.g. name. This is a large problem for maintainability.

Yes. Back in version 3.08, there were methods based on `AmountResource` or `ItemResource` only. Also, no demand/supply calculation until later.

I've wanted to add the use of integer identifiers, instead of the object references, to track both `AmountResource` or `ItemResource`, so that they become portable across simulation sessions after serialization.

But it turns out at a few level down, it does need the object instances of `AmountResource` or `ItemResource`...

Anyway, should we switch to a simple sql database to save use from a lot of future development troubles ?

**Comment by bevans2000** [comment]
Basically it's a nightmare. I've had 2 attempts to rework it but it is so intertwined. Why are the ItemResources & AmountResources kept separate? I don't want to say re-write it but it might need a rethink along these lines:

1. Just store any type of Resource in a single "store". 
2. Do not use integer as keys as magic numbers is a very bad anti-pattern.
3. Supply & Demand calculations are done automatically when resources are added or removed.
4. Stop throwing exceptions if there is not enough resources. The retrieve methods return the amount of resources available 

It is not an easy or quick job. It will need to be done on a branch to not affect the master stability.

**Comment by bevans2000** [comment]
Or of course we do nothing.

**Comment by mokun** [comment]
> Why are the ItemResources & AmountResources kept separate? 
> 1. Just store any type of Resource in a single "store".

May be they wanted to optimize ItemResources & AmountResources separately ?!

> 2. Do not use integer as keys as magic numbers is a very bad anti-pattern.

Oh. How do you handle mismatch of object references after serialization ?

> 3. Supply & Demand calculations are done automatically when resources are added or removed.

Yes Inventory class saves the supply & demand info on each storage and retrieval of a resource.

But there's no need of calculating the supply & demand on a resource in each transaction. 

It doesn't need it until GoodsManager needs to calculate the VP and price of a resource.  

This saves some CPU cycles.

> 4. Stop throwing exceptions if there is not enough resources. The retrieve methods return the amount of resources available

That's true ! 

The UI or the console or the log terminal should give some hints to tell the player that it's running out of something.
 
> It is not an easy or quick job. It will need to be done on a branch to not affect the master stability.

It's a lot of work I must say.

**Comment by mokun** [comment]
@bevans2000 ,

Can you create a new command for displaying the vp and the price of goods in a settlement in the console ? 

also compare the price/vp across a number of settlements ? 

In future, we may be able to create some sort of *cost of living* metrics in each settlement for comparison purposes.

**Comment by bevans2000** [comment]
> @bevans2000 ,
> 
> Can you create a new command for displaying the vp and the price of goods in a settlement in the console ?
What do you mean by vp? Is it GoodValue? How does this differ from price?

**Comment by mokun** [comment]
> What do you mean by vp? Is it GoodValue? How does this differ from price?

Value Point (VP) is how valuable a resource is.

> How does this differ from price?

Price is very different from value point.

e.g. Regolith is very very valuable. But it's price is low.

e.g. VP for regolith is 5000. But price is $.02 per kg.

e.g. VP for Explorer Rover is 3000. Price is $5000 per item.

**Comment by bevans2000** [comment]
Ok, I'll have a look. Potential for a lot of values so might need th ability to filter the Good to reduce the amount of numbers to display

**Comment by bevans2000** [comment]
I think this should drop the 3.1.2 milestone. I looked into this and  it is a big piece of work but with big performance and memory benefits.

**Comment by mokun** [comment]
> I feel we should stop holding active Units (Vehicle, Person, Robot) in the Inventory class; only store Equipment which are passive. The active Units manage their container and also their containers (Settlement & Vehicle) maintain a list of the contained Units already. So having them held in Inventory is a duplication.

So, if we do it right, it should look like a tree node structure with parent node and child nodes.

We can make each child having only one direct parent node at a time. but of course that parent node itself can have a parent node above it.

If we organize this tree it this way, then there won't be any duplication ?!

**Comment by bevans2000** [comment]
Yes that's what I think. The problem is what to do with Equipment. As they are a Unit they have a true parent. But that parent could be a Person and that doesn't support list of owned Equipment directly. Nevertheless I think Inventory should just hold non-units like Parts and Resources.

**Comment by bevans2000** [comment]
First step is to isolate the storing of Units. Most Inventory instance belong to Equipment who only hold Resources so they can have a simpler/smaller Inventory object. Settlements, Vehicles, Robots & Person can hold other Units so they need the full Inventory. I think this leaves 2 classes:

- Inventory - Holds just resources
- UnitInventory - subclassed from Inventory but includes the ability to store Units.
Might have to consider #302 as well

**Comment by mokun** [comment]
Should EVASuit hold a person ? It used to be. Now it only hold resources.

**Comment by bevans2000** [comment]
Ohh interesting theoretical question....
So my take is EVAsuit is an Equipment so it is owned by other higher level Units. A Person uses an Equipment. The Person is contained by the Mars surface

**Comment by mokun** [comment]
@bevans2000 

I'm still trying to figure out why this [commit](https://github.com/mars-sim/mars-sim/commit/48bde658595f891c947f1731db6176736d3133c9) is causing the MainWindow to fail to show up. 

In this commit, a container no longer has an instance of Inventory. I'm hoping this would save a lot of needless operation for equipment/container class. 

Anyway, I have been hunting down anything that said *container.getInventory()* because from now on, it will return null. This is probably why some panels have to do with getting an instance of a container's inventory would fail to load in MainWindow.

How would you detect where it fails to load ?

**Comment by mokun** [comment]
We don't have a console command for showing a list of equipment/container and its content yet. 

I can see we do have */i* that shows the amount and item resources.

Can we have one for equipment ?

```
MuskVille >  ​/h
Sorry I didn't understand you. Here is what I know about

Control Keys :
 * tab - Auto completes the input; for commands (long & short) and arguments
 * up - Goes back in the history
 * down - Goes forward in the history

Console Commands (* <short command> <long command>)
Group : Common
 * /xp expert              * /-  intro
 * /?  help                * /rt repeat

Group : Settlement
 * /ai airlocks            * /mn mission now
 * /b  bed                 * /mr mission radius
 * /bu building            * /o  objective
 * /cy country             * /pe people
 * /cr crop                * /pr processes
 * /d  dashboard           * /re research
 * /i  inventory           * /rs resource
 * /jd job demand          * /rb robots
 * /jp job prospect        * /rl role
 * /jr job roster          * /sc science
 * /lv level               * /so social
 * /l  location            * /ss study
 * /ml malfunction         * /t  task
 * /mf manufacture         * /v  vehicles
 * /me meals               * /w  weather

Group : Simulation
 * /#  bye                 * /ms mission summary
 * /c  connect             * /p  pause
 * /d  date                * /sv save
 * /di distance            * /se settlements
 * /ev events              * /sp speed
 * /lo log                 * /st stop
 * /mp mission plan
```

**Comment by mokun** [comment]
Now I do see that in InventoryCommand, you combined the 3 types together into one as shown below.

Can we have 3 separate commands instead ? 

For container, as you know, we can't use getInventory() anymore since the resource and quantity that's being stored in the container's class. 

But EVA Suit is a different animal. It's still an equipment but it does have an Inventory instance to keep track of various resources inside. 

If you like the current approach for storing a resource, we can extend that to the EVASuit as well for multiple resources ?!

Do feel free to tweak it in whatever ways are better.



```java
	/** 
	 * @return 
	 */
	@Override
	protected boolean execute(Conversation context, String input, Unit source) {

		Inventory inv = source.getInventory();
		
		StructuredResponse buffer = new StructuredResponse();
		String capacity = "Limitless";
		String available = "All";
		if (inv.getGeneralCapacity() < Double.MAX_VALUE) {
			capacity = String.format(CommandHelper.KG_FORMAT, inv.getGeneralCapacity());
			available = String.format(CommandHelper.KG_FORMAT, inv.getRemainingGeneralCapacity(false));
					
		}
		buffer.appendLabeledString("Capacity", capacity);
		buffer.appendLabeledString("Available", available);
	
		Map<String,String> entries = new TreeMap<>();
		Collection<Equipment> equipment = inv.findAllEquipment();
		if (input != null) {
			// Filter according to input
			equipment = equipment.stream().filter(i -> i.getType().toLowerCase().contains(input)).collect(Collectors.toList());
		}
		// Counts Equipment type but exclude Robot; Hack until Robots are correctly subclasses
		Map<String, Long> eqCounts = equipment.stream()
									.filter(e -> !(e instanceof Robot))
									.collect(Collectors.groupingBy(Equipment::getType, Collectors.counting()));
		for (Entry<String, Long> eq : eqCounts.entrySet()) {
			entries.put(eq.getKey().toLowerCase(), eq.getValue().toString());
		}
		
		// Add Items
		Set<ItemResource> itemResources = inv.getAllIRStored();
		if (input != null) {
			// Filter according to input
			itemResources = itemResources.stream().filter(i -> i.getName().contains(input)).collect(Collectors.toSet());
		}
		for (ItemResource ir : itemResources) {
			String name = ir.getName();
			int amount = inv.getItemResourceNum(ir);
			if (amount > 0) {
				entries.put(name, "" + amount);
			}
		}
		
		// Add Resources
		Set<AmountResource> amountResources = inv.getAllAmountResourcesStored(false);
		if (input != null) {
			// Filter according to input
			amountResources = amountResources.stream().filter(a -> a.getName().contains(input)).collect(Collectors.toSet());
		}
		for (AmountResource ar : amountResources) {
			String name = ar.getName();
			double amount = inv.getAmountResourceStored(ar, false);
			if (amount > 0) {
				entries.put(name, "" + String.format(CommandHelper.KG_FORMAT, amount));
			}
		}

		buffer.appendTableHeading("Item", 30, "Amount", 10);
		for (Entry<String, String> row : entries.entrySet()) {
			buffer.appendTableRow(row.getKey(), row.getValue());
		}
		context.println(buffer.getOutput());
		return true;
	}
```

**Comment by bevans2000** [comment]
So you want one for Equipment, Resources & parts?
I'm away for a few days this week so will revisit it next week.

**Comment by mokun** [comment]
> So you want one for Equipment, Resources & parts?

Mixing them together is kinda hard to read, right ?

**Comment by bevans2000** [comment]
> @bevans2000
> 
> I'm still trying to figure out why this [commit](https://github.com/mars-sim/mars-sim/commit/48bde658595f891c947f1731db6176736d3133c9) is causing the MainWindow to fail to show up.
> 
> In this commit, a container no longer has an instance of Inventory. I'm hoping this would save a lot of needless operation for equipment/container class.
> 
> Anyway, I have been hunting down anything that said _container.getInventory()_ because from now on, it will return null. This is probably why some panels have to do with getting an instance of a container's inventory would fail to load in MainWindow.
> 
> How would you detect where it fails to load ?

I would run it in debug mode and put a breakpoint on Exception throw. This will find the root cause however there is some bad code in places where exceptions are the expected norm so you may have to wade through a few. You could try refining the breakpoint to just NPE.

**Comment by mokun** [comment]
> I would run it in debug mode and put a breakpoint on Exception throw. This will find the root cause however there is some bad code in places where exceptions are the expected norm so you may have to wade through a few. You could try refining the breakpoint to just NPE.

It turns out it's just the same old multiple monitor setup issue with [UIConfig](https://github.com/mars-sim/mars-sim/issues/414)  that has been plaguing us.

**Comment by mokun** [comment]
We've been using the lightweight Inventory for Equipment objects. Closing this for now.
