### ISSUE TITLE
Cannot leave a vehicle parked in the garage after the mission is over

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#349]
**Describe the bug**
- Aimar is stuck inside a rover parked in a garage. The mission was over and the vehicle came back and everything got unloaded successfully, with the exception that Aimar was still inside. The other member Mia didn't get stuck.

**Expected behavior**
A mission is over. The vehicle came back and got all the stuff unloaded. The members should get off the vehicle as well and be free to do whatever.

**Screenshots**
Aimar has multiple issues as follows : 
1. He was day dreaming
2. He was stuck inside the vehicle in a garage and cannot move

![image](https://user-images.githubusercontent.com/1168584/119248037-30bfa100-bb43-11eb-8991-63494ad0fcdd.png)

3. His hunger was off chart
4. After sol 9, no sleep hours has been recorded, after loading from the saved sim the 2nd time on sol 10
5. At sol 12, his thirst was at 4000 msol
6. In the Task schedule tab, There is no record of tasks performed prior to sol 8. The activities from sol 1 to sol 7 were not found (is it because after loading from the saved sim ?)

![image](https://user-images.githubusercontent.com/1168584/119248104-c9eeb780-bb43-11eb-8fd8-867d22367aa3.png)

7. Aimar has no problem with his fatigue as it is only ~255 msol. The activity of `Sleeping` does show up in the schedule.
8. However, other than `Sleeping`, Aimar could not perform any other tasks, other than `Day Dreaming`.

![image](https://user-images.githubusercontent.com/1168584/119248609-2acbbf00-bb47-11eb-9475-bb74b706e3d4.png)

9. The Spirit II rover shows having one crew member (namely Aimar) still inside. But the crew member's name and activity is NOT shown inside the member table.
10. Aimar is shown in Location Tab of the Person Window to be inside  "Garage 1 in SPIRIT II".

![image](https://user-images.githubusercontent.com/1168584/119248907-3e782500-bb49-11eb-882c-93485a3c0bb2.png)

**Desktop**
 - Build 5727

**Comment by mokun** [comment]
Note: it was last reloaded on sol 10 as follows : 

```
2021-05-22T20:42:36.2 (Config) SimulationConfig : Done loading all xml files.
2021-05-22T20:42:36.2 (Config) SimulationConfig : Please go to the mars-sim console's Main Menu to choose an option.
2021-05-22T20:42:36.2 (Config) Simulation : Initiating the simulation core engine...
2021-05-22T20:42:36.2 (Config) MasterClock : -----------------------------------------------------
2021-05-22T20:42:36.2 (Config) MasterClock :          User defined time-ratio : 128.0x
2021-05-22T20:42:36.2 (Config) MasterClock :               Min msol per pulse : 0.02
2021-05-22T20:42:36.2 (Config) MasterClock :               Max msol per pulse : 2.0
2021-05-22T20:42:36.2 (Config) MasterClock :  Max elapsed time between pulses : 1000ms
2021-05-22T20:42:36.2 (Config) MasterClock :                    Accuracy bias : 0.5
2021-05-22T20:42:36.2 (Config) MasterClock : -----------------------------------------------------
00-Adir-01:000.000 (Config) Simulation : The file to be loaded is C:\Users\mkhelios\.mars-sim\saved\default.sim
00-Adir-01:000.000 (Config) Simulation : Loading and processing the saved sim. Please wait...
00-Adir-01:000.000 (Config) EVASuit :  EVA suit's unloaded weight : 20.3 kg
00-Adir-01:000.000 (Config) EVASuit :       Total gas tank volume : 3.9L
00-Adir-01:000.000 (Config) EVASuit :                Full Tank O2 : 66.62 kPa -> 1.0    kg - The Maximum tank pressure
00-Adir-01:000.000 (Config) EVASuit :                  Nomimal O2 : 17.0  kPa -> 0.2552 kg - The suit target pressure
00-Adir-01:000.000 (Config) EVASuit :                  Minimum O2 : 11.94 kPa -> 0.1792 kg - The safety limit
00-Adir-01:000.000 (Config) Simulation :  --------------------------------------------------------------------
00-Adir-01:000.000 (Config) Simulation :                    Info on The Saved Simulation                      
00-Adir-01:000.000 (Config) Simulation :  --------------------------------------------------------------------
00-Adir-01:000.000 (Config) Simulation :                    Filename : default.sim
00-Adir-01:000.000 (Config) Simulation :                        Path : C:\Users\mkhelios\.mars-sim\saved\
00-Adir-01:000.000 (Config) Simulation :                        Size : 4.88 MB
00-Adir-01:000.000 (Config) Simulation :               Made in Build : 5726
00-Adir-01:000.000 (Config) Simulation :   Current Core Engine Build : 5727
00-Adir-01:000.000 (Config) Simulation :     Martian Date/Time Stamp : 00-Adir-10:326.505
00-Adir-01:000.000 (Config) Simulation :  --------------------------------------------------------------------
00-Adir-01:000.000 (Config) Simulation :  Note : The two builds are NOT identical.
00-Adir-01:000.000 (Warning) Simulation : Attempting to load a simulation made in build 5726 (older) under core engine build 5727 (newer).
00-Adir-01:000.000 (Config) Simulation :   - - - - - - - - - Sol 10 (Cont') - - - - - - - - - - - 
00-Adir-10:326.505 (Config) Fishery : [Schiaparelli Point] Large Greenhouse 1 - 14 fish, 270 weeds
00-Adir-10:326.505 (Config) Fishery : [New Pompeii] Fish Farm 1 - 146 fish, 2250 weeds
00-Adir-10:326.505 (Config) UnitManager : Setting up 6 threads for running the settlement update.
00-Adir-10:326.505 (Config) MainWindow : width : 1920  height : 1055
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:/C:/Users/mkhelios/.m2/repository/com/weblookandfeel/weblaf-core/1.2.13/weblaf-core-1.2.13.jar) to method sun.font.FontUtilities.fontSupportsDefaultEncoding(java.awt.Font)
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
00-Adir-10:326.505 (Config) AudioPlayer : Playing background music track #1 'Areologie.ogg'.
00-Adir-10:327.954 (Warning) Rover : [Spirit II] out-of-range O2 pressure at 0.0 kPa detected.
```

**Comment by bevans2000** [comment]
If possible use the console and connect to Aimar. Go to expert mode and run the 'work' command. This will show the Task cache. I suspect there nothing to do because Aimar is report as not un the Settlement which restricts available Tasks.

**Comment by mokun** [comment]
> If possible use the console and connect to Aimar. Go to expert mode and run the 'work' command. This will show the Task cache. I suspect there nothing to do because Aimar is report as not un the Settlement which restricts available Tasks.

Yes I do use console to look at Aimar's location. 

It said he's indeed in Garage 1 of that settlement.

So obviously, both Aimar and Mai came back home successfully from the mission.

It's just that Aimar couldn't get out of the garage and/or the rover.

Many other stats are also erroneous. Some are probably pre-existing and have nothing to do with the location state issue.

**Comment by mokun** [comment]
@bevans2000 

I haven't seen any more incidents of this. Have you ? 

It's for a settlement having a garage.

A vehicle came back from a mission and parked inside a garage. 

Somehow this person gets trapped inside that vehicle forever.

**Comment by bevans2000** [comment]
No I haven't but to be honest I haven't been looking for it.

**Comment by mokun** [comment]
I'll leave this thread alone for now and come back to that later if we see it again.

**Comment by bevans2000** [comment]
Is this still a problem?
