### ISSUE TITLE
Update the date stamp header

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#35]
Should we update to exactly the date of the official release of 3.1.0 or just write a python script or java program to grasp the date the file was last revised ? 

From :

> /**
>  * Mars Simulation Project
>  * Weather.java
>  * @version 3.08 2015-06-15
>  * @author Scott Davis
>  * @author Hartmut Prochaska
>  */
> 

To :

> /**
>  * Mars Simulation Project
>  * Weather.java
>  * @version 3.1.0 2017-03-11
>  * @author Scott Davis
>  * @author Hartmut Prochaska
>  */
>

**Comment by larsnaesbye** [comment]
Isn't it possible to tell Maven to increment a build number? Something like this: https://rterp.wordpress.com/2012/03/16/stamping-version-number-and-build-time-in-properties-file-with-maven/

**Comment by mokun** [comment]
That method suggest using pom.xml. It implies one has to run maven test in order to insert the date.

Instead of maven, we could use svn. 

see http://svnbook.red-bean.com/en/1.4/svn.advanced.props.special.keywords.html

I've made an attempt to semi-automatically insert the date onto a file on build [3666](https://sourceforge.net/p/mars-sim/code/3666/)

> /**
>  * Mars Simulation Project
>  * MarsProject.java
> * @version 3.1.0 2016-10-03
>  * @author Scott Davis
>  * $LastChangedDate$
>  * $LastChangedRevision$
>  */

But It was still a little clumsy.

We'll explore this further.

**Comment by mokun** [comment]
We have since settled on what the timestamp header would look like. 

We are now using @date to annotate the date a file was last modified.

We've got rid of the need to annotate the version of mars-sim on the header

Closing this thread now.
