### ISSUE TITLE
Mineral Exploration and collecting rock samples

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#353]
**Describe the bug**
There are irregularities occurring in a `Mineral Exploration`

**Desktop**
 - Build 5762

**Screenshot 1**
![image](https://user-images.githubusercontent.com/1168584/120113817-17b18400-c131-11eb-94b1-2d999b389bdf.png)

**Expected behavior**

1. The Mission Tool 'Info' tab should tell the exact amount of rock samples, minerals or ores being collected from a mission.
2. The Rover Windows should tell how much rock samples currently being carried in Inventory tab. Currently, it does not and it shows only individual specimen boxes that carry them. 
3. The amount of rock samples in each bag should vary and not be exactly at 50.1 kg.
4. The Specimen Box should NOT have "unknown" weight in kg when the content is known to be rock samples.
5. The Specimen Box should always label clearly what kind of content inside, especially when the weight/kg is known. 

**Screenshot 2**
![image](https://user-images.githubusercontent.com/1168584/120114515-598ff980-c134-11eb-9073-9cd6d6dd962c.png)

**Additional consideration**

6. Where exactly in settlements are these newly collected rock samples being stored ?
7. The Mission Tool 'Nav' should be made more useful than just showing different dots of colors of minerals, how about the amount of minerals at each site/navpoint ?
8.  Shall we use the console as the interface and the Commander Dashboard to showcase and compare across settlements how much of these rock samples, minerals, and ores have been collected, to give player a sense of accomplishment for ?

**Screenshot 3**
![image](https://user-images.githubusercontent.com/1168584/120116505-59e0c280-c13d-11eb-9b9e-5b27c1a0ce68.png)

**Comment by mokun** [comment]
@bevans2000 ,

I've just added a new `resourceCollected` map in Settlement in this [commit](https://github.com/mars-sim/mars-sim/commit/e52f9646d2407b3670ed0c2509e973ccf17e1ac1) for recording resources being collected by the citizens of a settlement.

In particular, I applied it toward the `rock samples` collected.

Note that it got *consumed* during a scientific study.

May be we can also use the console to query how much all the resources were being collected for ranking, etc.

**Comment by bevans2000** [comment]
Are the rock samples stored in the Inventory class as well?

**Comment by mokun** [comment]
> Are the rock samples stored in the Inventory class as well?

Yes. They were first carried within a `Specimen Box` after being excavated. 

> Note that `Specimen Box` is an `Equipment`.

So the rock samples are essentially in the inventory of a `Specimen Box`

Next, a person was carrying this box into a `Vehicle`. 

So the `Specimen Box` is inside the inventory of a person.

Next, the person got inside a vehicle. 

This way there's a chain of units within units via the use of the a number of Inventory classes.

**Comment by bevans2000** [comment]
Chain of units makes perfect sense. I was just wondering why the rock amounts need recording in the inventory and a new map in the Settlement.

**Comment by mokun** [comment]
> Chain of units makes perfect sense. I was just wondering why the rock amounts need recording in the inventory and a new map in the Settlement.

Currently, as strange as it may sound, I found out that some rock samples actually get *consumed* while being studied in a vehicle lab. 

So these rock samples never get showed up in a settlement for storage. 

There needs to be a way to capture the statistics of excavating the rock samples.

The purpose of the rock samples is that a person may use it to continue the field study in his field of scientific endeavor. 

We should probably further "quantify" the difference between having it and not having it. 

In reality, after slicing and dicing a rock samples for study, a sample set should still be stored and displayed in a settlement. 

How should we handle this ?

@Urwumpe , how would you envision that to be done ?
\

**Comment by mokun** [comment]
It looks like the Mineral Exploration mission undertaken by Rover Princess was able to collect 23,768 kg of Rock Samples. It's a little too much.

![image](https://user-images.githubusercontent.com/1168584/120942821-2f17e080-c6e0-11eb-976e-7d72d6b016bc.png)

**Comment by mokun** [comment]
In this sim, on sol 53, one settlement has such an insane amount of Rock Samples : 
![image](https://user-images.githubusercontent.com/1168584/121763617-51e83180-caf2-11eb-939f-4d9e0d2efd98.png)

**Comment by mokun** [comment]
Fixed.
