### ISSUE TITLE
Person is involved in too many Scientific studies started

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#359]
**Describe the bug**
Too many Scientific Study proposals seem to be started. This then leads over time to People collaborating on too many studies.

**Expected behavior**
The probability score in the MetaTask should be bias towards those with a scientific nature to limit the number of proposals created.

**Comment by mokun** [comment]
I notice that people are **bouncing** in and out at Science Tool, when they are in the *Performing Research* phase.

See my [screenshot](https://github.com/mars-sim/mars-sim/issues/357#issuecomment-858136779)

**Comment by bevans2000** [comment]
Generally there are 2 issues:

- People are too eager to create a new Scientific Study proposal
- People seem negative about continuing with Research on collaborating studies

I feel both will be due to the Task probability scores. I can have a look later today after work.

**Comment by mokun** [comment]
In build 5454, it takes too long (~40 sols) to complete a collaborative lab experiments.

We need to reduce the time limit.

```
00-Adir-11:990.467 (Info) PerformLaboratoryExperiment : [Europa] Sara De Vries - Just spent 4321.0 millisols in performing collaborative lab experiments on Meteorology #1.
00-Adir-11:990.467 (Info) PerformLaboratoryExperiment : [Europa] Oscar Andersen - Just spent 3953.8 millisols in performing collaborative lab experiments on Botany #4.
00-Adir-11:991.828 (Info) DigLocalIce [x11] : [Europa] Sara De Vries -  Started digging for ice.
00-Adir-11:995.704 (Info) DigLocalIce [x11] : [Europa] Oscar Andersen -  Started digging for ice.
00-Adir-12:044.704 (Info) ProposeScientificStudy : [Europa] Sara De Vries - Finished writing a study proposal in Physics.
00-Adir-12:045.223 (Info) ScientificStudy : [Europa] Sara De Vries - Finished writing proposal for Physics #7 study. Starting to invite collaborative researchers.
```

**Comment by mokun** [comment]
It's possible that the blocks of code below in ScientificStudy generates a time completion value that's as large as 47 sols.

```
	/**
	 * Computes the time of interest for this scientific study
	 * 
	 * @param index
	 * @return
	 */
	private double computeTime(int index) {
		// Gets the average time from scientific_study.json
		int mean = ScienceConfig.getAverageTime(index);
		// Modify it with random gaussian (and limit it to not less than 1/4 of the mean) for this particular scientific study
		double mod = RandomUtil.getGaussianDouble();
		if (mod > 10)
			mod = 10;
		return Math.max(mean / 4D, mean + mean * mod / 5D);	
	}
```


I'd say if it's more realistic to, say, set it at half the time it is currently. e.g. ~20 sols.

In reality it does have 47 sols to finish writing a research paper or tweak and refine how to run some experiments.

What should we do to strike that balance between the real world and the simulated world ?

**Comment by bevans2000** [comment]
Yes I agree it needs reducing. I plan to work on this next.
Also I want to increase the probability on the Accept task so we can get the Study moving quicker. Also allow multiple invites to be active, at the moment only one invite is active at once.
Lastly limit the  number of studies a Person can do.

**Comment by bevans2000** [comment]
Changes are three fold:
1. Prevent too many studies being  started; so only "Science" roles can start a study
2. Configurable limit on how many studies a Person can contribute towards
3. Changed Task priorities such that the Proposal and Invitee phase are given high priority to get them completed quickly

Still probably needs some tuning.

**Comment by mokun** [comment]
Sure. Great fixes!

So is it just a natural consequence to rarely see a 4-person settlement to get motivated in doing science ?

**Comment by bevans2000** [comment]
Yes, of course they could contribute but would not take the lead.

I wondered if having the concept of working agreements between Reporting Authorities would be useful? So science studies can only include Persons from friendly Authorities. For example NASA & ESA would work together but CSA on it own. This could also be applied to Trade between settlements in someway.

**Comment by mokun** [comment]
> For example NASA & ESA would work together but CSA on it own. This could also be applied to Trade between settlements in someway.

Yes. This would especially be useful in Command Mode when the player is commanding one settlement only.

We can even implement a friendliness index. If settlement A is donating x, y, z to settlement B, then A is practically courting or befriending B and the friendliness score of B toward A will go up, etc.

**Comment by bevans2000** [comment]
I have put some ideas in #363
