### ISSUE TITLE
Android vs. Web

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#36]
What do you guys think of developing mars-sim for android vs. for web ?

To me, it's more appealing to make mars-sim run under android.

also, I just read this good news at https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html

We've since incorporated some java 8 language features into mars-sim. Now it means we don't have to revert those changes in the core engine to make it work under android. But building an UI from scratch for android does take a lot of time.

**Comment by larsnaesbye** [comment]
Well, I'm very much a web guy and I don't have an Android phone :D

**Comment by larsnaesbye** [comment]
If we do a web version it shouldn't be as Web Start in an applet, since the Java browser plugin will likely go to the way of othe Rich Media framework plugins (Flash, Silverlight...): http://www.v3.co.uk/v3-uk/news/2443810/oracle-signals-the-end-of-java-applet-support-for-browsers

**Comment by mokun** [comment]
Sure. Applet and JWS are going away. Are we using Springboot instead?

**Comment by larsnaesbye** [comment]
If we do make a version for Android, we'll have to deal with small screens (compared to minimum desktop requirements). Do you think it's worth it?

**Comment by mokun** [comment]
> we'll have to deal with small screens (compared to minimum desktop requirements). Do you think it's worth it?

Screen size could be a LIMFAC but popularity of many android games tell us that people like them just as much and I myself prefer portability over hot-seat console games.

Whether it's web or App-based, imagine what it's like to have a cooperative simulation in which 10 players are playing the same sim across a network, each having his/her own android device. 

A commander-in-charge would make promotion to recruit new immigrants. He will elect his own cabinet members and assign various level of permission among them when it comes to making settlement- wide decision.

**Comment by larsnaesbye** [comment]
Well, even if we could make a dynamic and responsive UI under different sizes, Android is a locked platform. Web is more open and accessible and we could make it run in an applets browser instead?

**Comment by mokun** [comment]
If we want to reuse the core engine written in Java, we'll need at least Springboot.

In theory, but I was going to say that using Gluon is ever better since Springboot is geared toward Web applicatin only.

If we use Gluon, we won't have to worry about being locked in any particular platform. See https://pidome.org/info/blog-news/2015/8/27/glued-the-interfaces-together-alpha-version-downloads-available.html

We can still mars-sim as a desktop application but we'll have to redo the UI using whatever gluon provides. But its [javafxports](http://docs.gluonhq.com/javafxports/) is powerful. It allows porting the codes to Android/iOS/Web, which is what we want, don't we ?

**Comment by mokun** [comment]
> we could make it run in an applets browser instead

As you know, chrome and other browsers already ban applets due to security vulnerability

Oracle is also phasing out Java applet support in JDK9.

**Comment by larsnaesbye** [comment]
I wonder if there is a JavaFX to HTML5/JS mapping library. Running it in a browser would be awesome....

**Comment by mokun** [comment]
Because JavaFX's WebEngine always uses older versions of WebKit, some webpages are not rendered correctly.

btw, this site https://www.amcharts.com/javascript-maps/ has javascript-based maps and looks pretty

**Comment by AlmasB** [comment]
@mokun I know mars-sim uses [FXGL](https://github.com/AlmasB/FXGL) to some extent. FXGL now fully supports Android (and most of the functionality has been ported to web too). I wonder if it is easy to update all of the UI to use FXGL, in which case running on Android would be straightforward.

**Comment by mokun** [comment]
>  FXGL now fully supports Android (and most of the functionality has been ported to web too). 

@AlmasB, that's a very good news. I didn't know that until just a few days ago. Thanks for creating FXGL and I'm sure it will gain traction with the rest of the JavaFX community that there is a good use case for developing game engines on top of JavaFX and it's up how much we users are pushing for its adoption. Will more look into rebuilding mars-sim UI with FXGL in upcoming days.

**Comment by mokun** [comment]
I'm closing this discussion for now
