### ISSUE TITLE
Use unmanned drones to deliver goods between settlements

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#361]
## **Is your feature request related to a problem?**
- Trading of goods exists in mars-sim but rare. Due to prolong transport distances, trading is inconvenient and unrealistic. 

## **Describe the solution you'd like**
- We envision that Amazon-like delivery of goods in a timely manner would become common place.

## **Describe alternatives you've considered**
- Automated drone that runs on hydrogen or methane could solve
- Rudimentary traffic control would need to be in place. 

## **Additional context**
See this [memo](https://www.dhs.gov/science-and-technology/news/2019/02/12/snapshot-working-nasa-secure-drone-traffic) issued by U.S. Homeland Security expressing its willing to work with NASA and U.S. Federal Aviation Agency (FAA) on an  Unmanned Aircraft Systems (UAS) Traffic Management (UTM) infrastructure 

See [this](https://www.slashgear.com/nasas-ambitious-drone-air-traffic-control-trial-faces-its-toughest-challenges-22577585/) as well for some nice pictorial depictions.

We also have an old vehicle [wiki](https://github.com/mars-sim/mars-sim/wiki/New-Vehicles) drafted up in the past.

**Comment by mokun** [comment]
See this [presentation](https://www.hydrogen.energy.gov/pdfs/review19/ia011_jakupca_2019_o.pdf) from the U.S. Department of Energy/NASA on the use of fuel cell for future space applications.

**Comment by mokun** [comment]
@bevans2000 

I'd like to build something in the Command Mode to show the player how far it is from his settlement to another settlement. 

Can you also add a command in the console to find the distance between two settlements ?

We do have the method `getDistance()` in Coordinates that we can use.

**Comment by bevans2000** [comment]
I think we have a distance command already  but I'll check and get back to you.

**Comment by bevans2000** [comment]
Yes there is a distance command already. If you are connected to a Settlement it automatically uses that as the 1st point.

**Comment by mokun** [comment]
@bevans2000 

It looks like we can't start any `Delivery` mission because the value points (VP) calculation shows there's zero benefit of doing delivery.

![image](https://user-images.githubusercontent.com/1168584/124365154-0578a900-dbfb-11eb-9afc-5f0ce0f511b1.png)

Any insight as to how to fix it ? 

The probability score of a delivery meta mission is always zero because those calculations in DeliveryUtil (the counterpart of the TradeUtil) are always zero.

**Comment by mokun** [comment]
btw, 

I've tried to tidy up the GoodsManager yesterday. 

All amount resource raw materials should have high VP -- ideally, this should drive the need of settlement to acquire more of them, but there is still some missing gaps here and there and don't work as expected.

e.g. if a vehicle is down for maintenance and, say, it needs a few required parts (e.g. communication circuit board) before they can patch it up. 

GoodsManager is supposed to catch this and raise the VP in such a way that the settlement begins producing the resources and the items that are needed to assemble a communication circuit board. 

```
	<!-- 2015-05-19 Added manufacturing communications circuit board. -->
	<process name="manufacture communications circuit board" tech="3" skill="4" work-time="400" process-time="500"
			power-required="1.0">
		<inputs>
			<part name="microcontroller" number="1" />
			<part name="logic board" number="2" />			
			<part name="steel sheet" number="1" />
			<part name="electrical wire" number="1" />
			<part name="wire connector" number="1" />
			<part name="light emitting diode bulb" number="10" />
			<part name="plastic sheet" number="1" />
		</inputs>
		<outputs>
			<part name="communications circuit board" number="1" />
		</outputs>
	</process>
```

Last time when it happens, the VP of the communication circuit board doesn't go up dramatically enough to *drive* the process.

**Comment by mokun** [comment]
Finally get the Delivery mission working with drones between settlements. 

![image](https://user-images.githubusercontent.com/1168584/124399257-1a267100-dccf-11eb-900e-cadfbf896ead.png)

**Comment by bevans2000** [comment]
Super. I must check this out.

**Comment by mokun** [comment]
Both `Drone 001` and `Drone 004` happen to arrive at New Plymouth at more or less the same time. One is in unloading phase. The other one under negotiation phase.

![image](https://user-images.githubusercontent.com/1168584/124400195-899f5f00-dcd5-11eb-95c1-22aafafef5ae.png)

**Comment by mokun** [comment]
At the destination settlement, these numbers (in red box) aren't correctly presented. 

The travelled km is not the same as the proposed km.

Remaining km should be zero.

But when the drone starts the second leg of the journey to return home, the remaining km will start counting down from whatever estimated km.


![image](https://user-images.githubusercontent.com/1168584/124400771-d422da80-dcd9-11eb-9cc4-098f2e615cf2.png)

**Comment by mokun** [comment]
@bevans2000 ,

I have trouble figuring out why the vehicle operator is being flipped all the time. 

![image](https://user-images.githubusercontent.com/1168584/125233214-f3e66f80-e292-11eb-928a-6615a8b7620f.png)

![image](https://user-images.githubusercontent.com/1168584/125233289-18424c00-e293-11eb-90cd-750bbebc0842.png)

As a result, it can never truly proceed with the phase of embarking.

I suppose this will impact other missions as well.

Since Delivery mission is using autonomous drones, no one actually needs to be the pilot/driver. 

But for Delivery/Trade mission, we do need a starting member to be the negotiator for the VP transaction.

**Comment by mokun** [comment]
See below : 

```
00-Adir-10:592.512 (Info) TaskManager : [Schiaparelli Point] Leonardo DaVinci - Quit Reading. Unloading Drone 001 in Garage.
00-Adir-10:592.512 (Info) UnloadVehicleGarage : [Schiaparelli Point] Leonardo DaVinci - Unloaded EVA Suit 002 from Drone 001.
00-Adir-10:592.512 (Severe) Inventory : [Bag 028] Insufficient stored amount to retrieve cane fiber. Storage Amount : 0.0 kg. Attempted Amount : 4650.0 kg
00-Adir-10:592.512 (Info) UnloadVehicleGarage : [Schiaparelli Point] Leonardo DaVinci - Unloaded a total of 7.92 kg of resources from Drone 001.
00-Adir-10:592.512 (Info) PilotDrone [x54] : [Zvezda - Drone 004] DeliveryBot 003 - Took control of the drone.
00-Adir-10:623.148 (Info) TaskManager [x22] : [Schiaparelli Point] DeliveryBot 003 - Quit Consolidating Containers. Piloting Drone 004.
00-Adir-10:647.187 (Info) TaskManager : [Schiaparelli Point] Lena LaGranda - Quit Sleeping. Loading Drone 001 in Garage.
00-Adir-10:669.841 (Info) FindingLife : [New Plymouth] Amanda Johnson - Updating the report of the oxygen content in the soil samples.
00-Adir-10:674.455 (Info) TaskManager : [Schiaparelli Point] Seán Smith - Quit Sleeping. Loading Drone 001 in Garage.
00-Adir-10:742.648 (Info) TaskManager : [Schiaparelli Point] Ray Bradbury - Quit Sleeping. Loading Drone 001 in Garage.
00-Adir-10:742.648 (Info) TendGreenhouse : [Schiaparelli Point - Large Greenhouse 1] Nishka Nirmal - Growing potato tissue-culture in the botany lab.
00-Adir-10:780.574 (Info) TendGreenhouse : [New Plymouth - Inflatable Greenhouse 1] Carlos Diaz - Growing potato tissue-culture in the botany lab.
00-Adir-10:780.574 (Info) ProposeScientificStudy : [New Plymouth] Jeffrey Campbell - Finished writing a study proposal in Chemistry.
00-Adir-10:780.574 (Info) TaskManager [x3] : [Schiaparelli Point] Leonardo DaVinci - Quit Sleeping. Loading Drone 001 in Garage.
00-Adir-10:780.574 (Info) ProposeScientificStudy : [New Plymouth] Jeffrey Campbell - Finished writing a study proposal in Chemistry.
00-Adir-10:780.574 (Info) TaskManager : [Schiaparelli Point] Lena LaGranda - Quit Sleeping. Loading Drone 001 in Garage.
00-Adir-10:780.574 (Info) PilotDrone [x9] : [Zvezda - Drone 004] Hina Sasaki - Took control of the drone.
00-Adir-10:780.574 (Info) TaskManager [x8] : [Schiaparelli Point] Hina Sasaki - Quit Sleeping. Piloting Drone 004.
00-Adir-10:788.972 (Info) ScientificStudy : [New Plymouth] Jeffrey Campbell - Finished writing proposal for Chemistry #7 study. Starting to invite collaborative researchers.
00-Adir-10:788.972 (Info) PilotDrone [x9] : [Zvezda - Drone 004] DeliveryBot 003 - Took control of the drone.
00-Adir-10:799.261 (Info) TaskManager [x3] : [Schiaparelli Point] DeliveryBot 003 - Quit Consolidating Containers. Piloting Drone 004.
```

**Comment by mokun** [comment]
> See below :
> 
> ```
> 00-Adir-10:592.512 (Info) TaskManager : [Schiaparelli Point] Leonardo DaVinci - Quit Reading. Unloading Drone 001 in Garage.
> 00-Adir-10:592.512 (Info) UnloadVehicleGarage : [Schiaparelli Point] Leonardo DaVinci - Unloaded EVA Suit 002 from Drone 001.
> 00-Adir-10:592.512 (Severe) Inventory : [Bag 028] Insufficient stored amount to retrieve cane fiber. Storage Amount : 0.0 kg. Attempted Amount : 4650.0 kg
> 00-Adir-10:592.512 (Info) UnloadVehicleGarage : [Schiaparelli Point] Leonardo DaVinci - Unloaded a total of 7.92 kg of resources from Drone 001.
> 00-Adir-10:592.512 (Info) PilotDrone [x54] : [Zvezda - Drone 004] DeliveryBot 003 - Took control of the drone.
> 00-Adir-10:623.148 (Info) TaskManager [x22] : [Schiaparelli Point] DeliveryBot 003 - Quit Consolidating Containers. Piloting Drone 004.
> 00-Adir-10:647.187 (Info) TaskManager : [Schiaparelli Point] Lena LaGranda - Quit Sleeping. Loading Drone 001 in Garage.
> 00-Adir-10:669.841 (Info) FindingLife : [New Plymouth] Amanda Johnson - Updating the report of the oxygen content in the soil samples.
> 00-Adir-10:674.455 (Info) TaskManager : [Schiaparelli Point] Seán Smith - Quit Sleeping. Loading Drone 001 in Garage.
> 00-Adir-10:742.648 (Info) TaskManager : [Schiaparelli Point] Ray Bradbury - Quit Sleeping. Loading Drone 001 in Garage.
> 00-Adir-10:742.648 (Info) TendGreenhouse : [Schiaparelli Point - Large Greenhouse 1] Nishka Nirmal - Growing potato tissue-culture in the botany lab.
> 00-Adir-10:780.574 (Info) TendGreenhouse : [New Plymouth - Inflatable Greenhouse 1] Carlos Diaz - Growing potato tissue-culture in the botany lab.
> 00-Adir-10:780.574 (Info) ProposeScientificStudy : [New Plymouth] Jeffrey Campbell - Finished writing a study proposal in Chemistry.
> 00-Adir-10:780.574 (Info) TaskManager [x3] : [Schiaparelli Point] Leonardo DaVinci - Quit Sleeping. Loading Drone 001 in Garage.
> 00-Adir-10:780.574 (Info) ProposeScientificStudy : [New Plymouth] Jeffrey Campbell - Finished writing a study proposal in Chemistry.
> 00-Adir-10:780.574 (Info) TaskManager : [Schiaparelli Point] Lena LaGranda - Quit Sleeping. Loading Drone 001 in Garage.
> 00-Adir-10:780.574 (Info) PilotDrone [x9] : [Zvezda - Drone 004] Hina Sasaki - Took control of the drone.
> 00-Adir-10:780.574 (Info) TaskManager [x8] : [Schiaparelli Point] Hina Sasaki - Quit Sleeping. Piloting Drone 004.
> 00-Adir-10:788.972 (Info) ScientificStudy : [New Plymouth] Jeffrey Campbell - Finished writing proposal for Chemistry #7 study. Starting to invite collaborative researchers.
> 00-Adir-10:788.972 (Info) PilotDrone [x9] : [Zvezda - Drone 004] DeliveryBot 003 - Took control of the drone.
> 00-Adir-10:799.261 (Info) TaskManager [x3] : [Schiaparelli Point] DeliveryBot 003 - Quit Consolidating Containers. Piloting Drone 004.
> ```

Why would vehicle.getOperator() == null to begin with ? 

Seems like it's at this method performTravelPhase(MissionMember member) in VehicleMission. I've just changed things in this recent [commit](https://github.com/mars-sim/mars-sim/commit/5a6c3217342a44d4774a794a6d9c925de9339dab) but it still doesn't prevent the vehicle operator flipping from happening ?

**Comment by bevans2000** [comment]
Does this only happened after a reload?

**Comment by mokun** [comment]
> Does this only happened after a reload?

After the change, it seems to happen with or without a reload.

**Comment by mokun** [comment]
It may have to do with this snippet of codes in VehicleMission but not sure.

```
	/**
	 * If the mission is in TRAVELLING phase then only the current driver can participate.
	 * If the mission is in REVIEWING phase then only the leader can participate.
	 * 
	 * @param worker Worker requesting to help
	 */
	@Override
	public boolean canParticipate(MissionMember worker) {
		boolean valid = true;
	
        if (REVIEWING.equals(getPhase())) {
        	valid = getStartingPerson().equals(worker);
        }
        else if (TRAVELLING.equals(getPhase())) {
			if (vehicle.getOperator() != null) {
				// Check if I am the driver.
				if (vehicle.getOperator().getOperatorName().equals(worker.getName())) {
					// Vehicle thinks I'm driving but I am looking for a new Task ????
					vehicle.setOperator(null);
					logger.log(vehicle, worker, Level.WARNING, 0, "No longer being the vehicle operator.");
				}
				else {
					// Someone else is driving
					valid = false;
				}
			}
        }
		return valid && super.canParticipate(worker);
	}
```

**Comment by mokun** [comment]
When I comment out the line `vehicle.setOperator(null);` in this [commit](https://github.com/mars-sim/mars-sim/commit/29f58d87b711cfbd786f7c7d149b64ec72bb9a5f), looks like it doesn't flip from one pilot to another anything more.

However, for some strange reason, delivery missions can NO LONGER be shown in the Monitor Tool's Mission tab. 

![image](https://user-images.githubusercontent.com/1168584/125248342-cc020680-e2a8-11eb-9952-713354b1e740.png)

**Comment by bevans2000** [comment]
Yes this is what I was going to suggest. The `VehicleMission` assumes that the Vehicle always needs an operator. I would add a new method to Vehicle `isAutonomous` then use that value to decide if an operator is required. In the Vehicle class add the method with a default return of false. Then override it in the `Drone` class to return true.

**Comment by mokun** [comment]
> I would add a new method to Vehicle `isAutonomous` then use that value to decide if an operator is required. In the Vehicle class add the method with a default return of false. Then override it in the `Drone` class to return true.

ic. if we do it this way, we still need to consider how to make the PilotDrone task class that extends the task OperateVehicle to work well without a human pilot.  And what role the Delivery bot has as well.

**Comment by bevans2000** [comment]
Well if the Drone is autonomous then what does the PilotDrone task represent? I assume that it is needed to program the destination into the Drone at the start of a Mission? So it probably does not need to extend the OperateVehicle Task.

**Comment by mokun** [comment]
> Well if the Drone is autonomous then what does the PilotDrone task represent? 

For now it still requires at least a person to act as a trader for this drone when it arrives at the destination settlement.

As for piloting, a person doesn't have to be the pilot the whole time. A delivery bot can step in to replace his role.

But for trading, it needs a person to do the task.

> I assume that it is needed to program the destination into the Drone at the start of a Mission? 

I don't know if a person is needed at the beginning. I think the delivery bot can initiate the mission.

> So it probably does not need to extend the OperateVehicle Task.

Some calculation of the trajectory and speed are currently done in OperateVehicle class, rather than in PilotDrone.
