### ISSUE TITLE
Sponsoring Agencies

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#363]
Based on this [post](https://github.com/mars-sim/mars-sim/issues/288#issuecomment-862519553), we could streamline the codebase on how the sponsor string is being used by switching it to ReportingAuthority enum.

> Q 1:  Any Sponsor is a ReportingAuthority. Of not does it matter if it is not ?

Yes in a way. Currently, we define sponsor as the name of a space agency, a space business (SpaceX), or a space organization (e.g. Mars Society). 

![image](https://user-images.githubusercontent.com/1168584/122264970-084e6c80-ce8d-11eb-8809-1f5aeccfde4d.png)

We initially envision creating ReportingAuthority and its related set of classes acting as the mission control for all the initial settlements, until Mars establishes its own governance and has a government of its own.

> Q 2 : Why in the settlement.xml do we use the long Sponsor name and not just use the code values of the ReportingAuthorityType? It would make it easier to avoid typos.

Yes we could use the short abbreviated sponsor name to save space in `settlements.xml` and their enum in the code. 

Then within each ReportingAuthority, we always call getLongName() to output the long name. 

> Q 3: The -template argument is actually taking the integer id of the template settlement in the settlement.xml? So if the order changed the id would point to a different template.

Personally, I see that we should allow player to play SpaceX and have the flexibility in following either a standard SpaceX template or to choose the alternative, namely, one of NASA's template or ESA's template.

We could alert the player saying it's not the standard for that sponsor if they do choose the alternates.

> Q 4: A real confusing one for me. Why do we have 2 entries for every ReportingAuthority in the enum type? One for the short name and one for the long. These should be combined to be one with 2 different names.

It was just a transition we made half way. Yes we can switch to just using NASA, ESA, CNSA, SX (SX as SpaceX ?), MS (Mars Society ?), etc.

**Comment by mokun** [comment]
Hi all @bevans2000 , @Urwumpe, @jbosmans , @scud1 , @shirishag75 , @larsnaesbye 

In terms of new features, what kind of practical interactions would you like to see between a sponsor and its settlement that makes sense to get implemented for mars-sim down the road (in near and mid terms) ?

**Comment by bevans2000** [comment]
Points 2 & 4 in your post are important as it relates to code maintainability and that should always be important to us because this is not a full time job for any of us so things have to be easy to understand after a period looking at something else.
Point 3 we should introduce a 'level' property for the templates then the user could select 'SpaceX lvl 3'. The template name then could just become optional and/or auto-generated from the Sponsor and level combination. 
Point 1 is the one I don't understand. Is there a difference between Sponsor and the Reporting Authority. Everywhere in the code the Sponsor gets mapped to an Authority. But what does the Sponsor influence once a simulation is up and running? Does it then just become a tag on Settlements & Persons?

**Comment by shirishag75** [comment]
I have questions to which I have no answers currently which are both IRL as well in game. For e.g. we know that now apart from U.S. China is also there. And this would be confusing and probably a big big, so excuse. 

https://spaceflightnow.com/2021/05/25/chinese-rover-drives-onto-surface-of-mars/

Now from many of the fables and tales, usually mars is usually done in sectors. So for me the first question would be how would that be done and are there any interesting features where more than one group or country would like to have research on and collaborate. 

Also maybe all countries do not want to be in one place but be at different places pegged together by interests. How do we simulate that ?

Also how do you make missions and each country may have different missions which might be more interesting to it than others, depending on their needs. For e.g. food-related research maybe something with both India and China may co-operate and compete. There may be other areas too. 

As far as reporting goes, what sort of reporting and to whom. For e.g. Indian astronauts would be reporting to ISRO but do they need to report to some sort of Galactic authority or whatever. If so, what are and would be the terms and conditions. How frequent and what sort of data they would be needing ? Also how private or public that data would be ??? In many ways, it could be a can of worms. I have no clue where you want to go with this, so perhaps you give a more higher level understanding so I/we know what you are thinking about. 

Good to see you are good, hope others are also well, be safe , get vaccinated :)

**Comment by mokun** [comment]
> Is there a difference between Sponsor and the Reporting Authority ?

No they are the same thing.

> Everywhere in the code the Sponsor gets mapped to an Authority. But what does the Sponsor influence once a simulation is up and running? 

That's what we're discussing and exploring in this thread.

> Does it then just become a tag on Settlements & Persons?

I suppose we want to give each sponsor some subtle influences over the direction or the policy of her settlement since by definition the sponsor fund the settlement. 

Say if the settlement does X, Y, Z objectives, then the sponsor or the mission control will reward the settlement by sending resupplies A,B and C. 

But as time goes by, it'll get harder and harder to exert control when Mars is still inconveniently far away based on rocket technology.

**Comment by mokun** [comment]
> Also maybe all countries do not want to be in one place but be at different places pegged together by interests. How do we simulate that ?

That's a good question. 

We're designing in such way that each sponsor will have her uniquely objectives and vested interest in the fate of their settlement. 

e.g. some earlier development effort points to having China interested in primarily *prospecting minerals* on Mars.

```
public class ProspectingMinerals implements MissionAgenda, Serializable  {
	/** default serial id. */
	private static final long serialVersionUID = 1L;

	private final String name = "Prospercting Precious Minerals on Mars";
	
	private final String[] phases = new String[] {
			"Analyze Various Signature of Minerals",
			"Corroborate Surface Geological Data with On-Orbit Scans",
			"Core Drill Rock Samples from Selected Locations"};

	// Note : index for missionModifiers : 
	//	0 : AreologyFieldStudy
	//	1 : BiologyFieldStudy
	//	2 : CollectIce
	//	3 : CollectRegolith	
	//	4 : Exploration
	//	5 : MeteorologyFieldStudy
	//	6 : Mining
	//  7 : Trade
	//  8 : TravelToSettlement
	
	private final int[][] missionModifiers = new int[][] {
			{3, 0, 0, 3, 3, 3, 3, 0, 0},
			{3, 0, 0, 0, 0, 3, 0, 0, 0},
			{0, 0, 0, 0, 4, 0, 6, 0, 0}
	};
	
	@Override	
	public int[][] getMissionModifiers() {
		return missionModifiers;
	}
	
	@Override
	public String[] getPhases() {
		return phases;
	}


	@Override
	public String getObjectiveName() {
		return name;
	}


	@Override
	public void reportFindings() {
		System.out.println("I'm putting together reports of the helium-3 and other trace trace content in the collected soil samples.");
	}

	@Override
	public void gatherSamples() {
		System.out.println("I'm analyzing the wealth of mineral contents from the colleted soil samples.");
	}
}
```

**Comment by mokun** [comment]
> Also maybe all countries do not want to be in one place but be at different places pegged together by interests. How do we simulate that ?

Yes. They can be spread out or similarly interested in certain areas with high concentration of minerals or high probability of water deposit.

Elon Musk pointed out he has wanted his first base to be near some sub-surface water ice deposits.

```
The poles have readily available pack ice, but it has been decided that a relatively warm site (in Martian terms) should be considered along with berk water source, in the form of the suspected  massive sub-surface water ice deposits at Arcadia Planitia.

There were four other sites considered by SpaceX for establishing Mars Base Alpha.

They were Deuteronilus Mensae, Phlegra Montes, Utopia Planitia and southern Arcadia Planitia with the later one being the focus of SpaceX’s planned robotic surveyors to scout the terrain.  
```

See this [post](https://thehumanoid.net/2019-09-elon-musk-news-update-mars-base-alpha-location-arcadia-planitia-starship-human-space-colonization/)

**Comment by bevans2000** [comment]
Maybe we should limit ScientificStudy to people of the same ReportingAuthority. Also the Reporting Authority could have Objectives that influence the creation of new  Missions.

**Comment by mokun** [comment]
> Maybe we should limit ScientificStudy to people of the same ReportingAuthority. 

hmmm. I have wanted to allow *academic freedom*. It's true that some of the research could become classified by that nation state. 

it will be interesting to model this type of dynamics. The player who acts as a sponsor will decide if he wants to cooperate with another sponsor and on certain ground with certain research agreement in place.

It's not hard to image that in near future, international espionage of research and development (R&D) takes place on Mars, as much on Earth.

> Also the Reporting Authority could have Objectives that influence the creation of new Missions.

Yes the `missionModifier` on each type of MissionAgenda class is currently serving the purpose tweaking the potential of having various missions in each settlement in accordance with what her sponsor wants.

```
	// Note : index for missionModifiers : 
	//	0 : AreologyFieldStudy
	//	1 : BiologyFieldStudy
	//	2 : CollectIce
	//	3 : CollectRegolith	
	//	4 : Exploration
	//	5 : MeteorologyFieldStudy
	//	6 : Mining
	//     7 : Trade
	//     8 : TravelToSettlement
	
	private final int[][] missionModifiers = new int[][] {
			{3, 0, 0, 3, 3, 3, 3, 0, 0},
			{3, 0, 0, 0, 0, 3, 0, 0, 0},
			{0, 0, 0, 0, 4, 0, 6, 0, 0}
	};
```

I'm sorry that it may look cryptic currently.

The 3 rows are the 3 overarching goals here : 

```
	private final String[] phases = new String[] {
			"Analyze Various Signature of Minerals",
			"Corroborate Surface Geological Data with On-Orbit Scans",
			"Core Drill Rock Samples from Selected Locations"};

```

The 8 columns represents those 8 types of missions.

We're testing how well the modifiers work and so there's no wiki or documentation yet :D

**Comment by mokun** [comment]
Just did a [commit](https://github.com/mars-sim/mars-sim/commit/bfc550d7c7fb75800ee6a733c1eb751fada3eb09) in which a new task called `ReportMissionControl` is added. 

Usually a commander or sub-commander will perform this task. 

It sort of simulates reporting the findings to the mission control sponsor. A log statement will be printed out.

**Comment by mokun** [comment]
@bevans2000 , 

Can you take a look at the `MarsProjectHeadless` ? I can't start a single spacex settlement from it after we changed a few things recently.

I can see you refactor `MarsProjectHeadless` nicely and now `MarsProject` is not as organized by `MarsProjectHeadless`.

**Comment by mokun** [comment]
> I can't start a single spacex settlement from it after we changed a few things recently.

This is more related to these two feature request / issues in the past :
1. https://github.com/mars-sim/mars-sim/issues/260
2. https://github.com/mars-sim/mars-sim/issues/152

**Comment by bevans2000** [comment]
Sure I will look at `MarsProject`. I think our various starting classes have quite a bit of duplication. I would if we should have a single `MarsLauncher` class and drive it from various starting routes.

**Comment by mokun** [comment]
> I think our various starting classes have quite a bit of duplication. I would if we should have a single `MarsLauncher` class and drive it from various starting routes.

How do we refactor in such a way that we have one single `MarsLauncher` class ?

The hard part is that we compile into two separate jars, one for Swing and one for Headless on their own maven submodule.

But as you know, this division is artificial since both use Swing component.

**Comment by bevans2000** [comment]
We would still have the separate main classes but the shared logic  centralised. I was wanting to move the build initial settlements out of the `UnitManager` as part of #355. So may be consider a shared class called `MarsBuilder` that understand the user requests and then populate the simulation. I would also include the executor logic for the bootstrapping in here.

**Comment by mokun** [comment]
> I was wanting to move the build initial settlements out of the `UnitManager` as part of #355

Ok, will there be any newly introduced features with this shared class ? 

Q: Will there be two separate jars to be compiled, right ?

**Comment by bevans2000** [comment]
Yes as many jars as we want. I see the benefit as consolidating the features to make sure the same are available to all jars. Maybe implement the the idea of defining custom settlements.

**Comment by bevans2000** [comment]
@mokun OK so how SHOULD the command line arguments be used for a single Settlement simulation? I've changed the headless but the UI version is a little different but I can see benefit in consolidating.

- -X the latitude of new settlement
-  -Y the longitude as above
- -sponsor The Reporting Authority of the new settlement
-  -country This appears not be to used anywhere?
- -template This should be the full template string in the settlements.xml ?

**Comment by mokun** [comment]
Currently, this would work

`-new -8192x -template:3-X -x:5.05S -y:4.21E -sponsor:SPACEX -country:USA`

**Comment by bevans2000** [comment]
How about we drop the ':' and go for argument and value pairs? I want to combine the argument parsing for all the jars into one.
What if you wanted to use a ESA template but with NASA as sponsor? Would it be more flexible to specific the full template name and the sponsor argument becomes an override for creating the Settlement?
I can't see where the country is used in the code but I'll double check again.

**Comment by mokun** [comment]
> How about we drop the ':' and go for argument and value pairs?

Sure. Can you give an example here ?

> What if you wanted to use a ESA template but with NASA as sponsor? Would it be more flexible to specific the full template name

Sure. np. 

But at some point in future, a template may include some custom things specifically designed for a particular sponsor.

For instance, a Japanese settlement may have Sushi shop, instead of a dining hall or cafeteria. Of course right now, each building type use the same generic names, regardless the sponsor/country.

**Comment by bevans2000** [comment]
`-new -ratio 8192 -template 3-X -x 5.05S -y 4.21E -sponsor SPACEX -country USA`
Like this, a more common approach.

**Comment by mokun** [comment]
> `-new -ratio 8192 -template 3-X -x 5.05S -y 4.21E -sponsor SPACEX -country USA`
> Like this, a more common approach.

ok. So the difference is that the separator between key and value is now a whitespace, instead of being a colon. 

I though most Java command line argument would use the colon but I could be wrong. 

For instance, [here](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html).

**Comment by mokun** [comment]
So, at some points in the past, we don't require the use of the hyphen or the dash. 

In that case, the colon is crucial, since the word after a whitespace is the key of a key-value pair.

So, EITHER we mandate the use of the dash to indicate the beginning of a key or argument. 

OR we mandate the use of the colon between the key and the value of a key-value pair.

**Comment by bevans2000** [comment]
I've never used a tool or worked on a application that uses a colon as the separator. The headless uses Apache Commkn and we should use this everywhere. https://commons.apache.org/proper/commons-cli/usage.html

**Comment by bevans2000** [comment]
Done changes to the UI MarsProject. A lot simpler and clearer now. Also had to change the SimulationConfigEditor which also could start simulations.
Need to do a bit of testing of the various start-up scenarios but it is looking much simpler and clearer now. A single consolidated set of runtime arguments across both executable JARS.

**Comment by mokun** [comment]
> Done changes to the UI MarsProject

When you say UI, you mean the UI thread management ?

**Comment by bevans2000** [comment]
Consolidating the startup classes

**Comment by bevans2000** [comment]
49681b726013ffa9343332361d95a794584b21a8

Added a '-nogui' argument to the UI Mars Project that just runs the console and no Swing. Also changed the '-x' & '-y' to '-lon' & '-lat' to make it obvious which is which.
Also manged to simplify the start up so there is not any need for running thread pool to start up.

**Comment by mokun** [comment]
> Added a '-nogui' argument to the UI Mars Project that just runs the console and no Swing. Also changed the '-x' & '-y' to '-lon' & '-lat' to make it obvious which is which.

@bevans2000 

Can we modify the content inside [setup.md](https://github.com/mars-sim/mars-sim/blob/master/setup.md) ? 

It talks about starting the mars-sim and the kind of arguments one can use.

**Comment by bevans2000** [comment]
Yes I can take a look.

**Comment by mokun** [comment]
@bevans2000 ,

Currently, on my laptop, the Phase 3-X template can't start the sim. 

Somehow, the time ratio is zero.

```
2021-07-03T13:33:39.8 (Config) MarsProject : Starting Mars Simulation Project v3.2.0 - Build 5897 - 64-bit Java 13.0.2 - 8 CPU threads
2021-07-03T13:33:40.0 (Config) SimulationConfig : The xml folder already existed.
2021-07-03T13:33:40.0 (Config) SimulationConfig : The version.txt has the same BUILD 5897 as the core engine's.
2021-07-03T13:33:40.5 (Config) SimulationConfig : Done loading all xml files.
2021-07-03T13:33:40.5 (Info) SimulationBuilder : Starting a single Settlement sim using template Phase 3-X with settlement name = New Copenhagen
2021-07-03T13:33:40.5 (Config) Simulation : Initiating the simulation core engine...
2021-07-03T13:33:40.6 (Config) MasterClock : -----------------------------------------------------
2021-07-03T13:33:40.6 (Config) MasterClock :          User defined time-ratio : 128.0x
2021-07-03T13:33:40.6 (Config) MasterClock :               Min msol per pulse : 0.02
2021-07-03T13:33:40.6 (Config) MasterClock :               Max msol per pulse : 2.0
2021-07-03T13:33:40.6 (Config) MasterClock :  Max elapsed time between pulses : 1000 ms
2021-07-03T13:33:40.6 (Config) MasterClock :                    Accuracy bias : 0.5
2021-07-03T13:33:40.6 (Config) MasterClock : -----------------------------------------------------
2021-07-03T13:33:41.0 (Config) TerrainElevation : [New Copenhagen]                 Elevation : -0.673 km
2021-07-03T13:33:41.0 (Config) TerrainElevation : [New Copenhagen]         Terrain Steepness : 0.0
2021-07-03T13:33:41.0 (Config) TerrainElevation : [New Copenhagen]       Ice Collection Rate : 0.73 kg/millisol
2021-07-03T13:33:41.3 (Config) EVASuit :  EVA suit's unloaded weight : 20.3 kg
2021-07-03T13:33:41.3 (Config) EVASuit :       Total gas tank volume : 3.9L
2021-07-03T13:33:41.3 (Config) EVASuit :                Full Tank O2 : 66.62 kPa -> 1.0    kg - The Maximum tank pressure
2021-07-03T13:33:41.3 (Config) EVASuit :                  Nomimal O2 : 17.0  kPa -> 0.2552 kg - The suit target pressure
2021-07-03T13:33:41.3 (Config) EVASuit :                  Minimum O2 : 11.94 kPa -> 0.1792 kg - The safety limit

2021-07-03T13:33:42.7 (Config) UnitManager : Robot GardenBot 001 is being sent to New Copenhagen since Schiaparelli Point doesn't exist.
2021-07-03T13:33:42.7 (Config) UnitManager : Alpha crew member 'Karen Andersen' has the designated settlement called 'Schiaparelli Point' but it doesn't exist.
2021-07-03T13:33:42.7 (Config) Mind : [New Copenhagen] Paul Gruber - Becomes Chemist, approved by Mission Control.
2021-07-03T13:33:42.7 (Config) Mind : [New Copenhagen] Ava Thomson - Becomes Meteorologist, approved by Mission Control.
2021-07-03T13:33:42.7 (Config) Mind : [New Copenhagen] Alexandra Stoica - Becomes Physicist, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Dimitrios Dimitriadis - Becomes Pilot, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Balázs Farkas - Becomes Areologist, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Liisa Tamm - Becomes Mathematician, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Alisa Pärn - Becomes Biologist, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Laura Fontana - Becomes Architect, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Liam Van Dijk - Becomes Technician, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Vasileios Petridis - Becomes Physicist, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Kostas Angelopoulos - Becomes Areologist, approved by Mission Control.
2021-07-03T13:33:42.8 (Config) Mind : [New Copenhagen] Leonor Pereira - Becomes Technician, approved by Mission Control.
00-Adir-01:000.000 (Config) MasterClock : [Unknown] MasterClock : Proposed pulse 0.00144 increased to a minimum of 0.02.
00-Adir-01:000.020 (Config) UnitManager : Setting up 1 thread(s) for running the settlement update.
00-Adir-01:000.020 (Config) MarsProject : Starting GUI
00-Adir-01:000.020 (Config) MainWindow : width : 1920  height : 1055
00-Adir-01:000.020 (Warning) CookMeal : [New Copenhagen] ChefBot 004 - Cannot cook any meals. None of the ingredients are available.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.alee.utils.ReflectUtils (file:/C:/Users/mkhelios/.m2/repository/com/weblookandfeel/weblaf-core/1.2.13/weblaf-core-1.2.13.jar) to method sun.font.FontUtilities.fontSupportsDefaultEncoding(java.awt.Font)
WARNING: Please consider reporting this to the maintainers of com.alee.utils.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
00-Adir-01:004.386 (Config) AudioPlayer : Playing background music track #1 'Areologie.ogg'.
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Lander Hab 1] Paul Gruber - Designated a bed at (1.5, 3.16).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Ava Thomson - Designated a bed at (-9.8, 16.2).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Alexandra Stoica - Designated a bed at (-9.8, 14.8).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Lander Hab 1] Dimitrios Dimitriadis - Designated a bed at (-0.39, 3.46).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Lander Hab 1] Balázs Farkas - Designated a bed at (-3.14, 0.83).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Lander Hab 1] Liisa Tamm - Designated a bed at (-3.04, -1.04).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Alisa Pärn - Designated a bed at (-9.8, 13.4).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Laura Fontana - Designated a bed at (-9.8, 12.4).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Liam Van Dijk - Designated a bed at (-9.8, 11.0).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Vasileios Petridis - Designated a bed at (-9.8, 9.6).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Kostas Angelopoulos - Designated a bed at (-14.2, 16.2).
00-Adir-01:010.035 (Info) LivingAccommodations : [New Copenhagen - Residential Quarters 1] Leonor Pereira - Designated a bed at (-14.2, 14.8).
00-Adir-01:062.148 (Config) MasterClock : Time-ratio 128x -> 0x
00-Adir-01:062.148 (Warning) MasterClock : Elapsed real time is 30169 ms, longer than the max time 30000 ms.
```

**Comment by mokun** [comment]
@bevans2000 

I'm adding some more intelligence to detecting if TR is at zero in some cases and adjust accordingly.

**Comment by bevans2000** [comment]
Exactly what happened to me. I think with this template it generates a condition where there is a loop in the Task logic so the pulses become very long. You can see the warm about elapsed time. This pushes the time ratio calculation to set it to zero.

**Comment by bevans2000** [comment]
> Exactly what happened to me. I think with this template it generates a condition where there is a loop in the Task logic so the pulses become very long. You can see the warm about elapsed time. This pushes the time ratio calculation to set it to zero.

Yes stopping it reaching zero would be a good safety feature.

**Comment by bevans2000** [comment]
I think that we could implement "friendship" agreements between the Reporting Authorities. RA that are happy to work together. 
This could then impact ScientificStudy and influence who can collaborator (#357) and also what Trade can be done and cost. 
Also if we implement #375 then we can have multiple Settlements of the same RA; then maybe trade between them are free?

**Comment by larsnaesbye** [comment]
Reporting Authorities could possibly have levels of will to cooperate, a bit like the relationships between settlers? This could change over time, but not often and only gradually so, so it doesn't oscillate wildly.

**Comment by bevans2000** [comment]
Looking at the `MissionAgenda` & `ReportingAuthority` subclasses they all basically have the same logic. This suggests that these class can be replaced with generic versions that are configured via a new XML configuration file. This file would only be loaded at the creation of a new Simulation. This

**Comment by mokun** [comment]
> Reporting Authorities could possibly have levels of will to cooperate, a bit like the relationships between settlers? This could change over time, but not often and only gradually so, so it doesn't oscillate wildly.

Hey @larsnaesbye, how have you been ? 

Yes. But we could add different dimension to this relationship between two settlements.

So it can be a composite score that sums up from a number of things.

**Comment by larsnaesbye** [comment]
> Hey @larsnaesbye, how have you been ?

Absolutely, primarily spending time getting my work life to be [more about positioning using a combination of satellites and ground stations](https://eng.sdfe.dk/about-us/organisation/spatial-references). :-)

**Comment by mokun** [comment]
> > Hey @larsnaesbye, how have you been ?
> 
> Absolutely fine, primarily spending time getting my work life to be [more about positioning using a combination of satellites and ground stations](https://eng.sdfe.dk/about-us/organisation/spatial-references). :-)

Wow! what a great real world application

**Comment by bevans2000** [comment]
I've now realised that we should not have the Reporting Authority hardcoded in the source. It should be driven by configuration. This opens up oppotunity to define different set ups in the future. This also means people names have to be totally driven by country and not sponsor, which actualy makes better sense.
