### ISSUE TITLE
Excessive Specimen boxes created in disembarking (Excessive use of CopyOnWriteArrayList)

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#364]
**Describe the bug**
In one run over 300 specimen boxes were created to unload a Vehicle. This results in large increase in memory consumption and a slow down of the simulation. There did not seem to be an obvious problem or early sign of an issue.

**To Reproduce**
Never seen the problem before and could not reproduce.

**Expected behavior**
There is a significant problem with the over use of the CopyOnWriteArrayList. Each time an entry is added the internal array is copied so when using it to create a temporary list to return a normal ArrayList should always be used. `Inventiry.getContainedUnits` is a good example and this is where the above problem was manifested; the Unit Thread was just growing the internal byte array all the time.

**Comment by bevans2000** [comment]
This might be related to disembarking Missions after a reload.

**Comment by bevans2000** [comment]
I think this maybe be a case of #334. If a Vehicle is parked in a Garage when the simulation is saved awaiting unloading; when the sim is reloaded the Garage is not persisted and hence the Vehicle becomes "lost" and is no longer in the Garage. But the Vehicle location status is inside a Settlement so there is a conflict which prevent the UnloadVehicle task working.

**Comment by mokun** [comment]
> when the sim is reloaded the Garage is not persisted and hence the Vehicle becomes "lost" and is no longer in the Garage.

oic.
