### ISSUE TITLE
Time Ratio (TR) Adjustment based on the Tick Per Sec (TPS)

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#369]
We've been recently experimenting with having the simulation automatically adjust the time ratio (TR) (also known as the *speed* of the simulation).

See this [thread](https://github.com/mars-sim/mars-sim/commit/c80fed0615daea794339132c02f82686ef7db1b4#r52797553).

We have also replaced the old TR slider found in the *Time Tool* with two buttons on the bottom left of the `MainWindow`'s status bar on [build 5870](https://github.com/mars-sim/mars-sim/commit/db6731d4b07d78fcb06798ed40fb520a88ae032e).

Let's continue our discussions of any corrective actions for optimizing the simulation speed here.

**Comment by mokun** [comment]
@bevans2000 

I don't know why those 'slow' param labels aren't being updated in `TimeWindow` right now.

I've tried putting those setText() into a in updateTimeLabels(). But the result is the same.

They don't get updated unless I clicked on the Time Tool panel.

```
	@Override
	public void uiPulse(double time) {
		if (desktop.isToolWindowOpen(TimeWindow.NAME)) {
			// update the slow labels
			updateSlowLabels();
		}
	}

	/**
	 * Update the calendar, the time ratio and time compression labels via ui pulse
	 */
	public void updateSlowLabels() {
		// Update the two time labels
		updateTimeLabels();
		// Update the calender
		calendarDisplay.update();
	}

	public void updateTimeLabels() {
		
		if (marsTime != null) {
//			String ts = marsTime.getDateTimeStamp();
//			if (!ts.equals(":") && ts != null && !ts.equals("") && martianTimeLabel != null)
//				SwingUtilities.invokeLater(() -> martianTimeLabel.setText(ts));			
			
			int solElapsed = marsTime.getMissionSol();
			if (solElapsedCache != solElapsed) {
				solElapsedCache = solElapsed;
				String mn = marsTime.getMonthName();
				if (mn != null)// && martianMonthLabel != null)
					SwingUtilities.invokeLater(() -> martianMonthLabel.setText("Month of " + mn));
				setSeason();
			}
		}
		

		// Create average TPS label
//		if (aveTPSLabel != null) {
			double ave = masterClock.updateAverageTPS();
			SwingUtilities.invokeLater(() -> aveTPSLabel.setText(formatter2.format(ave)));
//		}

		// Create execution time label
//		if (execTimeLabel != null) {
			long execTime = masterClock.getExecutionTime();
			SwingUtilities.invokeLater(() -> execTimeLabel.setText(execTime + MS));
//		}
		
		// Create sleep time label
//		if (sleepTimeLabel != null) {
			long sleepTime = masterClock.getSleepTime();
			SwingUtilities.invokeLater(() -> sleepTimeLabel.setText(sleepTime + MS));
//		}
		// Create mars pulse label
//		if (marsPulseLabel != null)  {
			double pulseTime = masterClock.getMarsPulseTime();
			SwingUtilities.invokeLater(() -> marsPulseLabel.setText(Math.round(pulseTime *1000.0)/1000.0 + MSOL));
//		}
			
		int ratio = (int)masterClock.getTimeRatio();

//		if (timeRatioLabel != null)
			SwingUtilities.invokeLater(() -> timeRatioLabel.setText(ratio + "x"));

//		if (timeCompressionLabel != null)
			SwingUtilities.invokeLater(() -> timeCompressionLabel.setText(ClockUtils.getTimeString(ratio)));
	}
```

**Comment by mokun** [comment]
btw, feel free to change the ClockListener and alter the uiPulse() method as you see fit.

https://github.com/mars-sim/mars-sim/blob/044dbee00576547bb2825cd570ab04f1c458021e/mars-sim-core/src/main/java/org/mars_sim/msp/core/time/ClockListener.java#L21-L28

**Comment by bevans2000** [comment]
> @bevans2000
> 
> I don't know why those 'slow' param labels aren't being updated in `TimeWindow` right now.
> 
> I've tried putting those setText() into a in updateTimeLabels(). But the result is the same.
> 
> They don't get updated unless I clicked on the Time Tool panel.
> 
> ```
> 	@Override
> 	public void uiPulse(double time) {
> 		if (desktop.isToolWindowOpen(TimeWindow.NAME)) {
> 			// update the slow labels
> 			updateSlowLabels();
> 		}
> 	}
> 
> 	/**
> 	 * Update the calendar, the time ratio and time compression labels via ui pulse
> 	 */
> 	public void updateSlowLabels() {
> 		// Update the two time labels
> 		updateTimeLabels();
> 		// Update the calender
> 		calendarDisplay.update();
> 	}
> 
> 	public void updateTimeLabels() {
> 		
> 		if (marsTime != null) {
> //			String ts = marsTime.getDateTimeStamp();
> //			if (!ts.equals(":") && ts != null && !ts.equals("") && martianTimeLabel != null)
> //				SwingUtilities.invokeLater(() -> martianTimeLabel.setText(ts));			
> 			
> 			int solElapsed = marsTime.getMissionSol();
> 			if (solElapsedCache != solElapsed) {
> 				solElapsedCache = solElapsed;
> 				String mn = marsTime.getMonthName();
> 				if (mn != null)// && martianMonthLabel != null)
> 					SwingUtilities.invokeLater(() -> martianMonthLabel.setText("Month of " + mn));
> 				setSeason();
> 			}
> 		}
> 		
> 
> 		// Create average TPS label
> //		if (aveTPSLabel != null) {
> 			double ave = masterClock.updateAverageTPS();
> 			SwingUtilities.invokeLater(() -> aveTPSLabel.setText(formatter2.format(ave)));
> //		}
> 
> 		// Create execution time label
> //		if (execTimeLabel != null) {
> 			long execTime = masterClock.getExecutionTime();
> 			SwingUtilities.invokeLater(() -> execTimeLabel.setText(execTime + MS));
> //		}
> 		
> 		// Create sleep time label
> //		if (sleepTimeLabel != null) {
> 			long sleepTime = masterClock.getSleepTime();
> 			SwingUtilities.invokeLater(() -> sleepTimeLabel.setText(sleepTime + MS));
> //		}
> 		// Create mars pulse label
> //		if (marsPulseLabel != null)  {
> 			double pulseTime = masterClock.getMarsPulseTime();
> 			SwingUtilities.invokeLater(() -> marsPulseLabel.setText(Math.round(pulseTime *1000.0)/1000.0 + MSOL));
> //		}
> 			
> 		int ratio = (int)masterClock.getTimeRatio();
> 
> //		if (timeRatioLabel != null)
> 			SwingUtilities.invokeLater(() -> timeRatioLabel.setText(ratio + "x"));
> 
> //		if (timeCompressionLabel != null)
> 			SwingUtilities.invokeLater(() -> timeCompressionLabel.setText(ClockUtils.getTimeString(ratio)));
> 	}
> ```

Maybe the Swing thread has crashed or is blocked because the code is using `updateLater`. Try calling the setLabel directly. The question is should the ui be updated by the clock thread or should there be a dedicated ui thread the just refreshes ui components at a fixed rate. #309 is a similiar issue.
