### ISSUE TITLE
JDK 9 support

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#37]
In order to test for java 9 support on mars-sim in eclipse, we need to use a special Eclipse SDK build available at http://download.eclipse.org/eclipse/updates/4.7-Y-builds/

see https://wiki.eclipse.org/Java9 and https://marketplace.eclipse.org/content/java-9-support-beta-oxygen for details.

I suppose it will be easier to extend mars-sim to support openjdk 9 versus openjdk8/openjfx 8.

Let me know if you guys are interested in pursuing java 9.

**Comment by larsnaesbye** [comment]
The question is if we will release before or after the advent of Java 9. I would prefer before, but if we know it's going to take longer, then maybe it's good to prep for 9.

**Comment by mokun** [comment]
Since java 9 will bring a number of major changes (the import paths for some java API will change), there's a good chance that we will need to maintain a separate branch just to make mars-sim compiled under java 9. Does it worth the extra effort ?

Note: it's good that the support of openjdk/openjfx is no longer an [issue](https://github.com/mars-sim/mars-sim/issues/1) .

**Comment by larsnaesbye** [comment]
> Note: it's good that the support of openjdk/openjfx is no longer an issue .

I agree. Let us see about it - Java 9 [isn't due until July](http://www.java9countdown.xyz/) and our tools most certainly will not be optimized for quite some time.

Is there anything in Java 9 that will give us significant improvements with regards to MSP? If not, then I suggest we wait with pursuing it until it's at least in Golden Master, since changes happen all the time like in any major release project....

**Comment by larsnaesbye** [comment]
It seems that Eclipse Oxygen now has support for Java 9. So we are good for moving to JDK 9.0.1 :-)

**Comment by mokun** [comment]
Because of Project Jigsaw in Java 9, according to this [spec page](http://openjdk.java.net/projects/jigsaw/spec/sotms/) and the [quick-start
 page](http://openjdk.java.net/projects/jigsaw/quick-start), we'll have to define the dependency explicitly by creating a `module-info.java` for each maven sub-module in the source root directory, namely, `src/main/java` since mars-sim is multi-module. When compiled, so it will be turned into a module descriptor, namely, `module-info.class`. 


Question :  Do we need to state each maven artifacts and/or class file that are to be packaged into a jar file for that maven sub-module ?

**Comment by mokun** [comment]
Also, each maven artifact (the third party library) will need to support JDK 9 according to [this page](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-AFD3BDEC-99FC-4F3C-946F-A1CD2D05B74B). 

See [this page](https://wiki.openjdk.java.net/display/quality/Quality+Outreach) that shows a list of open source library that "support JDK 9".

**Comment by mokun** [comment]
This page https://cwiki.apache.org/confluence/display/MAVEN/Java+9+-+Jigsaw shows the Java 9 compatibility of various maven plugins.

**Comment by larsnaesbye** [comment]
JDK 10 is even out now :-P

**Comment by mokun** [comment]
I suppose we should look into reducing the dependence on maven artifact from now so as to make mars-sim easier to port from one java version to the next 😀

**Comment by larsnaesbye** [comment]
I hope that each new version will brek fewer things than before :P

**Comment by mokun** [comment]
@shirishag75 @larsnaesbye , the way I understand is that there are currently at least two obstacles that we'll need to work out.

(1) Transitioning mars-sim to go beyond Java 8 or OpenJDK 8 requires the changing the codes Project Jigsaw. See http://openjdk.java.net/projects/jigsaw/ This affects both Oracle Java or OpenJDK.

(2) JavaFX is bundled with Oracle Java 8 but not with OpenJDK. Therefore, if someone uses OpenJDK 8, he will need to install OpenJFK separately in his machine. Beginning Java 9, Oracle introduce breaking changes in the import statement that call for JavaFX UI elements. According to Oracle, they want to give away JavaFX to the open source community one day so that its development is faster.

It looks like we will need to maintain you separate versions of mars-sim, one for supporting the use of Java 8, one for Java 9 and beyond. Do we want that ?

Also, should we quit using JavaFX UI ?

**Comment by larsnaesbye** [comment]
I don't like the idea of two separate versions of our code, not when it's as complex and voluminous as it is today. It won't be long until Java 8 isn't supported anymore (http://www.oracle.com/technetwork/java/eol-135779.html) anyway.

**Comment by mokun** [comment]
It seems there is a couple of issues we are dealing with here. Let's break them down and separate them apart.

1. We need a way-forward plan to support mars-sim fans who have installed only java 9 and above (not java 8).

2.  We need to determine if supporting java 8 (or openjdk with openjfx 8) still have any merit.

3. If Debian is unable to resolve bugs under openjdk and openjfx 9, how would this affect our support base ?

....

**Comment by larsnaesbye** [comment]
We could supply a JRE 8 with our distribution, but @shirishag75 is right: Java 11 is going to be LTS and since we haven't made a 'real' release for some time we might as well go own that path(?).

**Comment by shirishag75** [comment]
Just to share, as I'm on Debian testing, we just got java 10 in testing which means the next release of Ubuntu whenever they release would have java 10 as default and not java 8 . 

```
$ sudo aptitude safe-upgrade -y
Resolving dependencies...                
The following NEW packages will be installed:
  openjdk-10-jre{a} openjdk-10-jre-headless{a} 
The following packages will be upgraded:
  default-jre default-jre-headless java-common snipped rest 
15 packages upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 109 MB of archives. After unpacking 184 MB will be used.
```

**Comment by larsnaesbye** [comment]
I seem to recall that JavaFX will be separated in version 11.

**Comment by mokun** [comment]
@larsnaesbye, that's true. JavaFX won't be included in Oracle's Official Java 11. 

But the confusing part is that, for the open source community, OpenJDK 8 never includes OpenJFX from the beginning. One always has to compile their own version of OpenJFX for their machine.

I just updated some changes in our [Development Environment](https://github.com/mars-sim/mars-sim/wiki/Development-Environment) wiki page. Now it shows the links for downloading JavaFX's binaries. See "A. Compiled Java Binaries".

@shirishag75, in short, you may want to try out an OpenJFX 8 build from https://chriswhocodes.com/ or an OpenJFX 11 ea build from http://jdk.java.net/openjfx/

**Comment by mokun** [comment]
@shirishag75, for debian, I'll rely on what they post on this page at https://packages.qa.debian.org/o/openjfx.html

**Comment by shirishag75** [comment]
The problem is I'm running Debian testing and the default-jre is now openjdk-10 as shared above and the sense I get from reading the mails in the debian-java team they wanna put all their energies in getting openjdk 11 transitioned in Debian as fast as possible. The reason being simple, while Oracle hasn't talked about openjdk apparently but JDK 11 is supposed to be supported for 5 years and the openjdk team is probably thinking along similar lines.  

This is probably the craziest time to do anything on mars-sim till java 11 and openjfx 11 don't become a reality, sometime late October, November 2018 . 

I was also looking at https://github.com/mars-sim/mars-sim/wiki/Setting-Command-Line-Environment-using-Git and it seems that probably 

`mvn clean package install` does not work for Debian as lot of maven stuff is already there. 

```
$ aptitude search libmaven-
p   libmaven-antrun-extended-plugin-java                 - Extended integration between Maven and Ant                    
p   libmaven-antrun-plugin-java                          - Maven AntRun Plugin                                           
p   libmaven-archiver-java                               - Archiver component for Maven                                  
p   libmaven-archiver-java-doc                           - Archiver component for Maven - API documentation              
p   libmaven-artifact-transfer-java                      - Apache Maven Artifact Transfer                                
p   libmaven-assembly-plugin-java                        - Maven Assembly Plugin                                         
p   libmaven-bundle-plugin-java                          - Maven plugin to handle artifact OSGi metadata                 
p   libmaven-clean-plugin-java                           - Maven clean plugin                                            
p   libmaven-common-artifact-filters-java                - Maven Common Artifact Filters                                 
p   libmaven-common-artifact-filters-java-doc            - Documentation for Maven Common Artifact Filters               
p   libmaven-compiler-plugin-java                        - Maven Compiler plugin                                         
p   libmaven-dependency-analyzer-java                    - Maven Dependency Analyzer                                     
p   libmaven-dependency-plugin-java                      - Maven Dependency Plugin                                       
p   libmaven-dependency-tree-java                        - Maven Dependency Tree                                         
p   libmaven-dependency-tree-java-doc                    - Documentation for Maven Dependency Tree                       
p   libmaven-deploy-plugin-java                          - Maven Deploy plugin                                           
p   libmaven-doxia-tools-java                            - utilities for integrating Doxia in Maven                      
p   libmaven-doxia-tools-java-doc                        - Documentation for Maven Doxia Integration Tools               
p   libmaven-ejb-plugin-java                             - Maven EJB Plugin                                              
p   libmaven-enforcer-plugin-java                        - Maven build rule execution framework                          
p   libmaven-exec-plugin-java                            - Exec Maven Plugin (transitional package)                      
p   libmaven-file-management-java                        - Maven File Management API                                     
p   libmaven-file-management-java-doc                    - Documentation for Maven File Management API                   
p   libmaven-filtering-java                              - Maven Filtering                                               
p   libmaven-indexer-java                                - Maven :: Indexer                                              
p   libmaven-install-plugin-java                         - Maven install plugin                                          
p   libmaven-invoker-java                                - Maven Invoker                                                 
p   libmaven-invoker-plugin-java                         - Maven Invoker Plugin                                          
p   libmaven-jar-plugin-java                             - Maven Jar Plugin                                              
p   libmaven-javadoc-plugin-java                         - Maven Javadoc Plugin                                          
p   libmaven-mapping-java                                - Apache Maven Mapping                                          
i A libmaven-parent-java                                 - Maven metadata for Apache Maven itself                        
p   libmaven-plugin-testing-java                         - Maven Plugin Testing                                          
p   libmaven-plugin-testing-java-doc                     - Documentation for Maven Plugin Testing                        
p   libmaven-plugin-tools-java                           - Maven Plugin Tools                                            
p   libmaven-processor-plugin-java                       - Maven plugin to process annotations for Java 6 at compile time
p   libmaven-reporting-api-java                          - Maven Reporting API                                           
p   libmaven-reporting-exec-java                         - Apache Maven Reporting Executor                               
p   libmaven-reporting-impl-java                         - Maven Reporting API Implementation                            
p   libmaven-reporting-impl-java-doc                     - Documentation for Maven Reporting API Implementation          
p   libmaven-repository-builder-java                     - Maven Repository Builder                                      
p   libmaven-repository-builder-java-doc                 - Documentation for Maven Repository Builder                    
i A libmaven-resolver-java                               - Library to handle Java artifact repositories                  
p   libmaven-resolver-transport-http-java                - Library to handle Java artifact repositories (HTTP transport) 
p   libmaven-resources-plugin-java                       - Maven resources plugin                                        
p   libmaven-scm-java                                    - Maven SCM - Common API for SCM operations (Core API)          
p   libmaven-scm-java-doc                                - Maven SCM - Common API for SCM operations (Documentation)     
p   libmaven-scm-providers-java                          - Maven SCM - Common API for SCM operations (Providers)         
p   libmaven-script-interpreter-java                     - Maven Script Interpreter                                      
p   libmaven-shade-plugin-java                           - Maven shade plugin                                            
p   libmaven-shared-incremental-java                     - Maven incremental build utilities                             
p   libmaven-shared-incremental-java-doc                 - Maven incremental build utilities (documentation)             
p   libmaven-shared-io-java                              - Maven API for I/O support                                     
p   libmaven-shared-io-java-doc                          - Documentation for Maven API for I/O support                   
p   libmaven-shared-jar-java                             - Maven JAR Utilities                                           
p   libmaven-shared-jar-java-doc                         - Documentation for Maven JAR Utilities                         
i A libmaven-shared-utils-java                           - Replacement for plexus-utils in Maven                         
p   libmaven-shared-utils-java-doc                       - Replacement for plexus-utils in Maven (documentation)         
p   libmaven-site-plugin-java                            - Maven Site Plugin for generating a site                       
p   libmaven-source-plugin-java                          - Maven Source Plugin                                           
p   libmaven-verifier-java                               - Maven Verifier Component                                      
p   libmaven-verifier-java-doc                           - Documentation for Maven Verifier Component                    
p   libmaven-war-plugin-java                             - Maven WAR Plugin

```

But that's a different discussion altogether.

**Comment by shirishag75** [comment]
@mokun see bugs.debian.org/850921 . So from what Emmanuel has shared and from what I had already guessed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850921#64 the libopenjfx-java version 8 is just a placeholder to be used for faster processing when libopenjfx-java 11 comes in 3-4 months in now. It probably would have a huge diff. but still would be easily reviewed by Debian ftpmasters and then pushed in either experimental or unstable what the maintainer thinks would be best. The idea would then be to see if there are any RC bugs (release-candidate bugs) and if not, have a quick transition and let people try it out on testing before Debian freeze i.e. Feb 2019. 

We anyways can't do anything till default-jdk doesn't move to 11 so the best would be to lie quietly till openjdk does become the default-jdk .

**Comment by mokun** [comment]
@shirishag75 @larsnaesbye, yes it will be too troublesome to maintain two separate branches (one on Java 8, one on Java 9 and beyond). 

As of today, Oracle has Java 8u171/172 and Java 10.0.1 as the general availability release. They no longer advertised Java 9 on their [download page](http://www.oracle.com/technetwork/java/javase/overview/index.html).

Since they have moved on from Java 9 to Java 10, I agree that we are to simply move our codebase to supporting only Java 9 from now on. 

See this [commit](https://github.com/mars-sim/mars-sim/commit/422805877c3e6136d0c7b24e9846682dfe19cca2) for my first shot at module-info.java that I've been removing incompatibilities with Java 9 in the recent builds. 

But as of this moment the master branch is still Java 8 based. To test Java 9, I actually have to change the compiler version from Java 8 to Java 9/10 and back and forth each time.

So in the next build, I'll update some maven dependencies to supporting Java 9/10 only and there will be no going back :) Our codebase will be based on Java 9 and the development environment must have jdk 9/10 installed at the minimum.

Having said that, we do have the choice in compiling mars-sim to two separate binaries-- one will be good for running in Java 8 VM only and one for Java 9/10/11 VM.

**Comment by shirishag75** [comment]
I am just going to wait till java 11 comes in Debian repositories along with a compatible openjfx release before trying any more things. This will take some time.

**Comment by mokun** [comment]
@larsnaesbye @shirishag75 , 

As of r4268, we are reasonably done with converting our master branch to supporting Java 9. Closing this issue for now.

**Comment by shirishag75** [comment]
Hi all, just to update few things, seems Java 11 release is about a month away according to the schedule - 

http://openjdk.java.net/projects/jdk/11/#Schedule 

I do have the latest openjdk-jre that is there is in testing - 

```
$ apt-cache policy openjdk-11-jre
openjdk-11-jre:
  Installed: 11~24-1
  Candidate: 11~24-1
  Version table:
     11~27-1 100
        100 http://deb.debian.org/debian unstable/main amd64 Packages
 *** 11~24-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages


```

**Comment by mokun** [comment]
@shirishag75 , can you run v3.1.0-b1 on the machine that has openjdk/jfx 11 on it ? 

Do you have openjfx 11 installed ?

The gui and headless versions in v3.1.0-b1 are separate binaries and must be downloaded separately, as you know.

**Comment by shirishag75** [comment]
Nope, do not have. I am waiting for the DD's to solve the issues and help them (if possible) if everything is in working order. I do not  want  to risk using a binary or making/compiling openjfx 11 because I don't  know the switches they use for enhanced protection. I will update the bug when I have more news.

**Comment by mokun** [comment]
@shirishag75 , can you open a new ticket for openjdk/jfx 11 support ? Chances are new issues will be uncovered with running mars-sim under openjdk/jfx 11. Thanks!

**Comment by shirishag75** [comment]
just made a new bug-report at https://github.com/mars-sim/mars-sim/issues/74, this is with the headless mode now.

**Comment by mokun** [comment]
Java 9 is being supported since v3.1.0-preview 9. Closing this issue now.
