### ISSUE TITLE
Malfunction not fixed - repairers are sick or cannot find malfunction

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#377]
**Describe the bug**
- one of the 3 types of Malfunction is never finished
- The 3 repairers got stuck at this task and got very sick 

**Expected behavior**
- Should send an interactive alert to the player that the General Repair is not done 
- Should provide options for the player to send more people to fix it and to relieve the previous repairer.

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/126024106-9deeca55-d7cf-44ca-b0fc-2381a464b847.png)

**Desktop (please complete the following information):**
 - build 5954

**Additional context**
```
00-Adir-07:007.906 (Info) Building : [Europa] Solar Photovoltaic Array 30 - A meteorite impact over is imminent.
00-Adir-07:007.906 (Info) Malfunction : Meteorite Impact Damage - Incident #1 - Estimated GENERAL work time: 342.6
00-Adir-07:007.906 (Warning) Malfunction : Meteorite Impact Damage - Incident #1 - Repair requires plastic pipe(x2).
00-Adir-07:007.906 (Warning) MalfunctionManager : [Europa] Solar Photovoltaic Array 30 - Meteorite Impact Damage. Probable Cause : Act of God.
00-Adir-07:007.906 (Info) RepairEVAMalfunction : [Europa] Lenna Pärn was appointed as the chief repairer handling the EVA Repair for 'Meteorite Impact Damage' on Solar Photovoltaic Array 30
00-Adir-07:007.906 (Info) Malfunction : Meteorite Impact Damage - Incident #1 - EVA repair work initiated by Lenna Pärn.
00-Adir-07:007.906 (Info) Malfunction : Meteorite Impact Damage - Incident #1 repairer Lenna Pärn leaving the scene.
00-Adir-07:007.906 (Info) RepairMalfunction : [Europa] Anna De Jong - Was appointed as the chief repairer handling the Emergency work for 'Meteorite Impact Damage' on Solar Photovoltaic Array 30
00-Adir-07:007.906 (Info) RepairMalfunction : [Europa] Sara De Vries - Was appointed as the deputy repairer handling the Emergency work for 'Meteorite Impact Damage' on Solar Photovoltaic Array 30
00-Adir-07:007.906 (Info) RepairEVAMalfunction : [Europa] Oscar Andersen was appointed as the deputy repairer handling the EVA Repair for 'Meteorite Impact Damage' on Solar Photovoltaic Array 30
00-Adir-07:050.285 (Info) RepairMalfunction : [Europa] Andy Hoffmann - Wrapped up the Emergency Repair of 'Meteorite Impact Damage' in Solar Photovoltaic Array 30 (111.6 millisols spent).
00-Adir-07:050.285 (Info) RepairMalfunction : [Europa] Sarah Muller - Wrapped up the Emergency Repair of 'Meteorite Impact Damage' in Solar Photovoltaic Array 30 (112.2 millisols spent).
00-Adir-07:051.323 (Info) RepairMalfunction : [Europa] Anna De Jong - Wrapped up the Emergency Repair of 'Meteorite Impact Damage' in Solar Photovoltaic Array 30 (112.7 millisols spent).
00-Adir-07:051.323 (Info) RepairMalfunction : [Europa] Sara De Vries - Wrapped up the Emergency Repair of 'Meteorite Impact Damage' in Solar Photovoltaic Array 30 (113.3 millisols spent).
00-Adir-07:051.323 (Info) RepairMalfunction : [Europa] Emilia Saar - Was appointed as the chief repairer handling the General work for 'Meteorite Impact Damage' on Solar Photovoltaic Array 30
00-Adir-07:052.500 (Info) RepairMalfunction : [Europa] Anna De Jong - Was appointed as the deputy repairer handling the General work for 'Meteorite Impact Damage' on Solar Photovoltaic Array 30
00-Adir-07:106.286 (Info) Malfunction [x26] : Meteorite Impact Damage - Incident #1 repairer Dimitrios Dimitriadis leaving the scene.
```

**Comment by bevans2000** [comment]
Interesting. The resolution all depends how autonomous we want the simulation to be. The Malfunction logic drops "dead" persons already so I would suggest that this should be extended to people who are below the minimum fitness threshold. Then dropping these would then release a slot that someone else could come along and claim hence keeping the repair going.

**Comment by bevans2000** [comment]
I also managed to reproduce this problem last night on one of my runs. It's a difficult one to reproduce.

**Comment by mokun** [comment]
Hmm somehow I have observed this happened a few rimes in some sim sessions.

How about we create an expert command to add extra fatigue on a repairer and artificially inject a malfunction just to test it?

**Comment by bevans2000** [comment]
Nice idea. Yes that would be useful. It could be a command to adjust the Person physical condition, e.g. thirty, hunger, fatigue.
I'll do it tonight

**Comment by bevans2000** [comment]
Added an extra mode to the health command.

**Comment by mokun** [comment]
In the beginning, Lounge 1 needs 3 types of repairs. 

General Repair is still not done. But the EVA repair isn't done and the Emergency repair isn't done.

Q: Why can't they work on General Repair ?

```
00-Adir-10:329.795 (Warning) RepairMalfunction : [Starcity] Oliver Andersson - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:330.917 (Warning) RepairMalfunction [x6] : [Starcity] Xingrui Xie - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:331.283 (Warning) RepairMalfunction [x6] : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:332.135 (Warning) RepairMalfunction [x2] : [Starcity] Maja Johansson - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:332.549 (Warning) RepairMalfunction [x7] : [Starcity] Xingrui Xie - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:332.722 (Warning) RepairMalfunction [x7] : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:333.656 (Warning) RepairMalfunction [x2] : [Starcity] Maja Johansson - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:334.069 (Warning) RepairMalfunction [x8] : [Starcity] Xingrui Xie - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:334.229 (Warning) RepairMalfunction [x8] : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:334.718 (Info) MakingLifeMultiplanetary : [Starcity] Xingrui Xie - Updating the report of the best practices in resource utilization.
00-Adir-10:335.424 (Warning) RepairMalfunction [x3] : [Starcity] Maja Johansson - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:335.985 (Warning) RepairMalfunction [x8] : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:336.844 (Warning) RepairMalfunction [x4] : [Starcity] Maja Johansson - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:338.373 (Warning) RepairMalfunction [x8] : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:340.981 (Warning) RepairMalfunction : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:341.156 (Warning) RepairMalfunction : [Starcity] Emily Kelly - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:341.156 (Warning) RepairMalfunction [x2] : [Starcity] Maja Johansson - Can not find a Malfunction to work on for Lounge 1
00-Adir-10:341.369 (Info) RoverMission : [New Plymouth Vicinity] Pathfinder II was being disemabarked at New Plymouth.
00-Adir-10:342.459 (Warning) RepairMalfunction [x9] : [Starcity] Mishka Roy - Can not find a Malfunction to work on for Lounge 1
```

**Comment by mokun** [comment]
Only one of them are sick. The rest of them have good health.

![image](https://user-images.githubusercontent.com/1168584/127728724-f8e57b1e-c732-4376-af33-36204ab6a34e.png)

**Comment by mokun** [comment]
General Repair is a strange category.

Can we simply have : 
1. Emergency EVA repair
2. Emergency non-EVA repair
1. non-Emergency EVA repair
2. non-Emergency non-EVA repair

**Comment by mokun** [comment]
@bevans2000 ,

In this case, no one is repairing the *Large Sabatier Processor 2*.

It dawns on me that they can't because *Large Sabatier Processor 2* is not a habitable building and no one can enter it.

So we should fix it in such a way that any non-habitable building won't generate General Repair.

We need to be a little more careful in considering how a type of repairs is associated with a malfunction. 

![image](https://user-images.githubusercontent.com/1168584/127754207-65b5d73f-5dea-4d89-8dd7-b02234e7e151.png)

**Comment by bevans2000** [comment]
> General Repair is a strange category.
> 
> Can we simply have :
> 
> 1. Emergency EVA repair
> 2. Emergency non-EVA repair
> 3. non-Emergency EVA repair
> 4. non-Emergency non-EVA repair

Sorry been really busy this weekend. OK, this seems clearer. So a Malfunction could involve 4 work types instead of the existing 3. The changes I did a while ago should make it easier to implement this. But I still think there might be a problem with Repairers "forgetting" about their jobs. I think the Task probability needs tweaking such that once you become a repairer the probability is raised to get the job completed. Also "Reading" has too high a Task probability.

**Comment by mokun** [comment]
@bevans2000 

Guess this one is still not resolved. 

Just moved this to 3.3.x milestone

**Comment by bevans2000** [comment]
Yes I've not had time to look at this.

**Comment by mokun** [comment]
We'll need to find a way to make it work.

```
00-Bora-21:257.897 (Warning) RepairMalfunction [x5] : [Schiaparelli Point] Rik Declercq - Can not find a Malfunction to work on for Laboratory 1
00-Bora-21:257.897 (Warning) RepairMalfunction [x3] : [Schiaparelli Point] Ray Bradbury - Can not find a Malfunction to work on for Laboratory 1
00-Bora-21:257.897 (Warning) RepairMalfunction [x5] : [Schiaparelli Point] Natalia Szymański - Can not find a Malfunction to work on for Laboratory 1
00-Bora-21:257.897 (Warning) RepairMalfunction [x5] : [Schiaparelli Point] Judith Morris - Can not find a Malfunction to work on for Laboratory 1
00-Bora-21:257.897 (Warning) RepairMalfunction [x5] : [Schiaparelli Point] Conor Ryan - Can not find a Malfunction to work on for Laboratory 1
00-Bora-21:257.897 (Warning) RepairMalfunction [x5] : [Schiaparelli Point] Tommaso Colombo - Can not find a Malfunction to work on for Laboratory 1
00-Bora-21:257.897 (Warning) RepairMalfunction : [Schiaparelli Point] Hugo Andersson - Can not find a Malfunction to work on for Laboratory 1
```

**Comment by bevans2000** [comment]
I will look at this next

**Comment by bevans2000** [comment]
I've made a start on this and decided to change the repair work so General & Emergency each have the potential to be inside and Eva activities. This now gives a total of 4 repair efforts.

**Comment by mokun** [comment]
> General & Emergency each have the potential to be inside and Eva activities. This now gives a total of 4 repair efforts.

What's the definition of a General repair ?

**Comment by mokun** [comment]
> What should be the definition of a _General_ repair ?

Guess we can say it simply means *non-emergency*. So it's an abstract concept

May be we should have a DEGREE OF EMERGENCY from 1 to 100, where 100 is extremely life-threatening.

Then we would reduce it to having just two kinds of repairs : indoor vs. EVA

**Comment by mokun** [comment]
> So we should fix it in such a way that any non-habitable building won't generate General Repair.

And this is important since no one can walk inside a *non-habitable* building to do an indoor repair.

**Comment by bevans2000** [comment]
> > What should be the definition of a _General_ repair ?
> 
> Guess we can say it simply means _non-emergency_. So it's an abstract concept
> 
> May be we should have a DEGREE OF EMERGENCY from 1 to 100, where 100 is extremely life-threatening, for each repair.
> 
> Then we would reduce it to having just two kinds of repairs : indoor vs. EVA

Yes we could do but I think that is over complicated. During the emergency repair the Malfunction is impacting on the resources, e.g. losing oxygen. General is non emergency as you say.

**Comment by bevans2000** [comment]
> > So we should fix it in such a way that any non-habitable building won't generate General Repair.
> 
> And this is important since no one can walk inside a _non-habitable_ building to do an indoor repair.

That's fine because a Malfunction in a non habitable building could have an Emergency EVA phase and a General EVA phase. Probably could add a check to make sure no Inside work is required for a non inhabitable building.

**Comment by mokun** [comment]
> > > What should be the definition of a _General_ repair ?
> > 
> > 
> > Guess we can say it simply means _non-emergency_. So it's an abstract concept
> > May be we should have a DEGREE OF EMERGENCY from 1 to 100, where 100 is extremely life-threatening, for each repair.
> > Then we would reduce it to having just two kinds of repairs : indoor vs. EVA
> 
> Yes we could do but I think that is over complicated.

I thought it makes it simple and more maintainable by reducing the number of classes and remove the artificial boundary. 

 > During the emergency repair the Malfunction is impacting on the resources, e.g. losing oxygen.

In reality if it puncture the wall, then it's losing and leaking air, like right now they said in the international space station.

Then there are cases for affecting specific items such as gas canisters that stores oxygen, methane.

So those methods that account for losing gases are not good and should be applied for building or vehicle chamber wall or EVA suit puncture only , right?

**Comment by bevans2000** [comment]
Malfunctions already have severity so that could dictate the Emergency. `MalfunctionMeta` already defines if resources are affected so they would come into play fir the duration of the malfunction. Maybe we could prorate the effects on amount of repair remaining, e.g. if 100% is still left then the full effect on resources but only 50% left then half the effect, 25% left then just a quarter etc etc.
Having just an EVA and Inside repair work certainly simplifies it. I'll do that. Might need a bit of tweaking of values in malfunction.xml but will be simplier.

**Comment by bevans2000** [comment]
@mokun Found a killer bug whilst making these changes in the `Settlement.getAirlock` method. The searching of potential airlock building is using the wrong iterator. It is uses the iterator from a previous `i` and not the new `ii` but the former has already been fully used. The inside of the loop is NEVER executed and this method always return null if there is more than one available Airlock. 
This could explain a lot of weird behaviour we see. Just shows the danger in using the old `Iterator` approach.
```		
		double leastDistance = Double.MAX_VALUE;

		Iterator<Building> ii = selectedPool.iterator();
		while (i.hasNext()) {
			Building building = ii.next();
			if (buildingConnectorManager.hasValidPath(currentBuilding, building)) {
```

**Comment by mokun** [comment]
> Maybe we could prorate the effects on amount of repair remaining, e.g. if 100% is still left then the full effect on resources but only 50% left then half the effect, 25% left then just a quarter etc etc.

Sure. it should taper off and not leaking the gas at a linear rate. Is that what you essentially mean ?

**Comment by mokun** [comment]
> Just shows the danger in using the old `Iterator` approach.

wow. thanks for spotting it.

**Comment by mokun** [comment]
There are also other potential tweaks regarding choosing which airlock to go out and which one to come back in. 

Currently, settlers aren't really making intelligent choice because we don't have a set of rules in place as to how to choose an airlock.

**Comment by bevans2000** [comment]
> > Maybe we could prorate the effects on amount of repair remaining, e.g. if 100% is still left then the full effect on resources but only 50% left then half the effect, 25% left then just a quarter etc etc.
> 
> Sure. it should taper off and not leaking the gas at a linear rate. Is that what you essentially mean ?

Yes exactly.

**Comment by bevans2000** [comment]
> There are also other potential tweaks regarding choosing which airlock to go out and which one to come back in.
> 
> Currently, settlers aren't really making intelligent choice because we don't have a set of rules in place as to how to choose an airlock.

At the moment on my branch everyone now wants to fix the EVA repair because they can all now find an airlock. Need to resolve that before completing the work.

**Comment by mokun** [comment]
> everyone now wants to fix the EVA repair because they can all now find an airlock

I can think of at least 3 selection criteria that determines the priority :

1. those having the JOB of being a mechanic (then engineer)
2. those having the highest mechanics SKILL
3. those having the ROLE of safety specialist
 
Anything else we may consider ?

**Comment by bevans2000** [comment]
It's more to do with how the MetaTask is not considering the free slots when scoring the probability factor. It's a bug in the changes I'm making but not found it yet. Once enough people are assigned then no more should get an option but it's not working. I'm sure it's easy to fix just need some free time.

**Comment by mokun** [comment]
What do you see is the quickest way to add a history of repair/maintenance for each building ?

Right now we use malfunction.xml to define different types of malfunction for a given system scope. 

The complication is the *system scope* is not the same as the building itself and is not the same as a building function. 
Rather, the system scope is sort of a combination of both.

**Comment by bevans2000** [comment]
So I think you're discussing 2 things here:
1.  A means to add history of Maintenance and Failures. I see this as a function of the `Malfunctionable` interface or the `MalfunctionManager`. Essentially Maintenance and Malfunctions are tightly coupled; without maintenance malfunctions are more likely. I feel generally we have a lack of Maintenance in the simulations or it occurs too infrequently.
2. I think the current use of 'system' to identify malfunctions works OK. Each Function has the potential to have specific malfunctions and also the physical Building can have specific malfunctions. I don't see a problem here unless I've missed something.

As to this issue; I've done what I think are all the changes but just need to get time for some tests with some longer simulation runs

**Comment by mokun** [comment]
There's something not right.

```
00-Adir-14:264.433 (Warning) RepairInsideMalfunction [x3] : [Starcity] Chloe Lapointe - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:266.433 (Warning) RepairInsideMalfunction [x3] : [Starcity] Chloe Lapointe - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:266.682 (Warning) RepairInsideMalfunction : [Starcity] Charlotte Gagne - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:267.432 (Info) Malfunction [x128] : Meteorite Impact Damage - Incident #1 - EVA repair work initiated by Taiga Ito.
00-Adir-14:267.432 (Info) Malfunction [x128] : Meteorite Impact Damage - Incident #1 repairer Taiga Ito leaving the scene.
00-Adir-14:267.941 (Warning) RepairInsideMalfunction [x3] : [Starcity] Chloe Lapointe - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:268.474 (Warning) RepairInsideMalfunction [x2] : [Starcity] Charlotte Gagne - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:268.779 (Info) MissionAgenda [x3] : [Zvezda] Olga Egorov - Health Hazards: Updating the report of the various health hazards for human beings on Mars.
00-Adir-14:269.189 (Info) VehicleMission [x4] : [Europa] David Moser - 2. Delivery #8 has an estimated remaining distance of 1281.0 km.
00-Adir-14:269.931 (Warning) RepairInsideMalfunction : [Starcity] Diane Richardson - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:270.644 (Warning) RepairInsideMalfunction [x2] : [Starcity] Charlotte Gagne - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:270.810 (Warning) RepairInsideMalfunction [x2] : [Starcity] Maika Dube - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:273.033 (Warning) RepairInsideMalfunction : [Starcity] Diane Richardson - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:273.033 (Warning) RepairInsideMalfunction : [Starcity] Charlotte Gagne - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:275.085 (Info) MissionAgenda [x6] : [New Plymouth] Barbara Allen - Finding Life: Updating the report of the oxygen content in the soil samples.
00-Adir-14:275.085 (Warning) RepairInsideMalfunction [x2] : [Starcity] Karen Ramirez - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:275.085 (Warning) RepairInsideMalfunction [x3] : [Starcity] Chloe Lapointe - Can not find a Malfunction to work on for ERV Base 3
00-Adir-14:275.731 (Warning) RepairInsideMalfunction : [Starcity] Charlotte Gagne - Can not find a Malfunction to work on for ERV Base 3
```

**Comment by bevans2000** [comment]
Might be because there are multiple active Malfunction. I will have a look

**Comment by bevans2000** [comment]
The problem is when there are multiple active Malfunctions; sometimes the repairer chooses a Malfunction where there are no available slots. The fix changes how a worker selects the Malfunction to work on; not just the most serious but there must be available slots.
The side effect is Robots can now work on Inisde repairs.
There is still a problem when a Malfunction needs Inside work but has no LifeSupport. Workers can start repairing the inside problem even though there is no "inside".

**Comment by mokun** [comment]
@bevans2000, 

Good that on your latest commit, you enabled robots to do repairs

If it makes sense to program robots to do so, then my next question is 

- how should we model a settler to program and test robots for certain repetitive tasks ?
- it would be interesting to create a new career path such as "Computer Science" and add new skillset such as "Software Engineering"

**Comment by bevans2000** [comment]
Interesting idea. Seems quite advanced compared to the current simulation. 

When testing this I managed to create grid lock in the airlocks with them being full but no one able to get out. I had multiple EVA repairs In progress.

**Comment by mokun** [comment]
> grid lock in the airlocks with them being full but no one able to get out. I had multiple EVA repairs In progress.

Yes I've just seen them getting stuck in the airlock when they are supposed to go out to do EVA repairs. 

Before the repair surfaces, there is no airlock grid lock.

So why would they get stuck in the airlock ? 

Also, I don't see them walking ALL THE WAY to the vicinity of building or vehicle that need EVA repair. Do you ?

**Comment by bevans2000** [comment]
I've seen the gridlock before if there is a lot of EVA traffic. Seems when the airlock is full, they get stuck.  Haven't noticed the walking.

**Comment by bevans2000** [comment]
I checked and in the RepairEVAMalfunction the phase is set to WALK_TO_OUTSIDE_SITE so people should walk a path to the external place. None of that has been changed.

**Comment by mokun** [comment]
I just found out why in some cases a EVA repair got mixed in with starting a `RepairInsideMalfunction` task
