### ISSUE TITLE
Default size on Main window too large

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#378]
**Describe the bug**
The way the main winnow is sized is troublesome. On my laptop the screen is smaller than the default so each time I have to change the screen resolution via the console if I want the full UI to be visible. The saved size in the ui defaults is ignored in the current code it always goes with what is selected in the console.

**Expected behavior**
I would like to drop the Change Screen Resolution feature altogether. Instead by default the main window will start with the size of the actual screen. Also allow the user to resize the screen to their desired preference; this is then saved in the ui defaults. On next start-up the previous screen size is restored.

**Comment by mokun** [comment]
@bevans2000 ,

What's your laptop max screen resolution ?

**Comment by mokun** [comment]
Guess most newer laptops these days are using 1920 x 1080. 

But some of the older ones may still be 1366 x 769.

I've been told that Java Swing's screen management is weird. Java 2D full screen mode is hard to implement.

In JavaFX, they make it much easier to have full screen mode vs. window mode.

That being the case, do you want to maximize the screen size to whatever the screen allows at the start of the sim ? 

So it will have a window frame, not the borderless mode, right ?  

Then my question is, when the player clicks on the top right hand button to switch off the full screen window frame, what default resolution should it be ?  

May be it should be whatever next smaller resolution ?!

**Comment by mokun** [comment]
Or the alternative is to make the MainWindow a resizable frame. 

See https://www.javacodex.com/More-Examples/2/7

This way, player can adjust it to whatever size he wants in real-time.
