### ISSUE TITLE
preview 6 not launching/datetime ParseException

### ISSUE THREAD

**Issue by Musickiller** [mars-sim/mars-sim#38]
F:\Games\MarsSim>java -jar mars-sim-3.1.0-p6.jar 1
Command: java -Djava.util.logging.config.file=logging.properties -cp .;*;jars\*
org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx512m -new
OUTPUT>23.03.2017 13:39:31(INFO) main.javafx.MarsProjectFX Mars Simulation Proje
ct v3.1.0 - Build 3899 - 64-bit 1.8.0_112 - 2 CPU threads
OUTPUT>23.03.2017 13:39:32(INFO) main.javafx.MarsProjectFX Starting a new sim in
 GUI mode in Windows 7
OUTPUT>23.03.2017 13:39:35(INFO) ui.javafx.mainmenu.SpinningGlobe JavaFX 3D feat
ures supported
OUTPUT>Missing a comboBox selection in Crew Editor!
OUTPUT>Missing a comboBox selection in Crew Editor!
OUTPUT>Missing a comboBox selection in Crew Editor!
OUTPUT>Missing a comboBox selection in Crew Editor!
OUTPUT>Missing a comboBox selection in Crew Editor!
OUTPUT>Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: ja
va.text.ParseException: Unparseable date: "2043-Sep-30 00:00:00"
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:79)
OUTPUT> at org.mars_sim.msp.core.time.MasterClock.<init>(MasterClock.java:130)
OUTPUT> at org.mars_sim.msp.core.Simulation.initializeIntransientData(Simulation
.java:324)
OUTPUT> at org.mars_sim.msp.core.Simulation.createNewSimulation(Simulation.java:
281)
OUTPUT> at org.mars_sim.msp.ui.javafx.config.ScenarioConfigEditorFX$SimulationTa
sk.run(ScenarioConfigEditorFX.java:575)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
OUTPUT> at java.lang.Thread.run(Unknown Source)
OUTPUT>Caused by: java.text.ParseException: Unparseable date: "2043-Sep-30 00:00
:00"
OUTPUT> at java.text.DateFormat.parse(Unknown Source)
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:77)
OUTPUT> ... 7 more

My comments:
I also had the "Unparseable date" error in 5'th preview. I have managed to launch 4'th once. As of now - I can not launch any version.
"OUTPUT>Missing a comboBox selection in Crew Editor!" happened when I opened crew sellection menu and changed from "alpha b." to "Sc. Point" several times.

**Comment by mokun** [comment]
Hi Musickiller,

> I also had the "Unparseable date" error in 5'th preview. I have managed to launch 4'th once. As of now - I can not launch any version.

It sounds like you can load the Configuration Editor on both p4 and p5 but cannot proceed further.

> OUTPUT>Missing a comboBox selection in Crew Editor!" happened when I opened crew sellection menu and changed from "alpha b." to "Sc. Point" several times.

Does it mean that mars-sim can still start properly if you begin a new sim with the two default settlements UNCHANGED ?

"2043-Sep-30 00:00:00" is the default Earth start time for mars-sim. 

I use  [GregorianCalendar](https://docs.oracle.com/javase/8/docs/api/java/util/GregorianCalendar.html)
and [SimpleDateFormat](http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) class from Java API to parse the String "2043-Sep-30 00:00:00" found in simulation.xml. 

It may have to do with localization of your Windows 7 machine. 

I'll look into it further.

**Comment by Musickiller** [comment]
Hi.
Thanks for a reply.
Yes. Editor is working.
No, I can not launch with default settings too, though I usually delete Alpha Base when I start the Sim.

Yes, it *may* be a localisation issue. I have Russian locale on my notebook (there the problem persists). But I thought I had English on my PC. Can't check it right away - it's 4:44 here and I have plans for tomorrow. Sorry. I'll try to change locale to English and launch again as soon as I have time for that.

However, it seem wise to use some numeral-only format for all time/date stuff all across the sim and to use readable format only when you need to display something. But I'm sure you knew that.

If you think you have fixed the issue - can you please send the binary file (or update the one on SourceForge)? I actually only wanted to see what's new, no serious compiling, contributing to anyone's projects... But bug-hunting is something I can never escape. So if you compile the jar anyway - I would be most glad to test it on my machines.

Regards,
MK.

**Comment by mokun** [comment]
I've just made some change in [r3901](https://github.com/mars-sim/mars-sim/commit/a265f0a5934d493b7c6142acb9090233f18b7383) to make use of ZonedDateTime instead of GregorianCalendar.

GregorianCalendar is from old Java API while ZonedDateTime is a new Java 8 feature and should be more fault tolerant when it comes to determining time zone and different language localizations. 

Also, I wonder if it happens only in windows and/or linux and/or MacOS in another localized language.

@shirishag75, do you mind testing v3.1.0-p6 on one of your localized machine to see if you run into this ParseException below ?

> OUTPUT>Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: ja
va.text.ParseException: Unparseable date: "2043-Sep-30 00:00:00"

**Comment by mokun** [comment]
@Musickiller and @shirishag75, please do try out [3902.jar.zip](https://www.dropbox.com/s/o85py1ps90thfxp/3902.zip?dl=0) in command line to see if the ParseException persist

**Comment by Musickiller** [comment]
> I've just made some change in r3901
Yes, I've read that. Just didn't have time to test then.

> please do try out 3902.jar.zip
Right away.

By the way, the locale of my PC is English. Strange.

**Comment by Musickiller** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

F:\Games\MarsSim>java -jar 3902.jar 1
Command: java -Djava.util.logging.config.file=logging.properties -cp .;*;jars\*
org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx512m -new
OUTPUT>26.03.2017 16:39:11(INFO) main.javafx.MarsProjectFX Mars Simulation Proje
ct v3.1.0 - Build 3902 - 64-bit 1.8.0_112 - 2 CPU threads
OUTPUT>26.03.2017 16:39:11(INFO) main.javafx.MarsProjectFX Starting a new sim in
 GUI mode in Windows 7
OUTPUT>26.03.2017 16:39:14(INFO) ui.javafx.mainmenu.SpinningGlobe JavaFX 3D feat
ures supported
OUTPUT>Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: ja
va.text.ParseException: Unparseable date: "2043-Sep-30 00:00:00"
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:84)
OUTPUT> at org.mars_sim.msp.core.time.MasterClock.<init>(MasterClock.java:130)
OUTPUT> at org.mars_sim.msp.core.Simulation.initializeIntransientData(Simulation
.java:324)
OUTPUT> at org.mars_sim.msp.core.Simulation.createNewSimulation(Simulation.java:
281)
OUTPUT> at org.mars_sim.msp.ui.javafx.config.ScenarioConfigEditorFX$SimulationTa
sk.run(ScenarioConfigEditorFX.java:599)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
OUTPUT> at java.lang.Thread.run(Unknown Source)
OUTPUT>Caused by: java.text.ParseException: Unparseable date: "2043-Sep-30 00:00
:00"
OUTPUT> at java.text.DateFormat.parse(Unknown Source)
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:82)
OUTPUT> ... 7 more

**Comment by Musickiller** [comment]
By the way, on Linux it works. With many artifacts, that may be caused by an unsupported version of Java or OpenJFX, but at least it runs. I'm scared to launch Preview 5.. Gladly I don't have to.

**Comment by Musickiller** [comment]
Good morning.. or whatever it is.
I had to reinstall Windows on my PC and ready to test whatever version you think I should test. As a reminder, I could launch preview 4 before I have launched any other version. But I think it's anyway more logical to try the latest, in case it's 4'th issue.

**Comment by mokun** [comment]
Does your Windows PC have Multilingual User Interface (MUI) ?
see https://superuser.com/questions/398905/russian-language-in-windows-7#398235

I'm wondering if one use Vistalizator to override the limit of one MUI language on non-Ultimate and non-Enterprise editions of Windows 7, it may also create confusing situation with the system locale as interpreted by Java.

How would Java interpret the system locale in these cases ?

1. Russian version of Window 7 with display language set to English
2. English version Window 7 with display language set to Russian
3. English version Window 7 with display language set to Russian with MUI installed

**Comment by mokun** [comment]
In EarthClock, I define one of the instances of SimpleDateFormat as follows: 

`f2 = new SimpleDateFormat("yyyy-MMM-dd HH:mm:ss");`

Java documentation saids this practically means :
`f2 = new SimpleDateFormat("yyyy-MMM-dd HH:mm:ss", Locale.getDefault(Locale.Category.FORMAT));`

Now, I'm going to change it to : 
`f2 = new SimpleDateFormat("yyyy-MMM-dd HH:mm:ss", Locale.US);`

**Comment by mokun** [comment]
@Musickiller, can you unzip the file below and run the following command

`java -jar LocaleDemo.jar`

[LocaleDemo.zip](https://github.com/mars-sim/mars-sim/files/873241/LocaleDemo.zip)

I need to find out what the output is when you run the jarfile.

To me, it's 

> My locale is en_US

Inside LocaleDemo.java, I simply use Locale.getDefault(Locale.Category.FORMAT) to obtain what your system locale would output.

```
import java.util.Locale;
public class LocaleDemo {
	public LocaleDemo() {
		System.out.println("My locale is " + Locale.getDefault(Locale.Category.FORMAT));
		// "My locale is en_US"
	}
    public static void main(String[] args) {
    	new LocaleDemo();
    }
}
```

**Comment by Musickiller** [comment]
Yes, it is ru_RU. I have remembered it this day, that I have selected that locale at the begining of installation. The only thing I change later is a language pack (which I didn't change on my PC last time).

May be you can use this code to ID user's locale and transform dates.. if there isn't a better way =)

Still I don't get why I could launch preview 4 at elast once on both machines o_O

**Comment by Musickiller** [comment]
Yes, I have the interface. Of course I have the Ultimate version xD Only loosers use Home versions =)
And I'm gonna change langpack as soon as it is downloaded.

**Comment by mokun** [comment]
> Still I don't get why I could launch preview 4 at elast once on both machines o_O

Here's what happen. We finally nail this down here. The newly defined date-time stamp on r3831 (on sourceforge svn on 2017-01-03) in simulation.xml was the main culprit.

> 2017-01-03 ... Change the format of Earth/Mars dates. 
> # CHANGES/IMPROVEMENTS
> 2. Change date time format.
> - rework the format of earth-start-date-time (from "09/30/2043 00:00:00" to "2043-Sep-30 00:00:00") 
> - rework the format of mars-start-date-time in simulation.xml (from "15-Adir-01:000.000" to "15-Adir-01 000.000")

simulation.xml up until and including r3830,  

```
		<!-- Earth start date/time -->
		<!-- "MM/dd/yyyy hh:mm:ss" format -->
		<!-- Default: 09/30/2043 00:00:00 -->
		<!-- Note that changing this date to another value is currently unsupported -->		
		<earth-start-date-time value="09/30/2043 00:00:00" />

```

simulation.xml beginning r3831,

```
		<!-- Earth start date/time -->
		<!-- "yyyy-MMM-dd hh:mm:ss" format -->
		<!-- Default: 2043-Sep-30 00:00:00 -->
		<!-- Note that changing this date to another value is currently unsupported -->
		<earth-start-date-time value="2043-Sep-30 00:00:00" />
```

Note that preview-4 was released on 2016-12-05 while preview-5 was on 2017-01-10. 

As you can see, the change was made on 2017-01-03. Therefore starting preview-5, it is affected.

Before r3831, it doesn't matter what locale your machine is having. Beginning r3831, it matters.

So i'll need to make it NOT sensitive to user's system locale somehow.

**Comment by Musickiller** [comment]
Can you just make a hand-made function to parse dates? That would make it locale independant for sure =D

> Another strange thing is that my Arch is ru_RU too. 

I should run that .jar you sent here on Arch too. Just in case it is not Russian somehow o_O

**Comment by mokun** [comment]
Please try [3903.zip](https://www.dropbox.com/s/wjwi1frh0vkmamc/3903.zip?dl=0).

I default the date-time stamp in mars-sim to US Locale, instead of checking for your system's locale.

In future, I'll rework the core engine and simulation.xml to accept other system locales. 

I suppose the java method Locale.getDefault(Locale.Category.FORMAT) works differently on a windows PC vs. a linux PC. 

btw, is your computer's bios using Russian or English ? I wonder if it would affect the result of the java method Locale.getDefault(Locale.Category.FORMAT) as well.

**Comment by Musickiller** [comment]
> Please try 3903.zip.

Right away. Have you considered making a shared folder where you can just put new builds for testing? Smth I saw at Cataclysm DDA.

> btw, is your computer's bios using Russian or English ?

Never seen Russian BIOS.. ever. O_O

**Comment by Musickiller** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\Games\MarsSim>java -jar 3903.jar 2
Command: java -Djava.util.logging.config.file=logging.properties -cp .;*;jars\*
org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx768m -new
OUTPUT>28.03.2017 4:05:19(INFO) main.javafx.MarsProjectFX Mars Simulation Projec
t v3.1.0 - Build 3902 - 64-bit 1.8.0_121 - 2 CPU threads
OUTPUT>28.03.2017 4:05:20(INFO) main.javafx.MarsProjectFX Starting a new sim in
GUI mode in Windows 7
OUTPUT>28.03.2017 4:05:24(INFO) ui.javafx.mainmenu.SpinningGlobe JavaFX 3D featu
res supported
OUTPUT>Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: ja
va.text.ParseException: Unparseable date: "2043-Sep-30 00:00:00"
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:84)
OUTPUT> at org.mars_sim.msp.core.time.MasterClock.<init>(MasterClock.java:130)
OUTPUT> at org.mars_sim.msp.core.Simulation.initializeIntransientData(Simulation
.java:324)
OUTPUT> at org.mars_sim.msp.core.Simulation.createNewSimulation(Simulation.java:
281)
OUTPUT> at org.mars_sim.msp.ui.javafx.config.ScenarioConfigEditorFX$SimulationTa
sk.run(ScenarioConfigEditorFX.java:599)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
OUTPUT> at java.lang.Thread.run(Unknown Source)
OUTPUT>Caused by: java.text.ParseException: Unparseable date: "2043-Sep-30 00:00
:00"
OUTPUT> at java.text.DateFormat.parse(Unknown Source)
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:82)
OUTPUT> ... 7 more

**Comment by Musickiller** [comment]
OK, no, I lied. I'm not asleep yet. I've managed to launch the Sim by altering date/time format:
https://yadi.sk/i/AORCs3Wv3GQDej
(Sorry, I've changed display language to Russian just to check if that affects the Sim any way (no, it's not).

But I can't live with 12 hour format and I hate this illogical month/date/year setup.

So I can launch the Sim, but I have to change "Format" setting before and after I play.

**Comment by Musickiller** [comment]
Do you  know what's also funny? I have saved the sim and launched it again under Russian setting:

```E:\Games\MarsSim>java -jar 3903.jar 3
Command: java -Djava.util.logging.config.file=logging.properties -cp .;*;jars\*
org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx1024m -new
OUTPUT>28.03.2017 4:30:48(INFO) main.javafx.MarsProjectFX Mars Simulation Projec
t v3.1.0 - Build 3902 - 64-bit 1.8.0_121 - 2 CPU threads
OUTPUT>28.03.2017 4:30:48(INFO) main.javafx.MarsProjectFX Starting a new sim in
GUI mode in Windows 7
OUTPUT>28.03.2017 4:30:49(INFO) ui.javafx.mainmenu.SpinningGlobe JavaFX 3D featu
res supported
OUTPUT>Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: ja
va.text.ParseException: Unparseable date: "2043-Sep-30 00:00:00"
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:84)
OUTPUT> at org.mars_sim.msp.core.time.MasterClock.<init>(MasterClock.java:130)
OUTPUT> at org.mars_sim.msp.core.Simulation.initializeIntransientData(Simulation
.java:324)
OUTPUT> at org.mars_sim.msp.core.Simulation.createNewSimulation(Simulation.java:
281)
OUTPUT> at org.mars_sim.msp.ui.javafx.mainmenu.MainMenu$LoadSimulationTask.run(M
ainMenu.java:455)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
OUTPUT> at java.lang.Thread.run(Unknown Source)
OUTPUT>Caused by: java.text.ParseException: Unparseable date: "2043-Sep-30 00:00
:00"
OUTPUT> at java.text.DateFormat.parse(Unknown Source)
OUTPUT> at org.mars_sim.msp.core.time.EarthClock.<init>(EarthClock.java:82)
OUTPUT> ... 7 more
```

I mean, look, "2043-Sep-30 00:00:00" is the date when everything starts, and not the current date. Why would it try to parse that date at all?

**Comment by mokun** [comment]
Can you run this [LocaleDemo.zip](https://github.com/mars-sim/mars-sim/files/874527/LocaleDemo.zip) and copy and paste the output ?

In my machine, it shows : 

> My locale is en_US - English (United States), United States
> 
> 123456.78099 --> 123,456.78
>     567890.0 --> 567,890.00
> 
>   Timezone offset is -8
>        DST offset is 1
> Local time is UTC -7:00
> 
> Start date/time for mars-sim
>           Default : 2043-Sep-30 00:00:00
>               Now : Tue Sep 29 17:00:00 PDT 2043
>

**Comment by mokun** [comment]
Do by all means try out [3904.7z](https://www.dropbox.com/s/23ou4cdpue8xpc5/3904.7z?dl=0).

Note: I use 7zip to compress the jar. It's better than zip, saving me ~ 1MB.

**Comment by Musickiller** [comment]
> Can you run this LocaleDemo.zip and copy and paste the output to me ?

C:\Users\MK\Desktop>java -jar LocaleDemo.jar
My locale is en_US - английский (Соединенные Штаты), Соединенные Штаты

123456.78099 --> 123,456.78
    567890.0 --> 567,890.00

  Timezone offset is 3
       DST offset is 0
Local time is UTC 3:00

Start date/time for mars-sim
          Default : 2043-Sep-30 00:00:00
              Now : Wed Sep 30 03:00:00 MSK 2043

Wait.. that's not right o_O The locale is set to Russian now. Everything is set to Russian now! But your app said English...

**Comment by Musickiller** [comment]
> Do by all means try out 3904.7z.

It haz worked!!!

**Comment by mokun** [comment]
> I can't order to manufacture anything. Not in the main hub, and not in the workshop. 

That's strange. Manufacturing works in my machine.

At the start of the sim, it has to compute what manufacturing processes are available by looking at the required inputs (oxygen, aluminum, etc.)

Next, it will look at the Material Science skill of the Makerbots and/or Technicians. If they are at level 1, it will remove any processes that require skills above level 1...

> I will start a new issue if you say that it's a problem (may be I'm just doing something wrong). (or you can do that yourself if I won't be here)

Do you mind documenting it and filing it as an separate issue if it continues ?

Also look at what Makerbots do. Sometimes they have nothing to do and await instructions. 

In future we'll refine what more unique tasks Makerbots are allowed to do based on their type and even allow users to "program" Makerbots.

**Comment by mokun** [comment]
> My locale is en_US - английский (Соединенные Штаты), Соединенные Штаты

My fault I should presented things a little more clearly.

I meant to first print a user's system locale and then set it to Locale.US and print out the 2nd result.

**Comment by Musickiller** [comment]
Sorry for my mistake with versions, folders and java cache.. Here is a log of new errors (but the sim is working on Russian date/time format setting (hurrraaaaay!)

[log.txt](https://github.com/mars-sim/mars-sim/files/880184/log.txt)

**Comment by mokun** [comment]
Alright. looks like I should just stick with "numerical" month instead of English month to avoid having to interpret the language locale.

**Comment by Musickiller** [comment]
I'm afraid it might be not as simple as that: there are still "31.03.2017 14:13" and "03\31\17 2:13PM"... Let's hope it's not exactly the problem that there is.

**Comment by mokun** [comment]
Question : do you mean what if user decides to change windows OS's date/time format to "31.03.2017 14:13" or "03\31\17 2:13PM" ?

It shouldn't affect the code since the code didn't ask for what kind of datetime format the machine is using. Rather, it was trying to create its own format for use in mars-sim with this line below : 
`cal.setTime(f2.parse(fullDateTimeString));
`

Sorry for the mess. The US/UK English month name seems to be at least partially responsible for our trouble. I've just switched back to using numeric month. Do tell me if the issue still exists in your particular system locale.

**Comment by mokun** [comment]
see if [3927.jar.z](https://www.dropbox.com/s/9ilhvjpjlomie26/3927.jar.7z?dl=0) works.

**Comment by Musickiller** [comment]
sorry. too busy now. as I told you, I have too much on my hands right now.

**Comment by miled** [comment]
I had a similar issue on a Windows 10 in French where simulator gets stuck on spinner for ever. I tried 3927.jar.z and it worked at first but then crashed with OutOfMemoryError exceptions once I got to Map tab.

FWIW, these are the error logs I got: 
https://gist.github.com/miled/16ddf9771d1fceae4151dabf855890e6

**Comment by mokun** [comment]
@miled, do you have 4+ GB memory in your machine ? I'm very curious about that OutOfMemoryError exceptions and wonder where it came from. Does it occur everytime you run 3927.jar ? Do you have another computer at home to try ?

**Comment by miled** [comment]
I've 8G. And no, it doesn't occur any more now that I downloaded jdk-8u121 and compiled the source. My guess, the java version I had before was out dated or something. 

Anyway, this a screenshot of 3927.jar running and everything appears nominal: https://i.imgur.com/7XW3VNz.png

**Comment by miled** [comment]
I used maven to compile it from command Iine. I'm not very familiar with java devs, I just followed your build instructions.

`java -jar 3927.jar 4` works fine.

**Comment by mokun** [comment]
@miled, appreciate for testing that in your machine. 

Do by all means feel free to comment.

Let me know if you want to be a part of the team to contribute to testing or whatever you're interested in improving.

**Comment by mokun** [comment]
closed. we'll revisit how best to represent the date/month when we add more language support to mars-sim.
