### ISSUE TITLE
Coordinate class should be immutable

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#399]
**Describe the bug**
The `Coordinate` class is used as a key for Map instances. However the class is not immutable so the value of the has could infect change after the key has been added to the Map. This would result in a missing a stored entries or even result in duplicate keys.

**Expected behavior**
The class should be immutable such that once created the equals and hash methods remain constant.
This will impact on other calling classes.

**Comment by mokun** [comment]
oic.

We can convert to become one of those Data class under Java 17.

If we decide to adopt Java 17 two months from now when it comes out.

**Comment by mokun** [comment]
> The class should be immutable such that once created the equals and hash methods remain constant.
> This will impact on other calling classes.

So when a person or a vehicle moves from one location to the next, do we want to create a new Coordinates instance to replace the old one ? 

We did the following in the LocationTabPanel: 
```
			/**
	 * Updates the info on this panel.
	 */
	@Override
	public void update() {
		if (!uiDone)
			initializeUI();
		
		// If unit's location has changed, update location display.
		// TODO: if a person goes outside the settlement for servicing an equipment
		// does the coordinate (down to how many decimal) change?
		Coordinates location = unit.getCoordinates();
		if (!locationCache.equals(location)) {
			locationCache.setCoords(location);

```

**Comment by bevans2000** [comment]
Yes but you should only have a single instance in memory for the vehicle that can be referenced elsewhere. So `locationCache = location;`. Using mutable classes as keys where the hash/equals methods are not constant can cause big problem as it an become random in the lookups.

**Comment by mokun** [comment]
> The class should be immutable

So in what way would you like to make it immutable ? 

But if a mission vehicle is on a journey to go to a waypoint, does it mean that in every frame, it will need to generate a new Coordinate instance ?

**Comment by mokun** [comment]
So in Person, we have 

```java
	/**
	 * Sets the unit's container unit.
	 * 
	 * @param newContainer the unit to contain this unit.
	 */
	@Override
	public void setContainerUnit(Unit newContainer) {
		if (newContainer != null) {
			if (newContainer.equals(getContainerUnit())) {
				return;
			}
			// 1. Set Coordinates
			setCoordinates(newContainer.getCoordinates());
			// 2. Set LocationStateType
			updatePersonState(newContainer);
			// 3. Set containerID
			// Q: what to set for a deceased person ?
			setContainerID(newContainer.getIdentifier());
			// 4. Fire the container unit event
			fireUnitUpdate(UnitEventType.CONTAINER_UNIT_EVENT, newContainer);
		}
	}
```
The line would call Unit's `setCoordinates` as follows: 

```java
	/**
	 * Sets unit's location coordinates
	 * 
	 * @param newLocation the new location of the unit
	 */
	public void setCoordinates(Coordinates newLocation) {
		location.setCoords(newLocation);

		fireUnitUpdate(UnitEventType.LOCATION_EVENT, newLocation);
	}
```
Which in turns would call Coordinates' setCoords() as follows: 
```java
	/**
	 * Set coordinates
	 * 
	 * @param newCoordinates Coordinates object who's location should be matched by
	 *                       this Coordinates object
	 */
	public void setCoords(Coordinates newCoordinates) {
		changed = true;
		// Update coordinates
		if (newCoordinates != null) {
			setPhi(newCoordinates.phi);
			setTheta(newCoordinates.theta);
	
			// Update trigonometric functions
			setTrigFunctions();
		}
	}
```

I wonder if it's necessary to setPhi and setTheta. Also, within them, setTrigFunctions() is being called.

May be instead of calling setCoords(), we only need to have set `location = newLocation);`.

**Comment by mokun** [comment]
But your idea has to do with keeping a lookup table of Coordinates instances, just like the person lookup table in UnitManager, right ?

**Comment by bevans2000** [comment]
No need for lookups, it is just standard immutable POJOs. The "bible" of good Java design/coding _Effective Java_ makes a compelling case but this site sums it up well if you don't have the book (it's a good buy); http://www.javapractices.com/topic/TopicAction.do?Id=29.

So in the Unit's setCoordinate method it would simply be
```
public void setCoordinates(Coordinates newLocation) {
    location = newLocation;

    fireUnitUpdate(UnitEventType.LOCATION_EVENT, newLocation);
}
```
The ```Coordinate.setCoords``` method would go as Coordinates would become immutable. The point is that the Settlement would be created with a new Location holding it's position; then every Unit inside that settlement would also reference the same Coordinate object. Remember as well Coordinates should only matter when the Unit is on the Mars Surface.
We have a similar problem with  #470 where we hold the same location in many duplicate copies.
And to some extent the same with ```MarsClock``` and the use of the clone method. Clone methods should be avoid if possible. Consider how Java ```LocalDateTime``` works; a moment in time is a fixed quantity and once created can not be changed. We should make the ```MarsClock``` also immutable and remove the static accessor method getting the current value from the MasterClock.... however that is for the future.
