### ISSUE TITLE
Migration from Sourceforge

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#4]
- [ ] Re-import entire SVN repo through the importer, mapping contributors to their GH accounts
- [ ] Establish a way of downloading the latest stable release on GH
- [ ] Put up notice on SF that we are moving, and the code is updated on GH from now
- [x] Move the webpages over to a GH Pages branch (this might change the URL of the page)
- [x] Copy all information over in GH Wiki
- [x] Copy open issues and questions over
- [ ] After a while - close the SF repo

**Comment by larsnaesbye** [comment]
Could we start with moving over issue tracking from SF? Like stopping new issues, closing the ones we can, and then move the rest over?

**Comment by shirishag75** [comment]
I can simply copy and paste the 15 open ones here, should I start with that ?

**Comment by shirishag75** [comment]
umm... there is this script which might help https://github.com/cmungall/gosf2github but it does have some limitations and requirements -

> Requirements:
> 
>  * This assumes that you have exported your tickets from SF. E.g. from a page like this: https://sourceforge.net/p/obo/admin/export
>  * You have a github account and have created an OAth token here: https://github.com/settings/tokens    
>  * You have "curl" in your PATH
> 
> TIP:
> 
> Note that the API does not grant permission to create the tickets as
> if they were created by the original user, so if your token was
> generated from your account, it will look like you submitted the
> ticket and comments.
> 
> Create an account for an agent like https://github.com/bbopjenkins -
> use this account to generate the token. This may be better than having
> everything show up under your own personal account
> 

Hope it's useful.

**Comment by larsnaesbye** [comment]
What do you say? Should I just copy/paste the SF issues over?

**Comment by shirishag75** [comment]
@larsnaesbye . I just did one at https://github.com/mars-sim/mars-sim/issues/8 . You will need to put the forwarding address at the sourceforge.net ticket and close it (I don't have admin access there) and put from where it is being imported in the ticket here . 

Would have preferred to import the user account but for that to happen, you would have to use the script. Optionally you could use connect with the reporters and ask them to put the report here and just close the bugs there.

**Comment by larsnaesbye** [comment]
Cool! I closed it at Sourceforge with a reference. Feel free to copy/paste the others over and I will also close them up :)

**Comment by larsnaesbye** [comment]
I'm migrating the rest over myself. Seems easier that way.

**Comment by larsnaesbye** [comment]
It is done :-) Now we need to move the code over.....

**Comment by shirishag75** [comment]
I didn't want to announce after moving over each bug, hence it was good you went that way. 

Did you look at the discussion that we had for migrating code over... Git and Github are good with code, not so good with binary images.

**Comment by larsnaesbye** [comment]
No I didnt....was is on FaceBook?

**Comment by shirishag75** [comment]
nope...actually in my head :(   Apparently git is not so good with binary images. See some of the discussions on stackoverflow precisely on this topic - 

http://stackoverflow.com/questions/1911005/git-and-binary-data#1911054

http://stackoverflow.com/questions/3618447/using-git-for-images

as well as 

http://softwareengineering.stackexchange.com/questions/80962/should-images-be-stored-in-a-git-repository

the consensus of most of the discussions has been have the images remain in svn as a sub-module triggered by git while the code-base is in git.  

There are two points to consider -

**Comment by larsnaesbye** [comment]
Hmmm...I don't see the links as making a good case for not moving. Do we really have that many large binary files? I know that we could clean up a lot too...

**Comment by larsnaesbye** [comment]
I'm thinking about moving the wiki over next...

**Comment by shirishag75** [comment]
Go ahead about the wiki. About binary images ideally, first cleaning up and then having some sort of history and understanding as to how often the changes to the binary files would be. 

If for instance, binary files are not touched for many a year, then it might make sense to move them over to git, if on the other hand,  there are frequent changes to the binary images, either new binary images or texturing, higher resolution pictures etc. then it might make sense to split the repository in two, the code part and the images part with images remaining in the svn module while the rest of the code moves onto git. 

Also remember that github has space limitations (even for foss projects) so we can't allow it to grow exponentially, see https://help.github.com/articles/what-is-my-disk-quota/ . Hope it clears some of the confusion.

**Comment by larsnaesbye** [comment]
I know, but we've been notoriously bad about including everything ever tried out in the repository. If we are forced to clean up just a tiny bit, then it's only good IMHO.

**Comment by shirishag75** [comment]
true. That is the reason why Git has [branches ](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/)

**Comment by larsnaesbye** [comment]
I've now moved most of the wiki over. Some pages I skipped because they contained things we've already done. There are 3 pages that have important images or formatting I'll have to look deeper into:

- Getting_Started_with_MSP
- Setting_up_a_MSP_development_environment_with_the_command_line
- UML_Diagrams

Images might have to be stored in a separate repo, like when we move the webpages over to GitHub Pages. I'll look into this, but please do edit away on what's been ported already :)

**Comment by mokun** [comment]
Thanks Lars. I also reworked the front page of wiki to show all wiki pages.
I've revised these wiki pages and at least formatted some of them to just
look better.

Question: how do I make the Pages tab on the right hand side show all wiki
pages by default? Currently it was in the collapsed position.

**Comment by larsnaesbye** [comment]
Yeah, I've wondered too how people manage to have it expanded by default, like [here](https://github.com/elastic/kibana/wiki).

**Comment by shirishag75** [comment]
umm... has anybody looked at settings ? Specifically https://github.com/mars-sim/mars-sim/settings . For some reasons, github pages is disabled while the wiki has pages. Could somebody look into that ?

**Comment by larsnaesbye** [comment]
That's not the same thing, I'm afraid. Github Pages is web pages served through a web server, but the wiki is just another repository of .md files (or whatever we choose).

**Comment by larsnaesbye** [comment]
An example of GitHub Pages is this: http://larsnaesbye.github.io/tempus/ - from a dead project of mine.

**Comment by shirishag75** [comment]
all is good. I asked the github people and this is what they had to say - 

> Thanks for writing in! Your Wiki had a custom sidebar titled "misc" which was preventing the automatically generated sidebar from being unfolded onto the page by default. The custom sidebar was empty, so I deleted it for you. Your Wiki's sidebar is now displayed by default.
> 
> https://github.com/mars-sim/mars-sim/wiki

**Comment by larsnaesbye** [comment]
Yeah! Also know that you can clone wikis and add other files to them. This is how I plan to add images :-)

**Comment by mokun** [comment]
Shirshag,

Thanks for engaging us in getting things rolling and also contacting github to remove the side bar.


Lars, 

Thanks for converting those wiki pages. 

I can see you add some new pages with "Project Development Idea: Roads", etc, yestersday.

I've processed a few of them--lightly edited the formats, updated the contents, added new comments. etc. 

Once done, I'll move the edited page to under "D. New Proposals".

Just so you know.

-Manny

**Comment by larsnaesbye** [comment]
I have now added a /images folder to the wiki. You will need to check out the wiki as a git repo in order to access it. The UML diagrams have been put in there and they're now displayed on the [UML diagrams](https://github.com/mars-sim/mars-sim/wiki/UML-diagrams)  page.

**Comment by larsnaesbye** [comment]
Wiki moved over. Next up should be the Web Pages :-)

**Comment by larsnaesbye** [comment]
Cool, now the web pages are up on http://mars-sim.github.io , we should update the SF page to say so. @mokun , do you have the auth to do this?

Also, since the web pages are over now, we need to move the code over. Did we find a smart to migrate all commit creds too?

**Comment by mokun** [comment]
>  migrate all commit creds too?

can we simply start a new repo with git and use it for 3.1.0 from now on?

we could leave the old svn repo alone.

if we do it this way, I suppose it wouldn't matter with the old commit creds.

**Comment by mokun** [comment]
Lars, let's save README.md 

How do you remove the old SVN linkage and create a git repo but keep the repo name -- https://github.com/mars-sim/mars-sim ?


do you use eclipse ? give me some instructions in accessing it in eclipse later.

**Comment by mokun** [comment]
I just did the import of the most recent mars-sim svn repo here for experimentation : https://github.com/mokun/mars-sim.

This time I exclude the /tools/ folder, since I import "https://svn.code.sf.net/p/mars-sim/code/trunk/mars-sim" instead.

**Comment by larsnaesbye** [comment]
I dont mind with old commit creds, I just wonder if others do :-)
So I guess we could just do a reimport and abandon the old repo.

As for the tools, I have never come to a conclusion if it's better to let them have their separate repo or stay in. We can just let them stay in I guess.

Most SVN info is stored in .svn directories within every directory. If you delete these, I think all SVN tracking disappears.

**Comment by shirishag75** [comment]
I would suggest to do two things -

a. Have a contributors file which lists all the contributors who have ever committed or patched or however they have committed to the project

b. Have the most recent sources which are in compilable state as the start of the git repo. Just make sure that images are kept out as well as tools. The images would be part of the wiki as had been shared earlier.  Let tools be a different repo. altogether and share instructions as to how to use the tools and images to build the game independently. 

If we do this way, I don't see anybody objecting to this way. Comments welcome. 

Wishlist - Maybe over time common build tools will be able to build the game .

**Comment by larsnaesbye** [comment]
I'm all for making a CONTRIBUTORS file then. It needs to be evident who contributed, also because this is a GPL project.
Tools can go into one (or more) other repos.

But @mokun is right, the README from the current GH repo should remain.

**Comment by larsnaesbye** [comment]
So, do we do these steps?
1) Keep the current GitHub repo, with README.md file, Wiki and Issues
2) Simply copy the updated code over, replacing the old version. Any .svn directories will be left out
3) Write a CONTRIBUTORS file
4) Leave a notice in the old SF repo that we've moved
5) Update info on cloning and building

Is that the new simplified plan? :-)

**Comment by shirishag75** [comment]
I am all for it, let's say what @mokun has to say on it.

**Comment by mokun** [comment]
ok. so far, only Lars and I report as the developers. it'll take a while to track down all other contributors if they are interested in laying claim to their contributions to this project.

so do we want it to look like https://github.com/mokun/mars-sim ?

what's next ?

**Comment by larsnaesbye** [comment]
I read somewhere that you can map contributors in GitHub afterwards, and I have a lot of mails back to 2005 and might compile a list of contributors from that.

**Comment by shirishag75** [comment]
in that case, I would simply suggest to go ahead and do the compilation as and when you have time.

**Comment by mokun** [comment]
Yes shirishag75 you are right. I do hope some of developers/contributors will come back, regardless how they used to contribute to mars-sim in the past. 

I did some research online, we have at least 4 options :

1. Migrate the entire codebase to Git and stop using SVN altogether
2. Don’t migrate any old/existing versions/projects to Git, but use Git for all new projects
3. Migrate some of the versions/projects to Git while continuing to use SVN for other projects
4. Use SVN and Git simultaneously on the same versions/projects

I suppose we are going for #2 above, right ?

**Comment by mokun** [comment]
I haven't used git enough to 

Based on this Bitbucket page at https://www.atlassian.com/git/tutorials/migrating-overview, SVN-to-Git migration process can be broken into the following 5 steps:

1. Prepare your environment for the migration
2. Convert the SVN repository to a local Git repository
3. Synchronize the local Git repository when the SVN repository changes
4. Share the Git repository with your developers via GitHub
5. Migrate your development efforts from SVN to Git

In our case, we already synchronized once and already created a repo.

Question 1 : exactly what git commands can we use to sync up our SVN (from SF) and our Git (from GitHub) up to including the latest commit ?

If we start out as a brand new repo, it's easy to do so in GitHub in just a few mouse click. But since we have wiki and issues already, GitHub no longer allow us to use their graphic interface to do so.

After this is done, we can start doing commits directly with Git. 

Question 2 :  what git commands from then on do we use to commit changes ? Can we list out the steps here ?

Note: the "opengl" branch was still there, did st-pa sync that for us ? I believe we should delete this opengl since it doesn't serve any purpose.

**Comment by larsnaesbye** [comment]
As far as I understand, GitHub supports the use of Subversion for its repos: https://help.github.com/articles/support-for-subversion-clients/

So is it really a tradeoff?

**Comment by larsnaesbye** [comment]
If it's easier to reimport into, say, 'mars-sim/mars-sim2' and then migrate issues and wiki again, then we can always delete the old import and rename the new back to 'mars-sim/mars-sim'.

**Comment by larsnaesbye** [comment]
When I commit something in git, it's usually:

2. `git add [files I've changed]`
3. `git commit -m '[message]'`
4. `git push`

The advantage is that I can select which changes I want to stage for committing, whereas in SVN it always chooses everything.

**Comment by mokun** [comment]
Yes Lars, we can always go back and update the authors at 

https://github.com/mars-sim/mars-sim-git/import/authors

Note: /mars-sim-git is the new created repo fully sync up with svn to the latest commit.

**Comment by larsnaesbye** [comment]
Cool! So that works now. Do we only need to move the wiki and issues to it then?

**Comment by mokun** [comment]
Let say I'm going to use Eclipse to commit a change in SF's svn. How do we sync up the latest change to  GH's /mars-sim-git ?

**Comment by larsnaesbye** [comment]
I don't know how you would do that automatically without having the same directory locally under both svn and git version control. Wouldn't it be easier to set up svn access from Eclipse to GitHub?
Like I mentioned, GitHub can be used with Subversion commands.

**Comment by larsnaesbye** [comment]
```
svn co --depth empty https://github.com/mars-sim/mars-sim-git
svn up trunk
```

**Comment by mokun** [comment]
what does "svn co https://github.com/mars-sim/mars-sim-git" do ?

**Comment by larsnaesbye** [comment]
Checkout the GitHub repo using Subversion :-)

**Comment by mokun** [comment]
why and when do we need to do this ?

**Comment by larsnaesbye** [comment]
My point is that you can setup Eclipse and Subversion to use the GitHub repo. So we no longer need the SF repo for people who prefer Subversion.

**Comment by mokun** [comment]
Can you show me step by step on what to do now ?

I just made a quick code change in eclipse. I made a commit to SF's SVN.  Now, what do I do to sync up the changes in GH's git ?

What would you have done differently ?

When will you do "svn co https://github.com/mars-sim/mars-sim-git" ?

**Comment by larsnaesbye** [comment]
Hold on. Do we really want two different repos, in two different places, using two different versioning systems, getting out of sync with each other all the time???
My thought was that from the day we had imported to GitHub we used the Github repo. People who wanted to use Subversion could still do that, others could use git.

**Comment by larsnaesbye** [comment]
Is it because we need an instruction in setting up Eclipse to work with the Github repo?

**Comment by shirishag75** [comment]
@mokun  please answer Lars. It doesn't make sense to have two repos, we want/need a single repo. in git. 

Having said that, there are few blog posts I think both of you should be aware of -

https://joeyh.name/blog/entry/what_I_would_ask_my_lawyers_about_the_new_Github_TOS/

https://joeyh.name/blog/entry/removing_everything_from_github/

https://www.earth.li/~noodles/blog/2017/03/github-tos-change.html

https://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm#e20170301-tg_wlog-10

**Comment by mokun** [comment]
Yes I'll definitely prefer having one repo, instead of two. 

It's just that we need to write down the steps on how to set up the developmental environment to do it the new way.

**Comment by mokun** [comment]
@shirishag75 I'll read up on GitHub's new TOS to see what the deal is.

Normally, in a official release, we bundle the source code of mars-sim together with its jar, plus all the jars that we depend on. These jars are downloaded from maven. We call them maven artifacts and they are under various BSD, CC and GPL licenses.

So far, Scott is using GPL 2.0 license to cover the source codes in mars-sim.

I don't understand how the latest changes in GitHub would adversely the open source projects out there yet and if it would somehow affect the distribution of mars-sim. 

May be the GitHub's change worsens the inherent legal mumble jumbo that have been there already. To me when it comes to licensing, nothing is clear cut until you meet your opponents in courts. Oracle vs. Google is one example that licensing aren't definitive no matter what. Do let me know any findings you may have.

**Comment by shirishag75** [comment]
@mokun - if you are using eclipse as the IDE on MS-Windows, then this probably will be most instructive to you -

http://www.vogella.com/tutorials/EclipseGit/article.html . 

I haven't had to use an IDE for anything, yet... and on GNU/Linux the CLI is pretty powerful to most of the things. 

The workflow is documented in that humongous tutorial page that I just shared, it's just you will have to figure out which pieces to keep and which are not relevant. 

For instance, it's no longer sufficient to have SHA-1 keys and we need to move SHA-256 or better.

See http://www.pcworld.com/article/3174676/security/sha-1-collision-can-break-svn-code-repositories.html and

https://www.theregister.co.uk/2017/02/23/google_first_sha1_collision/

**Comment by mokun** [comment]
It's true that linux CLI is sufficient and the preferred choice for some developers.

To me, I'm so used to the windows environment that I've just ventured to see how differently in setting up the Eclipse IDE for accessing GH repo directly.

What I found out was that, instead of inputting "https://svn.code.sf.net/p/mars-sim/code" as repo root url, I just have to replace it with "https://github.com/mars-sim/mars-sim-git.git"

Then the rest of the steps are the same as said in https://github.com/mars-sim/mars-sim/wiki/Setting-Up-Eclipse-IDE 

And viola ! Everything works just like before.

I'll update the wiki to reflect this url change.

**Comment by larsnaesbye** [comment]
> What I found out was that, instead of inputting "https://svn.code.sf.net/p/mars-sim/code" as repo root url, I just have to replace it with "https://github.com/mars-sim/mars-sim-git.git"

Exactly. That was my point - you can still use Subversion if you wish, just with the GitHub repo :-)
And if you want to switch to git at one point, you can too.

**Comment by mokun** [comment]
In summary,

1. We are sticking with SVN, specifically the use of SVN clients for accessing GH repo.

2. If you prefer graphical interface, 
- you may use any Eclipse IDE out there and you must install SVN support. You don't need to install or use EGit in Eclipse.  
- you may choose Approach 1 to set things up quickly as explained [here](https://github.com/mars-sim/mars-sim/wiki/Setting-Up-Eclipse-IDE). In this case, you will uses e(fx)clipse, which has SVN built-in via Subclipse.

3. If you prefer command line, 
- you will need to install Git (for macOS or Linux) or GitHub Desktop (for windows). In addition, you will need to install a svn client.
- you will use the commands in https://help.github.com/articles/support-for-subversion-clients/ as As Lars points out to commit changes.

**Comment by larsnaesbye** [comment]
Yes. That sounds like how the instructions should go :)

So...is mars-sim/mars-sim now the repo we use?

**Comment by mokun** [comment]
How do we go back to the original /mars-sim/mars-sim repo instead of /mars-sim/mars-sim-git while still retaining all the SVN commit history ? Do you know of a way to do it ? is it as simply as cloning between the two repos. Please proceed if you already know how.

**Comment by mokun** [comment]
@larsnaesbye and @shirishag75 , 

Can you verify if the instructions in https://github.com/mars-sim/mars-sim/wiki/Setting-Command-Line-Environment-via-SVN are correct ? 

Feel free to edit. 

Also, do you mind adding another wiki page showing users how to accomplish the same thing in Git instead of using SVN client ?

**Comment by mokun** [comment]
> For instance, it's no longer sufficient to have SHA-1 keys and we need to move SHA-256, SHA -3 or whatever is suitable to us.

@shirishag75 , 

Can you open up a new issue regarding the adoption of SHA-256 keys ?

I don't know what needs to be done yet but we can surely explore further.

**Comment by shirishag75** [comment]
@mokun Probably @larsnaesbye would be a better yet at the compiling. I do have maven at my end but haven't given stab yet at compiling unless all the other bits are in place - 

```
[$] mvn -version                                                                                                                  
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-1-amd64", arch: "amd64", family: "unix"
```

For the git page, the only differences in command-line are - 

```
$ git clone $URL.git 

$ git pull origin master

$ git branch $branch-name
``` 

(to get into branches, this is why git is in top, branching is faster and cheaper in git). 

simply doing` $ git branch --help` tells all the different possibilities.

**Comment by larsnaesbye** [comment]
@mokun : It looks right to me. So this means we're in business on GH :-)

**Comment by mokun** [comment]
Yes, now we have /mars-sim code repo working again !

In summary, I've been trying to figure out how to :

1. Backup all Issues in /mars-sim repo and restore them in /mars-sim-git
2. Backup all Wikis in /mars-sim repo and restore them in /mars-sim-git
OR:
3. Clone the codebase in /mars-sim-git repo and restore them in /mars-sim while keeping Commit History intact

We just need to do either 3, or 1 & 2 together.

At this moment, I haven't found an easy way to do 1. 

I can do partially 2-- I can clone all wikis into my hard drive but I can't push them back to other repos. 

I can do 3 except losing the releases/tags setup. 

btw, I'd like to leave /mars-sim-0 and/or /mars-sim-git repos open for experimentation if that's okay for everyone.

This way, I may avoid accidentally screwing up /mars-sim repo, where all the important Wikis and Issues are resided.

**Comment by larsnaesbye** [comment]
I might be able to do 2)... 

But now we use mars-sim-git as main repo for commits, right? Just to be sure I get code changes into the right repo :-)

**Comment by mokun** [comment]
> But now we use mars-sim-git as main repo for commits, right? Just to be sure I get code changes into the right repo :-)

No, I did 3 and /mars-sim is now the official repo :)

**Comment by larsnaesbye** [comment]
Perfect. Then our migration from SF to GH is done, I guess.
