### ISSUE TITLE
does pom.xml do a lookup at existing packages - 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#40]
While building saw this - 

```
[INFO] ------------------------------------------------------------------------
Downloading: http://jcenter.bintray.com/org/oxbow/swing-bits/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading: https://github.com/eugener/oxbow/raw/master/maven/repository/org/fxmisc/richtext/richtextfx/1.0.0-SNAPSHOT/richtextfx-1.0.0-20170322.163614-145.pom
Downloading: http://repo1.maven.org/maven2/org/fxmisc/richtext/richtextfx/1.0.0-SNAPSHOT/richtextfx-1.0.0-20170322.163614-145.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/fxmisc/richtext/richtextfx/1.0.0-SNAPSHOT/richtextfx-1.0.0-20170322.163614-145.pom
```

Btw saw this - 

```
[WARNING] Could not validate integrity of download from http://mars-sim.sourceforge.net/maven-repo/com/plaf/nimrod/nimrodlf/1.2c/nimrodlf-1.2c.jar: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available for http://mars-sim.sourceforge.net/maven-repo/com/plaf/nimrod/nimrodlf/1.2c/nimrodlf-1.2c.jar
```

Maybe you can fix the checksum bit or have checksums either on git or on svn repo somewhere.

**Comment by mokun** [comment]
hmmm. I've never seen that before.


btw, can you download http://mars-sim.sourceforge.net/maven-repo/com/plaf/nimrod/nimrodlf/1.2c/nimrodlf-1.2c.jar ?

It said it's a warning only. I think you can ignore it.

It was Scott who upload nimrodlf-1.2c.jar onto our mars-sim svn repo in sourceforge.

**Comment by mokun** [comment]
btw, richtextfx is not needed at this moment. It looks like maven is trying to reach out to 4 different repos (bintray's jcenter, github, maven central and oss.sonatype) to look for it.

**Comment by mokun** [comment]
I log onto the sourceforge's maven repo. See this ![nimrodlf](https://cloud.githubusercontent.com/assets/1168584/24282940/d4fa3222-101f-11e7-8fb3-faf13bbec759.png)

nimrodlf-1.2c.jar looks good. don't know why checksum validation was failed on your end.

**Comment by shirishag75** [comment]
what is nimrodlf do ? nm just found out http://nilogonzalez.es/nimrodlf/index-en.html, reading.

**Comment by mokun** [comment]
In short, it's a Java Swing Look and Feel library.

It adds a new color style to all the Java Swing UI elements.

**Comment by larsnaesbye** [comment]
@mokun , are we still embedding Swing UI components into the JFX build?

**Comment by shirishag75** [comment]
just adding to what @larsnaesbye shared, Debian policy doesn't like embedded copies of libraries anywhere. See https://www.debian.org/doc/debian-policy/#convenience-copies-of-code as well as is part of the reproducible-builds definition which almost all GNU/Linux distributions are following in order to not get nasty surprises in the future. 

https://reproducible-builds.org/docs/definition/

**Comment by mokun** [comment]
> [INFO] ------------------------------------------------------------------------
> Downloading: http://jcenter.bintray.com/org/oxbow/swing-bits/1.0.0-SNAPSHOT/maven-metadata.xml
> Downloading: https://github.com/eugener/oxbow/raw/master/maven/repository/org/fxmisc/richtext/richtextfx/1.0.0-SNAPSHOT/richtextfx-1.0.0-20170322.163614-145.pom
> Downloading: http://repo1.maven.org/maven2/org/fxmisc/richtext/richtextfx/1.0.0-SNAPSHOT/richtextfx-1.0.0-20170322.163614-145.pom
> Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/fxmisc/richtext/richtextfx/1.0.0-SNAPSHOT/richtextfx-1.0.0-20170322.163614-145.pom

I know what the above means now. It was trying to look for the package called richtextfx from different  repos. 

As you can see in https://github.com/FXMisc/RichTextFX, it's available in Sonatype snapshot repository only and is not in maven central repo.

Yesterday, I was compiling mars-sim after making some changes to it. It was looking for weblaf-ui and weblaf-core from a few repos.

**Comment by mokun** [comment]
> @mokun , are we still embedding Swing UI components into the JFX build?

@larsnaesbye , yes we do.

Some of those UnitWindow types (e.g. SettlementWindow, PersonalWindow, etc) now have some JavaFX UI in them. 

Rather than rebuilding everything from the ground up in JavaFX, I use JFXPanel class to embed JavaFX UI within a Swing JPanel. e.g. TabPanelDashboard and TabPanelPersonality.
