### ISSUE TITLE
Modeling how resources/equipment is being (un)loaded

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#404]
**Question**
- How should we model the process of loading and unloading resources from and to a rover or drone ?

**Current Modeling**
As of r6036, 
1. For an outside rover/drone , a settler would need to do EVA to go to its location to be its proximity but doesn't need to go inside the vehicle.
2. For rover/drone inside a garage, a settler would walk to the garage and approach that vehicle.
3. Then the settler would somehow *initiate* the transfer of, say, methane, from the settlement to the rover.
4. Strangely, the settler never has to carry that resource with him/her and take it to the rover.
5. Once the physical weight "limit" for this settler has been reached , he/she would leave. If on EVA,  he/she would go back to the airlock to go inside. 
6. A few millisols later, this settler would repeat steps 3 to 5.

**Better Modeling**
For an outside rover/drone , there should be two options. 
1. For gas or liquid transfer, 
   -- 1a. the hookup or will be performed. A settler can initiate a hookup command to automatically steer the vehicle to come next to a transfer station. 
2. For solid items, 
   -- 2a. the settler may drop it off at a transfer box inside the settlement. An outside service robot would transfer it to the rover. 
   -- 2b. the settler first pick up the resource/items and hand carry it as he/she goes through the airlock to do an EVA to the vehicle.

**Comment by mokun** [comment]
@bevans2000 

I'm testing a quick implementation of a direct hookup between a mission vehicle and settlement. 

During embarking phase, it takes too long for settler to **manually** load amount resources from settlement to vehicle.

The amount to be loaded is based on what a settler can physically handle.

It makes sense for the Item Resources to be loaded this way. 

But it doesn't make sense for the amount resources to be hand-carried by settler manually.

I'm hoping this will resolve two issues: 
1. While the settlers are inside the vehicle and get ready to leave, some amount of oxygen are kept being used up. When it falls below the *required* amount, it doesn't allow the vehicle to depart.
2. The current mechanism is to call assignTask() method to FORCE some settlers (with 50% of the chance to be picked) to come help out with the loading and unloading of resources. This causes the abandonment of tasks.

**Comment by mokun** [comment]
@bevans2000 

Currently, there's a bug in calculating the amount of resources needed. So for a short journey of, say 18 km, it somehow asks for the required resource of 256 kg of water.

I have yet found out why the calculation became erroneous.

It should have to do with getResourcesNeededForTrip() in VehicleMission as well as getResourcesNeededForTrip() in RoverMission.

```java
	/**
	 * Gets the number and amounts of resources needed for the mission.
	 * 
	 * @param useMargin Apply safety margin when loading resources before embarking if true.
	 *        Note : True if estimating trip. False if calculating remaining trip.
	 * @return map of amount and item resources and their Double amount or Integer
	 *         number.
	 */
	@Override
	public Map<Integer, Number> getResourcesNeededForTrip(boolean useBuffer, double distance) {
		// Note: currently, it has methane resource only
		Map<Integer, Number> result = super.getResourcesNeededForTrip(useBuffer, distance);

		// Determine estimate time for trip.
		double time = getEstimatedTripTime(useBuffer, distance);
		double timeSols = time / 1000D;
		int crewNum = getPeopleNumber();

		// Determine life support supplies needed for trip.
		double oxygenAmount = PhysicalCondition.getOxygenConsumptionRate() * timeSols * crewNum ;
		if (useBuffer)
			oxygenAmount *= Vehicle.getLifeSupportRangeErrorMargin() * Mission.OXYGEN_MARGIN;
		result.put(oxygenID, oxygenAmount);

		double waterAmount = PhysicalCondition.getWaterConsumptionRate() * timeSols * crewNum ;
		if (useBuffer)
			waterAmount *= Vehicle.getLifeSupportRangeErrorMargin() * Mission.WATER_MARGIN;
		result.put(waterID, waterAmount);

		double foodAmount = PhysicalCondition.getFoodConsumptionRate() * timeSols * crewNum ; 
		if (useBuffer)
			foodAmount *= Vehicle.getLifeSupportRangeErrorMargin() * Mission.FOOD_MARGIN;
		result.put(foodID, foodAmount);

		return result;
	}
```

Can you figure out how to fix it ?

**Comment by bevans2000** [comment]
Sure I can have a look. It won't be today, probably tomorrow

**Comment by mokun** [comment]
The loading issue is linked to https://github.com/mars-sim/mars-sim/issues/439

**Comment by mokun** [comment]
We could probably close this now since work has been been done under another issue thread.

**Comment by bevans2000** [comment]
I agree
