### ISSUE TITLE
Insufficient capacity to store a resource; Equipment cache and capacity; vehicle range and mission range

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#406]
**Describe the bug**
- There has been a lot of "Insufficient capacity to store" message for regolith, ice and methane lately

**Expected behavior**
- It shouldnt even attempt to store that much.
- It's not known why it would attempt to store such a huge amount of methane for a short journey 

**Desktop (please complete the following information):**
 -build 6056

**Additional context**

```
00-Adir-01:165.955 (Info) DigLocalRegolith : [5.05 S 4.21 E] Alfred Sørensen - Collected a total of 92.3 kg regolith.
00-Adir-01:165.955 (Severe) Inventory : [Alfred Sørensen] Bag 023 - Insufficient capacity to store regolith, capacity: 45.31, attempted: 87.612
00-Adir-02:546.203 (Info) BuildingManager : [New Copenhagen] Areos Aster - Stowed inside Garage 1.
00-Adir-02:546.203 (Info) VehicleMission : [New Copenhagen] Areos Aster - Fetching spare parts:  x1 fuel tank ID:2062   x1 fire extinguisher ID:2002   x1 gasket ID:2003   x1 valve ID:2004   x1 epoxy resin bottle ID:2005   x1 spark plug ID:2006   x5 electrical wire ID:2008   x2 decontamination kit ID:2137   x6 wire connector ID:2010   x1 plastic tubing ID:2011   x1 logic board ID:2141   x1 radio antenna ID:2013   x1 work gloves ID:2142   x1 communications circuit board ID:2016   x1 light emitting diode bulb ID:2099  
00-Adir-02:546.203 (Info) LoadVehicleGarage : [New Copenhagen] Areos Aster - 1. Cannot load 833.4 kg methane
00-Adir-02:546.203 (Severe) Inventory : [Unknown] Insufficient capacity to store methane, capacity: 180.0, attempted: 833.363
00-Adir-02:546.203 (Warning) LoadVehicleGarage : [New Copenhagen] Areos Aster - Allowed loading only 180.0 kg methane.
00-Adir-02:546.203 (Severe) Inventory : [New Copenhagen] Areos Aster - Insufficient capacity to store methane, capacity: 180.0, attempted: 653.363
00-Adir-02:546.203 (Severe) Inventory : [New Copenhagen] Cannot retrieve negative amount of resource: -615.5849480588372
00-Adir-02:546.203 (Severe) Inventory : [New Copenhagen] Areos Aster - Cannot store negative amount of resource: -615.58
00-Adir-02:648.077 (Severe) Inventory : [New Copenhagen] Insufficient stored amount to retrieve methane. Storage Amount : 566.1330371061327 kg. Attempted Amount : 653.3634072801979 kg
00-Adir-02:656.013 (Warning) LoadVehicleGarage [x65] : [New Copenhagen] Areos Aster - Allowed loading only 180.0 kg methane.
00-Adir-02:751.683 (Info) LoadVehicleGarage : [New Copenhagen] Areos Aster - Not having enough methane; Loaded: 0.0; Needed: 833.36; Settlement's need: 0.0; Settlement's stored: 546.18
...
00-Adir-05:879.537 (Severe) Inventory : [Sandra Sepp] Bag 050 - Insufficient capacity to store regolith, capacity: 35.61, attempted: 89.948
...
00-Adir-07:991.503 (Severe) Inventory : [Leah Nilsen] Bag 053 - Insufficient capacity to store ice, capacity: 32.11, attempted: 73.596
...
00-Bora-05:332.674 (Severe) Inventory : [Alfred Sørensen] Bag 081 - Insufficient capacity to store ice, capacity: 50.0, attempted: 87.994
```

**Comment by mokun** [comment]
@bevans2000 

Right now, only delivery mission works. 

All other missions could not get started (also they were mistakenly reported as 'Completed' in Mission Tool).

I don't see anything wrong with getFuelNeededForTrip() in VehicleMission.

**Comment by bevans2000** [comment]
Sure it was working ok last week when I did some runs. I will check my fork which doesn't have the latest commits.

**Comment by mokun** [comment]
> Right now, only delivery mission works.

Delivery missions rely on VehicleMission as well. So VehicleMission should be the culprit. 

Other missions depends on RoverMission and Delivery mission doesn't. So it's possible something in RoverMission that's causing it.

**Comment by bevans2000** [comment]
Could be. I've noticed recently over the last week that the simulation appears to be getting slower. The pulses are taking a long time to simulate. So I think that it is just spinning around trying to start Missions which then fail.

**Comment by bevans2000** [comment]
Since I've done a pull this evening I can get no Missions to start. The method `Mind.canStartMission` always returns false because the Person is never at the start of their shift. If you look at method `TaskSchedule.isPersonAtStartOfWorkShift` it uses an property called 'now' but this is never updated. So I don't know how it has ever worked; sure the property should have the time of day.

**Comment by mokun** [comment]
> The method `Mind.canStartMission` always returns false because the Person is never at the start of their shift.

Now that you mentioned this, the original intent is to limit the duration of time for starting new missions, or else it would use a lot of cpu to repeatedly asking for mission when someone else has already started the same type.

But these 3 types of missions, namely, EmergencySupply, RescueSalvageVehicle and Delivery should not be limited by that window and should be considered to start anytime.

**Comment by mokun** [comment]
> If you look at method `TaskSchedule.isPersonAtStartOfWorkShift` it uses an property called 'now' but this is never updated.

hmmm it's been a while since we touched this, right ? 

At least i've seen missions getting started in the last couple days but they got turned down because of "the insufficient capability".

**Comment by mokun** [comment]
> it uses an property called 'now' but this is never updated.

Okay. Committing the changes in a few minutes

**Comment by bevans2000** [comment]
Yes it needs to be updating with the current time but looking at the Git history seems to have been like that for a while. So it's a bit confusing.
The TaskSchedule is an area we should address in teh future because the Task logic seems split between Settlement & TaskSchedule.

**Comment by mokun** [comment]
It turns out the way the logics is currently being laid out, it doesn't stop the mission from being submitted and be approved, even if the mission requires, say 200 kg of methane, but the methane tank's capacity is only 180 kg.

I may have done something recently to evade this capacity checking lately.

**Comment by mokun** [comment]
btw, I did change some of the vehicle specs in the last two days.

It definitely make each vehicle require more fuels to travel each km. 

But even though it would affect the amount of fuel it will need to carry, it shouldn't be asking to carry so much fuel all of a sudden.

**Comment by mokun** [comment]
One big reason for having the so-called "insufficent capacity" hinges upon how `isFullyLoadedWithResources()` in `LoadVehicleGarage` and in `LoadVehicleEVA` are supposed to work.

**Comment by mokun** [comment]
I found out `getFuelNeededForTrip()` in `VehicleMission` can be problematic. 

Will make sure the amount of methane to be requested won't exceed the methane tank capacity of the vehicle. Fixing it now.

Still it doesn't make sense why would try to load a lot of food and other items. And why it would affect digging ice and regolith.

Sounds likes whatever happened with loading resources onto a vehicle is a SEPARATE CONCERN from the digging ice/regolith.

**Comment by bevans2000** [comment]
> One big reason for having the so-called "insufficent capacity" hinges upon how `isFullyLoadedWithResources()` in `LoadVehicleGarage` and in `LoadVehicleEVA` are supposed to work.

Yes these methods are very inefficient  because they clone the Inventory and trial the proposed loading. Inventory is already complex logic so it feels problematic. Probably should be refactored to calculate the mass directly.

**Comment by bevans2000** [comment]
I think the problem is in this commit to fix the excessive Equipment creation; e7bb5154ba4e5dece70229c4837b56cd26dd7cfe.
It reuses the Equipment but we need to cleardown the Inventory before it is reused.  The problem is how the LoadVehcileGarage.enoughCapacityForSupplies method calculates the capacity.

**Comment by bevans2000** [comment]
Basically we need to either:

1. Stop reusing Equipment which causes an continuous increase in memory
2. Rewrite this method so it calculates capacity is a simpler way just based on size.
3. Don't bother checking and just fail when we do the actual loading

As in a normal situation there is always capacity option 3 makes sense do code for the norm and handle the rare exception when it occurs.

**Comment by mokun** [comment]
> 2. Rewrite this method so it calculates capacity is a simpler way just based on size.

Or another option is to use H2 database and we already have it in pom.xml. It's just a matter of activating it.

**Comment by mokun** [comment]
> 3\. Don't bother checking and just fail when we do the actual loading
> 
> As in a normal situation there is always capacity option 3 makes sense do code for the norm and handle the rare exception when it occurs.

Say we want to build a set of class for containers from scratch.

e.g. We want 3 types of bags (small, medium, large volume/capacity) and 7 types of gas canisters (we have 7 types of gases) of various weight and volume.

**Comment by bevans2000** [comment]
> > 3. Don't bother checking and just fail when we do the actual loading
> > As in a normal situation there is always capacity option 3 makes sense do code for the norm and handle the rare exception when it occurs.
> 
> Say we want to build a set of class for containers from scratch.
> 
> e.g. We want 3 types of bags (small, medium, large volume/capacity) and 7 types of gas canisters (we have 7 types of gases) of various weight and volume.

Not new containers or classes,  we need just the logic to only emulate the capacity of the containers not the hold storing of resources. It's a tricky job but will improve things in terms of processing resources.
However in the short term make the enoughCapacity method be hardcoded to return true to test the theory of this stopping mission.

**Comment by mokun** [comment]
It keeps complaining that zero methane is loaded onto the Drone. 

But the fact is that 39.1 kg has been loaded.

How would you explain it ? 

How come it doesn't report what's in the vehicle's inventory correctly ?

```
00-Adir-02:333.921 (Info) LoadVehicleGarage [x11] : [Europa] Drone 002 - 1. Insufficient supply of methane  stored: 0.0 kg   required: 39.1 kg   toLoad: 39.1 kg   remainingCap: 100.0 kg 
00-Adir-02:338.992 (Info) VehicleMission [x43] : [Europa] Drone 002 - tripDistance: 1281.0 km   fuel economy: 42.6 km/kg   composite fuel margin factor: 1.3   Amount of fuel: 39.1 kg

```

![image](https://user-images.githubusercontent.com/1168584/128292863-7a57f71d-30c0-4f16-9536-b545ba82f273.png)

**Comment by mokun** [comment]
> So if you look at the enough capacity method it creates the potential Equipment to estimate the capacity of the Vehicle. These Equipment are not permanent but are reused from a cache. This is a problem as it's not real,y thread safe.

@bevans2000 

I just did a [commit](https://github.com/mars-sim/mars-sim/commit/72372008539896887616a23b90cfc32f71176664) to avoid threading issues by having each settlement storing an instance of Equipment.

I just checked. If it's a temporary equipment (the so-called `equipmentTypeCache` now located in Settlement), there's one and only one equipment of its type, right ?

**Comment by mokun** [comment]
> 1. Stop reusing Equipment which causes an continuous increase in memory
> 2. Rewrite this method so it calculates capacity is a simpler way just based on size.

@bevans2000 

So today, I'll work on a simplified approach for storing resources in containers.

But I won't touch other things such as Settlement, Vehicle, Person, etc. that relies on the Inventory class

**Comment by bevans2000** [comment]
I was thinking more about calculating the required capacity per Storage type (gas, solid, liquid) and then compare that to the expected containers.  Simplify the modelling of storage would be good but it is a big piece of work and difficult to do quickly. It is at the heart of all Units so first there needs some better separation. #306 #348 have a big part to play. 
This whole are needs a major change but it has to be gradual, feels like we should create a Git Project to hold all issues that relate to this area and work an a sensible order to do the changes. 
So for me #306 should be one of the first to just reduce the duplicate methods before starting any remodelling g.

**Comment by mokun** [comment]
> Simplify the modelling of storage would be good but it is a big piece of work and difficult to do quickly

I'm almost done and will commit it soon.
