### ISSUE TITLE
Support multiple Crews

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#410]
Only a single Crew can be applied to the simulation. This limits the pre-configured nature. Allowing multiple crews to be used will enrich the start conditions;
- Crews are assigned to an Initial Settlement
- Crew member placement does not rely on Sponsor but uses the assigned new Settlement
- Crew saved on file system in a "configuration repository"
- Crew Editor to be generic providing a drop down of configured Crews
- Site Editor allows configured Crews to be assigned to initial Settlements

**Comment by mokun** [comment]
Yes and it will be good to add flexibility for dragging and dropping crew members onto various combinations. 

Say, person A may be a good combination with person B, rather than person C.

I still recalled an old PC game called ["Race to Space"](https://archive.org/details/BARISCD).

In it, many crew members are first trained on Earth in preparation for various lunar missions as soon as various hardware become available for assembly.

Then player can choose who to go to which missions afterward.

**Comment by mokun** [comment]
See the [rework](https://github.com/raceintospace/raceintospace) version.

**Comment by bevans2000** [comment]
At first I'll concentrate on getting the modelling correct of Crews being group of people that can be assigned to any Settlement as a complete team. Obviously once done then we can preload some teams that have specialists, e.g. team of scientists, team of engineers.

**Comment by bevans2000** [comment]
All these changes are completed on a fork:
- Multiple crews can be managed and stored
- Big rework of the Crew Editor that can edit any of the stored crews and create new ones
- Crew Editor can add and remove Membes from a crew
- Crews now have a description field
- The Initial Settlement details now takes an optional Crew
- Settlement Builder allocates Crew members to the assigned Settlement, it is possible for Members to inherit the Sponsor of the owning Setflement
- Site Editor has a new Crew column to allow Crew tk be optionally assigned

When i get back from holiday I will, create a Pull Request

**Comment by mokun** [comment]
I have wanted to create two panels and have  buttons in the middle to move crew members from left panel to right panel. The left panel is a pool of candidates. The right panel is where the team is assembled.

**Comment by mokun** [comment]
Good thinking that you add the new `Crew` column in the Site Editor so that Player may choose which settlement to load what crew.

**Comment by bevans2000** [comment]
Next step is to allow the saving of different Initial Settlements as in #411
