### ISSUE TITLE
Create a Scenario concept by isolating the initial Settlements

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#411]
Separate the initial settlement details from the settlments.xml file into a scenario.xml. "Fixed" aspects such as templates will stay in the settlments.xml.
Scenario will be:
- Have a name & description
- Defines a set of Initial Settlements & Arriving Settlements
- Have a `Scenario` class within the code base to encompass the initial set-up
- Site Editor modified to the allow saving of Scenarios
- Support command line & Console options to select a saved Scenario
-  Have an export feature to allow Scenarios to be shared

**Comment by mokun** [comment]
@bevans2000 

I discover that if we start a Delivery or Trade mission manually in Mission Tool, we would have this UI window where we can move items from the left table to the right table.

![image](https://user-images.githubusercontent.com/1168584/131206951-85a3c362-72af-4826-b500-1274e1f5e473.png)

I see we can create something similar in choosing which settlers will be assembled into a team 

Then we may send various teams to a scenario. 

`TradeGoodsPanel` and `DeliveryGoodsPanel` the two classes that create the window above.

**Comment by bevans2000** [comment]
Certainly an option for a later release. Maybe we just need the ability to move Members between Crews instead of having a repository.
