### ISSUE TITLE
Relocate Reporting Authority pre-configured names

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#412]
The Equipment & Settlement names that are pre-configured for a Reporting Authority reside inside the equipment & settlement XML files. To make the addition of new Reporting Authorities easier these names should be oved into the governance.xml and hence the `ReportingAuthority` class.

**Comment by bevans2000** [comment]
So if we did want to go down this route then we should base it on Country for a start. Such bespoke logic should not be coded. The increased preference should be totally configurable either in food.xml or people.xml. I would add an optional countryfavourite attribute to food items then add Japan as a favourite for Sushi. There are probably other combinations.

**Comment by bevans2000** [comment]
Sure but if someone likes a particular food it is likely to be based on the Country of the Person; not their Sponsor. So Persons from Japan would prefer Sushi whether their sponsor is MS or SPACEX. To model special preferences it is better use the Country of birth that who you work for.

**Comment by mokun** [comment]
> To model special preferences it is better use the Country of birth that who you work for.

Ok so I guess it makes sense for a person to choose the preference based on either the country of origin or the sponsor. 

But for our sanity, we can default that to either one. 

We can also provide a way for the player to change it in the Favorite / Preference tab

**Comment by mokun** [comment]
Do you feel like we should show in the Site Editor the full sponsor's name or just the abbreviation ?

Similary, now in console, it shows, 

```
MarsNet >  ​/se
                  Name | Sponsor |     Template | Population
------------------------------------------------------------
              Ares One | ReportingAuthority [code=NASA] |    Phase 2-U |          8
                Europa | ReportingAuthority [code=ESA] |    Phase 2-E |          8
            Tian Cheng | ReportingAuthority [code=CNSA] |    Phase 2-C |          8
           New Pompeii | ReportingAuthority [code=ISRO] |    Phase 2-I |          8
               Kyocera | ReportingAuthority [code=JAXA] |    Phase 2-J |          8
              Starcity | ReportingAuthority [code=SPACEX] |    Phase 3-X |         12
                Zvezda | ReportingAuthority [code=RKA] |    Phase 3-R |         12
    Schiaparelli Point | ReportingAuthority [code=MS] |   Alpha Base |         24

MarsNet >  ​	
```

**Comment by bevans2000** [comment]
My goal here is to make Reporting Authority a User configurable item like Crews & Scenarios. There will be some pre-defined Authorities but a user can add and save their own. These could be referenced by a custom Scenario.
We need a feature to export and import a Scenario as well.

**Comment by mokun** [comment]
> My goal here is to make Reporting Authority a User configurable item like Crews & Scenarios. 

Sure. 

> There will be some pre-defined Authorities but a user can add and save their own. 

That's a good point. We can have some standard governing body such as "United Moon Colonies" (UMC) , etc. as built-in authorities. 

Then of course, we want to provide a way to include user defined authorities from xml.

> These could be referenced by a custom Scenario.

Yea we're talking about separate features 
1. authorities (built-in vs. xml defined)
2. scenario (built-in vs. xml defined)
3. crew (built-in vs. xml defined)
 
> We need a feature to export and import a Scenario as well.

When you say "feature", do you mean an UI window ?

**Comment by bevans2000** [comment]
Yes I mean new features to the existing SimulationConfigEditor. This is becoming a ScenarioEditor in reality.  I would also see the potential for a Reporting Authority Editor UI as well. Once done we may want to cut back on the Reporting Authorities we provided bundled with the release.

**Comment by bevans2000** [comment]
I've been working on a ReportingAuthority editor as part of this issue.  This will allow users to create and manage their own Reporting Authority that can be used in their own Scenarios. Still needs some work on the layout. 
![image](https://user-images.githubusercontent.com/20720166/131225199-b773abe7-9b17-4406-af2a-4f3109e83006.png)

**Comment by mokun** [comment]
> ReportingAuthority editor as part of this issue. This will allow users to create and manage their own Reporting Authority that can be used in their own Scenarios

That's awesome ! 

So the hard part is how to connect the agenda and objective of each authority to what bonus they get.

Q: what these bonuses do we envision that will impact tasks, missions and operations of a settlement and its settlers, etc ?

**Comment by bevans2000** [comment]
Yes I'm nearly there with it. Been super busy at work last week so had little time. Just need to fix the layout issue then j can create a pull request.
Yes so his does the MissionAgenda benefit a Settlement. In fact should it give any benefit?  I think it should influence the priority kn different missions and scientific studies. The latter is at there at the moment.
