### ISSUE TITLE
Optimize UIConfig

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#414]
**Describe the bug**
1. Sonarcloud listed the use of SAXBuilder in UIConfig as having security vulnerability.
2. UIConfig doesn't check for the presence of the second LCD monitor.

**Expected behavior**
1. Having an external DTD declaration file is having security risk.
    -- Solution : Use internal DTD embedded within the xml file.
2.  One solution is to save the location of the Main Window on both the first LCD monitor and the second LCD monitor. 
    -- If the second monitor is connected and then display the Main Window there. 
    -- If the second monitor has been disconnected, open the Main Window on the first monitor.

**Screenshots**
We should be able to eliminate the need for having a standalone `ui_settings.dtd` file
![image](https://user-images.githubusercontent.com/1168584/128387996-272c555f-a3c4-41a6-bcb5-a4e518b13aa8.png)

**Desktop (please complete the following information):**
 - build 6083

**Comment by mokun** [comment]
@bevans2000 

> This commit adds strange behaviour to the UI. Mine didn't appear for 10 minutes until I realised there was a Yes/No dialog hidden under the splash screen. 

Sorry about that. May be we can change the modality to make it show up on the top of application.

**Comment by mokun** [comment]
> Feels wrong that the user is asked to confirm they want to use a saved UI configuration. 

In my windows 11 machine, when I unplug a monitor and plug in another monitor. It confuses it enough that the main window would pop up in some sort of lala land. While the session keeps running, I cannot open the main window. It still exists as shown in the task bar.

**Comment by mokun** [comment]
> We should have a safe mode (new command line argument) instead where the UI Config is ignore. or a timeout on the question at least.

Hmmm. but how do I detect the problem in the code in the first place ?

**Comment by mokun** [comment]
Note that this affects the multi monitor setup only. 

If you have 2 or 3 monitors connected to one computer, you can test it as well.

That's why I'd like to proactively ask a player to choose whether he wants to use the last saved UI config.

Normally, one would choose yes. 

But if it can't be loaded up, then next time choose no to bypass loading the default window frame location saved in the ui config xml files.

**Comment by bevans2000** [comment]
I see. So could we just define the size of the main window but not the position and leave it to the OS to position it?

**Comment by mokun** [comment]
> could we just define the size of the main window but not the position and leave it to the OS to position it?

But how do we leave it to the OS to position it ? 

I guess in Java beside calling setSize(), we do need to call setLocation() for each window, right ?

**Comment by bevans2000** [comment]
I believe it normally allows the OS to position the window itself if no position is defined.

**Comment by bevans2000** [comment]
Actually I can't get the Monitor Tool to appear now unless I delete my ui_defaults before starting. 
There is a null pointer being thrown somewhere inside the UI that is killing the MonitorWindow constructor.
```
		setSize(new Dimension(mainWindow.getSelectedSize().width - 20, HEIGHT));
```
This line is throwing a NPE because getSelectedSize return null

**Comment by mokun** [comment]
> This line is throwing a NPE because getSelectedSize return null

It's fixed now

**Comment by mokun** [comment]
Now I'd like to add the "Quick Start" feature. 

Instead of selecting 1, 2, 3 in the console, choosing yes will directly start the default simulation.

**Comment by bevans2000** [comment]
Surely the command line -new should do this action? If it has -new then start the default Scenario or one specified. Same with the ui config, I don't know of another tool that asks if I want to use a saved configuration. We need to identify the root cause of the problem.

**Comment by bevans2000** [comment]
That sounds good, I have wanted to add this to the new argument.  Also if a Scenario is defined that will override the default one.

**Comment by bevans2000** [comment]
Is this done now? I optimised the UIConfig as part of #801

**Comment by mokun** [comment]
It still doesn't well in case of determining the starting location of the main windows we'll in case of having 3 monitors.

**Comment by bevans2000** [comment]
Ok, let's leave it open. I might have a look using my second monitor

**Comment by mokun** [comment]
I had this lately : 

> 01-Adir-01:019.777 (Warning) MainDesktopPane : Perserved Unit cannot be found


I can see in MainDesktopPane's openInitialWindows() as follows : 

```java
	/**
	 * Opens all initial windows based on UI configuration.
	 */
	public void openInitialWindows() {
		List<WindowSpec> startingWindows = mainWindow.getConfig().getConfiguredWindows();

		if (!startingWindows.isEmpty()) {
			UnitManager uMgr = mainWindow.getDesktop().getSimulation().getUnitManager();
			for(WindowSpec w : startingWindows) {
				switch(w.type()) {
					case UIConfig.TOOL:
						openToolWindow(w.name());
					break;

					case UIConfig.UNIT:
						Unit u = UnitWindow.getUnit(uMgr, w.props());
						if (u != null) {
							openUnitWindow(u, w);
						}
						else {
							logger.warning("Perserved Unit cannot be found");
						}
					break;
				}
 			}
		}
		else {
			if (mode == GameMode.COMMAND) {
				// Open the time window for the Commander Mode
				openToolWindow(TimeWindow.NAME);
				openToolWindow(CommanderWindow.NAME);
			}

			else {
				openToolWindow(GuideWindow.NAME);
			}
		}
	}
```

When I start a brand new simulation and choose to use the previous UI setting, it would load up all the previous unit that pops open when saving.

Is it reasonable to do so when starting a brand new sim ?

**Comment by bevans2000** [comment]
Yes because it's good to see the same unit in the new sim. If you change scenario it can occur. Just remove the warning message

**Comment by mokun** [comment]
> Yes because it's good to see the same unit in the new sim. 

So is it for debugging ?

**Comment by bevans2000** [comment]
> > Yes because it's good to see the same unit in the new sim.
> 
> So is it for debugging ?

Sort of but it's all part of preserving the UI layout between runs. Just take out the warning message.

**Comment by bevans2000** [comment]
Warning message removed

**Comment by mokun** [comment]
Eclipse is still showing the DTD warning message. I suppose codesmell have it as a security risk also.

**Comment by mokun** [comment]
@bevans2000 

Can you find way on how to save the zoom state of the settlement map ? 

Right now, after I start a new sim or load from a sim and open the settlement map, the zoom setting would sudden jump *erratically*. 

That's because the initial zoom value is in conflict with the saved value or the lack of it.

**Comment by bevans2000** [comment]
Yes totally. I will take a look

**Comment by bevans2000** [comment]
What is the goal in this issue for 3.7.0? To save the zoom state?
Anything else should be a new issues because this issues is covering too many different goals.

**Comment by mokun** [comment]
ok. I'll close this thread now. 

Let's open a brand new thread for saving the zoom state for the Settlement Map

**Comment by mokun** [comment]
Just fixed the zoom slider scale issue [here](https://github.com/mars-sim/mars-sim/commit/9bd7d3a6322f21fcbd12c93e4d334d352e26db3d).

**Comment by mokun** [comment]
@bevans2000 

Lately, I haven't been able to get UIConfig saved my tools and panel's position within the main window, even though I tried manually saving a simulation.

How do we trap any any issues it may have encountered when saving or loading panel positions for debugging ? 

Currently, it doesn't show exceptions, if it has any.

**Comment by bevans2000** [comment]
Check you ui config is being updated on exit first. This will help understand if its a saving problem or a loading problem.
