### ISSUE TITLE
3 methods with highest CPU usage

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#416]
For a 4-person settlement, below are the 3 methods with the highest CPU usage

![image](https://user-images.githubusercontent.com/1168584/128614027-5da675fb-0e89-47e7-8092-cdaa9d66264c.png)

1. ResourceProcess.processResources() 
   -- Inventory.storeAmoutnResource()
   -- Inventory.retrieveAmoutnResource()
2. Farmining.timePassing()
   -- Crop.timePassing
      --- Crop.computeharvest()
3. GoodsManager.determineGoodValue()
    -- GoodsManager.determineItemResourceGoodValue()
    -- GoodsManager.determineAmountResourceGoodValue()

**Comment by bevans2000** [comment]
Farming is dependent upon the number of crops planted. So large greenhouses take more CPU.

**Comment by mokun** [comment]
Another sampling : 
![image](https://user-images.githubusercontent.com/1168584/128615265-98d13b18-4172-4f96-ab30-f9de7a333ae8.png)

We've reduce GoodsManager's isLocallyConstructable() percentage in this [commit](https://github.com/mars-sim/mars-sim/commit/08cd06de93dfc3427cc227268bd3af95596589e0), 

I'm gonna tackle on GoodsManager.getEstimatedOrbitRepairParts().

**Comment by bevans2000** [comment]
ItemResourceUtil will be lookup for parts by name but if we consolidate with single way to reference items & resources. Once loaded there should be no need to use names, we should be able to use the identifier directly.

**Comment by mokun** [comment]
After this [commit](https://github.com/mars-sim/mars-sim/commit/ca3bd11720f2db09996ee2f516a21ad798453dcd)

GoodsManager is no longer stressing out the CPU. But we need to reduce other intensive work if we ever want to port it to portable device such as Android or iOS.

![image](https://user-images.githubusercontent.com/1168584/128615938-6b7d1d96-6587-46d6-9df2-3fa0adadd463.png)

**Comment by bevans2000** [comment]
Looks much better

**Comment by mokun** [comment]
Out of all the methods being sampled, the following 2 in retrieveAmountResource() in Inventory are the most used ones now : 

1. setAmountResourceCapacityCacheAllDirty(false); // occupies 8.1% + 11.1% + 4.2% + 2.6% + 2.1% + 0.3% of all cpu utilization
2. setAmountResourceStoredCacheAllDirty(false);    // occupies 7.7% + 10.4$ + 3.3% + 1.7% + 1.7% + 0.2% of all cpu utilization

**Comment by mokun** [comment]
1. setAmountResourceCapacityCacheAllDirty(false); 
   -- setCacheDirty()
       --- setAmountResourceCapacityCacheAllDirty()
   -- setAmountResourceCapacityCacheDirty()

2. setAmountResourceStoredCacheAllDirty(false)
   -- setCacheDirty()
       --- setAmountResourceStoredCacheAllDirty()
   -- setAmountResourceStoredCacheDirty()

**Comment by bevans2000** [comment]
To be honest I dont really understand the logic about the 'dirty' cache inventory.

**Comment by mokun** [comment]
> To be honest I dont really understand the logic about the 'dirty' cache inventory.

My best guess is that when we cache the changes of a resources within a certain period of time, instead of precisely exchanging the exact amount of that resource, the Inventory class would simply add and subtract from the cache, without having to check if there's enough. It can tolerate negative amount.

We kind of using a buffering or caching strategy in dealing with the excessive heat in Heating class but for different situation and reason.

**Comment by mokun** [comment]
> 'dirty' cache inventory.

I asked Scott once or twice in the past on when to use the dirty cache because it doesn't give accurate amount of a resource when using it.

I agree that maintainability of Inventory is becoming a nightmare when all those setting and resetting dirty caches (on top of resetting regular caches).

We may as well disable all the dirty caches.

**Comment by mokun** [comment]
Btw, on build 6100, after a number of optimization, including the [lightweight inventory](https://github.com/mars-sim/mars-sim/issues/348) for containers, we are now using a lot less heap memory. See below: 

The tick per second is a little faster but it's a big reduction of memory : 

![image](https://user-images.githubusercontent.com/1168584/128798090-e2c358e4-2459-4a48-beec-31b36c6a4980.png)
