### ISSUE TITLE
The use of Mars and MarsSurface as an Unit

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#417]
Currently, MarsSurface class extends Unit and is functionally different from Mars class 

Q1: Does MarsSurface need to be initialized to have *General Capacity*, like a settlement ?

Q2: Should any settlements, mining towns, weather stations be logically *stored* onto MarsSurface ?

Below is the what we have so far in the constructor of MarsSurface : 
```java
/**
 * MarsSurface is the object unit that represents the surface of Mars
 */
public class MarsSurface extends Unit implements Serializable {

	/** default serial id. */
	private static final long serialVersionUID = 123L;
	
	private static final String NAME = "Mars Surface";
	
	public MarsSurface() {
		super(NAME, null);
		
		setContainerUnit(null);
		setContainerID(Unit.OUTER_SPACE_UNIT_ID);
				
		getInventory().addGeneralCapacity(Double.MAX_VALUE);
		
		// This is hack playing on how the identifiers are created
		if (getIdentifier() != Unit.MARS_SURFACE_UNIT_ID) {
			throw new IllegalStateException("MarsSurface has wrong ID: " + getIdentifier());
		}
	}
...
}
```

**Comment by mokun** [comment]
@bevans2000 

Currently the class Mars is an odd ball. It creates three instances, namely, MarsSurface, SurfaceFeature, and OrbitInfo.

```java
public class Mars implements Serializable, Temporal {

	/** default serial id. */
	private static final long serialVersionUID = 1L;

	/** Mars average radius in km. */
	public static final double MARS_RADIUS_KM = 3393D;

	public static final double MARS_CIRCUMFERENCE = MARS_RADIUS_KM * 2D * Math.PI;

	// Data members
	/** Martian weather. */
	private Weather weather;
	/** Surface features. */
	private SurfaceFeatures surfaceFeatures;
	/** Orbital information. */
	private OrbitInfo orbitInfo;
	/** Mars Surface as a unit container */
	//private transient MarsSurface marsSurface;
	
	/**
	 * Constructor.
	 * 
	 * @param clock The Mars clock
	 * @throws Exception if Mars could not be constructed.
	 */
	public Mars(MarsClock clock) {
		// Initialize mars surface		
		//marsSurface = new MarsSurface();
		// Initialize orbit info
		orbitInfo = new OrbitInfo(clock);
		// Initialize weather
		weather = new Weather(clock, orbitInfo);
		// Initialize surface features
		surfaceFeatures = new SurfaceFeatures(clock, orbitInfo, weather);
		// Cyclic dependency !!!!
		weather.initializeInstances(surfaceFeatures);
	}
...
}
```
	




I'll rename Mars class to MarsEnvironment to fit what it currently does.

Will also rename the package domain from *org.mars_sim.msp.core.mars* to *org.mars_sim.msp.core.environment* 

Other than calling it Environment, is there a better terminology we can use ?

**Comment by mokun** [comment]
@bevans2000 ,

Actually we already commented out creating MarsSurface here.

**Comment by bevans2000** [comment]
Are you creating a common base class like Planet ? There should be no need for an explicit class on Earth, Mars & Moon. These should be instances of the same class.

**Comment by mokun** [comment]
> Are you creating a common base class like Planet ? There should be no need for an explicit class on Earth, Mars & Moon. These should be instances of the same class.

Sure. We can try this approach to see how it fares.  It would have limitations in future when we have to constantly reference it, right ?

**Comment by bevans2000** [comment]
I'm not sure of what changes you are planning but from a modelling perspective they have a lot of similarities.

**Comment by bevans2000** [comment]
Can we close this or move it to a new milestone?
