### ISSUE TITLE
Removing dangling missions

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#418]
**Describe the bug**
- Currently, it's still error prone in leaving dead missions in Mission Tool (see screenshot below)
-- One has to make sure endMission() in Mission would set `done = true`.
-- First, it's timePassing() in MissionManager would call cleanMissions() in every frame. Is it necessary to call it so frequently ? 
-- Second, it's cleanMissions() in MissionManager that removes unapproved, unfinished and completed missions from the `onGoingMissions` list by calling removeMission(). To do so, one has to make sure it would catch a particular type of `MissionStatus` enum.
-- At last, removeMission() in MissionManager is responsible for removing the mission listeners. 

**Questions**
- Q1. Should we keep a log of these unfinished or partially done missions ?
- Q2. What is the better way to end a mission gracefully in Mission, in light of the progress of each of these missions  ?  

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/129150169-2b2cea3b-4e90-4ada-93e4-14ec8c08bfc1.png)

**Desktop**
Build 6104

**Additional context**
```java
	/**
	 * Remove missions that are already completed.
	 */
	private void cleanMissions() {
		int index = 0;		
		if (onGoingMissions != null && !onGoingMissions.isEmpty()) { 
			// Check if onGoingMissions is null for passing maven test
			while (index < onGoingMissions.size()) {
				Mission m = onGoingMissions.get(index);
				List<MissionStatus> mss = m.getMissionStatus();
				if (mss != null && !mss.isEmpty()) {
					for (MissionStatus ms: mss) {
						if (m.isDone()
		//						|| !m.isApproved() // initially it's not approved until it passes the approval phase
								|| m.getPlan() == null
								|| m.getPhase() == null
								|| (m.getPlan() != null && m.getPlan().getStatus() == PlanType.NOT_APPROVED)								
								|| ms == MissionStatus.CANNOT_ENTER_ROVER				
								|| ms == MissionStatus.CANNOT_LOAD_RESOURCES									
								|| ms == MissionStatus.DESTINATION_IS_NULL		
								|| ms == MissionStatus.EVA_SUIT_CANNOT_BE_LOADED						
								|| ms == MissionStatus.LUV_ATTACHMENT_PARTS_NOT_LOADABLE				
								|| ms == MissionStatus.LUV_NOT_AVAILABLE
								|| ms == MissionStatus.LUV_NOT_RETRIEVED
								|| ms == MissionStatus.MINING_SITE_NOT_BE_DETERMINED
								|| ms == MissionStatus.NEW_CONSTRUCTION_STAGE_NOT_DETERMINED
								|| ms == MissionStatus.NO_AVAILABLE_VEHICLES
								|| ms == MissionStatus.NO_EXPLORATION_SITES
								|| ms == MissionStatus.NO_RESERVABLE_VEHICLES								
								|| ms == MissionStatus.NO_TRADING_SETTLEMENT
								|| ms == MissionStatus.USER_ABORTED_MISSION
//								|| ms.getName().toLowerCase().contains("no ") // need to first enforce standard
//								|| ms.getName().toLowerCase().contains("not ") // need to first enforce standard
								) {
							removeMission(m);
						} 
					}
				}
				
				index++;
			}
		}
	}
```

**Comment by mokun** [comment]
@bevans2000 ,

I just added `m.isDone()` above in cleanMissions() in MissionManager in the last [commit](https://github.com/mars-sim/mars-sim/commit/97d2a9a3646f48d8f657fcae9e503f939f3bf542). 

It could be counterproductive since it will REMOVE ALL completed mission as soon as it's over.

Do we want to see what missions each settlement has accomplished ? Should we keep a log of all missions that are even partially done or aborted ?

If we do, I'll need to comment it out.

**Comment by bevans2000** [comment]
I think it is good to see completed missions so they should stay.. Probably they should be purged after a  number of sols so it doesn't get out of hand. Non approved missions should definitely be removed.

**Comment by mokun** [comment]
Guess what we are doing currently is keeping the full blown Mission object, right ?

What if we create a separate mission log class for just storing crucial piece of info on each mission ?

**Comment by mokun** [comment]
So we're keeping a list of `onGoingMissions` and also `historicalMissions`. 

```java
public class MissionManager implements Serializable, Temporal {

	/** default serial id. */
	private static final long serialVersionUID = 1L;

	/** default logger. */
	private static transient Logger logger = Logger.getLogger(MissionManager.class.getName());
	private static String loggerName = logger.getName();
	private static String sourceName = loggerName.substring(loggerName.lastIndexOf(".") + 1, loggerName.length());
	
	private static final double PERCENT_PER_SCORE = 10D;
	/** static mission identifier */
	private int missionIdentifer;

	/** Mission listeners. */
	private transient List<MissionManagerListener> listeners;

	/** The currently on-going missions in the simulation. */
	private List<Mission> onGoingMissions;
	/** A history of mission plans by sol. */
	private SolListDataLogger<MissionPlanning> historicalMissions;
	
	private static List<String> missionNames;
	private static List<String> travelMissionNames;
	private static Map<String, Integer> settlementID;
	
	// Note : MissionManager is instantiated before MarsClock
	private static UnitManager unitManager = Simulation.instance().getUnitManager();
...
}
```

**Comment by mokun** [comment]
@bevans2000 

I sometimes see a blank line appears in the Mission Tool for a second. Then it vanishes automatically shortly after, as if it gets deleting in MissionManager. 

Have you seen that before ?

**Comment by bevans2000** [comment]
Yes and also in the Person Monitor window on Task. I think this is because we clear the name and description fields when ending Tasks and maybe Missions. These is no need to clear these. However I think some code is checking the description is null which is bad and we should remove it. We have a status property so that should.d be sufficient.
