### ISSUE TITLE
annoying pause window

### ISSUE THREAD

**Issue by Musickiller** [mars-sim/mars-sim#42]
Screenshot: https://yadi.sk/i/Z9tI8x3w3GMVvK
I don't think I really need to add anything. That thing is above all windows on my Linux (pun not intended). It may be caused by an incompatible java version - I don't know, have not run this OS for months, and for Arch it's very bad news.

And even if it was not above all windows, there is no need for such a big thing to indicate that there is a pause. May be I hit the pause only to read some help? And this thing does not allow me to do that comfortably. Personally, I would be much more comfy with a small "||" symbol near current time/date indicator.

P.S. I'm so glad you've transferred the project to GitHub - so much better that SourceForge!

**Comment by mokun** [comment]
Good point! 

In Java 7, Modality works well. Somehow Java 8's Modality for its Stage class behaves differently. 

My intent is to "block" only mars-sim and make it stay on top of mars-sim but not on top of other windows or applications

I have hoped to find a way to work around its limitation but now I'm going to get rid of the blue pause box. 

And I'll figure out a way to display "||" somewhere.

> transferred the project to GitHub - so much better that SourceForge!

Yes GH much more modern than SF!

**Comment by mokun** [comment]
Disabled the blue pause box in [r3903](https://github.com/mars-sim/mars-sim/commit/cce6267ccd1c3d7aa00ad807ca8e3365ec7b9180) but still looking for a place to display the "||" or the word "[PAUSE]" sign.

**Comment by mokun** [comment]
closed
