### ISSUE TITLE
~3% CPU at Main Menu 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#422]
After starting mars-sim, while it's still awaiting input at the console main menu, it's using ~3% CPU on my i7 quad core laptop.

![image](https://user-images.githubusercontent.com/1168584/130867985-3c374a89-709b-4b2b-b8d9-c46891cce57d.png)

![image](https://user-images.githubusercontent.com/1168584/130868263-289f42b6-75d9-4562-8390-253754ca977b.png)

Can the CPU utilization be lowered since it's only pooling and not doing anything ?

Can the splash window display be optimized ?

**Comment by mokun** [comment]
@bevans2000 

Is there a way to lower the CPU while running the Splash Window on the background ? 

![image](https://user-images.githubusercontent.com/1168584/176973072-4045fbf9-08fc-43ba-93ba-2bfec724d3b1.png)

**Comment by bevans2000** [comment]
3% is pretty low and it's probably not worth the effort to try to get it any lower.

**Comment by mokun** [comment]
It's done. Closing it.
