### ISSUE TITLE
Cannot calculate probability in TendGreenhouseMeta/No resource processing in Mining Outpost

### ISSUE THREAD

**Issue by Musickiller** [mars-sim/mars-sim#43]
I'm not sure that it is a problem at all. if it is not - let's just close it.

So.. I have started with 1 lvl 1 base 4 ppl and 6 bots and a strange problem appeared in the console (there are usually many of them if you start with settings different from default).

E:\Games\MarsSim>java -jar 3904.jar 4
Command: java -Djava.util.logging.config.file=logging.properties -cp .;*;jars\*
org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx1536m -new
OUTPUT>Mar 28, 2017 2:27:50 PM(INFO) main.javafx.MarsProjectFX Mars Simulation P
roject v3.1.0 - Build 3902 - 64-bit 1.8.0_121 - 2 CPU threads
OUTPUT>Mar 28, 2017 2:27:50 PM(INFO) main.javafx.MarsProjectFX Starting a new si
m in GUI mode in Windows 7
OUTPUT>Mar 28, 2017 2:27:51 PM(INFO) ui.javafx.mainmenu.SpinningGlobe JavaFX 3D
features supported
OUTPUT>Mar 28, 2017 2:28:32 PM(INFO) core.time.MasterClock CPU Benchmark 1 : 302
40 ms
OUTPUT>Mar 28, 2017 2:28:32 PM(INFO) core.structure.Settlement Setting Alpha Bas
e's Objective to Crop Farm
OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager GardenBot 001 ends up goin
g to Alpha Base since Schiaparelli Point doesn't exist.
OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager MakerBot 002 ends up going
 to Alpha Base since Schiaparelli Point doesn't exist.
OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Karen Andersen ends up goi
ng to Alpha Base since Schiaparelli Point doesn't exist.
OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Rik Declercq ends up going
 to Alpha Base since Schiaparelli Point doesn't exist.
OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Leonardo DaVinci ends up g
oing to Alpha Base since Schiaparelli Point doesn't exist.
OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Lena LaGranda ends up goin
g to Alpha Base since Schiaparelli Point doesn't exist.
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta GardenBot 001 cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta GardenBot 003 cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta Karen Andersen cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta Leonardo DaVinci cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta Karen Andersen cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta Karen Andersen cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta Leonardo DaVinci cannot calculate probability : null
OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
ta Leonardo DaVinci cannot calculate probability : null

**Comment by mokun** [comment]
> OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager GardenBot 001 ends up goin
> g to Alpha Base since Schiaparelli Point doesn't exist.
> OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager MakerBot 002 ends up going
> to Alpha Base since Schiaparelli Point doesn't exist.
> OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Karen Andersen ends up goi
> ng to Alpha Base since Schiaparelli Point doesn't exist.
> OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Rik Declercq ends up going
> to Alpha Base since Schiaparelli Point doesn't exist.
> OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Leonardo DaVinci ends up g
> oing to Alpha Base since Schiaparelli Point doesn't exist.
> OUTPUT>Mar 28, 2017 2:28:33 PM(INFO) core.UnitManager Lena LaGranda ends up goin
> g to Alpha Base since Schiaparelli Point doesn't exist.

The above lines are reasonable since you deleted the default "Schiaparelli Point". By default, they have to go somewhere.

> OUTPUT>Mar 28, 2017 2:28:34 PM(SEVERE) core.person.ai.task.meta.TendGreenhouseMe
> ta xxx cannot calculate probability : null

I haven't seen this for a long time. Does it happen only once ? Did you create Mars Direct Base (Phase 1) ?

**Comment by Musickiller** [comment]
> Did you create Mars Direct Base (Phase 1) ?

Yes, I think so. I'll test it again when I get back home.

**Comment by mokun** [comment]
I'm not able to reproduce this so far on my machine. If a person or a bot cannot calculate probability, then their TaskManager/BotTaskManager class is not working.

**Comment by mokun** [comment]
I found the culprit. It's when the user creates a Mining Outpost. 

Since there's no greenhouse in a Mining Outpost, no one needs to tend crops. 

I'm fixing TendGreenhouseMeta now so that when this task is being called out, it won't give anyone NullPointerException.

**Comment by Musickiller** [comment]
Currently impossible to reproduce on my machine due to great number of other errors in the last build.

**Comment by mokun** [comment]
I just fixed two issues in one shot when creating either Mining Outpost or Trading Outpost

(1). NullPointerException due to running TendGreenhouse/TendGreenhouseMeta when no preconfigured greenhouse is available in Mining/Trading Outpost template. 

I also remove the preconfigured Gardenbot for either template and send another type of bots instead.

(2). NullPointerException due to when creating Mining Outpost. It complains about the lack of resource processing (carbon scrubbing black/grey water treatment, etc.). 

I just need to add the ability of doing resource processing in the building Outpost Hub.

**Comment by mokun** [comment]
[r3915.jar.z](https://www.dropbox.com/s/5mi83fqfpyqj3fk/3915.jar.7z?dl=0)

**Comment by mokun** [comment]
closed.
