### ISSUE TITLE
Arriving Settlement should be part of a Scenario

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#431]
**Is your feature request related to a problem? Please describe.**
Arriving settlements are defined in a fixed global configuration and applied to all new simulations. These should be customisable for each new simulation oif required.

**Describe the solution you'd like**
Arriving Settlements should be part of a Scenario so they can be tailored fir the initial Settlements and Reporting Authority. This requires a change to the storage of Scenarios in XML as well as the simulation config editor. Crews should be allowed to be attached to arriving settlements as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by mokun** [comment]
So, during the simulation, what tool will be used to track which Arriving Settlements will be established ? 

is it `Resupply Tool` ? 

Currently, `Resupply Tool` tracks resupply missions for existing settlement.

Interestingly, it can also be used for creating new Arriving Settlements.

**Comment by bevans2000** [comment]
Hadn't thought that far ahead but the Resupply Tool makes sense.
