### ISSUE TITLE
Security Hotspot - PRNG

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#433]
According to Sonarcloud, it's a big security risk for using `Random`, instead of `SecureRandom` class.

![image](https://user-images.githubusercontent.com/1168584/132064895-61481c73-879b-44fb-a68a-ff41a3bdac09.png)

See `RandomUtil` class below: 

![image](https://user-images.githubusercontent.com/1168584/132064977-a97674a6-e650-4ced-b16d-64e3b1035ef7.png)

We're using an apache lib that uses it as well in `MarsProjectHeadless` below : 

![image](https://user-images.githubusercontent.com/1168584/132065297-7205f840-b1c6-4e9f-9d1e-ca30e7624103.png)

Shall we switch to `SecureRandom` ? 

https://docs.oracle.com/javase/8/docs//api/java/security/SecureRandom.html

This StackOverflow [page](https://stackoverflow.com/questions/1461568/is-securerandom-thread-safe) is discussing whether `SecureRandom` is thread safe and its method is synchronized or not.

**Comment by mokun** [comment]
@bevans2000 , 

We make a lot of calls to RandomUtil class in every millisol.

So I wonder if we can **cache** some of the common values for a short period of time.

**Comment by bevans2000** [comment]
I'm not sure I understand what you mean by caching the values. To be honest I would not worry about the security of Random. Because we are multi threaded the synchronised in the Random could cost time blocking threads. K did think about using a ThreadLocal so sacha Thread gets it's own copy and removes the conflict altogether.

**Comment by mokun** [comment]
> I'm not sure I understand what you mean by caching the values. To be honest I would not worry about the security of Random.

Sure. it's not much of a security risk per se in our case.

Now the question is, do we want to remove the E grade in sonarcloud because of that ?

**Comment by mokun** [comment]
@bevans2000 

I just switched to using SecureRandom class. 

It's good to re-seed once in a while but they said using `SecureRandom.getInstanceStrong()` method to create the instance would be potentially threads blocking when re-seeding.

**Comment by bevans2000** [comment]
To be honest I don't think there is anything wrong with the old approach. We don't need cryptographically strong random numbers.
I'm sure we can tell Sonarqube to ignore this or just ignore it. Is SecureRandom thread safe?

**Comment by mokun** [comment]
> I'm sure we can tell Sonarqube to ignore this or just ignore it. 


> Is SecureRandom thread safe?

Yes. For us, the initial seed should be good for the entire simulation session. 

But we can re-seed once in a while if we want to so as to ensure the randomness.

They are saying that if someone is to re-seed during the application, depending on the algorithm, it can be thread blocking.

**Comment by bevans2000** [comment]
Therefore if you want to reseed do it in the method ```UnitManager.timePassing``` before it passes the pulse to the Settlement Executors. At this point there is only 1 thread using the random.

**Comment by Urwumpe** [comment]
I am also all for disabling the warning. This isn't a security issue, this isn't a security context. I am not even sure, that we require a high-quality PRNG at all. If at all, I would care about how the random numbers are distributed. Are they evenly distributed, when we expected it? Is there a Gaussian distribution, when we expect this result? Etc.

I think we don't mind if the numbers are not perfectly random.

**Comment by bevans2000** [comment]
The other aspect is ```SecureRandom``` is 30-50x slower than ```Random```.. Certainly since my last rebase I have noticed it feels slower.  https://www.techiedelight.com/difference-java-util-random-java-security-securerandom/ see item 6.
We don't  need the uniqueness in our Random numbers. I think we some change it back to ThreadRandom (?) and I'll take care of SonarQube not to flag the error.

**Comment by mokun** [comment]
> I'll take care of SonarQube not to flag the error.

Yes please do !

> change it back to ThreadRandom (?)

Yes I'd like to try out other better algorithms out there that are thread-safe and faster than Java Random or ThreadLocal.

**Comment by mokun** [comment]
> I think we don't mind if the numbers are not perfectly random.

True... if one day we ever got to the point of merging mars-sim development into some sort of blockchain-type metaverses, then we will need to be cryptographically safe :D

**Comment by mokun** [comment]
> Is there a Gaussian distribution,

Yes I'd say our old `RandomUtil` does generate a reasonably good gaussian distribution but since by definition its output range is between positive infinity and negative infinity, we have to exercise extreme caution when using it.

**Comment by mokun** [comment]
Here's the difference between MersenneTwister and MersenneTwisterFast:


*MersenneTwister* is a drop-in subclass replacement for java.util.Random. It is properly synchronized and can be used in a **MULTITHREADED** environment. On modern VMs such as HotSpot, it is approximately 1/3 slower than java.util.Random.
 

*MersenneTwisterFast* is not a subclass of java.util.Random. It has the same public methods as Random does, however, and it is algorithmically identical to *MersenneTwister*. 

*MersenneTwisterFast* has hard-code inlined all of its methods directly, and made all of them final (well, the ones of consequence anyway). 

Further, these methods are <i>not</i> synchronized, so the same *MersenneTwisterFast* instance cannot be shared by **multiple threads**.

But all this helps MersenneTwisterFast achieve well over twice the speed of MersenneTwister. 

java.util.Random is about 1/3 slower than MersenneTwisterFast.

**Comment by bevans2000** [comment]
Key point is it has to be Thread safe or we use  ThreadLocal inside RandomUtil. Each thread having there own Random instance is not a problem.

**Comment by mokun** [comment]
> Key point is it has to be Thread safe or we use ThreadLocal inside RandomUtil. 

Okay. I'll revert back to ThreadLocalRandom for the time being.

> Each thread having there own Random instance is not a problem.

Yes. In future, once we sett up an instance for each thread, we'll adopt a faster and more efficient algorithm than ThreadLocalRandom.

**Comment by bevans2000** [comment]
I have marked these hotspots as safe in SonarQube so they will disappear now.
