### ISSUE TITLE
Duplicated crew member

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#434]
**Describe the bug**
- Duplicated crew member

**Expected behavior**
- Site Editor should not allow the same crew be selected more than once
- UnitManager should ensure no one with the same first and last name be loaded/generated in the same simulation
   - Should we add a middle initial for each person in order to distinguish those who happen to have the same first and last name but a different middle initial ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/132111664-1105ab8d-99cf-4b2b-88fe-41b81811869d.png)

**Desktop**
 - build r6167

**Comment by bevans2000** [comment]
I will modify the Site Editor to trap this condition

**Comment by mokun** [comment]
Can we make that list of Mars Society names in people.xml as founders ? 

Say, for each scenario or new simulation 4 of them would be randomly picked as the founder team. 

The advantage of having them in a settlement is that they will have a special bonus or ability of some sort. But how do we model that ?

**Comment by mokun** [comment]
But for us as project contributors/developers, let's think of a uniquely new ROLE or even a new JOB that we can take on and what can it be ?

**Comment by mokun** [comment]
@bevans2000, 

Now if I accidentally choose the same crew the second time, then I'm stuck. I cannot unselect that crew

![image](https://user-images.githubusercontent.com/1168584/132262313-726176f4-ec2e-4659-9b4d-b93a8ae2b6af.png)

What's the best way of solving this ?

**Comment by mokun** [comment]
Also, the `Undo` button is not working currently for some reasons.

![image](https://user-images.githubusercontent.com/1168584/132262493-8fa4796c-80d7-464c-83ab-1d55d397bc7b.png)

**Comment by bevans2000** [comment]
Because you want unselect a crew altogether. Should be easy to resolve

**Comment by mokun** [comment]
Let's add back checking lat and lon RIGHT AFTER they put in a new value.

![image](https://user-images.githubusercontent.com/1168584/132263255-253ec7f5-bb2d-4353-8b73-18e86f11dcd8.png)

e.g. if I input "22.S" or "22S", it should automatically validate the improper format and change it to "22.0 S".

I can fix this part after you.

**Comment by bevans2000** [comment]
Should be sorted now. There was quite a few problems with the error checking being done in different places but seems OK now,
