### ISSUE TITLE
NPE when loading and unloading resources from vehicle

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#439]
**Describe the bug**
A NPE is thrown sometimes when loading a vehicle with LoadVehicleGarage task (and EVA based loading). The code below shows that a catch has been put in but this is bad practice. 
```
			// Load resources
			try {
				if (amountLoading > 0D) {
					amountLoading = vehicleMission.loadResources(amountLoading, 
							requiredResources, optionalResources);
				}
			} catch (Exception e) {
				logger.severe(person, 20_000L, "Troubles loading resources: ", e);
			}
```
The problem lies in the explicit constructor, i.e. the one not used by the TaskMeta class. In the explicit constructor the vehicleMission is never identified and hence the NPE above. However this constructor is called from a VehicleMission subclass so I expect the value can be passed in.

**Comment by mokun** [comment]
> In the explicit constructor the vehicleMission is never identified and hence the NPE above

I wonder why vehicleMission would be null ?! 

The constructor would always define what vehicleMission is.

If it's null, then the task is ended.

**Comment by mokun** [comment]
@bevans2000 

Currently, it still have difficulties loading resources in some cases (but not in all cases) and the mission would stay forever at embarking phase, even though all the resources have been loaded in the vehicle and I can't figure out why.

Do you see any other abnormalities ?

**Comment by bevans2000** [comment]
There are 2 sets of constructors. The normal Task ones and another set that takes a long argument list, this one does not look up the vehicle mission. But this second set is called directly from a VehicleMission subclass so I think the ```this``` can be passed in. However I dont understand the purpose of explicitly starting a new Task and  bypassing the TaskManager.

**Comment by bevans2000** [comment]
I'm going to have a look at this today

**Comment by mokun** [comment]
Thanks! 

Guess we really need to get our sanity back from having to call VehicleMission's isVehicleLoaded() so many times to check on whether the vehicle's resources have been properly loaded.

So, if we are to do a breakdown here, when do we truly need to check on it ?
1. when embarking from a mission
2. when embarking from a delivery, trade, and emergency supplies missions to return home

I'm also suggesting may be having just the Mission Leader (aka the Starting Member of a mission) calling it to decide what needs to be loaded.

**Comment by bevans2000** [comment]
I thought we could create a ```Manifest`` object when the VehicleMission is created that records what is needed for this Mission. Then as we load it removes resources from the manifest until it is empty. 
I first want to consolidate the duplicate logic of the Garage & EVA load into a new ```LoadActivity``` class. This will make it easier to trace and track the problem and make changes.

**Comment by bevans2000** [comment]
I'm now thinking we have a ```LoadingController```  object for each VehicleMission when it is in the loading phase. This would be shared amongst all Load Tasks; seems to make more sense.

**Comment by mokun** [comment]
This issue is related to https://github.com/mars-sim/mars-sim/issues/404

**Comment by mokun** [comment]
Related to https://github.com/mars-sim/mars-sim/issues/344 as well.

**Comment by bevans2000** [comment]
Changes for the rework are done and everything looks ok. Logic is much simpler now. Need to run some long simulations.
42bd1f977f1e5e287f23a929b91fe8b8c368eed8

**Comment by mokun** [comment]
> Changes for the rework are done and everything looks ok. Logic is much simpler now.

Awesome ! 

So getting stuck in the airlock still happen in some specific circumstances but it has nothing to do with doing EVA repair ?

**Comment by bevans2000** [comment]
I don't think so. Just seems to be because so many people are trying to use it.

**Comment by bevans2000** [comment]
Just an update. Fixing an oversight on my behalf with the redesign concerning Delivery missions. The new design didn't work correctly when Drones had to reload for the return journey. It was still using the completed LoadingController of the original outbound load. 
I think this is solved now by using the current ```Settlement``` of the vehicle when starting the loading.

**Comment by bevans2000** [comment]
@mokun Have you seen a problem where on long simulations no new Missions get created? They all start to fail with not enough members. I'm sure it has nothing to do with the loading changes but can't figure out what's going on.

**Comment by mokun** [comment]
> They all start to fail with not enough members

So something prevents them from joining... ?! 

> Have you seen a problem where on long simulations no new Missions get created?

How many sols ? I'll try it.

**Comment by bevans2000** [comment]
> > They all start to fail with not enough members
> 
> So something prevents them from joining... ?!
Yes they all report not capable but dont know why. I plan to run the debugger this morning.

> 
> > Have you seen a problem where on long simulations no new Missions get created?
> 
> How many sols ? I'll try it.
I saw it about I sols in last night.

**Comment by bevans2000** [comment]
I think I have found the problem but not 100% sure. What is happening is there are a lot of people attached to Mission with a review pending; so everyone is already occupied. These Missions are not being reviewed because they are not shown on the ongoing mission list and hence never get a chance for review.
The reason I believe is this piece of code in MissionManager.addMission
`
		if (!onGoingMissions.contains(newMission)) {
			onGoingMissions.add(newMission);
			
			// Iterate mission identifer
			newMission.iterateIdentifer();
`
What is wrong with this is that the mission identifier is changed after it is added to the list but the mission identifier is used in equals method. This break a good principle in that attributes used for identification purpose should be immutable. 
I think by the way the Mission.equals method works; it leads to only one Mission per type being selected. I am looking into this now.

**Comment by bevans2000** [comment]
Found it. The `VehicleMission.equals` method is incorrect. It matches on just the mission type and not the actual mission identifier.  This means there is only one type of each Mission added to the MissionManager. 
Tricky one to find :satisfied:

**Comment by mokun** [comment]
This

**Comment by mokun** [comment]
Somehow, the vehicle is null in both `LoadVehicleGarageMeta::getMissionNeedingLoading` and `UnloadVehicleGarageMeta::getAllMissionsNeedingUnloading`.

We don't have this problem for a while until lately. I wonder why.

```
00-Bora-06:533.657 (Severe) LoadVehicleGarageMeta : [New Pompeii] Aarna Nirmal - Error finding loading missions.
java.lang.NullPointerException
	at org.mars_sim.msp.core.structure.building.BuildingManager.isInGarage(BuildingManager.java:1178)
	at org.mars_sim.msp.core.structure.building.BuildingManager.addToGarage(BuildingManager.java:1154)
	at org.mars_sim.msp.core.person.ai.task.LoadVehicleGarage.getAllMissionsNeedingLoading(LoadVehicleGarage.java:191)
	at org.mars_sim.msp.core.person.ai.task.meta.LoadVehicleGarageMeta.getProbability(LoadVehicleGarageMeta.java:61)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.rebuildTaskCache(PersonTaskManager.java:150)
	at org.mars_sim.msp.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:509)
	at org.mars_sim.msp.core.person.ai.task.util.PersonTaskManager.startNewTask(PersonTaskManager.java:240)
	at org.mars_sim.msp.core.person.ai.Mind.lookForATask(Mind.java:310)
	at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:253)
	at org.mars_sim.msp.core.person.ai.Mind.decideTask(Mind.java:180)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:123)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:854)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1123)
	at org.mars_sim.msp.core.structure.Settlement.otherTimePassings(Settlement.java:995)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:948)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:754)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by bevans2000** [comment]
This is a different problem so we should create a new issue.
It could be the mission has isDone and the vehicle has been released. The loading may have previously failed.

**Comment by bevans2000** [comment]
This is done now?

**Comment by mokun** [comment]
Sure. This thread is old.
