### ISSUE TITLE
Move our Trello boards over?

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#45]
We could move the Trello boards over to Projects. Is this interesting or are we not using kanban at all anymore?

**Comment by mokun** [comment]
I never use "Projects" in GH before. I'm creating a new entry now called "Switch to Gson for Serialization" to get a taste of how it works.

**Comment by larsnaesbye** [comment]
Cool. Did we use the Trello much anyway? I know some people were there, though.

**Comment by larsnaesbye** [comment]
I've copied over one board, but there's a whole lot on the 'web service' one in Trello. Would this work here?

**Comment by mokun** [comment]
Barry started the web service. 
@larsnaesbye, do you have experiences using Spring and/or Springboot ?

**Comment by larsnaesbye** [comment]
Nope, not yet.
