### ISSUE TITLE
Use of MissionType as identifier 

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#453]
**Describe the Improvement **
Missions (& MissionMeta) are referenced by 3 different means in the code base:
1. The MissionType enum
2. The DEFAULT_DESCRIPTION pattern with the constant in the meta class
3. Use of instance of against the Mission subclass
Both of the last 2 generate an excessive number of imports of classes to the callers. It also creates a coupling between classes that do not need to have one.
The code base should standardise on using the Missiontype enum as it provides a type safe and effecient way to identify the type of Mission.

**Comment by mokun** [comment]
Sure. Let's just stick with MissionType. 

It's very different to configure mission and won't be any player defined mission from xml anytime soon.

**Comment by bevans2000** [comment]
Yes using the enum will make it fixed but the reality is we are a million miles away from a plug and play architecture where new  missions can be added without coding. We have to flush the Mission dependencies out of the code first which this change will help do.
I will add this to 3.3.1 milestone

**Comment by mokun** [comment]
> I will add this to 3.3.1 milestone

Would it be better if we gather a few of these **architectural** related changes as a minor version update (e.g. 3.4.0) instead ? 

That's because these changes could potentially introduce new bugs and won't be discovered until later. 

On the other hand, if we discover any bugs and offer bug fixes, then it's good to roll those into patch update, such as 3.3.1.

**Comment by bevans2000** [comment]
Ok reassign it if you think that is best. But what's in scope for 3.3.1

**Comment by bevans2000** [comment]
Of course could crack on with 3.4 on the master branch and create a sub branch for any bugfixes on 3.3.0. Assuming the code has been tagged for 3.3.0

**Comment by bevans2000** [comment]
Fine. I'll work on this on a branch in my fork anyway.

**Comment by bevans2000** [comment]
@mokun Uncovered an interesting dependency. ```Job``` is dependent upon the ```Mission``` sub-classes which feels wrong. Job are more fixed such that if we add a new Mission I would not expect to have to go and update the Jobs. Mission is top of the dependency tree really because that is the purpose of all the simulation to complete Missions.
The pattern for Task is that it references the appropriate Job & Roles; not vice versa like Missions.
So I think we should turn this dependency inside out into the same pattern as Task -> Role & Job.
