### ISSUE TITLE
Mission Agenda should influence Science & Missions

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#455]
**Is your feature request related to a problem? Please describe.**
Reporting Authority has a number of Mission Agenda assigned to define the goals. These agendas should influence which science study and missions are created. This would allow the settlements of different authorities to take different paths.

**Comment by mokun** [comment]
> These agendas should influence which science study and missions are created. 

Absolutely ! 

> This would allow the settlements of different authorities to take different paths.

Yes mission weight will affect what mission to take on.

Science weight will influence what science to pursue.

But I'd love to see even more diversity in development beyond that. 

How do you tell how much each settlement be departing from one another ? 

What are the metrics for measuring these differences ?

**Comment by bevans2000** [comment]
> > These agendas should influence which science study and missions are created.
> 
> Absolutely !

I see the actual values being in the governance.xml file where the agendas are defined.  It's possible to allow the user to create their own mission agendas but I think that is a step too far at the moment. Just keep with a predefined palette of agenda that can be applied to custom Reporting Authorities. Once #453 is done it will make it easier to link Missions with the Agendas.

Probably a screen in the ui to show the combined ratings of all the applied agendas for an authority. The screen should be shared between the various windows showing Authority details to avoid duplication.
> 
> > This would allow the settlements of different authorities to take different paths.
> 
> Yes mission weight will affect what mission to take on.
> 
> Science weight will influence what science to pursue.
> 
> But I'd love to see even more diversity in development beyond that.
> 
> How do you tell how much each settlement be departing from one another ?
> 
> What are the metrics for measuring these differences ?

Now that's a good question I dont know the answer of 😁 But it could be  a Settlement is heavily influence to do Construction. At the moment this is never trigger automatically.

**Comment by bevans2000** [comment]
For Missions the approach to this will be:

- If there is a Mission Modifier on the ```SubAgenda``` then the integer value will be used as a priority value otherwise the value will be zero
- The selected priority value is clipped to 10 as a maximum
- Then a ratio of influence is calculated by (property value/10) * 0.5.
- The process is repeated for all SubAgendas assigned to give a total ratio value.
- The ratio is applied as a multiplier to the mission probability
-
So if a mission has a priority score of 10 in a single SubAgenda the overall probability score will be increased by 50%.
If a mission type appears as a priority score of 10 in one agenda and 5 in another the overall increase will be 75% (50 + 25)
If a mission type appears as a 10 in 3 agenda the increase is 150%
