### ISSUE TITLE
Computer Science and Computing

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#456]
It's never too late. We're now recruiting Computer Scientists and Data Scientists to be sent to Mars as settlers.

Also, one's Computer Skill will be taken into consideration for all applicants. 

Incidentally, owing to the need of meeting the demand of computing in any settlements, we are adding the role of Chief of Computing and Computing Specialists into day-to-day operations of a settlement.

**Comment by bevans2000** [comment]
Nice, do we need some Role specific Tasks now? Or maybe some special Science Study like creating a computer model for the Martian weather ?

**Comment by mokun** [comment]
> Nice, do we need some Role specific Tasks now? 

Good idea! 
 
> Or maybe some special Science Study like creating a computer model for the Martian weather ?

Just added computing as a science type.

So, how do we make use of studying a science topic such as modeling Martian weather ? 

To someone who chosen to study the Martian weather, What kind of impact or connection do we envision should happen for the settlement ? 

what other computing tasks do you have in mind that we can add ?

**Comment by mokun** [comment]
How about we add a "Data Center" or "Server Node" building. 

Probably cooling the server racks won't be that big of a deal on the surface of Mars. 

But we'll need to take a look at the convection, conduction and radiative cooling on Mars. See https://marspedia.org/Cooling

But we still need to think of the utility of these computing power.

**Comment by mokun** [comment]
I found some of the feedbacks and comments on this article called [Design considerations for Mars colony computer systems](http://shape-of-code.coding-guidelines.com/2019/11/17/design-considerations-for-mars-colony-computer-systems/) pretty amusing and interesting.

**Comment by bevans2000** [comment]
Data Center is a cool idea for a new building. We could have a DataCenter Function and use it in either a dedicated Building, e.g. Server Room or add it go an existing building for smaller Settlements.

**Comment by mokun** [comment]
> We could have a DataCenter Function

I have an idea in modeling how the computing power will be quantified. 

Say we create a metric called *Computing Unit* (CU). 

Every building function and/or resource processing would consume some CUs. 

As the settlement grows, the demand for more CUs would increase as well.

I would imagine scientific research would consume quite a bit of CUs as well.

To meet the demand proportionally, one would have to supply more server nodes by expanding the data center, etc.

**Comment by bevans2000** [comment]
Ok, yes I can see how that could work. It would need to increase the CU of an existing building as demand grows. The DataCenter would have a theoretical maximum CU related to how many servers the building could hold. Obviously a DataCenter would generate heat and consume a lot of power.

**Comment by mokun** [comment]
So for now, there are 3 main attributes to the COMPUTATION FunctionType as follows : 
```
			<computation computing-power="10" power-demand="1" cooling-demand=".5">
				<activity>
					<activity-spot xloc="0" yloc="0" />
				</activity>
			</computation>
```

**Comment by mokun** [comment]
For now, the BuildingPanel will showcase 3 textfields regarding the computing capability of any building having the Computation function :

![image](https://user-images.githubusercontent.com/1168584/135681847-581f5822-f1b9-4965-a088-4c28e27d1f74.png)

I suppose we need to connect certain existing tasks such as site surveys to make use of the available computational power.

What are those tasks ? 

Also, what new tasks do you see we can create for a computer scientist to do or for those having the role of Resource Specialist ?

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

We'll need to consider how a process may intricately consume certain amount of computational unit (CUs) within an interval of time.

Scenarios:
1. A greenhouse needs some 0.1 CUs for constantly monitoring the growth of each crop.
2. A mission team needs just 0.5 CUs to analyze satellite data for sites selection for a Regolith Processing mission 

Say, the max computational power provided by Lander Hab's server is 10 CUs at any given time.

For scenario 1, I'll need to take 1 CUs ( = 0.1 * 10) from it for a greenhouse having 10 crops. 

So, the remaining is 9 CUs at any given time.

But for scenario 2, it's just a one-off task to use the computer to analyze map data and is not a steady-state task.

So for, say, 10 msols, the available computational power would drop from 9 CUs to 8.5 CUs. 

And when the task is over, that is, after 10 msols, it climbs back to 9 CUs.

**Comment by mokun** [comment]
@bevans2000 

What kind of tasks can we create for a computer scientist to do in mars-sim ?

**Comment by bevans2000** [comment]
If we add the concept of "computing power" then the Computing Function would,d need a maintenace style Task. However I'm not sure if this is worth the effort to develop it.
Clearly we need to get Computer Scientists involved in any research that involves modelling.

**Comment by mokun** [comment]
> get Computer Scientists involved in any research that involves modelling.

Yes. We'll need to modify all the _topics.json files to include which collaborative science subject is needed under each topic. This way, no wrong collaborative subjects will be picked randomly.


For now, we have computing_topics.json as follows:

```json
{
	"subject": "Computing",
	"topics": [
			{"topic": "Autopiloting Surface Vehicles"},				
			{"topic": "Body Telemetrics"},
			{"topic": "Bacteria Mutation Modeling"},
			{"topic": "Drone Delivery Autorouting"},
			{"topic": "Genetic Algorithm of Martian Satellites Motion"},			
			{"topic": "Informatics for Martian Society"},
			{"topic": "Martian Climate Modeling"},
			{"topic": "Modeling of Local Gravitational Effects"},
			{"topic": "Modeling of Surface Radiation"},
			{"topic": "Modeling of In-situ resource processing"},
			{"topic": "Parts Reliability Modeling"}, 
			{"topic": "Quantum Communication Network"},
			{"topic": "Satellites Telemetry Processing"},			
			{"topic": "Simulation and Modeling of Martian Weather"}, 			
			{"topic": "Simulation of Microgrid Resiliency"},			
			{"topic": "Social Simulation"}
	]
}

```

**Comment by mokun** [comment]
Obviously the computing topics above are diverse and multidisciplinary. 

A few of them, such as "Informatics for Martian Society" or "Social Simulation", the primary subject may actually be "Social Science" and it's more fitting to have "Computing" as the second subject.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

See this proposal at https://www.theregister.com/2022/05/21/lonestar_moon_datacenter/

**Comment by bevans2000** [comment]
What's left to do with this ?

**Comment by mokun** [comment]
> What's left to do with this ?

hmm. Let me try to write for what I have in mind to do but never got back to this to piece things together  : 

1. Create codes that acknowledge the need for computing nodes in a settlements
2. Create computer maintenance downtime tasks
3. Create computer tasks/projects that will end up improving vehicle performance specs or building function specs or settlement specs
4. Write codes that link the power usage to the free and used computing nodes.
5. Write codes that will rank the computing achieve of this settlement against others.

**Comment by mokun** [comment]
@bevans2000 

Can you create a task for maintaining computer equipment ? 

Or some tasks that are dedicated for a computer scientist to do ? 

Currently, a comp scienstist is doing whatever everybody else is doing and has no specific tasks to do.

**Comment by bevans2000** [comment]
Sure. We could do a generic computer maintenance Task?

**Comment by Urwumpe** [comment]
> @bevans2000
> 
> Can you create a task for maintaining computer equipment ?

Not sure if a special maintenance task is really fitting there, since you also use the same generic maintenance task for nuclear reactors and rovers. 

> 
> Or some tasks that are dedicated for a computer scientist to do ?

What about something like: "Developing software", "Testing software", "Configuring system", "Defining new baseline", "Deploying software", "Managing technical debts", "Create algorithm", "Improve architecture" and (yuck) "Writing documentation".

**Comment by mokun** [comment]
@bevans2000 

What is the best way to model the use of computing resources ?

Even though we've been using those computing resources in a few tasks, however, the way it submits or schedules for future time is far from optimal. 

For instance, it doesn't look at when the next frame comes around and how fast the time ratio is. 

Say, right now, we are at sol 1:100 (on sol 1 at 100 msols) and I schedule for 0.01 CUs for the next 10 millisol.

But since the time ratio is 1024x, the next millisol is actually, say, at sol 1:120.

What is the best way to account for any time ratio so that it doesn't skip over millisols ?

**Comment by bevans2000** [comment]
We have to be very careful trying to influence how the pulses work. It is very possible actual millisols could be skipped and the logic has to  compensate for this.

**Comment by mokun** [comment]
> We have to be very careful trying to influence how the pulses work. 

Yes. For now, I've simplified how the computing resources are asked by using the integer msol. So, it's requesting, say, 0.01 CUs per msol.

To be realistic, we can always switch back to the exact millisols with decimal places.

The scheduling mechanism is now not as good.

**Comment by mokun** [comment]
For now, the BuildingPanelComputation will display and update the following 3 metrics : 

![image](https://user-images.githubusercontent.com/1168584/179425150-751f5ba9-b2c6-48ee-9d8e-83edbb92854e.png)

**Comment by mokun** [comment]
Just changed to show both the available CUs and Peak CUs as follows : 

![image](https://user-images.githubusercontent.com/1168584/179425518-547f8c2b-f70a-4362-9f1e-e033cf345b54.png)

And also: 
![image](https://user-images.githubusercontent.com/1168584/179425548-1734affc-f291-4ebf-9dcf-592b62e4b6c3.png)

**Comment by mokun** [comment]
The basic use of computing resources is done. 

We may as well close this thread now since it's getting too long.

@Urwumpe
For those features you have in mind, let's open a new thread for each of them.

**Comment by mokun** [comment]
Now that the concept of entropy is applied, each computing node will increase in entropy over time unless someone does the job of optimizing the node.
