### ISSUE TITLE
Optimise Relationship Manager

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#458]
**Describe the bug**
The RelationshipManger uses an unsupported graph package 'com.phoenixst.plexus' that is only available with the project SourceForge site. This has a high risk.
Also the `RelationshipManager` is a Singleton managing the social graph from a single place; hence it is not Thread safe. As well it involves a lot of lookups from `Person` to nodes in the graph.

**Expected behavior**
An alternative approach is to remove the single point of management; each Person would have a new `Social` instance which acts as a node in the relationship graph. The Person object becomes responsible for updating and maintain their own social attributes. 
Any larger graph traversal would be handled by a new `RelationshipHelper` class.
This would become Thread safe as updates are grouped by individual Settlements. The key new synchronisation point would be when relationships are created across Settlements which can be handled.
This would remove the need for the unsupported package.

**Comment by mokun** [comment]
We could take advantage of [Guava's graphic APIs](https://dzone.com/articles/an-overview-of-google-guava-and-introduction-to-it) since we have been using its bi-mapping methods. 

Or we could roll in our own implementation.

**Comment by mokun** [comment]
Related to https://github.com/mars-sim/mars-sim/issues/137

**Comment by bevans2000** [comment]
The key decidion is do we do big graph traversal or graph searching? I think not so a simple roll our own might be sufficient.

**Comment by bevans2000** [comment]
Looks like [Java GraphStream](https://graphstream-project.org/) is a good replacement for plexus. It also comes with a Swing visualisation to I should be able to add a UI Tool.

**Comment by mokun** [comment]
> [Java GraphStream](https://graphstream-project.org/) is a good replacement for plexus. It also comes with a Swing visualisation to I should be able to add a UI Tool.

good that this library have developed both swing and javafx visualization tool

**Comment by mokun** [comment]
We also have jgrapht in mars-sim-core's pom.xml. It was currently commented out though

```xml
		<!-- https://mvnrepository.com/artifact/org.jgrapht/jgrapht-core (917 KB)
		<dependency>
		    <groupId>org.jgrapht</groupId>
		    <artifactId>jgrapht-core</artifactId>
		    <version>1.3.1</version>
		</dependency-->
```

**Comment by bevans2000** [comment]
I made a mistake and JavaGraph doesn't support Serialization. 😥

**Comment by mokun** [comment]
> I made a mistake and JavaGraph doesn't support Serialization. 😥

That being the case, we should consider how we should transition to use JSON to serialize data.

**Comment by bevans2000** [comment]
The problem is a saved simulation would need 2 files. This will be a problem to manage. I'm sure we can do something to replace the unsupported library. I think there are 2 places were we use a graph traversal so it would be possible to replace with something inhouse. This would give us control over the serialisation as well.

**Comment by mokun** [comment]
> 2 places were we use a graph traversal so it would be possible to replace with something inhouse.

Yes. Currently both the CreditManager and RelationshipManager are using the old, expired graphing library in mars-sim.

@Urwumpe 

Can you think of any Java graph API out there that is JSON compatible ?

**Comment by bevans2000** [comment]
No I think your change is good removing the central graph

**Comment by mokun** [comment]
Allow a relationship to have 3 aspects in [this](https://github.com/mars-sim/mars-sim/issues/458).
