### ISSUE TITLE
Stalled Negotiation in Delivery mission

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#460]
**Describe the bug**
During the Delivery Negotiation phase of a Delivery Mission it can become stalled, particularly after restoring a saved simulation. The `NegotiateDelivery` Task exists but the assigned worker is no longer performing it. The Worker may have abruptly stopped due to sleep or food demands. When the assigned worker comes back to the mission it is not resumed but just checked for completeness. If not one is performing the Task it never completes.
```
		if (negotiationTask != null) {
			if (negotiationTask.isDone()) {
				buyLoad = negotiationTask.getBuyLoad();
				profit = estimateDeliveryProfit(buyLoad);
				fireMissionUpdate(MissionEventType.BUY_LOAD_EVENT);
				setPhaseEnded(true);
			}
		} 
```
This code from Delivery mission shows the problem; once the negotiation task is created it is never resumed only checked.
Secondly if the task becomes detached from the Worker at the time of saving the `Tasl.reinit` method is never called on the restore.

**To Reproduce**
Leave a simulation running and eventually one of the Delivery Missions will become stalled in the negotiation phase. Save and restore the simulation to fully see the affect.

**Expected behavior**
The fix is quit straight forward, the above code needs an else if condition to check if the caller is currently assigned to the negotiate task then it is assigned as their active task. If a null Person is returned from the Task; then it needs to be reinit.

**Comment by mokun** [comment]
> The Worker may have abruptly stopped due to sleep or food demands.

Good point.

Then my question is, how do we come up with the right time for negotiation ? 

Let say there's a 3000 miles distance between the origin settlement and the destination.

So if the drone arrives in the evening of the destination settlement, trader B in the destination is asleep. 

However, when trader B is on shift, trader A in the origin settlement is off shift.

If their work shift hours aren't overlapping, it seems very hard for a successful negotiation to take place. 

What should be the remedy ?

**Comment by mokun** [comment]
Also, it shouldn't be just the person whose job is trader. We should allow chief of supply and resources  and/or resource specialist to participate in the negotiation as well.

**Comment by bevans2000** [comment]
Hmm, 

> Also, it shouldn't be just the person whose job is trader. We should allow chief of supply and resources and/or resource specialist to participate in the negotiation as well.

Makes sense but that is harder to do because it involves changing the Worker of the task. I'm not touching that at the moment.

**Comment by bevans2000** [comment]
One step forward, two steps back......
Negotiation task seems to now be working but when reloading, someone has continued to unload the methane just loaded. So the Drone is stuck in the destination with no fuel I think it is an edge case but just trying to debug it.

**Comment by mokun** [comment]
> someone has continued to unload the methane just loaded

At the origin settlement, there's no need of having a person to load methane, oxygen, or water anymore. It's done automatically by assuming that pipe hookup is done by robotically.

May be this pipe hookup doesn't work on the destination settlement yet.

**Comment by mokun** [comment]
In both Rover and Drone's timePassing(): 
```
if (mission instanceof VehicleMission) {
	LoadingController lp = ((VehicleMission)mission).getLoadingPlan();
						
	if ((lp != null) && !lp.isCompleted()) {
		double time = pulse.getElapsed();
		double transferSpeed = 10; // Assume 10 kg per msol
		double amountLoading = time * transferSpeed;

		lp.backgroundLoad(amountLoading);
	}
}
```
I can see you've already replaced some codes with LoadingController.

**Comment by mokun** [comment]
My goal in timePassing() was to allow automatic transfer of methane, oxygen and water.

Can you reinstate the ability to do automatic transfer ?

But if there are additional Amount Resources and Item Resources, they will need to supposedly load them by hand (limited by the strength of the settlers) to the vehicle.

**Comment by bevans2000** [comment]
Automatic still works as it's a cool way of doing it, it gets triggered once a loading plan is created.
The problem I've got is at the destination someone is still unlocking when the next reloading starts. So they remove the methane that has been loaded.
The problem is trying to reproduce it since it's a very specific case but I think I know what is going wrong just waiting for it to reproduce.

**Comment by bevans2000** [comment]
Wow that proved very problematic. I under covered a few weird edge cases concerning Delivery & Trade missions when they reach the Trading Settlement.  The last commit has tried to rework the loading/unloading at the trading Settlement so it follows the same patterns as the starting Settlement, i.e. Person/Robot select the load Tasks via the normal Task probability map instead of being forced on them.
This has involved moving the logic to decide when a Mission can be loaded/unloaded into the Mission subclasses instead of having it in the Task. This is probably better as it makes the coupling cleaner. 
Also uncovered a case where an already reserved Vehicle can be used in another Mission. This can happen if a Scenario is used which will create a lot of Missions, e.g. many Settlements close together to generate Delivery & Trade. Note if they are too close then the whole system starts to fail; I think there is flaw in the logic of looking up the closest Settlement when travelling between Settlements close together.
This is currently on the 3.3.0 branch and needs merging back to master.
