### ISSUE TITLE
Exploration & Prospecting Missions don't work in darkness

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#469]
**Describe the bug**
If a Prospecting mission reaches a site during the dark hours it avoid the exploration and moves to the next waypoint. This means some Missions are wasted.
```
00-Adir-02:077.050 (Info) CollectResourcesMission : [Sand Crawler] Mia Grenier - Too dark for Collecting resources at prospecting site 1 of Regolith Prospecting #2, moving to next site
```

**To Reproduce**
It commonly happens just at the start of a new simulation as first mission set off in night time.

**Expected behavior**
The mission should have a new phase to wait for sunlight and then explore the site once that expires. This of course may exhaust the loaded resources so a maximum time should be put on the waiting.

**Comment by mokun** [comment]
> The mission should have a new phase to wait for sunlight and then explore the site once that expires.

interesting catch !

**Comment by mokun** [comment]
This reminds us that we should create some lighting equipment. 

Releasing a small drone for aerial imaging makes sense for exploration mission.
