### ISSUE TITLE
modifying height and weight of a person by country of origin

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#47]
Shall we work out a list of height modifier and weight modifier based on a person's country of origin when computing one's height and weight ?

Currently, we use the following two methods inside Person class for doing the job

> setupHeight();
> setupWeight();

In r3932, we've handcrafted a gaussian curve for setting the height/weight of a person, one for both male and female. 

However, we have yet considered one's country of origin as an important factor.
 
Also, we should look for a set of statistically accurate gender-correlated curves for setting height and weight for male and female.

e.g. from https://www.jotashoes.com/average-height-by-country, one may use the table to co-relate the height and weight of a person by one's country of origin.

Since we've already added the country field in Person, we may use it to pick a value from an array of height modifier and a value from an array of weight modifier when computing the height and weight. 

Anyone wanna help out getting this done ?

**Comment by mokun** [comment]
Note for now, I assume the following average for a 20-year-old in the US :

For male :     height : 176.5	weight : 68.5

For female :   height : 162.6	weight : 57.2

**Comment by larsnaesbye** [comment]
Good idea. Is country of origin the only thing we wish to take into account?

**Comment by mokun** [comment]
true. there are other factors that will definitely affect height and weight. 

When we finally add having babies, we'll need to create a curve for growing height and weight by age.

**Comment by bevans2000** [comment]
@mokun I'm going to look at this. We can clean up the creation of the Person object at the same time. Needing to call the initialize method is really bad design; an object should be useable after being constructed.

**Comment by mokun** [comment]
> Needing to call the initialize method is really bad design; an object should be useable after being constructed.

Sure see if you can simplify it.

That's because some instances aren't available at the time of finalizing the creation the Person object.

**Comment by bevans2000** [comment]
@mokun Right, I've pulled it apart and put it back together. Have a look at the draft PR #1181 to see what you think. 
Look at the ```PopulationChararcteristics``` which defines the details of a certain nation. These objects are created as part of the ```NationSpec```.
