### ISSUE TITLE
Create LocalPosition class for Units

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#470]
**Describe the bug**
Many Units and classes use the X, Y, Z as separate properties when calculating Walking paths and current position in Buildings.
This is inefficient and means 3 parameters or 3 set of getter/Setters when a single one would be better.
This also clashes with the Buildings/Activity sports which are defined in terms of Point2D. This is latter class is actually an AWT class and is quite heavyweight compared to a simpler version of our own. Plus the Point2D is not serializable itself but only it's private subclasses.
We should replace both areas with our own class that is integer based to make the arithmetic quicker. The position units should therefore become centimetres instead of meters.

**Comment by mokun** [comment]
Sure, we can create Location class with x, y, z when a person/robot is inside a vehicle or a settlement.

Once a person gets outside the settlement, it will switch to Coordinates class.

**Comment by mokun** [comment]
If we're switching over to javafx for UI, we may as well use `javafx.geometry.Point2D` class and roll in our own Line2D and Area for walking and collision. See https://stackoverflow.com/questions/32475229/which-point2d-should-i-use.

**Comment by bevans2000** [comment]
Our use of a 2d point in not about the UI so we should use our representation.

**Comment by bevans2000** [comment]
Also if the external class is extended to do other things we may be storing objects that are bugger than we need. I would like to

1. Replace the use of Point2D with our own simple POJO in the Activity spots. Plus make the lists immutable once constructed so they can be safely shared and remove any local copying
2. Combine all uses of x & y arguments to a single POJO; plus removing the X & Y from Person & Robot
3. Convert our own position class to be integer based instead of double. This will speed up any arithmetic and reduce storage, We would use centimeters as the unit instead of the current meter. A singe centimetre is accurate enough for our purposes.

**Comment by bevans2000** [comment]
Closed by accident in the pull request.
Next is activity spots followed by Walking Tasks but with some optimisation

**Comment by bevans2000** [comment]
Found a great optimisation during this reworking concerning ```WalkingSteps```. Currently the pattern we have is

1. Call ```Walk.canWalkSteps()```
2. Which in turn creates a ```WalkingSteps``` instance of the route.
3. If it return true then we create a ```Walk``` Task
4. The Constructor then creates another ```WalkingSteps``` instance with exactly the same parameters.
5. The constructor validates the 2nd Walking steps instance.

So I have changed this to have a factory method in ```Walk``` that creates and validates the ```WalkingSteps``` instance. Then if it validates it passes it to a new Walk constructor that accepts the WalkingSteps instance without revalidating.

**Comment by mokun** [comment]
> Then if it validates it passes it to a new Walk constructor that accepts the WalkingSteps instance without revalidating.

I see. 

btw, we added the two new TaskPhase in Walk not long ago because we were going to implement the 2nd floor: 

```
	private static final TaskPhase CLIMB_UP_LADDER = new TaskPhase(Msg.getString("Task.phase.climbUpLadder")); //$NON-NLS-1$
	private static final TaskPhase CLIMB_DOWN_LADDER = new TaskPhase(Msg.getString("Task.phase.climbDownLadder")); //$NON-NLS-1$

```

But we have yet created the methods climbingUpLadder(time) and climbingDownLadder(time) and pieced everything together. 

If SpaceX's Starship is to land on Mars, it would sense to use the inside of the Starship as the habitat for some reasonable period of time.

With that being the case, it makes sense for us to implement multi-levels for a building.

Besides the UI changes, what changes do you see as the necessary for being able to walk from one level to another ?
