### ISSUE TITLE
New CPU utilization after removing Inventory

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#480]
With #463 #475 #476 completed, the old Inventory is no longer being used. 

Now mars-sim uses a few percentage less CPU (wish it were a larger drop). At least, it runs a little smoother and is easier to manually increase the Time Ratio. 

![image](https://user-images.githubusercontent.com/1168584/138396470-e388a4e5-c0f1-4cac-a185-ed1fb054871c.png)

Now the two most intensive methods are
1. `ResourceProcessing.timePassing()` - 28.9%
2. `Farming.timePassing()` - 44.4%

Internally, they called `MicroInventory.getCapacity()` a lot.

@bevans2000 
Q1 : What strategy can we use ? 

Q2 : The global caching seems to have failed to work in the old Inventory, shall we try to cache the most often used resources locally in the farming building and/or in resource processing building ?

**Comment by bevans2000** [comment]
I am currently looking at improving the Mission logic and in particular reduce the calls to ```VehicleMission.isVehicleLoadable```

**Comment by mokun** [comment]
After the recent commit, the aforementioned excessive calling of store.. and retrieve... related methods are gone.

Now, calling Person.timePassing() dominates 30% of all CPU usage as follows:

![image](https://user-images.githubusercontent.com/1168584/145505297-63975573-a258-473a-b1ca-57bff8293298.png)

**Comment by mokun** [comment]
@bevans2000 Is there anything else on this thread that you would like to work on ?

**Comment by bevans2000** [comment]
No let's close it and start a new Thread a fresh
