### ISSUE TITLE
Trouble in embarking from and disembarking to a settlement

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#488]
**Describe the bug**
- Simulation frozen when a rover tries to embark

**Possible cause**
- `performEmbarkFromSettlementPhase()` in RoverMission is very cumbersome and needs better modeling.
- Needs to manage EVA Suits better. See this [commit](
https://github.com/mars-sim/mars-sim/commit/2d3f2bc15df859d432a463f4817f9cedfcb90075).
- Needs to model how to rescue ill occupants from vehicle. See this [commit](https://github.com/mars-sim/mars-sim/commit/d4e31ab3dbfc51c426a3b57bffe80e8f169e222b).

**Comment by mokun** [comment]
@bevans2000 

In conjunction with what we've been discussing in https://github.com/mars-sim/mars-sim/issues/474, It's problematic in Person's transfer() in prematurely removing a person from the building 

If person A gets inside vehicle V in a garage for loading and unloading resources, then person A is technically in 3 places at the same time, namely, being in vehicle V, in a settlement, and in a garage building.

But if person B is in vehicle V that's NOT in a garage and is outside in the settlement's vicinity. Person B would like to load and unload resources, then person B is in 1 place only, namely in vehicle V. 

So now, the Walk class needs to be able to process that idea.

That's why since the last few changes, the embarking and disembarking phase would have trouble processing the location of a person.

**Comment by bevans2000** [comment]
So how did it work before?

I would say that if the Vehicle is in a Garage then there is no need for the Person to enter the Vehicle, they stay in the Building.

**Comment by mokun** [comment]
> So how did it work before?
 
I suppose the old way was that a person in a vehicle in a garage would still keep the settlement and the building

> I would say that if the Vehicle is in a Garage then there is no need for the Person to enter the Vehicle, they stay in the Building.

That's an interesting perspective. 

Yes, it should be looked upon as both the person and the vehicle are in the building in the settlement.

No need to use transfer() on the person.

**Comment by mokun** [comment]
So in other words, we need to sort out how and where to add back the logic of removing and adding occupants (of a vehicle) in a settlement and/or building.

**Comment by mokun** [comment]
@bevans2000 

So far, I can't figure out how to do best in setting a person's container unit when a person steps into a rover inside a garage and step out of the rover inside a garage.

The `enteringRoverInsideGaragePhase()` and `exitingRoverGaragePhase()` in Walk is crucial.

It's not easy to determine when to call `addPeopleWithin()` in Settlement and `addPersonOrRobotToBuilding()` in BuildingManager.

The simulation can freeze during walking if we screw up the container unit. 

On top of that, I've tried revising disembark() in RoverMission to ensure that the mission members can come back to the settlement. So far, they are still stuck in the vehicle as the vehicle is being removed from the garage.

May be the first step is to code Walk-related classes defensively so that it will always automatically go back to the settlement without explicit instructions every time. Do you agree ?

**Comment by mokun** [comment]
btw, I've made calling those add____() methods in Settlement much less rigid to return true.

This way, transfer() will be more likely to return true and be successful.

**Comment by bevans2000** [comment]
I see. We have to be careful not to end up by just patching the symptoms. We need to see if we can get the UnitTest working. 
I do think we need a clean contract on how Units transition. I feel the transfer method should be responsible for controlling everything the containment then we can UnitTest it. So putting extra calls to setContainerUnit could make the matter worse.
As for the disembarking, it's weird because I can't understand how it worked in the first place 🤔 When a Mission Member calls the disembarking we should create the Walk Task then for them to leave.

**Comment by bevans2000** [comment]
If a Person is in a Vehicle (whether garaged or not) the ```isInSettlement``` has to return false as at the moment it is returning true. Otherwise Persons start doing Settlement tasks from the Vehicle. If they want to take part in Settlement Task then they have to leave the Vehicle.

**Comment by mokun** [comment]
> If a Person is in a Vehicle (whether garaged or not) the `isInSettlement` has to return false as at the moment it is returning true. 

ok. changing the `isInSettlement()` method in Person now.

**Comment by mokun** [comment]
See if you can come up with a more logical and workable approach to handle entering and exiting a vehicle inside a garage.

You said you would use transfer() to do so. When I tried that last time, the simulation froze and I couldn't tell what the reasons were.

```
00-Adir-02:406.177 (Info) BuildingManager : [Goddard Trading Post] Jetson - Already inside Garage 1.
00-Adir-02:406.177 (Info) VehicleMission : [Goddard Trading Post] Jetson - Prepared a loading plan sourced from Goddard Trading Post
00-Adir-02:406.177 (Info) VehicleMission : [Goddard Trading Post] Jetson - Fetching spare parts (id:2002 fire extinguisher x1  id:2003 gasket x1  id:2004 valve x1  id:2008 electrical wire x3  id:2137 decontamination kit x1  id:2010 wire connector x4  id:2011 plastic tubing x1  id:2142 work gloves x1  )
00-Adir-02:407.098 (Info) BuildingManager : [Goddard Trading Post] Liberty - Stowed inside Garage 1.
00-Adir-02:410.204 (Info) VehicleMission [x5] : [Goddard Trading Post] Jetson - Trip Distance: 12.0 km   Fuel Economy: 4.7 km/kg   Fuel Margin: 3.3   Fuel: 8.4 kg
00-Adir-02:411.458 (Info) RoverMission : [Goddard Trading Post] Elizabeth Martinez - Transferred EVA Suit 009 as spares from Goddard Trading Post to Jetson.
00-Adir-02:411.458 (Info) RoverMission : [Goddard Trading Post] Cheryl Smith - Transferred EVA Suit 036 as spares from Goddard Trading Post to Jetson.
00-Adir-02:411.458 (Info) RoverMission : [Goddard Trading Post] Chris Reed - Transferred EVA Suit 004 as spares from Goddard Trading Post to Jetson.
00-Adir-02:411.497 (Info) Walk : [Goddard Trading Post - Jetson] Elizabeth Martinez - Entered rover Jetson inside Garage 1.
00-Adir-02:411.497 (Warning) Settlement : [Goddard Trading Post - Jetson] Elizabeth Martinez - Not currently in a building.
00-Adir-02:411.497 (Warning) WalkingSteps : [Goddard Trading Post - Jetson] Elizabeth Martinez - Inside the settlement but not in a building.
00-Adir-02:411.497 (Severe) WalkingSteps : [Goddard Trading Post - Jetson] Elizabeth Martinez - initialWalkState : null
00-Adir-02:411.497 (Info) Walk : [Goddard Trading Post - Jetson] Cheryl Smith - Entered rover Jetson inside Garage 1.
00-Adir-02:411.497 (Warning) Settlement : [Goddard Trading Post - Jetson] Cheryl Smith - Not currently in a building.
00-Adir-02:411.497 (Warning) WalkingSteps : [Goddard Trading Post - Jetson] Cheryl Smith - Inside the settlement but not in a building.
00-Adir-02:411.497 (Severe) WalkingSteps : [Goddard Trading Post - Jetson] Cheryl Smith - initialWalkState : null
00-Adir-02:411.497 (Info) Walk : [Goddard Trading Post - Jetson] Chris Reed - Entered rover Jetson inside Garage 1.
00-Adir-02:411.497 (Warning) Settlement : [Goddard Trading Post - Jetson] Chris Reed - Not currently in a building.
00-Adir-02:411.497 (Warning) WalkingSteps : [Goddard Trading Post - Jetson] Chris Reed - Inside the settlement but not in a building.
00-Adir-02:411.497 (Severe) WalkingSteps : [Goddard Trading Post - Jetson] Chris Reed - initialWalkState : null
00-Adir-02:415.895 (Info) RoverMission : [Goddard Trading Post] Nathan Wright - Transferred EVA Suit 030 as spares from Goddard Trading Post to Jetson.
00-Adir-02:417.308 (Info) Walk : [Goddard Trading Post - Jetson] Nathan Wright - Entered rover Jetson inside Garage 1.
00-Adir-02:417.308 (Warning) Settlement : [Goddard Trading Post - Jetson] Nathan Wright - Not currently in a building.
00-Adir-02:417.308 (Warning) WalkingSteps : [Goddard Trading Post - Jetson] Nathan Wright - Inside the settlement but not in a building.
00-Adir-02:417.308 (Severe) WalkingSteps : [Goddard Trading Post - Jetson] Nathan Wright - initialWalkState : null
00-Adir-02:419.315 (Info) RoverMission : [Goddard Trading Post] Linda Morris - Transferred EVA Suit 017 as spares from Goddard Trading Post to Jetson.
00-Adir-02:420.324 (Info) Walk : [Goddard Trading Post - Jetson] Linda Morris - Entered rover Jetson inside Garage 1.
00-Adir-02:420.324 (Warning) Settlement : [Goddard Trading Post - Jetson] Linda Morris - Not currently in a building.
00-Adir-02:420.324 (Warning) WalkingSteps : [Goddard Trading Post - Jetson] Linda Morris - Inside the settlement but not in a building.
00-Adir-02:420.324 (Severe) WalkingSteps : [Goddard Trading Post - Jetson] Linda Morris - initialWalkState : null
00-Adir-02:420.369 (Info) RoverMission : [Goddard Trading Post] Bryan Evans - Transferred EVA Suit 045 as spares from Goddard Trading Post to Jetson.
00-Adir-02:421.906 (Info) Walk : [Goddard Trading Post - Jetson] Bryan Evans - Entered rover Jetson inside Garage 1.
00-Adir-02:421.906 (Warning) Settlement : [Goddard Trading Post - Jetson] Bryan Evans - Not currently in a building.
00-Adir-02:421.906 (Warning) WalkingSteps : [Goddard Trading Post - Jetson] Bryan Evans - Inside the settlement but not in a building.
00-Adir-02:421.906 (Severe) WalkingSteps : [Goddard Trading Post - Jetson] Bryan Evans - initialWalkState : null
00-Adir-02:422.105 (Info) RoverMission : [Goddard Trading Post] Craig Diaz - Transferred EVA Suit 046 as spares from Goddard Trading Post to Jetson.
00-Adir-02:423.337 (Info) Walk : [Goddard Trading Post - Jetson] Craig Diaz - Entered rover Jetson inside Garage 1.
00-Adir-02:439.864 (Info) PlanMission [x2] : [Goddard Trading Post] Craig Moore - Looking into the settlement's mission needs.
00-Adir-02:439.864 (Info) PlanMission [x2] : [Goddard Trading Post] Craig Moore - Determined that the settlement doesn't need a new mission.
00-Adir-02:447.291 (Info) PlanMission : [Goddard Trading Post] Earl Thomas - Looking into the settlement's mission needs.
00-Adir-02:447.291 (Info) PlanMission : [Goddard Trading Post] Earl Thomas - Determined that the settlement doesn't need a new mission.
00-Adir-02:449.110 (Info) DriveGroundVehicle : [5.05 S 4.21 E - Jetson] Craig Diaz - Took the wheel of the rover.
```

**Comment by bevans2000** [comment]
Ok, let me have a look. I'm working on #469 at the moment which has turned into optimising how Mission Phases are implemented.

**Comment by bevans2000** [comment]
Part of this problem maybe the inconsistent way we move Units around. I think we should a clear contract:

- transfer method is the only way to move a Unit from one parent to another. Solely responsible for detaching a Unit from it's parent.
- setContainer method is protected and is solely responsible for correctly adding the child unit to it's parent, e.g adds a Person to the Settlement people inside list

Secondly, I wonder if we are making life too complicated for ourselves concerning Building. Why bother holding an explicit Building property for Person? Just transfer Person to Buildings and don't have it separate. The more I think about this the more I think it will be cleaner. Same applies for Vehicle in a Garage; make the Building the container of the Vehicle.
Finding the Garage of a Vehicle is expensive at the moment requiring a search of all Settlement Garages.

**Comment by bevans2000** [comment]
In my last commit reworking Missions I found that the probability of a mission member resuming and starting an Unload is quite low. There is a double random and a double fitness check. The impact is Vehicles can take a while to be unloaded and I think that contributes to members remaining in the vehicle at the end of the Mission. Nevertheless the code base is a bit simpler.  Just doing some long runs.

**Comment by mokun** [comment]
Here, These 4 settlers cannot embark from a settlement called Kyocera.

2 (Anna O. and Yua F.) of them are stuck inside the vehicle
![image](https://user-images.githubusercontent.com/1168584/141024389-b7d76801-128c-4cc8-b6f8-2765024b62e0.png)

1 (Hinata S.) of them is dead. 
![image](https://user-images.githubusercontent.com/1168584/141024684-e4a898ea-33cb-4266-8c53-8ffd75ef2069.png)

Should the Vehicle Window shows 2 or 3 crew ?
![image](https://user-images.githubusercontent.com/1168584/141024820-fc5ff1be-6a1c-45de-aa5e-f16b53a62557.png)

![image](https://user-images.githubusercontent.com/1168584/141024944-2ddecfc0-65a1-4f3c-975e-debc9132b576.png)

**Comment by bevans2000** [comment]
The stack messages could be red herring because these can be generated from Task probability scores. 
But I guess the 2 in the vehicle are waiting for Aoto to enter the Vehicle to start Travelling. It looks like they maybe stuck in an airlock trying to get back in the Settlement. I had a similar problem with 4 people stuck in an airlock with nothing happening.

**Comment by bevans2000** [comment]
I have found an interesting problem with disembarking via EVA. If the Vehicle has a large crew of 4 or more then members start unloading including the oxygen whilst people are still inside. Sometimes all the oxygen is unloaded so that the EVASuits cannot be loaded and hence these people become stuck inside.
I'm going to change the approach so that all the EVASuits get fully loaded when disembarking if 1st triggers. Then the suits will be ready for people to use once they finish their current Task. I am going to move the loading logic out of ExitAirlock into the EVASuit class as well.
Also when doff an EVASuit we should not empty it of resources. When Unloading via EVA a person enters the Vehicle and takes off their Suit someone else unloads the last of the Oxygen so the suit can not be reloaded. This needs a tolerance for Suits not being fully loaded ready to use as well; to re-use a Suit it will not be 100% full in this scenario.

**Comment by bevans2000** [comment]
I've made some changes mainly focused on disembarking but they may help embarking as well.

**Comment by mokun** [comment]
> But I guess the 2 in the vehicle are waiting for Aoto to enter the Vehicle to start Travelling. It looks like they maybe stuck in an airlock trying to get back in the Settlement. I had a similar problem with 4 people stuck in an airlock with nothing happening.

Yes these two settlers are stuck but they are in the garage and have nothing to do with the airlock. Essentially, they can't leave the garage because they are reportedly not in the garage. 

WalkSettlementInterior was not able to resolve their location correctly as they step into and out of the garaged vehicle.

**Comment by mokun** [comment]
> If the Vehicle has a large crew of 4 or more then members start unloading including the oxygen whilst people are still inside. Sometimes all the oxygen is unloaded so that the EVASuits cannot be loaded and hence these people become stuck inside.

That's an interesting scenario.

So our operational model should not hook up the vehicle to pump all the stored oxygen away from vehicle to the settlement until everything else has been transferred. 

Once all other items and others resources are being carried back to the settlement and all the occupants have left the vehicle, the last thing to transfer is oxygen.

Of course, this is needed if the vehicle is outside and NOT in a garage.

In a garage, there's no need for this.

**Comment by bevans2000** [comment]
I think I've sorted it by preloading the EVA suits with resources. Plus making sure resources can not be taken from a suit.

**Comment by bevans2000** [comment]
Are we good to close this now?
