### ISSUE TITLE
Two `Filip Olsen`'s in Europa

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#491]
**Describe the situation**
- Should we allow two individuals happen to have the same first and last name in one settlement ?
- What about in the entire simulation ? 

![image](https://user-images.githubusercontent.com/1168584/139747379-97362b15-2f80-4070-82af-67a255a48f49.png)

**Solution**
- We may add middle initial to reduce the chance of this occurrence
- We may even distinguish them as `Filip Olsen 1` and `Filip Olsen 2`, even though this is not as natural
- Ignore this as long as it doesn't cause any problems

**Comment by bevans2000** [comment]
No this is wrong. I will take this.
Although very unlikely to get the same generated randomly.

**Comment by bevans2000** [comment]
Not sure how this could happen because there is a check for uniqueness there. Could one come off a Crew? Was this a saved Simulation? They certainly look like different Person objects

**Comment by bevans2000** [comment]
Closing this. Will open a new issue if it recurs with more evidence

**Comment by mokun** [comment]
That was the only time I saw two settlers having the same name. They even stay in the same settlement, namely 'Europa'.

We could create a test to see if it would accept two different individual having the same first and last name.
