### ISSUE TITLE
Excessive amount of O2 generated and CO2 consumed

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#495]
**Describe the bug**
- After recent commits in changing Farming, Crop and CropType, the BuildingPanel of a Inflatable Greenhouse building shows excessive amount of O2 generated and CO2 consumed on Sol 6.
 
![image](https://user-images.githubusercontent.com/1168584/140394953-075467b7-d3fa-4682-a60d-63e1ce764391.png)

**Comment by Urwumpe** [comment]
Yeah, sounds a lot higher than it should, a hectar of forest can't compete there. :D 

1 mol of CO2 and 2 moles of H2O should turn into 1 mol O2 and 1 mol of water, the rest of the balance is newly grown biomass. So, already the ratio of the products is off, we get more O2 than CO2 was consumed.

**Comment by mokun** [comment]
Also, in Sol 1, it doesn't display the stats.

**Comment by mokun** [comment]
I just fixed what happened on Sol 1.

![image](https://user-images.githubusercontent.com/1168584/140840423-2f3ade36-cbc0-46f3-8e7b-cc7b4e1a0012.png)

Instead of showing zero, it shows how much water/o2/co2 consumed or generated since the beginning of that day.

**Comment by mokun** [comment]
@bevans2000 ,

Can you take a look at the two methods both called `computeUsage()` in Farming? 

They have the same method name but different params. 

The one with two param doesn't provide the daily average correctly, based on the data stored in SolMetricDataLogger.

```java
	/**
	 * Computes the average water usage on a particular crop
	 *
	 * @return average water consumption in kg/sol
	 */
	public double computeUsage(int type, String cropName) {
		double result = 0;
		SolMetricDataLogger<Integer> crop = cropUsage.get(cropName);
		if (crop != null) {
			result = crop.getDailyAverage(type);
		}
		return result;
	}
```

**Comment by mokun** [comment]
For now, I'll switch to using the following for the time being: 

```java
	/**
	 * Computes the resource usage on all crops
	 *
	 * @type resource type (0 for water, 1 for o2, 2 for co2)
	 * @return water consumption in kg/sol
	 */
	public double computeUsage(int type) {
		// Note: the value is kg per square meter per sol
		double sum = 0;
//		for (Crop c : crops) {
//			sum += computeUsage(type, c.getCropName());
//		}
//		if (sum == 0) {
			if (type == 0) {
				for (Crop c : crops) {
					sum += c.getCumWaterUsage();
				}
			}
			else if (type == 1) {
				for (Crop c : crops) {
					sum += c.getCumOxygenUsage();
				}
			}
			else if (type == 2) {
				for (Crop c : crops) {
					sum += c.getCumCO2Usage();
				}
			}
//		}

		return Math.round(sum * 1000.0) / 1000.0;
	}

```

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

At the end of the day, this tiny inflatable greenhouse consumed a total of 100 kg of water and 5.9k kg of CO2 while producing 8k kg of oxygen.

Does it sound more right or wrong ?

![image](https://user-images.githubusercontent.com/1168584/140841096-188f8d35-39b3-4cb6-a2d1-a19b70253364.png)

**Comment by mokun** [comment]
Just fixed sync issue in resetting the counters back to zero:

At msol 999 or 000:
![image](https://user-images.githubusercontent.com/1168584/140846030-43b39d54-5994-4847-adcf-603c828b6f96.png)

At msol 006 (after 000)
![image](https://user-images.githubusercontent.com/1168584/140846110-1ed26930-e5f4-4f11-a3d5-450d677f80c3.png)

**Comment by bevans2000** [comment]
So if you have reset the counter back to zero, does that fix the root problem?

**Comment by mokun** [comment]
> So if you have reset the counter back to zero, does that fix the root problem?

Before my commit, they were already being reset back to zero. So it wasn't the root problem.

The real problem seems to be the *race condition* these counters are having.

It means that while it's being reset back to zero, the previous value of that counter was kept and added into the new value right at the change of sol.

Anyway, now it seems to work fine after I added *synchronized* to updateUsage() in Crop.

```java 
	/**
	 * Update the usage of all three major farming resources.
	 * 
	 * @param currentSol
	 */
	private synchronized void updateUsage(int currentSol) {
		String name = cropSpec.getName();
//		if (cumulative_water_usage > 0) {
			// Records the water usage per crop in the farm
			farm.addCropUsage(name, cumulativeWaterUsed, currentSol, 0);
			// Reset the water usage
			cumulativeWaterUsed = 0;
//		}

//		if (cumulative_o2 > 0) {
			// Records the CO2 consumption/generation in the farm
			farm.addCropUsage(name, cumulativeO2Generated, currentSol, 1);
			// Reset the consumption/generation
			cumulativeO2Generated = 0;
//		}

//		if (cumulative_co2 > 0) {
			// Records the oxygen consumption/generation in the farm
			farm.addCropUsage(name, cumulativeCO2Consumed, currentSol, 2);
			// Reset the consumption/generation
			cumulativeCO2Consumed = 0;
//		}
	}
```

**Comment by bevans2000** [comment]
How interesting. In theory there should be no race condition here because Crops are only ever updated by the assigned Settlement Thread. The only thing I can think of it the UI thread is updating it via a get method, may e when it turns over the day the UI is indirectly creating a new bucket in the DataLogger

**Comment by Urwumpe** [comment]
> 
> 
> @bevans2000 @Urwumpe
> 
> At the end of the day, this tiny inflatable greenhouse consumed a total of 100 kg of water and 5.9k kg of CO2 while producing 8k kg of oxygen.
> 
> Does it sound more right or wrong ?
> 

Would be interesting to know how much biomatter/sugar the plants produced in that time as well.

100 kg water ~ 5,500 mol H2O
5900 kg CO2 ~ 134,000 mol CO2
8000 kg O2 ~ 250,000 mol O2

During daylight, we have (mostly) photosyntesis, during the night only respiration. There could be some variables since the plants likely depend on day/night cycles similar to their usual habitat on Earth. Also it should depend on how much energy the plants consume for themselves during respiration.

So, what can be said for sure: Our plants produce far too much oxygen per CO2.

**Comment by mokun** [comment]
> 100 kg water ~ 5,500 mol H2O
> 5900 kg CO2 ~ 134,000 mol CO2
> 8000 kg O2 ~ 250,000 mol O2

Looking into the amount produced/consumed now

**Comment by Urwumpe** [comment]
I'll try to look for some real world data about plant metabolism. Maybe there is a good reference. Generally, you need a lot of plants (think hectares instead of square meters) to produce the oxygen that a single human consumes.

**Comment by mokun** [comment]
Currently, we use these 3 figures as follows in crops.xml. I'd say they are reasonable rates.

```xml
<crop-configuration>

	<!-- The average amount of carbon dioxide (kg) needed by a crop per square 
	     meter area during the day [kg/m2/sol] -->
	<!-- Default: .2 -->
	<carbon-dioxide-consumption-rate value =".2" />

	<!-- The average amount of oxygen (kg) needed by a crop per square meter 
	     area during the night -->
	<!-- Default: .1 -->
	<oxygen-consumption-rate value=".1" />

	<!-- The average amount of water (kg) consumed by a crop per square meter 
	     area in each Martian Sol [kg/m2/sol]
	Note : KSC has daily water makeup requirements of 7 to 10 L/sq m/day 
	depending on type and maturity of the crop -->
	<!-- Default: 3 -->
	<water-consumption-rate value="3" />

	<!-- The ratio of measured irradiance [ Wm^-2 to PPF on Mars. Useful for 
	     calculating the instantaneous PAR in Crop.java -->
	<!-- see http://physics.stackexchange.com/questions/52487/photometer-measured-irradiance-l-converted-to-photon-rate -->
    <!-- Default: 4.568 on Mar [in u mol / m2 /s / (W m^2)] (vs. 4.609 on Earth-->
	<watt-to-photon-conversion-ratio value="4.568" />

```

**Comment by mokun** [comment]
> 1 mol of CO2 and 2 moles of H2O should turn into 1 mol O2 and 1 mol of water, the rest of the balance is newly grown biomass. So, already the ratio of the products is off, we get more O2 than CO2 was consumed.

I'll check on the math.

Yes I agree we should be as scientifically reasonable as possible and also realistic when it comes to # of moles produced/consumed.

And as we turn on lights in the evening, thereby consuming some power as well, I wonder if some of the food crop may experience "burnout" if we give them too much light ?!

**Comment by Urwumpe** [comment]
I think this could even be ten times higher than it should be per square meter. Also real plants have only a relatively low ratio between the O2 they produce and O2 they consume themselves, even during the day. Also the amount of water depends on the crop and the temperature of the leaves. For my Drosera here, even 10l per square meter per day would be low on a hot summer day. 

Also, many plants require a night period for growing well (eg tomatoes, they foul under continuous sunlight), permanent daylight could be more harmful than useful.

**Comment by mokun** [comment]
From Crop's `computeHarvest()`, we have the following: 

```java
	/**
	 * Computes each input and output constituent for a crop for the specified
	 * period of time and return the overall harvest modifier
	 *
	 * @param solarIrradiance
	 * @param greyFilterRate
	 * @param temperatureModifier
	 * @param the maximum possible growth/harvest
	 * @param a   period of time in millisols
	 * @return the harvest modifier
	 */
	private double computeHarvest(double maxPeriodHarvest, ClockPulse pulse,
						double time, double solarIrradiance, double greyFilterRate,
						double temperatureModifier) {

		double harvestModifier = 1D;

		// TODO: use theoretical model for crop growth, instead of empirical model
		// below.
		// TODO: the calculation should be uniquely tuned to each crop
		// TODO: Modify harvest modifier according to the pollination by the number of
		// bees in the greenhouse
		// TODO: Modify harvest modifier by amount of artificial light available to the
		// whole greenhouse

		// Tune the growthFactor according to the stage of a crop
		double growthFactor = 5;
		// amount of grey water/water needed is also based on % of growth
		if (phaseType == PhaseType.GERMINATION)
			// if (phaseType == PhaseType.GERMINATION)
			growthFactor = .2;
		else if (percentageGrowth < 10D)
			growthFactor = .3;
		else if (percentageGrowth < 15D)
			growthFactor = .4;
		else if (percentageGrowth < 20D)
			growthFactor = .5;
		else if (phaseType == PhaseType.FINISHED)
			growthFactor = .4;
		else if ((phaseType != PhaseType.HARVESTING) && (phaseType != PhaseType.PLANTING))
			growthFactor = percentageGrowth/100D;


		// STEP 1 : COMPUTE THE EFFECTS OF THE SUNLIGHT AND ARTIFICIAL LIGHT
		if (cropSpec.getCropCategoryType() == CropCategoryType.FUNGI) {
			adjustEnvironmentFactor(1D, LIGHT_FACTOR);
		}
		else {
			computeLight(pulse, time, solarIrradiance);
		}

		// STEP 2 : COMPUTE THE EFFECTS OF THE TEMPERATURE
		adjustEnvironmentFactor(temperatureModifier, TEMPERATURE_FACTOR);

		// STEP 3 : COMPUTE THE EFFECTS OF THE WATER AND FERTIZILER
		computeWaterFertilizer(growthFactor, time, greyFilterRate);

		// STEP 4 : COMPUTE THE EFFECTS OF GASES (O2 and CO2 USAGE)
		// Note: computeGases takes up 25% of all cpu utilization
		computeGases(effectivePAR, growthFactor, time);
		// Note that mushrooms are fungi and consume O2 and release CO2

		// TODO: add air pressure modifier in future

		// Tune harvestModifier
		// Note that light is the dorminant environmental factor
		if (phaseType == PhaseType.GERMINATION) {
			harvestModifier = .8 * harvestModifier + .2 * harvestModifier * environmentalFactor[LIGHT_FACTOR];
		}
		else if ((phaseType != PhaseType.PLANTING) && (phaseType != PhaseType.INCUBATION)) {
			harvestModifier = .6 * harvestModifier + .4 * harvestModifier * environmentalFactor[LIGHT_FACTOR];
		}

		harvestModifier = .25 * harvestModifier + .15 * harvestModifier * environmentalFactor[FERTILIZER_FACTOR]
						+ .15 * harvestModifier * environmentalFactor[TEMPERATURE_FACTOR]
						+ .15 * harvestModifier * environmentalFactor[WATER_FACTOR]
						+ .15 * harvestModifier * environmentalFactor[O2_FACTOR]
						+ .15 * harvestModifier * environmentalFactor[CO2_FACTOR];

		// TODO: research how the above 6 factors may affect crop growth for different
		// crop categories

		return harvestModifier;
	}
```

Seems we need to be careful with the value of `growthFactor`. It jumps from value to value based on the PhaseType. It's step-wise changes. 

But we should modulate it more carefully since it affects how much water is needed and the amount of gases produced. 

As least we should probably make it continuous, based on the % percentage of growth instead.

Perhaps here is one small area in which we don't have hard-core science data on plant growth and we kind of being inventive in how we model the amount of water/O2/CO2 produced/consumed based on the stage of growth.

**Comment by mokun** [comment]
We implemented what's called the need factor, the fudge factor and growth factor. Looks like it causes the amount of O2 produced and CO2 consumed not in consistent with the water absorbed.

Now I'm consolidating them as we speak in Crop to make things cleaner and simpler.

**Comment by mokun** [comment]
By the way, we have two conversion ratios in Crop to ensure that the rate of O2/CO2 produced/consumed may stay consistent.

```java
	/**
	 * The ratio of oxygen to carbon during the day when photosynthesis is taking
	 * place and CO2 is absorbed and O2 is generated by the crop.
	 */
	private static final double O2_TO_CO2_RATIO = 44 / 32D;
	/**
	 * The rate of carbon dioxide to oxygen during night time when O2 is absorbed
	 * and CO2 is released by the crop.
	 */
	private static final double CO2_TO_O2_RATIO = 32 / 44D; // 6 CO2 --> 6 O2
	// 6nCO2+5nH2O⇒(C6H10O5)n+6nO2

	// public static final double SOLAR_IRRADIANCE_TO_PAR_RATIO = .42; // only 42%
	// are EM within 400 to 700 nm
	// see
	// http://ccar.colorado.edu/asen5050/projects/projects_2001/benoit/solar_irradiance_on_mars.htm#_top
	// public static final double WATT_TO_PHOTON_CONVERSION_RATIO = 4.609; // in u
	// mol / m2 /s / W m-2 for Mars only
```

But we probably need having one between water and O2/CO2 produced/consumed in near future. Shall we ?

**Comment by bevans2000** [comment]
Settlements are running out of water now as the consumption is very high in Greenhouses. I have made the 'refill' Console Command more generic and applicable to Settlement as well. This allows the water to be topped up in expert mode.

![Screenshot 2021-11-20 175834](https://user-images.githubusercontent.com/20720166/142736507-5df0b892-ae3d-4c30-b097-98f1411f9c33.png)
.

**Comment by mokun** [comment]
For an Inflatable Greenhouse, the total growing area for 10 crops is 200 m2. So Each crop is allocated with 20 m2 of space.

Similarly, for a Large Greenhouse, the total growing area for 40 crops is 800 m2. 

Is it good to assume ~4kg of water per m2 per sol ?

If so, we may need to consider drilling into a water source underground. 

This would be a more viable way for ensure a steady water supply.

**Comment by mokun** [comment]
In buildings.xml, we have "Sabatier RWGS Reactor" in SERV for generating some small amount of water per sol as follows:

```xml

	<building type="Starting ERV Base" width="10.0" length="10.0" base-level="0"
			wear-lifetime="3340000" maintenance-time="50" room-temperature="0" base-mass="30">
		<description> The Starting ERV Base (SERVB) is sent ahead of the arrival
			of the human crew. It supplies the settlement with H2 that can be
			converted into CH4 and H2O via Sabatier with RWGS. It performs also
			water electrolysis to generate H2 and O2. Unlike ERV Base, SERVB is
			NOT fully flight capable. It would require retrofitting to be
			flight ready.
		</description>
		<power-required base-power="0.5" base-power-down-power="0.05"/>

		<functions>
			<earth-return capacity="4" />
			<power-generation>
				<power-source type="Solar Power Source" power="5.0" />
			</power-generation>
			<power-storage capacity="20.0" />
			<resource-processing power-down-level="0.0">
				<process name="Sabatier RWGS Reactor" power-required="1.88" default="on">
					<input resource="carbon dioxide" rate="158.4" ambient="true" />
					<input resource="hydrogen" rate="14.4" ambient="false" />
					<output resource="methane" rate="19.2" ambient="false" />
					<output resource="carbon monoxide" rate="67.2" ambient="false" />
					<output resource="water" rate="86.4" ambient="false" />
				</process>
				<process name="Oxygen Generation System" power-required="2.5" default="on">
					<input resource="water" rate="144" ambient="true" />
					<output resource="hydrogen" rate="16" ambient="false" />
					<output resource="oxygen" rate="128" ambient="false" />
				</process>
			</resource-processing>
```

**Comment by bevans2000** [comment]
> For an Inflatable Greenhouse, the total growing area for 10 crops is 200 m2. So Each crop is allocated with 20 m2 of space.
> 
> Similarly, for a Large Greenhouse, the total growing area for 40 crops is 800 m2.
I have never realised that these are a very large area. Are the bigger than the area of the building itself?

> Is it good to assume ~4kg of water per m2 per sol ?
 Seems on the high side but I ha e no clue what is correct.
> 
> If so, we may need to consider drilling into a water source underground.
> 
> This would be a more viable way for ensure a steady water supply.

**Comment by mokun** [comment]
It's very feasible for a typical greenhouse on earth to take a multi-layer approach to maximize the crop yield.

There are other configuration such as a vertical greenhouse that can be deployed in such as a compact way that artificial light are used.

**Comment by bevans2000** [comment]
> It's very feasible for a typical greenhouse on earth to take a multi-layer approach to maximize the crop yield.
> 
> There are other configuration such as a vertical greenhouse that can be deployed in such as a compact way that artificial light are used.

Yes good point. Its artifical light so stacking is fine.

**Comment by Urwumpe** [comment]
A lot of the water should be evaporated by the plant and the soil and increasing moisture content of the air. An amount of it should be recovered by the life support system.

https://en.wikipedia.org/wiki/Evapotranspiration

https://www.usgs.gov/special-topic/water-science-school/science/evapotranspiration-and-water-cycle?qt-science_center_objects=0#qt-science_center_objects

The numbers for corn here mean, up to 3,8l per square meter is evaporated per Earth day. So, 760l of the water consumed by the 200 m² greenhouse should be evaporated at most.

**Comment by mokun** [comment]
> . An amount of it should be recovered by the life support system.

Yes. It's very reasonable to say that not all of the water the crop take in will be used up. Some of them will be released back to the greenhouse and got evaporated. 

May be water is being used as a good medium for temperature regulation as well as the carrier of waste and remover of toxic chemical buildup in a plant. This is true for human in that we urinate. 

Also, for human, in every breath we take, we inhale oxygen (~20%) in the air, we don't actually use up all of the oxygen. We exhale some oxygen and more CO2. 

<html>
<body>


Gas | % in inhaled air | % in exhaled air
-- | -- | --
Oxygen | 21 | 16
Carbon dioxide | 0.04 | 4


</body>
</html>

But in terms of gas exchange for plant/crop, seems it would be more complicated and vary from species and depends on the available light intensity which triggers photosynthesis.

**Comment by mokun** [comment]
@bevans2000 

Do you notice any anomaly on this now ?

**Comment by bevans2000** [comment]
No, but against we probably need Unit test to guarantee the logic is as expected. Will be very difficult to debug in a live simulation

**Comment by mokun** [comment]
Done.
