### ISSUE TITLE
Adopt Google Guava's MutableGraph

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#497]
**Feature Request**
- Adopt Google Guava's [MutableGraph](https://guava.dev/releases/21.0/api/docs/com/google/common/graph/Graph.html) for 
  - tracking relationship scores
  - tracking the container units in every settlement 

**Describe the solution you'd like**
- MutableGraph can be used for creating a hierarchy of who owns who, namely, tracking and changing the parent node and child nodes.

**Describe alternatives you've considered**
- The current approach requires updating the ContainerUnit instance in each unit whenever there is a change of ownership.
- It may have increased the cost of serialization.

See [wiki](https://github.com/google/guava/wiki/GraphsExplained).

**Comment by bevans2000** [comment]
#458 is related to this. I lime the idea of a graph for relationships but I can't see the benefit in the container ownership.

**Comment by mokun** [comment]
It's just more intuitive to use graph to describe the parent and child nodes, all under one graph.

Let's say we define each associated settlement to have its own graph that tracks every unit that belongs there.

**Comment by mokun** [comment]
btw, we've been using guava via its maven artifact.

**Comment by bevans2000** [comment]
OK, relationships is a classic graph problem, lots of nodes and arcs.
The Settlement -> child units is a single layer relationship and having a graph would be overkill. Plus we need to focus on stability as we have made some big changes and there are still lingering problems with them. #488 still neds resolving as they is something definitely wrong. Nevertheless if this is to be done it should be on a branch because recently the master branch has been unstable which is never good.

The simulation certainly "feels" faster after the inventory changes. The pulses are executing much quicker.

**Comment by mokun** [comment]
> The Settlement -> child units is a single layer relationship and having a graph would be overkill.

Yea it could be overkill and we can have our own implementation and optimization. 

For now, It only needs a maximum of 5 layers. e.g. Mars Surface -> Vehicle -> Settlement -> Person -> Equipment.

> still lingering problems with them. #488 still neds resolving 

The transfer() method must deal with setting container units, location states, coordinates etc.. These presentation can be arguably captured by a tree graph.

We only need to piece together building the tree for each settlement and add the ability to access and move the tree branches from time to time.

**Comment by mokun** [comment]
> OK, relationships is a classic graph problem, lots of nodes and arcs.

yes. graph comes in handy for depicting relationship scores. Currently we only account for one to one relationship. 

I wonder if in future we may use it to describe one-to-many relationship for representing group dynamics.  e.g. A, B, C have a group score of 40. But A, C, E have a group score of 80. So the 2nd group is a more "organic" group and they are more likely get together to do tasks/projects/missions.

**Comment by mokun** [comment]
I just found out Guava currently does not natively support Java serialization.

```
00-Adir-01:010.006 (Config) Simulation : Saving the simulation as default.sim.
00-Adir-01:010.006 (Config) Simulation : heapSize: 384.00 MB    heapMaxSize: 1.50 GB    heapFreeSize: 248.05 MB
00-Adir-01:010.006 (Severe) Simulation : ObjectOutputStream: Quitting mars-sim with NotSerializableException when saving C:\Users\mkhelios\.mars-sim\saved\default.sim : com.google.common.graph.StandardMutableGraph
00-Adir-01:010.006 (Config) UIConfig : previous ui_settings.xml deleted.
00-Adir-01:010.006 (Config) UIConfig : Saving the ui_settings.xml.
```

We'll have to find a different graph lib that does or simply roll in our own implementation for RelationshipManager and CreditManager.

Or we simply stick with the existing com.phoenixst.plexus API.

**Comment by bevans2000** [comment]
That s a shame but I think for the existing Relationship manager I think we can write our is  using Unitset to keep the serialized size down.
I'm looking at Missions at the moment trying to reduce the duplication and remove some SonarQube issues.

**Comment by bevans2000** [comment]
#458 will pick up changes to the graph package
