### ISSUE TITLE
How to edit commit msg

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#50]
@shirishag75 @larsnaesbye , I was going to add the description to the first (not the second) commit I made today but I forgot. 

> Remove path from log statement
> 
> r3968
> 2017-05-05
> 
> # CHANGE
> 1. Remove the maven module name and retain only the name of the class
> at the beginning of every log statement in the stacktrace.

How do I add it back ? thx

**Comment by larsnaesbye** [comment]
Hey @mokun  - just so I understand you: you wish to edit the message on a commit that has already been submitted?
If so, then there are several options depending on if it's the latest or not: http://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote

**Comment by larsnaesbye** [comment]
@mokun did you try out the suggestions? Or can we help in another way?

**Comment by larsnaesbye** [comment]
@mokun It's using 'rebase' as explained on https://help.github.com/articles/changing-a-commit-message/ - under "Amending the message of older or multiple commit messages".

**Comment by larsnaesbye** [comment]
In other words:
 * `git rebase -i HEAD~30` or 30 replaced with a number large enough to include the commit
* edit the line that says 'pick 533817' to 'reword 533817'
* save 
* From the manual: "In each resulting commit file, type the new commit message, save the file, and close it."
* Force-push the amended commits: 'git push --force'

**Comment by larsnaesbye** [comment]
@mokun - would you rather I do it instead or is it better to learn interactive rebase? :)

**Comment by mokun** [comment]
@larsnaesbye , can you do it ? I don't wanna mess it up

**Comment by larsnaesbye** [comment]
Okay I did it using interactive rebase. All commits since that one shows as 'mokun committed with larsnaesbye', but the comment is now there :-)

**Comment by mokun** [comment]
@larsnaesbye , I just made two commits in Eclipse using Git a moment ago (btw, I've since switched from using svn to Git in Eclipse for a while :)

The # of commits should have been 3996 but now it's jumped to 4024.

I did notice that when I pushed the commits, it lists out the last 20+ old commits and I think Eclipse was attempting to merge them but there's really nothing change--may be just your name after the rebase. 

Do you think you can fix it and remove those and bump back to 3996 ?

**Comment by larsnaesbye** [comment]
I'm not sure how we can push changes without them being commits...

**Comment by mokun** [comment]
Okay. I should just treat svn and git different because they are different. Issue closed.
