### ISSUE TITLE
overlapped activity spot inside a vehicle

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#501]
**Describe the bug**
- Each activity spot in a vehicle should be occupied by one person only
- Crew tab in Vehicle window should only show the crewmember who have been boarded inside the vehicle.

**Version**
 - Build 6423

**Additional context**
- Crystal N. is still at Lander Hab and has not boarded the vehicle
![image](https://user-images.githubusercontent.com/1168584/141035335-01d3ebbe-9e26-44b5-88af-1ad6c8399a97.png)

**Comment by mokun** [comment]
Just added a new column called "Boarded" 

![image](https://user-images.githubusercontent.com/1168584/141045758-68d125e1-c937-4600-9da6-caa37302790b.png)

**Comment by bevans2000** [comment]
I think this problem may have been resolved by 9d3f2e483edd79bdf3be02271999b6d6018c1be8

**Comment by mokun** [comment]
It looks good now.
![image](https://user-images.githubusercontent.com/1168584/142364616-02c4e31f-85b0-4501-a6c6-c19cf847536d.png)

One thing I notice is that the location of the vehicle goes from place to place when disembarking. There's no reason to move around while loading/unloading resources. Will commit the change in a moment.

**Comment by bevans2000** [comment]
Can we close this now?
