### ISSUE TITLE
Add garment and pressure suit; Customize EVA suit

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#502]
Essential clothing items such as garments and shoes should be taken into consideration in settler's everyday life on Mars 

Also, when doing an EVA, a settler needs to don a EVA suit. 

Each suit is actually made out of 12 item resources (parts), as seen in  `ItemResourceUtil.EVASUIT_PARTS`.

However, once being manufactured, these 12 parts are practically fused together and vanish and cannot be separately tracked. 

Suggestions: 
1. Add garment as everyday clothing to be worn in a settlement.  
2. Enable the `counter pressure suit` of an EVA suit to be worn inside a vehicle. 
3. Enable more customizations of parts of an EVA suit.
4. Track what parts are inside an EVA suit.

**Comment by mokun** [comment]
@bevans2000,

Right now, settlers are complaining that they can't find a garment from their settlement.

I can't find any reasons as to why they fail to do so.
```
00-Adir-01:138.685 (Warning) MicroInventory : [Europa] Sebastian Müller - Attempting to retrieve 1x garment but lacking 1x garment.
00-Adir-01:139.027 (Warning) MicroInventory : [Schiaparelli Point] Maxim Artyukhin - Attempting to retrieve 1x garment but lacking 1x garment.
00-Adir-01:143.792 (Warning) MicroInventory : [Schiaparelli Point] Rik Declercq - Attempting to retrieve 1x garment but lacking 1x garment.
00-Adir-01:152.877 (Warning) MicroInventory : [Zvezda] Roman Vasiliev - Attempting to retrieve 1x garment but lacking 1x garment.
00-Adir-01:167.435 (Warning) MicroInventory : [New Pompeii] Atharv Nagpal - Attempting to retrieve 1x garment but lacking 1x garment.
00-Adir-01:185.669 (Warning) MicroInventory : [Schiaparelli Point] Zuzanna Szymański - Attempting to retrieve 1x garment but lacking 1x garment.
```

A settler who is done with EVA would doff his EVA suit and put on the garment. So it happens in doffEVASuit() in `EnterAirlock` when calling wearStandardClothing().

Somehow, when it calls retrieveItemResource() in MicroInventory, no garment is found.

**Comment by bevans2000** [comment]
So basically everyone is walking round naked 😂😂😂😂 I will have a look

**Comment by bevans2000** [comment]
So the problem is in the ```Person.hasGarment``` method I think. It return true when the Person doesn;t have a garment which generates the error against the Person inventory.

**Comment by mokun** [comment]
You're right.

Currently, hasItemResource() in EquipmentInventory is bad. 

It checks on whether the garment id is in getItemResourceIDs() only and doesn't really look into whether the quantity of the garment is zero or not. 

Perhaps we should also fix getItemsStored() and getResourcesStored() in such a way that if the quantity is zero, that resource should not even be included.

**Comment by mokun** [comment]
Just added the ability to wear a pressure suit in vehicle.

If the pressure suit is not being used explicitly, then it goes back to being a part of the EVA Suit. 

Along the same line of reasoning, I do plan to make other parts shown inside an EVA suit.

However, something is not quite right with storing parts inside Equipment or EVASuit.

Currently, Equipment (and EVASuit) class doesn't implement ResourceHolder or ItemHolder.

**Comment by bevans2000** [comment]
Yes I agree holding g parts in a basic Equipment is not right.

**Comment by bevans2000** [comment]
Probably we should move the MicroInventory from Equipment to EVASuit as well. Having ut un Equipment means all the GenericContainer objects get a microinventory that they do not need.

**Comment by mokun** [comment]
> Probably we should move the MicroInventory from Equipment to EVASuit as well. Having ut un Equipment means all the GenericContainer objects get a microinventory that they do not need.

Yes. Relocating MicroInventory from Equipment to EVASuit as we speak
