### ISSUE TITLE
animated text in the main menu

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#51]
Hi Lars,

I'm incorporating more animation in those options in the main menu.

see static pic below
![animated main menu](https://cloud.githubusercontent.com/assets/1168584/25934876/1615748a-35d5-11e7-878a-d827b2f1393b.png)

When first loaded, it will draw a vertical line and out of that, all options will slide out to the right. 

When I hover over an option, it changes the color. 

When I choose an option, it will blur and darken that.

You can find MenuApp in the /javafx/mainmenu/ in the mars-sim-ui module and run it to see how it behaves.

I found the code from https://github.com/AlmasB/FXTutorials/tree/master/src/com/almasb/civ6menu

We can definitely more of these in other panels.

Any other places you think we can adopt similar animations ?

Note: I know we'll probably have to convert a lot of swing JPanel to JavaFX's UI first.

**Comment by larsnaesbye** [comment]
Wow! That looks stunning. I'll see if I can think of some places.

**Comment by mokun** [comment]
I didn't want to use that wall paper as its origin is unknown. 

So I use our Starfield class to get the white dots and the SpinningGlobe to get the mars globe. I haven't figured out a way to have the asteroid field rendered. 

The sun is glaring right at the center of the Mars globe

see [r3979](https://github.com/mars-sim/mars-sim/commit/73d01deb47bf10ce2d0e64500315a8de325b4998)

**Comment by mokun** [comment]
Animated menu items has been at least partially implemented. Closed.

**Comment by mokun** [comment]
@bevans2000 

I just recalled we did this with JavaFX back then. 

It also included a spinning (draggable) Mars globe.

I feel like we should either use LibGDX or reactiviate JavaFX.

**Comment by Urwumpe** [comment]
> Already thought of it. I want the Simulation Builder to post messages on to the Splash screen reporting the progress of the build

How difficult would it be to show the new features in a major version in an optional window during start?

**Comment by mokun** [comment]
The file called version_history.html is already there. 

However, it takes us to manually type into words what are being updated.

It's the number 6 link under the `User Guide` page.

Click on the link `Version History` on the first page as soon as you open the Help Browser. You won't miss it. 

<img width="783" height="562" alt="Image" src="https://github.com/user-attachments/assets/cbfdc544-3819-4ca6-9e70-38896b7f13e3" />
