### ISSUE TITLE
Ice collection not working

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#517]
**Describe the bug**
- Ice collection does not work. It stays at zero during Ice Prospecting.

**Expected behavior**
- The recent [commit](https://github.com/mars-sim/mars-sim/commit/00dc21bcb7eef3bc30b0a87c0e1b959842e2dfa0) enabled collecting various types of regolith but it was shown in Mission Tool that the ice collection is zero during Ice Prospecting.

**Screenshots**

**Version**
 - build 6522

**Additional context**
- The CollectResourcesMissionCustomInfoPanel class should display both the ice and regolith collection.

**Comment by mokun** [comment]
@bevans2000 

See if you can figure out why either there's zero ice collected or why the Mission Tool doesn't show the correct amount collected.

**Comment by bevans2000** [comment]
> @bevans2000
> 
> See if you can figure out why either there's zero ice collected or why the Mission Tool doesn't show the correct amount collected.

OK, I'll take a look

**Comment by bevans2000** [comment]
Yes, I've found what is wrong. It's the way how resources are explicitly recorded in the generic ```CollectResourcesMission```. Got a fix; just trying to get some tests done for different Missions to check it.

**Comment by mokun** [comment]
> It's the way how resources are explicitly recorded in the generic `CollectResourcesMission`

awesome !

**Comment by mokun** [comment]
> There was also a problem with Barrels not accepting ice as it is a solid not liquid. I have changed the approach so a Barrel accepts Liquid or Solid.

Sure.

Now that you reworked what a barrel can hold, it reminds me to rework the mass of each container. The amount resources and parts that they are composed of need to be in 
consistent with their weight.

**Comment by mokun** [comment]
Something prevents the amount of regolith collected by each person to be updated in Mission Tool:

![image](https://user-images.githubusercontent.com/1168584/144699170-eb26675c-b4f3-4035-8cf1-f4ac85981fb5.png)

**Comment by mokun** [comment]
After the mission is completed, the amount begins to show up.

![image](https://user-images.githubusercontent.com/1168584/144699925-87434935-3376-4003-8af3-a93487e5cf4e.png)

**Comment by mokun** [comment]
or may be it's because I saved the sim and exit and reloaded. 

Whichever the case, it's because the current implementation doesn't look into how much a person is carrying. It only looks for what's in the vehicle.

**Comment by bevans2000** [comment]
The person transfers al, their equipment to the vehicle at the end kf the EVA. Until that happens it is not recorded against the mission.

**Comment by bevans2000** [comment]
Related to EVAs being cancelled when too dark. c1fcf6339994929a34a200e0c6ee439454a44acd

**Comment by bevans2000** [comment]
I'm good to close this

**Comment by mokun** [comment]
As of pre-3.4.0 Build 6946, I looked up a few ice collection mission, none of them brought home any ice so far.

![image](https://user-images.githubusercontent.com/1168584/178848172-1bc70da9-dfab-4e8b-9737-a65eeb8d5e3e.png)

**Comment by bevans2000** [comment]
Its  because it's too dark for EVAs most likely.

**Comment by mokun** [comment]
> Its because it's too dark for EVAs most likely.

So to begin with, we'll need to do a better estimation of the total time it takes will factor in the wasted night time when EVA is not allowed and driving is prohibited.

We don't want to abrupt cut short the trip before we are able to find any ice.

If not, digging local ice would have been more profitable.

**Comment by bevans2000** [comment]
Or lower the light threshold so it is less likely to be a problem.
I will chand the EVAMission to add  an entry to the Mission log when it is too dark.
I quite often disable the check in the code when testing because I think it is too intolerant.

**Comment by mokun** [comment]
Not only ice collection, now regolith collection is not working as well. See https://github.com/mars-sim/mars-sim/issues/629

**Comment by bevans2000** [comment]
Ok let me have a look into it
