### ISSUE TITLE
using codacy

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#52]
@larsnaesbye 

I just started using codacy to help us code better by following their coding opinions.

see https://www.codacy.com/app/mokun/mars-sim/dashboard?bid=4569479

**Comment by larsnaesbye** [comment]
Nice. I've long been thinking if we could find some external review service :)

**Comment by larsnaesbye** [comment]
I [added it to the Wiki](https://github.com/mars-sim/mars-sim/wiki/Development-Environment), and I'll be looking at the NPath warnings :-)
