### ISSUE TITLE
Add a Settlement Combo Box, Building Tab in Monitor Tool

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#524]
**Is your feature request related to a problem? Please describe.**
- Currently, all robots, crops, mission, goods, etc. have their own respective tabs in Mission Tool. 
- However, each tab show the units across all settlements. 
- Even though a player can sort the settlement column so as to highlight what units are in each settlement, this is considered INFORMATION OVERLOADING.

![image](https://user-images.githubusercontent.com/1168584/145088990-eefdc41f-7423-4c34-8372-daad9717449f.png)

**Describe the solution you'd like**
- Have a settlement combo box to choose which settlement's unit to view in Monitor Tool.
- Should be able to choose one settlement at a time but may also choose all settlements under one's jurisdiction/sponsorship.

**Comment by mokun** [comment]
After the last two commits, it looks like this now:

![image](https://user-images.githubusercontent.com/1168584/145144836-3c58dde6-bf38-4044-9059-925556c9d627.png)

**Comment by bevans2000** [comment]
@mokun I like this feature. Should the Settlement tab still should ALL settlements?
Also I think we should add a Building tab and remove the building tab from the Settlement Unit window.. Then selecting a row in the Building tab would display a new Building Unit Window.

**Comment by mokun** [comment]
> Should the Settlement tab still should ALL settlements? 

hmm you point out what the settlement tab should have.

Now, I have in something else in mind.

What kind of visibility should sponsor A have over settlements that are not his own ?

So, in following this train of thought, we need a *sponsor* mode, not a *commander* mode.

A *sponsor* mode is for a player to play the role of a sponsor to manage a list of his settlements.

**Comment by mokun** [comment]
> The Crops tab does not react to the Settlement combo.

Right. We need figure out what useful info we should place in the crop tab.

For now, it's just not important enough to show what category of food crop are being planted....

There are many concerns regarding how well a greenhouse should operate to maximize the yield and minimize the inefficiencies.

None of these are captured in the crop tab so far.

What do you have in mind ?

**Comment by mokun** [comment]
>  should add a Building tab and remove the building tab from the Settlement Unit window.. 

> that would be interesting to show what's going on in a building. The atmosphere, power, the thermal status, etc.

> Then selecting a row in the Building tab would display a new Building Unit Window.

Do you have a visual example ?

**Comment by bevans2000** [comment]
> A _sponsor_ mode is for a player to play the role of a sponsor to manage a list of his settlements.

Interesting. I think the Command mode doesn't make sense and has an odd implementation as it us a pure client construct.

**Comment by bevans2000** [comment]
> > The Crops tab does not react to the Settlement combo.
> 
> Right. We need figure out what useful info we should place in the crop tab.
> 
> For now, it's just not important enough to show what category of food crop are being planted....
> 
> There are many concerns regarding how well a greenhouse should operate to maximize the yield and minimize the inefficiencies.
> 
> None of these are captured in the crop tab so far.
> 
> What do you have in mind ?

Simply filter the Crops shown based in the Settlement of the greenhouse.

**Comment by bevans2000** [comment]
> > should add a Building tab and remove the building tab from the Settlement Unit window..
> 
> > that would be interesting to show what's going on in a building. The atmosphere, power, the thermal status, etc.
> 
> > Then selecting a row in the Building tab would display a new Building Unit Window.
> 
> Do you have a visual example ?

No. But the Building tab would show the key common properties of the Building in the selected Settlement. I can add the tab if we want go down that route. Then work out how to rework the Settlement Unit window.

**Comment by mokun** [comment]
> But the Building tab would show the key common properties of the Building in the selected Settlement. I can add the tab if we want go down that route. 

Sure. Please go ahead and lead the way. I'd like to see how to implement it better than what we used to do with a ___TableModel and ___TableTab class.

**Comment by mokun** [comment]
> > Then work out how to rework the Settlement Unit window.

So, if we convert the *command mode* to *sponsor mode*, then it would make sense to have Settlement tab.

But you meant tweaking the settlement unit window ? 

Sure, making it less bloating is good !

**Comment by mokun** [comment]
> Simply filter the Crops shown based in the Settlement of the greenhouse.

So you want to show one crop per column ? 

I'm beginning to think that monitor tool is good for displaying certain kind of data and the format is not necessarily good for displaying other things...

**Comment by bevans2000** [comment]
> > But the Building tab would show the key common properties of the Building in the selected Settlement. I can add the tab if we want go down that route.
> 
> Sure. Please go ahead and lead the way. I'd like to see how to implement it better than what we used to do with a ___TableModel and ___TableTab class.

Sure no problem. I've got something very rough working in the Monitor tool. Just looking at a BuildingWindow. Needs a bit of more work but it will reduce the load on the SettlementWindow. Also it can be used from the Settlement layout screen when selecting g a Building.

**Comment by bevans2000** [comment]
> > Simply filter the Crops shown based in the Settlement of the greenhouse.
> 
> So you want to show one crop per column ?
> 
> I'm beginning to think that monitor tool is good for displaying certain kind of data and the format is not necessarily good for displaying other things...

I thought there was one row per Crop per Greenhouse? Maybe I'm confused, I will check.

**Comment by mokun** [comment]
> t there was one row per Crop per Greenhouse? Maybe I'm confused, I will check.

Yes. There's already a JTable with each row as a crop

**Comment by bevans2000** [comment]
I've add a draft Building tab to the Monitor Window. The Unit Building window doesn't do anything yet.

**Comment by bevans2000** [comment]
@mokun I've created an Alpha of the Building Window in this commit af32ae2ea49190812829415f2124940c9ef8e18e It is on a separate branch 'buildingwiindow-issue524'. The Building tab in Settlement is broken and doesn't render but I will tidy that up if we are happy with the Building window.
The Alpha just only supports the Living, Farming & Cooking functions at the moment. The General tab needs the image and type details adding. 
To migrate the existing Building Function panel isn't too difficult focusing on changing the top level panels.

**Comment by mokun** [comment]
Having a building tab is awesome.

Now, it would be cool to be able to have a combobox to check on each specific building function. 

How about creating also a building combobox that's next to the settlement combobox ?

Then the building function combobox will be next to them

In each combo box, we should have a "all" option that gives the player the ability to see all of the buildings or all of the functions at once. 

This "all" option is good for comparison.

e.g. I want to see the internal temperature of all buildings at once to look for discrepancy, not just one building's temperature.

**Comment by bevans2000** [comment]
Yes it feels much better especially for large Settlements. It is not updating at the moment because  buildings do not generate events but that will be east to fix. A filter could be useful.
I will crack on and convert the other ```BuildingFunctionPanels``` to the  building Window.

**Comment by bevans2000** [comment]
Now you have added a "Mars" tab with all Settlements I don;t think we need the "Settlement" tab that just show one settlement. It's a duplication?

**Comment by mokun** [comment]
How about having a "sponsored settlements" tab and a separate tab showing "non-sponsored settlements" ?

**Comment by mokun** [comment]
This [commit](
https://github.com/mars-sim/mars-sim/commit/657c0ab2be85a803f97b0dcf26b81725d7acac11
) removes the need for displaying the settlement combobox on the top middle of Monitor Tool when selecting the following 3 tabs : 
1. all settlement tab
2. Mission tab
3. Event tab

**Comment by mokun** [comment]
> Now you have added a "Mars" tab with all Settlements I don;t think we need the "Settlement" tab that just show one settlement. It's a duplication?

I see that both are needed since the "Mars" tab would show the general status for all settlements but the "Settlement" tab only show one particular settlement at a time.

But in case of a single settlement, it's true that both tabs have the same content.

In future, when we truly have the Command Mode, we could "mask" certain information of other settlements from being displayed. 

This is because only the settlement whose commander is the player would have all the info at his finger tip, but it makes sense that he may or may not have insight into other settlements until he starts interacting with each of them, right ?

**Comment by mokun** [comment]
btw, while fixing the FoodInventoryTableModel in this recent [commit](https://github.com/mars-sim/mars-sim/commit/f30f0c45b00509d9d2f01b4f1c76cc4e9a780416), I looked at BuildingTableModel and found out it doesn't update itself yet.

**Comment by mokun** [comment]
> btw, while fixing the FoodInventoryTableModel in this recent [commit](https://github.com/mars-sim/mars-sim/commit/f30f0c45b00509d9d2f01b4f1c76cc4e9a780416), I looked at BuildingTableModel and found out it doesn't update itself yet.

![image](https://user-images.githubusercontent.com/1168584/174883006-20b056d8-a9b2-472c-b118-bc0c044b6124.png)

For now, it tracks the power mode, power required, heat mode and temperature. We could probably show more metrics but we'll need to ask : what's the current use case you have in mind at this point ?

**Comment by mokun** [comment]
@bevans2000 

Is there one last thing you still want to implement in Building Tab for 3.4.0 ?

**Comment by bevans2000** [comment]
No I like the building tab. We still have the redundant nick name getter as there should only be one name but that is a different issue.

**Comment by bevans2000** [comment]
Can we close this now?

**Comment by mokun** [comment]
We can close it but I suppose we need to return and work on the real-time update on power, heat and temperature.
