### ISSUE TITLE
 Can't start simulation

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#53]
Carried over from https://sourceforge.net/p/mars-sim/tickets/80/
Date: 5/17/2017
Creator: Matthew Wilcoxson

I'm unable to start the application. I get a missing class as below:

> $ java -jar mars-sim-3.1.0-p6.jar new
> Command: java -Djava.util.logging.config.file=logging.properties -cp .::jars/ org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx1024m -new
> OUTPUT>Error: Could not find or load main class org.mars_sim.msp.javafx.MarsProjectFX
> 

I also tried to run it in directly:

> $ java -Xms256m -Xmx1024m -Djava.util.logging.config.file=logging.properties -cp mars-sim-3.1.0-p7.jar org.mars_sim.msp.javafx.MarsProjectFX.class
> Error: Could not find or load main class org.mars_sim.msp.javafx.MarsProjectFX.class
> 

I've tried 3.1.0-p6 and 3.1.0-p7, both have the same error. Version 3.0.7 works fine.

I'm using Ubuntu 17.04, with java:

> $ java -version
> openjdk version "1.8.0_121"
> OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-4-b13)
> OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by mokun** [comment]
hmm. I wonder why. 

Do you install the 3.07 debian version ?
I have ubuntu 17.04 as well and is using openJDK.

> $ java -version
> openjdk version "1.8.0_131"
> OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11)
> OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Can you update it to 1.8.0_131 to see if the problem goes away ?
Thanks for setting up this ticket and letting the community know.
If you don't mind, let's open an issue at https://github.com/mars-sim/mars-sim/issues and cut and paste the stuff over there and continue this conversation.

-Manny

**Comment by mokun** [comment]
I have Ubuntu 17.04 as well and is using openJDK and openJFX.

Let's find out what's going on.


> $ java -version
> openjdk version "1.8.0_131"
> OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11)
> OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Q1 : Did you install the 3.07 debian version or just running the v3.07 jar file ?

Q2 : did you also install OpenJFX ?

OpenJDK 8 currently does not automatically come with OpenJFX. They are two separate packages.

OpenJDK shares the API with the Java 8 but without JavaFX's UI components.

OpenJFX is the one providing us JavaFX's UI that mars-sim 3.1.0 are using.

Q3 : if after installing OpenJFX it's still not working, can you install Oracle's Java 8 to see if the problem goes away ?

Do Let me know what you find out. Thanks!

Manny

**Comment by larsnaesbye** [comment]
Haven't we closed the old ticket system? I also have Ubuntu 17.04...

**Comment by mokun** [comment]
I don't know how to "close" it per se. 

May be there's a way to block users from posting new tickets while allowing anyone to see the old tickets. I didn't see anything in the Admin option that allows us to do exactly that. 

Chances we have to carry over tickets from SF to GH manually until people realize GH is better

**Comment by akademy** [comment]
Hello again! (Sorry I put the issue in the wrong place!)

Yes, I didn't have JFX installed. Installing it fixed the problem (I actually came to the same conclusion after trying to build from the source):

    sudo apt install openjfx

The error message was a bit too cryptic, but IntelliJ's build message was much better: Error:(44, 24) java: package javafx.animation does not exist.

For issues: You could add a message to new issues on SourceForge- saying please don't use this, there's a section labelled "Help text to display on new ticket page:" in the settings.

Thanks

**Comment by larsnaesbye** [comment]
No problem! I'm glad you found the solution :)

Closing this ticket since it appears to work for you.

**Comment by mokun** [comment]
> For issues: You could add a message to new issues on SourceForge- saying please don't use this, there's a section labelled "Help text to display on new ticket page:" in the settings.

@akademy , thx for pointing that out. I just did that.

Feel free to provide us feedback and let me know if you are interested in contributing to mars-sim in whatever fashion you are comfortable with.

**Comment by akademy** [comment]
Thanks @mokun , when I have some spare time I would be interested in playing with the code (although apparently there's no official openjfx build for my OS, so that's job one!). Do you have a list of tasks that a newbie to the code would be able to tackle?

**Comment by mokun** [comment]
@akademy , what OS platform do you use ?

**Comment by mokun** [comment]
> a list of tasks that a newbie to the code would be able to tackle?

Yes there are definitely tons of things we want to improve upon. 

I'd say UI is the big obstacle to most people. Any graphical improvement is appreciate.

Besides, we are also looking at enriching our core features.

Question: are you interested in greenhouse farming ?
To me, I would think planting is one of the most important aspect of a Martian colony.

Currently, it takes a few clicks to find the list of crops that a greenhouse is cultivating : 
1. Double click a settlement's name on the Monitor Tool's Settlement Tab.
2. Choose the "Buildings" tab on the left of the panel.
3. Choose a greenhouse such as "Inflatable Greenhouse 1" in the top combo box. 
4. Scroll to the middle to see the crop list shown as a Java Swing's JTable.

Do you have a particular area that you are most passionate about when it comes to living on Mars ?

**Comment by akademy** [comment]
I work mostly on the OS OpenSUSE .

**Comment by akademy** [comment]
Interesting question on what I'd like to be doing on Mars. Difficult to pick one but I guess exploration, both human and robotic. But yes, greenhouses are likely the most important - giving air and food, plus a walk around the garden might be psychologically beneficial!

**Comment by mokun** [comment]
> The error message was a bit too cryptic, but IntelliJ's build message was much better: Error:(44, 24) java: package javafx.animation does not exist.

I wonder why javafx.animation didn't work in OpenSUSE. 

> apparently there's no official openjfx build for my OS, so that's job one!

I've just read about how people have tried compiling OpenJFX to work in OpenSUSE but didn't work.

Do you have any progress on that by any chance ?

**Comment by mokun** [comment]
@akademy,  we've since created a headless version of mars-sim without the use of any graphic framework (no swing or javafx components). It's only ~17 MB and doesn't require installing openjfx. Unfortunately, it's totally non-interactive and will save itself every 15 minutes. See https://github.com/mars-sim/mars-sim/releases
