### ISSUE TITLE
Use of the 2 emergency beds in the EVA airlock

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#532]
**Describe the bug**
- Currently, the 2 beds inside the EVA Airlock building are not being utilized but they were said to be "occupied" as shown in BuildingPanelLiving.
- They are still considered activity spots in LivingAccommodations.

Q: Can they be used for the Sleep Task ?

**Expected behavior**
- If a guest shows up, he/she may make use of these two guest beds.
- If a person is in a health emergency and just get transferred in through the airlock, the medical staff may use one of the beds for emergency surgery or post mortem examination. 

Q: If a settlements lack a medical building, can these two beds be treated as medical bed ?

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/146657871-c20e3edf-472a-4223-a0f3-11b2e8a51c7c.png)

**Comment by bevans2000** [comment]
I'm the opposite. At the moment there is no logic to treat these beds differently from those in a Hab. This means someone could use them as their permanent bed which doesn't make sense. I would drop the bed from  the Airlock building.
The bed occupied value in be UI could be  a bug with it showing the wrong value or does the value mean Beds Assigned?

**Comment by mokun** [comment]
Beds have been removed. 

Having beds or medical beds will draw settlers to show up for accommodation or medical reasons.

This complicates the matter.
