### ISSUE TITLE
People are not reported in  Vehicle

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#535]
**Describe the bug**
People are transferred to a Vehicle and their location is in the Vehicle but they are not present in the Vehicle crew. This was previously working fine but I don't know when it started failing. The impact is no one can exit the airlock from a Vehicle nor can Missions embark because they think no one is inside the Vehicle. I think there maybe a random element.

It is not a UI problem as I've debugged the underlining code.

**To Reproduce**
1. Just run the simulation
2. Wait for a Mission to start and people going tot he Vehcile
3. Compare the Person's Location to the Crewable occupants and there is a difference

**Screenshots**
![image](https://user-images.githubusercontent.com/20720166/146974896-da9a1e9e-add9-45ac-8fcc-745a14e984c3.png)

**Comment by bevans2000** [comment]
I've found it and it may explain weird goings on. The ```Person.getLocalGroup``` is removing entries from the Rover.getCrew collection. I trapped it by making the return of the latter method an unmodifableSet. The same problem will be present in the ```LifeSupport.getOccupants```.Not sure what the getLocalGroup method does but I will put a fix in later and make the returned Collections unmodifiable as a temp. check as well.

```
		if (isInSettlement()) {
			Building building = BuildingManager.getBuilding(this);
			if (building != null) {
				if (building.hasFunction(FunctionType.LIFE_SUPPORT)) {
					localGroup = building.getLifeSupport().getOccupants();
				}
			}
		} else if (isInVehicle()) {
			localGroup = ((Crewable) getVehicle()).getCrew();
		}

		if (localGroup == null) {
			localGroup = Collections.emptyList();
		}
		else if (localGroup.contains(this)) {
			localGroup.remove(this);
		}
```

**Comment by bevans2000** [comment]
Looks like it can be handled by changing the callers toavoid creating a List copy just to remove an entry.

**Comment by mokun** [comment]
> People are transferred to a Vehicle and their location is in the Vehicle but they are not present in the Vehicle crew.

So, what's the definition of being a vehicle crew ? 

To me, being a crew member means the person is being assigned on a mission. 

But that person can be coming in and out of the vehicle such as trying to load or unload things onto the vehicle.

Anyway, I changed something recently on `Person.getLocalGroup` and may have altered the way it behaves.

Thanks for fixing it.

**Comment by bevans2000** [comment]
Occupants is complementary of the container, the two should always be aligned. I think of them as a parent child relationship.
So when a mission member is in a Vehicle they are the occupant  but when they go on the surface they are not: their container is MarsSurface. But in both cases they remain a mission member.
Same applies for Settlement & MarsSurface.
