### ISSUE TITLE
CompositionOfAir class & LifeSupport Function

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#543]
### Discussed in https://github.com/mars-sim/mars-sim/discussions/538

<div type='discussions-op-text'>

<sup>Originally posted by **bevans2000** January  2, 2022</sup>
@mokun I've noticed that the CompositionOfAir class is actually implementing a capability of the Building class. The Building should be responsible for it's own composition stats. Plus doesn't the calculation overlap with the role of the LifeSupport function?
If a Building has no LifeSupport function then it has no air composition. Only inhabitable Buildings can have an Air Composition I think.
So I think we may have some expensive overlapping logic.</div>

**Comment by mokun** [comment]
@bevans2000 ,

So is the change done ? Anything else ?

**Comment by bevans2000** [comment]
Yes. I was thinking of changing from a Set to using  a List to hold the GasDetails. We only need a direct lookup when using the ui panel so it is a little wasteful in memory holding it as a Set when most Use Cases just iterate one the details.

**Comment by mokun** [comment]
> Yes. I was thinking of changing from a Set to using a List to hold the GasDetails. We only need a direct lookup when using the ui panel so it is a little wasteful in memory holding it as a Set when most Use Cases just iterate one the details.

I always thought a Set uses less memory footprint than a List since a list needs to enumerate where each element is at in a List while the elements in a Set have no order in place.

**Comment by mokun** [comment]
btw, I added this new wiki called [Life Support](https://github.com/mars-sim/mars-sim/wiki/Life-Support). 

As you know, currently we actually make use of *resource-processing* function instead of *life-support* function in a building.

And we haven't got that far in doing a detail modeling of the air composition within EVA Suit.
