### ISSUE TITLE
Weather data not updated

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#545]
**Describe the bug**
The weather data in the left panel no longer getting the daily update in the Settlement Map.

**Expected behavior**
The Sunrise, Sunset, Day Light, Zenith, max Light should have been updated by the end of each sol.

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/158713994-6e1c9fd4-2518-47a1-a20a-ea35e9c67b1c.png)

**Desktop (please complete the following information):**
 - r6675

**Comment by Urwumpe** [comment]
Do we have any calculations for this data yet?  Is Max. Light depending on the output of the solar arrays or simply the same as zenith?

**Comment by mokun** [comment]
> Do we have any calculations for this data yet? 

The solar irradiance data should have been captured.

> Is Max. Light depending on the output of the solar arrays or simply the same as zenith?

It's the max solar irradiance for that sol. It varies by location and season and a list of other factors. The optical opacity (caused by Martian dust) also affects its value.

**Comment by mokun** [comment]
We'll need to find out why those labels in SettlementTransparentPanel doesn't receive new values. 

May be it also has to do with the getting-dark method not working ?!

**Comment by mokun** [comment]
It looks like in this [commit](https://github.com/mars-sim/mars-sim/commit/c1fcf6339994929a34a200e0c6ee439454a44acd), it got already fixed. 

Unless we found something else, we'll close this.

**Comment by bevans2000** [comment]
I can't see how this change effect the weather.data. The problem I feel is there are many  caches holding this sort of data.

**Comment by mokun** [comment]
@bevans2000 

What do you think should be the strategy for analyzing the ever-changing weather for each settlement ?

I looked the class and methods responsible for it in this commit. 

It's quite a mystery as to why certain things don't work before. After changing a few things, now at least it works. 

Using the clock pulse to drive the update is just unreliable.

**Comment by bevans2000** [comment]
> Using the clock pulse to drive the update is just unreliable.

It's an event driven simulation so what else could we use? I've only looked at this logic in passing a while ago but for me it seems there was a lot of caching going on and it's based on Coordinates that could be changing when it's used as a Vehicle.

**Comment by mokun** [comment]
It's updating now. I'm closing this.

Perhaps in future, there's a way of predicting what time the sunrise, zenith, sunset will be at a given coordinate.

For now, it always takes one sol to determine those. 

May be we should consider saving these historical weather data for those coordinate and thus saving the computation resources.

**Comment by bevans2000** [comment]
We should not cache these values but calculate them. This accumulated overtime and there is never a purge of cached values.

**Comment by mokun** [comment]
> This accumulated overtime and there is never a purge of cached values.

ok. will do.

Both VehicleLog and Weather data map use MSolDataItem

`private Map<Coordinates, MSolDataLogger<DailyWeather>> weatherDataMap;
`
