### ISSUE TITLE
Edit Mission Dialog

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#547]
**Is your feature request related to a problem? Please describe.**
1. It makes sense to allow players to interact more with a mission, as said in https://github.com/mars-sim/mars-sim/discussions/448#discussioncomment-2376552. 

**Describe the solution you'd like**
1. We may reactivate the use of EditMissionDialog class. It was first instantiated by MissionWindow.
2. We'll need to hand craft specific actions that are allowed for each type of mission. 
3. In terms of actions, once the player click on the "Edit Mission button", the Edit Mission Dialog will pop up. The allowed list of actions are inside a combo box. Once an action is chosen, the player will need to click "Execute" button to set it into motion.  

**Describe alternatives you've considered**
1. Reactivate the "Abort" button and replace the "Modify" button to one or two specific actions in the MissionWindow. No need of opening another dialog.
 
**Screenshot**
![image](https://user-images.githubusercontent.com/1168584/158897671-7dfbadae-86c2-4d0d-943f-60cbcde4b6b2.png)

**Comment by mokun** [comment]
@bevans2000 

Can we discuss what allowed actions we want to craft for now ? 

These actions should be contingent upon the state of the mission.

When a mission is complete. It should be an empty list.

**Comment by bevans2000** [comment]
Sure good idea. I think changing member will be difficult but we can do something to change Missions. Having a generic abort and skip next waypoint will be easy. We could do the latter as an Advance to next phase which would also cover stopping any site exploration as well.

**Comment by bevans2000** [comment]
@mokun I've had a look at this now (after a busy few months at work). 
I think we have to make some change to make this generic enough. The flaw I see at the moment is there is no generic means to abort the current phase. At the moment stopping the Collection phase is explicit but what we need is the ability to abort the current phase and then let the normal Mission Phase processing take over. For a CollectionPhase/ExplorationPhase; the phase is not immediately stopped but marked as ending so that everyone returns to the vehicle. Also it is born out by there being a ```returnHome``` & ```endCollectingAtSite``` in the base ```Mission``` class.
 For the Abort scenario; the next navpoint would be set to the last waypoint; hence it returned home as soon as the current phase normally advanced. For the step current phase scenario; it will work perfectly.
Currently, it is possible that aborting the collection phase could start the return travel to home before everyone has returned to the vehicle.
Needs a bit of reworking but I think it's right.

**Comment by bevans2000** [comment]
Also ```Exploration`` & ```FieldStudyMission``` do not have any means to stop any EVA; hence have a generic means to abort the current phase would make sense.

**Comment by mokun** [comment]
> Also `Exploration` & `FieldStudyMission` do not have any means to stop any EVA; hence have a generic means to abort the current phase would make sense.

That's good you caught that these two missions couldn't be stopped

**Comment by bevans2000** [comment]
Hmmm, after a bit of investigation this could be an opportunity to simplify things in the Mission area and also improve performance.

1. Settlement.isMissionPossible has the same logic that is already in the MetaMission subclasses. And the centralised method may prevent non-Rover missions starting as the probability is calculated in terms of RoverMissions. The Settlement method should just be checking for disabled MissionTypes.
2. TravelMission is in a class hierarchy where it is only extended by VehicleMission. In fact you can't travel anyway without a vehicle as the travel logic is based on a time to move between the navpoints; so the two classes are implementing the same concept. We can collapse these to remove a redundant level.
3. The Missions that use an EVA (all extend RoverMission) should share a new common base class. The EVA logic is repeated differently in each subclass but based on the above we should be able to share it so EVA can be gracefully finished for all EVA based Missions using centralised logic.

**Comment by mokun** [comment]
> 3\. The Missions that use an EVA (all extend RoverMission) should share a new common base class. The EVA logic is repeated differently in each subclass but based on the above we should be able to share it so EVA can be gracefully finished for all EVA based Missions using centralised logic.

How the EVA operation should associate with a Mission has been one of the "pain" points, after we got rid of the Inventory class and replaced it with something else.

So, will this change be causing any problems for the following 3 scenarios ?
1. a person by himself walks into or out of the airlock of a settlement
2. a person by himself walks into or out of the airlock of a vehicle
3. a person on a vehicle drives into or out of the garage of a settlement

**Comment by mokun** [comment]
@bevans2000 

Does the User Abort button work currently ?

Are we still working toward re-activate this button ?

**Comment by bevans2000** [comment]
No there are w few whole in the existing logic because it is a lot of copy and pasting of logic which needs bringing together. I'm thinking of looking at this next as it is part of 3.4.0 as you said. I was excited by #621 but that could go to 3.5.0
