### ISSUE TITLE
Cannot move construction sites

### ISSUE THREAD

**Issue by VorChar** [mars-sim/mars-sim#55]
I tried to move a construction site manually and no matter what keys I pressed on my keyboard the site would not move nor rotate. Trying to use mouse was not that much of a success either as 90% of the times I could not drag the site and in rest 10% of the cases the site would move only in 1 direction.

Running: 
Mars-sim 3.1.0-p7
Windows 7
JDK 1.8.0_131

**Comment by mokun** [comment]
It's actually a known bug. We never finished debugging why the keyboard binding in the ConstructionWizard (also TransportWizard) class doesn't the work the way it's expected to.

I thought in 3.1.0-p7 I already commented out the ability for users to choose the location of a construction site but I'll double check.

Much thanks for pointing it out.

**Comment by mokun** [comment]
@VorChar, I've just fixed the issue with the mouse control when using construction wizard. Will show up in 3.1.0-preview 9.  Will need to research more on why keyboard control is still not working. I'm closing this issue for now. Let me know if you find any other bugs and provide feedback. Thanks!

**Comment by mokun** [comment]
In [r4171]{https://github.com/mars-sim/mars-sim/commit/aa5d382a6a36a7b234ff3b71ef0e3160a197c11e), I improved the responsiveness of the dragging the construction site box around, added a dashed line border, and lighten the color of the site box when the site is being dragged along.
