### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by TheThenThereThat** [mars-sim/mars-sim#556]
- Mars Sim not launching.
- Download the game today for the first time, but the game won't launch. Had JNI error, but downloaded Java 11 and the error stopped producing. Still won't launch both bat or jar file.

Specifications  
 - OS version : Windows 11, 
 - Java version : Oracle Java 8u321
 - mars-sim build version : 6679 and other versions

**Comment by Urwumpe** [comment]
Did you try launching it from a command prompt window (cmd.exe) already? Do you see any error messages there?

**Comment by TheThenThereThat** [comment]
![image](https://user-images.githubusercontent.com/103147749/162615380-46344a3b-1def-4933-86ac-33605bc66079.png)

Yes

**Comment by Urwumpe** [comment]
Weird, it has a problem handling the white space in the java executable path. Also, its possible your Java version is too old. Try going to at least 11, better 17LTS.

**Comment by mokun** [comment]
@TheThenThereThat 
> Java version : Oracle Java 8u321

Yes. It does require java 11.

We'll need to output a statement to notify users that running mars-sim below Java 11 is not supported anymore.

**Comment by mokun** [comment]
@TheThenThereThat 

>  downloaded Java 11 and the error stopped producing. Still won't launch both bat or jar file.

Can you also cut and paste what you see from cmd when running it under java 11 ? 

Thanks !

**Comment by bevans2000** [comment]
Well it looks like the batch file is wrong (I didn't even know there was one !). Also the dependencies jar has the wrong main class. I have just corrected it. It work now by running
```java -jar target\mars-sim-main-3.4.0-jar-with-dependencies.jar```

9352488020449df61628170f65b86480253d2506

**Comment by TheThenThereThat** [comment]
> s a problem handling the white space in the java executable path. Also, its
I am currently using Java 11.

**Comment by TheThenThereThat** [comment]
![image](https://user-images.githubusercontent.com/103147749/163731339-524f1762-ce2c-41a1-810c-fd32b4c0bac3.png)
Using java 11

**Comment by mokun** [comment]
> Well it looks like the batch file is wrong (I didn't even know there was one !). Also the dependencies jar has the wrong main class. I have just corrected it. It work now by running `java -jar target\mars-sim-main-3.4.0-jar-with-dependencies.jar`
> 
> [9352488](https://github.com/mars-sim/mars-sim/commit/9352488020449df61628170f65b86480253d2506)

@bevans2000 

> call java -jar ./mars-sim-main-[$CURRENT_VERSION]-jar-with-dependencies.jar new

In terms of running the batch file, guess no one is using it. But we could update it for the upcoming v3.4.0 release to say

> call java -jar 3.4.0_console_java11.jar 




Question: are we abandoning the need of running MarsProjectStarter class and go straight to running MarsProject at the start of the sim ?

**Comment by mokun** [comment]
> ![image](https://user-images.githubusercontent.com/103147749/162615380-46344a3b-1def-4933-86ac-33605bc66079.png)
> 
> Yes

It said "I/O issues: Cannot run program...."

It seems Java can run MarsProjectstarter class without any issue. Therefore you see it shows all those "--add opens....." 

However, it can't find MarsProject class.

**Comment by bevans2000** [comment]
Since my last commit the dependencies jar works fine,  direct from  the command line using the -jar option. No need to specify a main class.

**Comment by bevans2000** [comment]
Release 3.5.0 will work on Java 20
