### ISSUE TITLE
Couple problems with mineral exploration mission (Only tested one)

### ISSUE THREAD

**Issue by VorChar** [mars-sim/mars-sim#56]
I noticed while creating a mineral exploration mission that while game is paused I cannot see the changes to exploration sites as long as the game is paused. Dragging the flags around also has quite long lag to it.

When trying to modify a existing mission I cannot see any changes at all. If I write more letters to the name the name will remain save but once I commit the changes the name will update on monitor tool. Cannot add or remove members either maybe due to the fact that nothing seems to update while pressing on stuff

Running: 
Mars-sim 3.1.0-p7
Windows 7
JDK 1.8.0_131

**Comment by mokun** [comment]
> mineral exploration mission that while game is paused I cannot see the changes to exploration sites as long as the game is paused. Dragging the flags around also has quite long lag to it.

That's true. If the game is paused, the game loop is not being run and one CANNOT drag any flags at all in the "Create Mission Wizard" panel.  I'll find a way to get around it.

I'll also look into the long lag when dragging flags.

Great that you point this out.

**Comment by mokun** [comment]
> When trying to modify a existing mission I cannot see any changes at all. If I write more letters to the name the name will remain save but once I commit the changes the name will update on monitor tool.

Yes I confirm there is a lag in updating the Mission name in the "Description" textfield in the "Edit Mission" panel. We've been having issues with Swing's JTextField within a SwingNode under JavaFX's UI. Hope there's a simple way to resolve this.

**Comment by mokun** [comment]
> Cannot add or remove members either maybe due to the fact that nothing seems to update while pressing on stuff

I suppose from the design perspective, it should not allow adding/removing members once the Mission progresses the point that Vehicle has already embarked on the journey (left the settlement vicinity). The only way to stop that mission is to hit the "Abort Mission" button.

I may just grey out the

**Comment by VorChar** [comment]
I wasn't able to modify mission members even though the rover hadn't left base. I didn't have desserts so rover never left and still wasn't able to modify the team members of the mission.

I guess just disabling it instead of causing confusion might be a better option at this point

**Comment by mokun** [comment]
True. Inside the "Edit Mission" panel, user is supposed to be given the option to tell the rover to (1) quit the exploration or resource collection mission and (2) come back but the it's not working. Even the "Abort Mission" button has bugs and can't fully "recall" the vehicle and throw NullPointerException from time to time.

**Comment by mokun** [comment]
@VorChar, I've just fixed this flag dragging issue yesterday. Closing this issue now. Appreciate!
