### ISSUE TITLE
Did not work on windows 8.1!

### ISSUE THREAD

**Issue by lynxcode** [mars-sim/mars-sim#57]
How can I run windows 8.1 ? the main screen open but new game and load game command not work. 

```
Command: java -Djava.util.logging.config.file=logging.properties -cp .;*;jars\*
org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx1024m -new
OUTPUT>30.Tem.2017 20:32:23 (Info) MarsProjectFX : Mars Simulation Project v3.1.
0 (preview 7) - Build 3973 - 64-bit 1.8.0_141 - 4 CPU threads
OUTPUT>30.Tem.2017 20:32:25 (Info) MarsProjectFX : Starting a new sim in GUI mod
e in Windows 8.1
OUTPUT>30.Tem.2017 20:32:26 (Severe) SimulationConfig : Error reading config fil
e(s) below : No enum constant org.mars_sim.msp.core.resource.Phase.SOLİD
OUTPUT>java.lang.IllegalArgumentException: No enum constant org.mars_sim.msp.cor
e.resource.Phase.SOLİD
OUTPUT> at java.lang.Enum.valueOf(Unknown Source)
OUTPUT> at org.mars_sim.msp.core.resource.Phase.valueOf(Phase.java:17)
OUTPUT> at org.mars_sim.msp.core.resource.AmountResourceConfig.loadAmountResourc
es(AmountResourceConfig.java:84)
OUTPUT> at org.mars_sim.msp.core.resource.AmountResourceConfig.<init>(AmountReso
urceConfig.java:57)
OUTPUT> at org.mars_sim.msp.core.SimulationConfig.loadDefaultConfiguration(Simul
ationConfig.java:707)
OUTPUT> at org.mars_sim.msp.core.SimulationConfig.loadConfig(SimulationConfig.ja
va:222)
OUTPUT> at org.mars_sim.msp.javafx.MarsProjectFX.prepare(MarsProjectFX.java:394)

OUTPUT> at org.mars_sim.msp.javafx.MarsProjectFX$SimulationTask.run(MarsProjectF
X.java:386)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
OUTPUT> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
OUTPUT> at java.lang.Thread.run(Unknown Source)
OUTPUT>30.Tem.2017 20:32:32 (Info) SpinningGlobe : JavaFX 3D features supported
OUTPUT>Exception in loading sim. Folder parameter must be a valid folder
```

**Comment by mokun** [comment]
do you mean you cannot load a saved sim in Main Menu?

> OUTPUT>30.Tem.2017 20:32:26 (Severe) SimulationConfig : Error reading config fil
e(s) below : No enum constant org.mars_sim.msp.core.resource.Phase.SOLİD

It said It cannot load the Phase class and cannot read the enum SOLID and I wonder why.

Starting a new sim and loading a saved sim works in win 7 and 10 and I don't have win 8/8.1 to test on.

What window localization is your win 8 ?

**Comment by lynxcode** [comment]
win 8.1 TR, menu screen opened. software was not responding when I create new sim or load. Would you like share default .sim file for me, if you have. Thanks for all.

**Comment by mokun** [comment]
Let's do the following just in case : 

1. Create a new folder named "mars-sim-p7"
2. Relocate "mars-sim-3.1.0-p7.jar" there 
3. Open a command prompt and go to the "mars-sim-p7" folder
4. Type "java -jar  mars-sim-3.1.0-p7.jar" to run mars-sim

**Comment by mokun** [comment]
Would you like to try out 3.1.0-p8 to see if it works on your platform? It was just released earlier today. 

Do download the exe installer package and install it on your windows 8.1 to see if it works.

btw, do you by any chance run into issues with any java programs on your platform recently ?

**Comment by lynxcode** [comment]
:( still not work p7 and p8 (windows installer). It freeze print this line :
`OUTPUT> at java.lang.Thread.run(Unknown Source)` , It does not run, load and anything.

**Comment by mokun** [comment]
can you list out your computer specs for me ? what cpu ? how many core/threads ? how much memory ? what java version ?

**Comment by lynxcode** [comment]
sony vaio svf1521 series (TR-asia support)
cpu intel i5 3337u (It has 4 cores), 4gb RAM 
gpu nvidiaGT 740m and intel hd 4000
java version is 1.8.0_144. 
windows 8.1 64 bit
I ran mars-sim on my old intel core 2 due. and win 7 32 bit.

**Comment by mokun** [comment]
can any java program be run on your vaio ?

I suspect it has to do with the environmental variable on your windows 8.1 not being set up correctly.

see https://stackoverflow.com/questions/1672281/environment-variables-for-java-installation

> JDK_HOME  : %JAVA_HOME%
> JRE_HOME  : %JAVA_HOME%\jre

To me, I use JDK, and not JRE. it looks like you use JRE.

I was stuck with the wrong env variable before. Some java program installer was trying to change it and screw that up. 

Sometimes the "javapath" reference on my "PATH" in "System variables" (not in my User's variables") is causing problems. 

> "C:\ProgramData\Oracle\Java\javapath"

Q : how many versions of JRE/JDK have you installed ?

If you have javapath, then Oracle's "Java Control Panel" will decide which version of Java will be used.

**Comment by mokun** [comment]
> OUTPUT>30.Tem.2017 20:32:26 (Severe) SimulationConfig : Error reading config fil
e(s) below : No enum constant org.mars_sim.msp.core.resource.Phase.SOLİD

@lynxcode, have you by any chance changed out anything in resources.xml ? 

Or it's possible that in your system locale, Java has trouble with using this enum method called " valueOf()" for loading the resources.xml and the message.properties file and comparing the two. 

Note that the statement "PhaseType.solid	= solid" is found in message.properties 

see https://stackoverflow.com/questions/11914792/where-does-the-enum-valueofstring-method-come-from

So I'm going to issue a patch in the next build to use a different way to achieve the same objective of reading and comparing some values in the two files, just in case that some non-English system locale sensitive to this issue.

**Comment by lynxcode** [comment]
Hmmm!. I had guessed about localization problem. SOLID is truth string, but SOLİD is in my system language. Thanks, for all.

**Comment by mokun** [comment]
Let me know if you can run the latest build (if you need the binary jar file, let me know). Closing this issue for now.
