### ISSUE TITLE
Does not launch on Mac OS X

### ISSUE THREAD

**Issue by sandrobilbeisi** [mars-sim/mars-sim#58]
Hi

the software does not launch on Mac OS X 10.10.5

nothing gets logged to console !

Java is version 8 Update141 (build 1.8.0_141-b15)

the same problem happened with earlier versions of Mars-Sim and JDK

**Comment by mokun** [comment]
are you running 3.1.0-p7 ?

There are two ways to start mars-sim.

which way do you use ?

**Comment by sandrobilbeisi** [comment]
by double-clicking the jar file

**Comment by sandrobilbeisi** [comment]
this is what I get on the command line with version 3.07

> java -jar /Users/utente/Downloads/mars-sim/mars-sim-main-3.07.jar 
> 
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mars_sim/msp/MarsProjectStarter : Unsupported major.minor version 51.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> 
>

**Comment by sandrobilbeisi** [comment]
whilst version 3.1.0-p7

>java -jar /Users/utente/Downloads/mars-sim-3.1.0-p7.jar 
>
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mars_sim/msp/MarsProjectStarter : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by mokun** [comment]
I hope can double-clicking the jar file in your mac is able to start mars-sim. if not, it may have to do with the jdk setup or something.

If mars-sim is NOT started from a console, it won't show the log.

**Comment by mokun** [comment]
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mars_sim/msp/MarsProjectStarter : Unsupported major.minor version 51.0

It's possible that Java version 8 Update141 (build 1.8.0_141-b15) change the version nameplate and causes the Exception.

I use java 8 (build 1.8.0_131-b11) and don't any problem starting mars-sim.

I'll update to the latest JDK to see what happen on my macbook

**Comment by mokun** [comment]
I just installed JDK 64-bit build 1.8.0_144-b01.

Both methods for starting mars-sim work on my macbook. I can see the Main Menu and the spinning mars globe.

I first go to the folder having the jar file and type  : 

> java -jar mars-sim-3.1.0-p7.jar

**Comment by mokun** [comment]
> Exception in thread "main" java.lang.UnsupportedClassVersionError: 
> org/mars_sim/msp/MarsProjectStarter : Unsupported major.minor version 51.0

I've just converted the master branch to supporting Java 9 ( major.minor is version 53.0) since r4268. 

The latest build should run on both Java 9 and 10.

Let me know any issues you encounter and thanks for any feedback.
