### ISSUE TITLE
Empty Containers are not being fully reused

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#583]
**Describe the bug**
When a container is used it is assigned to only hold that single resource, correct. When the Large Bag is emptied, i.e. returned to the Settlement after a Mission it's quantity becomes zero but it is still tagged with the same resource.
What this means over time is the containers in a Settlement can not be fully reused and eventually there are no usable Containers not  resource locked.

**To Reproduce**
Steps to reproduce is to leave a Simulation running and keep checking the Equipment in a Settlement; eventually Containers locked with a resource.

**Expected behavior**
I think that when the quantity reaches zero we should assume that implicitly the Container is cleaned and can be re-used. We should make more of the GenericContainers re-usable in the ```EquipmentFactory.createEquipment``` method.

**Comment by mokun** [comment]
> I think that when the quantity reaches zero we should assume that implicitly the Container is cleaned and can be re-used.

Yes. 

But I was going to say that powdery substance such as regolith, various types of rocks and others should have dedicated bags.

Once a bag or large bag is being used by these resources, it makes sense they should probably be permanently labeled, unless the settlement has no way of making new bags. 

Do you think so ?

Also, we can have each settlement runs an inventory report by the end of every sol or every 3 sols. 

Then over time, we can use these reports to generate statistics to see how things are going and see the trending.

**Comment by bevans2000** [comment]
How do Settlements make new Containers if there are no empty ones of the correct Resource?
The Reg...Propspecting mission might have a problem with this approach. Because I don't think it decides what type of Reg is taken in the EVA (a, b or c) until on the surface. This means an unused Bag is always needed.

**Comment by mokun** [comment]
> This means an unused Bag is always needed.

Sure. I see what you mean now.

In other words, we want to verify if AT LEAST ONE empty container of each type is available.

So now, the question is, how often and when do we want to check if at least one is  available ? 

And exactly in what method do we want to perform this check so ?

Some methods are called many times per frame.

To avoid excessive checking, may be we check on it once on each frame or once per millisol ?

**Comment by bevans2000** [comment]
What about changing the ConsolidateContainers Task? When this Task is active; it does review all the Containers anyway. Maybe if a Container is emptied as part of this Task we could reset the Resource as it's been fully cleaned.

**Comment by mokun** [comment]
> What about changing the ConsolidateContainers Task?

How optimized is ConsolidateContainers Task now ?

I have wanted to reduce calling isEmpty() in GenericContainer but it seems no way to do it otherwise.

Also, the method findNumEmptyContainersOfType() in EquipmentInventory would call isEmpty() excessively.

**Comment by mokun** [comment]
@bevans2000 This page on [Equipment](https://github.com/mars-sim/mars-sim/wiki/Equipment) is quite old. Will you be able to add some design notes on how various class is currently being used ? Appreciate !

**Comment by bevans2000** [comment]
> @bevans2000 This page on [Equipment](https://github.com/mars-sim/mars-sim/wiki/Equipment) is quite old. Will you be able to add some design notes on how various class is currently being used ? Appreciate !

Sure. I'll try and do it this week.

**Comment by bevans2000** [comment]
If a Container is empties as part of ConsolidateContainers then we can "clean" it and reset the contained resource. This is an easy change with no impact on the processing load.
