### ISSUE TITLE
Height is not working correctly

### ISSUE THREAD

**Issue by EmilPetecki** [mars-sim/mars-sim#59]
Well, Mars Project is full of short people, about 70-80 cm tall, and they are all seriously obese. I don't know how it impacts the game but please, fix that and make the crew members stand tall.

**Comment by mokun** [comment]
Yes thanks for your observation. I'm fixing that now. 

I'm also fixing the frequent occurrence of being under-weighed. 

In both cases, it has to do with a typo made in the PhysicalCondition class. 

I was going to use Math.round(value * 100D)/100D to round up the height and weight but accidentally typed up Math.round(value * 100D)/200D instead, thereby cutting the values in half :(

Do let me know if you find any bugs or things that don't make sense. Appreciate !
