### ISSUE TITLE
Design Idea : Need a coherent UI for storing the full history of a mission

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#593]
**Describe the bug/issue**
What single UI can we envision in showcasing the full history of a mission ?

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 6783
 
**Additional context**
1. the Mission Tool does not show the FULL history of past missions.
2. In terms of Regolith Prospecting, it does show the result of the mission, namely the resource collected (Regolith, Reg-B, Reg-C, Reg-D). 
3. But it doesn't shows who the participants were, the distance traveled, etc.
4. On the other hand, the Monitor Tool's Mission tab records the dates (Mission filed, embarked, returned), mission cmdr, etc.

Q : Can we design an ONE-STOP SHOP to house all the mission info ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/173664268-0a402a40-04fc-47a0-af0e-09a19a95c98e.png)
1. From above, the Monitor Tool's Mission tab currently displays all the missions from all settlements. How do we reconcile the Home Settlement column with the settlement combox box on the top middle ?

![image](https://user-images.githubusercontent.com/1168584/173666331-2cd3c0be-92c6-471c-b33c-8ec56f2f31e1.png)
![image](https://user-images.githubusercontent.com/1168584/173666475-a11b73e8-f500-4892-b160-981eb602e342.png)
2. From above, the vehicle info (status, speed, traveled dist, etc.) are not properly recorded. No dates were included.

**Comment by bevans2000** [comment]
Relates to #888
