### ISSUE TITLE
Show demand, supply, quantity, total mass of each good

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#598]
**Is your feature request related to a problem? Please describe.**
1. Currently, the Trade tab in Monitor Tool shows only the quantity/kg, value and price of each good.
2. The quantity/kg column can be confusing since an amount resource has a total mass while an item resource/vehicle/equipment needs to keep track of the quantity.
3. In order for the mission planners to prepare ahead (as well as for development debugging purposes), it's good to provide detail insights by showing the values of the demand, supply, quantity, total mass of each good on a separate column.

**Comment by mokun** [comment]
See below. 
![image](https://user-images.githubusercontent.com/1168584/174643207-f8790cc1-c003-4f44-b835-89697e5c34e5.png)

Now we have the new Demand column and Supply column.

Also, the quantity (#) column is separated from the total mass (kg) column. 

That's because in for an Amount Resource, it is simply a heap of that resource available. No quantity is needed. 

But for an Item Resource, e.g. a hammer, say there are 10 hammers, each weight 0.5 kg. So there's both quantity and mass. Also, there's the total mass. In this case, we list out the total mass. Thus it's 5 kg.
But

**Comment by bevans2000** [comment]
The ```GoodsManager``` is quite complex. Also it's a singleton so there is also a risk with concurrency problems.

**Comment by mokun** [comment]
> Also it's a singleton so there is also a risk with concurrency problems.

It's no longer a singleton. Each settlement has its own, so that the demand, supply, value and price of a resource are different between each settlement.

**Comment by bevans2000** [comment]
The ```GoodManager``` is awful. Seems there are numerous overlapping methods, e.g. some times use Good and sometimes use Id. A lot of commented out code as well. Also there are a few "magic strings" where names are used to control logic; this is always dangerous.
First step would be to tidy the current class by removing commented code and any uncalled public/private methods. This would give a better view on what is going on.
Certainly can make a starts.

**Comment by mokun** [comment]
> e.g. some times use Good and sometimes use Id.

Yea. In case of a Part (an Item Source), sometimes it's useful to use its resource id for matching. 

But other times it's more helpful to get the object instance of a Part because we can use its object reference to gain access to other attributes of that Part, you know.

**Comment by mokun** [comment]
I'm reworking the relationship between cost and price and profit as follows : 

> profit = cost * factor * Math.log(value + 1)
> price = cost * (1 + factor * Math.log(value + 1));

**Comment by bevans2000** [comment]
I think what we should do in this area is make ```Good``` an abstract class and create a private subclass for each 'version' of a Good. The subclasses could reference their "parent" item directly, basically the Good class becomes a Facade to the real item.
For example ```GoodAmountResource``` would directly reference the associated ```AmountResource``` object. Then we can hold the cost & price modifiers directly on the AmountResource object and get them from the XML. This will remove a lot of the string equals lookup and simplify the code. 
The same pattern can be used for Equipment & Vehicles. Methods like ```computeCostModifier``` can become abstract and implemented in the different subclasses according to their own specific logic. We should be able to do some changes to GoodsUtil to utilise this new pattern.
I quite like this idea but don't want to trample on what your doing @mokun

**Comment by mokun** [comment]
Yes all those are much better ideas that by all means you are more than welcome to go ahead implementing them one by one 💯 

I'd like to create GoodType enum class but is it still something that's advantageous ?

**Comment by bevans2000** [comment]
What would the GoodType represent? There is already GoodCategory I think.

**Comment by mokun** [comment]
> What would the GoodType represent? There is already GoodCategory I think.

e.g. GoodType enums are INSTRUMENT, ELECTRICAL, UTILITY, etc. There are at least 20 different enums.

But GoodCategory only has a few.

Matching are done by a good's type string now and like you say, it's haphazard.

**Comment by bevans2000** [comment]
Right, yes that would fit in well is we start using the Item instance to underpin the Good.

**Comment by bevans2000** [comment]
I've made a start simplifying the Good & GoodUtil classes to use subclasses for the different Good categories. Going for a branch to start with.

**Comment by bevans2000** [comment]
@mokun The reworking of ```GoodsManager``` has become a monster task. This class is 6 sets of logic combined into a single class making it very difficult to understand what is going on. However in this commit fdc785e34b3d86671df793ceb764d0a323c43e98 I've managed to break the logic out at last into the separate subclasses.
What I have noticed is there are a few places in the Supply/Demand logic that don't make sense. Either they always return the same value or return a value that doesn't seem relevant. The clearly obvious mistakes I've corrected but there are some still remaining.
I need to tidy this code up and run some longer tests but ```GoodsManager``` is much better now.

**Comment by mokun** [comment]
> What I have noticed is there are a few places in the Supply/Demand logic that don't make sense. Either they always return the same value or return a value that doesn't seem relevant. 

Sure. Thanks for going over it.

I look forward to seeing cleaner logic.

Imagine how fun it is for us to create a new Martian world by crafting interesting sets of conditions. 

It'll be a lot of more if we can share that with players who are given the ability to steward some of the driving forces behind the economics of Mars.

**Comment by mokun** [comment]
> The clearly obvious mistakes I've corrected but there are some still remaining.

I have some reservations when it comes to type of manufacturing processes the code is selecting.  

Given that the selection priority is partially based upon the facility's tech level and the skill level of the settlers, I still find it very odd to see the lack of good choice. 

To me, one goal is to be able to produce concrete and cement so that more buildings will be constructed.

In case of a 24-person settlement, perhaps it's because the value point for concrete is quite low (only ~113), there seems to be always a very low priority for making construction-related materials.

Any thoughts on fixing it ?

**Comment by mokun** [comment]
@bevans2000 
Q : Do you see that I should continue to get rid of those resource-intensive industrial processes that have nothing to do with creativity in manufacturing.xml and move them over to buildings.xml and treat them as resource processes ?

**Comment by bevans2000** [comment]
Let me finish my changes as then the logic is isolated out of GoodsManager and hence it's easier to understand. 
Also try and avoid making  changes to the GoosManager for a day since the logic has moved and the git merge is harder on my branch.

**Comment by mokun** [comment]
> Also try and avoid making changes to the GoosManager for a day since the logic has moved and the git merge is harder on my branch.

Sure. I'll leave GoodsManager alone for now.

**Comment by bevans2000** [comment]
Cool. I'm doing the merge now so plan to create a PR later today.

**Comment by bevans2000** [comment]
Can we close this one now? The remaining Good optimizations we can do as normal commits.

**Comment by bevans2000** [comment]
> There must be a better and more systematic way in setting the demand at a certain default and not to rely on matching the the specific name of that good.
> 
>

I think my comment on abe13cb7a755a6755ba91f271e7a0babf1b3d21e suggests a better way to use the XML files to allow the supp,y anc demand modifiers to be defined for certain parts/resources. The defaults would be base on GoodType.

**Comment by mokun** [comment]
> The defaults would be base on GoodType.

So, if we no longer match the name of a good, then, in case of the *methane fuel cell* and *methanol fuel cell*, do we need to create a new good type for them ?

**Comment by bevans2000** [comment]
No because for  _methane fuel cell_ and _methanol fuel cell_ we would specify explicit supply & demand modifiers for these Parts. But the majority of parts can be covered by their GoodType ; there will be less Parts where the Type default is not correct.

**Comment by mokun** [comment]
This thread is becoming long and is starting to branch off in other directions.

I'll close this now, since the original purpose of this issue was to add a demand, supply, quantity and mass column for each good has been fulfilled. 

We'll carry on our discussions elsewhere.
