### ISSUE TITLE
Use Price instead of Value Point determining a trade or delivery

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#601]
**Is your feature request related to a problem? Please describe.**
1. Currently, Value Point (VP) is being used between two settlements for a Trading or Delivery mission.
2. The Credit or Debit point is defined as the differences in VP between resources that are bought, sold and delivered.

**Describe the solution you'd like**
1. Switch to using Price instead of VP.
2. The Credit/Debit will become the differences between the total price of all resources bought & sold by the settlement A and the total price of the resources bought & sold by the settlement B.

**Additional context**
1. Each trade/delivery is considered a two-way street. 
2. Even though settlement A may be the one initiating the trade/delivery, while it may sell resources to settlement B, it also buys resources from settlement B at the same time.
3. The differences between all the buying and settling will result in Credit/Debit for that single trade/delivery.

**Version**
- pre-3.4.0 build 6814

**Comment by mokun** [comment]
@bevans2000 

How extensive will the rework of https://github.com/mars-sim/mars-sim/issues/506 be like ?

Should we wait for it to finish first before this one ?

**Comment by bevans2000** [comment]
I haven't looked at #506 for a while. I think #506 was about removing a lot of duplicate code so in theory doing #506 first would make sense because there would be only one set of code to update in this issue?

**Comment by bevans2000** [comment]
We should complete the reworking of GoodsManager in #598 first.

**Comment by mokun** [comment]
> Do you still see a purpose in maintaining the ValuePoint approach if you want to use Price? 

hmm that's a good question. 

We should further narrow down exactly what we see as the primary and may be secondary purpose for the idea of value point . 

In the past, it serves roughly as a priority score that tells us what to manufacture and produce. It's sort of a dream list.

But now that we have cost (though incomplete) and price, trading/delivery should be price-dependent and driven by economics, instead of what the settlement wants to buy but carrying too much of a price tag to own...

**Comment by mokun** [comment]
> I am currently looking to improve how GoodsManager manages the caches and calculating the values for different Good types.

That's great !

Do you want to work on the how the "input" resources should be included as the base cost ? 

We only factor in "output" resources when calculating cost.

**Comment by mokun** [comment]
Also, because all settlements use the same set of manufacturing formulae for producing derived resources, the cost for a derived resource is the SAME for all settlements. 

But we could vary it by allowing the specs of a factory or a manufacturing process to be "upgraded". 

May be research results from some engineering or physics or material science subjects would promote an upgrade "project" to be carried by a team. But then, we need to put together the concept of a project first, as proposed in another thread.

**Comment by mokun** [comment]
Also, we didn't use real regression to look into the cost of a resources. 

e.g. If resource A, B, C are the raw resources. resource D, E, F are derived resources.

Say D comes from A and B, while D comes from B and C and F comes from D and E.

So, the true cost for a F consists the cost of A + 2*B + C and we would skip the cost of D and E.

Currently, it's not done this way and we may have done incorrectly because we didn't factor in the order.

The cost of F should not be known until we figure out the cost of D and E.

**Comment by bevans2000** [comment]
The cost of a load to Trade should be solely based on the total cost of all items in the load. That is clear because then we can clearly define profit for a mission and negotiation. 
My puzzle is how do we initially choose the items in a load? This is the method getBestGood, it has to use the VP.

**Comment by mokun** [comment]
> My puzzle is how do we initially choose the items in a load? This is the method getBestGood, it has to use the VP.

hmm. now that we break the problem down, I'll say that logically speaking, if I have to acquire something from a settlement afar, I'll look at how much my settlement is willing to produce this part vs. another settlement's willing to produce this part. 

Also, I'll look at the availability of this resource in my settlement and another settlement. 

If it takes too long or cost too much to produce it in my settlement, and that another settlement already have it in stock, I'll go to that settlement to alleviate the stress in my supply chain, you know.

**Comment by bevans2000** [comment]
Think the trade command is being really helpful because it has shown the mission cost is huge for Trade. But I've found the problem now. We can simplify how the load credit is calculated when using Good cost instead of value.

**Comment by mokun** [comment]
> We can simplify how the load credit is calculated when using Good cost instead of value.

But for now, i think the cost is the same from all settlements due how we define it.

**Comment by mokun** [comment]
why not using *price* ?

**Comment by bevans2000** [comment]
Correct but some thing we can work on later

**Comment by bevans2000** [comment]
Closing this as the new Commerce logic does not use Value Point
