### ISSUE TITLE
Show a person's meta task probabilities in console

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#603]
**Is your feature request related to a problem? Please describe.**
1. It's immensely helpful to debug what is planning to do or could possibly do
2. meta task probabilities is the taskProbCache map in PersonTaskManager.

**Describe the solution you'd like**
1. The existing command /ta shows only what a person is doing at the moment
2. Add a command called /mt (meta task) to output a table with # of rows and 3 columns.
3. The rows are the different possible meta tasks that he can undertake
4. The 3 columns are : (1) meta task name, (2)  probability score, (3) percent that this metatask could be chosen.

**Describe alternatives you've considered**
1. Alternatively, one may create a meta task tab in a person window to show the content of this table.
2. Since it changes frequently, it should probably house a button to click on in order to refresh to the latest probability scores.

**Additional context**
 ```
00-Adir-02:665 Elodie Girard >  ​/?

Control Keys :
 * tab - Auto completes the input; for commands (long & short) and arguments
 * up - Goes back in the history
 * down - Goes forward in the history

Console Commands (* <short command> <long command>)
Group : Common
 * /xp expert              * /-  intro
 * /?  help                * /rt repeat

Group : Person
 * /ac activities          * /pf profile
 * /at attributes          * /rp role prospect
 * /be bed                 * /sh shift
 * /eq equipment           * /sk skills
 * /e  eva                 * /sl sleep
 * /fr friend              * /so social
 * /h  health              * /sts status
 * /i  inventory           * /st study
 * /jp job prospect        * /ta task
 * /l  location            * /t  training
 * /m  mission

Group : Simulation
 * /#  bye                 * /ms mission summary
 * /c  connect             * /p  pause
 * /d  date                * /mp planning
 * /di distance            * /sv save
 * /ev events              * /se settlements
 * /ep explored            * /sp speed
 * /lo log                 * /st stop

More detailed help by using > help <long command>
00-Adir-02:665 Elodie Girard >  ​
```

**Comment by mokun** [comment]
@bevans2000 Can this is done easily ? 

How do you usually debug why a meta task is chosen by a person ?

I'm trying to find out why no regolith digging have been performed recently and why.

**Comment by bevans2000** [comment]
I use the Console and switch to expert mode. Then you can use the 'work' command to see that last set of Task probabilities.
Or use the diagnostics command with the task argument and it will dump event Task Meta cache to a file.

**Comment by bevans2000** [comment]
But answering your specific question; it is already done in the ```work``` command

**Comment by mokun** [comment]
> But answering your specific question; it is already done in the `work` command

Yes. I can see the wk command now.  

See below in case of Jeremy Adams in console.

```
00-Adir-01:000 MarsNet >  ​/c Jeremy Adams
Connecting to Jeremy Adams .....
Hi, My name is Jeremy Adams and I am a Areologist based in New Plymouth where I am the Logistic Specialist
At the moment, I am 
I am Peak in performance, Famished, Isotonic, Relaxed and Rested.

00-Adir-01:142 Jeremy Adams >  ​/xp
Switching on expert mode
00-Adir-01:142 Jeremy Adams >  ​work
                        Job : Areologist
                  Favourite : Tinkering
                          Task |   Prob |          Trait | Favourite
--------------------------------------------------------------------
        Writing Mission Report |   6.54 | [TEACHING, LEADERSHIP] |        []
                 Tending Crops | 108.00 |     [ARTISITC] | [Tending Plants]
             Digging Local Ice | 1371.88 |     [STRENGTH] | [Operation]
                      Teaching |  47.93 |     [TEACHING] |        []
    Maintaining vehicle by EVA |   0.58 |             [] |        []
        Planning for a mission |   5.32 |             [] |        []
                  Day Dreaming |   0.00 |             [] |        []
        Digging Local Regolith | 13585.56 |     [STRENGTH] | [Operation]
                      Relaxing |   0.04 |   [RELAXATION] |        []

00-Adir-01:142 Jeremy Adams >  
​
```
He's most likely supposed to be digging regolith but it's blank in the Task cell of the All Citizen tab in Monitor Tool.

![image](https://user-images.githubusercontent.com/1168584/175719214-a325aa8b-74d4-487b-8679-614dfbbe0023.png)

 Also blank in the Task Description and all other text areas in the Activity tab of his person window.

![image](https://user-images.githubusercontent.com/1168584/175719246-2b6f6a64-d9d3-40fb-99c0-b2ca60ae254b.png)

Interestingly, in Schedule tab, it's reported that he's alternating between Digging Local Regolith and Digging Local Ice.

![image](https://user-images.githubusercontent.com/1168584/175719348-4707eaf4-9707-422e-a44c-fad2e82ae07f.png)

Below shows Jeremy may have been stuck right outside the EVA Airlock. 
Q: could it be due to recent changes in that he's not able to walk outside ?
![image](https://user-images.githubusercontent.com/1168584/175719512-6260a63e-5bb6-4389-947a-1255c452f01c.png)

Below shows that no one is at the inner door waiting.
Also, he wasn't in the airlock reservation list.
![image](https://user-images.githubusercontent.com/1168584/175719691-0f8ef6e4-b767-40e3-a7dc-ad8f645095f3.png)

**Comment by mokun** [comment]
It works well now as follows :

```

00-Adir-05:375 Schiaparelli Point >  ​/c Anaisha Sai
Connecting to Anaisha Sai .....
Hi, My name is Anaisha Sai and I am a Mathematician based in Schiaparelli Point where I am the Chief of Logistics and Operations
At the moment, I am Digging Local Regolith
I am Peak in performance, Famished, Want a Sip, Relaxed and Rested.

00-Adir-05:572 Anaisha Sai >  ​/xp
Switching on expert mode
00-Adir-05:572 Anaisha Sai >  ​/wk
                        Job : Mathematician
                  Favourite : Lab Experimentation
                          Task |   P Score |    P % |                     Trait |          Favourite
----------------------------------------------------------------------------------------------------
             Tending Fish Tank |     10.40 |   0.33 |                        [] |   [Tending Plants]
        Digging Local Regolith |   1789.16 |  57.39 |                [STRENGTH] |        [Operation]
           Maintaining vehicle |      6.21 |   0.20 |                        [] |                 []
        Planning for a mission |     45.43 |   1.46 |                        [] |                 []
                      Teaching |     16.57 |   0.53 |                [TEACHING] |                 []
        Writing Mission Report |     24.00 |   0.77 |    [LEADERSHIP, TEACHING] |                 []
                 Tending Crops |    294.00 |   9.43 |                [ARTISITC] |   [Tending Plants]
                       Meeting |     54.00 |   1.73 |                        [] |                 []
             Digging Local Ice |    847.07 |  27.17 |                [STRENGTH] |        [Operation]
                  Day Dreaming |      0.00 |   0.00 |                        [] |                 []
  Reporting to Mission Control |     26.00 |   0.83 |    [LEADERSHIP, TEACHING] |                 []
                      Relaxing |      0.04 |   0.00 |              [RELAXATION] |                 []
            Listening to Music |      4.88 |   0.16 |              [RELAXATION] |                 []

00-Adir-05:572 Anaisha Sai >  ​
```

**Comment by bevans2000** [comment]
You have added a % column, nice

**Comment by bevans2000** [comment]
The blank in the Task comes from the description attribute being set to an empty String when a Task finishes. I think we shouldn't do this because in theory a Person is always assigned a Task.

**Comment by bevans2000** [comment]
But I think we can close this because the original objective is completed now
