### ISSUE TITLE
Simulation freezes if pressing the save button while it was on pause

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#605]
**Describe the bug**
1. The simulation becomes frozen when I try to save the simulation that has been on pause.

**To Reproduce**
1. Click the slide button on bottom left to pause the simulation in order to check on something.
2. Click to uncheck the "Pause Overlay On/Off" button on bottom left.
3. Click on either the Save or SaveAs button on top left.
4. Simulation freezes.

**Expected behavior**
1. It's very essential to enable the ability to save a simulation that's on pause.
2. It's unreasonable to 

**Version**
- pre-3.4.0 build 6834

**Additional context**
1. There are two separate saveSimulation() methods, one in MainWindow, one in Simulation.
2. Simulation's saveSimulation() can only be called by clockPulse() in Simulation.
3. MainWindow's saveSimulation() can be called by either MainWindowMeu's shortcut via Ctrl-S or ToolButton saveAsButton or saveButton.
4. From mainWindow's saveSimulation(), Simulation's requestSave() is called and a save request is submitted.
5. In console, when choosing /sv or save, it calls Simulation's requestSave() as well.
6. However, if  a simulation is on pause, then there's no clock pulse.
7. Therefore,  Simulation's saveSimulation() will never be called and simulation is NOT being saved.

**Comment by mokun** [comment]
@bevans2000, 

It appears to have something to do with Swing's UI thread, because when the application was frozen and no longer respond to any of my input, I would go to console, and I can unpause it as follows : 

```
00-Adir-01:243 MarsNet >  ​/p
Restarting the simulation...
Restarted
00-Adir-01:243 MarsNet > 
``` ​

So, how would you like to fix this UI freeze issue, as well as allowing the simulation to save, even when it's on pause?

**Comment by bevans2000** [comment]
Sure, I'll assign it to myself

**Comment by mokun** [comment]
@bevans2000 

What should be the approach in giving back this ability ?

**Comment by bevans2000** [comment]
I haven't looked yet so not sure but I see no reason why it would not be working.
