### ISSUE TITLE
QuantumRenderer Error in fedora

### ISSUE THREAD

**Issue by lynxcode** [mars-sim/mars-sim#61]
I have QuantumRenderer error on my fedora 27 machine. I can't install nvidia driver( I have gt 740m ). Is there other way to open this project.  
`Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx1024m -new
OUTPUT>Graphics Device initialization failed for :  es2, sw
OUTPUT>Error initializing QuantumRenderer: no suitable pipeline found
OUTPUT>java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
OUTPUT>	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
OUTPUT>	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
OUTPUT>	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
OUTPUT>	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
OUTPUT>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
OUTPUT>	at java.lang.reflect.Method.invoke(Method.java:498)
OUTPUT>	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
OUTPUT>Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
OUTPUT>	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
OUTPUT>	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
OUTPUT>	at java.lang.Thread.run(Thread.java:748)
OUTPUT>Exception in thread "main" java.lang.reflect.InvocationTargetException
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
OUTPUT>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
OUTPUT>	at java.lang.reflect.Method.invoke(Method.java:498)
OUTPUT>	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
OUTPUT>Caused by: java.lang.RuntimeException: No toolkit found
OUTPUT>	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:217)
OUTPUT>	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)`

**Comment by mokun** [comment]
Hi @lynxcode , do you use Oracle Java or OpenJDK/OpenJFX ?

**Comment by mokun** [comment]
I found this [thread](https://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s#21203726) in StackExchange.

**Comment by lynxcode** [comment]
I use openjdk/jfx and fedora27 64 bit. 
`Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.msp.javafx.MarsProjectFX -Xms256m -Xmx1024m -new
OUTPUT>Jan 15, 2018 12:03:53 PM (Info) MarsProjectFX : Mars Simulation Project v3.1.0 - Build 4082 - 64-bit 1.8.0_151 - 4 CPU threads
OUTPUT>Jan 15, 2018 12:03:53 PM (Info) MarsProjectFX : Starting a new sim in GUI mode in Linux
OUTPUT>Jan 15, 2018 12:03:53 PM (Info) SpinningGlobe : JavaFX 3D features supported
OUTPUT>Exception in Application start method
OUTPUT>java.lang.reflect.InvocationTargetException
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
OUTPUT>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
OUTPUT>	at java.lang.reflect.Method.invoke(Method.java:498)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
OUTPUT>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
OUTPUT>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
OUTPUT>	at java.lang.reflect.Method.invoke(Method.java:498)
OUTPUT>	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
OUTPUT>Caused by: java.lang.RuntimeException: Exception in Application start method
OUTPUT>	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
OUTPUT>	at java.lang.Thread.run(Thread.java:748)
OUTPUT>Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_iio.so: /usr/lib/jvm/openjfx/rt/lib/amd64/libjavafx_iio.so: undefined symbol: jpeg_resync_to_restart
OUTPUT>	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
OUTPUT>	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
OUTPUT>	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
OUTPUT>	at java.lang.Runtime.load0(Runtime.java:809)
OUTPUT>	at java.lang.System.load(System.java:1086)
OUTPUT>	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
OUTPUT>	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
OUTPUT>	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
OUTPUT>	at com.sun.javafx.iio.jpeg.JPEGImageLoader.lambda$static$0(JPEGImageLoader.java:109)
OUTPUT>	at java.security.AccessController.doPrivileged(Native Method)
OUTPUT>	at com.sun.javafx.iio.jpeg.JPEGImageLoader.<clinit>(JPEGImageLoader.java:108)
OUTPUT>	at com.sun.javafx.iio.jpeg.JPEGImageLoaderFactory.createImageLoader(JPEGImageLoaderFactory.java:49)
OUTPUT>	at com.sun.javafx.iio.ImageStorage.getLoaderBySignature(ImageStorage.java:419)
OUTPUT>	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:317)
OUTPUT>	at com.sun.javafx.tk.quantum.PrismImageLoader2.loadAll(PrismImageLoader2.java:127)
OUTPUT>	at com.sun.javafx.tk.quantum.PrismImageLoader2.<init>(PrismImageLoader2.java:71)
OUTPUT>	at com.sun.javafx.tk.quantum.QuantumToolkit.loadImage(QuantumToolkit.java:727)
OUTPUT>	at javafx.scene.image.Image.loadImage(Image.java:1065)
OUTPUT>	at javafx.scene.image.Image.initialize(Image.java:807)
OUTPUT>	at javafx.scene.image.Image.<init>(Image.java:621)
OUTPUT>	at org.mars_sim.msp.ui.javafx.mainmenu.Globe.<init>(Globe.java:67)
OUTPUT>	at org.mars_sim.msp.ui.javafx.mainmenu.SpinningGlobe.createDraggingGlobe(SpinningGlobe.java:155)
OUTPUT>	at org.mars_sim.msp.ui.javafx.mainmenu.MenuApp.addGlobe(MenuApp.java:106)
OUTPUT>	at org.mars_sim.msp.ui.javafx.mainmenu.MenuApp.createContent(MenuApp.java:82)
OUTPUT>	at org.mars_sim.msp.ui.javafx.mainmenu.MainMenu.initMainMenu(MainMenu.java:161)
OUTPUT>	at org.mars_sim.msp.javafx.MarsProjectFX.start(MarsProjectFX.java:499)
OUTPUT>	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
OUTPUT>	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
OUTPUT>	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
OUTPUT>	at java.security.AccessController.doPrivileged(Native Method)
OUTPUT>	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
OUTPUT>	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
OUTPUT>	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
OUTPUT>	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
OUTPUT>	... 1 more
OUTPUT>Exception running application org.mars_sim.msp.javafx.MarsProjectFX`

**Comment by mokun** [comment]
@lynxcode , let me know if you're still having issue with running it in fedora.

**Comment by mokun** [comment]
Closing it for now. May reopen it as needed. 

openjfx 11 has just been released and we are incorporating it for testing now.
