### ISSUE TITLE
Male to Female Ratio

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#614]
**Describe the bug**
Q: do we want to have 1:1 male-to-female ratio in most settlements ?

**Expected and unexpected behavior**
Unless specified otherwise, UnitManager should bring the ratio to as much as 1:1 as possible ?

**Java classes involved**
UnitManager, SettlementBuilder, PersonConfig should work together in unison on this.

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/177070060-152b51e0-12fe-4929-bc9d-ab0025dd1448.png)
As seen above, this 4-person SpaceX settlement has all female crew.

**Stacktrace**
```
00-Adir-01:000.000 (Config) Mind : [Boringburg] Barbara Nelson - Becomes Doctor, approved by Mission Control.
00-Adir-01:000.000 (Config) Mind : [Boringburg] Rita Campbell - Becomes Botanist, approved by Mission Control.
00-Adir-01:000.000 (Config) Mind : [Boringburg] Catherine Young - Becomes Technician, approved by Mission Control.
00-Adir-01:000.000 (Config) Mind : [Boringburg] Anna Roberts - Becomes Pilot, approved by Mission Control.
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 6884

**Additional context**
1. We could add an optional attribute in some xml files to use player decide what ratio is desired for the type of settlement.
2. It can be a default ratio for each sponsor, based upon the statistics from the past space program that country/bloc would maintain.

**Comment by bevans2000** [comment]
Nice idea. The change should be in the SettlementBuild class as that drives the creation of new entities. The driving property should be on the ReportingAuthority class and hence in the XML file.

**Comment by mokun** [comment]
We haven't done anything yet.

Today I notice another all-female crew as follows :
![image](https://user-images.githubusercontent.com/1168584/188290363-30ede637-b25c-4a9d-aad2-7ef12034c0df.png)

**Comment by mokun** [comment]
Somehow this 4-person settlement is all female. 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/0c7e434b-f157-4ae5-915e-2111cc090178)

Don't know why.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/abaa65a0-72cc-4855-9778-db90c94e2b20)

I suppose we don't need to be too restrictive. 

We could give player the option of 
1. random ratio
2. fix ratio > choose ratio

**Comment by mokun** [comment]
That SpaceX settlement Teslapolis is supposed to have male to female ratio of 1:1. But at the end, it's all female.

**Comment by bevans2000** [comment]
OK, the problem is in the ```SettlementBuilder``` and ```Resupply``` when adding new arrival. I'll tackle it.
