### ISSUE TITLE
Have one XML file per Settlement template

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#621]
**Is your feature request related to a problem? Please describe.**
The current settlement.xml is a very large file. This requires parsing and memory to hold the associated ```SettlementTemplate``` however only a few are actually used.

**Describe the solution you'd like**
The proposal is to store each template in  a dedicated XML file in the same pattern used for Scenarios. The template will only be loaded on demand reducing the parsing and memory consumption. The config class can derived the names of the available the templates from the file names.

Secondly, custom templates can be held in the users local configuration directory.

**Comment by bevans2000** [comment]
Also maybe do the same approach to building.xml file; a separate XML per Building spec.

**Comment by mokun** [comment]
> Also maybe do the same approach to building.xml file; a separate XML per Building spec.

That's true. building.xml is growing big.

But how do you divide up ? what does "a separate XML per Building spec" means ?

**Comment by bevans2000** [comment]
One building type per file is what I was thinking. I've got ideas on how to do this so let's start with with settlement xml first.

**Comment by bevans2000** [comment]
@mokun Do you think we should extend this approach  to the Building as well? There is a nice simplicity to it with each item in a separate file loaded in demand. But there are 40+ buildj gs.

**Comment by mokun** [comment]
Yes this seems more elegant. 

Also you update it to the newer xsd format and I heard the reader should read faster and more secure in principle, right?

**Comment by mokun** [comment]
But with your proposal, do we still need to read in all buildings because some codes in BuildingManager may rely on knowing all building types? 

It can probably be pushed to read at runtime and on demand, instead of having to read all at once at the startup.

**Comment by bevans2000** [comment]
XSD should always be used instead of the older DTD. It is much more flexible.
I can't see any logic that would require to know about all the potential buildings types.
