### ISSUE TITLE
Consolidate Process definition

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#624]
**Describe the improvement**
There appears to be 3 means to specify Processes that take input and produce output, ```WasteProcessSpec```, ```ManufactureProcessInfo``` & ```ResourceProcessSpec```. All have very similar properties and look to be copy and paste of each other in places.
Waste & Resource processes are described in-situ in the Building.xml which results in the same process being repeated hence bloating the files. 

**Improvement**
The improvement is to create a single ```ProcessSpec``` with a type field to cover all 3 cases above. These would be defined within the existing manufacturing XML file. Buildings could reference any required Processes by name,

**Comment by mokun** [comment]
I imagine in future with this new ProcessSpec, we can define other types of processes, other than just these 3 types of processes currently.

But note that, the manu process is the only one that has tech level and skill level requirement imposed upon.

The other two are inherent process of a buiding.

**Comment by bevans2000** [comment]
This is now superseded by a project covering all aspects of the consolidation.
