### ISSUE TITLE
Separate the Mission interaction from the implementation

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#625]
**Describe the problem**
There is a requirement to create a new type of internal Project for training etc. This is similar to Missions but more lightweight. This is discussed in #308.
Also the Mission structure heavily uses a vert deep inheritance hierarchy that can be complex to follow execution. New Missions are difficult to add unless there are a variant of an existing one.

**Improvement**
The improvement is to create a generic Project definition that can be re-used in Missions & Scientific Studies plus future internal projects.
The model below shows how the Project structure can be fitted to the existing Mission module. It gives some example of ProjectSteps that would be available to Missions. The concreate Mission class would be responsible for creating the order of ProjectSteps to be executed. This would remove the heavily layered inheritance logic within Missions.
It could also be re-used for Scientific Studies and the new internal Projects.

Resourcing provisioning would be simplified as each ProjectStep would define the needed resources individually which could be consolidated for a project.

![target model](https://www.plantuml.com/plantuml/png/XLDDRzim3BthLn0v9S0QODUWXtwiXm7h42H3TrOisk4gInb5RUbblts2BIE9NASdMtoFV8zFzbqGpH9Rg_Pa46f2QuBIko2iAu7AwX1WpVuNLgBo4rRGeAoPF9EypHUNzIsAM6pHIObyyqrPUiPsXnpAycDaHYVhlGvuWU4HgoZatVodvrVa4pRxFeER6vXzNYxJspCv0ub_wD40jsgUcPywS07BOQsDjwWcLjuA7jJPEzmcZNnUGKqShb3oUGKEZoDQlsYnOGR-zMlYi6G9TtSs3Vh32Ii5D_Wx4gFPOF2HApn5ttiftIld1O6fsGlu6YweAtX83mFU0Huf2BacPHi2UTSHbahrOVvW_GTjPmAFWivSv9j9Jo_t7p7QdURNIP8Y9yYrhd1mqPktM7VUSp7PVXhSzdF_ahMmGs1qkaMpF1lqWdkgB0wjMVRT-INtOnbLTFGNvAFWVF4kbci9BJ_NJCjnbF40jOV-bpnPBpgw-LyeDEIqfFf8uJuVhoSo5YnYEViaJ3baGcEu_UF1UkxCNUyhfROLeHEggTfAD6zbE9dr4CaQSisZTq4uLgNEUCbHH5zT88CJTt3QcroIoV3GL91GjzdF5F4krM9h_mC0)

**Comment by mokun** [comment]
> a generic Project definition that can be re-used in Missions & Scientific Studies plus future internal projects.

Yes. Can't wait for that to happen so that we can create more team oriented activities for settlers to do together.

> Mission structure heavily uses a vert deep inheritance hierarchy that can be complex to follow execution

True. It's too complicated in creating a new mission and the codes break too easily.

**Comment by bevans2000** [comment]
So in the context of the new Project approach the number of Project steps would not be fixed. We could add new ones as we go along.
The current Mission design is very rigid with no scope for change

**Comment by bevans2000** [comment]
I've started some preparation work for this. First stage is to isolate the current Mission implementation from the actually callers. I've created a ```Mission``` interface and will do the same for ```VehicleMission``` next.
Not sure what to do about ```RoverMission``` yet; I feel it really should be a package only abstract class and not used outside the implementation.

**Comment by bevans2000** [comment]
Been busy so not had any time to work on this. But I've created a ```VehicleMission``` interface but the logic is very intertwined with the rest of the simulation; more than I had thought. The initial commit on the branch captures ALL the interactions with VehicleMission and there are too many.
The next stage is to simplify these interactions into a more stable and isolated design to allow a different Mission implementation to be introduce in parallel.

**Comment by bevans2000** [comment]
This is part of the new project
