### ISSUE TITLE
Stranded outside while unloading resources by EVA 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#630]
**Describe the bug**
- Anna was trying to help unloading resources from rover Martian Cloud but got stranded mysteriously outside on the surface of Mars
- The Ice Collection mission was completed (though no ice was successfully collected. See also [this](https://github.com/mars-sim/mars-sim/issues/517#issuecomment-1183747466)). 
- Martian Cloud did return and disembarked successfully home. Anna was the mission commander. Everything looked normal.

**Expected and unexpected behavior**
- Since if the codes mistakenly allows her to go outside when the rover already went inside a garage, Anna should be able to intelligently decide to come back inside.

**Java classes involved**
List out possible Java classes/methods that are behaving incorrectly.

**Screenshots**

1. Anna was still outside frozen
![image](https://user-images.githubusercontent.com/1168584/179099168-453d4a73-89e8-4eec-927a-aae2c6eb94dc.png)

2. Anna was unable to die
![image](https://user-images.githubusercontent.com/1168584/179099345-11f7c332-6dfd-4a3b-bff5-7e3a3e3e67a2.png)

3. Martian Cloud was at the Completed phase.
![image](https://user-images.githubusercontent.com/1168584/179099742-0cc2638c-5c84-446f-8a29-e6f631205391.png)

**Stacktrace**
```
00-Adir-05:775.644 (Info) EVAMission : [0.1414 N 0.0426 E] Martian Cloud - EVA out of time
00-Adir-05:778.758 (Info) ConnectWithEarth [x2] : [Tian Cheng] Qiang Xu - Watching a movie - 0.148 CUs Used.
00-Adir-05:783.972 (Warning) RoverMission : [0.1414 N 0.0426 E - Martian Cloud] Lena LaGranda - Not fit to operate Martian Cloud
00-Adir-05:795.437 (Info) EVAMission : [0.1269 N 0.0486 E] Martian Cloud - Continue travel, sunrise too late 00-Adir-06:281
...
00-Adir-05:810.779 (Info) VehicleMission : [0.0006 N 0.0002 E] Martian Cloud - Arrived back home Schiaparelli Point.
00-Adir-05:810.779 (Info) RoverMission : [Schiaparelli Point] Martian Cloud - Disembarked at Schiaparelli Point triggered by Anna Kondo.
00-Adir-05:810.779 (Info) RoverMission : [Schiaparelli Point] Martian Cloud - Preloading 4 EVA suits for disembarking.
00-Adir-05:810.779 (Info) TaskManager : [Schiaparelli Point - Martian Cloud] Rik Declercq - Quit 'Proposing a Areology Study' to start new Task 'Unloading Martian Cloud by EVA'.
...
00-Adir-05:843.076 (Info) UnloadVehicleEVA : [0.0000 N 0.0000 W] Rik Declercq - Unloaded Barrel 743 from Martian Cloud.
...
00-Adir-05:848.613 (Info) UnloadVehicleEVA : [0.0000 N 0.0000 W] Rik Declercq - Just unloaded 7.1 kg of resources from Martian Cloud.
...
00-Adir-05:858.474 (Warning) MicroInventory : [Schiaparelli Point] Martian Cloud - Attempting to retrieve 9.296 kg water but lacking 4.0 kg.
...
00-Adir-05:863.504 (Info) EnterAirlock : [Schiaparelli Point - Martian Cloud] Rik Declercq - Could not enter Martian Cloud. Already full.
...
00-Adir-05:888.788 (Info) UnloadVehicleEVA : [0.0000 N 0.0000 W] Anna Kondo - Just unloaded 3.28 kg of resources from Martian Cloud.
...
00-Adir-05:899.561 (Info) UnloadVehicleEVA : [0.0000 N 0.0000 W] Anna Kondo - Just unloaded a total of 1 items from Martian Cloud.
...
00-Adir-05:905.306 (Info) UnloadVehicleEVA : [0.0000 N 0.0000 W] Anna Kondo - Just unloaded a total of 5.0 kg of resources from Martian Cloud.
...
00-Adir-05:911.004 (Info) EnterAirlock : [Schiaparelli Point - Martian Cloud] Anna Kondo - Could not enter Martian Cloud. Already full.
...
00-Adir-05:946.992 (Info) EnterAirlock : [Schiaparelli Point - Martian Cloud] Lena LaGranda - Could not enter Martian Cloud. Already full.
...
00-Adir-06:007.665 (Info) BuildingManager : [Schiaparelli Point] Martian Cloud - Already inside Garage 1.
...
00-Adir-06:008.518 (Info) UnloadVehicleGarage [x22] : [Schiaparelli Point] Maria Pereira - Unloaded EVA Suit 133 from Martian Cloud.
...
00-Adir-06:009.487 (Info) UnloadVehicleGarage : [Schiaparelli Point] Maria Pereira - Unloaded a total of 0.09 kg of resources from Martian Cloud.
...
00-Adir-06:037.517 (Severe) WalkRoverInterior : [Schiaparelli Point] Anna Kondo - Not inside rover Martian Cloud.
00-Adir-06:039.016 (Severe) WalkRoverInterior : [Schiaparelli Point] Lena LaGranda - Not inside rover Martian Cloud.
...
00-Adir-06:080.564 (Info) RoverMission [x5] : [Schiaparelli Point] Martian Cloud - Disembarked at Schiaparelli Point triggered by Rik Declercq.
00-Adir-06:088.316 (Info) UnloadVehicleGarage : [Schiaparelli Point] Rik Declercq - Unloaded EVA Suit 169 from Martian Cloud.
00-Adir-06:089.354 (Info) UnloadVehicleGarage : [Schiaparelli Point] Rik Declercq - Unloaded a total of 0.15 kg of resources from Martian Cloud.
...


```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 6950

**Additional context**
- We should ensure defensively that a person is NOT allowed to go outside by EVA to unload a vehicle unless there is no garage space left in the settlement.

**Comment by mokun** [comment]
@bevans2000 

Have you seen this still happening from time to time ? Even though it's now only happening in very rare occasion

**Comment by bevans2000** [comment]
No I haven't noticed this but I haven't been looking for it.

**Comment by mokun** [comment]
This line `settlement.getBuildingManager().isInGarage(vehicle)` in loadingPhase() and in anyVehiclesNeedEVA() in LoadVehicleEVA.

It's supposed to do the job of checking whether the vehicle went into a garage and is no longer outside.

Now I can think of a scenario in which this person can get stuck outside.

Say, if a vehicle is outside and is being loaded by a person, while it's happening, somewhere the following method is being called: 

```
	/**
	 * Adds a vehicle to a random ground vehicle maintenance building within
	 * a settlement.
	 *
	 * @param vehicle    the vehicle to add.
	 * @param settlement the settlement to find a building.
	 * @throws BuildingException if vehicle cannot be added to any building.
	 *
	 * @return true if it's already in the garage or added to a garage
	 */
	public boolean addToGarage(Vehicle vehicle) {
		if (isInGarage(vehicle)) {
			// Vehicle already on Garage
			vehicle.setPrimaryStatus(StatusType.GARAGED);

			return true;
		}

		return (addToGarageBuilding(vehicle) != null);
	}
```

While the vehicle is being moved to a garage, but the person is still physically within the vehicle, this could be where the problem is when running LoadVehicleEVA because we did not TERMINATE the loading or if a person is getting out of an airlock while we move the vehicle to the garage.

**Comment by mokun** [comment]
Have you seen any instances when this still happens ?
