### ISSUE TITLE
Coding style recommendations?

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#64]
I tend to abuse four functions in Eclipse whenever I have written something:

Organize imports (Ctrl-Shift-O)
Format (Ctrl-Shift-F)
AutoRefactor (Alt-Shift-Y, big set of simple refactors, requires plugin http://autorefactor.org/ )
UCDetector (Alt-Shift-U, finds unused code, requires plugin http://www.ucdetector.org/ )

Shouldn't we make some guidelines or best practice recommendations somewhere?

**Comment by mokun** [comment]
Yes we could ! Let me know where to start

**Comment by larsnaesbye** [comment]
Some good guides already exist, like [Twitter's on GH](https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/styleguide.md): 

But we could start with the first two shortcuts - Organize imports and Format.

**Comment by larsnaesbye** [comment]
Sure, will do sometime next week :)

**Comment by larsnaesbye** [comment]
First version up at https://github.com/mars-sim/mars-sim/wiki/Coding-recommendations
