### ISSUE TITLE
Create a task that studies and analyzes map data set

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#641]
**Is your feature request related to a problem?**
 - Create a task for remotely analyzing the satellite map data. This task can be done before, during and after an Mineral Exploration mission.

**Describe the solution you'd like**
- After an initial Mineral Exploration mission, a site location is pinpointed with very *low* estimation amount of mineral concentration.
- This new task would be used to raise their values so that a subsequent Mining mission would be more meaningful.
 
**Describe alternatives you've considered**
- Continue to explore the same site by calling the following method in `ExploreSite` would increase the estimation amount
 ```
	/**
	 * Improves the mineral concentration estimates of an explored site.
	 *
	 * @param time the amount of time available (millisols).
	 */
	private void improveMineralConcentrationEstimates(double time) {
		double probability = (time * Exploration.EXPLORING_SITE_TIME / 1000.0) 
				* (getEffectiveSkillLevel() + person.getSkillManager().getSkillLevel(SkillType.PROSPECTING)) / 2D
				* ESTIMATE_IMPROVEMENT_FACTOR;
		if (probability > .9)
			probability = .9;
		if ((site.getNumEstimationImprovement() == 0) || (RandomUtil.getRandomDouble(1.0D) <= probability)) {
			improveSiteEstimates(site, getEffectiveSkillLevel());

			logger.log(person, Level.INFO, 5_000,
					"Exploring at site " + site.getLocation().getFormattedString()
					+ ". Estimation Improvement: "
					+ site.getNumEstimationImprovement() + ".");
		}
	}
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7030

**Additional context**
- It's also possible to come up with a task for collaborating with Earth researcher to get more resources in raising the estimation values in some sort of academic exchange program.
- We may consider allowing the set up of some remote weather station at some site to gather data to further refine the calculation and the estimation improvement on the mineral excavation.

**Reference**
- See https://github.com/mars-sim/mars-sim/issues/636 about the Site for a Mineral Exploration mission.
- See https://github.com/mars-sim/mars-sim/issues/628 about Mineral Exploration vs. Mining mission.
- See https://github.com/mars-sim/mars-sim/wiki/Minerals-and-Water-Bound-Ores on the 10 mineral types and 3 locale types and 6 ore deposit types.
- See [minerals.xml](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/resources/xml/minerals.xml).
- See [MineralMapConfig](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/environment/MineralMapConfig.java).
- See [ExploredLocation](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/environment/ExploredLocation.java).
- See [MineralConcentration](https://github.com/mars-sim/mars-sim/blob/master/mars-sim-core/src/main/java/org/mars_sim/msp/core/environment/MineralConcentration.java).

**Comment by mokun** [comment]
And this task for sure will make meaningful use of the computing resources being implemented in this [thread](https://github.com/mars-sim/mars-sim/issues/456).

**Comment by mokun** [comment]
@Urwumpe 

I want to see if we can generate a simple point cloud of the types of mineral resources or water resource on a site.

You mentioned that in this [thread](https://github.com/mars-sim/mars-sim/issues/154). 

The interesting thing is doing some 3-D model to visualize things, rather than that there's 5% probability of finding Hematite at this site and 7% chance of finding Chalcopyrite, etc.

**Comment by Urwumpe** [comment]
Yeah, let me take a look there, maybe I can at least provide a generator for the areologic layers. Thankfully, Mars had no complex plate tectonics for a while.

**Comment by mokun** [comment]
@bevans2000 

I'm going to add a few new data members to `ExploredLocation`.

Things such as estimated area, volume or mass of the mineral reserve have been missing.

Then we can figure out how to make settlers set up and use instruments at a site so as to give a better mineral estimate.

Next, we can work on the possibility of purchasing air time or air rights to use Synthetic Aperture Radar (SAR) satellites to scan areas and narrow down territories as to where to explore. 

At last we can simulate how to use a settlement's computing resources or even have multiple settlements collaborating on a project with talented individual working together to stitch various data sets into one coherent picture of a site.

**Comment by mokun** [comment]
> a generator for the areologic layers

That would be some interesting to see !
