### ISSUE TITLE
Tweak Simlogger

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#647]
**Is your feature request related to a problem? Please describe.**
- Currently, Simlogger has a long param called `long timeBetweenLogs` that will check if the same log statement is asked to be reprinted with a prescribed period of time. This param is in millisecond only and is not in msol. 
- Second, the way the log statement is printed - namely, printing it at the end and with [x84], etc., does not aid debugging.

**Describe the solution you'd like**
- First, instead of using the machine time in terms of millisecond, we could provide another option of having an extra param with msol, or a convenient way of translating millisols back to miliseconds in certain cases.
- Second, printing a log statement at the beginning to report the onset of an event and then print another one at the end with [x84], etc..

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7058

**Comment by bevans2000** [comment]
Not sure I get the point of the change to the log format. Can you provide an example?

**Comment by mokun** [comment]
```
00-Adir-01:578.430 (Info) SystemCondition  [x142] : [New Pompeii] MakerBot 004 - Positioned to get recharged. 
```

Say that MakerBot 004 first plugged itself onto the station at a certain time in the past, And it spent a total of 142 frames at the station.  But we don't really know what time it starts from this log statement.

But we do know the very last log was made at `00-Adir-01:578.430`.

There are many situations in which I'm only interested in when it FIRST starts an event, i.e. plugging itself on a robotic station for the very first time, NOT when it ends.

So what we want is a param to choose whether I want 
- the first statement, or 
- the last statement or 
- both

**Comment by mokun** [comment]
Also, if I want to get some statistics such as finding out in 100 millisols, how many times a person tend the greenhouse, it's more advantageous for me to designate the log to capture millisols, instead of milliseconds.

**Comment by bevans2000** [comment]
I want to simplify the ```Loggable``` interface and drop the coordinate and container methods. I want to replace it with a new getContext method  that returns a String that provides a context of the entity. This means we can use the Loggable in more classes that are not Units.
Secondly the ```Entity``` interface can be used with a new name of ```NamedEnitity```

**Comment by mokun** [comment]
> drop the coordinate and container methods.

But showing coordinate is very good to me. It tells me a settler's lat and lon on the surface of Mars

Can't remember when we use for the container though. May be it's NOT being used often. 

But it's good that EVA Suits as Equipment that extends Unit are Loggable. It was helpful when we were debugging the transfer of EVA Suits.

**Comment by mokun** [comment]
> This means we can use the Loggable in more classes that are not Units.

**Comment by mokun** [comment]
> This means we can use the Loggable in more classes that are not Units.

I'll love that !

**Comment by bevans2000** [comment]
No coordinates will still be shown but they will be in the context

**Comment by bevans2000** [comment]
@mokun I have started looking  at this. I am going to rename```Entity``` to ```NamedEntity``` and then delete ```Loggable```. The new ```NamedEnitity``` will then be used as the seed for logging. This interface will, have a ```getContext``` method that provides the context for the entity in the logging statements. So all good and allows non Units to be used in logging much easier.
However there is a problem, the Bin logic is incorrectly using Entity as well as the owner as a Unit. I see no reason to have both.
Is this ResourceBin logic actually used? Seems to have heavily increased the size of the Equipmentinventory class.
I'm going to clean up the bin logic before making the logging changes.

**Comment by mokun** [comment]
> Is this ResourceBin logic actually used?

No it hasn't yet.

**Comment by bevans2000** [comment]
It's good practice to only add code when it is needed. Otherwise the projects end up having  a lot of unused code which leads to unwanted technical debt. Do it on a branch and keep it out of the main build.
In the next release I want to remove all the dead code. Just over complicates the whole project.

**Comment by bevans2000** [comment]
Wow, the use of our logging framework is very inconsistent. The simlogger has grown too much with way too many overlapping methods. I have just gone through and cleaned it up before making and logic changes.
The proposed change will be a big benefit for classes like Crop and Scientific Study which are not Units.
I will create a PR for the cleanup before doing the other changes

**Comment by mokun** [comment]
Q: how do we avoid having to call *EnterAirlock* x239 times as shown below, when the very first time calling it should tell me not to bother entering that airlock ? 

```
01-Adir-01:833.123 (Info) EnterAirlock [x239] : [Zvezda - EVA Airlock 1] Pavel Bykovsky - Cannot ingress. Exterior door locked at EVA Airlock 1.
01-Adir-01:833.123 (Info) EnterAirlock [x239] : [Terminus - EVA Airlock 3] Beverly Martinez - Cannot ingress. Exterior door locked at EVA Airlock 3.
01-Adir-01:833.123 (Info) EnterAirlock [x239] : [Terminus - EVA Airlock 3] Marilyn Thompson - Cannot ingress. Exterior door locked at EVA Airlock 3.
01-Adir-01:834.040 (Warning) Storage [x544] : [Dream City] Ran out of Taro.

```

There are many tasks that would show up like that. 

What can we do to those tasks ?

**Comment by bevans2000** [comment]
There is no simple single answer. Each case needs understanding why it is occurring and what can be done.
The enter airlock case is because the person will keep trying to enter the airlock during g the same pulse. My guess is the Task logic attempts to enter and continues until it hits the execution limit. 
In case where the person can not advance we should change the task phase e duction method so it consumes all the clock pulse, this means the person essentially waits to enter and tries next pulse.

**Comment by mokun** [comment]
>  instead of using the machine time in terms of millisecond, we could provide another option of having an extra param with msol, or a convenient way of translating millisols back to miliseconds in certain cases.

@bevans2000 

We should be able to easily create a method for converting the milisols to milliseconds to make this possible. 

There is a few benefits associated with this for debugging in milisols and not milliseconds

If I pause the simulation. It shouldn't count toward the time.
