### ISSUE TITLE
Modelling of time

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#650]
**Describe the situation**
Earth time is modelled using a custom ```EarthClock``` class which has numerous bespoke methods. Java has an off the shlef way to model earth time using the existing time package, e.g. LocalDateTime. We should totally remove EarthClock and replace it with the standard Java time classes.

Secondly, ```MarsClock``` represents an every moving time value. Time should be modelled as a fixed immutable object representing a fixed moment in time, as in the LocalDateTime implementation. We should replace the clock approach with a MarsDateTime which is equivalent to the standard earth date time. This would remove the need to call the ``clone``` method excessively and guarantee that there is only one representation in memory for the same point in time.

The MasterClock would be responsible for providing the current Earth & Mars time going forward. This would be automatically updated in each clock pulse.

**Comment by mokun** [comment]
> Secondly, `MarsClock` represents an every moving time value. Time should be modelled as a fixed immutable object representing a fixed moment in time

Yes. Currently we have two constructors in MarsClock. This can be confusing. One has moving time value and has been used in too many class/methods. The other does have one fixed time value only stored inside.

**Comment by mokun** [comment]
> Java has an off the shlef way to model earth time using the existing time package, e.g. LocalDateTime.

How do we use Java's time package to construct a new MarsClock ? 

Note that the timekeeping methods on Mars are very different from Earth and there's no standard Martian time yet.

We are defining our own in-house standard things as we speak.

Also, we haven't considered how to implement Time Zone in mars-sim yet. 

Since there's no national order on Mars yet, we could easily divide Mars into 12 time zones based on longitude, as some has suggested.

**Comment by bevans2000** [comment]
We only use the standard Java time packages to replace EarthClock. We build our own to represent Mars time

**Comment by mokun** [comment]
Do you still like the Earth time and calendar, namely, `earthDateField`, on the top right of the Main Window ?

It requires Weblaf's component `WedDateField` but their development is very slowly. @Urwumpe suggested in the past that we switch UI layout manager to something else but they don't quite support Java 17 and uses reflection.

Any suggestion to rebuild that Earth time and calendar with something similar or better ?

**Comment by bevans2000** [comment]
I think having just the Mars time is sufficient.

**Comment by Urwumpe** [comment]
I think we only need to support Mars time for more interaction, and maybe have GMT time as simple text field somewhere for reference. A custom Mars date picker or time-picker would be nice to have, but not high priority, since we rarely need to select a time manually.
