### ISSUE TITLE
Rework MasterClock's time ratio to improve stability

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#655]
**Is your feature request related to a problem? Please describe.**
- Rework MasterClock's *time ratio* to increase NOT as the exponent of 2.

**Describe the solution you'd like**
- May consider starting at 128x in the multiple of 128x for increase, such as 128x. 128x, 256x, 512x, 768x, 896x, 1024x, 1152x, 1280x, 1408x, 1536x, etc.
- Or starting at 256x in the multiple of 256x.

**Describe alternatives you've considered**
- Make various functions such as `Heating` work better under high time ratio in long run.
- Only change the time ratio increase after 1024x.

**Specifications  (please complete the following information):**
- pre-3.4.0 build 7089
 
**Additional context**
- Increase the ***pulse width*** steadily as time ratio increases in order to prevent negative sleep time.

**Comment by mokun** [comment]
@bevans2000 

I'm experimenting on allowing a gradual increase of the pulse width, aka `lastPulseTime` in MasterClock, in relation to the time ratio.

Do you have any concerns over that ?


How we currently model `lastPulseTime ` is as follows: 

```
				// Get the time pulse length in millisols.
				lastPulseTime = (realElaspedMilliSec * desiredTR) / MILLISECONDS_PER_MILLISOL;

				// Pulse must be less than the max and positive
				if (lastPulseTime > 0) {

					acceptablePulse = true;

					if (lastPulseTime > maxMilliSolPerPulse) {
						logger.config(20_000, "Pulse width " + Math.round(lastPulseTime*100_000.0)/100_000.0
								+ " clipped to a max of " + maxMilliSolPerPulse + ".");
						lastPulseTime = maxMilliSolPerPulse;
					
					}
					else if (lastPulseTime < minMilliSolPerPulse) {
						logger.config(20_000, "Pulse width " + Math.round(lastPulseTime*100_000.0)/100_000.0
								+ " increased to a minimum of " + minMilliSolPerPulse + ".");
						lastPulseTime = minMilliSolPerPulse;
					}
				}
```

**Comment by mokun** [comment]
I would expect the current *pulse width* should be compared to the `optMilliSolPerPulse` at the end of each frame. 

So if the *pulse width* deviates too much from it, then one would gradually bring it back to `optMilliSolPerPulse`.

```
		minMilliSolPerPulse = simulationConfig.getMinSimulatedPulse();
		maxMilliSolPerPulse = simulationConfig.getMaxSimulatedPulse();
		// The optimal width of a pulse
		optMilliSolPerPulse = minMilliSolPerPulse + ((maxMilliSolPerPulse - minMilliSolPerPulse) * 0.25);
		maxWaitTimeBetweenPulses = simulationConfig.getDefaultPulsePeriod();
		desiredTR = (int)simulationConfig.getTimeRatio();

		// Safety check
		if (minMilliSolPerPulse > maxMilliSolPerPulse) {
			logger.severe("The min pulse millisol is higher than the max pule.");
		}
```


```
2022-08-03T12:50:14.1 (Config) MasterClock : -----------------------------------------------------
2022-08-03T12:50:14.1 (Config) MasterClock :                  Base time-ratio : 128x
2022-08-03T12:50:14.1 (Config) MasterClock :           Min millisol per pulse : 0.0112644016
2022-08-03T12:50:14.1 (Config) MasterClock :       Optimal millisol per pulse : 0.8532784212
2022-08-03T12:50:14.1 (Config) MasterClock :           Max millisol per pulse : 3.37932048
2022-08-03T12:50:14.1 (Config) MasterClock :  Max elapsed time between pulses : 1000 ms
2022-08-03T12:50:14.1 (Config) MasterClock : -----------------------------------------------------
```

**Comment by mokun** [comment]
@bevans2000 ,

As you see at time ratio all the way through 2048x, the pulse width remains at around 0.855 millisols.

Above 2048x, it starts to go haywire.

![image](https://user-images.githubusercontent.com/1168584/182705037-40e26733-a809-4a81-91d1-28f882f09da5.png)

So I suppose `optMilliSolPerPulse` is not designed as a fixed value at all.

It's suppose to increase as time ratio increases. 

It's suppose to decrease as time ratio decreases.

**Comment by bevans2000** [comment]
A width pulse width produces a more inaccurate simulation.  In particular the Task logic can consume all the provided pulse width in some situations. So as the pulse gets wider, the same Task can consumed more Mars time at different speeds which seems wrong.

**Comment by mokun** [comment]
>  the Task logic can consume all the provided pulse width in some situations. 

Yes let's fix those tasks so that the remaining time will be returned for that person to go and do another task.

> as the pulse gets wider, the same Task can consumed more Mars time at different speeds which seems wrong.

It merely revealed some underlying problems that we haven't addressed, namely, simply consuming the remaining time, instead of properly returning those remaining time. 

Say my cooking task has a duration of 20 msols. The pulse width is now 2 msols.

If I've done 19 msols in the last frame, then at this frame, I only need to use 1 msol to complete this task. At this frame, I would have started another task and contribute 1 msol to this task.

If we consume the remaining task, then it would be inaccurate.

So, we should fix this regardless we want to vary the pulse width or not, right ?

**Comment by mokun** [comment]
Also, the thing is that having fixed pulse width is very inflexible. 

To me, I want to do a fast forward to **Sol 100**  to see how stable everything is.

But if we have fixed pulse width, I can only set the time ratio to a max of 2048x and have to wait for a long time to get to **Sol 100**.

**Comment by mokun** [comment]
In the next few commit, I'll create a *standard* pulse for use in all task phases of all tasks.

The width of this *standard* pulse is tentatively set to be, say, a fourth, of the latest pulse width.

This way, while in the time parameter of a task phase may bring as much as, say, 10.1380 millisols to that task phase, it will automatically consume of no more than a fourth of this time (i.e. less than 2.53 millisols). 

It will need 4 standard frames to complete this task phase. 

However, if the task phase already have special, hand-crafted codes to take care of how much time is supposed to be used for that activity, then we will need to modify a few things to make this setup fully compatible.

**Comment by mokun** [comment]
From https://github.com/mars-sim/mars-sim/commit/3ba307e04b9ad8c0ede12e6166e3c6518571e249#commitcomment-80338873
> But it seems the same purpose could have been achieved by limiting the time used when calling Task.performMappedPhse instead of changing the logic in every Task implementation.

Yes. What I've done is to wrap around `takeAction()` in `timePassing()` in both `Mind` and `BotMind` within a while loop and inject a standard pulse time each time.

This will save us from going through each task to change how it should consume time in a task phase.

But I'm a bit worry because of the inconsistency we've been having in how some of these task phase are consuming the time in each frame and how they are tracking the total work time.

**Comment by bevans2000** [comment]
I've just pulled these change and seeing some weird behaviour. Using the speed command in the console, the actual time ratio changes continuously. It's not constant.
Also the pulses are so smaller my simulation is not speeding up and it taking longer. It is creating 8K pulses per 1 minute in real time. I am also getting 100s of compressed messages than the pulse width is too small.
Something is now not right.

**Comment by bevans2000** [comment]
Running my simulation for 30 real minutes at x1024 and only simulated 0.500 sol. 
Also the uptime is now wrong; mine reports 4m 45s after 30 minutes running.
I on holiday next week so I will wait until I get back and check then.

**Comment by mokun** [comment]
> Using the speed command in the console, the actual time ratio changes continuously. It's not constant.

There are two places where the value of actualTR is computed. 

One is within addTime() has been modified as follows: 

```
	/**
	 * Adds earth time and mars time.
	 *
	 * @return true if the pulse was accepted
	 */
	private boolean addTime() {
		boolean acceptablePulse = false;

		if (!isPaused) {
			// Find the new up time
			long tnow = System.currentTimeMillis();

			// Calculate the elapsed time in milli-seconds
			long realElapsedMillisec = tnow - tLast;
			
			// Make sure there is not a big jump; suggest power save so skip it
			if (realElapsedMillisec > MAX_ELAPSED) {
				// Reset the elapsed clock to ignore this pulse
				logger.warning("Elapsed real time is " + realElapsedMillisec + " ms, longer than the max time "
			                   + MAX_ELAPSED + " ms.");
				
				// Reset lastPulseTime
				lastPulseTime = optMilliSolPerPulse;
				// Reset realElaspedMilliSec
				realElapsedMillisec = (long) (optMilliSolPerPulse * MILLISECONDS_PER_MILLISOL / (int)simulationConfig.getTimeRatio());
			}
			
			else if (realElapsedMillisec == 0.0) {
				// Set realElaspedMilliSec
				realElapsedMillisec = (long) (optMilliSolPerPulse * MILLISECONDS_PER_MILLISOL / desiredTR);
			}
			
			else {
				// Adjust the actual TR
				checkActualTR();
				
				// Obtains the latest the time pulse length in millisols.
				lastPulseTime = (realElapsedMillisec * actualTR) / MILLISECONDS_PER_MILLISOL;
				
				// Adjust the time pulse
				checkPulseWidth();
			}
			
			if (lastPulseTime > 0) {
				acceptablePulse = true;
			}
			
			// Elapsed time is acceptable
			if (keepRunning && acceptablePulse) {
				
				// The time elapsed for the EarthClock aligned to adjusted Mars time
				long earthMillisec = (long)(lastPulseTime * MILLISECONDS_PER_MILLISOL);

				// Calculate the actual rate for feedback
				actualTR = earthMillisec / realElapsedMillisec;

				if (!listenerExecutor.isTerminated()
					&& !listenerExecutor.isShutdown()) {

					// Update the uptimer
					uptimer.updateTime(realElapsedMillisec);

					// Add time to the Earth clock.
					earthClock.addTime(earthMillisec);

					// Add time pulse to Mars clock.
					marsClock.addTime(lastPulseTime);

					// Run the clock listener tasks that are in other package
					fireClockPulse(lastPulseTime);
				}
				else {
					// NOTE: when resuming from power saving, timePulse becomes zero
					logger.config("The clockListenerExecutor has died. Restarting...");
					resetClockListeners();
				}
				
				// Do the pulse
				timestampPulseStart();
			}
		}
		return acceptablePulse;
	}
```

`earthMillisec` is based upon `lastPulseTime`, which is the width of a pulse, as you know.

`long earthMillisec = (long)(lastPulseTime * MILLISECONDS_PER_MILLISOL);`


The basic definition of actualTR hasn't been changed. It was the same as before :
`actualTR = earthMillisec / realElapsedMillisec`

It's actually a good thing to find out how `actualTR` varies over time since `earthMillisec` and `lastPulseTime` vary over time.

On the other hand, `preferredTR` is a fixed value and is the value of the exponent of 2.

**Comment by mokun** [comment]
> Also the pulses are so smaller my simulation is not speeding up and it taking longer. It is creating 8K pulses per 1 minute in real time. 

Yes I know that before the change, the pulse width is at ~0.85.

Now that I tweaked the `optMilliSolPerPulse ` to be as follows: 

```
	/**
	 * Adjusts the optimal pulse time according to the desire TR.
	 */
	private void adjustOptimalPulseWidth() {
		// Re-evaluate the optimal width of a pulse
		optMilliSolPerPulse = minMilliSolPerPulse 
				+ ((maxMilliSolPerPulse - minMilliSolPerPulse) * desiredTR / MAX_TIME_RATIO);
	}
```

It increases proportionally with `desiredTR / MAX_TIME_RATIO`. 

But it seems that in case of very small time ratio, the optimal pulse time is too small.

For large time ratio, the optimal pulse time is a lot bigger proportionally.

**Comment by mokun** [comment]
We could define the first available time ratio to be 128x. So there will be NO MORE 1x to 64x.

```
		<!-- The time span covered by each simulation pulse is defined below. These are defined in terms of
		     milliSols. The lower the value, the more accurate the simulation but the more pulses & more expensive
		     to calculate. Note both values can be adjusted if the processing becomes too excessive.
		-->
		<!-- Default: 0.0112644016 millisols or 1 earth second. Min is 0.01. Max is 10.1380. 
		     Must be smaller than max-simulated-pulse   -->
		<min-simulated-pulse value="0.0112644016"/>

		<!-- Default: 10.1380 millisols or 15 earth mins. Min is 0.01. Max is 10.1380 
		     Must be greater than min-simulated-pulse   -->
		<max-simulated-pulse value="10.1380"/>

```

May be we could define the min-simulated-pulse to be bigger to start with.

**Comment by mokun** [comment]
For a 1-settlement simulation, I have the following at the start of the sim

![image](https://user-images.githubusercontent.com/1168584/183226969-d98e7623-448a-4915-b660-836e59dbca87.png)

**Comment by mokun** [comment]
30 seconds later, I increase the speed. The Uptime looks rather normal to me.

![image](https://user-images.githubusercontent.com/1168584/183227098-f9ba8fb4-8e25-4c37-a28e-6e3651e78c40.png)

**Comment by bevans2000** [comment]
I think the actualTR is correctly Reporting the achieved rate. For my simulation the time pulse was so small it was never increasing and always below the desired rate. I was doing a 2 settlement simulation.

**Comment by mokun** [comment]
> May consider starting at 128x in the multiple of 128x for increase, such as 128x. 128x, 256x, 512x, 768x, 896x, 1024x, 1152x, 1280x, 1408x, 1536x, etc.
> Or starting at 256x in the multiple of 256x.


@bevans2000 

Is there anything that prevents us from adding more time ratios in between ?

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

Currently, all time ratios are the multiples of 2. 

May be the advantage is that they aid computation in what the previous or next time ratio is.

But they really don't need to be that way, right ?

**Comment by Urwumpe** [comment]
I don't think so, since the sim isn't anything real-time anyway.

**Comment by mokun** [comment]
> I don't think so, since the sim isn't anything real-time anyway.

Agree. It should be much better if we make less abrupt change as we switch to having smaller incremental increase or decrease of time ratio.

**Comment by mokun** [comment]
> I think the actualTR is correctly Reporting the achieved rate. For my simulation the time pulse was so small it was never increasing and always below the desired rate. I was doing a 2 settlement simulation.

I'll attempt to change how the actualTR and desiredTR should relate to sleepTime. 

Ideally speaking, if actualTR is greater or less than desiredTR, then our goal is to see a increase or decrease on actualTR by adjusting the sleepTime. Or may be we need to adjust the pulse width as well.

I see how it works currently is not optimal and is reworking MasterClock and will commit once done.

**Comment by mokun** [comment]
@bevans2000 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/24c35b53-df47-4407-8add-96bb8c73512b)

I'm trying to find out what's consuming CPU resources, thus stretching the pulse width and slowing down the TPS.

**Comment by mokun** [comment]
Guess I didn't realize earlier there was an unsuccessful commit that never went upstream. 

That commit has to reworking the meteorite impact for each settlement. 

I'll see if it's the culprit causing the anomaly to happen.

Stay tune.

**Comment by mokun** [comment]
@bevans2000 

I just tried going back a few commits to this from 2 days ago 
> [Merge pull request](https://github.com/mars-sim/mars-sim/commit/a461271325ac4d3d0ac238e67584f5867a012f5d) https://github.com/mars-sim/mars-sim/pull/1181 [from mars-sim/person_issue47](https://github.com/mars-sim/mars-sim/commit/a461271325ac4d3d0ac238e67584f5867a012f5d)

The time anomaly was found as well. See below : 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/58c32e90-adf9-4956-8b36-2d56193df836)

So it must have been there for a little while.

I'll go back another day to see how far back it first started.

**Comment by mokun** [comment]
I made another one day jump to go back to this one on Dec 22, 2023 :
> [Rework building activity spots](https://github.com/mars-sim/mars-sim/commit/4c3fbd18848108ad89e64a57ee188c28d29e2093)

It looked normal again without any time anomaly. The Pulse width stays within limits. See below : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/10137593-fe3c-4521-9c8f-b8a793bbc525)

So we now know the anomaly was introduced between this [4c3fbd1 commit]() and that [a461271 commit](https://github.com/mars-sim/mars-sim/commit/a461271325ac4d3d0ac238e67584f5867a012f5d).

**Comment by mokun** [comment]
@bevans2000 

I don't know how real but when using VisualVM to try to track it down. All it shows is the 46% of CPU are on settlers walking outside checking for collisions : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/16b3e863-910e-41a9-ae27-e63968a36dc2)

Is there a way to override the EVA operation or to stop settlers from going outside in Console ? 

If they all stay inside, let's see if the time anomaly disappears.

**Comment by bevans2000** [comment]
Just take the appropriate MetaTasks out of the main list. You will also have to disable that weird code that does a schedule EVA.

**Comment by mokun** [comment]
> Just take the appropriate MetaTasks out of the main list. 

If I try manually commenting out dig local meta tasks, it may impact many things... Will try tomorrow 

>You will also have to disable that weird code that does a schedule EVA.

I thought you have replaced scehduling EVA with your own implementation and they work well, right ?

**Comment by mokun** [comment]
I've found out the culprit is what happens within an EVA Chamber during ingress.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/de19f47f-3eb1-41c9-938a-228da59ec242)

Andrei Matei is the only person inside this EVA Airlock. 

Pressurizing the chamber seems to have causing the sudden jump in CPU in EnterAirlock.

It seems to have started on this commit called [Get empty EVA chamber pos](https://github.com/mars-sim/mars-sim/commit/62e62e9a4dde77785bdbc4f45ad10f226d22027f)
on 12.23.2023.


Trying to see what needs to be fixed now.


```
01-Adir-01:441.508 (Info) EVAOperation : [9.6800 N 24.5700 E] Andrei Matei - EVA Digging Local Regolith aborted: End of Work Shift.
...
01-Adir-01:444.643 (Info) MasterClock : optPulse is larger than 5: 14.740240854763652
01-Adir-01:446.263 (Info) MasterClock : optPulse is larger than 5: 14.355794507198189
01-Adir-01:447.916 (Info) MasterClock : optPulse is larger than 5: 13.982177587454496
01-Adir-01:449.598 (Info) MasterClock : optPulse is larger than 5: 13.618917358970997
01-Adir-01:451.312 (Info) MasterClock : optPulse is larger than 5: 13.265835887777982
01-Adir-01:453.058 (Info) EnterAirlock : [Arcadia - EVA Airlock 1] Andrei Matei - Chamber already depressurized for entry in EVA Airlock 1.
...
01-Adir-01:453.058 (Info) MasterClock : optPulse is larger than 5: 53.06334355111193
...
01-Adir-01:454.925 (Info) MasterClock : optPulse is larger than 5: 318.38006130667156
01-Adir-01:457.027 (Info) EnterAirlock : [Zvezda - EVA Airlock 1] Vyacheslav Aksyonov - Ready to depressurize the chamber.
...

```

**Comment by bevans2000** [comment]
Well done finding the problem. Let's redesign this area in the future and simplify it

**Comment by mokun** [comment]
@bevans2000 

I don't know what it is. Something is constantly causing the execution time to go beyond 1 sec. This causes the simulation to pause from time to time on my laptop with 8 cores.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/c15b9077-259f-4b6a-824a-00e85db5ef56)

**Comment by bevans2000** [comment]
I have seen this and it's annoying. I have noticed 1000s occurrences of certain log messages. My guess is the recent pulse changes means some Task logic is repeatedly looping.

**Comment by mokun** [comment]
Okay. I'll take a closer look at Heating, AlgaeFarming and Fishery's time Passing() tomorrow to see if the changes made in them recently are causing the spike in execution time.

**Comment by mokun** [comment]
Would you like to try limiting indoor activities only to see if the execution time spike would go away ? 

Is there a way to use Visualvm better to capture methods that cause the spike ?  at the moment when it happens ?
