### ISSUE TITLE
maven error under openjdk 10 in debian

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#66]
I got the following errors while trying to compile under openjdk 10 using - 

`mvn clean package install `

see http://paste.debian.net/1024414/

although jftr, at least in openjdk 10 openjfx is still part of openjdk .  Am surprised to see the networking and other errors, either upstream library is not good, or some changes need to be done in mars-sim, in either way, above my head. 

Hope it helps.

**Comment by mokun** [comment]
The openjfx package needs to be installed. As you can see below, javafx.animation and other JavaFX packages are missing.

> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/Simulation.java:[42,24] package javafx.animation does not exist
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/Simulation.java:[43,24] package javafx.animation does not exist
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/Simulation.java:[44,26] package javafx.application does not exist
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/Simulation.java:[45,19] package javafx.util does not exist
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/Simulation.java:[152,27] cannot find symbol
>   symbol:   class Timeline
>   location: class org.mars_sim.msp.core.Simulation
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/UnitManager.java:[60,26] package javafx.collections does not exist
> [ERROR] /home/shirish/games/mars-sim/mars-sim-core/src/main/java/org/mars_sim/msp/core/UnitManager.java:[61,26] package javafx.collections does not exist

**Comment by mokun** [comment]
@shirishag75 , I'm still in the process of looking into each class in mars-sim that use Oracle's proprietary API (such as `com.sun.javafx.iio.ImageFrame`). 

Java 8 allows the use of these internal APIs. They are subject to change from each major version of Java.

However, in Java 9, Oracle decides to make it very strict in their usage. They are inaccessible unless I do something to fix it.

I'll have to weed them out if I cannot find the substitute.

See [1](https://stackoverflow.com/questions/1834826/it-is-a-bad-practice-to-use-suns-proprietary-java-classes), [2](https://github.com/TestFX/TestFX/issues/228), and [3](https://blog.codefx.org/java/java-9-migration-guide/)

**Comment by mokun** [comment]
> The openjfx package needs to be installed.
> As you can see below, javafx.animation and other JavaFX packages are missing from line 17-28 from your stack trace.

To my understanding, since the creation of JavaFX and inclusion of it in the official Java 8, Oracle decided that it's best to separate the openjfx source code and binary package from each openjdk release for the open source community.

**Comment by shirishag75** [comment]
I do understand that, it will take time to be figured out. I/We in the Debian community are looking to see java 11 to be released soon so that a proper binary for openjdk11, openjre11 and openjfx with the same version :)

**Comment by mokun** [comment]
@shirishag75 , do you have openjdk 9 with openjfx installed in debian by any chance ? 

See if you can try out the v3.1.0p9_java9 on it to see how well it runs.

**Comment by shirishag75** [comment]
I am right now cold on java 10 so unable to help till 11 comes out.  In Debian testing there is openjdk-8-jre and openjfx but only for java 8 - 

```
$ aptitude search openjfx
p   libopenjfx-java                                      - JavaFX/OpenJFX 8 - Rich client application platform for Java (
p   libopenjfx-java-doc                                  - JavaFX/OpenJFX 8 - Rich client application platform for Java (
p   libopenjfx-jni                                       - JavaFX/OpenJFX 8 - Rich client application platform for Java (
p   libopenjfx-jni-dbgsym                                - debug symbols for libopenjfx-jni                              
p   openjfx                                              - JavaFX/OpenJFX 8 - Rich client application platform for Java  
p   openjfx-source                                       - JavaFX/OpenJFX 8 - Rich client application platform for Java (
```

**Comment by mokun** [comment]
I suspect openjfx 8 may work with openjdk 9/10. It seems there's no recent update on JavaFX specs. Only bug fixes. Do you mind trying that ?

**Comment by shirishag75** [comment]
I tried that but it asks to install openjdk-8-jre install. 

```
$ sudo aptitude install openjfx
The following NEW packages will be installed:
  openjdk-8-jre{a} openjdk-8-jre-headless{a} openjfx 
0 packages upgraded, 3 newly installed, 0 to remove and 19 not upgraded.
Need to get 27.4 MB of archives. After unpacking 100 MB will be used.
Do you want to continue? [Y/n/?] n
Abort.

```

**Comment by mokun** [comment]
See [this](https://www.mkyong.com/linux/debian-change-default-java-version/). 

You can have as many versions of java installed as you want. I sometimes use ubuntu and multiple Java 8 builds installed. It's just a matter of switching from one to another based on my need. I

I'm just trying to see if at least you can run the latest mars-sim under openjdk/jfx 8 on debian.

**Comment by mokun** [comment]
Has anyone successfully installed openjdk/jfx 9 on debian ? I was reading [this](https://groups.google.com/forum/#!topic/linux.debian.maint.java/PbQTqxH6CnQ)

**Comment by shirishag75** [comment]
There were other people trying to do the same thing, but all questions come to naught, see this [thread](https://lists.debian.org/debian-java/2018/05/msg00064.html)

**Comment by mokun** [comment]
> FWIW, I did try to do as shared above and the results come to nothing.

Sorry that I should clarify between being as a `user` running mars-sim as a user under Java 8 VM vs. being a `developer` setting up maven to compile the mars-sim source codes.

> Note : I have just lately switched the master branch to supporting Java 9 only. The source code can no longer be compiled under Java 8 without some [particular changes](https://github.com/mars-sim/mars-sim/commit/0df864882ab72fa2ad0a86f3f3375d12180dc8fd).

So I'm trying to see if there is any hiccup in simply running mars-sim in debian under Java 8 for `users` but need to double check if everything works as expected. You are a more proficient in linux than me and especially debian is your preferred platform.

**Comment by mokun** [comment]
Can you tell me a bit more details when you compile the source code as seen in http://paste.debian.net/1026712/ ?

Can you post the more detail log ? 

It said it fails when compiling `mars-sim-mapdata`.

There is a total 6 classes in this particular maven submodule but none of them make use of any JavaFX API. They use only standard Java API. So openjdk should suffice.

**Comment by shirishag75** [comment]
hope this helps http://paste.debian.net/1026717/

**Comment by shirishag75** [comment]
I did the following - 

```
~/games/mars-sim$ cat pom.xml | grep maven.compiler.source
		<maven.compiler.source>10</maven.compiler.source>
						<source>${maven.compiler.source}</source>

~/games/mars-sim$ cat pom.xml | grep maven.compiler.target
		<maven.compiler.target>10</maven.compiler.target>	
						<target>${maven.compiler.target}</target>
```

**Comment by mokun** [comment]
So it's good. http://paste.debian.net/1026733/ shows javafx package is missing. no more issues with `mars-sim-mapdata`.

> As far as eclipse is concerned, as shared by you, see this so the eclipse build does not help me as we got an ancient build in Debian.

Sounds like the developers of Debian distro is sticking with old Eclipse package from 6 years ago. I have no idea if there's any technical reasons behind for it.

Is it an option for you to install the latest Eclipse IDE package for Java development ? 

I recommended [efxclipse](http://downloads.efxclipse.bestsolution.at/downloads/nightly/sdk/) but you can always use the latest standard eclipse IDE for Java, either 4.7.3a or 4.8RC2 in linux

**Comment by shirishag75** [comment]
From what I could understand and have been knowing the Debian ecosystem a bit, it seems that the Java packaging team had been short-staffed for quite sometime.  Hopefully they will be able or even be forced to upgrade the eclipse packaging or have netbeans 9 as an alternative build environment.  The due date for all packages to pass through NEW and then into unstable/sid and testing/buster is February 2019.  So will have to see what all they do. I have subscribed to the bug so will know what steps they take next.

**Comment by shirishag75** [comment]
Just had an update about java-common yesterday, see the changelog.gz - 

```
java-common (0.66) unstable; urgency=medium

  * Team upload.

  [ Emmanuel Bourg ]
  * Use salsa.debian.org Vcs-* URLs
  * Removed the GCJ paths from jvm_includes
  * Simplified debian/rules

  [ Matthias Klose ]
  * Remove all references to the plugin and gcj packages.
  * Add the default values for Java 12

 -- Emmanuel Bourg <ebourg@apache.org>  Mon, 28 May 2018 15:59:28 +0200

```

**Comment by mokun** [comment]
@shirishag75 , I've been refactoring the codes for compiling into a binary that requires no javafx or openjfx. It'll be very super lightweight. I estimate the size for this binary to be ~18MB.

It'll just run on a terminal/console without any GUI. Progress will be autosaved once every 15 minutes. 

Will be available soon for you to test run it in debian.

**Comment by mokun** [comment]
@shirishag75 , may be you can try out [jenv](https://github.com/gcuisinier/jenv) for switching between JDK 
 versions. The author said it works in debian.

**Comment by mokun** [comment]
@shirishag75 , I've just published the headless version of mars-sim. It's only ~17 MB and doesn't require installing openjfx. See https://github.com/mars-sim/mars-sim/releases
