### ISSUE TITLE
Reduce CPU utilization

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#662]
**Describe the Improvement**
- Hunt down any method calls that utilize excessive resources
- Optimize CPU utilization

**Expected and unexpected behavior**
- Lower the % CPU utilization of the JVM task that hosts mars-sim on local machine 
 
**Java classes and methods involved**
- determineConstructionParts() in `MaufactureConstructionMaterials`
- excessive calling of getAmountResourceRemainingCapacity() in `EquipmentInventory`
- getAllConstructionStageInfoList() in `ConstructionUtil`

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/183576247-1a7db67a-e903-4bf8-94fe-3f50dda2030f.png)

![image](https://user-images.githubusercontent.com/1168584/183577452-187d9a7a-c921-4271-8589-72b735aaeda5.png)

![image](https://user-images.githubusercontent.com/1168584/183578546-c1a82b56-cdbe-4541-9a94-c2c44dbcdd23.png)

![image](https://user-images.githubusercontent.com/1168584/183578813-9ed7f146-3392-43b9-9804-c71f8d5acca2.png)

**Specifications**
 - pre-3.4.0 build 7118

**Comment by bevans2000** [comment]
I think we can close this now? A lot of changes have been done to reduce the load
