### ISSUE TITLE
Incorrect vehicle status and missing events such as exploring site after sunrise 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#667]
**Describe the bug**
- Vehicle status is not being updated correctly
- Sequence of events in log is not updated correctly 

**Expected and unexpected behavior**
- Vehicle status should be set to `Parked` when the speed at zero.
- It should print `Exploring Site` again in the schedule/log right after 'EVA - Not enough sunlight' after the sun comes up to make it clear that they do have the opportunity to explore the site. It was just that it has a delay.

**Java classes involved**
- `VehicleStatus`, `EVAMission`

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/184779970-0c258444-3d50-4f0b-acfc-b58764d852b1.png)

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7144

**Comment by bevans2000** [comment]
Vehicle status is a bug. Should be easy to fix.

Mission status I'm not sure this is a problem. Once the "EVA - Not enough sunlight" occurs; the current explore site is aborted; the next phase will be "Travelling". But this can only occur once everyone has returned to the Rover. In the screenshot I guess the 2 Persons are returning to the Rover and hence they are still using the "Exploring Site" task.

**Comment by bevans2000** [comment]
Yes being stuck in an Airlock would recreate that situation.
