### ISSUE TITLE
No oxygen and out of fuel in the vehicle when embarking

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#670]
**Describe the bug**
- Vehicle occupants cannot breathe
- Rover runs out of fuel prematurely

**Expected and unexpected behavior**
- During embarking, resources are still being loaded, occupants inside a rover should be in EVA suit 
- Adequate oxygen and fuel should be loaded before departure

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/185536962-d85c49f3-9130-4f81-9d49-7d94310ad34d.png)

**Stacktrace**
```
00-Adir-03:159.573 (Severe) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Sua You - Oxygen sensor triggered.   Actual: 0.0 kg  Required: 1.0E-4 kg
00-Adir-03:159.573 (Info) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Sua You - Suffered from Suffocation
00-Adir-03:159.573 (Severe) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Sua You - Reported lack of oxygen.
00-Adir-03:159.573 (Severe) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Haun In - Oxygen sensor triggered.   Actual: 0.0 kg  Required: 1.0E-4 kg
00-Adir-03:159.573 (Info) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Haun In - Suffered from Suffocation
00-Adir-03:159.573 (Severe) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Haun In - Reported lack of oxygen.
00-Adir-03:159.797 (Severe) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Haeun Chai - Oxygen sensor triggered.   Actual: 0.0 kg  Required: 1.0E-4 kg
00-Adir-03:159.797 (Info) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Haeun Chai - Suffered from Suffocation
00-Adir-03:159.797 (Severe) PhysicalCondition : [40.0000 N 100.0000 W - Kia] Haeun Chai - Reported lack of oxygen.
...
00-Adir-03:162.715 (Info) HealthProblem : [40.0000 N 100.0000 W - Kia] Sua You -  was suffocated for too long and was dead.
00-Adir-03:162.715 (Warning) DeathInfo : Sua You passed away in Kia
00-Adir-03:162.715 (Info) ScientificStudy : [Schiaparelli Point] Naima Saini - Remove dead invitee Sua You.
00-Adir-03:162.715 (Info) HealthProblem : [40.0000 N 100.0000 W - Kia] Haun In -  was suffocated for too long and was dead.
00-Adir-03:162.715 (Warning) DeathInfo : Haun In passed away in Kia
00-Adir-03:162.816 (Info) ScientificStudy : [40.0000 N 100.0000 W - Kia] Sua You - Areology #8 was canceled/abandoned due to FEMALE death.
00-Adir-03:162.916 (Severe) TabPanelCrew : PersonTableModel cannot be added.
```

**Specifications**
 - pre-3.4.0 build 7156

**Additional context**

@bevans2000, In the past, when a mission vehicle is being prep for the mission, it woud automatically hook up to the settlement (either in a garage or outside the buildings) to allow the automatic transfer of methane and oxygen and possibly water. However, the rest of the resources or items would need to be hand carried by settlers into the vehicle. Is it still true or not ?

**Comment by bevans2000** [comment]
Yes it should still be in place but this is what I mentioned last week. Something has been changed because this happens very often. 
Also in the screenshot, how can the vehicle be Out of Fuel before it enters the 'Travelling' phase ? Was this Mission still Embarking? I think that the loading is being aborted and Vehicles are setting off too soon before everything has been loaded.

**Comment by bevans2000** [comment]
I'm going to look into this at the weekend.

**Comment by bevans2000** [comment]
The problem is recent change to ```VehcileMission.computeTotalDistance```. It returns zero when the Vehicle is at the initial Settlement and hence nothing is loaded. 
I'll sort it. We can also optimise the logic by sorting the leg distance on the ```NavPoint``` instance when we created it; hence removing the need to recalculate it every time.

**Comment by mokun** [comment]
> It returns zero when the Vehicle is at the initial Settlement and hence nothing is loaded.

oic

**Comment by mokun** [comment]
> The problem is recent change to `VehcileMission.computeTotalDistance`.

There are 3 methods 
1. `computeTotalDistanceRemaining` 
2. `computeTotalDistanceTravelled`
3. `computeTotalDistanceProposed`

I tried to minimize having to run these 3 methods excessively.
Therefore, we have 3 corresponding *get* methods that return values and do not need to recompute values : 
1. `getTotalDistanceRemaining` 
2. `getTotalDistanceTravelled`
3. `getTotalDistanceProposed`

**Comment by bevans2000** [comment]
I've sorted the initial problem and doing some tests. Still have the problem of People consuming more Food that the predicted consumption. Missions run out of food in the middle now. Can we change it back so they consume food according to the defined rate?

**Comment by mokun** [comment]
> Can we change it back so they consume food according to the defined rate?

Have you tried commenting out the effect leptin and Ghretin in EatDrink to see if mission still runs out of food ?

**Comment by mokun** [comment]
I'm thinking of tracking how much food a settler eats per sol in reality to see if it matches up the recommended amount.

**Comment by bevans2000** [comment]
> > Can we change it back so they consume food according to the defined rate?
> 
> Have you tried commenting out the effect leptin and Ghretin in EatDrink to see if mission still runs out of food ?

No I haven't but I will give it a try
