### ISSUE TITLE
Use SimLogger to track non-Unit type actors

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#671]
**Is your feature request related to a problem? Please describe.**
- Simlogger cannot track how many times the same log statement has been generated for non-Unit type actors 

**Describe the solution you desire to see**
- Modify `baseLog()` in Simlogger to generate a unique string id for all non-Unit type actors

```
	/**
	 * Does the actual logging to the logger.
	 * 
	 * @param location
	 * @param actor
	 * @param level
	 * @param timeBetweenLogs
	 * @param message
	 * @param t
	 */
	private void baseLog(Unit location, Loggable actor, Level level, long timeBetweenLogs, String message,
			Throwable t) {
		if (!rootLogger.isLoggable(level)) {
			return;
		}

		long dTime = timeBetweenLogs;

		String uniqueIdentifier = getUniqueIdentifer(actor);
		TimeAndCount lastTimeAndCount = lastLogged.get(uniqueIdentifier);
		StringBuilder outputMessage = null;
		if (lastTimeAndCount != null) {
			synchronized (lastTimeAndCount) {
				long now = System.currentTimeMillis();
				if (now - lastTimeAndCount.startTime < dTime) {
					// Increment count only since the message in the same and is within the time prescribed
					lastTimeAndCount.count++;
					return;
				}

				// Print the log statement with counts
				outputMessage = new StringBuilder(sourceName);
				outputMessage.append(OPEN_BRACKET).append(lastTimeAndCount.count).append(CLOSED_BRACKET);
			}
		}
		else {
			// First time for this message
			outputMessage = new StringBuilder(sourceName);
		}

		// Add body, contents Settlement, Unit nickname message"
		outputMessage.append(COLON);
		if (actor == null) {
			// Actor unknown
			outputMessage.append("System").append(CLOSED_BRACKET_SPACE);
		}
		else if (actor instanceof Settlement) {
			// Actor in bracket; it's top level
			outputMessage.append(actor.getName()).append(CLOSED_BRACKET_SPACE);
		}
		else if (actor instanceof ConstructionSite) {
			outputMessage.append(actor.getName()).append(CLOSED_BRACKET_SPACE);
		}
		else { // In case of a person or robot or building
			// Need container hierarchy in brackets
			if (location == null) {
				outputMessage.append(LocationFormat.getLocationDescription(actor));
			}
			else {
				outputMessage.append(LocationFormat.getLocationDescription(actor, location));
			}
			outputMessage.append(CLOSED_BRACKET_SPACE).append(actor.getName()).append(DASH);
		}

		outputMessage.append(message);

		if (t == null) {
			rootLogger.log(level, outputMessage.toString());
		}
		else {
			rootLogger.log(level, outputMessage.toString(), t);
		}

		// Register the message
		lastLogged.put(uniqueIdentifier, new TimeAndCount());
	}
```

**Describe the rationale**
- Sometimes non-Unit type actors such as a type of `Crop`, a type of `Power Source` need to generate a log . Also Simulation, SimulationConfig and other utility-type class generate a lot of the same statement within a period of time. Having an unique string id assigned to them will be needed to put the maps such as `loggers` and 'lastLogged' to work for them.

```
	private static Map<String, SimLogger> loggers = new HashMap<>();
	private static Map<String, TimeAndCount> lastLogged = new ConcurrentHashMap<>();
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7170
 
**Additional context**
- Remove the use of the word "Unknown" or "System" for non-Unit type actors

**Comment by bevans2000** [comment]
I think the better approach is to make the things you want to log to implement the ```Loggable``` interface. Basically they need a name and parent Unit that is their container. The actor in SimLogger does not have to be a Unit. 
For example ```Crop``` & ```Power Source``` do have a parent Building. This is a better approach.

**Comment by bevans2000** [comment]
Hmm, just noticed that a ```getVehicle``` method has been added to the Loggable interface which is wrong. The presence of a Vehicle has nothing to do with the logging so this need removing first. Logging is all about the container hierarchy.

**Comment by mokun** [comment]
> `getVehicle` method has been added to the Loggable interface which is wrong.

Sure. getVehicle has just been removed. 

As a side note, if the unit is a settlement or mars surface or other future units that is higher than a settlement, then getAssociatedSettlement doesn't make much sense but currently it already has some class depends on it. Is there a way to make it more logical ?

Currently, Unit, Malfunctionable and Worker are the 3 classes that uses Loggable.

I'll go ahead and implement Loggable in Crop as well.

**Comment by bevans2000** [comment]
Good, I can't think of any reason for the associated Settlement method.

**Comment by bevans2000** [comment]
Looking good now. Much cleaner and we can expand to other entities.

Shall we close this now
