### ISSUE TITLE
Should DigLocalMeta check for any available airlocks in every frame ?

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#678]
**Is your feature request related to a problem?**
- A lot of settlers are turned away when they arrive at the airlock. Most are owing to not fulfilling the fitness requirement.
- We need to facilitate EVA ingress and egress. Currently, the airlock reservation system does not work well. 

**Case Study**
- A case in point is that in computing the probability of `DigLocal`, we have the following

```
   /**
     * Computes the probability of doing this task.
     * 
     * @param settlement
     * @param person
     * @param collectionProbability
     * @return
     */
    protected double getProbability(Settlement settlement, Person person, double collectionProbability) {

    	// Will not perform this task if he has a mission
    	if ((person.getMission() != null) || !person.isInSettlement()) {
    		return 0;
    	}

        double result = 0D;

    	// Check if an airlock is available
        if (EVAOperation.getWalkableAvailableAirlock(person, false) == null)
    		return 0;

        //Checked for radiation events
    	boolean[] exposed = settlement.getExposed();

		if (exposed[2]) {
			// SEP can give lethal dose of radiation
            return 0;
		}

        // Checks if the person is physically fit for heavy EVA tasks
		if (!EVAOperation.isEVAFit(person))
			return 0;

        // Check at least one EVA suit at settlement.
        int numSuits = settlement.findNumContainersOfType(EquipmentType.EVA_SUIT);
        if (numSuits == 0) {
            return 0;
        }
	
        // Check if at least one empty bag at settlement.
        int numEmptyBags = settlement.findNumContainersOfType(containerType);
        if (numEmptyBags == 0) {
            return 0;
        }
```

**Describe the rationale**
- We need to assess how we should allow a settler to use an airlock. 
- How would a [schedule](https://github.com/mars-sim/mars-sim/issues/637) be helpful and how to implement it ? 

In the past, we use `getWalkableAvailableAirlock()` to check if any airlock is available. However, it is no longer useful because we now ask a person to reserve an airlock prior to using it.

Since there's a total of 4 chambers in an airlock, the max # of reservation is also 4. 

Those who have the reservation will get to use it.

The question is, what method or class is responsible for making an airlock reservation ? 

Who make the call ? The settlement or the person ? 

How would it impact what DigLocalMeta will need to check ? 

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7261

**Comment by bevans2000** [comment]
Airlocks are getting more complicated as we try to fix problems. Reserving a chamber before a Person gets there just feels wrong. You can't reserve a slot until you are stood infront of the Airlock.
Re fitness; only the Operator needs to be fit. The others could just "struggle" in and get the Operator to drive the airlock. Also I think the cycle time is too long.

**Comment by mokun** [comment]
> Reserving a chamber before a Person gets there just feels wrong. You can't reserve a slot until you are stood infront of the Airlock.

Yes. I've already commented out the need for reservation for the time being until we sort things out.

> Re fitness; only the Operator needs to be fit. The others could just "struggle" in and get the Operator to drive the airlock. 

Hmm. so do you mean the operator needs to be more fit because he's supposedly responsible for everyone's safety ? I haven't thought about that till now.

> Also I think the cycle time is too long.

hmm. For now, the time it takes is just an arbitrary number. 

If we add in a few more physiology parameters, we could have a crude model of how long a person needs to be breathing a pure form of oxygen without nitrogen.

Also, I've read that living in a low pressure environment in settlement and in vehicle would help purging the nitrogen out of our blood QUICKER, thus requiring SHORTER *pre-breathing* and quicker adaptation to being confined in EVA suit and working and exploring outside on the surface of Mars.

**Comment by mokun** [comment]
Related to https://github.com/mars-sim/mars-sim/commit/edf8920da2eb02bd1f895b60411ece820a37451e
