### ISSUE TITLE
Remove requirement for sunlight for certain missions

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#679]
**Is your feature request related to a problem? Please describe.**
- There have been too many tasks that cannot be started or completed due to low or no sunlight

**Describe the solution you desire to see**
- Allow artificial lights. Bring outdoor lamps to illuminate mission sites
- Or we may simply suspend or relax the sunlight requirement in certain missions to see in those tasks or mission can be completed without other issues, thereby isolating the sunlight issue from other problem

**Describe the rationale**
- Settlers should not have expected plenty of sunlight when living on Mars. 
- It may be true that some outdoor tasks should be curtailed when there's insufficient amount of sunlight.
- However, within the settlement vicinity, digging local regolith or ice should NOT be stopped simply because there is no sunlight. 

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7261
 
**Additional context**
- Use of area lighting should be highly considered in the vicinity of the settlement.

**Comment by bevans2000** [comment]
Nice changes this should help our situation.
We could assume that certain Vehicle has a floodlight capability to illuminate the local site vicinity.

**Comment by mokun** [comment]
> certain Vehicle has a floodlight capability to illuminate the local site vicinity.

oh that's true as well. It will drain the battery or need fuel cell to provide this power capability to illuminate the site.

So we'll need to create floodlight as an `Item Resource` and put together its supply chain to produce it.

**Comment by bevans2000** [comment]
Yes that sounds good to add  an Item

**Comment by bevans2000** [comment]
I am going to use this opportunity to improve the ```EVAOperation``` class and simplify the interaction with the subclasses.
It will use the ```ExperienceImpact``` introduced in #1285

**Comment by mokun** [comment]
We could put "flood light"  to work. Will need to create logics to bring the flood light and cables on every missions and supply power for the flood light to turn on.

**Comment by bevans2000** [comment]
Yes that could work. I'm slightly changing how EVAOperations work so it's a bit cleaner.

**Comment by bevans2000** [comment]
@mokun I've been busy today working on UnitTest. Generally the project has a massive shortfall of UnitTests which is wasting time trying to diagnose problems in the simulation. 
As part of this change how all EVA based Task are started in changed. So I have build a framework to test any EVA Task now. I've done it for the EVA Vehicle maintenance and it's found  few edge cases that would cause bug. Have a look at this commit and the new UnitTests.

[e2e3051](https://github.com/mars-sim/mars-sim/pull/1299/commits/e2e30516c7449768262a65b134ce05632ace202f)

**Comment by mokun** [comment]
Sure 😃. It doesn't make sense to curtail the mission when the sun is down. The use of flood light to illuminate the area to continue the mission makes a lot of sense.
