### ISSUE TITLE
Resource Processing toggling cannot respond to the need of the settlement. Same in Manufacturing

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#682]
**Describe the bug**
- Currently, after regolith is excavated, the resource processing doesn't respond to the need of the settlement by processing them into sand and other resource right away. 
- The same is true for water ice. Although a lot of ice is dug up, it heaps up and doesn't nothing and no process is triggered to melt them into water.

**Expected and unexpected behavior**
- The settlement should sense the lack of regolith or water ice and prompt the settlers to fulfill its needs. This is done by giving a high probability score for excavating regolith and ice via `DigLocalMeta`. 
- However, in order to fulfill the need of the whole supply chain, the settlement would need to trigger other actions, such as asking settlers to toggle on certain resource processes, such as *"melt and filter ice"* or *"convert regolith to ores with sand"*, etc. to process raw in-situ resources obtained from Mars.

**Discuss any potential problems you have and have not ruled out**
- `getResourcesValueDiff()` in `ToggleResourceProcess` does not seem to compute the resource score correctly when comparing the demand on each resource process and selecting the correct process to work on.

**Java classes involved**
- The task `ToggleResourceProcess` has a few methods for handling resource processes. 
- `ToggleResourceProcessMeta` would pick one process to toggle, namely, to turn it ON or OFF. 

**Specifications**
 - pre-3.4.0 build 7280

**Comment by mokun** [comment]
@bevans2000 

For now, `ToggleResourceProcessMeta` only select one resource process, out of dozens of processes out there to toggle on and off. Also, most of the time, this particular process has low probability score and don't get picked among other meta tasks.

e.g. ERV-A 1 has processes A1, A2, A3, A4. ERV-B 1 has processes B1, B2, B3. Lander Hab 1 has A1, and B1.

When choosing a process to toggle, the algorithm would compute a resource score for each resource. 

The score should be the sum VPs of all the output resources divided by the sum VPs of all the input resources.

The process having the highest resource score would be selected.

However, this algorithm has vulnerability. 

e.g. The process A1 will always be the winner in every case, simply because the amount [in kg/sol] of one of its output resource is the highest, thus leading to a very high score for this particular process.

When its VP drops, then there's a chance that another process would be picked but it's not guarantee.

In our case when regolith is excavated, the VP of regolith will actually drop, thus there is even less chance that "convert regolith to ores with sand" will be picked to toggle it on.

**Comment by mokun** [comment]
See https://github.com/mars-sim/mars-sim/commit/6dd980692b6694f09d541ee6fa6a3652c4df6b62

**Comment by mokun** [comment]
@bevans2000 

I'm going to implement the effort level that will favor the resource process to take place. 

It dawns on me that we may use a comboxbox to allow player to change/select the overall effort level for all resource processes.

If it works well,  we may allow player to select the level for each building or each resource process type.

The effort level will be like a bonus in increasing output resource score. 

If player select the highest effort level (say 10), the output resource score become higher.

As a result, the resource process will have a higher chance of getting executed.

**Comment by mokun** [comment]
Will also implement effort level for manufacturing

**Comment by bevans2000** [comment]
What about #624 ? You are making the same changes twice?

**Comment by bevans2000** [comment]
Relates to #1236

**Comment by mokun** [comment]
The "Sabatier RWGS Reactor" process can finally be turned on after this [commit](https://github.com/mars-sim/mars-sim/commit/c96462919ec5cf91491f2cc046c3295aa7ba29ad). 

Before that the ambient input CO2 resource caused this process to be ignored.

Closing it now.
