### ISSUE TITLE
Possible Bug with Settlements

### ISSUE THREAD

**Issue by AloysiousTasch** [mars-sim/mars-sim#685]
Hello again,

I believe I am experiencing a bug involving the settlements in the latest 3.4.0 6975 version. Every time I try to locate a settlement, it takes me to Europa, but the settlers aren't from ESA and the actual name of the base is New Seoul. It is also not allowing me to switch settlements. 

Also, I am new to this so I apologize for any errors and unnecessary information. I am just going to follow the steps provided in the "bug report" template.

Steps:
1. When I load into the game, I use the "search" tool to find a settlement/settler.
2. Whenever I press on a colonist or settlement and click on "find", it automatically takes me to "Europa" of ESA
3. If I click on a settler, they appear to have a name of Korean origin
4. If a settler is doing a task, the sim says they are doing it at New Seoul, not Europa.
5. If I try to switch to another settlement, nothing happens.

I would expect to be taken to the correct settlement and have a proper syncing of bases and colonists.

I would add screenshots, but I am still having trouble. I will if I have time, but earlier I did all of my homework and I am thoroughly exhausted from the day.

For the stacktrace, will do the same as I did with the screenshots: (Import this if I have time). 

**Stacktrace**
Cut and paste the stacktrace or the log statement from your terminal/command prompt.

Specs:
 - Windows 10
 - openjdk 11.0.16
 - 3.4.0 (Build 6975)

Also, I'm just curious: What is the logo of the MSP download files? Personally, I think it looks like a penguin.

Thanks,
Aloysious Tasch

**Comment by mokun** [comment]
> Every time I try to locate a settlement, it takes me to Europa, but the settlers aren't from ESA and the actual name of the base is New Seoul. It is also not allowing me to switch settlements.

So you start mars-sim using default setting to create numerous settlements, right ? 

Yes. It was a bug with the Monitor Tool that stop player from choosing a different settlement other than the first one on the list.

**Comment by mokun** [comment]
> not allowing me to switch settlements.

btw, this has been fixed. Probably at https://github.com/mars-sim/mars-sim/commit/f33809421f65999b1b28aed7480b7999c312554f and other subsequent commits.

**Comment by AloysiousTasch** [comment]
Thank you!

I would love to test the newest build, especially with my new knowledge of downloading files.

**Comment by bevans2000** [comment]
Is there still a problem?

**Comment by bevans2000** [comment]
@mokun Can we close this?

**Comment by mokun** [comment]
Sure. @bevans2000 , is there a bug you'd like to fix before I compile the binary and upload a newer build for @AloysiousTasch to play test it ?

**Comment by bevans2000** [comment]
I know if no outstanding bug for this Issue so gl ahead and make a build and close this
