### ISSUE TITLE
eclipse prefs files inside /.settings

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#69]
@larsnaesbye and @shirishag75 , can you help deleting all of those nasty eclipse prefs files (e.g. org.eclipse.core.resources.prefs, etc.) inside the /.settings/ directory in each submodule ?

I'm sorry that it's very irritating to have them fetched from upstream in the past and they also affect me everytime and move to another computer and setup a development environment from scratch. 

The fact is that they are already in our codebase and often time they mess up with setting up the Build Path in eclipse IDE. 

I'm not that proficient with git command. But I know there are ways to do a SUPER QUICK `git rm --cached -r .settings` or something similar to delete all of them in one fell scoop.

see https://stackoverflow.com/questions/24583288/how-to-ignore-ide-settings-on-git and 
https://stackoverflow.com/questions/35114228/egit-set-gitignore-to-ignore-all-eclipse-project-files

I can't delete them inside eclipse and then do a commit to remove them from the codebase since without them my eclipse IDE won't work in the first place.

If I did it in GitHub webpage, i can only delete one file at a time. 

I've tried to delete the `.project` and `.classpath` one by one previously and set up the .gitignore and so forth in the last 30 commits. Tired of doing it manually.

Took forever to do something simple :(

**Comment by larsnaesbye** [comment]
Shouldn't we add a .gitignore file in every submodule, then?

**Comment by mokun** [comment]
Yes I've just have the entry `/.settings/` inside each .gitignore to prevent future upload. 

But it's already after the fact that we uploaded those prefs files into our repo. That's why we need to remove those files from our codebase. 

When I set up eclipse IDE in another machine and clone our repo, those prefs files will STILL be fetched from upstream as long as they still exist.

**Comment by mokun** [comment]
I just did it the old fashion way. it's done.

**Comment by shirishag75** [comment]
so if I do a clean git clone I would get it clean, is that what I/we are supposed to see ?

**Comment by mokun** [comment]
Yes we just got rid of these config files. 

Since they contain unique settings on how each eclipse IDE is configured, they have nothing to do with mars-sim and shouldn't be there in the first place. 

It was just that when we do a commit, it's very easy to include them since we didn't have them stated in .gitignore in the past.

But if you don't use eclipse, it really doesn't matter.
