### ISSUE TITLE
No normal task available for a person. Why is newCache empty ?

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#699]
**Describe the bug**
- A person has no normal tasks available, even after calling rebuildTaskCache() in PersonTaskManager

**Expected and unexpected behavior**
- The taskCache map should NOT be empty, regardless the work shift type

**Discuss any potential problems you have and have not ruled out**
- Unknown

**Java classes involved**
- `PersonTaskManager`
- `TaskManager`
- `TaskCache`

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/192074524-6858a921-15f9-4047-bce2-aa1d6542d5fc.png)

![image](https://user-images.githubusercontent.com/1168584/192074731-2644e0f4-e55b-4e29-9437-18aa024a54d8.png)

Vivaan's schedule always look normal, except that she's actually stuck inside airlock chamber. She shouldn't be doing other tasks there.
![image](https://user-images.githubusercontent.com/1168584/192074578-74775e72-6e91-42bc-8ef9-a852f6dd833e.png)

Vivaan has NOT been able to eat or sleep much in Sol 1. Now is at the beginning of Sol2.
![image](https://user-images.githubusercontent.com/1168584/192074775-c05ae300-57d6-4274-bfa9-addabf189a30.png)

**Stacktrace**
The log statement keeps showing up
```
00-Adir-01:919.769 (Warning) PersonTaskManager [x170] : [22.0000 N 82.9000 W] Vivaan Chandra - No normal task available. Get default tasks.
```

Why would if (newCache.getTasks().isEmpty()) become true below in `PersonTaskManager` ?

```
		// Create new taskProbCache
		TaskCache newCache = new TaskCache();

		// Determine probabilities.
		for (MetaTask mt : mtList) {
			double probability = mt.getProbability(person);
			if ((probability > 0D) && (!Double.isNaN(probability)) && (!Double.isInfinite(probability))) {
				if (probability > MAX_TASK_PROBABILITY) {
					if (!mt.getName().toLowerCase().contains("sleep")) {
						logger.log(person, Level.WARNING, 10_000,
							mt.getName() + "'s probability is at all time high ("
							+ Math.round(probability) + ").");
					}
					probability = MAX_TASK_PROBABILITY;
				}

				newCache.put(mt, probability);
			}
		}

		// Check if the map cache is empty
		if (newCache.getTasks().isEmpty()) {
			newCache = getDefaultTasks();
			logger.warning(person, 30_000L, "No normal task available. Get default tasks.");
		}
...
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7370

**Additional context**

**Comment by mokun** [comment]
@bevans2000 ,

Why would newCache be empty ?

**Comment by bevans2000** [comment]
This happened before but would have resulted in the daydreaming Task. It means for that perskn the task probabilities are all zero so the fixed default task set gets used.
I don't think this is an issue it's that now it is handled differently.

**Comment by bevans2000** [comment]
I think the problem is she is stuck in the airlock where she won't be able to do anything. The appropriate Eva task should not have ended with her in the airlock.

**Comment by bevans2000** [comment]
After a Pull I'm getting the same problem. Something has changed because People are outside for no purpose, i.e. the are looking for a new Task before they return to the Settlement. That is why they cannot find anything to do.
It looks like a different change has made them go outside.

**Comment by bevans2000** [comment]
Right so a task is failing when the Person is outside which leaves them stranded which is an error situation. This means we will have to send them back inside which will be done if the correct Task is selected. This should be fixable but we are solving the symptom and not the root cause.
