### ISSUE TITLE
have mars-sim -noaudio and mars-sim -backend -alsa as options 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#7]
This is in reference with https://github.com/mars-sim/mars-sim/issues/6 . 

Two options came straight to mind , such as -

```
$ mars-sim -noaudio 
$ mars-sim -alsa 
```

There could be many more options that could be put if we are able to get mars-sim to use CLI instead of straight jumping into the game.

**Comment by mokun** [comment]
> $ mars-sim -noaudio 

That's a wonderful idea for turning off the need of checking for sound before starting the game ! Will work on it. 

> $ mars-sim -alsa 

Question : how often do linux machines use ALSA ? 

I haven't used ubuntu enough or other linux distro to tell if most linux use ALSA or not. 

btw, currently, we are not just using the default Java sound API. Beginning version 3.1.0, we've replaced all wav sound clips with ogg format and started using an ogg decoder called  [jorbis](see http://www.jcraft.com/jorbis/)

You can see the following maven dependency in the pom.xml under mars-sim-ui/

> 		<dependency>
> 			<groupId>org.jcraft</groupId>
> 			<artifactId>jorbis</artifactId>
> 			<version>0.0.17</version>
> 		</dependency>

So I'll need to look up on more on ALSA to see if jorbis is able to work with ALSA.

**Comment by mokun** [comment]
The thread right [here](http://www.java-gaming.org/index.php/topic,24686.0) is discussing JavaSound API and OSS and ALSA.

**Comment by shirishag75** [comment]
That is a $1000 question ;)

Frankly speaking, pulseaudio works when it works, when it doesn't, it's a rude beast to troubleshoot. 

My machine used to play well with pulseaudio and then one day it just stopped. IIUC Pulseaudio by default is a daemon and if something goes wrong, it just restarts itself. This is good when it's working. When you are attempting to trouble-shoot it can become a headache. All the different sinks etc. is enough make a simple 2 speaker person go kaput. 

I tried various troubleshooting examples from https://wiki.archlinux.org/index.php/PulseAudio which is my go-to wiki in terms of community documentation. They do it well. I think I even went to the freedesktop people to share my issue but nothing came out of it. 

I then chose ALSA and I'm a happy camper ever-since.

**Comment by mokun** [comment]
I'm looking into switching to this java-vorbis-support package here at https://github.com/Trilarion/java-vorbis-support

> Combination and continuation of JOrbis, JavaSPI and Tritonus-Share to provide Ogg/Vorbis playback capabilities for Java using the Sound SPI.

It combines 3 packages into one. 

I'm hoping that this package would provide a way for me to seize back the sound control from linux to mars-sim's sound panel. 

In issue https://github.com/mars-sim/mars-sim/issues/1 , I fixed the sound problem temporarily in linux by just disabling the mars-sim's sound control since the result of the `boolean hasMasterGain` in linux is always `FALSE` for some strange reason. 


> If you take a look, you will see I made some changes in OGGSoundClip's setGain(), added disableSound() in MainScene and added and made use of a new boolean field hasMasterGain in AudioPlayer, etc.

**Comment by larsnaesbye** [comment]
Wouldn't it be more logical to specify things with -audio followed by a value?
```
mars-sim -audio none
mars-sim -audio alsa
mars-sim -audio pulseaudio
```

**Comment by shirishag75** [comment]
that actually would be nice as it would be more like a switch then anything else.

**Comment by mokun** [comment]
Just added the "noaudio" option when starting a new sim or loading a saved sim in r4256

To start a new sim with background music and sound effect disabled, type the following :  
> java -jar 4256.jar new noaudio
(the use of the argument "new" may be omitted)

To load a saved sim with background music and sound effect disabled, type the following :  
> java -jar 4256.jar load noaudio

Note: it will take more time to dig in to understand how alsa vs. pulseaudio work in various linux distro. For the time being, if a linux distro doesn't have the proper sound driver installed, mars-sim would not be able to control its Master Gain in AudioPlayer and the audio would be automatically be disabled.

Let me know if you run into any issues.

**Comment by mokun** [comment]
I'haven't tested this in linux distro because it will take more time to know it works in alsa and pulseaudio for linux

At least, in windows and macOS, this "no audio" option work. 

Let me know if you run into issues with the audio.

**Comment by mokun** [comment]
We've added the new "noaudio" switch.

Closing this issue for now. Will explore how alsa and pulseaudio work in linux in future.
