### ISSUE TITLE
Incorrect values until after reviewing the mission is complete

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#700]
**Describe the bug**
- The Monitor Tool's `"All Citizens" Tab does not show that a few settlers are members of a mission
- `Mission` became an interface recently. Since then, `AbstractMission` became the class that houses the mutable data members.
- fullMissionDesignation is NOT calculated until createFullDesignation() in called.
- Certain methods such as getFullMissionDesignation() in Mission cannot return correct value unless the mission review is completed and mission has been approved. 

**Expected and unexpected behavior**
- Calling mission.getFullMissionDesignation() in PersonTableModel should return the proper value
- Gabriel's Unit Window `Activity` tab does show him as the member of **Regolith Prospecting 1** in the Mission Description textfield

**Discuss any potential problems you have and have not ruled out**
- Nothing else

**Java classes involved**
- Mission
- AbstractMission
- PersonTableModel

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/192078685-8952498d-35d3-410e-9ee6-2de5f8e595c2.png)

![image](https://user-images.githubusercontent.com/1168584/192078444-6ef8817c-3891-4e29-a442-7129b05f7b3f.png)
![image](https://user-images.githubusercontent.com/1168584/192078494-9a650604-dda9-43e1-a10b-e26425abd980.png)
![image](https://user-images.githubusercontent.com/1168584/192078616-e2e8fff7-8aa6-444d-94f9-30afa8ec2072.png)

**Stacktrace**

`PersonTableModel::getValueAt` has the following :
 
```
			case MISSION_COL: {
				mission = person.getMind().getMission();
				if (mission != null) {
					result = mission.getFullMissionDesignation();
				}
			}
				break;
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7371

**Additional context**
- A similar issue arise in https://github.com/mars-sim/mars-sim/commit/523c7ae4a09d01fdf4f3c29b22f6bcee592dcb65 in that one must call computeTotalDistanceProposed() in VehicleMission so as to calculate distanceProposed. Thus the error came when `ReviewMissionPlan` won't be able to rely on the value of distanceProposed after the review has been completed and mission is approved.

**Comment by bevans2000** [comment]
This behaviour was the same in the old implementation. The Designation was not create until a Mission started. If you want to change the logic then it's easy; just say how you want it to work.

**Comment by bevans2000** [comment]
So what the problem here? I think the designation shouldn't be created until the Mission is approved; at that point the Missikn truly starts.

Also can be avoud changing the headlines of the Issues as new problems are found that are not related to the original problem? It leads to long comment histories in issues that are not always relevant to the original problem. Good practice is too create a bug and fix it and close it. If that uncovers a different problem then we create a new issue.

**Comment by mokun** [comment]
> Also can be avoud changing the headlines of the Issues as new problems are found that are not related to the original problem? 

Agree.

My intention of editing the title is for quickly locating what have been discussed. I'll minimize that.

> It leads to long comment histories in issues that are not always relevant to the original problem. Good practice is too create a bug and fix it and close it. 

Sure.

> If that uncovers a different problem then we create a new issue.

Yes. We've been doing that more or less. 

Since one issue can easily to another one, we may briefly mention a newly discovered issue in conjunction with the old issue on an existing thread. But it takes more time and documentation to open a new thread, you know. 

But yes it's a good thing to separate concerns.

**Comment by bevans2000** [comment]
I think there is no bug here. The Designation should only be set once a Mission has been approved. Happy to close this ?

**Comment by mokun** [comment]
Ok. There may be a better way to say in Monitor Tool that this person is being a member of a mission under review.
