### ISSUE TITLE
Simplify the Vehicle Mission interface

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#702]
The ```VehicleMission``` interface has too many methods relating to NavPoints and is a confusing interaction. Simplify the interaction model to allow a better transition to the new implementation.

**Comment by mokun** [comment]
> `VehicleMission` interface has too many methods relating to NavPoints and is a confusing interaction.

Sure. We could further reduce the methods into a few respective categories and split them into a few interfaces if you want.

**Comment by bevans2000** [comment]
By first stab just moved all the externally called methods to the interface. Going to look at how the NavPoints are used externally.
