### ISSUE TITLE
Unable to go back to settlement to eat

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#703]
**Describe the bug**
- A settler doesn't know where to get food to reduce hunger

**To Reproduce (Please provide steps)**
1. Suppose a settler is inside a vehicle but there's no food there
2. Say, this vehicle has either not departed yet or has just got back from a mission and just arrived at the settlement 
3. The settler is extreme hungry and have very low performance
4. The settler would get stuck inside the vehicle, not knowing he could go back to the settlement to eat

**Expected and unexpected behavior**
-  The `EatDrinkMeta` should be able to include logics to allow the `EatDrink` to be picked and walk back to the settlement to eat

**Java classes involved**
- `EatDrinkMeta`
- `EatDrink`

**Solutions**
- Add logics in `EatDrinkMeta` and `EatDrink` to accommodate the situation where the settler is inside a vehicle and the vehicle's container is settlement.
- The person should leave the vehicle and step back into the settlement to eat
- No settlers should not depart for a mission unless hunger is below 200 or so to avoid consuming food stored in the vehicle
- In future, create an architecture in `Mind` to automatically hunt for source of food. It should be one of those **innate ability** for a person to survive and should not be Meta task driven. 

**Screenshots**
They are sitting duck.
![image](https://user-images.githubusercontent.com/1168584/192157113-c257871a-7c8a-4b25-af8f-e3b9e5b0a44b.png)

The timestamp for the return should have been captured there at the red box in Monitor Tool right at the start of the disembarking process.
![image](https://user-images.githubusercontent.com/1168584/192157216-eb6f576f-6f38-4f5c-aae6-d5d903c22083.png)

They can't leave the vehicle and are busy with other tasks because EatDrink task never get selected
![image](https://user-images.githubusercontent.com/1168584/192157294-9c6ac0eb-9400-45c7-bd13-24b5e55924bb.png)

They haven't been able to eat when the vehicle ran out of food during the mission
![image](https://user-images.githubusercontent.com/1168584/192157508-5164a934-6d81-455d-8088-1de5ae4f4fe0.png)

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7395

**Additional context**
- **Not enough food.** log statements are found in this simulation. See this [thread](https://github.com/mars-sim/mars-sim/issues/664#issuecomment-1257125213) for separate discussion.

**Comment by mokun** [comment]
@bevans2000 

Shall we create logics in `Mind` to automatically hunt for food without going through meta task selection ? 

Just like a bot that will be forced to be recharged automatically when it's low power ?

**Comment by bevans2000** [comment]
Yes we can do the same pattern as bot mind BUT note it still uses the MetaTask. The point is it doesn't call the probability score, but just creates directly. Whilst this doesn't sound important it us because it cleans up the starting of a new Task.
Do you want me to make the change ?

**Comment by mokun** [comment]
> I will update the `PersonTaskManager` to automatically trigger at eat Task when they are very hungry.

Sure. I added the logics in EatDrink and EatDrinkMeta to walk back and it seems to work. But it's still a very convoluted way and is prone to error. Next time when we add new features to EatDrink I'll need to remember...

Better you added something in `PersonTaskManager` to make it happen.

Can you also do it for `Sleep` for settlers ?

**Comment by bevans2000** [comment]
Sure but I've realised that we need to be careful with forcing a Person to eat/sleep. If they get forced to Eat when inside for example; if they can not complete the Eat Task then next time they will still be hungry and the process will get repeated.
I think influencing the Task Cache on the Person's state is correct because at the moment it's just a random change.

**Comment by mokun** [comment]
> Sure but I've realised that we need to be careful with forcing a Person to eat/sleep.

Yes. I've been cautious in trying to lay out what logics should be involved if a person is both very tired and very hunger at the same time and what is most sensible for him to do...

**Comment by mokun** [comment]
As a matter of fact, I've actually seen a person alternately between the two tasks back-to-back every couple millisols over a long period of time, which doesn't make sense. 

But I haven't done anything consciously too much to address that yet.

**Comment by mokun** [comment]
In reality, a person would go through sometimes a cycle of feeling hungry as well as a cycle of feeling tired because of the hormonal cycles are involved.

May be there's a better way to model these physiological effect in future, instead of trying so hard to hand craft each response in EatDrink and Sleep.

**Comment by mokun** [comment]
@bevans2000 

We have a lot of people having the following log right now repetitively :
```
01-Adir-02:537.651 (Warning) PersonTaskManager : [MuskVille] Shirley Young - Need health tasks
```

Shirley has zero fatigue but a bit hungry
![image](https://user-images.githubusercontent.com/1168584/192428822-5aef6988-0831-439d-8068-211bbf182e26.png)

Shirley's doing fine but keep sleeping
![image](https://user-images.githubusercontent.com/1168584/192428990-f34711a2-1df0-4298-8e2d-a157f4980abf.png)

**Comment by bevans2000** [comment]
So its driven by the is hungry method. I suspect this is the case I discussed where She can  not find anything to eat so it keeps coming back to the task cache. Probably we should raise the threshold to only trigger the health Task when a person is starving not just hungry.

**Comment by bevans2000** [comment]
One problem we do have is the value returned by the get probability method is not balanced. One task can return a massive value which dominates the cache and means the result for the eat Task can get ignored. Ideally we need to standardise the return values so the are balanced and have a maximum value ensuring all Tasks get a fair chance. Then a hungry person would gradually increase their chance of eating.
The probability score becomes more like a priority, say with a range of 0..10 where 0 means no need and 10 is a must. This would mean a change to how scores are calculated but make it more even and more stable.

**Comment by bevans2000** [comment]
OK, so the problem relates with this repeated messages is actually a problem in the ```EatDrink``` Task. A hungry/thirsty Person is forced to task the EatDrink task due to the new logic, rightly so.
But the EatDrink Task is ending before any change is done. The method `PhysicalCondition.drinkEnoughWater` is always returning true even when the Person is very thirsty. Hence the logic get stuck in a loop with the Person trying to replish themselves but the Task is failing them. I think it has something to do with the recent changes to record how much is eat and drunk.
However I've taken out the change to pre-empt the need for the EatDrink Task until the EatDrink task is working correctly.

**Comment by mokun** [comment]
All `PhysicalCondition::drinkEnoughWater` does is about checking against the max daily limit, not the current state of how thirsty a person is. It's needed because it helps limiting EatDrink from being run excessively.

Now I can think of a scenario in which `PhysicalCondition::drinkEnoughWater` doesn't serve its purpose well. 

It was when a person drank a lot of water at the **beginning** of a sol and, say, he even exceeded the max H2O_CONSUMPTION * 1.5.

let's say, throughout the course of the sol, he did a lot of outdoor tasks and exercise and get very thirsty. 

Before the end of the sol, he will be of course very very thirst. 

However, he won't be able to drink water because `PhysicalCondition::drinkEnoughWater` would return true.

So I'll add another condition here to see if he's thirsty 

```
	/**
	 * Has this person drank the amount of water that exceed the max daily limits ? 
	 * 
	 * @return
	 */
	public boolean drinkEnoughWater() {
		Double w = consumption.getDataPoint(3);
		if (w != null) {
			if (w.doubleValue() >= H2O_CONSUMPTION * 1.5
					&& thirst < THIRST_CEILING_UPON_DRINKING)
				return true;
		}

		return false;
	}
```

Committing the change now.

**Comment by bevans2000** [comment]
Yes if the condition is thirsty then the Person must be allowed to drink no matter how much they have consumed. Can the same happen for food?

**Comment by mokun** [comment]
I just removed the erroneous calling of endTask() just after completing one frame of the task phase in either eating or drinking. Things are working now.

**Comment by mokun** [comment]
@bevans2000 

Do you still see any anomaly ?

If not, we'll close this now.

**Comment by bevans2000** [comment]
No, let's close it
