### ISSUE TITLE
Set the first Martian year to 01

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#704]
**Is your feature request related to a problem? Please describe.**
- The first resupply missions was launched prior to the planetfall of the first settlement.
- If the first Martian year is `00`, then the launch date shown in **Resupply Tool** would logically become the year of `-1`. A negative year is not a common expression. In Western Calendar, we normally use BC and AD to denote this relationship. 

**Describe the rationale**
- Currently, when the simulation starts, the initial timestamp is `00-Adir-01:000` in the format of `Year-Month-Sol:Millisols`. 
- It means it's the year `00`, the month of `Adir` (the first month of the year), the sol of `01` and at the millisols of `000`. 
 
**Describe the solution you desire to see**
- Simply advance one year ahead
- This way, set the first Martian orbit as `01` - the year the simulation starts
- At a result, any resupply missions being sent last year would have a timestamp of orbit `00` 
- Note: the weakness is that the launch year of a resupply mission being sent two years ago would still be `-1`.

**Version**
 - pre-3.4.0 build 7401

**Comment by bevans2000** [comment]
The initial mars data should be derived from the Earth Start Date. This will ensure that Earth & Mars date remain synchronized.
https://www-mars.lmd.jussieu.fr/mars/time/martian_time.html

**Comment by mokun** [comment]
> The initial mars data should be derived from the Earth Start Date.

Yes. Ideally speaking, we want that sol 0 of orbit 0 (or sol 1 of orbit 1) to begin at the very day of the human landing on Mars.

However, in case of mars-sim, we conveniently define orbit 1 month 1 and sol 1 to start on the day when Ls (areocentric latitude of Mars) to be sufficiently close to zero (thus Ls = 0).

**Comment by bevans2000** [comment]
But if we derive the real Mars time from the earth time it would be more realistic

**Comment by mokun** [comment]
> But if we derive the real Mars time from the earth time it would be more realistic

what does it mean ?

**Comment by mokun** [comment]
This was done in v3.4.0.
