### ISSUE TITLE
Repair a malfunction vehicle

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#709]
**Describe the bug**
- Currently, repairing a malfunction vehicle is not modeled in detail

**Expected and unexpected behavior**
- Need to define what needs to be repaired on a vehicle
- Need to define the circumstances where repair is warranted 
- Create appropriate tasks and meta tasks 

**Discuss any potential problems you have and have not ruled out**
- `RepairEVAMalfunction` and `RepairInsideMalfunction` used to be utilized for finding vehicle malfunctions. However, many details are undefined and logics are confusing.

For instance, the method below in `MalfunctionFactory` attempt to gather all the malfunctions, namely, building malfunctions, vehicle malfunctions and equipment malfunctions, based on the location of a person.

```
	/**
	 * Gets a collection of malfunctionable entities local to the given person.
	 *
	 * @return collection collection of malfunctionables.
	 */
	public static Collection<Malfunctionable> getLocalMalfunctionables(Worker source) {

		Collection<Malfunctionable> entities = new ArrayList<>();

		if (source.isInSettlement()) {
			entities = getBuildingMalfunctionables(source.getSettlement());
		}

		if (source.isInVehicle()) {
			entities.addAll(getMalfunctionables((Malfunctionable) source.getVehicle()));
		}

		Collection<? extends Unit> inventoryUnits = null;

		if (source instanceof EquipmentOwner) {
			inventoryUnits = ((EquipmentOwner)source).getEquipmentSet();

			if (inventoryUnits != null && !inventoryUnits.isEmpty()) {
				for (Unit unit : inventoryUnits) {
					if ((unit instanceof Malfunctionable) && !entities.contains((Malfunctionable) unit)) {
						entities.add((Malfunctionable) unit);
					}
				}
			}
		}

		return entities;
	}
```

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7437 
 
**Additional context**
 - Create `RepairMissionVehicle` if it involves external repair on the outside of a vehicle. However, the vehicle is still out there on a mission. Thus it requires performing EVA to do the job 
 - Create `RepairInsideVehicle` if it involves only internal repair and can be undertaken by a person within the vehicle without EVA
 - Create `RepairGarageVehicle` if it involves external repair on the outside of a vehicle and the vehicle can be parked inside a garage and without EVA

**Comment by bevans2000** [comment]
I think it might have been resolved in #740
