### ISSUE TITLE
debian build not running because wrong file endings

### ISSUE THREAD

**Issue by akademy** [mars-sim/mars-sim#72]
The debian build installed but it does not run because the file
/usr/bin/mars-sim
is saved with DOS end-of-line types

Resaving the file with unix endings fixes this problem. 

(The hashbang needs to have unix line endings or it will not run.)

**Comment by mokun** [comment]
Hi akademy, appreciate much for pointing that out. Do you want to do a pull on both the v3.1.0-b1 and master branch ?

**Comment by akademy** [comment]
Can do. I'll clone and put a pull request in.

**Comment by akademy** [comment]
I looked at the file in the repository (this one: mars-sim/mars-sim-main/src/deb/mars-sim ) and the line endings appear correct. 

My guess is the problem is caused when the debian package is built. Do you have build scripts I can see? (It's also possible the git setting "core.autocrlf" is causing a change at some point)

**Comment by mokun** [comment]
no build script need to create the file mars-sim/mars-sim-main/src/deb/mars-sim 

The whole deb package is put together using a maven plug-in.

It may have to do with me running Eclipse IDE in Windows. 

Sometimes I used Notepad++ in windows. I might have edited the `mars-sim`  with window EOL...

It looks like when I package the `MarsProject_3.1.0-b1_java9_batch.7z`, I cut and paste a different mars-sim file to the root folder when I should have used the good one at mars-sim/mars-sim-main/src/deb/mars-sim 

But this shouldn't affect the deb package `MarsProject_3.1.0-b1_java9_deb.deb`....?

**Comment by mokun** [comment]
Also, help me if the following syntax is good :  

```
#!/bin/bash
if [[ $(java -version 2>&1) == *"OpenJDK"* ]]; then echo 'You are using OpenJDK'; else echo 'You are not using OpenJDK'; fi

#!/bin/sh
java -Xms256m -Xmx1024m -Djava.util.logging.config.file=logging.properties -cp /usr/share/mars-sim-main/* org.mars_sim.main.javafx.MarsProjectFX -new
```

should I stick with bash shell or sh ?

**Comment by akademy** [comment]
Of the four files:
./mars-sim-headless/src/main/resources/mars-sim
./mars-sim-headless/src/deb/mars-sim
./mars-sim-main/src/main/resources/mars-sim
./mars-sim-main/src/deb/mars-sim

only 
./mars-sim-headless/src/main/resources/mars-sim
has the wrong lone endings.

**Comment by akademy** [comment]
You should remove one of the hashbangs as only a hash bang on the very first line is interpreted.

I'd usually use `#!/bin/sh` if possible, however, the substring search users a "bashism" so I'd put in
`#!/usr/bin/env bash`

The rest of the text is fine, although for completeness you may want to also check for java first.

So something like:
`
#!/usr/bin/env bash
echo "Launching Mars Sim..."
if command -v java >/dev/null 2>&1;
then
	echo >&2 "Java found"
else
	echo >&2 "You don't have Java. Aborting"
	exit 1
fi

if [[ $(java -version 2>&1) == *"OpenJDK"* ]]; 
then 
	echo 'You are using OpenJDK'
else 
	echo 'You are not using OpenJDK'
fi

java -Xms256m -Xmx1024m -Djava.util.logging.config.file=logging.properties -cp /usr/share/mars-sim-main/* org.mars_sim.main.javafx.MarsProjectFX -new
`

**Comment by mokun** [comment]
Appreciate much @akademy ! 

The path of looking for the MarsProjectHeadless class was also bad but fixed now.

**Comment by mokun** [comment]
For anyone who have trouble starting the Mars Simulation Project in linux/macOS, please download the following updated  `mars-sim` and replace the one that came with the package you downloaded : 

A. For GUI Edition
1. Batch version : 
at https://github.com/mars-sim/mars-sim/blob/master/mars-sim-main/src/main/resources/mars-sim

2. Debian version: 
The other one for the batch edition is at https://github.com/mars-sim/mars-sim/blob/master/mars-sim-main/src/deb/mars-sim

B. For Headless Edition
1. Batch version: 
at https://github.com/mars-sim/mars-sim/blob/master/mars-sim-headless/src/main/resources/mars-sim

2. Debian version: 
The other one for the batch edition is at https://github.com/mars-sim/mars-sim/blob/master/mars-sim-headless/src/deb/mars-sim

**Comment by mokun** [comment]
Closing this thread now.
