### ISSUE TITLE
Capitalisation of static values

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#723]
**Describe the question**
Throughout the code we run the Capitialize method many times to convert fixed entity names into a user representation. Each time we run this a new String is created. Entities such as Enum and items loaded from the XML files, Goods & Food names. 

**Expected and unexpected behavior**
Why down we just define the names in the correct case at the source and remove the need for the wasteful Capitalise method.

**Comment by mokun** [comment]
Do you mean you want to make all the Amount Resource (and Parts and Equipment, etc.) name to begin with upper case letters ?

**Comment by mokun** [comment]
Shouldn't we simply be making it more defensive ? 

If someone mix both upper case and lower case letter in a resource name, we would still be able to match it correct since we call .toLowerCase() before comparison. Will that be sufficient ?

**Comment by bevans2000** [comment]
For lookups, yes we always do via ```equalsIgnoreCase``` totally agree.
But if the name attribute is aimed for human reading; then we should create those names in the correct format at source. Running the same method 1000s of times in the simulation that always returns exactly the same predictable result isn't right. Sure it's not consuming a massive amount of CPU but it has a high call frequency.
I found this out doing the works for #719 when reworking the ```MonitorWindow```. Many of the model classes continuously capitalise the same string in the rendering. I was going to remove it from the model and create a dedicated ```TableCellRenderer``` but realized that is just moving the problem.

**Comment by bevans2000** [comment]
OMG, I thought I had done enough changes to just change the names  in the XML files to get the tables and panel to show human usable names. However I've opened a can of worms.
The lookups and logic in ```ItemResourceUtil``` and ```AmiuntResourceUtil``` is a bit of a house of cards. There is a mixture of ```toLowerCase``` calls within the entities and the config class that pushes everything to lower case. But there are ineffeciencies and unused methods.
The changes have a positive impact in it removes some unneeded maps objects and methods.
The change is much bigger than I wanted so am going to test it on a branch.
