### ISSUE TITLE
Inconsistent Icons in the UI

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#728]
**Describe the bug**
The Swing UI has inconsistent icons. The same concept is shown with a different icons in different window. These should be consolidated into a single set of consistent icons, Some examples:

- Settlement Icon in the Person window is used as the Building icon in the Monitor Tool
- Science Tool icon is different from the Science icon in the Person window
- Mission tab & Mission button in the Monitor Window do not match the Mission Tool
- Location tab in the Unit Window is different from the Location button in the Monitor Window

**Comment by mokun** [comment]
Sure. I'll fix them.

**Comment by bevans2000** [comment]
Looking better

**Comment by bevans2000** [comment]
Liking the new icons. Some icons that are inconsistent

- Robot icon in the Monitor tool and the Settlement Unit Window (I like the latter one with open arms)
- Citizens in the Monitor tool and the Settlement Unit window
- Occupants panel in Building Unit window is different from the Citizens, I think it should be the same
- Crew  panel in Vehicle Unit window is different from the Citizens, I think it should be the same
- Missions in the settlement Unit window is different from the Monitor Tool & the toolbar (these are consistent and look good)
