### ISSUE TITLE
Create resource_processes.xml

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#729]
**Is your feature request related to a problem? Please describe.**
- Currently, when a building has a function of handling a certain `Resource Process`, it needs to spell out the amount of each input and output resource explicitly each time.
- e.g. if Lander Hab has process A and ERV-A also has process A, then the content of process A has to be defined twice in `buildings.xml`. 

**Describe the solution you desire to see**
- Create `resource_process.xml` to define a gold *standard* on the amount of input resources required and the amount of output resources produced for each resource process.
- Vary the `number-modules` attribute to increase/decrease the capability of doing that resource process in a building
- Vary the `power-required` attribute accordingly

**Describe the rationale**
- This saves boilerplates and maintains consistency 

**XML codes**
```
<resource-processing power-down-level="0.0">
			
	<process name="Sabatier RWGS Reactor" number-modules="4" power-required=".47" default="on">
		<!-- the amount of input and output (per module) -->
		<input resource="carbon dioxide" rate="39.6" ambient="true" />
		<input resource="hydrogen" rate="3.6" ambient="false" />
		<output resource="methane" rate="4.8" ambient="false" />
		<output resource="carbon monoxide" rate="16.8" ambient="false" />
		<output resource="water" rate="21.6" ambient="false" />
	</process>
```

**Version**
 - pre-3.4.0 build 7525

**Additional context**
- May add new attributes such as `efficiency` and `degradation` in future to ***customize*** or individualize how well each resource process is performed in a building

**Comment by bevans2000** [comment]
This has some link to #624

**Comment by bevans2000** [comment]
@mokun I have created a new Project to cover everything about Processes. We have 4 implementation of essentially the same concept. Have a single way to define the processes will be a starting point.

**Comment by mokun** [comment]
> We have 4 implementation of essentially the same concept.

Yes but I don't know at what level we can integrate all 4 together.

But we could certainly divide them up into TWO types of processes here

1. manufacturing and food production are currently more of an on-demand process. Once it's triggered, it starts to accumulate work time and process time. When done, it produces an output resource.

2. On the other hand, resource and waste processing are continuous. Once it's turned on, it uses input resources and produce output resource on each frame.

**Comment by bevans2000** [comment]
I think it is possible to combine all 4. Certainly in terms of configuration entities but I'll start with Resource & Waste processing.

Explain what the ambient and waste classification to the inputs/outputs represents?

**Comment by mokun** [comment]
btw, currently, we don't have settlers toggling on and off waste processes. It can be done together under one meta task. We will need to fix this before releasing 3.4.0

**Comment by bevans2000** [comment]
Why is the toggling not automatic? Seems a waste of time for Settlers to be doing the same thing

**Comment by mokun** [comment]
> Why is the toggling not automatic? 

I suppose for now it's by design it's not fully automatic.

One justification is that since it requires CPU of a machine to gauge if a resource process is indeed needed by the settlement by computing and comparing the resource scores.

So it may as well be registered as a meta task that a settler needs to do to pick which resource process is needed.

**Comment by mokun** [comment]
> Seems a waste of time for Settlers to be doing the same thing

Of course, we are talking about two sides: 
1. which one to *toggle on* 
2. which one to *toggle off*

So it seems determining which one to *toggle on* can be more time consuming.

But if the process can't be proceeded because one of the input resources is lacking, then it has to be *toggled off* no matter what.

**Comment by mokun** [comment]
For now, in BuildingWindow's `Waste Processing` tab, we can see the following: 
![image](https://user-images.githubusercontent.com/1168584/197608700-a0a2bd48-de4f-482a-8e8b-ce620b131659.png)

**Comment by mokun** [comment]
What it shows in those screenshots is that players can still manually toggle on and off each process in a building.

**Comment by mokun** [comment]
> I'm not going to touch the current logic, just consolidate the config and move it XML files for now.

Ok. I'll wait for at least this brand new xml to be made before releasing 3.4.0.

**Comment by bevans2000** [comment]
I think combining all 4 'Process definitions' into a single one would work but the Waste & Resource process would become quite generic. 
But it is definitely possible to combine Waste & Resource.

**Comment by bevans2000** [comment]
It seems there is no difference in terms of the logic between Resource and Waste processing. Just that they represent difference concepts.

**Comment by mokun** [comment]
For now there's no difference. To me, waste processing is supposed to be a 24x7 operation since the input resources are NOT wanted. 

They shouldn't need to be manually turned on and off. However, for small settlements, there aren't that much wastes yet.

On the other hand, resource processing should be done as needed only since it can be challenging to find balance. 

e.g. water -> hydrogen + oxygen

The input resource of one process can be very limited such as water.

But one may need to split water in order to get hydrogen, which is needed to create methane, and to get oxygen, which is needed for breathing.

Sometimes I need more oxygen, but sometimes I need more water.
