### ISSUE TITLE
Missing jar, when added manually JNI error

### ISSUE THREAD

**Issue by Paculino** [mars-sim/mars-sim#73]
**Describe the bug/issue**
Error: A JNI error has occurred, please check your installation and try again.
A Java Exception has occurred.

**Affected Area**
System/Java Virtual Machine Launcher
On a freshly installed/updated mars sim.

**Expected behaviors**
I expected the mars sim to open.

**Actual/Observed Behaviors**
Errors prevent use.
Error: A JNI error has occurred, please check your installation and try again.
A Java Exception has occurred.

**Reproduction (optional)**
 - Steps to reproduce the problem

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
e.g. Include the followings :
 a. Person Window showing various activity tabs 
 b. Settlement/Vehicle Window 
 c. Monitor Tool's showing People/Vehicle/Mission tabs  
 d. Settlement Map, etc.

**Specifications  (please complete the following information):**
 - OS version : Microsoft Windows [Version 10.0.17134.165]
 - Java version : 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
 - mars-sim build version : 3.1.0-b1 (using the main download, and also putting in the download of the jar file because it was missing/not found by terminal in the main download)

**Additional context**
Fresh installation because last one was installed incorrectly, although apparently better than this time. Perhaps I should have continued using 3.06

**Comment by mokun** [comment]
Hi @Paculino , thanks much for filing this ticket.

> mars-sim build version : 3.1.0-b1 (using the main download, and also putting in the download of 
> the jar file because it was missing/not found by terminal in the main download)

Have you downloaded `MarsProject_3.1.0-b1_java9_jar.7z` ?

is it possible for you to install Oracle Java 10 on your machine ?

> java version "1.8.0_161"
I didn't compile 3.1.0-b1 under Java 8 and thus it's not intended to run under Java 8. Sorry I didn't make it clear.

If it's too hard, do let me know.

**Comment by Paculino** [comment]
Thank you, it works now. Sorry for making such a dumb mistake.

**Comment by mokun** [comment]
Thanks for filing the ticket and feel free to provide more feedback!

It's true that many people are still using Java 8. 

If I can find an easy way in near future to configure Eclipse IDE to compile mars-sim under both Java 8 and Java 9 binaries at once, I'll post the binary that support Java 8 as well for people to download.
