### ISSUE TITLE
Consolidate the processing logic of Waste & Resource processing

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#739]
The ```WasteProcess``` class is an exact subset of the ```ResourceProcess``` class.
Also the level property of the ```ResoruceProcess``` has no impact on the processing since the production level is defined outside the process.

**Comment by bevans2000** [comment]
@mokun What is the level meant to do in the ResourceProcess class? It has  o effect at all because the production level is passed in when th process is executed. This is calculated from the amount t of power available.
I think the level should be removed because the ```ResourceProcessSpec``` defines the maximum rate of the process so allowing th user to exceed that is wrong.

**Comment by bevans2000** [comment]
@mokun Does the toggling work once the simulation get running? I'm 95% sure it is nothing I have changed because I've just moved and consolidated existing logic. The Settlement seems to maintain a cache that is not getting refreshed I think. 
I'm going to take a look on the branch.

**Comment by mokun** [comment]
> What is the level meant to do in the ResourceProcess class? It has o effect at all because the production level is passed in when th process is executed.

The level of effort is just a param for players to adjust.

Selecting a higher level means the process will have a stronger weight to proceed forward.

For now, the default level currently is 2.

In Settlement Unit Window's Resource Processing tab, player can choose a different level.

**Comment by mokun** [comment]
I just checked. It turns out there's *two* *different* kinds of ***level*** here.

The level of effort was recently added in and is supposed to be player adjustable. It has to do with the push the commander wants this process to proceed.
 
But the production level of a resource process has to do with the power mode (or the power available) and has been in use for a while.

In `ResourceProcessing`, we have

```
	/**
	 * Time passing for the building.
	 *
	 * @param accumulatedTime amount of time passing (in millisols)
	 * @throws BuildingException if error occurs.
	 */
	@Override
	public boolean timePassing(ClockPulse pulse) {
		boolean valid = isValid(pulse);
		if (valid) {

			double productionLevel = 0D;
			if (getBuilding().getPowerMode() == PowerMode.FULL_POWER)
				productionLevel = 1D;
			else if (getBuilding().getPowerMode() == PowerMode.POWER_DOWN)
				productionLevel = powerDownProcessingLevel;
			// Run each resource process.
			Iterator<ResourceProcess> i = resourceProcesses.iterator();
			while (i.hasNext()) {
				i.next().processResources(pulse, productionLevel, getBuilding().getSettlement());
			}
		}
		return valid;
	}
```

**Comment by mokun** [comment]
Now that there's a lot of "Attempting to toggle ...* msg somehow. I'll take a closer look as well to see why.

```
01-Adir-01:181.669 (Info) ToggleResourceProcess : [Zvezda] ERV-A 2 - Milana Dyomin: Attempting to toggle on 'Carbon Formation Reactor'.
01-Adir-01:182.366 (Info) MaintainBuilding : [New Seoul] RepairBot 006 - Maintaining Hallway 3.
01-Adir-01:182.366 (Info) ToggleResourceProcess : [Europa] Lander Hab 1 - Marie Lund: Attempting to toggle on 'Carbon Formation Reactor'.
01-Adir-01:182.366 (Info) ToggleResourceProcess : [New Plymouth] ERV-B 2 - Arthur Sanchez: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:183.715 (Warning) ResourceProcess : [New Pompeii] Case A. Used up all 'Carbon' input to start 'Produce Styrene'. Required: 0.26 kg. Remaining: 0.083 kg in storage.
01-Adir-01:185.520 (Info) AnalyzeMapData : [Tian Cheng] Jun Tang - Total computing needs: 0.968 CUs. score: 0.571. rand: 0.031. seed: 0.031. 7 candidate sites identified. Final site selected: (1.1046 S, 17.3741 E).
01-Adir-01:187.665 (Info) MaintainBuilding : [New Boston] RepairBot 010 - Maintaining Fish Farm 1.
01-Adir-01:188.108 (Info) ToggleResourceProcess : [Europa] ERV-B 1 - Sophia Steiner: Attempting to toggle on 'Produce Styrene'.
01-Adir-01:188.910 (Info) MaintainBuilding : [Europa] RepairBot 002 - Maintaining Laboratory 1.
01-Adir-01:189.281 (Info) ToggleResourceProcess : [Schiaparelli Point] ERV-B 1 - Emilia Rebane: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:189.632 (Warning) ResourceProcess : [Kyocera] Case A. Used up all 'Carbon' input to start 'Produce Styrene'. Required: 0.204 kg. Remaining: 0.086 kg in storage.
01-Adir-01:191.445 (Info) ToggleResourceProcess : [Kyocera] ERV-B 1 - Kaito Ogawa: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:191.701 (Info) PrepareDessert : [New Boston] Mia Jensen - Finished preparing Soymilk.
01-Adir-01:192.423 (Info) AnalyzeMapData : [Schiaparelli Point] Chiara Marino - Total computing needs: 1.188 CUs. score: 0.5. rand: 0.034. seed: 0.034. 7 candidate sites identified. Final site selected: (16.6834 N, 52.3760 W).
01-Adir-01:193.318 (Info) ToggleResourceProcess : [New Plymouth] ERV-B 2 - Bonnie Lewis: Attempting to toggle on 'Produce Polyethylene'.
01-Adir-01:193.530 (Info) ToggleResourceProcess : [Schiaparelli Point] ERV-B 3 - Leonardo DaVinci: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:195.102 (Info) MaintainBuilding : [Kyocera] RepairBot 005 - Maintaining Hallway 8.
01-Adir-01:195.102 (Info) ToggleResourceProcess : [New Pompeii] ERV-B 2 - Ryan Malhotra: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:195.102 (Info) ToggleResourceProcess : [New Boston] ERV-B 1 - Eliott Martin: Attempting to toggle on 'Produce Styrene'.
01-Adir-01:195.489 (Info) ToggleResourceProcess : [Tian Cheng] Lander Hab 1 - Xiaoqing Feng: Attempting to toggle on 'Carbon Formation Reactor'.
01-Adir-01:197.225 (Info) ToggleResourceProcess : [Schiaparelli Point] Atmospheric Processor 1 - Jeanne Bernard: Attempting to toggle on 'Plasma Pyrolysis Assembly (PPA) Reactor'.
01-Adir-01:198.579 (Info) ToggleResourceProcess : [Kyocera] ERV-B 2 - Kota Kobayashi: Attempting to toggle on 'Produce Polystyrene'.
```

**Comment by bevans2000** [comment]
Yes exactly. I will leave the level alone for now then . We can revisit it once I've finished these changes

**Comment by bevans2000** [comment]
I saw the same thing then after day 1 they seem to slow down and no one wants to toggle. I changed the Console command to make it more obvious when a toggle is needed.
Ok but be careful because I have a lot of changes pending in that area.

**Comment by bevans2000** [comment]
I have one more change to make to remove the use of ```SimpleEntry``` because that is a dangerous class to use outside Maps. We have no control over it. in fact , I was surprised in has a public constructor because it should be private to restrict use to the Map.

**Comment by mokun** [comment]
> I changed the Console command to make it more obvious when a toggle is needed.

If it's too hard to use console to see what process has been toggled on/off, you can use Monitor Tool's Building Tab to find 
![image](https://user-images.githubusercontent.com/1168584/198896067-76f0988f-6ca4-4560-8d01-03cb91de40ba.png)

**Comment by mokun** [comment]
In my stacktrace, I have
```
01-Adir-01:203.365 (Info) ToggleResourceProcess : [Europa] ERV-B 2 - Marie Lund: Attempting to toggle on 'Produce Styrene'.
```

If I open the Europa's ERV-B 2's Building Unit Window, it shows that the process `Produce Ethylene` is on. It has a green dot.

![image](https://user-images.githubusercontent.com/1168584/198896157-f784a2f9-1dda-4dce-9caf-25af81f8dac8.png)

**Comment by mokun** [comment]
Also, in Europa's Settlement Unit Window's Resource Processing tab, it shows the same thing in the ERV-B 2 building.

![image](https://user-images.githubusercontent.com/1168584/198896273-21ecb2fa-f409-403a-b91a-8f32f9d48701.png)

**Comment by mokun** [comment]
So either Marie Lund's attempt to toggle on 'Produce Styrene' is successful, or she's attempting to toggle on a process erroneously if it has already been toggled on.

**Comment by mokun** [comment]
I just looked inside ToggleResourceProcess class.

That log statement has to do with declaring its intention to attempt to toggle in the constructor.

But it's not until it's at the FINISHED phase when it truly said "Done manually toggled" on or off.

I'll change the logger.info statement printout by updating the ToggleResourceProcess to make it easy to use the find feature in eclipse to locate the building and the process of interest. 

Now it's very difficult to do since it inserted the name of the settler in-between the building name and the process name. For instance,

```
01-Adir-01:193.318 (Info) ToggleResourceProcess : [New Plymouth] ERV-B 2 - Bonnie Lewis: Attempting to toggle on 'Produce Polyethylene'.
01-Adir-01:193.530 (Info) ToggleResourceProcess : [Schiaparelli Point] ERV-B 3 - Leonardo DaVinci: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:195.102 (Info) MaintainBuilding : [Kyocera] RepairBot 005 - Maintaining Hallway 8.
01-Adir-01:195.102 (Info) ToggleResourceProcess : [New Pompeii] ERV-B 2 - Ryan Malhotra: Attempting to toggle on 'Produce Polystyrene'.
01-Adir-01:195.102 (Info) ToggleResourceProcess : [New Boston] ERV-B 1 - Eliott Martin: Attempting to toggle on 'Produce Styrene'.
01-Adir-01:195.489 (Info) ToggleResourceProcess : [Tian Cheng] Lander Hab 1 - Xiaoqing Feng: Attempting to toggle on 'Carbon Formation Reactor'.
```

**Comment by bevans2000** [comment]
> > I changed the Console command to make it more obvious when a toggle is needed.
> 
> If it's too hard to use console to see what process has been toggled on/off, you can use Monitor Tool's Building Tab to visualize it. 

I was hoping to push the change today but I've been ill so it will have to wait until later in the week

**Comment by mokun** [comment]
> I was hoping to push the change today but I've been ill so it will have to wait until later in the week

No problem. Take care and be rested !

**Comment by mokun** [comment]
>  remove the use of SimpleEntry because that is a dangerous class to use outside Maps.

So SimpleEntry is essentially a key value pair. But why is it dangerous ?

**Comment by bevans2000** [comment]
> > remove the use of SimpleEntry because that is a dangerous class to use outside Maps.
> 
> So SimpleEntry is essentially a key value pair. But why is it dangerous ?

Because ```SimpleEntry``` is an inner class that belongs to ```AbstractMap``` so it is an implementation class of the Map interface. There is no guarantee that it will not change because it is an private implementation. I'm going to replace it with an explicit new inner class.

**Comment by mokun** [comment]
> no guarantee that it will not change because it is an private implementation. I'm going to replace it with an explicit new inner class.

oic

**Comment by bevans2000** [comment]
I've done a replacement but I've got Covid at the moment so will have to wait until I push it.

**Comment by mokun** [comment]
> I've done a replacement but I've got Covid at the moment so will have to wait until I push it.

Sure. np.

**Comment by mokun** [comment]
We still have quite a lot of "... made an attempt to toggle it on" msgs 

When we see one, it should mean that it's at ToggleResourceProcess's constructor's already and a person will toggle on a process.

But for now, it seems that 90% of the time doesn't not result in toggling that process successfully, or else another msg will print, saying that it was well done. why ?


```
01-Adir-01:367.369 (Info) ToggleResourceProcess : [Starcity] Atmospheric Processor 2 - Carbon Formation Reactor : Craig Baker made an attempt to toggle it on.
01-Adir-01:367.955 (Info) AnalyzeMapData : [New Plymouth] Martha Wright - Total computing needs: 2.331 CUs. score: 1.333. rand: 0.084. seed: 0.084. 13 candidate sites identified. Final site selected: (4.0670 N, 20.3580 E).
01-Adir-01:367.955 (Info) ToggleResourceProcess : [Zvezda] Lander Hab 1 - Syngas Plant : Elizaveta Artyukhin made an attempt to toggle it on.
```

**Comment by bevans2000** [comment]
OK, I am seeing toggle happen but basically at the start of a Sim there are a lot of toggles pending. I made a change to spread these around more. I'll keep an eye open for them,

**Comment by bevans2000** [comment]
I think there could be a problem with the toggleAvailable method. I'm looking into it tonight.

**Comment by mokun** [comment]
Can it still detect if a process needs to be toggled on or off ?

In the past, it used to be able to do so.

We have two conditions :

1. Toggling on a process if all input resources are available and the score of this process is the highest.
2. Toggling off a process if any one of the input resources has run out.
 
Note that we could make condition 2 be done automatically without having to send a settler to manually or remotely toggle off this process.

**Comment by bevans2000** [comment]
I touched none of the internal logic but I will examine it next
