### ISSUE TITLE
openjdk 11 headless mode

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#74]
Dear all, 

I download the headless version and tested the integrity to see if the archive was good - 

```
~/games$ 7z t MarsProject_3.1.0-b1_java9_headless_batch.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_IN,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 17538572 bytes (17 MiB)

Testing archive: MarsProject_3.1.0-b1_java9_headless_batch.7z
--
Path = MarsProject_3.1.0-b1_java9_headless_batch.7z
Type = 7z
Physical Size = 17538572
Headers Size = 926
Method = LZMA2:24
Solid = +
Blocks = 1

Everything is Ok                                                            

Folders: 2
Files: 29
Size:       18381002
Compressed: 17538572
```

Then extracted the archive - 

```
~/games$ 7z x MarsProject_3.1.0-b1_java9_headless_batch.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_IN,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 17538572 bytes (17 MiB)

Extracting archive: MarsProject_3.1.0-b1_java9_headless_batch.7z
--
Path = MarsProject_3.1.0-b1_java9_headless_batch.7z
Type = 7z
Physical Size = 17538572
Headers Size = 926
Method = LZMA2:24
Solid = +
Blocks = 1

Everything is Ok                                                        

Folders: 2
Files: 29
Size:       18381002
Compressed: 17538572
```

Saw the extracted directory - 

```
:~/games/MarsProject_3.1.0-b1_java9_headless_batch$ ls
CHANGELOG_3.1.0-b1.md  CONTRIBUTING.md  LICENSE   mars-sim.bat        README.md
configuration.txt      jars             mars-sim  README_3.1.0-b1.md
```

I tried running the game with - 

```
~/games/MarsProject_3.1.0-b1_java9_headless_batch/jars$ java -jar mars-sim-headless-3.1.0-b1.jar 5 healess new
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx2048m -new
OUTPUT>2018-08-25T03:39:41.1 (Info) MarsProjectHeadless$SimulationTask : Starting Mars Simulation Project v3.1.0-b1 - Build 4421 - 64-bit 11 - 4 CPU threads
OUTPUT>2018-08-25T03:39:41.8 (Info) MasterClock : Based on # CPU cores/threads, the following parameters have been re-adjusted :
OUTPUT>2018-08-25T03:39:41.8 (Info) MasterClock : Time Ratio (TR) : 64x
OUTPUT>2018-08-25T03:39:41.8 (Info) MasterClock : Time between Updates (TBU) : 150.0 ms
OUTPUT>2018-08-25T03:39:41.8 (Info) MasterClock : Ticks Per Second (TPS) : 6.67 Hz
OUTPUT>2018-08-25T03:39:41.8 (Info) MasterClock : *** Welcome to Mars and the beginning of the new adventure for humankind ***
OUTPUT>2018-08-25T03:39:43.4 (Info) Weather : [Plymouth Base] On L_s = 0.2, Dust Devil-1 was first spotted near Plymouth Base.
OUTPUT>2018-08-25T03:39:43.5 (Warning) LivingAccommodations : [Alpha Base] Larry Ponda does not have a bed yet.
```

I don't see anything more than that. There isn't anyway to run any debug commands as well :(

**Comment by shirishag75** [comment]
So, in the headless mode AFAIU it's basically like a visual novel. 

I did see that eventually it did make a default.sim which it puts at `~/.mars-sim/saved`

**Comment by mokun** [comment]
Edit the mars-sim file and add `-8192x` to the line `org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx512m -headless -load default.sim`

**Comment by mokun** [comment]
Then type `./mars-sim` in linux to start the simulation

**Comment by mokun** [comment]
> OUTPUT>2018-08-25T20:06:12.7 (Severe) [x442] PhysicalCondition : [Dune Runner] Randy Jorden has insufficient oxygen.

Looks like Randy Jorden went out of oxygen inside the Rover `Dune Runner`. 

In future we'll have to put in more code to help users find out why there's no more O2. 

The most probable reason is that there is a malfunction to the vehicle and it leaks O2. 

Or it lingers too long in a location digging regolith and it ran out of O2 on its way coming back home.

This goes into designing the interface to let users participate more in the mission planning of a vehicle excursion.

**Comment by shirishag75** [comment]
stumped again - 

```
~/games/MarsProject_3.1.0-b1_java9_headless_batch$ ./mars-sim 
bash: ./mars-sim: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by mokun** [comment]
Hi @shirishag75 ,

Have you replaced the `mars-sim` file with the latest version at 

https://github.com/mars-sim/mars-sim/blob/master/mars-sim-headless/src/main/resources/mars-sim

and then edit it by adding `-8192x` ?

It was discovered that the `mars-sim` that came with the binary package had windows EOF ending. 

So I added `II. Download and Replace the mars-sim executable file` in https://github.com/mars-sim/mars-sim/releases and explained that need.

May also have to do a chmod to make it executable.

Note that the time-ratio switch such as `-8192x` currently works in the headless version of the binary only and and won't work on any GUI versions.

**Comment by shirishag75** [comment]
I did, I actually cloned the repo. and copied the mars-sim file over to the headless batch release. 

I did edit  mars-sim and chmod +x it  . 

```
~/games/MarsProject_3.1.0-b1_java9_headless_batch$ cat mars-sim | tail -1
java -Djava.util.logging.config.file=logging.properties -cp .::jars/ org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new -8192x
```

```
I did try to run it but couldn't  due to - 

~/games/MarsProject_3.1.0-b1_java9_headless_batch$ ./mars-sim 
Launching Mars Simulation Project...
Java found
You are using OpenJDK
Error: Could not find or load main class org.mars_sim.headless.MarsProjectHeadless
Caused by: java.lang.ClassNotFoundException: org.mars_sim.headless.MarsProjectHeadless
```

I have no idea why it couldn't  find the class mentioned in https://github.com/mars-sim/mars-sim/releases/download/v3.1.0-beta1/MarsProject_3.1.0-b1_java9_headless_batch.7z or rather ~/games/MarsProject_3.1.0-b1_java9_headless_batch$  directory.

**Comment by shirishag75** [comment]
the last  command worked, now need to find a way to interact with the simulation rather than just  seeing the output in non-gui mode.

**Comment by mokun** [comment]
Note that the time-ratio argument won't work in any GUI version of mars-sim. It works in the headless binary only.

**Comment by mokun** [comment]
> the last command worked, now need to find a way to interact with the simulation rather than just seeing the output in non-gui mode.

We may have to design a text-based menu interface to be able to interact with the simulation, unless we find a way to send commands to a Java app in real-time.

**Comment by shirishag75** [comment]
I'm ok with either way, although a text-based menu interface looks more appealing but probably more hard work.  Maybe what you could do is try a branch or two and we could test both ways to see which one works.  See https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches if you want to know how to create a git branch. Just holler when you think any changes need to be tested and will do the same. 

Once we are satisfied we can just merge the appropriate developmental branch with the master branch  see https://stackoverflow.com/questions/5601931/best-and-safest-way-to-merge-a-git-branch-into-master .

**Comment by mokun** [comment]
Yes we have already created branches. For now there are only two, namely, `3.1.0-b1` and `master` since we don't have that many developers. In future, we would avoid committing directly to master branch but now it's not an issue.

**Comment by mokun** [comment]
I'll have to look for a good framework that provides a text-based menu interface that runs on a terminal and doesn't use Java Swing.

**Comment by shirishag75** [comment]
hope you do a new release at https://github.com/mars-sim/mars-sim/releases soonish.

**Comment by mokun** [comment]
I've added a new project named "Interacting with mars-sim under Text-based Console" in https://github.com/mars-sim/mars-sim/projects

**Comment by shirishag75** [comment]
just saw it, nice. It's too bad we don't have a roadmap template like it is in some other places.

**Comment by shirishag75** [comment]
@mokun  where is the pre-release mate ?

**Comment by shirishag75** [comment]
just tried with the updates you did last night, now it seems to fail in the tests somewhere. 
[maven-tests-failed.txt](https://github.com/mars-sim/mars-sim/files/2407576/maven-tests-failed.txt)

**Comment by mokun** [comment]
The mars-sim-service submodule causes the maven test to fail. 

I don't think I'm able to fix the Spring Boot related problem at this point. 

Barry is the one who wrote the code in this submodule. 

Meanwhile, I'm very closed to putting together a new feature that has to do with submitting proposals to the commander of a settlement.

Once I'm done debugging the initial implementation, I'll commit it before releasing 3.1.0-b2.

Stay tune !

**Comment by mokun** [comment]
I'll simply comment out the mars-sim-service submodule when compiling the v3.1.0-b2. 

This way, the maven tests in this submodule won't be run and thus no errors will result !

**Comment by shirishag75** [comment]
The surefire-reports also need to be commented out as they are also generating errors while trying to compile.

**Comment by shirishag75** [comment]
With the latest commit e79324a6ce have been getting java.lang.NullPointerException in Tests -

[mvn-package.txt](https://github.com/mars-sim/mars-sim/files/2418037/mvn-package.txt)

**Comment by mokun** [comment]
@shirishag75 , I'm publishing the build 4447 headless edition for your review. See https://github.com/mars-sim/mars-sim/releases/tag/r4447

It was compiled to be Java 9 compatible using Oracle JDK 10.0.2. It's uncertain if it can be run under Java 11 or openjdk 11. Do let me know. Thanks !

It will make more work to set up openjdk 11 in eclipse. I've been trying to set up a separate eclipse build to make that happen for mars-sim but it's still work in progress.

**Comment by shirishag75** [comment]
@mokun  it works, see - 

![mars-sim-text-terminal](https://user-images.githubusercontent.com/727626/46131713-f601ef80-c259-11e8-9558-77cd40480b94.png)

although I did get this on the terminal, dunno if it's significant or not - 

```
$ java -jar r4447_headless.jar 
Command: java -Djava.util.logging.config.file=logging.properties -cp .:*:jars/* org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new
? >2018-09-27T13:31:03.0 (Info) MarsProjectHeadless$SimulationTask : Starting Mars Simulation Project v3.1.0-b2 - Build 4447 - 64-bit 11 - 4 CPU threads
? >SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
? >SLF4J: Defaulting to no-operation (NOP) logger implementation
? >SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by shirishag75** [comment]
was trying with the latest commit 07fe0d6e2 and still got the same issue  . 

Was using mvn package with mvn version 3.5.3 - 

```
$ mvn --version
Apache Maven 3.5.3
Maven home: /usr/share/maven
Java version: 11, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-1-amd64", arch: "amd64", family: "unix"
```

**Comment by mokun** [comment]
SLF4J is being used by at least 2 maven dependencies. 

It's not directly used by mar-sim.

In other words, SLF4J is a dependency of a dependency.

**Comment by mokun** [comment]
Closing this now.
