### ISSUE TITLE
TaskMeta.getProbability should return an object instead of a double

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#740]
**Is your feature request related to a problem? Please describe.**
Some of the Taskmeta classes calculate target entities as part of the getProbability method. These are the target of the appropriate Task. For example the RepairInsideTaskmeta selects a Malfunction and then pushes it into the Settlement object which is picked up in the RepairInsideTask constructor. Essentially this is caching within the Settlement. This can create problems with cached entities becoming out of date or stale.

**Describe the solution you desire to see**
A cleaner solution is for the elected Entity to be passed as the result of the probability calculation, a new class containing the probability score and an optional object. This would be saved in the TaskMap and then the object would be passed to the actual Task in the createInstance method.
This removes the need for a Task to recalculate the Entity to execute the Task on.  
The majority of the TaskMeta do not use a caching mechanism and will continue to work based on the probability score.

**Comment by bevans2000** [comment]
There will be a great side effect from this change. We will be able to support multiple entries in the cache for the same Task. So if a Settlement has multiple Malfunctions, a Person currently only has one repair Task in the cache. But it the new approach the Person can have an entry associated to each Malfunction with individual scores. The same pattern for multiple Greenhouses needing rendering and toggling processing. This will be a good change.
The MetaTasks can be slowly changed to create multiple Tasks.

**Comment by mokun** [comment]
Do you think we can also work toward creating a ***job board*** for each settlement ? 

This way, tasks from each division will be posted and will be distributed.

If no jobs are posted, then it falls back to the meta task approach to pick a task to run

**Comment by bevans2000** [comment]
Yes I think so. The job board is a pending job list for the Settlement instead of a Person.

**Comment by bevans2000** [comment]
@mokun I have  changed the ```TendGreenhouse``` logic so it now returns a task cache entry for every Farming entry that needs help; see the screenshot showing the output from the work Console command. Each is individually scored separately from the Settlement. I really like this approach and can see it being applicable for Malfunction repair, Resource Processing & Load/Unload Vehicles at least.

![Screenshot multiple tend crops](https://user-images.githubusercontent.com/20720166/200124961-ba86a38b-e236-456f-b71c-22c88f140089.png)

Have a look at the latest commit 44274b2dd6184a73273994c5ac598b818fa6c439
The pending Task logic needs a little change to bring it into line. After that I'll push it if you've happy with the approach. Then we can tackle converting other MetaTasks as part of a main activity.

**Comment by mokun** [comment]
Sounds cool! Can you push it ?

**Comment by mokun** [comment]
Btw, the other day I was thinking of how to make the best use of the Commander Window or Dashboard as the one-stop-shop to present info and centralize as many options over there for players to choose from.

**Comment by mokun** [comment]
So when we put together a job board, I suppose we will have to change again how to retrieve a malfunction or a building that needs maintenance, right?

**Comment by bevans2000** [comment]
> So when we put together a job board, I suppose we will have to change again how to retrieve a malfunction or a building that needs maintenance, right?

No I hope that the concept of ```TaskJob``` will give us the items that can go in the Job Board. Then the MetaTask classes that directly create lists of TaskJob can be called to populate the board. And of course we can create board items in any other way. We need a way to define which MetaTasks can contribute towards the board but that should be easy.

**Comment by bevans2000** [comment]
> Sounds cool! Can you push it ?

PR done.

I see the multiple job approach can be used for:

- Load/Unload Vehicle in both EVA & Inside - The vehicle is the target object
- Repair Task both EVA & Inside with the Malfunction the target or maybe the Malfunctionable
- Tend Fish, same pattern as TendCrop
- Toggle Resource; target would be the ResourceProcessor being toggled
- VehicleMaintenance - target object the Vehicle

All of the above would be sources for the your Job board concept so I feel this is a really good change that will open up opportunities.  I have introduce inconsistency in the modelling around ```constructInstance``` method but I know how to fix it in a latter commit.

**Comment by mokun** [comment]
@bevans2000 
That's great you incorporate these tasks into this approach one by one !

**Comment by bevans2000** [comment]
Yes slow and steady. It is simplifying a lot of logic.

**Comment by mokun** [comment]
I'm also thinking of standardizing time slots. 

If we define the small interval of time for each task for each time ratio, we would have simplified some significant amount of logics in `Mind` and `TaskManager` as well.  Do you think so ?

**Comment by bevans2000** [comment]
Maybe but my worry is this would decrease the accuracy of the simulation because steps would have to confirm to a fixed time unit. But having said that the double arithmetic is expensive

**Comment by bevans2000** [comment]
Can probably extend this to include the Maintenance tasks as well since they are focused on a particular Builiding.

**Comment by bevans2000** [comment]
@mokun Did you capture your idea of a Settlement Task board anywhere? The changed approach in this issue is going part of the way to support it. This would need to create a list of TaskJob based on the Settlement and then bind them to a Person by applying the various modifiers.
I just need to migrate

- TogglePowerSource
- UnloadVehicle
- Load vehicle

All the other Settlement based Meta Tasks have been converted.

**Comment by mokun** [comment]
> Did you capture your idea of a Settlement Task board anywhere?

It's actually @Urwumpe's idea. He posted it here at https://github.com/mars-sim/mars-sim/issues/141

> All the other Settlement based Meta Tasks have been converted.

That's awesome !

**Comment by bevans2000** [comment]
Due to the improvement to make maintenance period flexible in the ```MalfunctionManager``` vehicle maintenance is too frequent now because the old style MetaTasks are using a fixed period. This will be resolved in the next set of changes using the existing logic from MaintainBuilding.

**Comment by mokun** [comment]
> vehicle maintenance is too frequent now

What do you see as one or two next steps in improving the simulation of vehicle maintenance ?

**Comment by bevans2000** [comment]
This is quite easy. Vehicle maintenance is using an old approach of a fixed single score. It is not using the new MalfunctionManager getMaintenaceWindow method that allows different entities to have different maintenance schedules.
I will change the meta class to evaluate the vehicles individualy according to the window.

**Comment by bevans2000** [comment]
I have converted all the MetaTasks that can generate multiple jobs per call. 
There is one remaining tidy up operation that I'm going to do which will consolidate the repeated duplicate code for overcrowding.
