### ISSUE TITLE
Make flexible Shift Patterns

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#743]
**Describe the bug**
Shifts are not flexible but hard coded within the simulation. There are 2 shift patterns supported (A,B) & (X,Y,Z) where the start times are hard coded. The shift pattern for a Settlement is selected according to the number of settlers. 
The purpose of the Shift patterns is to have a main daily time shift but as Settlements round round the planet this concept breaks down.
Secondly, every person has a ```TaskSchedule``` which contains logic that is more suited to the Shift than the Person. This is further complicated by ```Settlement``` also having similar logic.

**Expected and unexpected behavior**
An alternative is to remove the hard-coded shift settings and add the concept of shift patterns to the settlement configuration. Shift patterns could be extended to include the concept of repeated "off Shift"/Rest days.
On Call would be a special shift automatically added.
The settlement templates would reference which Shift Pattern to use; this would also accommodate the time zone of the Settlements Locations, e.g. morning sunrise shift is still that on opposite sides of the planet.
To support this would be the creation of some new configuration classes but the big change would be the replacement of the individual ```TaskSchedule``` with a reference to a Settlement ```Shift``` instance used by everyone on the same shift. The Shift object would control when Persons change Shift; not the individual as is the case now. Probably a new ```ShiftManager``` object for the Settlement that also controls who has a day off.
There would be some impact on TaskManager choosing the potential TaskMeta instances.

**Comment by mokun** [comment]
I'd like to address the need to implement time zone on Marsnin connection with the changes in how work shift should work.

As I recall, the shift A in a settlement at longitude 0 will have a different start time than the shift A in a settlement, say, longitude 90. 

In this case, the time difference should be 250 millisols.

If we have time zone one day, we would do it differently.

**Comment by mokun** [comment]
Btw, it totally makes sense to include one rest day  for every 7 days.

Each person will be given a rest day randomly but they need to have a different rest day so as not to impact the operation.

Also, each should have a memory or a preference of what weekday he used to be the rest day and stay with that weekday unless it needs to be changed.

Another thing needs to be resolved is what happened when a person comes back from a, say , 10-day mission? 

Will his rest day be accumulative, just like in the real world ?

To follow down this rabbit hole, will a settler be given vacation days and sick days?

What fun activities can we put together for them to do productively on those off days?

**Comment by bevans2000** [comment]
> I'd like to address the need to implement time zone on Mars in connection with the changes in how work shift should work.
> 
> As I recall, the shift A in a settlement at longitude 0 will have a different start time than the shift A in a settlement, say, longitude 90.
> 
> In this case, the time difference should be 250 millisols.
> 
> If we have time zone one day, we would do it differently.

Yes I think the time zone will be easy to accommodate in a ShiftManager class. Assuming the Shift Patterns are defined in terms of a working day then when a ShiftManager is created it will create the Shifts at the appropriate time offsets.

**Comment by mokun** [comment]
> Yes I think the time zone will be easy to accommodate in a ShiftManager class.

I wonder how it would affect mission traveling. e.g. Drone flies across different time zone.

Q: How many different time zone across 0-360 longitude would you create ?

**Comment by bevans2000** [comment]
> > Yes I think the time zone will be easy to accommodate in a ShiftManager class.
> 
> I wonder how it would affect mission traveling. e.g. Drone flies across different time zone.
> 
> Q: How many different time zone across 0-360 longitude would you like to create ?

I have no idea if there is any external research on time zone on Mars. For the shifts we don't need a time zone just an millisols offset to apply to the Shift pattern in the ShiftManager constructor. .

**Comment by mokun** [comment]
> For the shifts we don't need a time zone just an millisols offset to apply to the Shift pattern in the ShiftManager constructor. .

Let's say there are two settlements and they are 80 degree longitude apart. 

The trouble is that a work shift (say, Shift A) in these two settlements will start at a different millisol and it becomes INCONSISTENT and is difficult for player to tell when shift A would start since it depends on the longitude of where the settlement is located at.

**Comment by bevans2000** [comment]
Yes I understand. But if we have a shift called Night Shift you would expect that to be active during the nighttime which will be a different time.

**Comment by bevans2000** [comment]
@mokun I've been working on this over the weekend ion a branch. Made good progress and things are easier to understand now.

I'm puzzling about what to do for the preferred shift logic. It seems very complicated and I'm planning on dropping. As a replacement I'm thinking of implement Shift rotation which means that every N Sols everyone's shifts are rotated so everyone will get a new Shift assigned. Then everyone get a change at all Shifts.
Plus this matches reality where people change Shift

**Comment by mokun** [comment]
> I'm thinking of implement Shift rotation which means that every N Sols everyone's shifts are rotated so everyone will get a new Shift assigned. Then everyone get a change at all Shifts.

Do you mean at the end of a sol you have to roll the dice to re-determine work shifts ?

Do you mean everyone's work shift gets shuffled for the next sol at that time ? 

This could wreck everybody's sleep pattern, realistically speaking.

Everyone has a preferred shift and we can let the chiefs choose their shift first and then the rest.

**Comment by bevans2000** [comment]
No each Shift Pattern would define how many Sols the shifts remain stable. For example 12 Sols; then the Shifts would be reassigned. I've removed a lot of complex code and simplified it.
I've got to do the preferences based on Job yet, that's next. Needs a bit of thought but I think each Job would have a preferred hours of working and then the logic can align that with the shifts. For the Astronomer this was hard-code in the old approach.
Remember in this new model Shifts are configurable so for large Settlements we could have overlapping daytime shift and a skeleton shift at night.
My latest commit on the branch is working but it's a bit rough. Need to revist the Console Person shift command and create a new 'shifts' command for a Settlement.
But I'm quite happy with how it it looking.

**Comment by mokun** [comment]
>  so for large Settlements we could have overlapping daytime shift and a skeleton shift at night.

When you say *overlapping*, it reminds me that in real life I have experienced working in places where 3 shifts (9 hours for each duration) are necessary for the continuous operations.

So, say, shift X is 12am-9am and shift Y is 8am-5pm and shift Z is 4pm-1am

In this case, shift X and shift Y has 1 hour overlapping (8am-9am). So that those working in shift X has the opportunity to hand over and brief those in shift Y. 

Similarly, between 4pm-5pm, those in shift Y turns over works to those in shift Z.

Same as with shift Z and Y from 12am-1am.
 
To do so in mars-sim, we will need to create a new task that allows a person to meet another person or two person to specifically *turn over* unfinished work task to the next shift.

We may or may not be able to tackle on this until we implement [this](https://github.com/orgs/mars-sim/projects/4).

**Comment by bevans2000** [comment]
Yes you can now create those type of Shift patterns; I will create one in the default configurations. I should have said that each Shift can have a different % of the population; so a night shift can have a low number of people assigned.

It's all working as far as I can tell. There are a couple of potential extra things I could add:

1. Implement logic so one person in a Shift gets a day off.
2. Allow Role & Job to specify a preferred working hours and use that to influence the Shift allocation
3. After so many Sols (at least 10) reallocate all the Shift allocations

@mokun  What do you think? Any or all of them

**Comment by mokun** [comment]
> 3. After so many Sols (at least 10) reallocate all the Shift allocations

why relocating work shift ?

**Comment by mokun** [comment]
> 1. Implement logic so one person in a Shift gets a day off.

So the question is, what would drive a person to get a day off ? 

I can see
1. He's been working for 6 days. So he's entitled to have one day for break
2. It's the first day of the week (equivalent to a Sunday) and it should have minimal manning. Most people should have take off that day.
3. He just came back from a 3+ day long mission and is automatically off the next day.

Do you like these conditions ?
5.

**Comment by bevans2000** [comment]
Someone won't be on the same shift forever. What about giving someone a day off when they change Shift? A transition period. The Shift Manager could choose one person at random to swap their Shift.

**Comment by mokun** [comment]
@bevans2000 

This [Work Shift wiki] is severely outdated, especially after the change above. Can you revise it ? 

Thanks !

**Comment by bevans2000** [comment]
Ok leave it with me

**Comment by bevans2000** [comment]
> @bevans2000
> 
> This [Work Shift wiki] is severely outdated, especially after the change above. Can you revise it ?
> 
> Thanks !

Done

**Comment by mokun** [comment]
So, how do you handle work shift during a mission ?
 
![image](https://user-images.githubusercontent.com/1168584/204390719-6319b505-818d-4d79-b51e-2de5a12a51e9.png)

I imagine during the excursion, it needs to be 24/7 or set to be "On Call" because the person will do whatever needed.

I wonder if Emma above is still at Work Shift "A" or "On Call". 

Will it go back to whatever work shift previously assigned, when the mission is over ?

**Comment by bevans2000** [comment]
The OnCall is just an override flag now in the ```ShiftSlot``` class. So when a mission completes the flag is reset and the original shift is used. When #761 is done, it will be easy to put Person on leave for a fixed period after a mission completes. We would create a new future scheduled event to reset the on leave flag.

**Comment by mokun** [comment]
So in case of Emma, should it be shown in person window and monitor tool that she's on shift A or On Call?

**Comment by mokun** [comment]
> When #761 is done, it will be easy to put Person on leave for a fixed period after a mission completes

That's awesome 😍

**Comment by bevans2000** [comment]
> So in case of Emma, should it be shown in person window and monitor tool that she's on shift A or On Call?

You will have to check or change the shared method that creates a String description  of the ShiftSlot state. I can't remember if it only veers says OnCall. I think the task Console Command shows the original Shift

**Comment by mokun** [comment]
It's very cool that the Work Shift label now shows when a person will be on duty and when he will be off duty.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/c0e3a17b-8277-43ed-beea-da9ba3f4ab60)

Now I think it's also a good idea to show the exact time (namely, start time and end time) of the shift of a person is at.

We could do it in the tooltip of the top panel over that work shift icon. See `orange` box in the snapshot above

Currently, Kenneth Cooper is on A work shift.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

I can see down the road in near future we may do two things :

(1). Create an UI panel for player commander to drag and drop the work shift of a person. 

Should we use Organization tab to do it ? 

It already has everyone's name and role in it.  

May be we can create empty slots for A/B or X/Y/Z in such a way in the tree chart that we can drag and drop names ?! Is it possible ?

**Comment by mokun** [comment]
(2). Implement the concept of time zone on Mars. 

I have heard discussions saying the easiest in doing timekeeping on Mars is to divide Mars into 12 time zones by longitudes separated by 30 degree each (360/12 = 30).

Currently, each work shift starts and ends at a different time in each settlement.

That's because we have to account for the longitude drift of a settlement.
 
We have defined the start of a sol using the so-called Universal Martian Standard Time (UMST), which defines 0 millisols at Ary crater at longitude.

So say, at 500 millisols at settlement A (say at longitude 0), for simply it's supposed to be the brightest time of the sol.

However, at the same instant of time half way around Mars at settlement B (say at longitude 180), it would be at the middle of the night.

**Comment by Urwumpe** [comment]
@mokun I think for managing the shift, it would be simpler to assign the settler to a shift team, with the number of teams depending on shift model and rotation patterns. This could then really done by drag and drop, if we just have either a list box with the members of a team or the teams in the organisation tree as nodes, so the members could be dragged there. 

Also, why not a 24 time zones on an almost 24 h Mars?

**Comment by mokun** [comment]
> either a list box with the members of a team or the teams in the organisation tree as nodes, so the members could be dragged there.

Yes that's very much doable. 

Say if there are two work shifts in a settlement, then we have a common pool of settlers and then two separate list boxes. 

This way, players may drag and drop each of them into these two boxes, or drag a settler from one box to another.

We can also add the Off-duty box and on-leave box.

**Comment by Urwumpe** [comment]
Yes, thats sounds good. Also possible or a second away to configure things, could be a drop down in the settlers unit window. 

And some buttons to automatically assign free settlers (or filtered) to shifts would be good.

**Comment by bevans2000** [comment]
Just pointing out that we made bug changes to shifts a while ago and there are be any number of shifts in a settlement; not just 2.
Also shift automatically rotate people around the shifts giving them a period of leave between. So if the user can add people to specific shifts those assignment may get automatically changed later. I don't think the current shift implementation has much wrong with it. It is a fair compromise between configuration simplicity n XML against the automatic nature.

**Comment by mokun** [comment]
> there are be any number of shifts in a settlement; not just 2.

Do you mean that there's no longer either 2 shifts or 3 shifts ? 

In the old days, for a 2-shift settlement, it'll be 500 millisols each, if there's no overlap time.

For a 3-shift settlement, it'll be 333 millisols each, if there's no overlap time.

**Comment by mokun** [comment]
>  So if the user can add people to specific shifts those assignment may get automatically changed later.

So for a 4-person settlement, say if 2 settlers is sick or both of them go to a mission, then the Shift Manager will automate the changes and have the other 2 who remain in the settlement  cover a 500-millisol work shift separately in that settlement, right ?

**Comment by bevans2000** [comment]
The shift are not hardcoded any more, they  are defined in configurations. The Shift Manager aims to meet the required target quota for each shift. So an overnight shift can have less people defined. Have a look at the settlement template
