### ISSUE TITLE
Robot Job is using class names to select MetaTask

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#749]
**Describe the bug**
Delivery Robots are not doing load/unload Tasks. They only do Teaching & Charging. This has occurred since #740 .

**To Reproduce (Please provide steps)**
Start a simulation and wait for a Vehicle to return from a Mission; DeliveryBots do not take part in the unloading.

**Expected and unexpected behavior**
The root cause is some incorrect code that is using the classname of the MetaTasks to select which Tasks a Robot can do. Using name is very fragile logic. With the new changes were MetaTasks have been consolidated; this has broken this hidden logic. I know nothing about this dubious algorithm when doing #740.
Secondly the dependency is the wrong way round; a Robot should not be dependent upon the Task. A Task can be added without needing to change the core classes. For Person; the MetaTask list suitable Person Jobs.

**Discuss any potential problems you have and have not ruled out**
This should adopt the same pattern as Person JobType where the appropriate RobotTypes are defined in the MetaTask definition. The BotTaskManager can then filter on the potential MetaTasks to sub-select the appropriate ones. This removes the reliance on MetaTask name as well as putting the responsibility for selection onto the MetaTask.

**Comment by mokun** [comment]
So in case of a person, he/she can learn and adapt.

A physicist can tend crops. It's just that he would not perform as good as a botanist.

But in case of a robot, we assume the robot type is fixed and cannot be changed. 

e.g. A delivery bot is not programming and perhaps not physically built to be like a garden bot that can tend crop.

Therefore, each robot type is limited to performing a certain set of tasks.

As long as you figure out the way to make these assumptions work, I have no problem that.

**Comment by bevans2000** [comment]
No Tasks still need to be filtered by RobotType but the way we do it currently based on names inside the RobotJob class is not great. The MetaTasks should be define which skills Job types and Robot Types are needed to complete that Task. 
I've fixed that in a branch this evening. Just looking at how to do the Teach tasks.

**Comment by bevans2000** [comment]
Changing the Teach selection logic was a bit trickier than I was expecting. Going to run some simulations to check it.

**Comment by mokun** [comment]
> The MetaTasks should be define which skills Job types and Robot Types are needed to complete that Task.

Sure. So let's also implement this approach that you have conceived. I've seen you've done that for Person class already and it's really great.

**Comment by bevans2000** [comment]
Change is done and on the way
