### ISSUE TITLE
unable to read default.sim - Java serialization issue, debian packaging

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#75]
Dear all, 

I was trying to read default.sim but was unable to read it. It would have been nicer if it was something like .json output or something which is readable but isn't, stumped.  I read the documentation on https://mars-sim.github.io/ but was unable to find anything about it. Wasn't even able to upload the default.sim to github :(

**Comment by mokun** [comment]
@shirishag75 , 

For now, mars-sim uses the standard `Java Serialization API` to save the data. So it's in a binary format and is very bulky in size. So we use xz compression to cut down its footprint but it's still slow and is not hack proof either.

Yes I agree we should make the saved file readable.

See this JSON conversion goal at https://github.com/mars-sim/mars-sim/projects/1 in our site. It's among one of the important goals in near term.

I'll have to figure out a few things before I can start refactoring the code. If someone could lend a helping hand, it could be done quicker !

**Comment by shirishag75** [comment]
just ping me when you start refactoring the code. I can help with testing but that's all I can help with.

**Comment by mokun** [comment]
> it's just that all of the above are already in Debian, so if we work with existing solutions, it would be so much easier when not many or any dependencies need to be packaged from the outside.

I recall Ubuntu used to have a Ubuntu Store and there have been discussion on how to publish mars-sim there. But it turns out to be very hard because the way mars-sim is currently compiled and packaged under Maven makes it not possible to go and look for the existence of a separate dependency already installed in your machine.

To my knowledge, the deb version of the mars-sim can be installed on different linux platform. 

How different do Ubuntu, Debian, Fedora, etc. handle dependencies ? Does it fully depend on the package manager they use ?

**Comment by shirishag75** [comment]
Actually Ubuntu derives much of it work from Debian as do most of the other deb-based distributions.  What works most of the time is shareable libraries and modules. I say most of the time is because Debian supports 25 hardware architectures and at times, in some of them due to a dependency not being built during a transition or an rebuild it takes time. 

Let me share an example of what I mean. 

see https://www.mozilla.org/en-US/firefox/organizations/

As can be firefox ESR i.e. Firefox Extended Support release is now 60.0.x and for buster that probably will be the release. 

You can see the transition slot for updating from firefox 52.0.x to 60.0.x at  https://tracker.debian.org/pkg/firefox-esr

and also an attempted build cycle at https://buildd.debian.org/status/package.php?p=firefox-esr which shows the build-dependency for a successful build-dependency or what was missing or/and a log to fix it. 

So, in essence while it would be hard work (probably) in having a way in which instead of using maven and downloading packages from the web, look for existing shared libraries on the system, my experience is that the packages are more integrated and in the short, medium and long-term the project may have more contributors downstream as well as upstream but it will require changing the way things are atm for sure.

**Comment by mokun** [comment]
see https://superuser.com/questions/140271/howto-install-firefox-dependencies-on-debian-without-root-privileges

According to that question from 2010 on that page , 

```
Firefox will not run at all without the following libraries or packages:

* GTK+ 2.10 or higher
* GLib 2.12 or higher
* Pango 1.14 or higher
* X.Org 1.0 or higher
```
We'll need to dig further to see how firefox may automatically look for missing dependencies in the machine.

Another question is : do we want mars-sim to behave like firefox ? 

In a way, we're at a crossroad. Normally, for a typical PC game, we don't want someone to worry about having to download extra stuff and make it as simple as possible. 

What do we envision mars-sim should morph into in near future ?

**Comment by mokun** [comment]
The discussion at https://stackoverflow.com/questions/2649334/difference-between-static-and-shared-libraries#2649430 is a little too general. It simply explained what static vs. shared libraries are. Also, it's C/C++ specific. 

We taught about it in a different thread already and we'll investigate further on how Java program may share dependencies.  I suspect Maven can be put to use.

**Comment by shirishag75** [comment]
I also looked at google protobuf and there are already quite a few of them packaged in Debian (except the java ones) - 

```
$ aptitude search protobuf
p   gogoprotobuf                                         - alternative protocol buffer support for Golang - utilities     
p   golang-github-gogo-protobuf-dev                      - alternative protocol buffer support for Golang - sources       
p   golang-gogoprotobuf-dev                              - transitional package -- safe to remove                         
p   golang-goprotobuf-dev                                - Protocol buffer support for the Go programming language        
p   golang-protobuf-extensions-dev                       - Protocol Buffer extensions for the Go language                 
p   gradle-plugin-protobuf                               - Protobuf Plugin for Gradle                                     
p   libactivemq-protobuf-java                            - ActiveMQ Protocol Buffers Maven plugin                         
p   libactivemq-protobuf-java-doc                        - ActiveMQ Protocol Buffers Maven plugin - documentation         
p   libghc-protobuf-dev                                  - Google Protocol Buffers for Haskell                            
v   libghc-protobuf-dev-0.2.1.2-71bd9                    -                                                                
p   libghc-protobuf-doc                                  - Google Protocol Buffers for Haskell; documentation             
p   libghc-protobuf-prof                                 - Google Protocol Buffers for Haskell; profiling libraries       
v   libghc-protobuf-prof-0.2.1.2-71bd9                   -                                                                
p   libprotobuf-c-dev                                    - Protocol Buffers C static library and headers (protobuf-c)     
i A libprotobuf-c1                                       - Protocol Buffers C shared library (protobuf-c)                 
p   libprotobuf-c1-dbgsym                                - debug symbols for libprotobuf-c1                               
p   libprotobuf-dev                                      - protocol buffers C++ library (development files)               
p   libprotobuf-java                                     - Java bindings for protocol buffers                             
p   libprotobuf-java-format-java                         - Library to serialize protobuf messages to XML, JSON and HTML   
i A libprotobuf-lite10                                   - protocol buffers C++ library (lite version)                    
p   libprotobuf-lite10-dbgsym                            - debug symbols for libprotobuf-lite10                           
p   libprotobuf-lite17                                   - protocol buffers C++ library (lite version)                    
p   libprotobuf-lite17-dbgsym                            - debug symbols for libprotobuf-lite17                           
p   libprotobuf-lite9v5-dbgsym                           - Debug symbols for libprotobuf-lite9v5                          
p   libprotobuf10                                        - protocol buffers C++ library                                   
p   libprotobuf10-dbgsym                                 - debug symbols for libprotobuf10                                
p   libprotobuf17                                        - protocol buffers C++ library                                   
p   libprotobuf17-dbgsym                                 - debug symbols for libprotobuf17                                
p   libprotobuf9v5-dbgsym                                - Debug symbols for libprotobuf9v5                               
p   protobuf-c-compiler                                  - Protocol Buffers C compiler (protobuf-c)                       
p   protobuf-c-compiler-dbgsym                           - debug symbols for protobuf-c-compiler                          
p   protobuf-compiler                                    - compiler for protocol buffer definition files                  
p   protobuf-compiler-dbgsym                             - debug symbols for protobuf-compiler                            
p   protobuf-compiler-grpc                               - high performance general RPC framework - protobuf plugin       
p   protobuf-compiler-grpc-dbgsym                        - Debug symbols for protobuf-compiler-grpc                       
p   python-protobuf                                      - Python bindings for protocol buffers                           
p   python-protobuf-dbgsym                               - debug symbols for python-protobuf                              
v   python2.7-protobuf                                   -                                                                
p   python3-protobuf                                     - Python 3 bindings for protocol buffers                         
p   python3-protobuf-dbgsym                              - debug symbols for python3-protobuf                             
v   python3.6-protobuf                                   -                                                                
v   python3.7-protobuf                                   -                                                                
p   r-cran-rprotobuf                                     - GNU R package providing an interface to the Protocol Buffers AP
p   r-cran-rprotobuf-dbgsym                              - debug symbols for r-cran-rprotobuf                             
p   ruby-google-protobuf                                 - Protocol Buffers                                               
p   ruby-google-protobuf-dbgsym                          - debug symbols for ruby-google-protobuf
```

**Comment by mokun** [comment]
Yes we will probably adopt either GSON or protobuf for serializing/deserializing data in near future.

**Comment by shirishag75** [comment]
Any updates on this ? I am reading https://tools.ietf.org/html/rfc8259 and https://tools.ietf.org/html/rfc7493 and read https://en.wikipedia.org/wiki/Gson as well as https://en.wikipedia.org/wiki/Protocol_Buffers . In between Gson and protobuf, Gson seems to be more human-friendly while protobuf seems to be a bit more machine-friendly. Looking forward to know if any updates have been done in-between.

**Comment by Urwumpe** [comment]
I would vote against GSON because it again uses Java reflection, which is maybe easier to use, but terribly slow and means being essentially there where the project started. 

I would throw the name "Jackson" into the ring. Its pretty common in Java and robust, and it must not rely on reflection, especially if just using the streaming API.  https://github.com/FasterXML/jackson

**Comment by shirishag75** [comment]
@Urwumpe I did share  libjackson-json-java as an alternate as well. I would be happy with that, it is already well supported in Debian. Could you look into default.sim and see if you can make an attempt to have it something which is more simpler and accessible for us ?

**Comment by Urwumpe** [comment]
Sure, I can give it a try.

One thing I noticed with the current system: The save files grow quickly in size. I already manually deleted a few dozen 70 MB files from my SSD lately, because old autosaves are kept right now. What about an option to limit the number of autosave files? Maybe allow a strategy in the configuration like: Keep last n sols, first sol of the past m months and one file every new orbit, for the past o years.

**Comment by shirishag75** [comment]
we had actually communicated on this privately. I had similar experiences of save files becoming big, unreadable and not really worth. Most of the info. that we need is usually in the form of logs, the save file should just give the us 'state' of things when we pause/end the simulation as for that. That should hardly be a few kb at the most, not the monstrosity that it is now. 

I had also asked/commented that old autosaves/old builds/save files which are not compatible with the current release/build should be automatically deleted or be converted to the new format but this I don't think will be possible unless we have the .json file format which is simpler to read and convert. It would be also cheaper both in the short and long-term if it's in an open format . Even if the conversion methodology fails, it would be easy to figure out what went wrong. There are indeed many benefits of having .json based file format for saving.

**Comment by Urwumpe** [comment]
I agree there mostly. I have for example no issue with historic data being recorded beyond the logs (and maybe be useful for the simulation itself), but I never jumped back and forth in time for a simulation by loading old saves. Maybe somebody else sees it differently in certain events (for example: all members of a mission die in the garage by airlock failure), but for me, a completely sequential history would be fine. 

Like in the simplest form: 
# Historic data is kept in memory for 10 sols. 
#When a new sol starts, the 10th sol data is written to a separate file in a "simulation work space" and forgotten. 
#When some entity in the simulation needs old data, the necessary historic data files are read in a read-only state.  For example, for viewing this data in GUI or via console ("What did you do on Sol 7?")

This could also be done by a relational database for example, likely better than by using files. But it would be completely different to how it is done right now.

**Comment by Urwumpe** [comment]
Well, I for example never go back to old autosaves - I just have a simple linear history in all my simulations. 

But I can see that it makes sense to be able to do just that for debugging.

**Comment by shirishag75** [comment]
True. We would need both need both forward and backward compatibility, backward compatibility for debugging purposes (why x used to happen in x build in a certain manner and why it doesn't happen in y build) forward-compatible so that when desirable new features are added those can be piggy-backed upon without re-doing everything. I have so many games half-played or half-completed especially in FOSS games because of x or y new feature, I had to do things from scratch. The game doesn't reward the user from completing till a certain checkpoint and then moving ahead.

**Comment by Urwumpe** [comment]
Well, lets keep it simple first. I doubt I can get something perfect done in first iteration. Maybe something bad, is that OK?

**Comment by shirishag75** [comment]
sure, bad is good then what we have currently ;)

**Comment by mokun** [comment]
@shirishag75 @Urwumpe , 

Yes I'll first add some file management options for saved simulations such as how often they want to autosave and  and set limits on # of saved files.

**Comment by mokun** [comment]
@Urwumpe,

A cursory look tells me Gson supports serializing more data structures than other libraries.

However, it's good that you pointed out Gson uses reflection which is slow and will probably be deprecated in future beyond Java 11.

I'll look into Jackson more and is reading https://www.reddit.com/r/java/comments/340m5q/best_java_json_parser_gson_or_jackson/

Quesion: do you recommend using proto buffer ?

**Comment by mokun** [comment]
@shirishag75 

> We would need both need both forward and backward compatibility, backward compatibility for debugging purposes

I suspect forward and backward compatibility will be a different topic that we can explore in future :)

Once we are able to save data in json format, we can play detective to look into every aspects of a settlement in the simulation to find what happens.

**Comment by shirishag75** [comment]
> @shirishag75
> 
> > We would need both need both forward and backward compatibility, backward compatibility for debugging purposes
> 
> I suspect forward and backward compatibility will be a different topic that we can explore in future :)
> 
> Once we are able to save data in json format, we can play detective to look into every aspects of a settlement in the simulation to find what happens.

agreed :)

**Comment by shirishag75** [comment]
This does eat up lot of disk resources and quickly . 

```
018-11-08T04:48:39.2 (Info) MasterClock : Ticks Per Second (TPS) : 6.67 Hz
2018-11-08T04:48:40.5 (Info) Simulation : Attempting to load the simulation from /home/shirish/.mars-sim/saved/default.sim
2018-11-08T04:48:47.1 (Info) Simulation : This sim file was made in build 4520 (size : 632.5 MB)
```

**Comment by mokun** [comment]
Fixing it now.

**Comment by shirishag75** [comment]
Did you see https://github.com/mars-sim/mars-sim/issues/124 , the file size does become big. 

Btw JFR java 11 is also now available in stretch backports https://tracker.debian.org/news/1001346/accepted-openjdk-11-90412-4bpo91-source-amd64-all-into-stretch-backports-stretch-backports/ 

and there was a new release in Debian for google-gson-java recently which would probably end up in stretch-backports soon as well. 

https://alioth-lists.debian.net/pipermail/pkg-java-maintainers/2018-November/078887.html

**Comment by mokun** [comment]
It'll take some time to investigate and limit the size of those objects that are expanding in size over time.

Meanwhile, I'll add a feature in `MarsNet System` to do an estimate of the current size of those objects in the next build or so.

**Comment by shirishag75** [comment]
that would be cool. Hopefully you can document the same so we could help you as much as needed.

**Comment by shirishag75** [comment]
I do get the following info., although atm the file size is fine - 
```

:~/.mars-sim/saved$ ls -lh 
total 6.9M
-rw-r--r-- 1 shirish shirish 3.6M Nov 14 01:52 default.sim
-rw-r--r-- 1 shirish shirish 3.3M Nov 14 01:36 previous.sim
```

in marsnet - 

```
Connected with MarsNet > ​check size


      Serializable object :     Size  (before compression)
 ---------------------------------------------------------
            CreditManager :    19.4 MB
   HistoricalEventManager :     5.3 KB
       MalfunctionFactory :    12.6 KB
                     Mars :    52.0 B 
              MasterClock :    50.3 KB
           MedicalManager :     2.2 MB
           MissionManager :    19.4 MB
      RelationshipManager :    -1.0 B 
             ResourceUtil :     3.3 KB
   ScientificStudyManager :    73.0 B 
         SimulationConfig :     2.2 MB
         TransportManager :    84.0 B 
              UnitManager :    -1.0 B 
 ---------------------------------------------------------
                    Total :    43.3 MB

```

**Comment by Urwumpe** [comment]
Should this "Check size" feature also be supported in JSON? It would require some thinking which uncompressed size to measure.

**Comment by shirishag75** [comment]
To my mind, it makes sense as we would be able to debug if and when needed but if it's too complex or something we can do that later.  Don't see any downside to it except our [Technical Debt](https://en.wikipedia.org/wiki/Technical_debt)

**Comment by mokun** [comment]
@Urwumpe , 

I've just started playing with JSON serialization using jackson. 

For now, I can save the content of the `Mars` class to a json file.

If I read back just the content and print it out, it's also fine. 

Correctly me if I'm wrong, if I want to read back each data member and list and map of a class, I will have to manually write methods to overwrite each existing values. That sounds like a lot of work, especially when I have to deal with each class/object with in `UnitManager` class hierarchy.

In comparison, Java Serialization is pretty much automatic and is so much easier to implement.

**Comment by mokun** [comment]
@Urwumpe , 

How would you serialize a Person object into json efficiently? Since within the Person class are other class and sometimes it goes down a few layers.

Java Serialization arguably does a good job of serializing objects within objects AUTOMATICALLY.

Is there a way to avoid refactoring the codes and still be able to quickly switch over to json serialization ?

**Comment by Urwumpe** [comment]
Q1: Depends on the JSON implementation we use. Even with jackson, we have multiple different ways to implement it. 

Q2: I would say by databinding and avoiding deep copys  by using references where possible. Also, I would separate the Person model class from the actual entity in the simulation, which should be a subclass of the POJO Person and which implements the needed interfaces to be used at runtime. Or encapsulate the POJO into another object (cleaner separation, but makes the code weird to read)

For the big picture, I would write the data of one entity and its subobjects (which it owns by composition) in one JSON file and the data of other entities into other files. Primarily for being more modular, but also for keeping the files easier to read. After loading a set of files with references, there would need to be a phase to resolve the references and create one big simulation model.

Also, about big pictures question, I would divide data in mars-sim by the following five classes:

1. Short message bodies for communication (JSON)
2. Saving simulation state (JSON)
3. Defining initial state of a simulation run (JSON)
4. Complex, rarely changing master data (XML)
5. Output of reports or statistics (XML and/or (X)HTML)

I would still keep XML in use there - its better for describing complex data. There are many things hard-coded right now, that would be better described in XML. We should have a better system for loading such master data though, that is a) modular and b) extended easily by mods. 

Q3: Sure, but I would still say it would make sense to refactor for other reasons as well. For example, we could separate the modules and packages better that way and make things easier to extend again.

**Comment by shirishag75** [comment]
Can somebody give an update on how the json serialization bit is coming along ? I looked at all of the history, and it seems this has been something which has been overlooked quite a bit. Maybe opening this up would also it easier for some of the other problems that we see more clearly as well. Looking forward to see what we can come up with. I am 

One thing which I noticed is @Urwumpe statement that some of the things are hard-coded. Whatever is hard-coded, does that need to be in the save-game file. Shouldn't default.sim have the bare minimum state data and all dynamic data from the session. I do see that in ~/.mars-sim we do have an xml directory which has bunch of stuff which have *.xml I am guessing they are part of the saved game. If this is right, it should in theory save us quite a bit of bandwidth (as in data) while saving default.sim .

**Comment by mokun** [comment]
> I do see that in ~/.mars-sim we do have an xml directory which has bunch of stuff which have *.xml I am guessing they are part of the saved game

They are NOT a part of any saved sims at all. 

They are [config files](https://github.com/mars-sim/mars-sim/wiki/Configuring-XML-Files) and provide attributes or values that set up the initial conditions of a settlement.

At the beginning of a sim (whether it is starting a brand new sim, or loading from a new sim), the values contained in these xml files will be *read* into the RAM.

**Comment by mokun** [comment]
> Can somebody give an update on how the json serialization bit is coming along 

We've been trying to make mars-sim more stable and been getting rid of a lot of NPE, etc.

It's quite a bit of work to switch over to JSON serialization.

@Urwumpe ,
Can you help setting up an example of using Jackson to serialize a Equipment or a Vehicle instance, etc. ?
