### ISSUE TITLE
More Mission Phases. Distinguish between those who joined a mission but never come onboard 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#754]
**Is your feature request related to a problem? Please describe.**
(1) Currently, there is no way to tell which person has been elected to join a mission but never come onboard the vehicle and embarked from the settlement.
(2) Also, there seems to be cases where a person didn't get onboard the vehicle on time.
(3) Multiple activities are expected to be accomplished in the `Embarking` (and `Disembarking`) Mission Phase. 

**Describe the solution you desire to see**
- We need to formulate a consistent approach in getting members to board the vehicle within a specified period of time. 
- We could implement 4 new Mission Phases in RoverMission  
1. Pre-Mission Training - let crew members get together to rehearse for the mission and confirm the mission objectives (note: may model more activities in future)
2. Resource Loading  - crew members to load resources - charge battery, hook up resource transfer hoses, hand-carry
3. Final Vehicle-Checkup - prepare and/or retrofit vehicle for a mission (note: may model more activities in future)
4. Boarding - crew members to get onboard with a agreed period of time

**Describe the rationale**
- It's very helpful to be able to tell if a person did come onboard when the vehicle departs from the settlement.
- The two new Mission Phases will clearly delineate what needs to get done.

**Specifications  (please complete the following information):**
 - pre-3.4.0  build 7631

**Comment by bevans2000** [comment]
Persons not boarding is a problem in the Walk logic. I spend sometime tracking one particular case and the member could not find a Walk path to the Garage; the path wanted to take them out via an Airlock. 
That logic looks a bit complicated and I didn't want to touch it.
I agree that we need to separate out the Loading phase from Embarking. We can load the vehicle before getting people to enter the Vehicle; the latter only needs doing during Embarking.  If we do that then we can implement a timeout for missing Members. The logic is pretty clean now based in the ```AbstractVehicleMission```. We can use the existing property that record when the current phase started.
I'll take a look.

**Comment by mokun** [comment]
> That logic looks a bit complicated and I didn't want to touch it.

Yes. Good that you pointed this out. The use of those two Task Phases and their methods for entering and exiting garage can be flaky and not as reliable. 

In `Walk`, we have
```
	private static final TaskPhase EXITING_ROVER_GARAGE = new TaskPhase(Msg.getString("Task.phase.exitingRoverGarage")); //$NON-NLS-1$
	private static final TaskPhase ENTERING_ROVER_GARAGE = new TaskPhase(Msg.getString("Task.phase.enteringRoverGarage")); //$NON-NLS-1$

...
	@Override
	protected double performMappedPhase(double time) {
		if (getPhase() == null) {
			throw new IllegalArgumentException("Task phase is null");

		} else if (EXITING_ROVER_GARAGE.equals(getPhase())) {
			return exitingRoverGaragePhase(time);
		} else if (ENTERING_ROVER_GARAGE.equals(getPhase())) {
			return enteringRoverInsideGaragePhase(time);

```

The question is, as we start to apply the concept of [Project](https://github.com/orgs/mars-sim/projects/4), what shall we do for task class such as `Walk` ?

**Comment by bevans2000** [comment]
I wouldn't worry about that yet. It's in the future but even with a project a Task will still have the same execute interface, so Walk maybe virtual the same. They don't all have to use the Project concept

**Comment by mokun** [comment]
In this case, Alice is reportedly "exploring a site". However, she's "not" onboard the vehicle.

On the other hand, Lyam and Scott are onboard the vehicle and exploring a site.

![image](https://user-images.githubusercontent.com/1168584/232902804-567f587b-9e7e-429f-8ba8-afd7d264dea8.png)

We need to define what onboard means clearly.

It could mean the person never get on the mission, or the person is simply not inside a vehicle.

**Comment by bevans2000** [comment]
This does not need reopening as it is working correctly. On board means physically in the Vehicle. So Exploring Site Task but in the airlock preparing to leave the vehicle will be reported as on board until they transfer to the surface. Then they are Exploring Site but not On Board. That is how the same Task can cover both states.The same happens in reverse when returning.

**Comment by bevans2000** [comment]
Can we close this again? If it is a different problem then lets create a new clearer Issue

**Comment by mokun** [comment]
Okay. I suppose we can add tooltip to explain more on what onboard really means.
