### ISSUE TITLE
Too many malfunctions on sol 1

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#755]
**Describe the bug**
- After recent change, we receive a relatively high number of malfunctions on sol 1.
- Should we report the malfunction fixed (the corresponding repair) on the Event Tab in Monitor Tool ? Currently, we do and the same event is mentioned twice at a result.

**Expected and unexpected behavior**
- We need to do some balancing so that settlers will not be too busy repairing.

**Java classes involved**
MalfunctionManager

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/202307323-95e4dd10-f862-4c86-86f6-1ef0cb6253fc.png)

**Specifications  (please complete the following information):**
 - pre-3.4.0 build 7631

**Additional context**
- Unless we come up with a parametric way to define what is reasonable, we will need to arbitrarily define the max number of malfunctions for a settlement within the specified period of time and then use a param to modulate the  number of incidents back to the acceptable leve.

**Comment by bevans2000** [comment]
This is because ```MalfunctionManager``` has a better modeling of maintenance periods that can vary instead of previously being fixed at 100. Maybe there is a fixed duration in the triggering of Malfunction ?

**Comment by bevans2000** [comment]
Yes ```MalfunctionManager``` just looks at the absolute time since last maintenance until comparing it to the maintenance period. So this is producing more malfunctions because components run for longer before they need maintenance. I will make a change.
