### ISSUE TITLE
use jdeb for making java packages. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#76]
It probably would need some contribution to jdeb 2.0 but see https://github.com/tcurdt/jdeb . It could help a lot in making java packages for Debian and with that helping all deb-based distributions including Ubuntu and others.

**Comment by mokun** [comment]
Yes, we have been using jdeb 1.6 in mars-sim. 

See the following portion of `<plugin>` in pom.xml in mars-sim-main : 

> 			<plugin>
> 				
> 				<groupId>org.vafer</groupId>
> 				<artifactId>jdeb</artifactId>
> 				<version>1.6</version>
> 				<executions>
> 					<execution>
> 						<phase>package</phase>
> 						<goals>
> 							<goal>jdeb</goal>
> 						</goals>
> 						<configuration>
> 							<dataSet>
> 								<data>
> 									<src>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/share/mars-sim-main</prefix>
> 									</mapper>
> 								</data>
> 								<data>
> 									<src>${project.basedir}/src/deb/mars-sim</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/bin</prefix>
> 										<filemode>755</filemode>
> 									</mapper>
> 								</data>
> 								<data>
> 									<src>${project.basedir}/src/deb/copyright/copyright</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/share/doc/mars-sim-main</prefix>
> 									</mapper>
> 								</data>
> 								<data>
> 									<src>${project.basedir}/src/deb/changelog.gz</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/share/doc/mars-sim-main</prefix>
> 									</mapper>
> 								</data>
> 								<data>
> 									<src>${project.basedir}/src/deb/icon.png</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/share/doc/mars-sim-main</prefix>
> 									</mapper>
> 								</data>
> 								<data>
> 									<src>${project.basedir}/src/deb/mars-sim.desktop</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/share/applications</prefix>
> 									</mapper>
> 								</data>
> 								<data>
> 									<src>${project.basedir}/src/deb/man/mars-sim.1.gz</src>
> 									<type>file</type>
> 									<mapper>
> 										<type>perm</type>
> 										<prefix>/usr/share/man/man1</prefix>
> 									</mapper>
> 								</data>
> 							</dataSet>
> 						</configuration>
> 					</execution>
> 				</executions>
> 			</plugin>

**Comment by shirishag75** [comment]
from what I can/could understand of pom.xml its not plugin as much as the ArtifactID which are important. I would try to see/get as many of the artefacts in Debian as possible so outside library usage is less or none. Debian prefers DFSG licenses.

**Comment by mokun** [comment]
May be in future when more developers are joining the project, we can reopen this issue and help us in using jdeb to get maven artifacts. 

This way, the mars-sim binary would be smaller and more portable.

Please take a look at https://github.com/mars-sim/mars-sim/issues/1072 on what we are currently planning to do.
