### ISSUE TITLE
Replace Clock polling with Scheduled events

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#761]
**Describe the bug**
The simulation is driven by time pulse events. Within the pulse receiver many entities check the current clock to wait for a certain time duration to elapse to trigger an action. This is inefficient because the check is performed for every clock pulse.

Cases are:

- Shift manager changing polling the clock to decide which Shift is on duty
- Supply missions being set in the future
- Settlement updating the Goods manager
- Calculating when Crops change phase during their development

All of these compare the current clock time to a fixed point in the future or an elapsed duration.

**Expected and unexpected behavior**
It would better to create events so that actions can be automatically trigger at a fixed point in the future. This removes the need to repeatedly compare the clock to a fixed value. An event would be a simple action listener interface where the action is executed when the time has past.
The registered event would be queued iin time order withn their respective controlling Settlement to avoid any concurrency issues. Then the pulse in the Settlement only has to check the 1st event to see if it has past instead of all events as in the current code.

This approach could rep,ace all of the refresh patterns within the code base.

**Comment by mokun** [comment]
> All of these compare the current clock time to a fixed point in the future or an elapsed duration.

Yes. We constantly compare if it is the beginning of a new day.

**Comment by mokun** [comment]
And I suspect we may be able to construct some sort of a timer class that works on MarsClock and not the system clock.

**Comment by bevans2000** [comment]
Exactly, the timer task would be based on MarsClock

**Comment by mokun** [comment]
> The registered event would be queued iin time order withn their respective controlling Settlement to avoid any concurrency issues.

But why would the old approach create concurrent issues? It was only "reading" a value within the same thread and it shouldn't cause the exception, right?

**Comment by bevans2000** [comment]
If we have a single Queue of events then these have to be executed as a singleton because they cover multiple Settlements. So having a Queue per Settlement maintains the "Unit of Work" being the Settlment.

**Comment by mokun** [comment]
> because they cover multiple Settlements. So having a Queue per Settlement maintains the "Unit of Work"

oic. 

So, do you see that the culprit is in mars-sim-ui's package in which those TableModel classes in Monitor Tool have bad queues that need to be changed and restructured so that they will work on only one settlement at a time ?

**Comment by bevans2000** [comment]
> > because they cover multiple Settlements. So having a Queue per Settlement maintains the "Unit of Work"
> 
> oic.
> 
> So, do you see that the culprit is in mars-sim-ui's package in which those TableModel classes in Monitor Tool have bad queues that need to be changed and restructured so that they will work on only one settlement at a time ?

Not really, there is no magic pattern. With any concurrent processing you need to make sure which entity is in  control of updating and for us that is the Settlement. Everything belongs to a settlement so any updates should always be done within the context of that settlement, we do this via the settlement's time passing method. There are few singletons and we update those from the UnitManager thread in a single thread.
The problem with the UI is it reads entities that are being updated by a settlement thread. This is harder to solve but we can minimise the problem by making sure any properties that need calculations are not accessed from the ui thread. This is what I did for the MonitorWindow by caching the expensive properties and reading them in the listener method which in turn is the Settlement thread, hence there is no clash. Basic properties like String can be read directly by the UI thread.

**Comment by bevans2000** [comment]
This can be expanded into Resupply missions and refreshing the GoodsManager.

**Comment by mokun** [comment]
> The problem with the UI is it reads entities that are being updated by a settlement thread. This is harder to solve but we can minimise the problem 
by making sure any properties that need calculations are not accessed from the ui thre
So let's say there are hashmaps in those table models. 

Should they be ConcirrentHashMap instead?  

This way, the reading of values by the UI thread will need will not be blocked. Only writing of values by the UI thread would be partially blocked during the updates.

**Comment by bevans2000** [comment]
ConcurrentHashMap are expensive because they take a copy in memory when they are read so they and independent of the background updates.

**Comment by bevans2000** [comment]
Changing ```Crops``` to use Future event is too difficult and not worth it as advancing time does have an important impact on Crops.
Shift & GoodsManager are done.
