### ISSUE TITLE
Expand SettementTasks to other MetaTasks

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#768]
**Describe the change**
Some of the remaining ```FactoryMetaTask``` instances are governed by the status of a Settlement and not the Worker so they should be converted to SettlementMetaTask so their output can be shared amongst workers. 

- ReviewMissionPlan should be converted. The demand attributes of the created SettlementTask should be set to the number of missions needing a review.
- Manufacturing tasks can also be shared
.

**Comment by bevans2000** [comment]
```ManufactureGoods``` is very tightly coupled to the ```Worker``` requesting the task. I't looks too complicated to convert into a SettlementMetaTask.

**Comment by bevans2000** [comment]
@mokun I've just converting ExamineBody but found an interesting problem. We remove buried Persons from the citizen list in a Settlement which creates a concurrent modification exception;. I can fix the problem easy but should we keep the buried people associated with a Settlement but just not execute a time pulse, e.g. they become dormant?

**Comment by mokun** [comment]
Yes. I haven't thought of the ramification of having a dead mm or buried person and how it should be handled when this dead person instance still exist in Unit manager. Good catch !

**Comment by bevans2000** [comment]
> Yes. I haven't thought of the ramification of having a dead or buried person and how it should be handled since this dead person instance still exist in Unit manager. Good catch !

I think we need to adopt:

* Dead - cobtaibed as an indoor Person of their home settlement
* Buried - contained by MarsSurface

On both cases the Person remains a citizen of the Settlement but does not receive a time pulse. Keeping them a citizen allows us to track deaths on a Settlement

**Comment by mokun** [comment]
> Buried - contained by MarsSurface

I see. So logically speaking, an EVA person should be on the Mars Surface as well. 

But even though a buried person is also on Mars Surface, he should and/or can be excluded from being called in the settlement thread, right?

**Comment by bevans2000** [comment]
> > Buried - contained by MarsSurface
> 
> I see. So logically speaking, an EVA person should be on the Mars Surface as well.
> 
> But even though a buried person is also on Mars Surface, he should and/or can be excluded from being called in the settlement thread, right?

So I've checked the current code and it's not straight forward. But once someone is Buried they are currently removed from the Citizen list of a Settlement; on 2nd thoughts I think this is the correct approach. This means buried people do not appear on the Monitor Tool which feels correct. So I'm going with that logic but will tidy it up to remove the concurrency exception.

**Comment by mokun** [comment]
Yes. The old way of handling a dead and/or buried person is insufficient.

**Comment by mokun** [comment]
> This means buried people do not appear on the Monitor Tool which feels correct.

I'm not sure if this is true . 

Currently, if a person is dead and or buried, it still shows up in the people tab in monitor tool, right?

It actually makes it hard for me to focus on those who are alive.

Can we add a checkbox for players to choose to to include or exclude dead people, and a separate checkbox to include/exclude buried [people?

**Comment by bevans2000** [comment]
What happens if your change tab in the Monitor Tool after the Person has died? It could be that the tool is not reacting to a Person leaving the Settlement 
But we can remove citizens as soon as they die if you want? Just needs a change in the new Settlement method.

**Comment by mokun** [comment]
> But we can remove citizens as soon as they die if you want?

If that person is removed, players would not have noticed that someone has died. 

So, it's better we provided a checkbox option for players to choose whether they want to display dead/buried people, right ?

**Comment by mokun** [comment]
> So, it's better we provided a checkbox option for players to choose whether they want to display dead/buried people, right ?

I'm on track adding a checkbox in MonitorWindow so that the entity list in PersonTableModel will filter dead people.

Will commit in a moment.
