### ISSUE TITLE
Not enough GardenBots in large settlements

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#771]
**Describe the bug**
There are not enough GardenBot for large settlements. In the default Scenario the large settlements have 4 greenhouses but only 2 GardenBots. This results in a excess of Tend Greenhouse task always being present.
The reverse can also be true where a small settlement may not have any Greenhouses but GardenBots are still created.
The bot allocation is done on population of the Settlement.

This has become obvious after #769.

**Expected and unexpected behavior**
The allocation of Robot Types should be based on the contents of the Settlement and solely the population:

- GardenBot numbers depends upon the number of Greenhouses
- ChefBot on the number of Kitchen facilities
- MedicBot depends on the population
- DeliveryBots on the numebr of Vehicles
- RepairBots on the number of Buildings needing inside maintenance. 
etc etc

This should be a function of the ```RobotJob``` class to provide expandability. Then when creating new Robots the current allocaiton can be compared to the desired allocation. From this it is possible to assess the "demand" for a certain RobotType. The type with the highest demand is created.
The desired count would be adjusted to the target total numebr of Robots.

**Additional context**
This can also be expanded into the Goods value for Robots, the value can be based on the demand. For example, if a Settlement has enough GardenBots; then their Buy Value would be very low as they are not needed.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

> The allocation of Robot Types should be based on the contents of the Settlement and solely the population:

Besides allocating the # of robot types, we should define more clearly what it means to tend the crop in order to make it more meaningful.

> the value can be based on the demand. For example, if a Settlement has enough GardenBots; then their Buy Value would be very low as they are not needed.

Without the detail or what a gardenbot or a farmer may do, merely increasing the value of the multiplier that goes into the modified work hours would suffice to fix it but still not meaningful enough and sounds more like like cheating.

So can deepen the modeling fidelity of what it means to tend a greenhouse ?

When it comes to taking care of the greenhouse, detail tasks such as 
1. trimming down the overgrown
2. paying attention to the nutrients uptake
3. Propagating the new seedlings
4. Adjusting the light level

Health should be a multi-dimensional index and not just a 1-D percentage number.

**Comment by bevans2000** [comment]
Yes I see what you mean but the problem is 2 levels. This issue is specifically addresses the mixture of Robots is based on population and not the Settlement structure. So if I create a Settlement with 10 greenhouses I would not have enough GardenBots. Another example is a Settlement that is a "resort/hotel" that has many kitchens/dining areas; we would need more ChefBots.
So this issue need addressing but at the lower level there is a problem of how to gauge demand in general. I've done some changes as part of #769 and things are slightly more balanced now.

**Comment by bevans2000** [comment]
As part of this change I plan to make some modelling changes to Robots:

- Move pre-defined Robots out of robots.xml; this file will just define the characteristics of Robot Types.
- Introduce the concept of a "model/make" with individual characteristics, e.g. 2 different GardenBot could be different makes and hence have different characteristics how they tend greenhouses
- Rework the ```RobotJob.getSettlementNeeds``` so it calculates the ideal number of Robots needed for that Settlement
- Use the above to influence the creation of new Robots & the Goods value of Robots via ```RobotValue``` (although I don't know how but feels it is related)

**Comment by mokun** [comment]
> Introduce the concept of a "model/make" with individual characteristics, e.g. 2 different GardenBot could be different makes and hence have different characteristics how they tend greenhouses

I have in mind to diversify the tasks for gardenbots. They can help taking pictures and gather plant growth metrics, trimming dead branches, etc.

Once ready, say, 50 pics was taken on a crop and various growth metrics are gathered, a person may come in to determine what to do next. 

This way, gardenbots are not doing exactly the same things as a human being.

**Comment by bevans2000** [comment]
That's an interesting idea, so the TendGreenhouse task would have different Phases for a Robot compared to a Person.

**Comment by mokun** [comment]
> so the TendGreenhouse task  would have different Phases for a Robot compared to a Person.

We can make those sample gathering tasks doable by anyone, including any settlers and gardenbots.

It's just that the post-analysis part needed to be done by someone having high botany skill and went through some sort of certified training.

Speaking of training, the concept of certification could be a good addition for complementing the abstract concept of skill levels.

**Comment by bevans2000** [comment]
Certification is just having a certain skill to a predefined level?

**Comment by bevans2000** [comment]
@mokun I have redone the Robot allocation logic so each RobotType is assessed on it's own merits. The logic is now in a new class ```RobotDemand``` that is a transient class created when new Robots are added. It does:

1. Calls the ```RobotJob.getOptimalCount``` to firstly know how many of each type are needed per the Settlement
2. This set is converted into a percentage distribution
3. When selecting a new robot the current Robt count is mapped onto the %age distribution
4. The shortfall for each type is then calculated
5. The type with the biggest shortfall is selected

The subclasses of ```RobotJob``` each have an individual different implementation that assesses specific attributes of the Settlement. 
The changes are on a branch at the moment.

**Comment by mokun** [comment]
> Certification is just having a certain skill to a predefined level?

I see we can develop the modeling further in this area to make it more reality-based.

For instance, `Engineering` is actually a very broad subject area. We could model many types of certification area within this one category.  

Same is `Medicine` and any of the 20 skills that we currently have.

Before someone can promote to the next skill level, they would have to take an examination to get certified for a particular area.

So we would need to create new tasks in which settler spend time studying for an certification exam and even how many times one would take the exam. 

btw, the `Reading` task kind of serves a bit of this purpose on a particular subject. 

It's good to cleanly divide the learning into (1) ***Theory***, namely, the academics such as Reading and Study for an exam) and (2) ***Practice***, namely, hands-on experience (labor hours /millisols spent in a task).

If the exam is passed, he gets the stamp of approval for certain types of professional certification.

If he get certified over a few area (or even the next tier of the same area), then we may be qualified for promotion to the next skill level, etc.

**Comment by mokun** [comment]
Btw, we have an empty `Training` class that we haven't done anything with it so far.

But we are currently using the enum `TrainingType` class and `TrainingUtils` class only that are for determining the previous trainings and for computing the modifiers for determining a person's role only.

But we could start a new `Certification` class with bronze, silver and gold tiers. 

We may be able to associate or unite it with `FavoriteType`.

Also, we can tie certification to the scientific topic when writing a paper. There are already a list of topics within each scientific subject. We just need to tidy them up into cleanly defined sub areas. 

Say, in Physics, we may have "Classical Physics", "Particle Physics", "Quantum Theory", "Condense Matter", etc.
