### ISSUE TITLE
Settlement class has too much logic

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#773]
**Describe the bug**
This has been a bug bear of mind for a while. The ```Settlement``` class contains logic that would be better placed closer to the target classes. For example bed allocation, Robot type selection, tune Job Defects. 

This means the class is over 3000 lines long and has a lot of different logic embedded. 

Key changes:

- The ```ResourceStats``` can be changed to the existing DataLogger framework. This will simplify the time methods
- The ```solCache``` attribute is not needed as the MetaTasks have access to the current marsTime already
- Bed Allocation logic can be moved to the LivingAccomodation function as a static based on a Settlement
- Tuning Job allocation
- Objective levels can be changed so that ```GoodsManager``` also uses ObjectiveType

**Comment by mokun** [comment]
> bed allocation, Robot type selection, tune Job Defects. This means the class is over 3000 lines long and has a lot of different logic embedded.

Sure. Let's clean them up.

**Comment by bevans2000** [comment]
Another example is the method ```createAdjacentBuildings``` which is called by external classes. But this logic of this method should be moved to the Building ConnectionManager.  The callers should then use the ```Settlement.getBuildingConnectors``` method which has the same outcome BUT the adjacent buildings come from a pre-calculated cache.

**Comment by bevans2000** [comment]
Move the find airlock methods to a Walk class as static method.
Move chatting person logic to the Conversation class

**Comment by mokun** [comment]
I've moved some methods out already. 

Will need to relocate the rest of airlock related methods to building manager, or better yet. I'll create a new EVA manager to handle some data members.

**Comment by bevans2000** [comment]
Ok, I've commented already places were we can tidy up the Settlement class.

**Comment by bevans2000** [comment]
Also the use of ResourceStat can be changed to the existing DataLogger framework.
The solCache attribute is not needed as the MetaTasks have access to the current marsTime already.

**Comment by bevans2000** [comment]
I am going to look at the overlap between Settlement and GoddsManager. Plus how it interacts with the Review Task

**Comment by mokun** [comment]
> overlap between Settlement and GoddsManager

what kind of overlaps ?

**Comment by bevans2000** [comment]
> > overlap between Settlement and GoddsManager
> 
> what kind of overlaps ?

The review logic relies more on GoodsManager than Settlement so it should be moved.
Also how then objective adjust the good manager factors is messy and bloated

**Comment by mokun** [comment]
Can we have two ways of updating the demand value of a good ? Namely, a fast one and a slow one.

1. All life support resources need a fast response to its demand value.

2. All emergency repair requests that ask for parts replacement needs a fast response also.

3. Non-urgent maintenance parts replacement can use the slow one.

4. The slow one is the default

**Comment by bevans2000** [comment]
I'm not directly looking at that yet BUT its important that the demand value is accessible quickly to any caller, I.e. read only. Getter  methods should ideally be immutable. We should update the demand values periodically using the FutureScheduledEvent framework. That is what we do for the buy and sell lists. In theory we could refresh the demand values at the same time.

**Comment by mokun** [comment]
> its important that the demand value is accessible quickly to any caller, I.e. read only.

Agree !

> We should update the demand values periodically using the FutureScheduledEvent framework. 

ic. This could be used for slow update.

But if the oxygen is dwindling, we need a immediate surge of the oxygen demand value right away, and that's where the fast response is needed.

**Comment by bevans2000** [comment]
Ok. Let me work on the changes I know about and then build from there

**Comment by mokun** [comment]
We need to talk about what our design philosophy should be. 

Should we shdit to focusing more on creating as much UI control elements for players to choose what they should do ? 

Or should we continue down the path of making everything automated and "hands off" fashion ?
