### ISSUE TITLE
EVA suits cannot be repaired in a Vehicle

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#778]
**Describe the bug**
If an EVA suit fails in a Vehicle the Person cannot repair it. The log message suggest a pending Task is created for the repair but it cannot be found. Name is the old 'RepairInsideMalfunction'.

Relates to #741 
**To Reproduce (Please provide steps)**
Once a Mission has started use the create Malfunction console command to trigger the failure. 

**Expected and unexpected behavior**
The pending task created should use the new TaskJob approach.
.

**Comment by bevans2000** [comment]
I've also noticed last night another a couple of other issues:

- It is not possible from the console 'create malfunction' command to trigger a EVA Malfunction; only in a Settlement.
- Broken EVA Suits in a Settlement are not being added tot eh Settlement Backlog.

I will address both of these at the same time.

**Comment by bevans2000** [comment]
Proved to be a bit trickier than planned. Another problem I've uncovered is that we never call the method 
 ```Equipment.timePassing``` because there are many Equipment that are passive. The net effect is that once a Equipment based Malfunction is completed; it is never cleared from the ```MalfunctionManager``` leaving the Equipment unusable. 
Malfunctions should remove themselves from the MalfunctionManager once they have been completed and not rely on time passing.

**Comment by mokun** [comment]
So Is there a console command for checking if some equipment/vehicle have malfunctions ?

**Comment by bevans2000** [comment]
> So Is there a console command for checking if some equipment/vehicle have malfunctions ?

Yes, run the 'malfunction' command on either a Settlement kr Vehicle

**Comment by mokun** [comment]
I mean for equipment

**Comment by bevans2000** [comment]
The console will show the malfunctions of anything contained including Equipment and Buildings
