### ISSUE TITLE
Robot's battery always show Full 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#779]
**Describe the bug**
- Why would all bots' battery always shown as Full ?
- Also, some bots are running charging tasks

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/208583024-1938bf60-e947-49bf-8bee-5f569cabd9f7.png)

**Specifications**
 - pre-3.5.0 build 7726

**Comment by bevans2000** [comment]
Charging is the default Task when there is nothing else to do so many idle Robots are continuously at Full Charge.  This loosely relates to #771 because the mix of Robots is not aligned to the needs of the Settlement structure. Maybe we should change the default Task to "Idle" or change the Charge Task to have a new Phase 'Power Save" once it is fully charge but remaining at the Robotic Station. I quite like the later.

**Comment by Urwumpe** [comment]
Could we use the robot batteries maybe as power storage for the base like planned on Earth as Vehicle-to-Grid (V2G)? In that case, longer idle times or robots would not be wasted time and we could have more fluctuations in the power demand or supply.

**Comment by mokun** [comment]
> Could we use the robot batteries maybe as power storage for the base like planned on Earth as Vehicle-to-Grid (V2G)?

It's possible. 

Interestingly, in some buildings under the power-storage tag, we may find something like : 

```
<power-storage capacity="20"  discharge-rate="1.25"/>
```

I double check and found that a robot battery is currently by design rated at 20 kWh capacity also.

I suppose these batteries can even be swapped in and out if needed.

In comparison, "Medium Battery Array" offers 300 kWh for storing excess utility power as follows : 
```
	<!-- An Array of Electrical Batteries -->
	<building type="Medium Battery Array" width="5.0" length="10.0" base-level="0"
			wear-lifetime="3340000" maintenance-time="50" room-temperature="0" base-mass="500">
		<description> The Medium Battery Array showcased an advanced battery system that
			stored excess power during non-peak hours and released power during peak power
			usage.
		</description>
		<power-required base-power="0.5" base-power-down-power="0.05" />

		<functions>
			<!-- power storage capacity in the energy unit of kW hr. -->
			<power-storage capacity="300"  discharge-rate="1.75"/>
		</functions>
	</building>
```

In terms of Item Resources (or Parts), we have "Chemical Battery" rated at 15kWh :

```
<part name="Chemical Battery" type="vehicle" mass="225.0">
		<description>Assuming the achievement of 15 kg/kWh 
		for a full battery with supportive structures, 
		this 15kWh rechargeable battery provides 'auxiliary' 
		electrical power to the vehicle, on top of the primary
		fuel cell stack. It operates at 400V. With 15 kWh capacity,
		or 37.5 Ah (= 15/.4). Assume 6.43 km/kWh (based on a Tesla Model S
		battery pack weighing 2240 kg with 100 kWh capacity that can travel 
		643 km), this battery allows traveling a distance of 96.5 km on a single charge.
		</description>
		<maintenance-entity-list>
			<entity name="rover" probability="2" max-number="4" />
			<entity name="light utility vehicle" probability="2" max-number="1" />
			<entity name="delivery drone" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>
```

At the same time, we also `EVA Battery` (1.2 kWh) as follows :  
```
	<part name="EVA Battery" type="EVA" mass="2.4" >
		<description>Assuming the achievement of 500 Wh/kg, this 
		rechargeable battery module is rated for 150 W at 18V 
		for providing 8 hrs of electrical power to the EVA suit. 
		Total energy capacity is 150 * 8 = 1.2 kWh. Weight: 1.2/.5 = 2.4 kg
		</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>
```

So, may be the first step is to standardize them by creating an intermediate Part called "Battery Module". 

Say if each "Battery Module" is 2 kWh, then a robot battery would need 10 modules. Each type of  "Vehicle Battery" may need a different number of modules. A building battery will also have a different number of modules to match its needs, etc.

**Comment by bevans2000** [comment]
Also after #771 we can specify a different charge capacity for different Robots. So this might work with your battery module idea, maybe expand it to say how many battery modules a Robot takes instead of the specific Charge.
