### ISSUE TITLE
why do we need the following artifacts or plugins ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#78]
As and when I would find them, I would like to know why we need a particular maven plugin . 

For instance we have libjacoco-java already in Debian, why do we need the maven plugin ?

```
$ aptitude show libjacoco-java
Package: libjacoco-java                  
Version: 0.8.1-1
State: installed
Automatically installed: no
Priority: optional
Section: java
Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Architecture: all
Uncompressed Size: 683 k
Depends: libasm-java (>= 6.0)
Description: free code coverage library for Java
 JaCoCo is a code coverage checking library for Java. It has been integrated into many libraries and tools like Gradle,
 Maven, and Android SDK. 
 
 This package currently provides 2 libraries: 
 
 * org.jacoco.core.jar 
 * org.jacoco.report.jar
Homepage: http://www.eclemma.org/jacoco

```

Also that library is old, no work done for last 4 years or so :(

whereas libmaven-processor-plugin-java is already there in testing - 

```
$ aptitude show libmaven-processor-plugin-java
Package: libmaven-processor-plugin-java  
Version: 3.3.2-2
State: installed
Automatically installed: no
Priority: optional
Section: java
Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Architecture: all
Uncompressed Size: 70.7 k
Depends: libmaven-plugin-tools-java (>= 3.5), libmaven3-core-java (>= 3.5.2), libplexus-compiler-java (>= 2.8.3), libplexus-utils-java
Description: Maven plugin to process annotations for Java 6 at compile time
 The Maven processor plugin helps to use from Maven the new annotation processing provided by Java 6 integrated in the
 Java compiler. This plugin could be considered the 'alter ego' of the Maven apt plugin.
Homepage: http://bsorrentino.github.io/maven-annotation-plugin/

```

**Comment by mokun** [comment]
Seems like JaCoCo came with Maven when you installed Maven in your machine. Can you double check that ? 

mars-sim does not use JaCoCo in any of its pom.xml's

**Comment by shirishag75** [comment]
umm... that is strange then because at - 

https://github.com/mars-sim/mars-sim/blob/master/pom.xml

specifically at line 157 I see the following - 

```
<build>
		<pluginManagement>
			<plugins>
<!-- <plugin> <groupId>org.jacoco</groupId> <artifactId>jacoco-maven-plugin</artifactId> 
```

**Comment by mokun** [comment]
oh I see it used to be included but as you can see, `<!--` and `-->` are being used before and after that block to comment out this plugin in the current pom.xml.

It's not needed anymore after r4428 as of 2018-08-24.

In other words, you can remove it when the next build 3.1.0-b2 is released.

Thanks for pointing that out!

**Comment by shirishag75** [comment]
Maybe also remove it in a future commit perhaps. 

In the same block nativedependencies-maven-plugin is also mentioned, maybe that too is not used anymore, am I correct ?

**Comment by shirishag75** [comment]
Another one which seems to be dead and buried is the maven-release-plugin, see https://axelfontaine.com/blog/dead-burried.html
