### ISSUE TITLE
Starting the 3.4 swing jar files without parameters results in message box "Problem starting Can not find settlement_phase2-us.xml"

### ISSUE THREAD

**Issue by Urwumpe** [mars-sim/mars-sim#783]
**Describe the bug**
When starting the jar files by double click (under windows) or calling `java -jar .\3.4.0_swing_java11.jar`, the program displays a message box with the error message "Problem starting Can not find settlement_phase2-us.xml". In the console window, there is a IllegalStateException. 

**To Reproduce (Please provide steps)**
1. Double click on the jar file or
2. Run `java -jar .\3.4.0_swing_java11.jar`

Erased the .mars-sim folder in user directory

The problem can also be reproduced by launching with -new and select "Yes" for creating a new default simulation.

**Expected and unexpected behavior**
The program is able to launch with a default scenario or behaviour (Suggestion: Resume the previous simulation.)

Any error message show to the user should use proper grammar and spelling. Any such error message displayed to non-developers should contain enough information to understand the problem and ideally suggest actions to fix it. 

**Screenshots**

![grafik](https://user-images.githubusercontent.com/10480792/209469544-528ba590-dde5-4a29-aa55-192eea6ce168.png)

**Stacktrace**
```
01-Adir-01:000,000 (Severe) MarsProject : Problem starting Can not find settlement_phase_2-us.xml
java.lang.IllegalStateException: Can not find settlement_phase_2-us.xml
        at org.mars_sim.msp.core.configuration.UserConfigurableConfig.loadItem(UserConfigurableConfig.java:137)
        at org.mars_sim.msp.core.configuration.UserConfigurableConfig.getItem(UserConfigurableConfig.java:182)
        at org.mars_sim.msp.core.structure.SettlementBuilder.createFullSettlement(SettlementBuilder.java:108)
        at org.mars_sim.msp.core.structure.SettlementBuilder.createInitialSettlements(SettlementBuilder.java:91)
        at org.mars_sim.msp.core.SimulationBuilder.start(SimulationBuilder.java:314)
        at org.mars_sim.main.MarsProject.parseArgs(MarsProject.java:191)
        at org.mars_sim.main.MarsProject.main(MarsProject.java:469)
```

**Specifications  (please complete the following information):**
 - Windows 11
 - java version "16.0.2" 2021-07-20

**Comment by mokun** [comment]
Looks like it's Java 16 that causes this. We'll need to investigate why. 

At least, for now, using Java 11 won't run into this issue.

From the stacktrace above, it shows that UserConfigurableConfig: getItem returns a null value. 

```
	/**
	 * Gets a item by its name.
	 * 
	 * @param name
	 * @return
	 */
	public T getItem(String name) {
		T found = knownItems.get(name);
		if (found == null) {
			// Then it's a load on demand entry
			String file = getItemFilename(name);
			logger.config("Loading a template on demand: '" + itemPrefix + " " + name + "'.");
			loadItem(file, true);

			found = knownItems.get(name);
		}
		return found;
	}
```

@bevans2000  What do you make of this ?

**Comment by bevans2000** [comment]
Looks solvable. I've assigned it to me

**Comment by bevans2000** [comment]
The problem has nothing to do with Java 16. The settlement templates have been renamed with mixed case which breaks the extract bundled XML logic.
Correct on a bugfix branch and will make release 3.4.1
