### ISSUE TITLE
openjdk 11 support and openjfx release 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#79]
This is for tracking openjdk 11 support and openjfx release . 

This is the version of openjdk 11 now in Debian testing - 

```
$ apt-cache policy openjdk-11-jre
openjdk-11-jre:
  Installed: 11~28-1
  Candidate: 11~28-1
  Version table:
 *** 11~28-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

Just saw this https://lists.debian.org/debian-java/2018/09/msg00041.html so looks like we can expect a new openjfx soonish (unless something breaks horribly or something) . 

But that wouldn't diminish my interest in seeing the headless mode.

**Comment by mokun** [comment]
looks like they have to resolve an incompatibility issue with the new gradle version (because of the gradle-debian-helper) before they can sign off Java 11.

**Comment by shirishag75** [comment]
yup, as shared Emmanuel is working on it. This was told to me last month as well, that the new version of gradle has some issues. I am hopeful they will work it out sooner rather than later.

**Comment by shirishag75** [comment]
I would also recommend looking at https://lists.debian.org/debian-java/2018/09/msg00042.html and the resources I shared therein. Gives some more insight on what happen in the near and medium term.

**Comment by mokun** [comment]
Sure. It makes sense to wait till Java 11 comes out.

I'll look for any incompatibilities that may arise due to any changes in existing APIs.

This way, the next pre-release, namely v3.1.0-b2, will be able to run on top of Java 9, 10, and 11.

**Comment by mokun** [comment]
I was told that openjfx 11 requires at least openjdk 10.

**Comment by mokun** [comment]
We've migrated to Java 11 since [build 4945](https://github.com/mars-sim/mars-sim/releases/tag/4945). Close this thread now.
