### ISSUE TITLE
Define UI icons in a dedicated IconSet file

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#791]
**Describe the improvement**
The path to icons are defined in the language properties file but they are more constant than the language bindings.
Within the code they are reference to the local of resources for the PNG images.

The icons can be defined in a single dedicated properties files based on a unique id along with the appropriate file to load. This file could be preloaded into an icon manager as a single operation. The code would then just reference Icon via the unique ID.

It would also support multiple file format as currently the application code needs to know the format of the image file.

The logic should use default nami g convention as much as possible such that the IconSet defines overrides to the defaults.
This is a reworking of the ```ImageLoader``` class.

Follow on activity from #789

**Comment by mokun** [comment]
> The icons can be defined in a single dedicated properties files based on a unique id along with the appropriate file to load

When you say unique id, do you mean an int or just a string id ?

Currently, we have two main places (either img.xxx or icon.xxx) from messages.properties where we can find a list of IDs for icons : 

```
img.speed.speedUp      = /icons/speed/forward.png
img.speed.increase     = /icons/speed/increase.png
img.speed.decrease     = /icons/speed/decrease.png
img.speed.play         = /icons/speed/play.png
img.speed.pause        = /icons/speed/pause.png
img.speed.slowDown     = /icons/speed/rewind.png

...
icon.screwdriver			= /icons/tabpanel/screwdriver_24.png
icon.spanner				= /icons/tabpanel/spanner_24.png
icon.inventory				= /icons/tabpanel/inventory_24.png

```

May be we can unite them into one ID format.

**Comment by bevans2000** [comment]
Yes I think we can remove these from the message properties and rely more on naming conventions to remove the lookups. My main concern was different ways in the code to load images/icons with the IconManager from weblaf and our own ImageLoader. Once weblaf is gone we can think about this one.

**Comment by mokun** [comment]
Our current ImageLoader works well, right ? 

May be you can standardize or further optimize how it's being used in a more consistent manner.

For sure, the drawback with ImageLoader is that it doesn't load svg icons.

If we can find a replacement for IconManager from weblaf, it will be truly great, since svg files generate scalable size of icons.

**Comment by bevans2000** [comment]
There is a mixture of classes that take part in Icon/Images. 

- MSPIconManager (holding class to cover weblaf IconManager)
- SVGIcon
- ImageLoader

We will standardise on 2 patterns:

- IconManager (new) - Handles ALL Icons and source will be either PNG/JPEG. This is a consolidation of the temp. MSPIconmanager.
- ImageManager (exiting ImageLoad reworked). Any images will be defined as SVG; mainly used by the Settlement Tool.

In both cases we will drop the use of the Msg class to look up the location of the real file; the 2 above will be keyed by a logical name. We will look to use naming conventions as much possible with each manager having a dedicated properties file to deliver custom "logical name" to "real file".

**Comment by bevans2000** [comment]
@mokun I noticed last night that the icons are 24x24 instead of the standard 16x16. Any reason?

**Comment by bevans2000** [comment]
> That's because when it's 16x16, some important details are not visual.
> 
> Once we have bigger fonts, can we also have bigger icons?

Bigger than 24x24.......... how big is your monitor? I would downgrade to standard 16x16 personally but let's standardize on 24x24. There are some which are 16x16 and they look a bit odd so we can resize them to 24x24.

**Comment by mokun** [comment]
Sure. Does it mean your icon manager will automatically enlarge those 16x16 icons to 24x24 ? 

I have seen 16x16 icons got patched with empty pixels in 24x24 area and that would look ugly

**Comment by bevans2000** [comment]
> Sure. Does it mean your icon manager will automatically enlarge those 16x16 icons to 24x24 ?
> 
> I have seen 16x16 icons got patched with empty pixels in 24x24 area and that would look ugly

No that is very difficult to keep the stretch smaller icon without losing clarity. I haven't changed the loading from PNG, only simplified how icons are referenced and shared. But in theory we could have 2 sets of icons in different sizes and the user could configure. Short term is all PNG icons should be 24x24 so they look consistent. The latest commit is an intermediate phase.
