### ISSUE TITLE
Excessive log stating "Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint"

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#799]
**Describe the bug**
- Need to turn off this excessive log statement

**To Reproduce (Please provide steps)**
1. Go to Settlement Map
2. Zoom in or out the map by using the mouse scroll 
3. Stacktrace will show excessive number of the same statement 
```
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
```

**Discuss any potential problems you have and have not ruled out**
- Based on this [page](https://www.jfree.org/forum/viewtopic.php?t=4116), the culprit is due to the use of JFreeChart in combination with Batik in rendering svg image in Java2D

**Java classes involved**
- Batik maven artifact
- jfreechart maven artifact

**Stacktrace**
```
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
Graphics2D from BufferedImage lacks BUFFERED_IMAGE hint
...
```

**Specifications**
 - pre-3.5.0 build 7780

**Comment by bevans2000** [comment]
Yes I noticed this. I worked on the ```SettlementMapPanel``` last night so will see if there is anything that can be done. Might have to wait until we centralize icon/image management in #791

**Comment by bevans2000** [comment]
Have to make sure that the System Property "org.apache.batik.warn_destination" is set to false. It is set in some classes but the call needs to be raised up into the ```MainWindow``` class.
