### ISSUE TITLE
Mining ending at Mining Site due to Not enough resources to continue 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#8]
Created: 2014-11-26
Migrated from https://sourceforge.net/p/mars-sim/tickets/15/

This incident created a NullPointerException inside method miningPhase() at the line 504 `getRover().setTowedVehicle(luv)` in Mining.java, causing the system to crash.

While mining, the vehicle Shooting Star ran out of oxygen (and water).

Caused by: 

```
java.lang.NullPointerException
at org.mars_sim.msp.core.person.ai.mission.Mining.miningPhase(Mining.java:504)
at org.mars_sim.msp.core.person.ai.mission.Mining.performPhase(Mining.java:319)
at org.mars_sim.msp.core.person.ai.mission.Mission.performMission(Mission.java:358)
at org.mars_sim.msp.core.person.ai.Mind.takeAction(Mind.java:128)....
```

**Comment by shirishag75** [comment]
![boris debic location of shooting star](https://cloud.githubusercontent.com/assets/727626/22943697/818ed2b4-f314-11e6-9578-2bf9287f571d.png)

![boris debic starvation](https://cloud.githubusercontent.com/assets/727626/22943728/95fdff7c-f314-11e6-81dc-a500d6d2b5dd.png)

![no oxygen and water on vehicle shooting star](https://cloud.githubusercontent.com/assets/727626/22943753/a56fdc32-f314-11e6-8822-8797e5fbcc4f.png)

**Comment by mokun** [comment]
Calling `luv.setTowingVehicle(null);` at line 439 in Mining.java will detach towed light utility vehicle if necessary.

If the phase is not ended, it will mark the site as mined and begin to attach light utility vehicle for towing with the lines 547 and 548 :

```
getRover().setTowedVehicle(luv);
luv.setTowingVehicle(getRover());
```

It results in NullPointerException if 
1. getRover() is null (Shooting Star became null)
OR 
2. luv is null (the Light Utility Vehicle is missing, i.e. NOT being brought to the mining site). 

> While mining, the vehicle Shooting Star ran out of oxygen (and water).

Perhaps it was when the vehicle Shooting Star ran out of O2/H2O, the logic made it null in that clock frame.

Will keep observing to see if this issue pops up again.

**Comment by mokun** [comment]
This NullPointerException has been resolved. Thanks @shirishag75 for pointing that out. Issue closed.
