### ISSUE TITLE
Clean up use of Fonts & Colors in Swing  UI

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#801]
**Describe the improvement**
The Swing UI is ow using vanilla Swing components. This allows us to control the styling of the UI by the UIManager and Look & Feel classes. However some components are using explicit Font and Color assignments.

**Expected and unexpected behavior**
Remove the majority of the Font and Color assignments so that all components pick up styling from the single Look and Feel.

Eventually, once completed, the user can select the look and feel.

**Comment by mokun** [comment]
We can even use flatlaf in conjuncture with [Jide-oss as a plugin](https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-jide-oss). 

But we have already been using the formdev version of [Jide-oss (3.7.12)](https://search.maven.org/artifact/com.formdev/jide-oss) here and there.

**Comment by bevans2000** [comment]
My opinion is do we need to use special components? It's clear the standard components are covering nearly everything, we have a coup,e of in house components now, JMemoryBar and JStatusBar. The benefits of staying with the standard components is we can use look a d feel to style the ui consistently. 
Let's keep going with this Task to centralise the styling. I've got some changes to commit

**Comment by mokun** [comment]
It looks differently now.

Fonts like smaller.

Can we have some lines back ? e.g. in the toolbar, menu, etc.

The box dimensions in the Mars Navigator are off now.

**Comment by bevans2000** [comment]
It's using standard components now. The point is we can now look to use a different Look and Feel to control how it looks. The problem is there is a lot of Fonts/Color/styling in specific places. If we clean it down to a single set then it gives us better control.

Have a got with this Demo to see how we can control it. https://www.formdev.com/flatlaf/#demo
FlatLAF supports custom look and feel; so we could create our own if you want. I'm going to make the L&F selectable from the Options window and hold it in the ConfigUI.

**Comment by bevans2000** [comment]
Yes I agree, the Navigator Window seem wrong now. Not sure why but I'll look.

**Comment by mokun** [comment]
Beside, FlatLAF that you start using, we've been using jide-oss.

**Comment by bevans2000** [comment]
> jide-oss

It doesn't look well maintained anymore. What do we use it for?

**Comment by bevans2000** [comment]
@mokun Also I've worked out how to use the UI Swing Default to remove the need for ZebraTable as well. There is a alternative colour property that can be used on the normal Cell Renderer so that makes it much simpler and reacts to the colours in the LAF. I'm going to make this change as well.
Do you want to use a slightly larger font as well you mentioned?

**Comment by mokun** [comment]
> Do you want to use a slightly larger font as well you mentioned?

Yes. That would be awesome.

**Comment by bevans2000** [comment]
> > Do you want to use a slightly larger font as well you mentioned?
> 
> Yes. That would be awesome.

Ok, lets see what we can do. I feel its coming together now. The UI is very consistent now and cleaner in the code.

**Comment by bevans2000** [comment]
> > > Do you want to use a slightly larger font as well you mentioned?
> > 
> > 
> > Yes. That would be awesome.
> 
> Ok, lets see what we can do. I feel its coming together now. The UI is very consistent now and cleaner in the code.

Changed the default font.

Also we should drop the "Settlement" column in the MonitorTabs because the Settlement is already shown in the drop down at the top so it is just wasting screen space. The Robot tab is a good example of it not providing any benefit.

**Comment by mokun** [comment]
> Also we should drop the "Settlement" column

But will it be helpful in Command Mode or in case a person has multiple settlements under his belt and he can see all people or all vehicle or missions under one tab ?

**Comment by bevans2000** [comment]
Hmmm, interesting but we don't support that at the moment. So the drop down could show Settlement and Reporting Authorities?  It would need some reworking but not a current issue to be resolved.

**Comment by mokun** [comment]
How would you *refresh* the existing, invisible/hidden components when you decide to choose a new color theme ?

![image](https://github.com/mars-sim/mars-sim/assets/1168584/a3cd9cfd-dd3d-4491-8657-30de8d9cbd95)

By default, I start mars-sim in dark theme. So at the start, I opened the Mars Calendar and it was created in dark theme.

A few second later, I switched to the orange theme. Then I wanted to take a look at the Mars Calendar again. Unfortunately, it still stay at the old dark theme.

I notice other components also didn't get the chance to let the new theme refresh their color as well.

How do you enforce that programmatically ?

**Comment by bevans2000** [comment]
Any component that is attached to the root gets refreshed. The issue here is that the calendar is cached and only created once.
Change it so the dialog is created a fresh each time it is popped up. To be honest, caching the calendar dialog doesn't really save anything
