### ISSUE TITLE
Waste & Resource Process panels in UI are not fully utilising LAF

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#804]
**Describe the improvement**
The Waste & Resource processing panels in the Building & Settlement Unit Window is represents as a stack of JPanels. This means whilst that looks and feel like a table they act as a full panel. This means no color styling of the "rows" or selections.
Also there is a lot of repeated code across the various panels.

**Improvement **
Create a new sharable ```ResourceProcessPanel``` Component that will internally use a scrollable table to display the processes. This will also support sorting of the processes. 
The table needs to support editing so processes can be enabled/disabled. It also needs to react to when a process changes running state.

**Comment by bevans2000** [comment]
For the Settlement variant, in addition we should look to be able to jump to the Unit Details window for the Building cell. This could be made a generic "handler" as in the MonitorWindow. It could be applied to numerous table through the UI.
We could add a small "details" icon in the cells that support the linking tot he UnitWindow.
Essentially this is replicating the UnitTab logic from the MonitorWindow everywhere.

**Comment by bevans2000** [comment]
The new approach will looks something like. Note the columns can be sorted by Process or Building

![Screenshot 2023-02-20 225136](https://user-images.githubusercontent.com/20720166/220210024-5d4f78d8-e348-41e9-9e0a-38e9da86cd84.png)

**Comment by bevans2000** [comment]
@mokun I think we should also convert the Manufacturing panels (Building & Settlement) into tables as well. Having the ability to sort on the various fields is useful. Also I like the look of it being a Table 😄

**Comment by mokun** [comment]
> convert the Manufacturing panels (Building & Settlement) into tables as well.

Sure. Panels are clumsier than tables.

**Comment by bevans2000** [comment]
> > convert the Manufacturing panels (Building & Settlement) into tables as well.
> 
> Sure. Panels are clumsier than tables.
I've created a new issue #806 . It will be a squeeze to get the 2 progress bars in but I think it's possible. It might be we have to use an "X/Y" representation but I will experiment.
