### ISSUE TITLE
Standardise attributes in Unit & Tool Windows

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#808]
**Is your feature request related to a problem? Please describe.**
Many of the TabPanels have lists of labelled values in a JPanel. This use a mixture of layout sizing.
The values parts are handled as JTextFields which means they result in a drawing a large border round the text.

**Describe the solution you desire to see**
Create a new detected JPanel that will hold lists of label and content items. This will centralise the spacing and layout management across all TabPanel.
The panel will also format the label parts in Bold.

**Comment by bevans2000** [comment]
@mokun This is the last item I feel in the Improve Swing UI project. I want to centralise how we render lit of attributes which happens throughout.
The screenshot below is an example I've played with where I have applied Bold to the value labels.
![Screenshot 2023-03-03 222725](https://user-images.githubusercontent.com/20720166/222842712-ff98858c-c0d6-453d-85c3-555479a8a8e7.png)
 the whole UI.

**Comment by mokun** [comment]
That's really awesome ! Minor and gradual. But for sure good improvement.

**Comment by bevans2000** [comment]
> That's really awesome ! Minor and gradual. But for sure good improvement.

Great. Yes I like it as well. I'll roll it out on the other windows tomorrow then.

**Comment by bevans2000** [comment]
@mokun I think the restyling to use a consist and centrally controlled style is virtually complete. I like the common look and feel now. I'm sure there may still be some other area that need tweaking.
One outstanding window is the TimeWindow; this uses a mixture of fonts and colours. Do you want to keep it with a customer LaF?
I want to have a quick look at #809 as it might be novel to be able to switch the fonts specifically the size if accessibility of a user is an issue.

**Comment by mokun** [comment]
I suppose it's good to have a blue or green color for the earth time and an brown or orange color for the Mars time. 

It's good in how you want UIConfig to be in charge of all the Tool Windows such as TimeWindow to give a consistent look. 

Do you think it may be a good thing start allowing more customization such as giving color to a label down the road ?

**Comment by bevans2000** [comment]
You can see in #809 I thunk fount selection would be useful. Its a question of how far we want to go. IMHO selecting colours is too far but maybe we should look to use colours from the look and feel instead of hardcoding. 

We could calculate some custom colours based on the selection colors. But I don't really understand the best way to do logic on colors.

Probably should look to offer more LaF?

**Comment by mokun** [comment]
By the way, I notice the map on the nav tab of the Mission Tool is somehow truncated and its bottom has a gap. 

I recall we had this issue previously. It should have been a square, instead of a rectangle.

Also since we have added the mouse support, do you think we may as well remove those four elongated arrow buttons ?

**Comment by bevans2000** [comment]
I hadn't noticed but will take a look.

Yes happy to drop the points of the compass buttons. The mouse is the best way to move around. We do need a zoom feature on that panel.

**Comment by mokun** [comment]
I might have opened a ticket on adding the ability to zoom.  It's not easy to resolve.

**Comment by bevans2000** [comment]
Ok. I'll have a search for it

**Comment by mokun** [comment]
@bevans2000 

![image](https://user-images.githubusercontent.com/1168584/228150245-d4b35b05-00a4-40de-84f3-acf5ec0824e1.png)

Can we use mud orange secondary color, instead of what we have now, namely, bright red ?

Better yet is we give players the option in selecting a secondary color.

Also, the medium grey in all table column header doesn't seem to look that good because the header font color is also black. 

Can we use a DARKER TONE of the secondary color in the table column header instead ?

Corresponding, can we also change the header font color to WHITE in order to give the best contrast ?

![image](https://user-images.githubusercontent.com/1168584/228151478-d2eb8175-8920-4106-ad21-ea4143b7551f.png)

**Comment by bevans2000** [comment]
So the colour of the LAF can be selected from the Settings menu. Yes there is an Orange colour available. If you want we can make that the default; it's all in the StyleManager now.
I agree the TableHeader colour is not good; again it is calculated in the StyleManager. I think it needs to be a variant from the table selection foreground colour so it adapts.

**Comment by bevans2000** [comment]
The colour will be updated, it's a problem with the menu logic. I'll look into it

**Comment by mokun** [comment]
Thanks for the fix.

Now I have a situation when I first start a new sim, I haven't opened the Monitor Tool yet.

The default theme is Red.

I open the menu and change the theme to Dark Blue right away.

I can see the highlighted menu item in Dark Blue.

![image](https://user-images.githubusercontent.com/1168584/228661585-f525c636-2e31-4aed-81f6-6c00ea8f4ced.png)

After that, I open up the Monitor Tool.

I would expect the dark blue in Monitor Tool table.

However, it still load up in the same old default Red theme in Monitor Tool.

![image](https://user-images.githubusercontent.com/1168584/228662146-735b34c4-0498-4566-bf22-d19cd36e4747.png)

Seem we have a mixture of Red and blue theme. 

Question, does it mean that each Tool Window keeps its own theme ?

Why can't the theme change be made global ?

**Comment by bevans2000** [comment]
Let me check.

**Comment by mokun** [comment]
> Can you check that the color changes correctly once opened?

Yes. once the Monitor Tool has been opened up, changing theme works fine.

**Comment by bevans2000** [comment]
I'm pretty sure I know what the problem is. I will look into it tonight.

**Comment by mokun** [comment]
Yes. Lazy loading effectively resolve this L&F change issue.

**Comment by mokun** [comment]
Currently, the top left most is the sound control, next to it is an array of Tools buttons. 

<img width="1383" height="77" alt="Image" src="https://github.com/user-attachments/assets/122f5daa-8570-40b1-9989-9cadf5c9f79e" />

I find it it very awkward to have file related functions (the load, save and exit button, help, wiki) on the right. 

All classical applications have these buttons on the left most, you know.

So I'd like to move these functional buttons back to the left on the top menu bar, is it okay ?

**Comment by bevans2000** [comment]
Yes no problem. This issue is not really about the toolbar so I would create a fresh one.
