### ISSUE TITLE
Fonts configurable in the Ui

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#809]
**Is your feature request related to a problem? Please describe.**
The ultimate goal of the Swing Improvement project is for the styling and layout to be consistent and configurable. Colour and decoration is governed by the look and feel selection.  However the font is still hard coded.
Font selection is now governed by the ```StyleManager``` for labels, heading and sub headings.

**Describe the solution you desire to see**
The solution should be that the Font definitions should come from the ```UIConfig``` class. The ui config file will allow the various fonts to be either fully defined or adjusted, e.g. size or style.
Curently it is suggest to change the config file manually and not provide a font selection fro  the UI.

.

**Comment by mokun** [comment]
In the past, I find out the linux incarnation of mars-sim always ends up with having bigger font size than it would have been in windows or macOS. Have you noticed that ?

**Comment by bevans2000** [comment]
I noticed last night that the small labels used in the Person & Settlement Unit Window are hardcode and not derived from the default font. It may be worth creating a new dedicated Panel to hold/style these "primary properties". Then we could apply to Robot & Vehicles easily.
