### ISSUE TITLE
remove old releases of junit which are abandoned upstream and add support for junit 5 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#81]
I have been having problems with the tests getting all sorts of java null pointer exception . 

To figure out I removed the .m2/repository and forced the pom.xml's files to again call junit and saw that it called junit version 3.8.1 and junit 4.1.2 

```
~/.m2/repository/junit/junit$ ls
3.8.1  4.12
```

From junit.org and the github repo. junit 3.8.1 is nowhere to be found which means it seems to be abandoned. 

https://github.com/junit-team

While it supports 4.12 series still the last commit was in december 2014 

https://github.com/junit-team/junit4/releases

While junit 5 is the new kid on the block with flurry of releases - 

https://github.com/junit-team/junit5/releases 

I will try to figure out which of the pom.xml's call junit and see if can find out where it calls specific releases, if possible.

**Comment by mokun** [comment]
junit 5 introduces some new features and can use lambda expression from Java 8. 

Yes at some point, we'll update it to junit 5

**Comment by shirishag75** [comment]
Any update on this ?

**Comment by mokun** [comment]
@shirishag75 

Just so you know that from this [page](https://stackoverflow.com/questions/47158583/executing-junit-4-and-junit-5-tests-in-a-same-build) it explains by including vintage engine in junit5, all the previous junit 3 and junit4 test cases will continue to work under junit5.

**Comment by mokun** [comment]
@bevans2000 

We can now start writing junit5 test cases.

Which area do you think of in desperate need of it ?
