### ISSUE TITLE
Previous opened Tools should reappear when restarting the simulation

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#810]
**Is your feature request related to a problem? Please describe.**
When the simulation is restarted it does not open the tool windows that were open when it was last closed. This means the same windows have to be opened each time.

**Describe the solution you desire to see**
The UIConfig should define which windows are open at shutdown and then reopen these windows automatically at start-up.
In addition, the Tools should be configured with the same settings at shutdown, e.g. MonitorTool should have the same Settlement & Tab selected. If the Settlement does not exist; then it is handled silently.
If no windows were open; then the default windows will be opened.

**Comment by mokun** [comment]
So should the tool windows settings be saved for each particular session, or just the previous mars-sim session ?

**Comment by bevans2000** [comment]
> So should the tool windows settings be saved for each particular session, or just the previous mars-sim session ?

Not sure I understand the question. 
But I think the window states (position, open/closed, internal settings etc) should be saved in the config XML when the tool closes. Then when the next simulation runs the same layout is opened if possible. I say if possible, because a Unit may not be available if a different Simulation is run the second time.
I have a cunning plan on how to save the internal Tool & Unit windows states in an extendable fashion without polluting ```UIConfig``` with details of all the different windows classes.

**Comment by mokun** [comment]
> should be saved in the config XML when the tool closes

This means that it will load the tool window settings without discriminating which mars-sim simulation under which is saved.

**Comment by mokun** [comment]
> So should the tool windows settings be saved for each particular session, or just the previous mars-sim session ?

I suppose that once we replace the Java serialization with JSON/XML serialization, we may even consider saving the tool window positions per simulation.

For now, it makes very little difference, since the user customization of UI element is very limited.

**Comment by bevans2000** [comment]
Yes window positions will be saved independently of the simulation. I have it working now on my laptop. Just finishing saving the tool settings.

**Comment by bevans2000** [comment]
@mokun Have a look at the latest commit. I have added the ability for the Tool windows to be re-opened when a simulation restarts.
In addition the Monitor Window & Settlement Tools will also go back to the original settings, e.g. same selected Settlement and position. The Settlement Window also remembes which labels are being displayed.
I want to preserve the selected layers on the Navigation Window as well.
