### ISSUE TITLE
Use a Tree control in the Resupply window

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#824]
**Is your feature request related to a problem? Please describe.**
The Mission Tool now uses a Tree control to present the available missions replacing the double list design.
The double list design is still in use in the Resupply Tool. The 2 list represent pending and arrived supply missions.
This approach does not show which supply missions belong to which settlement.

**Describe the solution you desire to see**
The improvement should be to use a Tree control to show Resupply Missions in a tree under a Settlement parent node.
Each mission would also be decorated with an icon to indicate whether the mission is pending/in transit/arrived.

New Settlement missions will be grouped under a single "New Settlements" parent.

Off shoot from #822

**Comment by mokun** [comment]
It's true that in case of a brand new Settlement, the name may or may not be given ahead of time in the Resuuply Tool

**Comment by bevans2000** [comment]
Also for the New Settlement Mission the tool should show the components being delivered as in the Resupply Mission. Suggest a common panel to show the contents of a Transport mission based on a new interface ```TransportContent``` that can be applied to the ```SettlementTemplate``` as well as the Resupply Mission.

**Comment by mokun** [comment]
See attached screenshot below : 
![image](https://user-images.githubusercontent.com/1168584/231287871-8c9dd5ec-1b89-43ea-a601-8ca8245a000a.png)

Q1 : Shall we display the template name ? 

Q2 : Better yet, can we give player the opportunity to create its own name for each resupply mission ?

**Comment by bevans2000** [comment]
Yes, good point. I've just realised that this is the outcome of the ```toString``` method. I can change this in the renderer class.

**Comment by mokun** [comment]
May be we can give each resupply mission an unique identifier (like the unique alphanumeric id of a mission) as a part of the default name, if player doesn't want to spend time creating a name for it.
