### ISSUE TITLE
Make HistoricalEvents structured

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#827]
**Is your feature request related to a problem? Please describe.**
Events in the ```MonitorTab``` cannot be selected and used as the source of navigation to other tools similar to the unit tables. From an Event it should be possible to jump directly to the UnitWindow where the event has occurred.
The ```HistoricalEvent``` class has all the attributes as String and not Objects, e.g. ```Unit``` or ```Coordinates```.

**Describe the solution you desire to see**
The ```HistoricalEvent``` class should hold references to the ```Unit``` where the event occurred and the exact position in terms of ```Coordinates```. This will have a knock on effect to the subclasses and the calls to those Constructors.
This will have no negative impact on he memory consumption; in fact it will improve it by removing the need to create some temporary Strings.

**Comment by bevans2000** [comment]
@mokun What role does ```SimpleEvent``` play? It seems we convert all the values of a ```HistoricalEvent``` into integer lookup values into shared lists in the EventManager. I can't understand what this is saving us.
I'd like to drop SimpleEvent and just use the HistoricalEvent everywhere.

**Comment by mokun** [comment]
> @mokun What role does `SimpleEvent` play? It seems we convert all the values of a `HistoricalEvent` into integer lookup values into shared lists in the EventManager. I can't understand what this is saving us. I'd like to drop SimpleEvent and just use the HistoricalEvent everywhere.

Ok. Will we consider saving historical events into a separate JSON files instead ? 

We could generate an unique id for each simulation session when it comes to finding and loading the right JSON historical events.

I see this will be the first step toward JSON serialization.

**Comment by bevans2000** [comment]
@mokun I'm in 2 minds what to do with the ```HistoricalEvent```. I could just leave it using String values but it would not allow us to "jump" from a row in the Event table to the Mission Window or a Unit Window.
The alternative is to add more structure to the ```HistoricalEvent``` so that from any event we can display the associated Entity, could be Unit window or Resupply tool or Mission tool. This would need a trimming and consolidation of the properties of the event.  Then the question is how do we identify which Objects can be displayed in a window, this could be a Unit, Transportable or Mission as each has a dedicated tool window.

So I am thinking of adding a new interface ```Entity``` that represents any top-level Object simulated, i.e. the 3 classes described above. This interface virtually shadows the concept we have of in the ```Loggable``` interface. This new ```Entity``` interface would also be applied to the desktop & Monitor tool when finding the selectable objects & coordinates.

**Comment by mokun** [comment]
I wonder if we should start to thinking about creating data structures that can be serialized in json
