### ISSUE TITLE
DeliveryBot not in a building

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#828]
**Describe the bug**
- Excessive log statements regarding a delivery bot not being in a building

**Discuss any potential problems you have and have not ruled out**
- Out of all 10 settlements, only this particular delivery bot in Port Ares runs into this walking issue
- This delivery bot gets trapped inside a EVA Airlock and unable to get out.

**Java classes involved**
- Walk, ChargeMeta
 
**Screenshots**
It shows the bot is charging.
![image](https://user-images.githubusercontent.com/1168584/227793276-8a398811-1fcc-4c72-841d-c02c7284b081.png)

It only has one task so far.
![image](https://user-images.githubusercontent.com/1168584/227795296-e50e4b42-9625-4584-8ceb-8a33212399b1.png)

It is standing right on the inside of the inner door of that EVA Airlock.
![image](https://user-images.githubusercontent.com/1168584/227795377-bd0a3ace-9489-4be8-a37a-50b4e1570a33.png)

**Stacktrace**
```
01-Adir-01:678.894 (Info) ToggleResourceProcess : [New Boston] ERV-B 1 - Produce Polyethylene : Jesse De Jong made an attempt to toggle it on.
01-Adir-01:679.221 (Warning) ChargeMeta [x18] : [Port Ares] DeliveryBot 011 - Not in a building
01-Adir-01:679.221 (Info) ToggleResourceProcess : [New Pompeii] ERV-B 1 - Extract nitrogen compounds from regolith : RepairBot 004 made an attempt to toggle it on.
01-Adir-01:680.688 (Warning) ChargeMeta [x18] : [Port Ares] DeliveryBot 011 - Not in a building
01-Adir-01:682.164 (Warning) ChargeMeta [x18] : [Port Ares] DeliveryBot 011 - Not in a building
01-Adir-01:683.651 (Warning) ChargeMeta [x18] : [Port Ares] DeliveryBot 011 - Not in a building
01-Adir-01:684.468 (Info) AbstractVehicleMission : [Europa] Schlitten - Prepared a loading plan sourced from Europa.
01-Adir-01:684.468 (Info) TaskManager : [Europa] Elias Eriksson - Given a new task order of 'Load via EVA Regolith Prospecting #7'.
01-Adir-01:685.120 (Warning) ChargeMeta [x18] : [Port Ares] DeliveryBot 011 - Not in a building
01-Adir-01:686.629 (Warning) ChargeMeta [x18] : [Port Ares] DeliveryBot 011 - Not in a building
01-Adir-01:686.629 (Info) MissionManager : [Starcity] Damien Smith - Mission 'Ice Prospecting' probability: 0.17 base prob: 0.17 boost: 0.0 sponsor: 1.0
01-Adir-01:686.629 (Info) MissionManager : [Starcity] Damien Smith - Mission 'Regolith Prospecting' probability: 0.15 base prob: 0.15 boost: 0.0 sponsor: 1.0
```

**Specifications  (please complete the following information):**
 - build 7882

**Additional context**
- May need to manually add a list of buildings that bots cannot enter
- Is there a better way to avoid delivery bots (and other bots) from entering EVA Airlock buildings or other buildings ? 
- One exception is for repair bot to go inside any buildings for repair and maintenance

**Comment by mokun** [comment]
@bevans2000 

I actually notice this issue once in a while.

We may as well address this prior to releasing v3.5.0.

**Comment by mokun** [comment]
In addition, I also notice Delivery Bot 002 in Europa is somehow inside an inflatable greenhouse. 

![image](https://user-images.githubusercontent.com/1168584/227795536-b50f9927-7303-47f6-b631-0bed706fa1f7.png)

It has no business being there, unless it's finding a charging port. 

This turns out to be the case. 
![image](https://user-images.githubusercontent.com/1168584/227795678-28073594-8c86-4b8f-9f16-0298f87a6407.png)

I suppose we never did any path optimization for a bot. 

Walking should cost power/energy. 

It probably should not walk all the way to the greenhouse and could have waited in garage for the next charging opportunity if available.

**Comment by bevans2000** [comment]
Sure, I suggest we adopt auto-correction strategy here. When we detect the Robot is not in the Building for charging, we just move it to a different building.
I have also seen it and I think it has something to do with the initial Robot placement.

**Comment by bevans2000** [comment]
I assume you have got Java 17 working now

**Comment by bevans2000** [comment]
I found the root cause last night. The DeliveryBot has a default Building type of VEHICLE_MAINTENANCE for the initial placement. But in this settlement above; there is no Vehicle Garage so the Robot has no Building assigned.

**Comment by mokun** [comment]
I see. 

If not garage is available, it should probably be inside a command center, and then a lander hab, etc.

Can we have a hierarchy of places for each type of robot? 

Btw, it actually makes sense to create a specialized, small footprint, vehiclar EVA connecting module for the sole purpose of boarding a vehicle. 

Say, this module will need to be attached to a building on one side. The other side will have one or two ports for one or two vehicles to attach to. 

It will not have an EVA chamber because it will rely on the vehicle's EVA chamber for doing ingreess and egress.

**Comment by bevans2000** [comment]
Doesn't the Garage Building provide that already? I guess your proposal is it doesn't support Vehicle maintenance only loading. 
I do have an idea how to fix this. 
Further on however, we shouldn't create a DeliveryBot in the Settlement has no Vehicle Maintenance capability since it cannot load vehicles without one. So yes maybe there is a need for a new type of Building to support loading.

**Comment by mokun** [comment]
> Doesn't the Garage Building provide that already? I guess your proposal is it doesn't support Vehicle maintenance only loading.

I want to expand somewhat in how a vehicle can be docked with a settlement. 

Currently, a vehicle can be parked within a settlement's vicinity. It doesn't have to get inside a garage. Yet its container unit will be switched from being null to being that settlement. This is one of the most confusing part in terms of coding.

I also want to define and refine more cleanly what `Vehicle maintenance` is supposed to mean in the simulation. It can mean certain tasks such as maintaining, repairing, retrofitting, etc.

**Comment by mokun** [comment]
We should neatly define what it means for a vehicle to be externally "docked" with a building. 

The vehicle is still outside in that sense but a person can ingress into the vehicle and egress from it via its vehicular airlock.

**Comment by mokun** [comment]
>we shouldn't create a DeliveryBot in the Settlement has no Vehicle Maintenance capability

That's true.

I suppose currently a delivery bot can help with loading and unloading vehicles that have entered a garage.

Also, another important function of a delivery bot is that it can navigate drones.

Are there any other tasks you can think of ?
