### ISSUE TITLE
do we use plexus-core ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#83]
In mars-sim-core, pom.xml I see - 
```

<dependency>
			<groupId>com.phoenixst</groupId>
			<artifactId>plexus-core</artifactId>
			<version>0.9</version>
		</dependency>
```

This seems to be coming from http://plexus.sourceforge.net/  which seems to be abandoned. 

On mvnrepository.com plexus seems to be different - 

http://mvnrepository.com/search?q=plexus-core 

They seem to be owned by codehaus.org and the version is pretty different - 

```
<!-- https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-utils -->
<dependency>
    <groupId>org.codehaus.plexus</groupId>
    <artifactId>plexus-utils</artifactId>
    <version>3.1.0</version>
</dependency>
```

Maybe these are two different things altogether. I do see that the 'original' plexus gave some sort of graph usage but this seems to be different.

**Comment by mokun** [comment]
That plexus-core lib is old. Scott leaves a copy of the binary in our mars-sim's sourceforge repo.

I've tried replacing it with the modern version in the past but it didn't work.

Will come back to this in future.

**Comment by mokun** [comment]
Just removed all reliance on plexus graph. Closing this.
