### ISSUE TITLE
Can't load player-specified simulation file

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#830]
**Describe the bug**
- In the past, one can choose the eclipse launcher (the file `MarsProject -load.launch`) to load a specific simulation file. It would open a explorer-like window and ask for player to choose a file to be loaded.
- Now if a player wants to load a saved sim, it has to be called default.sim and must be in the home path root directory

**Specifications  (please complete the following information):**
 - pre-3.5.0 build 7894

**Additional context**
- MarsProject's parseArgs() should be modified to give the option of loading any saved file

**Comment by bevans2000** [comment]
Sounds reasonable but we have to cater for the headless version where there is no UI. I like using this argument approach to resume a simulation without user interaction. 
So let's add a new argument called '-resume' which starts but uses the loads the default sim without any user interaction. And the loads opens a file picker if there is no file specified

**Comment by mokun** [comment]
For the Swing UI version of mars-sim, there's two eclipse launchers for loading a saved sim :
- `MarsProject -load.launch` for loading any saved sim
- `MarsProject -load default.launch` for loading default.sim
They are in mars-sim-main submodule.

For the headless version of mars-sim, there are also two eclipse launchers for loading a saved sim :
- `MarsProjectHeadless -load or create.launch` for loading any saved sim
- `MarsProject -load or create -default.launch` for loading default.sim
They are in mars-sim-main submodule.

**Comment by mokun** [comment]
@bevans2000 

Thanks for the change. It can pop up a file chooser now for players to select a saved sim to load from.

The modality can be a tricky thing sometimes.

But when I run it, I didnt see anything, only to find out it's hiding behind the splash window and 

One thing I'll change is moving the file chooser to the top layer.

![image](https://user-images.githubusercontent.com/1168584/228959580-015939de-6e4c-4323-a581-bd34db71f459.png)

**Comment by bevans2000** [comment]
Yes give it a try
