### ISSUE TITLE
Update the Mars Sim Website

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#834]
The MarsSim website https://mars-sim.github.io/ is out of date in terms of screenshots and instructions.

Also the download should point to GitHub, not SourceForge. In addition add a link to the Wiki explaining how to run a downloaded JAR file and what the command line arguments are (this page may not exist)

**Comment by mokun** [comment]
Can we continue to keep a copy of future releases in SourceForge (SF) ? 

I actually favor using SF for keeping track of downloading mars-sim. 

It has simple built-in data analytic capability that capture what countries and what period of time the app is being downloaded. None of these are available in GitHub unless we figure out how to add these functions in future.

And perhaps it's not a bad thing to have two separate locations for downloading mars-sim.

**Comment by mokun** [comment]
> The MarsSim website https://mars-sim.github.io/ is out of date in terms of screenshots and instructions.

Yes we can put together newer screenshots.

In terms of general instructions, what would you like to add ?

For technical instructions, shall we refer them to README.md or to GitHub's wiki ?

**Comment by bevans2000** [comment]
> > The MarsSim website https://mars-sim.github.io/ is out of date in terms of screenshots and instructions.
> 
> Yes we can put together newer screenshots.
> 
> In terms of general instructions, what would you like to add ?
> 
> For technical instructions, shall we refer them to README.md or to GitHub's wiki ?

We need something to help run and start the simulation. Maybe a link to a page on the wiki explaining the command line arguments? I can do this page.

**Comment by shirishag75** [comment]
Looking forward to it.  Also maybe mention the size of the repo. so people have an idea. The last I looked, the size of the repo. was around 500 MB+ don't remember whether it was compiled  or uncompiled. It does give an idea as to how much space it would eat. Maybe one of the instructions so people know.

**Comment by mokun** [comment]
> The last I looked, the size of the repo. was around 500 MB+ don't remember whether it was compiled or uncompiled

As of today, the size of mars-sim source codes and html files is about 378 MB.

**Comment by mokun** [comment]
We could overhaul our project web page using a decent html editor that's open source.

I recommend using **Asciidoctor Editor**. 

![asciidoctor](https://user-images.githubusercontent.com/1168584/233686869-85ea84c3-0aa4-4edf-b87c-ecbdafab4cf6.png)

I found it in the Eclipse Marketplace as an eclipse plugin. 

It also has a [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode).

See [youtube](https://www.youtube.com/watch?v=Y2ODe5kqR1s) for a quick intro.

See this GitHub [page](https://eddiejaoude.github.io/book-open-source-tips/) as an example on how the formatting is easily done with least amount of effort.


Asciidoctor Editor

This eclipse plugin is a text editor for asciidoc files.

Features

Fast html preview
Easy to use, no special project setup necessary ([YouTube video](https://youtu.be/Y2ODe5kqR1s))
Can generate overview graph for bigger documents ([YouTube video](https://youtu.be/ekbYZJjN_Qw))
Uses [ASP](https://github.com/de-jcup/asp) for out-of-the-box usage (no installation of asciidoctor required) or can use installed asciidoctor with customizable CLI arguments
Can export to PDF
Code completion for pathes used in includes, images, diagrams etc. ([YouTube video](https://youtu.be/Bu_NMmVSt8M))
Supports text based diagram generation
( [ditaa](https://github.com/stathissideris/ditaa), [plantuml](https://plantuml.com/) and [graphviz](https://www.graphviz.org/)) ([YouTube video](https://youtu.be/xLbrTxxA_oI))
3 different preview modes:
Inline preview with editor
Vertical splitted
Horizontal splitted
Both variantes are immediately updated on text save
When cursor comes in line of anchor or headline it automatically scrolls internal preview to location - also opposite way, when selecting a headline in preview the editor part will be selected and shown (if not an included part...) ([YouTube video](https://youtu.be/VhTog9iwySs))
External preview
Using external Browser
Update per autorefresh in browser
time configurable
can be turned off also
Interesting when having multiple monitors and wanting to have full sized text document and preview
Provides asciidocconfig.adoc files ([YouTube video](https://youtu.be/sCQai1q_TPg), [Wiki](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Asciidoctor-configfiles))
Outline and Quickoutline
Headlines
Includes (double click opens file)
Syntax highlighting in Text Editor
Colors can be customized.
Dark theme automatic color support.
Templates + Simple code completion for existing words
Tooltips
Hyperlinking (CTRL+Mouse) and opening in IDE:
included asciidoc files
plantuml diagrams
ditaa diagrams
images
cross references ([YouTube video](https://youtu.be/Bnr2u_KTi-c))
external links
Can search for references of asciidoc files in workspace ([YouTube video](https://youtu.be/o4qu_CI-ZS0))
Convenient toolbar actions
Table wizard
Code block templates
Possibility to toggle TOC on/off in output view
Switch preview layout variant
Jump to top of preview (internal preview panel only)
Additional editors included for
.ditaa files
.plantuml files
Can convert one file or multiple files in selected folder
Formats supported:
markdown (*.md)
PlantUML editor (from Asciidoctor Editor) has many PlantUML examples (e.g. C4 diagram examples) which can be injected by toolbar action.
Can override attributes globally by preferences/from toolbar ([YouTube video](https://youtu.be/5OhWuJlMScA))
Links related to the plugin

[Issue Tracker](https://github.com/de-jcup/eclipse-asciidoctor-editor/issues)
[Release history](https://github.com/de-jcup/eclipse-asciidoctor-editor/releases)
[Wiki](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki)
[YouTube Video playlist](https://www.youtube.com/playlist?list=PLaBYAz_I_8tFByQ7EWnemjZgx7q-quDyp)
Additional links

[Asciidoctor Quickreference](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference) for details about syntax
[ditaa](https://github.com/stathissideris/ditaa)on github
[plantuml](https://plantuml.com/)
[graphviz](https://www.graphviz.org/)
Technical details

It uses internally ASP server or installed asciidoctor to provide a WYSWYG integration.
When using plantuml (or graphviz itself) you must ensure you have installed graphviz on your machine

**Comment by mokun** [comment]
It can generate html and pdf files quickly with preview and have nice default formatting with header and customizable image. 

@bevans2000 @shirishag75 

Shall we use this editor to rebuild our mars-sim project page ?

![Screenshot 2023-04-21 at 9 28 13 AM](https://user-images.githubusercontent.com/1168584/233687771-1c6e02b1-c46b-4731-8c77-7b41005c4bc7.png)

**Comment by mokun** [comment]
We can install it as our browser's [extension](https://mrduguo.github.io/asciidoctor.org/docs/editing-asciidoc-with-live-preview/).

See its original GitHub [site](https://github.com/de-jcup/eclipse-asciidoctor-editor).

Its JavaFX version is called [AsciidocFX](https://www.asciidocfx.com/). It's [here](https://github.com/asciidocfx/AsciidocFX).

**Comment by bevans2000** [comment]
Yes seems reasonable to use a better editor.

**Comment by mokun** [comment]
For a quick overview, see its project [page](https://mrduguo.github.io/asciidoctor.org/index.html).

**Comment by bevans2000** [comment]
I have been looking at something with work for WebSites, https://gohugo.io.
We should you so nothing like this which allows the pages to be markdown and then generates into a static website. Can be configured to deploy via a GitHub Action.
Also the reference docs we generate for the UI should be available online. I'm even things that the documentation should,d be a separate module in the build

**Comment by mokun** [comment]
Yes. hugo looks cool. We could use it to rebuild our mars-sim website.

**Comment by bevans2000** [comment]
I think we need a rethink. My suggestion is:

- Generated pages on Equipment and  Buildings should be copied to the website so it can be viewed outside of the game
- Current Wiki pages about how the simulation runs should be moved to the website
- The above 2 means the website can explain the simulation; these are in a new dedicated section called Simulation Logic
- The current readme.md file is too detailed. We should moved the detailed sections about development to the Wiki
- The simulation should use the new Simulation Logic section online instead of it being bundled

**Comment by bevans2000** [comment]
And yes Hugo is cool

**Comment by mokun** [comment]
See this [wiki](https://github.com/mars-sim/mars-sim/wiki/Inline-Help).

**Comment by bevans2000** [comment]
Yes I know this wiki entry.
My question is should we stop bundling the help pages into the JAR but instead host them online in the Github Pages? Who doesn't have access online these days?

**Comment by Urwumpe** [comment]
I prefer the option to have the documentation for the installed release bundled and installed offline, since it is more portable that way, e.g. I could run mars-sim on a Linux node that is physically disconnected from the internet. In my professional experience so far, the offline documentation was quite handy when having to maintain enterprise software. But you are right, in 99% of the time and geographic locations, online documentation could be the better service. 

We should need to pay attention to unsupported and supported versions in the online docs as well, like Gradle for example does with its version selector.

**Comment by mokun** [comment]
> the offline documentation was quite handy when having to maintain enterprise software

Yay. And we can talk about how to improve our inline documentation within mars-sim. 

We could improve the tutorial also.

>  pay attention to unsupported and supported versions in the online docs

Now we're on 3.7.0. So what you mean is that, say, our online docs started on 3.6.1.

The *supported* versions online are 3.6.1, 3.6.2 and 3.7.0.

But anything older than 3.6.1 (such as 3.6.0) is considered *unsupported*, right ?

**Comment by bevans2000** [comment]
@mokun I've purchased a new domain for us and configured our GitHub pages. So you can use [marssim.space](http://marssim.space)

**Comment by bevans2000** [comment]
OK, so I've been thinking about the website. Here's my thoughts:

1. Rework the GitHub pages to adopt Jekyll https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll
2. Break up the single index page into a number of section pages and use MarkDown
3. Create separate navigation sidebar, header & footer
4. Get the HelpGenerator to create pages in this style for all the Configuration Entities, e.g. vehicles, processes
5. Create a new GitHub action in the pages repo that automatically creates/replaces the generated pages

**Comment by mokun** [comment]
> GitHub pages to adopt Jekyll

Sure, we can change that. 

Currently, it's awkward and time consuming to update its content. 

We have to manually edit the index.html file and upload new pics. 

If there's a faster way to update, just like how we would update the GitHub wiki page by page, we should try.

**Comment by bevans2000** [comment]
Exactly. If we can support multiple pages then I feel most of the content about concepts in the main index.md should be to the website.

**Comment by bevans2000** [comment]
@mokun Have a look at this site. I have updated the generator so all the configurations are now web pages.
https://bevans2000.github.io/docs/features/entities/

**Comment by bevans2000** [comment]
If we go ahead with a new web site structure allowing multiple Markdown page we look to realign some of the documentation content. We have too much on the main readme.

- readme should be focused on developers and enough to get them going 
- wiki should explain the design and approach to the development, not for end users
- web site should be for end users who want to know more or those interested in the project

The majority of the current readme should be split between the web site and wiki

**Comment by bevans2000** [comment]
I've been playing with using Hugo as a better way to build a new website. It has better themes than Jekyll. I have been looking at https://www.docsy.dev/

**Comment by mokun** [comment]
So what other 'technical' materials do we want to include in our website down road ?

**Comment by bevans2000** [comment]
@mokun I have experimented with the Hugo web site generator over the Christmas break. 

I have created this new site http://hugo.marssim.space/
It's currently hosted on an S3 bucket but I like how it feels. Has separate pages defined as MarkDown and much better controls than the Jekyll pilot I did.
Responsive nature looks good; works on phone, tablet and laptop. Tell me what you think? I want to cherry pick some contents from the Wiki and add it to the website.

The source is here https://github.com/bevans2000/hugo-marssim

**Comment by mokun** [comment]
> http://hugo.marssim.space/

Somehow, this site can't be loaded on my android phone. It works on my laptop browser only.

**Comment by bevans2000** [comment]
Works fine on mine. Probably you have your phone set up secure so it won't load http sites

**Comment by bevans2000** [comment]
I'll move it to Https later

**Comment by bevans2000** [comment]
Right, try this version https://bevans2000.github.io/
I have moved it to GitHub Pages and it now automatically deploys.
This loads on my Android phone & iPhone without problem.
This is ready to go to replace the existing site.

**Comment by bevans2000** [comment]
web site has been re design to use a more modern framework allowing separate pages, navigation, Simulation definitions.
