### ISSUE TITLE
Sol label not wide enough or not updated 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#835]
**Describe the bug**
- The Sol label in the top right of the menu bar always shows `Sol : 1` in macOS
- how do we ensure it's wide enough for macOS and linux ?
- Can we ensure it has room for displaying at least 3-digit sol ? e.g. `Sol : 100` ?

**Screenshots**
![Screenshot 2023-03-31 at 10 44 42 PM](https://user-images.githubusercontent.com/1168584/229268025-6299342b-7d54-4870-85e4-86e70d8b151a.png)

**Version**
 - pre-3.5.0 build 7902

**Comment by mokun** [comment]
@bevans2000 

One reason that it happens like this is that I looks at the main windows once when it was in `Sol : 1`. 

Then I minimize the Main Window. 

16 sols later, I restore the Main Window to see how it goes.

Since the Sol label updates itself only when both it is visible and when the sol increment forward, it remains as `Sol : 1` throughout until after the millisol increment from 999 to 0 at the start of the new sol.

But on sol 17, it refreshes itself and shows `Sol : 17`.

**Comment by mokun** [comment]
The same thing just happened below : 

![Screenshot 2023-03-31 at 11 00 45 PM](https://user-images.githubusercontent.com/1168584/229268563-c6513ceb-22d6-49be-bba9-cc03eaac3b7d.png)

Last time I looked at the simulation at sol 20, even now it's sol 27. 

It doesn't refresh itself right like when I restore the Main Window.

It still shows `Sol : 20`.

**Comment by bevans2000** [comment]
It's because we only refresh the sol label when there is a new sol. I'll change it

**Comment by mokun** [comment]
The previous approach is not without merit.

It does seem like a big waste to update the sol, earth time and mars time labels when the main windows is already iconified or not visible.
