### ISSUE TITLE
Create generic Project classes

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#837]
Create the basic Project structure as per the design diagram. Then implement MineralExploration mission to use the new approach as an example. See #625

**Comment by mokun** [comment]
Does it also include breaking down the concept of `Task` into simpler components ?

**Comment by bevans2000** [comment]
> Does it also include breaking down the concept of `Task` into simpler components ?

Yes in theory but many Task are simple one phase. There I'd less repeation in Tasks compared to Missions.

**Comment by bevans2000** [comment]
I'm going to make a start on this next. I haven't thought through what the impact is on the UI/Console yet. The MissionWindow will have to be changed to be more focused on the new Interfaces instead of the concreate Mission classes.

**Comment by bevans2000** [comment]
> Sure. What new types of missions do you see we may first craft to serve as a demonstration under this new paradigm ?

I think initially try and reproduce the Mineral Exploration mission as it encompasses most of the problems. I need to make a final set of changes to the current implementation to isolate the implementation a bit more; then we can  branch out and implementation the new approach for the ```MineralExploration``` class.

**Comment by mokun** [comment]
> Stopped this work because of bug #846

Fixed in the latest [commit](https://github.com/mars-sim/mars-sim/commit/2bbc534c07e6942465c72341566015b2fc6ce17f)

**Comment by mokun** [comment]
So let me know if you run into any issues with vehicle on a mission while you're working out how to use `Project` to handle a mission.

**Comment by bevans2000** [comment]
Generic project framework created

**Comment by mokun** [comment]
Want to try #897 ?
