### ISSUE TITLE
replace jdom 1 with jdom 2 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#84]
It seems jdom 1.1.3 was ok with old versions of java i.e. java 1.2 to java 1.4 so it doesn't seem suited for java 8 or java 10/11 which will be there in due course. 

http://jdom.org/downloads/index.html

https://github.com/hunterhacker/jdom/wiki/JDOM2-Migration-Issues 

http://mvnrepository.com/artifact/org.jdom/jdom2/2.0.6

**Comment by mokun** [comment]
I'll look into adopting jdom 2 in future. For now, jdom 1 is functional and is being used for reading and writing xml files.

**Comment by mokun** [comment]
Done and closed.
