### ISSUE TITLE
Repeating Resupply Missions

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#842]
**Is your feature request related to a problem? Please describe.**
Resupply Missions are currently one offs with a fixed arrival date configured within the Scenario. Once they arrive the user has to create a new one for further resupplies.
In reality there would be a regular scheduled repeating Resupply Missions that deliver supplies at fixed periods. 
Occurred during development of #824

**Describe the solution you desire to see**
Allow the Resupply Mission definition in the Settlement Template to be specified as a repeating activity. Define the period of repeating, 12 weeks, 1 years etc. Once a repeating mission completes, the next one is scheduled for the future automatically based on the schedule period.
Also it has to be possible for a given Settlement to have multiple schedules allowing different supplies at different periods. 
The implementation should be driven by the SettlementTemplate, i.e. a given template can define what the default resupply schedule is. For example a Settlement using a template would automatically inherit the resupplies schedules of the template.
In the Scenario definition where Settlements are bound to Template it should be possible to defined whether the new Settlement uses the predefined resupplies schedules or none at all.  By default, resupplies missions would be recreated.
User can still add or cancel resupplies themselves.

**Comment by mokun** [comment]
>  a regular scheduled repeating Resupply Missions

Agreed. 

Until the settlement is able to manufacture or grow everything needed, it makes sense for mission planners to arrange for getting scheduled resupplies on resources/items that are too difficult to produce.

**Comment by mokun** [comment]
I suppose if player can edit these resupply missions and the future missions will be adjusted correspondingly. 

If that's the case, will it record the changes the player made ? 

Or is it better off forcing the player to come up with a new name ? 

Or we can make it not able to keep or reuse any old name(s) and will force the old name "Resupply Mission 1" to become "Resupply Mission 1A" by default, whenever the content of a resupply mission is altered.
