### ISSUE TITLE
Missions are driving past the NavPoint

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#846]
**Describe the bug**
After commit 39cf4c7 Vehicles do not stop at the 1st NavPoint in a Mission; they just keep driving. Also the distacne to the next nav point is never decreasing.

**Expected and unexpected behavior**
- Vehicle should stop when the 1st point is reached and start EVA

**To Reproduce (Please provide steps)**
Start a Vehicle Mission. On the 1st phase it just keep driving and doesn't stop. Eventually it runs out of fuel.
![Screenshot 2023-04-13 192809](https://user-images.githubusercontent.com/20720166/231850643-faa8d763-5214-4ddf-a08a-f0ec4b53a0e6.png)

**Screenshots**

**Comment by bevans2000** [comment]
@mokun Are you sure the calculations as I'm getting some Missions running out of Methane

**Comment by mokun** [comment]
Investigating it now.

It may have to do with the calculation of the instantaneous fuel economy or fuel consumption.

**Comment by mokun** [comment]
> I'm getting some Missions running out of Methane

I just fixed a case of divided by zero and ensuring the instantaneous fuel economy [km/kg] won't go infinite. But I don't see how this param would impact the actual methane usage.

Things look fine on my end. 

Can you take some screenshots and provide stacktrace next time when you see "running out of methane" ?

That way, I can trace it.

**Comment by mokun** [comment]
Shall we showcase all of those performance params such as fuel economy, fuel consumption, battery capacity, etc. in the `General` tab of the Vehicle Window ?

**Comment by bevans2000** [comment]
> Shall we showcase all of those performance params such as fuel economy, fuel consumption, battery capacity, etc. in the `General` tab of the Vehicle Window ?

Yes that makes sense.
