### ISSUE TITLE
Failure to compile mars-sim-core, google guice reflection issue, beryx console input cursor focus

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#85]
After reading up on http://maven.apache.org/guides/getting-started/index.html#How_do_I_compile_my_application_sources 

I started on compiling and packaging the individual components so that they are in .m2/repository (for now) . 

What I don't understand when installing why does mvn install it into /sf directory ?

just sharing the last few lines from the successful installation of mars-sim-mapdata in .m2/repository - 

```
[INFO] Installing /home/shirish/games/mars-sim/mars-sim-mapdata/target/mars-sim-mapdata-3.1.0-b2.jar to /home/shirish/.m2/repository/net/sf/mars-sim/mars-sim-mapdata/3.1.0-b2/mars-sim-mapdata-3.1.0-b2.jar
[INFO] Installing /home/shirish/games/mars-sim/mars-sim-mapdata/pom.xml to /home/shirish/.m2/repository/net/sf/mars-sim/mars-sim-mapdata/3.1.0-b2/mars-sim-mapdata-3.1.0-b2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.587 s
[INFO] Finished at: 2018-09-30T08:28:42+05:30
[INFO] ------------------------------------------------------------------------

```

After this bit was done, tried compiling mars-sim-core - 

```
~/games/mars-sim/mars-sim-core$ mvn compile 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< net.sf.mars-sim:mars-sim-core >--------------------
[INFO] Building mars-sim-core 3.1.0-b2
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from sonatype: https://oss.sonatype.org/content/repositories/releases/net/sf/mars-sim/3.1.0-b2/mars-sim-3.1.0-b2.pom
Downloading from oss.sonatype.org-snapshot: http://oss.sonatype.org/content/repositories/snapshots/net/sf/mars-sim/3.1.0-b2/mars-sim-3.1.0-b2.pom
Downloading from mars-sim: https://mars-sim.sourceforge.io/maven-repo/net/sf/mars-sim/3.1.0-b2/mars-sim-3.1.0-b2.pom
Downloading from central: https://repo.maven.apache.org/maven2/net/sf/mars-sim/3.1.0-b2/mars-sim-3.1.0-b2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.750 s
[INFO] Finished at: 2018-09-30T08:29:21+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mars-sim-core: Could not resolve dependencies for project net.sf.mars-sim:mars-sim-core:jar:3.1.0-b2: Failed to collect dependencies at net.sf.mars-sim:mars-sim-mapdata:jar:3.1.0-b2: Failed to read artifact descriptor for net.sf.mars-sim:mars-sim-mapdata:jar:3.1.0-b2: Could not transfer artifact net.sf:mars-sim:pom:3.1.0-b2 from/to sourceforge.net (scp://shell.sourceforge.net/home/project-web/mars-sim/htdocs/maven-repo): Cannot access scp://shell.sourceforge.net/home/project-web/mars-sim/htdocs/maven-repo with type default using the available connector factories: BasicRepositoryConnectorFactory: Cannot access scp://shell.sourceforge.net/home/project-web/mars-sim/htdocs/maven-repo using the registered transporter factories: WagonTransporterFactory: java.util.NoSuchElementException
[ERROR]       role: org.apache.maven.wagon.Wagon
[ERROR]   roleHint: scp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

It seems at at least from the first glance that the mars-sim-core still tries to find stuff from sourceforge.net which it shouldn't  and instead should have tried to use  /home/shirish/games/mars-sim/mars-sim-mapdata/target/mars-sim-mapdata-3.1.0-b2.jar instead of trying for a remote resource.

**Comment by mokun** [comment]
@shirishag75 , 

You mention you are using the `compile` argument as in `mvn compile`.

To me, I always use `clean package install`.

See step 3 in [(E). Building mars-sim for distribution](https://github.com/mars-sim/mars-sim/wiki/Setting-Up-Eclipse-IDE-with-Git).

I wonder if you need to `clean` out the old stuff first.

**Comment by shirishag75** [comment]
I tried doing mvn cean 

> @shirishag75 ,
> 
> > I started on compiling and packaging the individual components...
> > ~/games/mars-sim/mars-sim-core$ mvn compile
> 
> You mention you are using the `compile` argument as in `mvn compile` on each individual submodule.
> 
> To me, I always use all 3 arguments together `clean package install` in the base directory `mars-sim` (NOT on each individual submodule) to create and package all the jars needed in ONE SHOT.
> 
> May be in your case, you can do this
> 
> > ~/games/mars-sim$ mvn clean package install
> 
> No need to reinvent the wheel in that case.
> 
> See the Development Environment wiki in step 2 and step 3 of [(E). Building mars-sim for distribution](https://github.com/mars-sim/mars-sim/wiki/Setting-Up-Eclipse-IDE-with-Git).
> 
> I also wonder if you need to `clean` out the old stuff first.

The way I do it is - 

my mars-sim-master is always pristine. Whenever you do an update, I just pull the update from there. 

```
$ git-info

## Remote URLs:

origin	https://github.com/mars-sim/mars-sim.git (fetch)
origin	https://github.com/mars-sim/mars-sim.git (push)

## Remote Branches:

  origin/3.1.0-b1
  origin/HEAD -> origin/master
  origin/master

## Local Branches:

* master

## Most Recent Commit:

commit 846478ded31f1c706f81cde6a21be92163c26f7a
Author: mokun <mannykung@gmail.com>

    Enable 2 ai tasks for Repairbots

Type 'git log' for more commits, or 'git show <commit id>' for full commit details.

## Configuration (.git/config):

user.name=shirish agarwal
user.email=shirishag75@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/mars-sim/mars-sim.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

**Comment by mokun** [comment]
As you can see below in your stack trace : 

> testGetCurrentConstructionStage(org.mars_sim.msp.core.structure.construction.ConstructionSiteTest)  Time elapsed: 0.002 sec  <<< ERROR!
> java.lang.NullPointerException
> 	at org.mars_sim.msp.core.structure.Settlement.updateAllAssociatedPeople(Settlement.java:1881)
> 

If you go to line 1881 in Settlement.java, you will see the following codes : 
```
	/**
	 * Updates all people associated with this settlement
	 * 
	 * @return collection of associated people.
	 */
	public Collection<Person> updateAllAssociatedPeople() {

		// using java 8 stream
		Collection<Person> result = unitManager.getPeople().stream().filter(p -> p.getAssociatedSettlement() == this)
				.collect(Collectors.toList());

		allAssociatedPeople = result;
		justReloadedPeople = false;
		return result;
	}
```

It seems something in the Java 8 Stream API has changed.

I have Java 10.0.2 installed but you're using openjdk 11

When I try switching it to openjdk11 last week, it throws a number of errors (other than the JavaFX related ones). Some seems to have to do with the new Stream API syntax.

I'll need to do some research on this.

I didn't bother to set up a separate branch for Java 8 in the past.

Perhaps now it's better off for us to set up a separate branch for Java 11 or openjdk/openjfx 11, apart from the Java 9 master branch.

**Comment by mokun** [comment]
I've been using JDK 10 for compiling mars-sim. But I do compile the source codes at Java 9 level, not Java 10.

My Eclipse IDE has compatibility issues with Java 11. Even for the latest Eclipse version 4.9 just released.

It's possible that after the issues are resolved, we don't have to set up a separate branch.

**Comment by mokun** [comment]
> but the last option of exiting the simulation doesn't work if you wait too long to make a decision.

When you say "doesn't work", do you mean the terminal is frozen... ?

By the way, saving the simulation actually takes a couple seconds to enact, depending on the speed of your cpu.

So I'll need to somehow pause the menu at that period of time to prevent anyone from choosing any options at all.

**Comment by shirishag75** [comment]
Reply in-line :-

> > but the last option of exiting the simulation doesn't work if you wait too long to make a decision.
> 
> When you say "doesn't work", do you mean the terminal is frozen... ?
> 

The terminal is not frozen but doesn't accept any input at all. I can see the cursor blink but that's about it. 

> By the way, saving the simulation actually takes a couple seconds to enact, depending on the speed of your cpu.
> 
> So I'll need to somehow pause the menu at that period of time to prevent anyone from choosing any options at all.

The issue is at - 

```
2018-10-01T21:51:34.3 (Info) Simulation : Saving as default.sim...
2018-10-01T21:51:37.3 (Info) Simulation : Done saving. The simulation resumes.
```

**Comment by mokun** [comment]
Can you see the scroll bar on the right ? I can see you didn't scroll the new terminal all the way to the bottom. 

The two terminals are independent of each other. Each run on its own thread.

**Comment by shirishag75** [comment]
I just ran a new instance, I did the scroll the new terminal all the way to the bottom. In the amount of time it took to scroll, I am unable to stop/exit the simulation. 

Btw I have expanded my answer for somethings which you might think of adding as another text boxes before starting the simulation. We don't seem to also have any budgeting info. on the simulation as well.

**Comment by mokun** [comment]
Can you see the blinking cursor ? Can you input any number ?

I've just updated the code for inserting the line separator to hopefully make it work better for linux.

Will compile a new binary for test later today.

**Comment by mokun** [comment]
> The commander astronaut/cosmonaut doesn't know how many other people are in the settlement and their roles.

The default number of settlers is based on the settlement template phase.

Will add the ability to see and change later.
 
> S(he) doesn't know how many buildings s(he) has, the number of technologies s(he) has at her disposal, number of vehicles etc.

The design of the mars-sim is that each settlement template phase define all these.
 
> Are there or would there be any options of getting more supplies from near-earth/near-mars vehicles till the settlement is self-sufficient .

Will add the ability to see and change later.
 
> Communications within the colony itself and off-world

Can you draft up a brand new project on how communication is made between settlement and earth and other off-world colonies ? 

Once we put together the specs in it, we can begin coding it and building a model of how it works.

> I dunno if the game/simulation is nation-state based. If yes, if roles and nationalities, names can be changed for the gamer's preference and if any inherent advantages/disadvantages it might be for the choices the user needs/wants to make.

Yes. The user has the option of selecting the country and its space agency.

**Comment by mokun** [comment]
@shirishag75, let's start a new thread/issue that focuses the discussion on adding/tweaking the features for the interactive console.

**Comment by shirishag75** [comment]
> Can you see the blinking cursor on the right next to the end of the line `Enter your choice:` ?
> 
> Can you input any number by any chance ?
> 
> Note that the cursor has to do exactly at that particular position in order to input a number.
> 
> That's why I'm asking the developer of Text-io for help to see if there's anyway to fixate the position of the cursor. See [beryx/text-io#16](https://github.com/beryx/text-io/issues/16).
> 
> Also, I've just updated the code for inserting the line separator to hopefully make it work better for linux.
> 
> Will compile a new binary for test later today.

Sure. AFA being able to put a new number at the very last, if I'm fast yes, if I'm not fast then no. As I shared before, there needs to be some sort of pause or conditional statement put before the simulation begins OR some sort of interrupt although dunno if that would be possible. 

For sure, will start a new thread on the other items.

**Comment by mokun** [comment]
The author of [text-io](https://github.com/beryx/text-io/issues/16) just released an update to address the focus issue of the input cursor.

**Comment by mokun** [comment]
No longer applied. Closed.

**Comment by shirishag75** [comment]
This is still an issue. I think a workaround is needed. Because still it says at the beginning - 

```
~/games/mars-sim$ mvn package -e -X
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-3-amd64", arch: "amd64", family: "unix"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
