### ISSUE TITLE
Group and separate resource processes and migrate some from ERV-B to ERV-C

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#851]
**Is your feature request related to a problem? Please describe.**
- There are too many resource processes taking place in ERV-B.
- We can group them into various categories and separate them apart.
- We can move them into ERV-C.

**Describe the solution you desire to see**
- Create ERV-C for handling industrial chemical-related processes.
- Continue to use ERV-B for handling regolith/ore/mineral related processes.

**Describe alternatives you've considered**
- In the long run, we may consider making resource processes *independent of* the buildings. Rather, they are dependent upon specific types of replaceable industrial equipment package that are designed to handle certain resource processes. 
- These specific equipment package can be installed on any buildings, such as Lander Hab, Outpost Hab, Manufacturing Hab, etc. to provide various resource processing capabilities.

**Describe the rationale**
- Need to provide clarity to players in finding specific resource processes that are supported by an ERV.

**Screenshots**

**Specifications  (please complete the following information):**
 - pre-3.6.0 build 7949
 
**Extra**
- Add a tree control structure to present resources processes in the Process tab of a Building Window.

**Comment by mokun** [comment]
@bevans2000 

After I made the commit, the ERV-C works well. 

However, somehow none of vehicle svg files are being properly loaded in Settlement Map. I have no idea why.

Can you take a look to see what went wrong ? 

Appreciate !

**Comment by bevans2000** [comment]
Very odd. Yes I can take a look.

**Comment by mokun** [comment]
Btw, can we at runtime assign an enum value to each vehicle/building type, instead of matching strings ?

**Comment by bevans2000** [comment]
> Btw, can we at runtime assign an enum value for each vehicle/building type, instead of matching strings ?

There is already a VehicleType enum but not correctly used. The method getVehicleTypeString is bad so I'll sort it out. We need to rework how Vehicles are created because there is some confusing logic converting from name to VehicleType. Vehicles should be created from a VehicleSpec from which the VehicleType is defined. This will allow different specs for the same type of Vehicle. The same as we have for Robots. I have created #854 

As for Buildings, we should not have a fixed BuildingType because Buildings should be expandable. For Building the composite Functions are the important parts.

**Comment by bevans2000** [comment]
@mokun Which editor are you using to create the SVG images? I want to create a SVG image for the 2nd variant of Explorer Rover as part of #854

**Comment by mokun** [comment]
> Which editor are you using to create the SVG images?

I use inkscape.org

I've wanted to find another one that's faster and intuitive.

Let me know if you come across another open source editor that's decent enough for use.
