### ISSUE TITLE
Map not stretchable in Mission Tool's Navigation Tab

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#852]
**Describe the bug**
- In Mission Tool's Navigation Tab, the map cannot be stretched horizontally.
- If player hovers over the right edge of the Mission Tool and drag out the window panel horizontally, the map will have a black background appended to it. 

**Expected and unexpected behavior**
- The map should stay the same size when the Mission Tool window panel is being resized.

**Java classes involved**
- MissionWindow, NavpointPanel

**Screenshots**
![image](https://user-images.githubusercontent.com/1168584/232253321-353dea9d-c843-4819-aac7-f20440e80ed3.png)

**Specifications**
- pre-3.6.0 build 7949

**Additional context**
- Preferably, the map should be zoomable and scrollable.

**Comment by mokun** [comment]
@bevans2000 

![image](https://user-images.githubusercontent.com/1168584/232939272-0a64b4dc-97c7-401b-9509-1ce9b8f8c220.png)

**Comment by bevans2000** [comment]
The MapPanel is fixed size which is the problem. No idea why it is fixed size. Originally the Mission Window was fixed size as well so the problem never occurred. I can look into removing the fixed size of the Map Panel.

**Comment by mokun** [comment]
>  I can look into removing the fixed size of the Map Panel

I bet the current implementation of how each pixel is grabbed and placed to assemble the map would make it very hard to change how the whole map is being rendered.

**Comment by mokun** [comment]
By the way, the current resolution for the 3 map jpg files is only 2888 by 1440.

![image](https://user-images.githubusercontent.com/1168584/234712016-c2fa9217-46ec-4bc8-823e-361e4af0600e.png)

I already tried a few times to swap them out by a higher resolution 5776 x 2880. This would have been 4x the total number of pixels. 

But there's no one straight-forward the formula in mars-sim that we can instantly change in order to make the these 3 flat jpg maps to be
1. First projected onto a spherical surface correctly. 
2. Next, upon being assembled as a sphere
3. At last, it needs to be projected again onto a 300 by 300 flat surface to be displayed. 

It's easy for some pixels at the equator to go through the above 3 steps of transformation to be placed correctly. But it's a lot harder for pixels at the north or south pole to be unskretched and reskretched correctly.

See the basic idea [here](https://desktop.arcgis.com/en/arcmap/latest/map/projections/about-map-projections.htm).

```
/**
 * Surface map data.
 */
public class SurfaceMapData extends IntegerMapData {

	/**
	 * Constructor
	 */
	public SurfaceMapData() {
		super(SURFACE_MAP_FILE);
	}
}
```
Currently `IntegerMapData` in mars-sim-mapdata submodule is the class that allows these transformations to take place correctly.

**Comment by mokun** [comment]
Btw, the term **equirectangular projection** described how those 3 jpg maps are being pre-made. 

We may need to convert those parameters in `IntegerMapData`, so that we can use more advance projection techniques.

See the definition of those standard parameters below that's based on the [equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection) page :
![image](https://user-images.githubusercontent.com/1168584/234716102-642082af-f4aa-47b5-9bc8-52199ba99348.png)

In comparison, we have a scattered number of params as follows : 
```java
/**
  * A map that uses integer data stored in files to represent colors.
  */
 abstract class IntegerMapData implements MapData {

 	// Static members.
 	private static Logger logger = Logger.getLogger(IntegerMapData.class.getName());

	protected static final String SURFACE_MAP_FILE = "/maps/surface2880x1440.jpg"; // 2880x1440, 5760x2880
	protected static final String TOPO_MAP_FILE = "/maps/topo2880x1440.jpg";
	protected static final String GEO_MAP_FILE = "/maps/geologyMOLA2880x1440.jpg";

 	public static final int MAP_BOX_WIDTH = MapDataUtil.GLOBE_BOX_WIDTH;
 	public static final int MAP_BOX_HEIGHT = MapDataUtil.GLOBE_BOX_HEIGHT;
 	
 	public static final int MAP_WIDTH = MapDataUtil.MAP_WIDTH; 
 	public static final int MAP_HEIGHT = MapDataUtil.MAP_HEIGHT; 
 	
 	public static final double FACTOR = 1;
 	
// 	public static final double HALF_MAP_ANGLE = .48587D;
 	public static final double PIXEL_RHO = MAP_HEIGHT / Math.PI;
 	private static final double TWO_PI = Math.PI * 2D;
 	
 	private static final double PHI_ITERATION_PADDING = 1.26 * MapDataUtil.RATIO; // Derived from testing.
 	private static final double PHI_PADDING = 1.46 * MapDataUtil.RATIO; // Derived from testing.	
 	private static final double PHI_ITERATION_ANGLE = Math.PI / (MAP_HEIGHT / FACTOR * PHI_ITERATION_PADDING);
 	private static final double PHI_RANGE = Math.PI * PHI_PADDING * MAP_BOX_HEIGHT / MAP_HEIGHT * FACTOR;

 	private static final double THETA_ITERATION_PADDING = 1.46 * MapDataUtil.RATIO; // Derived from testing.
 	private static final double MIN_THETA_PADDING = 1.02 * MapDataUtil.RATIO; // Theta padding, derived from testing.
 	
 	private static final double PI_RATIO = TWO_PI * MAP_BOX_WIDTH / MAP_WIDTH * FACTOR;
	// Note : Polar cap phi values must display 2 PI theta range. 
 	private static final double POLAR_CAP_RANGE_1 = Math.PI / 6.54D; // derived from testing
 	private static final double POLAR_CAP_RANGE_2 = Math.PI - POLAR_CAP_RANGE_1;
 	private static final double MIN_THETA_DISPLAY = PI_RATIO * MIN_THETA_PADDING;
		
 	private static final double THETA_ITERATION_FACTOR = MAP_WIDTH / FACTOR * THETA_ITERATION_PADDING;
 	
 	// Data members.
 	private int[][] pixels = null;
```

Note that the 1.26, 1.46, 1.02 are being derived from experimental runtime testing and very unfortunately, they are only good for 2888 by 1440 pixel jpg maps.

They must be changed if higher resolution 5776 x 2880 pixel maps are being deployed.

**Comment by bevans2000** [comment]
I did have a quick look at this. The problem is everything is hard coded with constants. The visible map size has to come top down from the map panel and be passed as arguments. I think it can be changed but it's a big work. 

Secondly the mapdata is loaded into memory so if we use a bigger resolution it will consume more memory. So for any change we need to address that as well. 
At the moment not being able to zoom is a big disadvantage.

Short term we can change the layout so the map panel does not stretch.

**Comment by mokun** [comment]
Yea there are multiple issues to resolve.

To me, I'd like to figure out how to load higher resolution of maps. In this case , I'd need to find the relationship and the value of those parameters when the map pixels have changed.

Then next, I'd like to find out how to load the surface map by tiles.

Also, I'd like to compressand how to load higher resolution of height.elevation data set.

**Comment by bevans2000** [comment]
After having another look I think we can do something. I'm turning my focus to #837 the next few days but can help if you want.

I would look to:

1. Remove the MAP_WIDTH & MAP_HEIGHT from MapUtil and have the data width & height stored as fields in the IntegerMapData class. This will support the future of different resolutions.
2. I would pass in the the required width & height of the image to the ```MapData.getMapImage``` method. Obviously from the calling MapLayer class the values would still be fixed to the window size but we are pushing the constraint up the stack.
3. Then the clever part. I would change the logic in ```IntegerMapData.getMapImage``` to use the map data coordinate  frame instead of the Map. First transpose the centerPhi, centerThi, width & height into the bounding rectangle on the underlying map data, e.g. x,y,w,h. Then loading the image becomes a straight forward case of iterating through the mapdata according to the bounding box and creating the colour for each element.
4. The advantage is that if we have a bounding rectangle in the map data coordinate frame it will be possible to load that from tiles instead of a single double array 😄 . The ```IntegerMapData.findRectPosition``` method already has the calculations to convert from one coordinate frame to the other.

Then going forward, it should be possible to change the requested image size (w,h) based on the size of the panel. It should also be possible to support a zoom as well. The IntegerMapData would need a resolution field of the loaded mapdata and the getMapImage would passed the requested resolution; the 2 resolutions could produce a scaling ratio that is used in the calculation of the bounding rectangle and an aggregation on creating the color item, i.e. multiple map data values will contribute to a single Color value.

**Comment by bevans2000** [comment]
Also I would delete the ```TopoMapData```, ```SurfaceMapData``` & ```GeologyMapData``` classes and create the ```IntegerMapData``` classes direct in the map data factory. Move the constants of the map file location into the factory classes as well since this will allow us to drive this from a property file if we have different map resolutions.

So for example a MapData class could be a Facade to multiple MapData object that each have a different resolution. Depending upon the resolution requested in the ```getMapImage``` method it could chose which is the best underlying data to use.

**Comment by mokun** [comment]
I've just figured out how to load a different resolution of map now. 

Will upload a higher resolution 5760x2880 surface map, topo map and geo map as a ref.

Next is to allow the flexibility of having maps having various resolutions to be automatically detected and to remove those as much those hard coded params as possible.

**Comment by bevans2000** [comment]
How  are you handling the extra memory consumption that higher resolution requires? Have you removed the constants so different maps can have different resolutions ?

**Comment by mokun** [comment]
> How are you handling the extra memory consumption that higher resolution requires? 

Like you said, we will for sure progress to the point of loading only the portion of map data that will be viewed at a given time, without having to load the entire image. 

But this will entail making more drastic changes.

For now, the step one is removing the previous limitation of loading only 2880x1440 resolution of map.

**Comment by mokun** [comment]
I'm committed the change that made it possible to switch to higher resolution of maps.

Can you help out with removing the redundancy of having `SurfaceMapData`, etc. and stick with using only `IntegerMapData` for all 5 types of map ?

```java
/**
 * Surface map data.
 */
public class SurfaceMapData extends IntegerMapData {

	/**
	 * Constructor
	 */
	public SurfaceMapData() {
		super(SURFACE_MAP_FILE);
	}
}
```

Note that I haven't fully added all the new class to load the other 2 brand new maps. That's because they won't be needed once you made the change to how `IntegerMapData` can be handled.

**Comment by mokun** [comment]
See https://github.com/mars-sim/mars-sim/issues/26 and https://github.com/mars-sim/mars-sim/discussions/441 for related discussions.

**Comment by bevans2000** [comment]
Ok I can have a go. Are we going to make the changes to the getMapImage method?

**Comment by bevans2000** [comment]
This code is a bit spaghetti, there are constants in the map data package that define the UI size. I will improve the coupling.

**Comment by mokun** [comment]
> Are we going to make the changes to the getMapImage method?

I'll rather let you go head and modify it the way you envision.

**Comment by mokun** [comment]
> there are constants in the map data packagethat define the UI size. 

The initial size of the UI map box seems needed for calculation. But may be you can figure out a better way to calculate the placement of pixels.

**Comment by bevans2000** [comment]
What needs doing is to remove the hardcoded values. I will:

1. Create width, height & RTO fields on the MapData class. This will allow us to load different Maps at different resolutions
2. Change the getMapImage method to be data driven instead of the hardcoded constants
3. Move the panel size constant into the UI classes and pass the required image size to the MapData class
4. Slowly transform the users of the fixed constants to be data driven from the MapData being displayed. In particular RHO should always come from the MapPanel. This will make the zoom feature easier to add.

Also, since you changed the resolution the Mission Create screen not creating nav points correctly; they appear offset. I suspect there is some "magic logic" somewhere that assumes a specific resolution.

**Comment by bevans2000** [comment]
Can you explain what the ```IntegerMapData.LOWER_EDGE``` represents? I can't understand what it is doing or what it represents? It causing me a headache.

**Comment by mokun** [comment]
Mathematically speaking, `LOW_EDGE` simply means the following : 

```java
 	public static final int LOW_EDGE = HALF_MAP - MAP_BOX_HEIGHT / 2;
```

It's being used very often when I need to calculate the point or coordinate with this method called findRectPosition().

Because the flat jpg map is a distorted 2-D map, any given points in a 2-D map must be converted back to a coordinate on a sphere. 

However, we don't stop there. This point on a sphere (namely a coordinates on the surface of a sphere) must subsequently be re-converted back to a pair of rectangular coordinates which is where findRectPosition() comes in to make it happen.
 
Interestingly, we have two variants of this method : one in IntegerMapData for returning `Point` while the other one in Coordinates for returning `IntPoint`.

**Comment by bevans2000** [comment]
OK, I'll can handle it by having it as a property of the ```MapData```
I've made some changes to the mapping approach but on a branch as it might break things. Jump on the branch and have a look.

**Comment by bevans2000** [comment]
@mokun I've removed the constants now from ```IntegerMapData``` and converted the code so it is data driven from the loaded map. To prove this I have changed the resolution of the Geo map. This shows that the map rendering is driven from the underlying mapdata details and not any hard coded values. So it seems to work OK when the maps have different resolutions.
It should be possible now to allow the MapPanel to change size and then implement zooming at the ```Map``` layer as getScale is a method on the ```Map``` class. At the moment it directly returns the scale of the underlying data but it could apply a modifier.
The changes are still on a branch. I've created a Pull Request if you want to take it onto the main branch or test it on the branch.

**Comment by bevans2000** [comment]
You made some conflicting changes on the master branch so I've have to merge your changes in. That will take a while so I'll do it tomorrow. Tell me once you're done changing the maps and I'll do it in one go.

**Comment by mokun** [comment]
> Tell me once you're done changing the maps and I'll do it in one go.

Oh I didn't go here and read what you did and committed the changes .

Now the best is that I don't touch it until you fully implemented what you have.

**Comment by mokun** [comment]
All I did was piecing together the codes for choosing those 2 new brand new map types in Mars Navigator.

**Comment by mokun** [comment]
So this approach of scaling (on a map type) would require having at least the two jpgs, one higher resolution and one lower resolution, right?

So since we have 5 map types, it would means 10 jpg files, right? 

One was going to say thatnid we pick one pixel and dump 1 adjacent pixel next to it, then we can also effectively reduce the resolution or down-scale it by half.

But upscalimg one step it is may be allowed but it would be blurry.

**Comment by mokun** [comment]
So in this alternate approach, i may simply define a map scale level.

When it's at level 1, it's the original resolution.
At level 0, it's up scale once.
At level 2, it down scale once.
At level 3, it down scale twice.
At level 4, it down scales 3x.

We may need a cutoff at certain scale.

**Comment by bevans2000** [comment]
> All I did was piecing together the codes for choosing those 2 new brand new map types in Mars Navigator.

It's no problem. I've merge it in.

**Comment by bevans2000** [comment]
> So in this alternate approach, i may simply define a map scale level.
> 
> When it's at level 1, it's the original resolution. At level 0, it's up scale once. At level 2, it down scale once. At level 3, it down scale twice. At level 4, it down scales 3x.
> 
> We may need a cutoff at certain scale.

I still think the best approach is tiles with a high resolution then we can load them from file when needed and not keep the whole date in memory. Then with very high resolution source we can average the pixels up to give a zooming feature. What's the highest resolution source image you can get? 
Maybe have different levels of zoom for different maps as well.

**Comment by mokun** [comment]
Yes this alt approach deals with scaling only and is compatible with tiles.

Tiles reading is just segmented reading of a large  area.

**Comment by bevans2000** [comment]
> Yes this alt approach deals with scaling only and is compatible with tiles.
> 
> Tiles reading is just segmented reading of a large area.
> 
> I have a link to 8 big tiles of the entire Mars surface. Will posit it here.
> 
> May be we can format and use user's machine or 'user directory' to save these tiles, instead of keeping them in the memory.
> 
> I suppose this is how google map does on our computer.

Exactly, we probably need use more than 8 tiles so each isn't too large but I see it as we do a new class implementing the MapData  interface that has tiles.

**Comment by mokun** [comment]
Yes I suppose this alt approach deals with scaling only but it's also compatible with file tiles reading.

Tiles reading is almost like segmented reading of a large area and its purpose is to reduce the memory footprint of reading and keeping the whole image alive in memory.

EDIT : I have a link to 8 big tiles of the entire Mars surface [here](https://www.mars.asu.edu/data/mdim_color/). It's based on MDIM 1.0 standard only.

One of the latest map I added recently that's called "viking map" is sharper because it was processed and produced using MDIM 2.1

May be the next step is to format and use user's machine .mars-sim to keep the map bits as tile files after reading a certain whole geofence area. This way after I quit mars-sim today and I run it again in another session, it will read directly from .mars-sim and don't have to read from the image file.

This way it would allow the flexibility for future mars-sim to direct players to choose from a higher resolution map posted online, instead of using the low resolution map bundled with mars-sim.

I suppose google map caches what it reads somewhere in our computer.

**Comment by mokun** [comment]
May be the next step is to format and use user's machine `.mars-sim` to keep the map bits as tile files after reading a certain whole geofence area. 

Then if I quit mars-sim today and run it again in another session, it will read directly from `.mars-sim` and don't have to read from the image file.

This way it would allow the flexibility for future mars-sim to direct players to choose from a higher resolution map posted online, instead of restricting everyone to use the low resolution map bundled with mars-sim.

I suppose google map caches what it reads somewhere in our computer, right ?

**Comment by mokun** [comment]
Q: How would you "shrink" the resolution of a ma[ ? Namely, what algorithm would you use to effectively "reduce" the number of pixels of a map consistently ?

Say I have a high resolution 4000z2000 pixels map, out of that, I should be able to produce a 2000x1000 map, a 1000x500 map, and a 500x250 map, right ?

Is this how we create a map scale and add the ability to zoom in and out of a map ?
