### ISSUE TITLE
Switch to methanol as fuel for vehicles

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#853]
As a follow-on from this [discussion](https://github.com/mars-sim/mars-sim/discussions/609), it makes sense for mars-sim to go ahead with adopting the use of methanol (instead of methane) as the default fuel for transportation.

But methane will continue to serve its purpose in building heating and electricity generation as needed, alongside with the nuclear and the solar options.

**Comment by mokun** [comment]
There are issues with the acceleration and deceleration of vehicles.

As a result, currently it rarely consume any fuels. 

I'll need to lay out all the cases in startinga nd stopping a vehicles tomorrow again and rework all the relevant methods.

**Comment by bevans2000** [comment]
Have you thought of defining the vehicle fuel type in the VehicleSpec? Essentially the ```VehicleController``` represents the engine/power unit of a Vehicle and hence it could be subclassed according to the type of fuel allowing custom calculations for different fuel types.
For example, if we added a nuclear powered vehicle it would not working in the current design.

**Comment by mokun** [comment]
> if we added a nuclear powered vehicle it would not working in the current design.

Good point ! Say if it uses radioisotopes to power the rover, as some have suggested this approach, then VehicleSpec would be a good place to return what fuel it uses. I'll make some changes.

**Comment by bevans2000** [comment]
Essentially the VehicleController become VehicleEngine and we could subclass it for the different fuel types. This would allow us to have different calculations depending upon the fuel type.

**Comment by mokun** [comment]
Done !

> Essentially the VehicleController become VehicleEngine and we could subclass it for the different fuel types. 

Sure. We can even define fuel type in vehicles.xml.

> This would allow us to have different calculations depending upon the fuel type.

Now my question is, what kinds of vehicle do you have in mind and also their applications ?

**Comment by mokun** [comment]
I'll be adding a new attribute called `power-source` in vehicles.xml.

**Comment by bevans2000** [comment]
I assume power-source would drive a different type of VehicleController that would define a different fuel type.
Big question is what would happen if you add a nuclear source and there was no need for a fuel type how would the cope could with a null fuel type?

**Comment by mokun** [comment]
> what would happen if you add a nuclear source 

Yay I'm adding that and a few other options

> and there was no need for a fuel type how would the cope could with a null fuel type?

That would require more code change in VehicleController. 

Ideally speaking, in case of a fission nuclear reactor, it still consumes uranium. 

I've heard they put, say 70 kg of uranium oxide in a 10kW kilopower reactor. And that much would be good for 7 to 10 years. 

But to account for that, I'll need to find out how much kg it would consume per frame, it would be very very minimal. 

We'll need to do more changes doing some sort of a BLOCK retrieval of uranium.

But for now, we may just skip that tracking.

**Comment by mokun** [comment]
I found the following interesting info : 

- 1 kg of uranium oxide fuel can produce around 49,600 kWh of electricity, according to ScienceDirect Topics and YourQuickInfo.
- However, Lemielleux.com and Lisbdnet.com state that 1 kg of natural uranium corresponds to nearly 10,000 kg of mineral oil or 14,000 kg of coal and enables the generation of 45,000 kWh of electricity.
- Uranium-235 contains two to three million times the energy equivalent of oil or coal,

**Comment by Urwumpe** [comment]
It depends first of all on how much enriched it is, HEU has far more power content. Next, it depends on the burn down that you can achieve in a reactor. Older PWR can produce power from about percent enriched by burning it down to 1.9%, modern PWR can burn the same fuel down to 0.9%, lower is possible.

Of course, a smaller reactor has much more neutron leakage than a bigger one, which means it can run with slightly higher enriched fuel than larger reactor, without turning into a potential or poor nuclear bomb.

Fun fact: About 2/3 of the known Uranium reserves have lower energy content in their ore than coal, meaning you must mine more ore to get the same energy out of the fuel rods. But its at least low CO2 (unless you use Diesel engines and must use a lot of fuel to move one ton)

**Comment by mokun** [comment]
> It depends first of all on how much enriched

**Comment by mokun** [comment]
> It depends first of all on how much enriched 

Yes. That's true about how enriched it is. 

In principle, we could model harvesting and process uranium oxide (UO) on Mars. 

This should requires no less than a new processing facility or building with equipment and part capable of refining UO into whatever grade. 

Then we can have our little nuclear reactors keep track of how much UO is consumed. 

If not, UO will need to be imported from Earth or Moon.

Just beware of the outcome of playing with fire and if we are not careful, Chernobyl disaster can happen there :D 

We should probably start a new one on UO.

I'm closing this thread now.

**Comment by mokun** [comment]
@Urwumpe 

Would you advocate bringing back the traditional idea of the hydrogen fuel cell back to the fold and may be even bringing its sister [hydrogen combustion](https://www.youtube.com/watch?v=1Ajq46qHp0c) along for a ride !?

My idea is that the future of Martian transportation system shouldn't be betting on just one single technological portfolio, or else colonists may create a single point of failure if not careful.

**Comment by Urwumpe** [comment]
@mokun 

Depends. As fixed choice? Not really, poor energy density, even worse performance, we again need to bring our own oxygen. Not fun. Also, the ICE version has lubrication and overheating issues, which is a major challenge for engine designers, and all big German construction machine manufacturers and their engine suppliers work hard on that. A compromise with a LNG/methane engine with increased hydrogen portion in the fuel is an attractive compromise.

If you can allow customizing rovers, why not. Its a rather poor choice, but hydrogen is available and a less optimal machine is often better than no machine at all. So it might make sense for a base rich in hydrogen, but strangely little methane to go that way.

 But then, we could also allow madness like Chlorine Triflouride:

> It is, of course, extremely toxic, but that's the least of the problem. It is hypergolic with every known fuel, and so rapidly hypergolic that no ignition delay has ever been measured. It is also hypergolic with such things as cloth, wood, and test engineers, not to mention asbestos, sand, and water—with which it reacts explosively. It can be kept in some of the ordinary structural metals—steel, copper, aluminum, etc.—because of the formation of a thin film of insoluble metal fluoride that protects the bulk of the metal, just as the invisible coat of oxide on aluminum keeps it from burning up in the atmosphere. If, however, this coat is melted or scrubbed off, and has no chance to reform, the operator is confronted with the problem of coping with a metal-fluorine fire. For dealing with this situation, I have always recommended a good pair of running shoes.
