### ISSUE TITLE
Allow different Vehicle variants

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#854]
**Is your feature request related to a problem? Please describe.**
Currently the constructor of vehicles is defined by the text vehicle description. This is fragile and open to mist typing.
To expand, we need to support different models of the same vehicle type, e.g. same pattern as Robot/RobotSpec.

**Describe the solution you desire to see**
To solve this Vehicle constructor should be based on ```VehicleSpec```. The latter will have a new property defining the VehicleType of this specification. This will make Vehicle construction a little more involving needing a VehicleSpec so a new factory class will be created to help, e.g. similar to ```EquipmentFactory```. 

As a by product the ```Vehicle.getVehicleTypeString``` method will be removed.

**Comment by bevans2000** [comment]
There is an impact of #306 of this change.
The ```VehicleGood``` class uses the resource id of the ```VehicleSpec``` by using the associated ```VehicleType```. The current allocation scheme makes space for only 10 different VehicleGood objects. But if we fully implement this change we could more than 10 different VehicleSpecs. 
Options are:

1. The VehicleGood implementation may have to be changed to be based on VehicleType instead of VehicleSpec and hence the allocation range is fixed.
2. Each different VehicleSpec is mapped to a dedicated VehicleGood and the allocation is made wider than 10 with a safety check in the code
3. Implement #306 which allows more VehicleGood identifiers to be allocated

I think the best option is 1 in the short term but go to option 3 as part of #306.

**Comment by mokun** [comment]
Sure. 

I'll leave that change to you.

Meanwhile, I'll fix the acceleration issue and it should do only minimal changes to Vehicle, VehicleController, OperateVehicle, etc.

**Comment by bevans2000** [comment]
I'm working on a branch so I'll pick up the changes at the end with a merge.

**Comment by mokun** [comment]
Sure. Btw, I have in mind creating what's called Modular Equipment Paclage (MEP)

They are swappable mission modules on vehicle.

But it will take time to test and install on each vehicle during mission preparation and/or under any long term stretegies dictated by player under Commander Dashboard.

Each mission should have a customized set of equipment and instrument and settlers will need to be trained and have skills or cerification I'm using them to run experiments and collect samples, etc.

**Comment by mokun** [comment]
@bevans2000 

I'll about to make the two equipment, namely, Battery Modules and Fuel Cell stack, pluggable or modular for each vehicle.

But I'll wait for your refactoring done on the Vehicle and VehicleSpec to avoid conflicts.

**Comment by bevans2000** [comment]
Ok. But I'm on holiday in France so won't be making any changes until next week so if you want go ahead, make your changes.

**Comment by bevans2000** [comment]
I've noticed that we keep a lot of readonly copies of variables in a ```Vehicle``` that are coming from ```VehicleSpec```. It would be better to reference them directly in the VehicleSpec, e.g. width, height, num of battery models.
