### ISSUE TITLE
Goals and interaction on the console. 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#86]
While right now mars journey is more of a fantasy thing and we do not know how our body will cope with exposure to long-term less gravity as experienced here on Earth, from what little I know it long-term exposure to mars would be detrimental for us. 

https://exploratorium.edu/ronh/weight/

Also mars colonizations will be multi-decade or multi-generation effort to have a settlement on Mars. 

For the immediate part we would need to have focused short-term objectives that we would need to complete and long-term objectives. 

The first team/s would probably be smaller number of people and lot more robotics/automation to help keep things moving. 

I don't know if during or after play would there be ways of offering tips to a given situation ?

At the very least, food, creation of food (which means a greenhouse) .  repair, supplies for say 3 months or something for starters. 

If we would have a permanent hovering spacecraft above the martian atmosphere then astronauts can exchange schedules, get weather reports on sandstorms etc. and choose when to do farming, science or enlarging the area for human habitation and maybe even tourist activities to earn supplies etc.  Facetime or equivalent interviews to world press detailing off-world adventures. 

We also would need to think of having some sort of perimeter for safety purposes and making sure that the perimeter is up at all the times, just to be on the safe side. 

We would also need ways to share and interpret per person bodily functions, mood swings, stress issues etc. 

While I don't know in reality, but at least twice data dumps could probably sent from mars to the spacecraft and from there on to earth and vice-versa. Over years all the technologies as far as data sending is concerned, compression etc. would be good.  This might be automated but is something that either the commander needs to sign off .

At the end even if one journey ends in a disaster, the work will continue as a new commander and crew can take off from where the old team left off. 

I have more, but this should be enough for starters :)

A big part of such a thing is making sure that the budgets for years works out which will be tricky politically, how do our astronauts deal with that and deal with all the PR double-talking as well as share both the risks (to themselves) and the science they hope to gain out of it.

**Comment by mokun** [comment]
Wow @shirishag75 ! This is totally beyond just making existing core features available to the console. You have surely just tossed out a lot of great ideas altogether above.

Do you mind creating a project for each one of them one by one over time ? 

This way, we can keep track of the modeling and coding work and discuss further on how we plan to implement them and any roadblocks we will encounter.

For each feature, we'll first evaluate where we are at. Then we'll write out the prerequisites, the requirements, the specifications, etc. in detail.

**Comment by shirishag75** [comment]
I would rather leave to your capable hands to design project goals and be happy with just creating bug-reports which might influence you to think of the models that need designing. To give a simple example, having a reporter on-board may be a double-edged sword as a reporter would have his own agenda, the same goes for every role.  For instance, a biologist may argue his role is most important than the engineer's and vice-versa so possibility of ego clashes and just living in close proximity to each other without much of a social change is going to hamper our first batch of Martians.  See https://en.wikipedia.org/wiki/MARS-500#Psychological_effects and there have been quite a few.

**Comment by mokun** [comment]
We have the following 4 types of bases at the start of the simulation : 
```
Mars Direct Base (Phase 1)
Mars Direct Base (Phase 2)
Mars Direct Base (Phase 3)
Alpha Base (Phase 4)
```

Before SpaceX created the idea of BFR, it's assumed that a Mars Descent Vehicle would be reasonably designed to accommodate between 4-8 people.

Alpha Base has 24 people. It has 3 Lander Hab. 

So it would suggest having 3 separate descent vehicles landed over some period of time and each mission would be carrying 8 people.

Another way to look at it is that each phase of the settlement is in fact a "scenario" that you start with.

Also, at some point in future, we will start to account for the dry mass of the vehicle and the total weight of the payload (the people onboard and the equipment and the part and resources, etc.)

**Comment by mokun** [comment]
Just added a new wiki page on [Settlement Templates](https://github.com/mars-sim/mars-sim/wiki/Settlement-Templates).

I'll say yes that we can add a lot more meaningful content than what we have now. 

In real life, There's a lot of things that can happen in the everyday life of a group of people in a settlement.

It's both a matter of precisely defining what we are setting out to do and then meticulously implementing the details.

**Comment by mokun** [comment]
>  as a reporter would have his own agenda... a biologist may argue his role is most important than the engineer's and vice-versa so possibility of ego clashes and just living in close proximity to each other without much of a social change 

@shirishag75 , you are suggesting some complex scenarios as to how settlers interact with one another. It will take time to think through how we may come up with an abstract model of this kind of interaction and exchange between two individuals or within a group setting and how we can implement and program in an Object Oriented Programming environment.

For now, we do have a working modeling of [Relationship](https://github.com/mars-sim/mars-sim/wiki/Relationship), the subject of which I just put together a wiki page on it. 

For now, it's simply defined as the permutation score between two individuals. e.g. Score of (A, B)

**Comment by shirishag75** [comment]
I have seen both the Settlement Templates and the Relationship meter table and both seem good enough. 

The only thing I would suggest is make project 10 more narrowly focused rather than having everything under project 10. 

To be more clear, it would be better to have  Settlement Templates as Project 11 and Relationship as Project 12 as both are bound to grow and become complex. 

Having different projects and having them depend on each other will reduce complexity and help keep project 10 lean so that we do not miss out any important bits. 

If possible have a jar so I can see what you have been playing with recentish so I could comment further.

**Comment by mokun** [comment]
A lot of interesting ideas are being tossed out in this thread. Let's define and spell out the requirements one at time in detail in future. Closing this for now.
