### ISSUE TITLE
Separately download and install elevation data and map data type

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#867]
**Is your feature request related to a problem? Please describe.**
- Currently, the mars-sim app is bundled with a very low resolution elevation data set. It's only 4 pixel per degree (PPD) in resolution and is 2 MB in size. The next step up is a 16 PPD data set and is 32 MB in size.
> EDIT :
> - From time to time, a rover cannot find a route to go and get stuck in going home or going to a destination. 
> - This happens as the slope angle becomes too high for the vehicle to maneuver or to climb. 
> - This is attributed to the fact that low resolution of elevation data set is being used that can cause an abrupt jump from, say, 0 km to 3 km, in an instant.

**Describe the rationale**
- It provides higher fidelity in modeling and better flexibility to end users when the use of various resolutions of the elevation and map data sets are being offered.
- It will help keep the core mar-sim package lean in size.
- It is more manageable in development when the offering of mars-sim app and extra data sets are separate.

**Describe the solution you desire to see**
- Prepare a few additional jars with different resolution of elevation data and map data. 
- Create a menu option for managing and choosing a different elevation and map data set.
- When running the core mars-sim program, it will check on the default location in `.mars-sim` to see if at least one an elevation data set and one map data set exist in the local machine. 
- If available, it will proceed to start mars-sim, if not available, it will direct the player to download and install a data set separately.

**Describe alternatives you've considered**
- Bundle a higher resolution elevation and map data sets together with the core mars-sim app. The entire package will no longer be **portable**.
- This would invariably create a barrier in some remote part of the world in downloading a large program and timeout would occurs.

**Specifications**
 - v3.5.0

**Additional context**
- See recent [commit](https://github.com/mars-sim/mars-sim/commit/f73e4f777858a922144ad3c9a89c01bd85690f47) in testing the use of a 16 PPD elevation data set.
> EDIT :
> - Need to look into some scenarios in which the waypoint destination is, say, in the middle of crater, the vehicle may not be able to find a route to go down. 
> - The same can also happen if a settlement happens to be at a very low or high elevation spot. It will take a lot of energy to climb up to a peak or climb out of a valley.

**Comment by bevans2000** [comment]
So the main surface map we would have a higher resolution and the other a lower resolution? It will work now we made the MapData change yesterday. Does the terrain logic use the same map data?

I think everything has to be bundled into the one jar file.  But it would not be difficult to bundle a zipped version and unzip them to the filesystem automatically and then read the unzipped from the local disc.

**Comment by bevans2000** [comment]
I see the real problem as the amount of memory the larger dataset will consume. Could we hold the terrain data as shortint instead  of integer? Consumes half the space

**Comment by mokun** [comment]
I just modified/added more words regarding the situation (See under `EDIT`) on why a higher resolution elevation data set is better.

**Comment by mokun** [comment]
> Does the terrain logic use the same map data?

No. Currently, it uses a separate img file for elevation data.

Intuitively speaking, the topo map should give away the height. 

However, I have a hard time convert the color scheme to the actual height. 

I've asked this question in this long [thread](https://github.com/mars-sim/mars-sim/issues/225) in how one can set up the Digital Elevation Model (DEM) in mars-sim since the topo map uses it. It seems too complicated to be put into use.

So currently in Mars Navigator, the status bar reports two different height values. 

One is using the data provide by the MEGDR img file, while the other one is the use of the color of a pixel to determine the height. 

However, the second height value can be quite *off* from the first height value. Those handcrafted methods that I came up with are fully accurate, as discussed in that thread.

**Comment by mokun** [comment]
>  see the real problem as the amount of memory the larger dataset will consume. 

This is true. Currently, for 4 PPD, we have 1440 x 720 data points. It's a total of 1036800 ints staying in the memory.

The next resolution is 16 PPD (no 8 PPD data set somehow). This will be 2880 x 1400 points. It will be a 16x (since it's 4 times 4) jump in data points and memory space.

**Comment by mokun** [comment]
> Could we hold the terrain data as shortint instead of integer? Consumes half the space

I'm not sure. Each height value can range from -5 km to 8km. The range is too big for a short int, I think.

But there are compression scheme out there for compressing int array. I've tried it using a maven artifact called `JavaFastPFOR` in `MEGDRMapReader` class. The result is not as good. May be I haven't set it up correctly.

The thing is that the following method is read in every frame in TerrainElevation : 

```java
	/**
	 * Returns the elevation in km at the given location, based on MOLA's dataset.
	 *
	 * @param phi
	 * @param theta
	 * @return the elevation at the location (in km)
	 */
	public static double getMOLAElevation(double phi, double theta) {
		return mapDataUtil.getElevationInt(phi, theta)/1000.0;
	}
```

It in turns read getElevationInt() in MapDataUtil in every frame : 

```java
  /**
 	 * Gets the elevation as an integer at a given location.
 	 * 
 	 * @param phi   the phi location.
 	 * @param theta the theta location.
 	 * @return the elevation as an integer.
 	 */
 	public int getElevationInt(double phi, double theta)
```

At the end, getElevationInt() would read the elevation int array multiple times in every frame. Very high access. 

I suppose if we can reduce the frequency of reading this array, if all these calls came from the same settlement and the settlement itself is not going anywhere ! 

If it has to do with the vehicle on a mission, then it can be potentially be moved to a different elevation and it will be needed.

**Comment by mokun** [comment]
I just double checked. It said the following : 
> The minimum and maximum topography observations for the entire data set are -8068 and 21134 meters.

So it's from -8 k to 20 km. It's about 30,000 unique value. May be we have remapped it to a 2^15. 

A 15-bit lot for each height will suffice, if we want it.

**Comment by mokun** [comment]
> So currently in Mars Navigator, the status bar reports two different height values.

> One is using the data provide by the MEGDR img file, while the other one is the use of the color of a pixel to determine the height.

See the discrepancy between the two height values below : 

![image](https://user-images.githubusercontent.com/1168584/235343461-ef33dce1-06eb-44e9-9004-4210e20772d7.png)

**Comment by bevans2000** [comment]
I think this is a standalone change that will allow us to the surface images files as compressed files into the JAR (via the resources folder). We can then automatically uncompress them to the local filesystem automatically.
This has the advance:

- Reduces the size of the JAR file to download and then run in the JVM
- Image access will be faster because the image data will not be bundled into the JAR file.

**Comment by bevans2000** [comment]
Just had a look and this is quite easy. We could host the raw mapdata image files in a different location in our Git repo and then use the raw url as a reference, for example [Mars Global Map](https://raw.githubusercontent.com/mars-sim/mars-sim/master/mars-sim-mapdata/src/main/resources/maps/(geo)Mars_Global_Geology_Mariner9_12ppd.jpg)
 Introduce a ```FileDownloadHelper``` class that will cache them on the local filesystem; if not present it will download the file from Github. This would need a centralised properties file to allow the URL to be defined.
The flaw is we would have to tag it to a specific branch, always the master for example.
However, for the elevation data (MEGDR) we are still loading in a massive array into memory. The short array comes sequentially off the file so why not find the elevation directly from the file by seeking directly to the correct offset? We could put a cache in front so previously found elevations can be reused.
My guess is only 1% of the elevation data loaded is used by the simulation.

**Comment by mokun** [comment]
> We could put a cache in front so previously found elevations can be reused.

But one question is how worthy is it to set up `Map<Coordinates, Double> elevation` for caching elevation data ?

Since our latitude and longitude is now in 4 decimal places,

Say 
at (0.0010 N, 0.0010 S), elevation is 0 km.
at (0.0011 N, 0.0010 S), elevation is 0 km.
at (0.0012 N, 0.0010 S), elevation is 0 km.
at (0.0013 N, 0.0010 S), elevation is 0 km.
at (0.0014 N, 0.0010 S), elevation is 0 km.
at (0.0015 N, 0.0010 S), elevation is 0 km.

Finally,
at (0.0016 N, 0.0010 S), elevation is 0.1 km.
at (0.0017 N, 0.0010 S), elevation is 0.1 km.
at (0.0018 N, 0.0010 S), elevation is 0.1 km.
at (0.0019 N, 0.0010 S), elevation is 0.1 km.
at (0.0020 N, 0.0010 S), elevation is 0.1 km.

Would it be an overkill to cache tens of thousands of `Map<Coordinates, Double> elevation` this way to just read a simple double value of elevation ?

**Comment by bevans2000** [comment]
I agree  but I'm suggesting only caching the  coordinates that are needed, I.e load them on demand. But probably if we need a single x,y then load and cache all the elevations for a surrounding box.

**Comment by mokun** [comment]
Currently, in `Unit`, we have
```java
	/** The unit's location tag. */
	private LocationTag tag;

	/** The last pulse applied */
	private long lastPulse = 0;

	/** Unit location coordinates. */
	private Coordinates location;

	protected LocationStateType currentStateType;

	/**
	 * Gets the unit's location.
	 *
	 * @return the unit's location
	 */
	public Coordinates getCoordinates() {
		return location;
	}

	/**
	 * Sets unit's location coordinates.
	 *
	 * @param newLocation the new location of the unit
	 */
	public void setCoordinates(Coordinates newLocation) {
		location = newLocation;
		fireUnitUpdate(UnitEventType.LOCATION_EVENT, newLocation);
	}
```

See below that there are so many methods that calls on `getCoordinates()`. Does it need to keep its own 
`location`, especially when it's inside a container unit ?

I see that any units are inside a settlement, then, it shouldn't need to do extra calling to get the elevation. 

In general, if an unit is within another unit, then its elevation should be that of the container unit.

The only exception is when its parent is null or MarsSurface.

![image](https://user-images.githubusercontent.com/1168584/237056354-66fda99b-9976-4d10-aa13-403213ceeb84.png)

**Comment by mokun** [comment]
I also want to simplify those methods in `LocationTag`. They look very inefficient and complicated.
 
May be we can make use of  enum class `LocationStateType` more ?!?

**Comment by mokun** [comment]
So if an unit is within another unit, then we should simply set location to null.

And this will greatly simplify things. Only a parent unit should call setCoordinates() when it moves. 

e.g. when a vehicle moves.

![image](https://user-images.githubusercontent.com/1168584/237063015-8e9994c9-c77c-4dee-b2c9-7c8da0e70a06.png)

**Comment by mokun** [comment]
@bevans2000 

I just sort of "cache* the calling of computing elevation in this [commit](https://github.com/mars-sim/mars-sim/commit/a801ab67eacb1e342437165be0ef6060090a78f6).

If an unit in the settlement, then it won't need to go all the way to calling MapDataUtil's getElevation() to recompute the elevation.

It would simply read the stored elevation value of that settlement.

**Comment by bevans2000** [comment]
> So if an unit is within another unit, then we should simply set location to null.
> 
> And this will greatly simplify things. Only a parent unit should call setCoordinates() when it moves.
> 
> e.g. For a vehicle, when it moves, call adjustSpeed() and haltVehicle() will call setCoordinates().
> 
> There is no need to call setCoordinates() otherwise.
> 

Totally agree. I said this in 2021 that getCoordinates should always come from it's parent. You have to update the coordinate of a Unit in the transfer method when the new container is MarsSurface; it needs to be set to the coordinates of it's old parent it is leaving.

https://github.com/mars-sim/mars-sim/issues/329#issuecomment-845411997

**Comment by bevans2000** [comment]
> I also want to simplify those methods in `LocationTag`. They look very inefficient and complicated.
> 
> May be we can make use of enum class `LocationStateType` more ?!?

Personally I think LocationTag is confusing and over complex. The state type can be derived by looking at what type of Unit and the type of it's parent Unit.  For example, if the parent is of type MarsSurface then the stateTyp is always ON_SURFACE.

**Comment by mokun** [comment]
> Personally I think LocationTag is confusing and over complex.

**Comment by bevans2000** [comment]
> So it's better we set the coordinates of an unit to null when it's slaved after its parent.
> 
I think the coordinate doesn't need to be null; we can just leave it because we know it will be ingored.

> > You have to update the coordinate of a Unit in the transfer method when the new container is MarsSurface; it needs to be set to the coordinates of it's old parent it is leaving.
> 
> Ok, say a vehicle goes on a mission and leaves a settlement, the location of vehicle will be set momentarily to its settlement. Then as it starts to move, it will keep setting its coordinates to a new set of value.

The same case exists when a Person starts an EVA; they transfer to the MarsSurface and need to have their own coordinate field correctly set.

**Comment by bevans2000** [comment]
I've changed the code so it is downloading the map data (images & elevation) direct from guthub when the simulation runs and caches them. It works well but there ae 2 problems:

1. The UI pauses when it has to download the any file the first time. I need to change the ```MapPanel``` so it is asynchronous for the image loading. This is actually better way to run it
2. The significant problem is the mapdata is needed for terrain but it's needed for UnitTest; hence the UnitTests have to download the terrain data which is not good practice.

**Comment by bevans2000** [comment]
Making the map loading asynchronous is possible but is it worth it because it is only needed the first time a new map type is shown per installation.

**Comment by mokun** [comment]
> The same case exists when a Person starts an EVA; they transfer to the MarsSurface and need to have their own coordinate field correctly set.

I thought about what happened during EVA.

The person's location and its EVA suit's location should be either that of the vehicle of origin or settlement of origin. 

That's because we assume the person won't travel far by foot.

**Comment by mokun** [comment]
> The significant problem is the mapdata is needed for terrain but it's needed for UnitTest; hence the UnitTests have to download the terrain data which is not good practice.

Well, we could always make mars-sim bundle with a low resolution of map. 

Say it will always come with 2800x1400 maps, as in the old days.

**Comment by mokun** [comment]
> Can we give the player the choice by asking...

Now that we talk about this, I suppose the best practice is to create a main menu page in swing. 

This way, player can see what maps are bundled, what maps have been downloaded to player's local home folder and will be available.

**Comment by bevans2000** [comment]
I like that idea. Means we will have to make the available map types be data driven instead instead of being hardcoded in the code but that is a lot easier than making the MapPanel asynchronous. 
Yes I will work on that. The Filelocator can look on the classpath first and if not found can download it. When selecting the map type that has not been downloaded the user can be prompted to confirm the wait for the download.

**Comment by bevans2000** [comment]
This is proving a big change. I didn't realised that the Globe & the MapPanel use different images to represent the same Map type and they are totally unlinked. And to make matters worse the image files are held in 2 different locations. I am going to move them into the mapdata module.  
Once done it will be better and totally data driven so don't make any change to the map area in the UI please.
But long term I don't see the mapdata module being any use; we should consider moving it into the UI and moving the MEDGReader into the core module for the terrain.

**Comment by bevans2000** [comment]
@mokun Phew, done it.

The latest commit b39242c on this branch makes the map logic totally data driven. The types of maps available via the ```mapdata.properties``` file. Do you want to give it a try by building on the branch? The large maps file will be downloaded automatically from GitHub and cached on the local file system. It seems to be working OK and the code is much cleaner.
I have had to standardise which icons and colours are used on the different maps. To do this I've introduced the concept of "isColourful" map which in a generic way means different colours are used wiithout having to specialise the layers & display units.

I've had to take out the terrain calculations based on the RGB values. This doesn't seem to provide anything significant for the user as the terrain data is already available.

I need to clean the code to delete the RGB code and I need to update the Wiki to explain how to add new map types.

**Comment by mokun** [comment]
I have wanted to make the globe and surface maps in Mars Navigator 
(1). becoming larger (beyond 300 x 300), this increasimg the cosmetic value 
(2). Having more features loaded, thus improving the utility value in, for instance, the daily to daily mission planning for player commander 

The changes made recently makes it a lot easier for us to finally make (1) a realty.. 

So now we are almost onto (2), we ought to ask harder questions such as
A. Why do we need Mars Navigator in the first place ?
B. What concrete value can or should Mars Navigator provide to the daily settlement development ?
C. Can we have one integrated tool for mission planning, observation of logistics, settlement development ? 

Currently we have Mission Tool that use the surface map. Then the settlement map is totally unrelated.

**Comment by mokun** [comment]
> I've had to take out the terrain calculations based on the RGB values. This doesn't seem to provide anything significant for the user as the terrain data is already available.

Yes it's not being used for height determination anymore. 

But I'd like to reuse the RGB calculation would be useful in analyzing mineral content in near future. Doing so will make mineral or prospecting more scientifically based, removing speculation and randomness.

**Comment by bevans2000** [comment]
I like the Settlement Tool, yes it doesn't provide a massuve functional benefit but gives an element of realism to the simulation. Plus it looks good 😀
But let's move the discussion about that tool a different issue.
Have you tried using this branch version? I will try and clean it up tonight

**Comment by bevans2000** [comment]
> 
> But I'd like to reuse the RGB calculation would be useful in analyzing mineral content in near future. Doing so will make mineral or prospecting more scientifically based, removing speculation and randomness.

Ok but that's a different use case. We should change the MineralMap implementation to use an image instead if you want that. It could use the same downloading approach but where would you get the map source from?

**Comment by mokun** [comment]
Never mind. I just figured out how to check out another branch.

Yes I can see the followings : 

```
01-Adir-01:054.603 (Info) IntegerMapData : Loaded /maps/Orange_blended_surface_height_region_names_5760.jpg with pixels 5760x2880.
01-Adir-01:054.977 (Info) FileLocator : Extracting from resources /maps/surface600.jpg -> C:\Users\mkhelios\.mars-sim\downloads\maps\surface600.jpg
```

**Comment by mokun** [comment]
Yes I can see the following in stacktrace : 

```
...
2023-05-11T21:45:07.9 (Info) FileLocator : Content URL changed to https://raw.githubusercontent.com/mars-sim/mars-sim/download_issue867/content
...
01-Adir-01:000.000 (Info) FileLocator : Downloading https://raw.githubusercontent.com/mars-sim/mars-sim/download_issue867/content/maps/megt90n000eb.img -> C:\Users\mkhelios\.mars-sim\downloads\maps\megt90n000eb.img
...
01-Adir-01:010.084 (Warning) MainDesktopPane : Perserved Unit cannot be found
01-Adir-01:011.314 (Info) FileLocator : Downloading https://raw.githubusercontent.com/mars-sim/mars-sim/download_issue867/content/maps/Orange_blended_surface_height_region_names_5760.jpg -> C:\Users\mkhelios\.mars-sim\downloads\maps\Orange_blended_surface_height_region_names_5760.jpg
01-Adir-01:018.984 (Info) IntegerMapData : Loaded /maps/Orange_blended_surface_height_region_names_5760.jpg with pixels 5760x2880.
01-Adir-01:019.777 (Warning) MainDesktopPane : Perserved Unit cannot be found
01-Adir-01:019.777 (Config) MarsProject : Finish processing MarsProject.
01-Adir-01:026.765 (Severe) UnitManager$SettlementTask : Problem with pulse on Teslapolis : Invalid range
...

01-Adir-01:054.603 (Info) IntegerMapData : Loaded /maps/Orange_blended_surface_height_region_names_5760.jpg with pixels 5760x2880.
01-Adir-01:054.977 (Info) FileLocator : Extracting from resources /maps/surface600.jpg -> C:\Users\mkhelios\.mars-sim\downloads\maps\surface600.jpg
```

**Comment by mokun** [comment]
Yes 3 file have been successfully downloaded to a new directory called `.mars-sim/downlaods/maps` : 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/d6228a68-d818-46a0-94f7-edad6e9e7eb8)

It takes very little time for me to download since mine is 300 Mb connection. 

But for remote places it would take longer to download that large height data set, `megt90n000eb.img`, which is 32 MB.

So we could go back to bundling with only the smaller height data set, namely, `megt90n000cb.img` which is only 1.97 MB.

We can use swing to do a pop up asking if player is interested in downloading that next level of resolution file.

**Comment by mokun** [comment]
> Placed in the content/maps under the top level of the repo; then they are downloaded

So how do you upload files there ? 🤔

**Comment by bevans2000** [comment]
Just move the files into the content folder it git and do a commit like normal.
