### ISSUE TITLE
Add a locale combobox in Mars Navigator 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#878]
**Is your feature request related to a problem? Please describe.**
- Currently player needs to drag around the globe to find a specific location 
- Obviously, the first missing feature one should add to Mars Navigator is pinpointing known kocations

**Describe the solution you desire to see**
- Add a combobox with all known settlement
- Next, add landmarks and historic places
- In future, add custom regions or terrain of interest that has high resolution and may require download of new maps

**Describe the rationale**
- it's more intuitive to take a player to a known location with combobox choice

**Specifications  (please complete the following information):**
 - pre-3.6.0 build version 8053
 
**Additional context**
- Allow player to define/customize the default or HOME location for the rest button next to the lat and lon combobox

**Comment by bevans2000** [comment]
Can we close this now? The combo seems to work

**Comment by mokun** [comment]
Still fixing some conflicting issues. 

It should only allow choosing either inputting lat and lon and click on go, or to choose a settlement from its combobox.
