### ISSUE TITLE
info on roles & jobs and how they affect the mission, console window

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#88]
At least on the console/headless version you do not know the cost of the choices you make. From what I have read, there usually is some sort of team selection committee who along with the commander would make choices for who should be in the initial team. 

Right now we don't have enough info. to base our choices on. The choices are - 

0. Architect 
1. Aerologist 
2. Astronomer (wouldn't all the team members be Astronomers, what would be different about her/im ?)
3. Biologist 
4. Botanist ( isn't/shouldn't there be interdisciplinary applicants, perhaps a biologist-botanist combo for instance.) 
5. Chef 
6. Chemist 
7. Doctor 
8. Driver 
9. Engineer 
10. Mathematician 
11. Meteorologist (this person could be on the way station/spacecraft above Mars hovering.)
12.  Physicist 
13. Reporter 
14. Technician 
15. Trader

All in all, 16 roles, some more urgent than others in the initial attempts for sure. 

https://www.skyandtelescope.com/astronomy-news/some-plants-grow-well-in-martian-soil/

**Comment by mokun** [comment]
In that Jobs wiki, I just added the concept of calculating the `Job Prospect` in mars-sim.

> At least on the console/headless version you do not know the cost of the choices you make. From what I have read, there usually is some sort of team selection committee who along with the commander would make choices for who should be in the initial team.

We can certainly refine how a settler is being selected for a job. 

At the start of a simulation, every settler is a clean slate.

As you know, programmers typically use a pseudo random generator to define various attributes of a person.

The good thing is that there is a lot of characteristics of a person in mars-sim that meet our eyes. For instance, each person has a set of skills, attributes, preferences, favorites, personalities, etc.

So no two persons are the same.

**Comment by shirishag75** [comment]
that should somehow be revealed in the console. AFAIK there isn't a way to know the stats. and characteristics of a character on the console, is there currently ?

**Comment by mokun** [comment]
not on console yet.

there's a chat window in the GUI mode. 

working on bringing the ability of chat to the console.

**Comment by mokun** [comment]
In this latest [build](https://github.com/mars-sim/mars-sim/commit/33b5552a78c86a98614e7cd0720d469e797756af), I added a new option called "Chat with a party" in the console menu.

Will refine it some more and show it to you.

**Comment by mokun** [comment]
You can now see the roster list of people with their job and roles in the console mode. 

One thing I'd like to point out is that a person's job actually affect the initial role that would be assigned to him. 

See [Role wiki](https://github.com/mars-sim/mars-sim/wiki/Role).

**Comment by shirishag75** [comment]
I saw that, just need a release at some point to see that in action :)

**Comment by mokun** [comment]
The [last commit](https://github.com/mars-sim/mars-sim/commit/4c5afb48a51d27aaf90fac8418cd31402447ef2a) just refined how the job prospect will impact the settlement need of a job.
