### ISSUE TITLE
Concurrent exception during container consolidation

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#883]
**Describe the bug**
- It's not reliable for bots to execute consolidation task

**Expected and unexpected behavior**
- Bots do not need to perform this task unless being told to do so

**Discuss any potential problems you have and have not ruled out**
- The `equipmentSet` in the line below within the for loop somehow triggers this `ConcurrentModificationException` :

```java
	/**
	 * Finds all of the containers (excluding EVA suit).
	 *
	 * @return collection of containers or empty collection if none.
	 */
	@Override
	public Collection<Container> findAllContainers() {
		Collection<Container> result = new HashSet<>();
		for (Equipment e : equipmentSet) {
			if (e != null && e instanceof Container) {
				result.add((Container)e);
			}
		}
		return result;
	}
```

**Java classes involved**
- EquipmentInventory, ConsolidateContainers

**Stacktrace**
```
01-Adir-05:919.876 (Warning) Equipment [x4] : [New Boston] EVA Suit 178 - Could not be stored into Sojourner II'.
01-Adir-05:919.876 (Severe) UnitManager$SettlementTask : Problem with pulse on New Boston: null
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1579)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1602)
	at org.mars_sim.msp.core.equipment.EquipmentInventory.findAllContainers(EquipmentInventory.java:112)
	at org.mars_sim.msp.core.structure.Settlement.findAllContainers(Settlement.java:2228)
	at org.mars_sim.msp.core.person.ai.task.ConsolidateContainers.needsConsolidation(ConsolidateContainers.java:140)
	at org.mars_sim.msp.core.person.ai.task.ConsolidateContainers.needResourceConsolidation(ConsolidateContainers.java:125)
	at org.mars_sim.msp.core.person.ai.task.meta.ConsolidateContainersMeta.getProbability(ConsolidateContainersMeta.java:79)
	at org.mars_sim.msp.core.person.ai.task.util.FactoryMetaTask.getTaskJobs(FactoryMetaTask.java:91)
	at org.mars_sim.msp.core.robot.ai.task.BotTaskManager.rebuildTaskCache(BotTaskManager.java:194)
	at org.mars_sim.msp.core.person.ai.task.util.TaskManager.startNewTask(TaskManager.java:499)
	at org.mars_sim.msp.core.robot.ai.task.BotTaskManager.startNewTask(BotTaskManager.java:244)
	at org.mars_sim.msp.core.robot.ai.BotMind.lookForATask(BotMind.java:197)
	at org.mars_sim.msp.core.robot.ai.BotMind.takeAction(BotMind.java:167)
	at org.mars_sim.msp.core.robot.ai.BotMind.decideTask(BotMind.java:116)
	at org.mars_sim.msp.core.robot.ai.BotMind.timePassing(BotMind.java:95)
	at org.mars_sim.msp.core.robot.Robot.timePassing(Robot.java:332)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:1076)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:937)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:730)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

01-Adir-05:919.876 (Warning) Equipment [x4] : [New Boston] EVA Suit 178 - Just stored back into New Boston'.
01-Adir-05:922.051 (Warning) Unit : RepairBot 012 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : ChefBot 004 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : GardenBot 015 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : GardenBot 016 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : RepairBot 013 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : MakerBot 011 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : ChefBot 003 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : GardenBot 014 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : DeliveryBot 006 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : MakerBot 012 expected pulse #2932 but received 2933
01-Adir-05:922.051 (Warning) Unit : RepairBot 011 expected pulse #2932 but received 2933
```

**Specifications  (please complete the following information)**
 - pre-3.6.0 build 8059

**Additional context**
Exception occurs In ConsolidateContainers class when calling findAllContainers(), 
```java
   /**
     * Consolidate the container's resources.
     * 
     * @param inv
     * @return
     */
    private static boolean needsConsolidation(Unit container) {   	        
        int partialContainers = 0;
        
        boolean useTopInventory = container.getUnitType() == UnitType.SETTLEMENT;
        
        // In Vehicles do not use main store; keep in Containers
        for (Container e: ((EquipmentOwner)container).findAllContainers()) {
            if (e.getStoredMass() > 0D) {
                // Only check one type of amount resource for container.
                int resource = e.getResource();
                // Check if this resource from this container could be loaded into the settlement/vehicle's inventory.
                if (useTopInventory && (resource > 0) 
                		&& ((EquipmentOwner)container).hasAmountResourceRemainingCapacity(resource)) {
                	return true;
                }

                // Check if container is only partially full of resource.
                if (e.hasAmountResourceRemainingCapacity(resource)) {
                    // If another container is also partially full of resource, they can be consolidated.
                	partialContainers++;
                    if (partialContainers > 2) {
                    	// Need at least 3 containers
                        return true;
                    }
                }
            }
        }
    	
    	return false;
    }
```

**Comment by mokun** [comment]
@bevans2000 

This begins to happen when I increase the time ratio to 2048x.

**Comment by bevans2000** [comment]
Making sets Concurrent is not always the correct answer because they are expensive. Was there a Delivery or Trade Mission active do you know? The problem will be cross Settlement updates.

This get probability score looks expensive as well.

We should move consolidate containers to a Settlement Task.

**Comment by mokun** [comment]
> Making sets Concurrent is not always the correct answer because they are expensive. 

Yes I don't mean to make it simply concurrent as the quick fix. 

We just need to find out what's causing it and how to avoid the concurrent exception

> Was there a Delivery or Trade Mission active do you know? The problem will be cross Settlement updates.

There's no Delivery/Trade mission. 

It happens when bots are doing the task of consolidating container at high time ratios and there are 11 settlements in the simulation.

**Comment by bevans2000** [comment]
So does it always have the sand stack trace in the meta mission class?

**Comment by mokun** [comment]
> stack trace in the meta mission class?

it seems to have started from choosing a meta task class or task class .

**Comment by mokun** [comment]
May be somewhere else or even inside `MicroInventory` or somewhere, an element has just been removed. 

However, it wasn't using the `Iterator.remove()` method to remove that element. 

Using other removal method can potentially cause this type of exception.

**Comment by mokun** [comment]
This method `removeEquipment` in EquipmentInventory could be the culprit : 
```java
	/**
	 * Removes an equipment.
	 *
	 * @param equipment
	 */
	@Override
	public boolean removeEquipment(Equipment equipment) {
		return equipmentSet.remove(equipment);
	}
```

![image](https://github.com/mars-sim/mars-sim/assets/1168584/a306d419-24a4-4214-a093-e9d4bb060781)

It was called by 7 methods for ***possibly unsafely*** removing an equipment.

May be we can change the for loop into an iterator and use its supposedly safer `.remove()` method ?!?

**Comment by mokun** [comment]
```java
Iterator<Equipment> iterator = equipmentSet.iterator();
       while(iterator.hasNext()){
           Equipment e = iterator.next();
           iterator.remove();
       }

```

**Comment by mokun** [comment]
Why do we want `equipmentSet` to be an unmodifiable set of collection ? 

```java
	/**
	 * Gets the equipment set.
	 *
	 * @return
	 */
	@Override
	public Set<Equipment> getEquipmentSet() {
//		if (equipmentSet == null)
//			equipmentSet = new UnitSet<>();
		return Collections.unmodifiableSet(equipmentSet);
	}
```

I found out if I switch to iterator, it will trip off an `UnsupportedOperationException` as a result of what `equipmentSet` currently is.
```
01-Adir-01:010.065 (Severe) UnitManager$SettlementTask : Problem with pulse on Tian Cheng: null
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableCollection$1.remove(Collections.java:1056)
	at org.mars_sim.msp.core.person.Person.assignThermalBottle(Person.java:2232)
	at org.mars_sim.msp.core.structure.building.function.LivingAccommodations.assignStandardNecessity(LivingAccommodations.java:169)
	at org.mars_sim.msp.core.structure.building.function.LivingAccommodations.registerSleeper(LivingAccommodations.java:181)
	at org.mars_sim.msp.core.structure.Settlement.trackByMSol(Settlement.java:1010)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:944)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by bevans2000** [comment]
On its own the remove is not an issue. Concurrent list exceptions come from 2 causes:

1. Iterating a list in one thread whilst a second modifies the list. This scenario is not easy to find and is random. Good clear design can resolve these
2. Iterating the same list twice in the same thread stack trace where the bottom stack frame changes the list. Then when the higher  frame continues use iterating it fails because the list has changed. These are normally easy to find and fix

Previously we suffered from case 1 but now Units are only update by the Settlement  thread hence giving that containment. Trade and Delivery missions are the expectation because 2 Units from different Settlement interact. Therefore if you are not seeing Trade and delivery it come be case 2 but I cant see how. 
So I wonder if there is a bug and when consolidating containers we may have a leak in the scope of changes.

**Comment by bevans2000** [comment]
> Why do we want `equipmentSet` to be an unmodifiable set of collection ?
> 
Because we use EquipmentInventory to represent a collection of Equipment so if we want to remove or add items we should go via the methods of Equipment Inventory and not bypass its role. It's about having clear ownership of the data. 
But you have probably found the problem because we are not using the EauipmentInventory methods.

**Comment by mokun** [comment]
> so if we want to remove or add items we should go via the methods of Equipment Inventory and not bypass its role. I

The commit I just made bypass its role so that assignThermalBottle() can remove a thermal bottle and give it to the person who needs it. 

That's because the iterator is inside assignThermalBottle(), it'll need to call .remove method to remove the thermal bottle.

But always feel free to keep it unmodifiable while finding another way to remove or even transfer the bottle if possible.

**Comment by bevans2000** [comment]
I have trawled the code and cannot explain why the concurrent modification is happening nor can I reproduce it. However there a few fragile/suboptimal areas that can be improved:

1. Consolidate containers task should be on the Settlement backlog so the consolidate calcs are re-used and shared.
2. The calculateWater method should not assign the bottle because that method is implied to be read only and make no changes
3. The person "collects" the water bottle when they visit the Living Accommodation

Also I'm still not convinced by the change to the Equipment Inventory since I cannot see how that would solve the problem but unless we can find the real cause I don't want to change anything. My thought is the water bottle is a redherring nd the problem is concerning Robots/Consolidate

**Comment by mokun** [comment]
> Also I'm still not convinced by the change to the Equipment Inventory since I cannot see how that would solve the problem but unless we can find the real cause I don't want to change anything. 

Sure. I'll observe some more to see if the exception will come back or not.

The commit I made was only one circumstance in which the content of the `equipmentSet` has changed. 

Btw, while researching if using iterator to remove an element is safer, I also happen to look up those **transfer** methods and wonder if they are safe or optimal enough or not. 

The way these transfer methods are adding and removing elements could also be the culprit as other methods who are iterating through the `equipmentSet` would suddenly has a new element added or lose track of an element that have just been deleted.
