### ISSUE TITLE
Relocate all vehicle performance params calculations done in Vehicle class to VehicleSpec class

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#886]
**Is your feature request related to a problem? Please describe.**
- Move all vehicle performance params calculations from Vehicle class to VehicleSpec class

**Describe the rationale**
- VehicleSpec deals with the specific performance for each vehicle type and is a better location.

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8062

**Comment by bevans2000** [comment]
I like this idea.

**Comment by bevans2000** [comment]
Can we close this now
