### ISSUE TITLE
Create a standard approach to hold values that change over time

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#888]
**Is your feature request related to a problem? Please describe.**
The simulation currently hold a number of properties that change over time where the history is needed to be recorded, e.g. Mission log, Vehicle Status, Task schedule.
Each one uses a different mechanism and needs direct access to a ```MarsClock```. 
Other properties may benefit from the ability to record the history of changes.

**Describe the solution you desire to see**
Create a standard class using Generics that can record changes to a value over time. It would be related to the existing ```SolDataList``` logic. The class would record changes over time.
It would automatically tag the entries with a timestamp when the are inserted. In addition a fast access method to the last value would be provided.
This new class would be retrospectively fitted to the historical properties.

**Comment by bevans2000** [comment]
Related go #650

**Comment by mokun** [comment]
> It would automatically tag the entries with a timestamp when the are inserted. In addition a fast access method to the last value would be provided.

So in #917 we mentioned we could make MarsClock immutable. 

But if that's the case, will it still an advantage to those history logs that use MarsClock when we can't let these MarsClock instances gabage collected ?

Should we rather save those logs in JSON as separate text files and make these JSON log uniquely associated with a certain sim session ?

**Comment by bevans2000** [comment]
It makes no difference if we save in JSON or not. This is about how we model the values in memory. JSON is about how we persistent them.
Garbage collection is better when using MarsTime because a point in time is only represented by a single immutable object in memory, normal good design. Currently we create multiple instances of MarsClock that represent the same point in time.
Anyway I have the new MarsTime working on a branch where it works in parallel to MarsClock

**Comment by bevans2000** [comment]
This can also cover Role assignment #921

**Comment by bevans2000** [comment]
@mokun I have been looking at the  various way we store changes over time and the majority we are storing history which is optimised to ui at the expense of effecient memory usage. However the vast majority of these histories are never viewed in a ui so the extra storage is wasted.

So what I would like to do in consolidate it to use the new ```History``` class in most cases. But create a dedicated ui panel to show any History object. This would include centralizing the filtering/selection into the panel. This would help our UI code 

I think we could use at least in the following areas:

- person job and roles in the career panel
- vehicle status log
- mission log
- person activity log

**Comment by mokun** [comment]
> However the vast majority of these histories are never viewed in a ui so the extra storage is wasted.

Yes. It can be a waste if we don't document what those logs are and how to use them to the advantage of players.

So how do we better connections between what we show in a log and how they are needed in the simulation ?

**Comment by bevans2000** [comment]
Wow big question.... I'm not sure we can educate the users to use the logs but I think if we adopt a single pattern around a History then it will help. 
I see as just a way to see what has happened to help understand how the simulation works. 
We could put something in the simulation configuration to control how large each type of history grows to. At the moment it's fixed in the code.

**Comment by mokun** [comment]
> I see as just a way to see what has happened to help understand how the simulation works.

**Comment by mokun** [comment]
> I see as just a way to see what has happened to help understand how the simulation works.

Yes. It always ends up helping us developers in figuring out what's under the hood, if nothing else...

**Comment by mokun** [comment]
What's the capability now in terms of recording the usage of EVA Suit ?

I'd like to record:
1. The change of its container unit
2. The registered owner
3. The time it was put to use outside on the surface of Mars
4.  The time it was stowed in settlement or vehicle or carried by a person

Can you demonstrate ?

**Comment by bevans2000** [comment]
Well I think a way to do this is record the container changes over time. We can do this using the History<>class quite easy. 
I've got some time today so I can take a look.

**Comment by bevans2000** [comment]
Just started on this and realised there is a big confusion in how Unit Container hierarchy is handled. Unit can either be:

1. Transferred between Units, e.g. Equipment, Person, Vehicles
2. Fixed parent and never change, Building, Settlement, Construction Site

But all support the ability to change which is incorrect. I've realised this explains the problem of us modelling Location State type and other things. The base Unit does not support being moved by default; but only the subclasses that can be moved should have the methods, transfer, setContainerUnit. Making this change will simplify a lot of things and support cleaning up of the LocationStatetype property. 
This will allow us to override the changing container in EVASuit and record it's hsitory.

**Comment by mokun** [comment]
Awesome for delineating between static units (that need no container unit since they are pretty much served as container units only) and dynamic units (that must have container unit covering them).

> This will allow us to override the changing container in EVASuit 

Can you take a look at the log on why some EVASuit would *gets lost* ?

e.g. a person is on a mission. He came back from outside, when he boarded his rover and go through EnterAirlock, he doffed his suit snd checked in his suit successfully, as reported by the log. 

So the transfer of his EVA Suit 108 from person to vehicle appeared well.

Now, 100 millisols later, he attempted another EVA to perform ExploreSite.

As soon as he started through ExitAirlockand right at the beginning, he couldn't go further.

When he called up canExitAirlock, which called EVAUtil's getRegisteredEVASuit to see if his registered suit or even any suit is available in the vehicle, it returns false.

Why would that happen? Why would that suit disappear? 

Also I checked the vehicle's and that person's Inventory Tab's Equipment table and that EVA suit 108 was nowhere to be found.

Didn't he just dropped off his suit 100 millisols earlier ?

**Comment by bevans2000** [comment]
Sure let me look. I noticed calls to ```setContainerUnit``` outside the ```transfer``` method which should not be happening unless it is in a constructor. This may be a reason.

**Comment by bevans2000** [comment]
I'm on the case deep inside some debugging sessions. There is a problem with how the EVASuit is being transferred. It spontaneously is removed from the Vehicle Equipment list although it is still owner by the Vehicle; managed to find this by breakpointing in the debugger.
Also there is a mistake in the EVASuit selection with it not selecting suits that have no resources. I've sorted that.
I will pull together a Pull Request after if I can get to the bottom of it.

**Comment by bevans2000** [comment]
@mokun I hope #960 should fix the EVA problem. I ran some long runs and missions seemed to handle multiple Eva's reusing the eva suits without problem.

**Comment by mokun** [comment]
> #960 should fix the EVA problem

Yes it does seem it's gone now. Appreciate for tracking that down. 

Now the issues with loading saved sim seems to have to do with MarsTime. Can you see what it is ? 

It probably came from that commit or the commit prior to that. I saved my sim many time yesterday and loaded them without issue

**Comment by bevans2000** [comment]
I tried a few saves and reloads and didn't have a problem, Also the save Unit test is working fine.
