### ISSUE TITLE
Create a new TestDrive Mission

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#890]
Create a new Mission instance based on the new Mission Project approach. This will cover the basic steps of a Mission:

1. Review
2. Load Vehicle
3. Embark
4. Drive 
5. Disembark

**Comment by mokun** [comment]
Sounds good. 

And can we demonstrate how to use it to create, say, a division or department meeting, where all Engineering specialists are invited ?

**Comment by bevans2000** [comment]
Yes we can build on it. A test drive mission encapsulates the key parts of a generic Mission.

**Comment by mokun** [comment]
> Yes we can build on it. A test drive mission encapsulates the key parts of a generic Mission.

Can you put together an example by codes on how to create a team meeting ?

**Comment by mokun** [comment]
@bevans2000 

Is this the thread you were trying to find ?

**Comment by bevans2000** [comment]
No. It was to add something to how we use the secondary Vehicle Status. I was sure I created an issue. I will look through my stuff and try and find it
