### ISSUE TITLE
Have JAXA build a settlement in Cerberus Fossae fault zone

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#892]
**Is your feature request related to a problem? Please describe.**
- *Cerberus Fossae* (CF) is touted as one of the youngest surface on Mars. It is notably lacking in craters and is a geological area of interest due to its very seismic signature.
- JAXA would be a suitable space agency in mars-sim to be tasked with reasonable expertise to analyze its rock in the context of Mars quakes and embark on researching why Mars quakes still occur, even though there is currently no active volcanoes on Mars today.

**Describe the solution you desire to see**
- Relocate JAXA's *Kyocera* settlement coordinate in `scenario_default.xml` to a location near the CF fault zone.

**Describe the rationale**
- Cerberus Fossae is recognized as the very first fault zone found on Mars by NASA's Insight Lander
- It was speculated that lava (instead of water) was the fluid erupted from the Cerberus Fossae. 
- One may explore and find lava tubes that are suitable for future underground settlement. Feel free to discuss this [here](https://github.com/mars-sim/mars-sim/discussions/449).

**Screenshots**
![PIA25282-MarsInSightLander-InsideMars-20220517](https://github.com/mars-sim/mars-sim/assets/1168584/15d86372-2659-46dd-b7f4-9a735ed0728c)

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8083

**Additional context**
1. CF means “Rifts of Cerberus,” the terrifying three-headed hound that guards the entrance to Hades in Greek mythology 
2. [Cerberus Fossae](https://en.wikipedia.org/wiki/Cerberus_Fossae), Wikipedia.
3. [Rumbles on Mars Raise Hopes of Underground Magma Flows](https://www.quantamagazine.org/rumbles-on-mars-raise-hopes-of-underground-magma-flows-20210201/), Quanta Magazine, 01 Feb 2021.
4. [Cerberus Fossae – young tectonic fissures thousands of kilometres long on Mars](https://www.dlr.de/en/latest/news/2018/3/20180920_cerberus-fossae-mars), DLR, 20 Sep 2018.

**Comment by bevans2000** [comment]
Nice idea

**Comment by bevans2000** [comment]
Can we close this now

**Comment by mokun** [comment]
Yes done. It will be even greater one day when we can start a settlement within/using a lava tube or underground.
