### ISSUE TITLE
Enlarge the map box size from 300x300 to 600x600 pixels in Mars Navigator

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#895]
**Is your feature request related to a problem? Please describe.**
- With the higher resolution maps available to download, It's about time to double the map box size in Mars Navigator

**Describe the solution you desire to see**
- Change the map box height and width from 300 to 600 pixels

**Describe the rationale**
- The globe and the surface map are too small to look at

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8089

**Additional context**
- Currently, the left globe map is 600x300, its corresponding right surface map is 2880x1440 or higher 
- Typically, the right surface map needs to be around 5x resolution of the left globe map to make sense
- Q: Should we also make the left globe maps (aka`MarsMap`) downloadable as well ?
- Or, should we *derive* the left globe maps from the downloadable map ?

**Comment by bevans2000** [comment]
Isn't this just a other example,e kf #852

**Comment by mokun** [comment]
@bevans2000 

How do you load topo8192x4096.jpg to the repo ? Where is it at ? 

For now it's included in `/maps` folder but I know you uploaded other maps there.

**Comment by mokun** [comment]
> Isn't this just a other example,e kf #852

#852 originally has to do with making the map in Mission Tool not stretchable and is a different issue.

Now that you mentioned it, the Mission Tool Nav tab allocate only enough space to accommodate a 300x300 map box and the current 600x600 surface map rendering won't be able to fit. So I'll need to create a separate 300x300 map rendering for Mission Tool I suppose.

**Comment by bevans2000** [comment]
> @bevans2000
> 
> How do you load topo8192x4096.jpg to the repo ? Where is it at ?
> 
> For now it's included in `/maps` folder but I know you uploaded other maps there.
> 
> topo8192x4096.jpg is 16.2 MB and is too big to be included in the final jar.

Check out the last comment in #867. The downloadable maps are under the top level folder called content

**Comment by bevans2000** [comment]
The 600x600 panels are too big now. It takes over the whole desktop when I run it on my smaller laptop screen and I can't see the bottom button panel. Not all users will have a high res monitor. We really need to make the tool stretchable so a user can decide how big they want it.

**Comment by mokun** [comment]
> We really need to make the tool stretchable so a user can decide how big they want it.

Ok. User can always drag the map to see what's on left, right, top and bottom. 

I could make it a 450x450 map box instead.

The current approach requires a double array of 450 by 450 be set up.

May be soon we come up with a scheme of loading up maps in tiles. 

The goal should be giving the Mars Navigator and Mission Tool that can zoom in and out of certain section of the map.

**Comment by mokun** [comment]
@bevans2000 

Note that currently, after switching those low resolution cylindrical maps from 600x300 to 1200x600, it has to stick with the mapbox of 600x600.

I'm not able to reduce the mapbox back to 300x300, or else the zoombox and center coordinates won't be able to pinpoint the correct location on the globe.

In light of this, we may as well remove those low resolution maps 1200x600 once and for all. 

To do so would seem to involve a lot of changes. 

Even though, it pulls from one surface map, It will need to create and keep two separate sets of double array of ints, one for the globe, one for the surface map.

**Comment by mokun** [comment]
What does it take to remove those low resolution maps (namely those 1200x600 ones) once and for all and rely on just one map for rendering both the left globe and the right surface map ? 

I know this may initially involve a bit of code changes but will worth the effort. 

As you know, it doesn't make sense to have 2 sets of resolutions of the same feature map around while also keepimg two separate sets of double array of ints, one for the globe, one for the surface map.

**Comment by bevans2000** [comment]
> What does it take to remove those low resolution maps (namely those 1200x600 ones) once and for all and rely on just one map for rendering both the left globe and the right surface map ?
> 
> I know this may initially involve a bit of code changes but will worth the effort.
> 
> As you know, it doesn't make sense to have 2 sets of resolutions of the same feature map around while also keepimg two separate sets of double array of ints, one for the globe, one for the surface map.

Change the mapdata.properties file. Each line defines the lores & hires version. So just use the same map image name in both properties.
