### ISSUE TITLE
Error finding loading missions

### ISSUE THREAD

**Issue by larsnaesbye** [mars-sim/mars-sim#9]
Created: 2014-11-29
Migrated from https://sourceforge.net/p/mars-sim/tickets/17/ 

While I was fixing classes that have to do with food consumption, I'm having a mysterious "Error finding loading missions". It's java.lang.NegativeArraySizeException.

> Nov 28, 2014 5:08:42 PM INFO org.mars_sim.msp.core.person.ai.mission.Mission Regolith Prospecting ending at Disembarking due to Successfully disembarked.
> Nov 28, 2014 5:08:42 PM SEVERE org.mars_sim.msp.core.person.ai.task.meta.ConstructBuildingMeta Error finding building construction missions.
> Nov 28, 2014 5:08:42 PM SEVERE org.mars_sim.msp.core.person.ai.task.meta.LoadVehicleEVAMeta Error finding loading missions.
> Exception in thread "AWT-EventQueue-0" Nov 28, 2014 5:08:42 PM SEVERE org.mars_sim.msp.core.person.ai.task.meta.LoadVehicleGarageMeta Error finding loading missions.
> java.lang.NegativeArraySizeException
> at java.util.Arrays.copyOf(Unknown Source)
> at java.util.Arrays.copyOf(Unknown Source)
> at java.util.ArrayList.toArray(Unknown Source)
> at java.util.ArrayList.<init>(Unknown Source)
> at org.mars_sim.msp.core.person.ai.mission.MissionManager.getMissions(MissionManager.java:116)
> at org.mars_sim.msp.core.person.ai.mission.MissionManager.getMissionForVehicle(MissionManager.java:288)
> at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.isVehicleLoading(VehicleMapLayer.java:203)
> at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.drawVehicle(VehicleMapLayer.java:139)
> at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.drawVehicles(VehicleMapLayer.java:113)
> at org.mars_sim.msp.ui.swing.tool.settlement.VehicleMapLayer.displayLayer(VehicleMapLayer.java:89)
> at org.mars_sim.msp.ui.swing.tool.settlement.SettlementMapPanel.paintComponent(SettlementMapPanel.java:499)
> at javax.swing.JComponent.paint(Unknown Source)

**Comment by larsnaesbye** [comment]
![historical events not showing anything](https://cloud.githubusercontent.com/assets/7767079/22946851/1624fafa-f2f9-11e6-831e-0a7d2a0832d3.png)
![erring loading mission and paint problem](https://cloud.githubusercontent.com/assets/7767079/22946855/18dfead4-f2f9-11e6-8d41-bc54ce56d505.png)
[stack trace.txt](https://github.com/mars-sim/mars-sim/files/775188/stack.trace.txt)

**Comment by larsnaesbye** [comment]
Scott Davis - 2014-12-04      
This one is quite odd. The stack trace is all related to throwing a NegativeArraySizeException on MissionManager.getMissions() line 116, which is:
return new ArrayList<Mission>(missions);
I'm not seeing anything that would cause the missions variable to be a negative size collection. If it was null, this would have thrown a NullPointerException.
The only thing I can think of is that the missions variable somehow became corrupted, but I'm not sure how.
Please let me know if you see this problem again. I'm hoping it's just a freak occurance.

**Comment by larsnaesbye** [comment]
Lars Christensen - 2017-01-20      
I can't reproduce it with the current version - I suppose it's been a glitch or fixed since....

**Comment by mokun** [comment]
From the pic, the Time Tool was smeared and was not properly refreshed. It seems like it has to do with Eclipse. I recommend closing this issue for now. We can always revisit this if it resurfaces again.
