### ISSUE TITLE
organizations and countries missing 

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#90]
While there may be countries who would want to have their own individual martian programs, it is also possible that there may be intra-country people working together. This has not been factored in at least on the console side of the things.

**Comment by mokun** [comment]
Yes. 

Currently mars-sim allows users to assemble an international team with folks from different countries and space agencies.

This is done in the form of an alpha team of 4 members using crew editor.

Unfortunately, it's only available in GUI mode.

Will work on bringing it to the console mode.

**Comment by mokun** [comment]
I've added the ability to designate the country/space agency for the Commander in the console mode in this [build]( https://github.com/mars-sim/mars-sim/commit/5d93a830e7f5148b168f05cda04b297c448a5255).

**Comment by shirishag75** [comment]
Did see that in the 4479 build. Although having a roster would be cool. Will be awaiting development of that, so let's keep this open till that is seen in the console as well.

**Comment by mokun** [comment]
See [4501](https://github.com/mars-sim/mars-sim/releases/tag/4501). Closing it.
