### ISSUE TITLE
Port Ares and Europa are listed under the same panel

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#900]
**Describe the bug**
- From time to time, when loading the default scenario, Port Ares (from Mars Society) and Europa (from ESA) are placed under the same panel in Monitor Tool.

**Expected and unexpected behavior**
- If they belong to the same sponsor, then it actually make sense to place them under the same belt.
- But they belong to different sponsors and should NOT be placed together.

**Discuss any potential problems you have and have not ruled out**
- This happens only 30% of the time at the startup.
- After clicking on a tab in Monitor, the Port Ares entity would magically disappear.

**Java classes involved**
- MonitorWIndow, MonitorModel
 
***Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/c0e59336-4f99-4c67-a63a-15e65c84e066)

**Specifications  (please complete the following information)**
 -pre 3.6.0 build 8117

**Additional context**
- In future, when a settlement set up affiliated communication tower, weather stations, mining or trading outpost, etc., we should definitely list them under same tab location.

**Comment by bevans2000** [comment]
I think i know what this is. The SettlementTableModel will get an event when the new Settlement is created and add the Settlement. But when working in the filtered mode; it should ignore the event.
I can fix this.

**Comment by mokun** [comment]
Also, I have NPE from time to time when I choose the eclipse launcher to load a particular sim from my local machine. 

When I choose a sim from JFileChooser to load, the simulation does get loaded successfully. 

But the stacktrace shows NPE of a settlement from Monitor Tool.
