### ISSUE TITLE
Put settlements/stations/outposts of same space agency under one belt

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#903]
**Is your feature request related to a problem? Please describe.**
- Both Europa and Arcadia are ESA settlement in scenario_default.xml. It would be silly to separate them into different settlement panel in Monitor Tool.

**Describe the solution you desire to see**
- List both Europa and Arcadia under one belt.

**Describe the rationale**
- if a settlement creates numerous weather/communication stations, mining stations, trading outposts, etc. it's more intuitive to find and see the general statistics of them in single location.
- In future, we may even create a dashboard showcasing combined statistics of related settlements/stations/outposts.

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8131

**Additional context**
- One unintentional effect was found in that two unrelated settlements were put under one panel in #900. We want it to happen under a different circumstance/reason.

**Comment by mokun** [comment]
This design change would be nice in anticipation of having #907 in future.

**Comment by mokun** [comment]
@bevans2000 

Other than ESA, We also have 2 settlements under Mars Society now.

Can you change it in such a way to make the Settlement tab show 2 settlements, instead of one ?

**Comment by bevans2000** [comment]
Do you mean in the Monitor Window ?

**Comment by mokun** [comment]
> Do you mean in the Monitor Window ?

Yes. In Monitor Tool's Settlement tab.

Actually, the original purpose of this thread is to get weather stations, depots, outposts under the jurisdiction of a settlement all under one settlement tab.

I suppose each settlement should have its own settlement Tab.

But now, in view of this, we could build a combo box having a list of sponsors, in addition to the settlement combo box.

Player will be given the choice to select either one of the combobox.

If a sponsor is chosen in the sponsor combobox, then a sponsor tab will be created.

If a sponsor have two settlement, then the two settlement will both be shown in this tab and visual comparison can be made relatively easily in terms of resources, power, etc.

The vec'hicle tab will show all vehicles from both settlements under the selected sponsor.

Do you like that ?

**Comment by bevans2000** [comment]
We could do. It's a lot of work. Is not too tricky for tabs showing Units but harder for the tabs that only show details of a single Settlement like Crops or Goods. 
Secondly we should make a decision on the logn term layout of the UI before making large changes.

**Comment by mokun** [comment]
@bevans2000 

I just created [#1095](https://github.com/mars-sim/mars-sim/issues/1095).

How do we create a combobox that will take in either a list of settlements or a list of sponsors ?

**Comment by bevans2000** [comment]
Yes I think I need I know what we need to do. We will need to change the interface on MonitorTab.
I'm working on #1084 in the background but assign this issue to me and I will switch to doing this.

**Comment by mokun** [comment]
May be we can have two separate combobox, one with a set of settlements, one with a set of sponsors. 

If that's the case, then each tab in the monitor window will need to sense what game mode the simulation is at and load the right combobox accordingly.

Will you choose this approach?

**Comment by mokun** [comment]
Or just initially set up only one combobox with generic and fill it with elements of either settlements or sponsors, based on the game mode chosen.

Will the change be easier this way in all the tabs in the monitor window ?

**Comment by mokun** [comment]
Should we have two radio buttons, one for populating settlements in a combobox, one for populating authorities in that same combobox ?

**Comment by bevans2000** [comment]
I  an do it as one contains authority and settlement

**Comment by mokun** [comment]
But how ?

**Comment by bevans2000** [comment]
We will utilize the ```Entity``` interface so that we can have a single Combo holding Reporting Authority & Settlements. I'll create a new re-usable renderer that will support that type. 
Then the the MonitorTab will be changed to support different selection of ether a Settlement or Reporting Authority. The individual TableModels will need specific implementations. It's not too difficult.

**Comment by bevans2000** [comment]
@mokun I have created a Draft PR with the changes to filter on Authorities as well as Settlements in the Monitors Window.
Have a look.
I want to merge this once 3.7.0 is close off as it changes most of the Monitor Window model logic. But for the better. I'm particularly happy about the automatic show/hide of the Settlement column.

**Comment by mokun** [comment]
Currently, the settlement/sponsor combo box has some issues.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/f4bd1fe3-9224-4469-b92a-ccd9ee25d8bb)

1. The order of the settlement names changes from time to time. It become non-alphabetical for some strang reasons.
2. While I was viewing the Settlement Map of 'Foundation', all of a sudden the Settlement Map jump to Arcadia's.

Can you take a look ? Thanks !
