### ISSUE TITLE
Fix foundation/frame/building construction

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#909]
**Describe the bug**
- While investigating how to implement [#907](#907), it's been shown that various phases in the Building Construction Mission are broken.

**Expected and unexpected behavior**
- Fix the foundation/frame/building construction process

**Java classes involved**
- BuildingConstructionMission 

**Specifications (please complete the following information)**
- pre 3.6.0 build 8149

**Additional context**
- If construction materials are not available, it makes sense to ask mission members to perform the task of `DigLocalRegolith` to extract raw resources so as to begin resource processes to produce concrete and other construction materials.
- The algorithm of choosing a construction site needs work. 
- The selection process needs to be clearly defined and parameters should be shown and changeable in Command Dashboard.
- At least, player should be given the opportunity to select a construction site.

**Comment by mokun** [comment]
@bevans2000 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/f7d61c57-206e-4a45-9c10-3cb6ccb550bb)

Even though we don't have 63 kg concrete, we can still proceed with CREATING a mission instance of building this foundation. This part works well. I can click all the way to the end and the newly created Construction Mission will show up in Mission Tool

![image](https://github.com/mars-sim/mars-sim/assets/1168584/c5ddb83a-e8a3-4ee4-8426-a9906ba8e973)

Right now, as you can see, it said it still need 25 kg more concrete. 

Does it mean that somehow it has transferred 38 kg (= 63 kg - 25 kg) from settlement to the construction siste so far ?

We'll still on sol 1. I don't recall we added 38 kg concrete initially at the start of the sim. This can be an anomaly.

Anyway, I've worked on is smoothing out the any supply chain issues of providing enough input resources to make enough concrete quickly.

Right now, one other limitation is that without all 63 kg concrete, the construction won't start. 

Q: would it make sense to wait for all concrete to be ready ?

In real world, we mix the cement powder, water and loose sand or stones together to create concrete. 

After that, we need to pour the concrete right away to avoid getting dried up.

I suppose we want this process to be simulated as well.

We do need to get all the cement and sand ready in mars-sim to make concrete.

Any thought ?

**Comment by mokun** [comment]
btw, in order to process to the second `MissionPhase`, the player must right click on the construction site and choose **Confirm Site**. 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/9722a646-ffcd-47b3-984c-86474c5e5c47)

If NOT, it gets stuck at the first phase, namely, **Select Site** `MissionPhase`.

The reason for that need currently is that I can also choose **Relocate Site** to move the site elsewhere and doesn't have to be at this first location chosen by the algorithm.

So, it's after I'm comfortable with the location of the site that I have confirmed would go to the next phase.
 
What the better way can we with that ?

May be a ***Construction Tool*** that player can predefine site locations ahead of time ?

**Comment by bevans2000** [comment]
To be truthfully have not used the Construction feature much. I know the mission Construction is very coupled with the ui wizard which is not ideal. As you know I'm pushing to make the simulation autonomous as much as possible where the user directs and influences rather than is mandatory.

**Comment by mokun** [comment]
> marks the enclosed area as inaccessible and makes it possible to draw a red dashed polygon 

Yes marking some areas as inaccessible would be a good visual aid, all powered by Mars AI to make your life easier 😄 😁

**Comment by mokun** [comment]
> the AI could then build more beautiful bases.

Hmm so far we've been handcrafting each settlement template building by building. Very painstaking process.

Now that you mentioned the power of AI in making building/settlement map layout. I wonder how we may get there.

**Comment by Urwumpe** [comment]
Well, one option is always fake intelligence. Actually just random, but with smart programming. 

Another would be permutating possible extensions of a "base fractal", growing the base like a snowflake or a [dragon curve](https://en.wikipedia.org/wiki/Dragon_curve).

Harder would be implementing methodic product design, I still experiment with ways how to translate it into an algorithm.

**Comment by mokun** [comment]
> Another would be permutating possible extensions of a "base fractal", growing the base like a snowflake or a [dragon curve](https://en.wikipedia.org/wiki/Dragon_curve).

Wow ! 

I'd certainly love to play around using this snowflask/dragon curve concept to model the growth of a settlement.  

![330px-Fractal_dragon_curve](https://github.com/mars-sim/mars-sim/assets/1168584/297efd74-28a4-4e05-90df-8f41f8727090)

To me, it's fun having these mathematical theory implemented and applied more in mars-sim

![450px-Dragon_Curve_adding_corners_trails_rectangular_numbered_R](https://github.com/mars-sim/mars-sim/assets/1168584/0d308ab2-8273-46c0-93fa-a459cb7c691b)

Now I see that it's possible we first use this to **macroscopically** model the growth of a lunar colony. 

If we are to implement the use of it in mars-sim for growing a settlement, it would take away the need to individually define each building and to precisely model settlers' daily tasks and how each mission is run.

**Comment by mokun** [comment]
May be we can implement `City Mode` in mars-sim for growing settlements across the globe. 

This would be kind of moving away our current laborious focus of creating micro-simulations - individually define buildings, model settlers' daily tasks and mission, etc..

However, it would be just as fun to govern things at a higher level such as how the land use will evolve over time, how various factors will drive the development of certain regions, and how population will grow and people migrate from place to place to build new human societies across the whole planet.

**Comment by mokun** [comment]
@bevans2000 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/c65d63ea-acc2-4cef-abad-2d56b69cb2b2)

So far, we've worked out how to let settlement kick start construction mission.

However, it has trouble finishing the foundation, even though enough concrete has been provided.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/9b422ca7-00d1-42ed-abce-e94c7fb0d9f8)

So far, we still need to improve on: 
1. Missing Quantity should show 0 when done.
2. Show quantity reserved
3. Allow player to adjust the PERCEN ASSIGN for taking on `ConstructBuilding` task
4. Provide Mission Status

**Comment by mokun** [comment]
@bevans2000 

Ideally speaking, I'd like to resolve these 4 problems before releasing 3.6.0.

Any insights ?

**Comment by bevans2000** [comment]
Mission Status should be easy to fix. I don't understand when item 3 is above? Is this a variable set by the user; could be incorporated into #963

**Comment by mokun** [comment]
@bevans2000 

We can construct foundations, frames and buildings now. 

We should give player the flexibility to select the construction site location in near future.

**Comment by bevans2000** [comment]
That would.make sense. Something using the SettlementTool I would expect. Create an issue
