### ISSUE TITLE
No one is digging ice or regolith in any settlements

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#910]
**Describe the bug**
- Haven't seen anyone going out to dig regolith or ice for a while
- DigLocalMeta keeps returning zero probability 

**Expected and unexpected behavior**
- DigLocalRegolith and DigLocalIce should use the collection rate in calculating probability
- fix: enable DigLocalMeta to return non-zero value of probability

**Java classes involved**
- DigLocalRegolith, DigLocalIce, DigLocalMeta 

**Specifications (please complete the following information)**
- pre 3.6.0 build 8150

**Additional context**
- While working on [#907](https://github.com/mars-sim/mars-sim/issues/907) and [#907](https://github.com/mars-sim/mars-sim/issues/907), it was discovered that no matter how high a settlement's demand for regolith, there is no one digging regolith. Without regolith, there is no cement and concrete.

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

Now at least they are now digging regolith/ice normally.

We probably need an automatic excavator sitting on a dedicated site (then it will dig deep) or have it moving around to dig up reglith.

Any idea on how to do it ?

**Comment by Urwumpe** [comment]
Well, let me play captain obvious (I am sorry):

1. It has to fit into a lander or be build on Mars. So no Bagger 288 until very late in the "endgame".
2. Water and ice are heavy and settlements need lots of it. So the ice mining site will very likely be so close to the settlement, that it be counted as part of it. Ideally in pipe distance. 
3. Regolith is pretty much everywhere. When we need a special regolith site, something has to happen. Either kiloton demand or a special version of regolith is needed, that does NOT exist everywhere

**Comment by mokun** [comment]
> So no Bagger 288 until very late in the "endgame".

Do you mean Bag 288 as an Container/Equipment in mars-sim ?

**Comment by Urwumpe** [comment]
> > So no Bagger 288 until very late in the "endgame".
> 
> Do you mean Bag 288 as an Container/Equipment in mars-sim ?

LOL no, I mean this compact, little strip mining tool: [Bagger 288](
https://en.wikipedia.org/wiki/Bagger_288)

**Comment by mokun** [comment]
> little strip mining tool: [Bagger 288](https://en.wikipedia.org/wiki/Bagger_288)

wow this thingy costs you $100 M each ! The price tag could have manufactured a mini Starship in future :D

**Comment by Urwumpe** [comment]
In 1978, that should have been enough for a large Starship. ;)

**Comment by mokun** [comment]
oh well. 

NASA kept pumping cash over the years into Sierra Nevada's little lifting body [spaceplane](https://en.wikipedia.org/wiki/Dream_Chaser
). They supposedly started the development since 2004.

Been 20 years but it's probably still years away from being operational.

**Comment by mokun** [comment]
Done.
