### ISSUE TITLE
Mission aborted: not enough water or food

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#911]
**Describe the bug**
- There have been numerous aborted missions recently due to NOT having enough water or food.
- The remaining amount of water and food is being checked every 40 millisols 
- During one "Wait for Sunrise", the occupant of a vehicle cannot drive the rover or cannot perform the mission and the mission got aborted. 
- This new extra wait time may NOT have been anticipated when counting the # of hours or # of sols that go toward calculating more resources to be added when loading resources.

**Expected and unexpected behavior**
- Mission should not be aborted if running out of food or water. 
- They should have slowly been curtailing the mission to the point that they shortened the mission and  go home early but receive some sort of penalty for their mission.

```java
- RoverMission has these modifiers : 
	/* The marginal factor for the amount of water to be brought during a mission. */
	private static final double WATER_MARGIN = 1.5;
	
	/* The marginal factor for the amount of oxygen to be brought during a mission. */
	private static final double OXYGEN_MARGIN = 1.25;
	
	/* The marginal factor for the amount of food to be brought during a mission. */
	private static final double FOOD_MARGIN = 1.5;
```

- Yet there's already Rover's getLifeSupportRangeErrorMargin() that boosts up these life support resources 's amount
 
**Discuss any potential problems you have and have not ruled out**
- RoverMission's `getResourcesNeededForTrip` is an **Override** method that override AbstractVehicleMission's `getResourcesNeededForTrip`. The calling chain is NOT straight forward to understand and resolve. It could be simpler 

**Java classes involved**
- AbstractVehicleMission's `getResourcesNeededForTrip`
- AbstractVehicleMission's `getResourcesNeededForRemainingMission`
- RoverMission's `getResourcesNeededForTrip` 
- RoverMission's `addLifeSupportResources`
- EVAMission's `getEstimatedTimeAtEVASite`
- EVAMission's `getEstimatedRemainingEVATime`

**Specifications (please complete the following information)**
- pre 3.6.0 build 8157 

**Additional context**
- The amount of fuels estimated for the remaining journey is getting much more accurate after fixing the estimated fuel consumption (FC) and fuel economy (FE) in the last few commits. 
- Since the FC and FE affects the distance or remaining mission range calculation, it seems as if the life support resources shortage was hidden before and NOT uncovered until now.

**Comment by bevans2000** [comment]
I agree this logic is difficult. Its one of the changes I'm adopting in #890.

**Comment by mokun** [comment]
> Its one of the changes I'm adopting in https://github.com/mars-sim/mars-sim/issues/890.

In trying to offer a fix on these bugs triggered by some major changes in vehicle specs related lately , I did have to touch a few more mission related class. Without that, it will leave many things broken for you to deal with while you are wrapping up the project mission.

My change is straightforward and hopefully easy to merge on your end.

**Comment by bevans2000** [comment]
As part of #890 it is an alternative to the existing Mission not a correction of them. I see once we get the new approach working we can migrate over the existing Mission. I've nearly got the Test Drive Mission working.

**Comment by mokun** [comment]
> alternative to the existing Mission not a correction of them.

That;s great. I'll look forward to it.

Does it mean that you create a new set of class files for missions under project structure ?

**Comment by bevans2000** [comment]
Yes, totally new set of class using a new approach in a new package. It can work along side the existing approach but I plan to migrate the Mission to the new approach.
The new approach is much cleaner and easier to understand. Jump on the branch and have a look if you want.

**Comment by mokun** [comment]
Will it use any new xml files to define anything in particular ?

**Comment by bevans2000** [comment]
Interesting idea. The goals is to have a Mission based on a number of selectable steps. This could be defined in XML yes but things like the logic of selecting exploration sites would need to be invoked in someway.
At the moment I thing the first step is to replicate the current logic is a cleaner and easier to understand framework that is more flexible.
Then we could work on making the Mission setup data driven from XML.

**Comment by mokun** [comment]
Depending on the time the mission embarks, if they drive the vehicle at night, it will take longer to get to the destination. 

This will seriously affect the food/water needed and thus the trip time. We'll need to account for that in our resource estimate.

And now I just found out we have turned off the terrain and sunlight modifiers that will slow down the vehicle speed...

We'll see what happen.

**Comment by mokun** [comment]
Do you still see any mission aborted due to this issue ?

**Comment by bevans2000** [comment]
No, let's close it

**Comment by mokun** [comment]
This rarely happens now. Closing it.
