### ISSUE TITLE
Remove Coordinate copy constructor

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#913]
**Is your feature request related to a problem? Please describe.**
As the ```Coordinates``` class is immutable there is no benefit in having a copy constructor as the original will never change.

Therefore we should remove this constructor to remove the need for excessive object creation.
This impact a few other areas in the code.

**Comment by mokun** [comment]
Sure !

> This impact a few other areas in the code.

Like what other areas ?

**Comment by bevans2000** [comment]
Just do a Call Hierarchy in your IDE to see where it is used.
