### ISSUE TITLE
Record Role Assignment History

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#921]
**Is your feature request related to a problem? Please describe.**
- There is no log on when the role of a person is changed.

**Describe the rationale**
- A settler's role change should be as crucial as one's job. 
- The important of role will still need to be further defined and refined.
- Tracking role assignments is one step toward the appreciation of a role a person will play.

**Describe the solution you desire to see**
- Model the change of role to how job assignment is recorded.
- Allow Career tab to generate a log entry on the role change, similar to job change.

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8210

**Additional context**
- We want to cast the vision that the defining features of a role in career progression is something a person would be worth pursuing, even living on Mars.
- It may be helpful in defining a Career class for the purpose of tracking how much time and effort settlers spend in fulfilling their duties. 
- We could set up role scores and job scores.
- We could set up an achievement system to reward settlers of their diligence in their role and job assignment.

**Comment by bevans2000** [comment]
This is one of the cases for #888 so let's sweep it up in that generic solution
