### ISSUE TITLE
IntegerMap.java Performance/Readability Issues (and Solutions)

### ISSUE THREAD

**Issue by bdowrick** [mars-sim/mars-sim#924]
**Describe the bug**
Currently, `getMapImage()` in `IntegerMapData.java` suffers from a couple of issues to do with performance and readablity.
For performance - The map generation takes roughly ~50ms - 180ms depending on the center coordinates passed into it. This is wildly inconsistent due to the weird nature of the loop, calculating index, phi, and theta by iterating through phi/theta values...?

For readability - It's not immediately clear what, why, or how these values are calculated and the maths behind it is needlessly obscured.
 
**Expected and unexpected behavior**
- Iterate only over MapBox values (0,0) to (Width, Height) instead of calculating phi/theta bounds
- Easily readable and well documented code

**Discuss any potential problems you have and have not ruled out**
- List out other possible issues in this situation you have encountered and whether you have or have not ruled out.

**Java classes involved**
`IntegerMapData.java`

**Solution:**
I have put together a fixed version that reduces performance on my machine to ~60ms. This is significanltly more consistent and does not suffer from fluctuations depending on location. Overall benchmarks show a 12% avg. improvement but this is based on location

**Side Note:**

Using OpenCL (org.jogamp.jocl) dependency, I was able to reduce the time per frame to anywhere from 0-2ms using the GPU and parallelizing the entire calculation

# Screenshots
## Old Code
Note that not all of it fits in the screenshot.
![image](https://github.com/mars-sim/mars-sim/assets/16632004/095ec272-b77b-4034-adb7-c2a22a593536)

## Proposed New Code
Note the `convertRectToSpherical` function called. This is identical to the `Coordinates.java` implementation of it but was translated over into `mars-sim-mapdata` (using Point2D return values instead of Coordinates)
![image](https://github.com/mars-sim/mars-sim/assets/16632004/571addcf-b762-4797-a18b-558c4d6888c5)

**Comment by bdowrick** [comment]
@mokun @bevans2000 

I can submit a pull request with the updates if this seems good enough

**Comment by mokun** [comment]
Hi @bdowrick ,

Yes thanks for pointing that out how to reduce the complexity and appreciate for benching it.

Please do a pull by all means !

**Comment by mokun** [comment]
> Using OpenCL (org.jogamp.jocl) dependency, I was able to reduce the time per frame to anywhere from 0-2ms using the GPU and parallelizing the entire calculation

Great to hear that you must have used JOCL before. I can find that as a maven artifact in https://mvnrepository.com/artifact/org.jocl/jocl/2.0.5 

Do modify the pom.xml to use it.

I'll love to see that pull from you soon.

**Comment by bdowrick** [comment]
Fantastic! I'll put through the JOCL implementation shortly :)

It requires a couple extra depedencies (being Gluegen-RT and JOCL) but I'll detail those in the pull request

**Comment by bevans2000** [comment]
Cool change. The OpenCL package now in mapdata, is that OpenCL code that you've copied in or is that a mars sim specific wrapper to the OpenCLlibrary?

Now this new approach will guarantee a fully populated sub-map we could try to make the Navigator window resizable again. Last time I tried, the old logic brokedown at large maps and had blank semi-circle at the edges because the spherical calculations failed.

**Comment by mokun** [comment]
> to make the Navigator window resizable again.

@bevans2000 
Currently, the Mission Window is resizable. Particularly, the Navigation Tab can be resized.

It's just that the map can't be stretched beyond whatever we hard coded. It's 450 by 450 at this point, you know.

Also, I just switched over to using JSplitPane in this [commit](https://github.com/mars-sim/mars-sim/commit/10a0a37fb0ff9b4f450b9624948fda4d17673868). 

At least now, we have the freedom to use the center split bar to help resizing the top and bottom panel.

**Comment by bdowrick** [comment]
`OpenCL.java` has it's inspiration from [this](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/util/OpenCompute.java). It's currently a `mars-sim` specific wrapper for the jogamp JOCL library.

Ideally I'd like to move it to it's own java module so that `mars-sim-mapdata`, and `mars-sim-core` can depend on, and use this class without circular dependencies. And replace some more complex calculations in surface layers (MineralMapLayer more specifically)

Another cool thing about this implementation is it comes with a zoom feature (using modification of the `rho` variable passed into either function).
See here (ignore the markers in the wrong location): Using `rho / 5`;
![image](https://github.com/mars-sim/mars-sim/assets/16632004/ccebe0c2-43fb-47e4-9028-f434fa732431)

**Comment by bevans2000** [comment]
When I run it I get this
```
Exception in thread "AWT-EventQueue-0" com.jogamp.opencl.CLException$CLBuildProgramFailureException: 
CLDevice [id: 2295030075456 name: Intel(R) HD Graphics 4400 type: GPU profile: FULL_PROFILE] build log:
2:1:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
2:25:17: error: use of undeclared identifier 'M_PI'
2:28:17: error: use of undeclared identifier 'M_PI'
2:36:78: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
2:43:29: error: use of undeclared identifier 'M_PI'
2:65:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
2:66:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
2:76:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
2:77:1: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
CLDevice [id: 2295086074592 name: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz type: CPU profile: FULL_PROFILE] build log:        
Compilation started
Compilation done
Linking started
Linking done
Device build started
Device build done
Kernel <getMapImage> was successfully vectorized (8)
Done. [error: CL_BUILD_PROGRAM_FAILURE]
        at com.jogamp.opencl.CLException.newException(CLException.java:84)
        at com.jogamp.opencl.CLProgram.build(CLProgram.java:392)
        at com.jogamp.opencl.CLProgram.build(CLProgram.java:230)
        at org.mars_sim.mapdata.OpenCL.lambda$getProgram$0(OpenCL.java:54)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at org.mars_sim.mapdata.OpenCL.getProgram(OpenCL.java:51)
        at org.mars_sim.mapdata.IntegerMapData.<init>(IntegerMapData.java:93)
        at org.mars_sim.mapdata.MapDataFactory.getMapData(MapDataFactory.java:85)
        at org.mars_sim.mapdata.MapDataUtil.getMapData(MapDataUtil.java:108)
        at org.mars_sim.msp.ui.swing.tool.map.MapPanel.setMapType(MapPanel.java:262)
        at org.mars_sim.msp.ui.swing.tool.map.MapPanel.<init>(MapPanel.java:85)
        at org.mars_sim.msp.ui.swing.tool.navigator.NavigatorWindow.<init>(NavigatorWindow.java:205)
        at org.mars_sim.msp.ui.swing.MainDesktopPane.getToolWindow(MainDesktopPane.java:336)
```

**Comment by bevans2000** [comment]
It's no big problem for me at the moment I should add as I'm looking at Mars Time

**Comment by mokun** [comment]
> CLDevice [id: 2295030075456 name: Intel(R) HD Graphics 4400 type: GPU profile: FULL_PROFILE] build log:

Do you have a Nvidia/AMD GPU on your computer ?

**Comment by mokun** [comment]
I don't have the exception above. 

But if I keep dragging the map very often. It results in the following stacktrace : 
 
> xception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Cannot reserve 811008 bytes of direct buffer memory (allocated: 1609864424, limit: 1610612736)
> 	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
> 	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:121)
> 	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332)
> 	at com.jogamp.common.nio.Buffers.newDirectByteBuffer(Buffers.java:79)
> 	at com.jogamp.common.nio.Buffers.newDirectIntBuffer(Buffers.java:142)
> 	at com.jogamp.opencl.CLContext.createIntBuffer(CLContext.java:302)
> 	at org.mars_sim.mapdata.IntegerMapData.gpu(IntegerMapData.java:260)
> 	at org.mars_sim.mapdata.IntegerMapData.getMapImage(IntegerMapData.java:223)
> 	at org.mars_sim.msp.ui.swing.tool.map.CannedMarsMap.createMapImage(CannedMarsMap.java:71)
> 	at org.mars_sim.msp.ui.swing.tool.map.CannedMarsMap.drawMap(CannedMarsMap.java:83)
> 	at org.mars_sim.msp.ui.swing.tool.map.MapPanel$1.mouseDragged(MapPanel.java:119)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:327)
> 	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6674)
> 	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3407)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6395)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4592)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> E

**Comment by bdowrick** [comment]
I'll fix these up asap and put through a fallback to cpu if it fails.

**Comment by mokun** [comment]
> And replace some more complex calculations in surface layers (MineralMapLayer more specifically)

Yes. Computing the MineralMapLayer is indeed slow. 

When this layer is off, the whole rendering speeds up significantly in both classical non-OpenCL and OpenCL cases.

**Comment by bevans2000** [comment]
> > CLDevice [id: 2295030075456 name: Intel(R) HD Graphics 4400 type: GPU profile: FULL_PROFILE] build log:
> 
> Do you have a Nvidia/AMD GPU on your computer ?

No, the machine I was using was an oldish laptop. I use for mars-sim; Lenovo G50-70 (https://www.lenovo.com/hk/en/laptops/lenovo/g-series/g50-70/). Got a built-in Intel Graphics 4400.
Obviously I wasn't expecting it to pick up a GPU for this laptop but use the cpu based calcs.

**Comment by mokun** [comment]
> a fallback to cpu if it fails.

Awesome ! I was gonna ask for fallback in case there's no GPU...

```
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Cannot reserve 811008 bytes of direct buffer memory (allocated: 1609864424, limit: 1610612736)
```

And what memory is it talking about above ? need to allocate more ?

**Comment by mokun** [comment]
> Lenovo G50-70

From that page, it does say it has both AMD Radeon R5 M230 2GB and Intel® HD Graphics 4400. So ...

**Comment by bdowrick** [comment]
@bevans2000 - Issue caused by a graphics driver that doesn't support 64bit precision (double), replacing double with float should fix this

@mokun  - Issue caused by a memory leak where the outputs of the kernel weren't properly released after use.

I'll put through a pull once I've tested the fixes out properly

**Comment by bevans2000** [comment]
> @bevans2000 - Issue caused by a graphics driver that doesn't support 64bit precision (double), replacing double with float should fix this
> 
> @mokun - Issue caused by a memory leak where the outputs of the kernel weren't properly released after use.
> 
> I'll put through a pull once I've tested the fixes out properly

Yes, this is an old laptop I use. I haven't tried it on my other one yet.

**Comment by mokun** [comment]
Thanks @bdowrick, it works well now. Map display is smoother.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/a973ae3c-7f3f-4133-a2d6-e159e2469e0c)

Now with the JOGL patch, in case of the 12-settlement default scenario sandbox, my CPU usually hovers between 3.5% to 10%. 

But if I start dragging my mouse on the surface map intensely, it could go up to 22% as shown in the snapshot above. 

Also, GPU util can go up to ~5.1 %. 

Now a big problem seems to lie with Mineral map layer. JOGL patch won't help that.

Good that we just isolate this as a major problem here and we'll need to optimize the mineral concentration computation. 

So do feel free to probe around other issues also and let us know any improvement you can think of. 

Your feedback and comments are welcome here. 

We appreciate your contribution much on this thread.

**Comment by bevans2000** [comment]
Work fine for me now.
@bdowrick what do you fancy trying next? Other issues are open

**Comment by mokun** [comment]
Btw, based on @bdowrick's work, today I'm experimenting with the use of mouse scroll to zoom in and out of the surface map. I'll commit the change soon.

**Comment by mokun** [comment]
@bevans2000

To pick up on our conversation on https://github.com/mars-sim/mars-sim/issues/1606,

Looks like currently there are issues with using GPU opencl from time to time (but not all the time)
It said `Index 600 out of bounds for length 600'.

@bdowrick 
Any ideas what to improve in IntegerMap now ?

```
01-Adir-01:049.786 (Config) IntegerMapData : GPU OpenCL accel enabled.
01-Adir-01:049.786 (Config) MapDataFactory : Loading map type 'vikingMDIM'. Res level: 0. Map name: 'Viking Colorized Global Mosaic MDIM 2.1'. Color: true
01-Adir-01:050.471 (Severe) IntegerMapData : Exception with GPU OpenCL accel when running gpu(). Index 600 out of bounds for length 600
```

- With GPU enabled, the map gets distorted : 
<img width="763" height="565" alt="Image" src="https://github.com/user-attachments/assets/38246f6c-9e1f-4db1-a318-a5897c9178a7" />


- With GPU disable, the maps works : 
<img width="770" height="571" alt="Image" src="https://github.com/user-attachments/assets/ecf56f32-d702-4edb-9f06-86b08ff2b1fd" />
