### ISSUE TITLE
difference between persons, people and settler ? Tasks, Schedule

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#93]
There doesn't seem to be any difference between the terms or at least it isn't apparent. 

Using either term we get a list of all the people. Why do we need three terms for the same thing or are there going to be a different meaning going forward to all the three distinct words ?

**Comment by mokun** [comment]
There is no diff.

Wouldn't it be fun to amp up mars-sim with Natural Language Processing (NLP) ?

See https://wit.ai/ for inspiration.

**Comment by shirishag75** [comment]
that was my thought but thought it might be too processing intensive.

**Comment by mokun** [comment]
For now, you can ask a person what he's doing with `task` or `doing`

You can ask him if he's on a mission with `mission`

However, a person can do a number of things every time you ask. 

Depending on the duration of a task, it can be done from a few millisols to 100 millisols.

So I'll have to come up with a different way to display these real-time data. 

It will involve continuously updating the console with a stream of data until the user press q to end the stream.

**Comment by mokun** [comment]
> what is the job schedule/rotation on a particular base like ?

For small bases, each person works 12 hours a sol. So they have 2 work shifts, namely, `A` and `B`.

For larger bases, each person works 8 hours a sol. They have 3 work shifts, namely, `X`, `Y` and `Z`. 

We put together a new wiki [Task](https://github.com/mars-sim/mars-sim/wiki/Tasks#work-shift) later.

For sure, we can provide players for visibility to the kind of tasks expected and even forecast the need of the settlement, as suggested by this [thread](https://github.com/mars-sim/mars-sim/issues/141) 

Also, it will be great to allow players to customize their only work shift hours and do whatever make sense. 

For instance, during the night when there is no sunlight, EVA operations are generally not allowed, unless there is emergency repair. So at that period of time, work demand is low, etc.

**Comment by mokun** [comment]
Closing this now.
