### ISSUE TITLE
how do I copy and paste from the text terminal to clipboard ?

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#94]
There doesn't seem to be a way to copy and paste from the text terminal to the clipboard . I cannot use either right-click select and copy via mouse or CTRL+Shift+C to copy to clipboard. 

Any ideas ?

**Comment by mokun** [comment]
I just ask the developer to take a look into this at https://github.com/beryx/text-io/issues/18

**Comment by shirishag75** [comment]
@mokun  the developer has shared various ways in which this can be handled, please see which you think would be the most appropriate, integrate it and then maybe release a headless jar to see if the fixes are good . Let's keep it open till I'm able to give feedback on what happens.

**Comment by mokun** [comment]
Awesome ! I'll change the shortcut for showing a list of countries and will implement the copy and paste in the console.

**Comment by mokun** [comment]
It's done. Closing it.
