### ISSUE TITLE
Remove Mars globe from Mars Navigator

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#942]
**Is your feature request related to a problem? Please describe.**
- Let the surface map take the center stage in Navigator Window to let player see more detail.

**Describe the rationale**
- Mars Globe is currently the same size as the surface map. With the recent [improvement](#924) implemented in `IntegerMapData`, the surface map is now fully capable of zooming in and out. the Mars Globe on the left side of Mars Navigator looks static, have black lines artifacts and no longer being particularly useful .

**Describe the solution you desire to see**
- Remove the globe would give back more room for Mars Navigator and focus on providing more functional capability to the surface map.

**Describe alternatives you've considered**
- Leave the globe as a small inset near the top or bottom left corner of the surface map

**Screenshots**
![image](https://github.com/mars-sim/mars-sim/assets/1168584/a7350ff6-d992-42da-a085-18f52862cad0)

**Specifications  (please complete the following information):**
 - Pre 3.6.0 build 8260

**Additional context**
- Provide more options to highlight, describe unique landmark and/or geographical features, pinpoint and center them on the surface map.

**Comment by bevans2000** [comment]
I e been so busy looking at the modelling of Martian time I forgot to checkout the changes. If the right hand panel zooms then I agree just have a single panel.

**Comment by mokun** [comment]
Yes. Plus that fact that the surface map can display the markers for settlement and vehicle names, landmark names and others. The globe doesn't have these ability. 

So unless we find other good uses for the globe, we don't really need it anymore.

**Comment by mokun** [comment]
This is what it will look like, at least for now : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/4741da12-62d9-4de4-8fd5-aaab1f6a939e)

![image](https://github.com/mars-sim/mars-sim/assets/1168584/6c571117-0aa4-45d5-ac57-d2bf2f6a3b70)

Note that I've tried to figure out how to make the background black padding to show up when it gets small enough to look like a globe.

Either the BufferImage returns a color deep space background or getRGBColorInt() is bad.

I know paintComponent() in MapPanel works well because if I remove display the image, the starfield does show up.

Before I commit this, I'll first make sure @bdowrick knows about this somewhat drastic but easy work since he's working on [#935](https://github.com/mars-sim/mars-sim/issues/935) and we may run into conflicts revising the  class files.

Let me know.

**Comment by bevans2000** [comment]
Looks good.

**Comment by mokun** [comment]
@bdowrick 

A moment ago I committed [this](https://github.com/mars-sim/mars-sim/commit/2ae1f453cea3250b48b14dca5ed0e6009e2b9ba4) with regard to fixing a bug in eating food and drinking water.

What I didn't realize it would actually proceed to commit [this](https://github.com/mars-sim/mars-sim/commit/92310863a7f23fe08219e3301965c48e9630048e) (regarding the Mars Globe) as well.

So both commit went through together in one shot. This is very strange.

I encountered a bug earlier in eclipse in handling the commit and I gave up with it and already backed those affected files up.

Anyway, hope it won't affect much on the class files you may be working on.

I still hope to deconflict on the class file you may be working on. and

**Comment by mokun** [comment]
@bdowrick 

I just cleaned up those already commented-out lines in all map related class so that you can get a better copy to work on.

**Comment by bdowrick** [comment]
Loved this change by the way! The globe is so nice to move around now, and looks fantastic the way you've placed it in the Mars Navigator.

We might be able to get a space background through culling any pixel that have coordinates that 'miss' the planet. 
Likely we might be able to inverse the sphere calculations to get a rotating Star background that can be loaded in from an official source

I'm fairly certain the background color currently is just because whatever pixel is set at 0,0 is that color?

**Comment by mokun** [comment]
@bdowrick 

> the background color currently is just because whatever pixel is set at 0,0 is that color?

It's still a mystery to me as to why it won't use the black color for empty space or the starfield.

Can you take a shot at it ?

![image](https://github.com/mars-sim/mars-sim/assets/1168584/5e2c5317-a609-4dc4-86f6-82af8e40ab85)

If I switch to the topo map, the empty space would have a green background. It helps me it somehow bleeds out of that last pixel from the edge, instead of leaving it the value of the array zero or black.

Or is this the alpha channel problem when constructing the BufferImage ?

It shouldn't have anything to do with loadMapData() in IntegerMapData,

In getMapImage(), I've tried setting up BufferedImage instance with just about all types (such as TYPE_INT_ARGB, TYPE_INT_ARGB, TYPE_4BYTE_ABGR, etc.) and none of them gives me the black empty space around the globe when fully zoomed out

```java
 		// Create a new buffered image to draw the map on.
 		BufferedImage result = new BufferedImage(mapBoxWidth, mapBoxHeight, 
 				BufferedImage.TYPE_INT_ARGB);//.TYPE_INT_ARGB);//TYPE_4BYTE_ABGR);

```

It doesn't seem to have to do with MapPanel's paintComponent(). I've tried 
1. setComposite(AlphaComposite.SrcOver), 
2. setBackground(Color.BLACK);
3. clearRect(0, 0, Map.DISPLAY_WIDTH, Map.DISPLAY_HEIGHT);
4. setPaint(Color.BLACK); 
5. setColor

None of them works.

```java
	public void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (desktop != null && isShowing() && 
        		(desktop.isToolWindowOpen(NavigatorWindow.NAME)
        		|| desktop.isToolWindowOpen(MissionWindow.NAME))) {
	        
        	Graphics2D g2d = (Graphics2D) g;
	        
        	g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
			g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
			g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
			g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
			
	        if (wait) {
	        	if (mapImage != null) 
	        		g2d.drawImage(mapImage, 0, 0, this);
	        	String message = "Generating Map";
	        	drawCenteredMessage(message, g2d);
	        }
	        else {
	        	if (mapError) {
	            	logger.log(Level.SEVERE,"mapError: " + mapErrorMessage);
	                // Display previous map image
//	                if (mapImage != null) g2d.drawImage(mapImage, 0, 0, this);
	
	                // Draw error message
	                if (mapErrorMessage == null) mapErrorMessage = "Null Map";
	                drawCenteredMessage(mapErrorMessage, g2d);
	            }
	        	else {

	        		g2d.setComposite(AlphaComposite.SrcOver); 
	        		
//	        		g2d.setBackground(Color.BLACK);
	        		
	        		// Clear the background with white
//	        		g2d.clearRect(0, 0, Map.DISPLAY_WIDTH, Map.DISPLAY_HEIGHT);

	        		// Paint black background
//	        		g2d.setPaint(Color.BLACK); 
	        		
//	        		g2d.setColor(Color.BLACK);
//	                
//	        		g2d.fillRect(0, 0, Map.DISPLAY_WIDTH, Map.DISPLAY_HEIGHT);
//	
	        		g2d.drawImage(starfield, 0, 0, Color.BLACK, this);
	
	                if (centerCoords != null) {
	                	if (marsMap != null && marsMap.isImageDone()) {
	                		mapImage = marsMap.getMapImage();
	                		if (mapImage != null) {
	                			g2d.drawImage(mapImage, 0, 0, this);
	                		}
	                	}
	                	else
	                		return;
	
	                	// Display map layers.
	                	
	                	// Put the map layers here.
	                	// Say if the location of a vehicle is updated
	                	// it doesn't have to redraw the marsMap.
	                	// It only have to redraw its map layer below
	                	Iterator<MapLayer> i = mapLayers.iterator();
	                	while (i.hasNext()) i.next().displayLayer(centerCoords, marsMap, g);
	                	
                		g2d.dispose();
	                }
	        	}
	        }
        }
    }

```

Back when we have the GlobeMap. Inside drawMap(), it uses MemoryImageSource to create the image and it never have that problem...

```java
	/**
	 * Creates a 2D map at a given center point.
	 * 
	 * @param newCenter the new center location
	 */
	public void drawMap(Coordinates newCenter) {	
		
		// Create image out of buffer array
		globeImage = displayArea
				.createImage(new MemoryImageSource(MAP_H, MAP_H, imageArray, 0, MAP_H));
```

If you figure out what went wrong, do by all means commit the change. Much appreciated !

**Comment by mokun** [comment]
@bdowrick 

I came across your github repo [here](https://github.com/bdowrick/computational-economy) on economics, goods and markets and they sounds like an interesting project.

Do you think you can build up the economic model further in mars-sim and incorporate some of the features of your work ?

**Comment by bevans2000** [comment]
The navigator tool isn't usable in a 1368x732 screen because the control panel can be shown because the window is too tall. The window doesn't support resizing now. This screen resolution is not unusable on a laptop.

**Comment by mokun** [comment]
ok I'll make the surface map 512 by 512. Currently, it's 600 by 600.

**Comment by mokun** [comment]
The surface map box has always had a fixed size since the beginning.

I haven't tried experimenting with making the surface map box variable in width and height yet. 

It seems daunting when the height and width are not the same. 

But it could be just a matter of recalculating the pixels in that double array and probably no big deal.

If we optimize the map pixel generation further, it's possible to support full screen and still with little or no noticeable degradation in rendering the surface map.

**Comment by bevans2000** [comment]
Can we close this or move it to a new milestone?

**Comment by mokun** [comment]
The only thing not done on this thread is the starfield background.

**Comment by bevans2000** [comment]
Can we fix this then? Feels like we have too many active issues at the moment and it would be good to close down 3.6.0.

**Comment by mokun** [comment]
I'm not able to get rid of that background color. Can you take a look ?

**Comment by bevans2000** [comment]
I will but it's not my speciality 😄

**Comment by bevans2000** [comment]
@mokun The mineral layer in the latest build is now very slow and doesn't display as many mineral as previously. Is this expected?
I'm cleaning up the MineralMap classes and thought it was something I had done but I've checked against 3.6.0 and it behaves the same.
I am going to create a UnitTest to check the RandomMineralMap logic now as well

**Comment by mokun** [comment]
> The mineral layer in the latest build is now very slow and doesn't display as many mineral as previously. Is this expected?

Which two builds would you like to compare ? 

We make it necessary for player to turn on each mineral. The more minerals it has to render, the slower the speed.

**Comment by bevans2000** [comment]
In the older release say 3.4, the mineral layer showed a lot more colours. My point is I don't know what is the expected correct behaviour, plus I don't remember it being that slow

**Comment by mokun** [comment]
For sure, in 3.6.0, the size of the Mars Navigator is bigger than in 3.5.0, the latency of rendering the mineral layer is becoming more noticeable.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/87366e75-cf59-435a-acd3-ca3094144c41)

It's intentional that when player drags the mouse across the map, the mineral concentrations will be temporarily unavailable for display, or else, it would significantly bog down the CPU.

When we zoom in and out, we could have used similarly strategy to make the mineral concentrations temporarily unavailable for display in order to speed up the rendering.

**Comment by bevans2000** [comment]
OK, so maybe I was just looking in the wrong location and didn't have enough mineral deposits. Do we have a configuration setting to influence how many mineral deposits are created?

**Comment by mokun** [comment]
> 3.4, the mineral layer showed a lot more colours. My point is I don't know what is the expected correct behaviour, plus I don't remember it being that slow

The length and width of the Navigator have increased from 300 to 512. Therefore, it takes longer for the loop to finish rendering the mineral layer.

**Comment by mokun** [comment]
The bulk of the work is done on this thread. 

What still remains to be done is to get rid of that background color. We'll worry about that in future.
