### ISSUE TITLE
have different playing styles - RPG elements, achievements, role, skill, attributes

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#95]
There could be different playing styles and achievements related to that. 

While I do not have an idea as to how much in-depth role-playing you want, one idea 
which I have been thinking of is having side-quests or minor missions which support the overall mission. 

One way you could be a stand-offish commander and just order around people 

a more interesting way perhaps is that you get down and help the crew which could have many benefits. 

The morale of the person you are working with is higher and you could unlock more quests which would improve the mission overall. 

Just to have an example - 

Let's say the commander is a repair mechanic (role) alongwith another skill s/he has . I did think about having each person having 2 skills so especially in small settlements if somebody is ill or down or something we have somebody who can take care of that role till another specialist (role) is appointed. 

Anyways in the example I thought was thinking he could help repair/create quests or missions related with biologist or/and botanist and adding more to that storyline. 

I do not know how large the maps (scale) you would have of the martian maps but having farms and what not could just add number of hours to the game. Even making hybrid crops by experimentation would be cool. 

One idea would be to have skill checks, attributes and a way to gain new perks to borrow from traditional rpg genre elements. It could also have a leveling system. 

If this has been already on the plate than apologies, if not maybe create a new sub-project :)

**Comment by mokun** [comment]
There's quite a lot. Let's break down everyone you said into individual projects/issues !

**Comment by mokun** [comment]
> Let's say the commander is a repair mechanic (role) alongwith another skill s/he has . I did think about having each person having 2 skills so especially in small settlements if somebody is ill or down or something we have somebody who can take care of that role till another specialist (role) is appointed.

Yes each person can acquire a number of skills. 

e.g. A person whose is a `Botanist` has a level 1 `Botany` skill at the start of the sim.

If she happens to be in a building that has a malfunction, she may or may not want to help with the repair. If she does repairs, she will earn points in `Mechanics` skill. 

Skills are also be taught. A mechanic can teach him Mechanics skill and earn more points.

So it's possible that in Mission Sol 30, she has `Botany` skill level 3 and `Mechanics` skill level 2 and she can help out with some mechanical work part time.

**Comment by mokun** [comment]
> One idea would be to have skill checks, attributes and a way to gain new perks to borrow from traditional rpg genre elements. 

I just created a new wiki page on the [Attributes](https://github.com/mars-sim/mars-sim/wiki/Attributes)

**Comment by mokun** [comment]
Just edited the wiki page [Skills](https://github.com/mars-sim/mars-sim/wiki/Skills)
