### ISSUE TITLE
Members never bring their EVA suits if boarding a mission vehicle in garage 

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#958]
**Describe the bug**
- For Alpha Base's missions, none of the occupants have EVA suits in the rover Dusty Star. They can't go out to do regolith prospecting.

**Expected and unexpected behavior**
- Case 1: No garage in a settlement :
When boarding the vehicle, each member already has already donned an EVA suit. They will doff the suit in the vehicle. This isn't the issue.
- Case 2: Have garage and board the vehicle parked in garage :
Need to ensure `RoverMission` manually transfer sufficient # of EVA Suits from settlement to vehicle. This is what's missing.

**Java classes involved**
- RoverMission, ExitAirlock, Walk

**To Reproduce (Please provide steps)**
- Steps to reproduce the behavior:
1. Observe how the Alpha Base does a mission and check if there are any EVA suits stored in a vehicle during the trip.

**Stacktrace**
```
01-Adir-03:053.576 (Warning) EVASuitUtil : [0.0272 N 0.0618 E - Dusty Star] Hanna Szabó - Could not find any EVA suits in Dusty Star.
01-Adir-03:053.576 (Warning) ExitAirlock : [0.0272 N 0.0618 E - Dusty Star] Hanna Szabó - Could not find a working EVA suit and needed to wait.
01-Adir-03:056.909 (Warning) EVASuitUtil [x5] : [0.0272 N 0.0618 E - Dusty Star] Emma Pichler - Could not find any EVA suits in Dusty Star.
```

**Specifications (please complete the following information)**
- pre 3.6.0 build 8335

**Additional context**
- One could use enteringRoverInsideGaragePhase() in Walk to transfer EVA suits from settlement to vehicle prior to departure.

**Comment by bevans2000** [comment]
The correct fix is to the EVAsuits the the required equipment list for the Mission if the vehicle is not in a Garage

**Comment by mokun** [comment]
> The correct fix is to the EVAsuits the the required equipment list

Good point.

We could do both. 

The required equipment should have EVA suits

Then after loading, if it's still missing during departure. I don't mind doubling check it.

Also, what if the settlement doesn't have enough (i.e. not everyone have an EVA suit). 

We'll need to decide the ratio of # of EVA suits in a vehicle versus the# of EVA suits staying in a settlement.

**Comment by mokun** [comment]
I just found this snippet in `RoverMission` : 

```java
	/**
	 * Performs the departing from settlement phase of the mission.
	 *
	 * @param member the mission member currently performing the mission
	 */
	@Override
	protected void performDepartingFromSettlementPhase(Worker member) {
		Vehicle v = getVehicle();
...
...
				// If person is not aboard the rover, board the rover and be ready to depart.
				if (!getRover().isCrewmember(person)) {

					Walk walk = Walk.createWalkingTask(person, adjustedLoc, 0, v);
					if (walk != null) {
						boolean canDo = assignTask(person, walk);
						if (!canDo) {
							logger.warning(person, "Unable to start walk to " + v + ".");
						}

						if (!isDone() && isRoverInAGarage
							&& settlement.findNumContainersOfType(EquipmentType.EVA_SUIT) > 1
							&& !hasBaselineNumEVASuit(v)) {

							EVASuit suit = EVASuitUtil.findRegisteredEVASuit(settlement, person);
							if (suit != null && !suit.transfer(v)) {
								logger.warning(person, "Unable to transfer a spare " + suit.getName() + " from "
									+ settlement + " to " + v + ".");
							}
						}
					}
```

```java
	/**
	 * Does the vehicle have at least the baseline numbers of EVA suits ?
	 *
	 * @param vehicle
	 * @return
	 */
	protected boolean hasBaselineNumEVASuit(Vehicle vehicle) {
		boolean result = false;

		int numV = vehicle.findNumContainersOfType(EquipmentType.EVA_SUIT);

		int baseline = (int)(getMembers().size() * 1.5);

		int numP = 0;

		for (Person p: ((Crewable)vehicle).getCrew()) {
			if (p.getSuit() != null)
				numP++;
		}

		if (numV + numP > baseline)
			return true;

		return result;
	}
```

**Comment by mokun** [comment]
'RoverMission' is dealing with too many different situations (a lot of *if-then*'s ) when embarking and disembarking.

It is very fragile and hard to test.

You won't use `RoverMission` in your new project mission architecture, right ?

**Comment by mokun** [comment]
We also *cheated*

```java
					EVASuit suit0 = getEVASuitFromVehicle(person, v);
					if (suit0 == null) {
						EVASuit suit1 = EVASuitUtil.findRegisteredEVASuit(emergencySettlement, person);
						if (!suit1.transfer(v)) {
							logger.warning(person, "EVA suit not provided for by " + emergencySettlement);
						}
					}

```

**Comment by mokun** [comment]
It turns out they do count if there are enough EVA suits in the settlement in `RoverMission` and even limit the # of members prior to departure : 

```java
	/**
	 * Calculate the mission capacity the lower of desired capacity or number of EVASuits.
	 */
	protected void calculateMissionCapacity(int desiredCap) {
		if (!isDone()) {
			// Set mission capacity.
			int availableSuitNum = MissionUtil.getNumberAvailableEVASuitsAtSettlement(getStartingPerson().getAssociatedSettlement());
			if (availableSuitNum < desiredCap) {
				desiredCap = availableSuitNum;
			}
			setMissionCapacity(desiredCap);
		}
	}
```

**Comment by mokun** [comment]
@bevans2000 

What's the best way to programmatically convey that a person has put on a EVA suit ?

**Comment by mokun** [comment]
@bevans2000 

What's the best way to programmatically convey the fact that a person has *put on* a EVA suit vs. just *carrying* an EVA suit but hasn't really put it on ?

Any pros and cons from each approach if more than one ?

**Comment by mokun** [comment]
Note that I'm still tracking down the bug as to why and how some EVA suits disappeared after the person went through `EnterAirlock` to come back in from outside and supposedly dropped off or transfer his suit onto the rover. 

Shortly later, he needs to go out again. But when he looks for his suit, it's nowhere to be found somehow.

**Comment by mokun** [comment]
Btw, I'm enabling the ***Search Tool*** to be capable of searching for the whereabout of EVA Suits by popping up a suit's `EquipmentUnitWindow`.

![image](https://github.com/mars-sim/mars-sim/assets/1168584/96c3a24d-6435-4473-8e92-8d1bf6d32cbb)

![image](https://github.com/mars-sim/mars-sim/assets/1168584/0cc8d976-2c4f-4fc6-a896-41435b7cb84e)

**Comment by mokun** [comment]
Looks like this is done.
