### ISSUE TITLE
Change SettlementPreferences logic to be more generic to cover Policies

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#963]
**Is your feature request related to a problem? Please describe.**
The modifiers used to score various activities in the simulation in terms of a Settlement are controlled by a common set of Preferences. These can be modified/viewed from the UI.
There is also a parallel set of controls for Process Override that have separate logic.

**Describe the solution you desire to see**
The Override can be transformed into a modified version of the Preference logic. This improved logic could define a set of Policies for a Settlement that could be either a flag or a modifier. The benefit is this would be a single solution to cover all cases and be very generic.
The Type field in the PreferenceKey class would define if a double or boolean value should be held; hence influencing the UI.
This would deliver a generic solution that can be used elsewhere.

**Comment by mokun** [comment]
Referencing [this](https://github.com/mars-sim/mars-sim/commit/6051bb3f929759215e02cfe0e359e6c481011f86) and [#511](https://github.com/mars-sim/mars-sim/issues/511) here.

**Comment by mokun** [comment]
A person's Preference class should do something similar for him. 

While he may be more likely or less likely perform a task/mission, he should be given the ability to choose to *override* as well.

In a sandbox session, the player is in *God-mode*. It makes sense to give player the ability to click on that override check box to turn on and off certain tasks/mission over a person.

**Comment by bevans2000** [comment]
Coincidentally I have been looking at the ```Preferences``` class. It's got some problems with it and redundant code & maps objects.

**Comment by mokun** [comment]
> Coincidentally I have been looking at the `Preferences` class. It's got some problems with it and redundant code & maps objects.

Yes do make them more efficient
