### ISSUE TITLE
Add search history in Search Tool; New layout

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#967]
**Is your feature request related to a problem? Please describe.**
- Currently, Search Tool has limited functions. 
- For instance, it does not record what units have been selected. 

**Describe the solution you desire to see**
- Add search history
- Use FlatLAF's ability to show a magnifier glass at the leading edge of the search text field and a clear button at its trailing edge

**Describe the rationale**
- Improve the ability of Search Tool will be crucial as mars-sim scales to handle dozens of settlements, each having hundreds of settlers.
 
**Screenshots**
- See the snapshot below from FlatLaf Demo : 
![image](https://github.com/mars-sim/mars-sim/assets/1168584/3e441e99-5be9-440e-9cce-eec45e0a61a8)

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 3876

**Additional context**
- In future, one should further develop the ability for the Search Tool to look for things such as settlers, vehicle, bots, settlement (outposts, depots, stations), buildings, equipment, and even for goods.

**Comment by mokun** [comment]
I've just added three new features as follows : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/fe631925-635f-4f82-83e9-7622c172c508)

**Comment by mokun** [comment]
@bevans2000 

Can we think of more use cases from FlatLaf demo that we can make use of ?

**Comment by mokun** [comment]
@bevans2000 @Urwumpe 

When my friend first try out mars-sim, they find the UI very difficult to navigate and counter-intuitive. 

So I'd like to improve the visual aspect of mars-sim as our old classic desktop from the windows 3.1 era really need an overhaul. The concept of the main window is not as elegant as it used to be.

Today I've drawn some inspiration from JGoodies's [Showcase 23.06](https://www.jgoodies.com/downloads/demos/)

If we do continue to stick with Swing for the next couple of years to save time to work on other things, we could.

We can retain our classic main window desktop while gradually revamping our main screen to be half game-like and half dashboard message oriented.

At last I believe JGoodies show us we can still reuse most of our Swing UI code while reinventing our desktop to be more message oriented.

So when running the Showcasae demo, the first thing you'll see is a narrow strip of control icons anchored to the left edge of the screen. It has five icons : a return icon, a menu icon, a search icon, a home icon, and a setting icon at the bottom.

![Screenshot 2023-07-09 at 7 53 51 PM](https://github.com/mars-sim/mars-sim/assets/1168584/773c5d0d-beef-4ead-9ba7-816c3d4aa851)

In case of mars-sim, we could leave our ToolWindow's icons such as the Mission Tool, Resupply Tool, Science Tool, Settlement Map, Mars Navigator accessible from there. 

When one of these tools opens up, it should occupy the whole desktop space or at least nicely dock at a default location such as the top left, etc.

Then there are these tiles in the desktop. I imagine our future workspace can be populated with these tiles of various categories, each representing a kind of workflow for the commander to decide to work on or even some statistics pie or bar charts attached to measuring some quantity over time and space.

![Screenshot 2023-07-09 at 7 57 03 PM](https://github.com/mars-sim/mars-sim/assets/1168584/7ea9f307-426d-4322-8da4-290967f1708f)

![Screenshot 2023-07-09 at 8 12 36 PM](https://github.com/mars-sim/mars-sim/assets/1168584/b432e2b8-279a-465b-8eb2-53b4f634a084)

**Comment by mokun** [comment]
When I look at those ArcGIS's [dashboards](https://www.esri.com/arcgis-blog/products/ops-dashboard/decision-support/dashboards-in-arcgis/), it gives me the feeling that I can take care of things by aggregating multiple datasets and analyzing trends to project what may happen in near future.

Is it what a commander is supposed to do for his settlement ?

**Comment by bevans2000** [comment]
The important thing is to decide on the user interaction and then worry about the look and feel. So yes the desktop approach is old school but how do you think data should be presented?

**Comment by mokun** [comment]
> The important thing is to decide on the user interaction 

That's a great point !

interaction is supposed to be immersive and not shallow. Clicking a few buttons methodically to win a game is not what we are aiming to achieve.

I see that giving utility value or actual substance to an immersive experience is more important than ever.

> how do you think data should be presented?

The incoming data should be presented in a form that help users relate and feel and embrace the immensity of the responsibility of its outcome if choosing to act upon it or withhold it.

**Comment by bevans2000** [comment]
One route to take is to improve the event manager so that it provides a steady stream of 'news' to the user. The recent change I did means from an event the user can single click onwards to a detailed view of the entity logging an event. 
Maybe instead of that being in the monitor tool we have it a right hand view that provides a feed of interesting activities.
We could also provide another view that is a browser or tree view of entities, starting with Settlements then drilling down into people or robot, vehicle etc

**Comment by mokun** [comment]
> Why not create a project and we can do some.mockups on alternative layouts before touching any code

Sure. After 3.6.0, we will open a new project and define what the new layout should look like. 

May be it's time we go back to use JavaFX ?

**Comment by bevans2000** [comment]
Can we close this or move it to a new milestone?
