### ISSUE TITLE
Why maven instead of gradle, openjfx 11, packaging for debian, maven-debian-helper,

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#97]
Why did you use maven instead of gradle ?

Today I was trying to help out somebody and saw gradle is much better, at least in terms of declaring dependencies and such . 

See https://paste.debian.net/1047545/ for an example. 

It gives such a beautiful tree-like structure for dependencies, compile-path, test-path, runtime-dependencies which should make packaging far more easier than using maven. 

Even dependencies for tests are clearly defined so one doesn't have to run around much. 

https://spring.io/guides/gs/gradle/

There could be three things though - 

a. There is some similar functionality in Maven that I don't know about (very much possible.)
b. Apache came in 2004 while Gradle came in 2007 and you were already familiar with Maven 
c. There is some shortcoming in Gradle that I don't know. 

It would be nice if nothing else, to learn something new from you :)

**Comment by mokun** [comment]
To me, Maven is a complete suite of things from testing to dependency, packaging and everything in between. It's very good for configuring how things can be done for complex projects. Yes it's more difficult to learn and it uses xml.

Gradle is newer and easier but some parts still needs to be ironed out. 

I do like the fact that Android uses Gradle and if mars-sim ever wants to be launched in any mobile platform, we should transition mars-sim to embrace gradle in future.

**Comment by shirishag75** [comment]
didn't know it used gradle, that's cool. I did see that gradle shows separate trees for dependencies, for tests and for runtime-dependencies which from what little experience I have is lesser than the build-time ones. In theory it should be much easier for newbies to get into. I'm getting why they are now more Android developers than java developers apart from the Android SDK bit  ;)

**Comment by seamlik** [comment]
The XML files when using Maven might be a bit annoying (which is probably why Android chose Gradle), but as a result most Maven projects are structures in a very similar and simplistic way. Gradle scripts are indeed very flexible, but that's also the reason why maintaining Gradle packages in Debian is a bit painful...

To be honest, as a Java package maintainer in Debian, I am so very glad to see anything that uses Maven. 😂

@mokun In fact, there's no need to switch to use Gradle even you want the project consumed by an Android one. Well unless you want to build an Android module (AAR package).

**Comment by mokun** [comment]
Hi @seamlik, I'd love to get some help from you in figuring out how to integrate mars-sim with debian-- making use of the existing dependencies in debian in such a way that the Debian edition of mars-sim will be lean.

**Comment by seamlik** [comment]
> I'd love to get some help from you in figuring out how to integrate mars-sim with debian

Hi @mokun , when a Maven package is built in Debian using [`maven-debian-helper`](https://wiki.debian.org/Java/MavenDebianHelper), it will automatically use the artifacts available in Debian's archive. As a result, a lot of dependencies won't be up-to-date, but the unit tests might be able to catch the bugs because of it.

**Comment by shirishag75** [comment]
@seamlik I read the maven wikipedia page before playing around with mvn package . I did try to also individually try to package mars-network-ui using `$ mvn package `

**Comment by mokun** [comment]
@seamlik , I'll look into using `maven-debian-helper`. 

The pom.xml that is responsible for compiling the debian edition of mars-sim is at https://github.com/mars-sim/mars-sim/blob/master/mars-sim-main/pom.xml

Can you show me what to add to this pom.xml file ?

You can see other debian related misc. files at https://github.com/mars-sim/mars-sim/tree/master/mars-sim-main/src/deb

**Comment by seamlik** [comment]
In order to build a package that complies to The Debian Policy (which is something like you want, without dependencies bundled), you would need to understand how to build a Debian package in the official way.

There is a [guide for Debian packaging](https://www.debian.org/doc/manuals/debmake-doc), and also a  slightly outdated [tutorial for `maven-debian-helper`](https://wiki.debian.org/Java/MavenRepoHelper).

But you can also take a look at a [very simple Debian package that uses Maven](https://salsa.debian.org/java-team/dd-plist/tree/master/debian). Everything you need would be placed in a directory called `debian`, and then you run `dpkg-buildpackage` to start the build.

**Comment by mokun** [comment]
> I read the maven wikipedia page before playing around with mvn package . I did try to also individually try to package mars-network-ui using $ mvn package but came with the same errors.

@shirishag75 , `mars-sim-network` requires openjfx 9. 

It's for adding multiplayer mode in mars-sim over the home network. However, I have not been maintaining this submodule for a while.

`mars-sim-ui`, however, requires not only openjfx 9, but also `mars-sim-core`, `mars-sim-mapdata` and `mars-sim-network`.

So if `mars-sim-network` fails to compile, `mars-sim-ui` will automatically fail or will be skipped and won't even compile.

**Comment by mokun** [comment]
> Also lot of the 'dependencies' that I saw of mars-sim are/were still based on openjdk-8 so looking from Debian buster perspective, we are much better off. IIRC, Manny is still not able to build openjdk-11-jre and openjdk-11-jdk and uses openjdk-10 for most of his development environment.

Just to clarify it : mars-sim currently passed maven test and can be compiled under Java 9 and 10. It no longer support Java 8. We have since moved on.

Now I'm trying to figure out what changes it needs to support openjdk 11 and openjfx 11.

**Comment by shirishag75** [comment]
I don't know if this will help you or not but this is the debian openjfx packaging gitlab repo. 

https://salsa.debian.org/java-team/openjfx

Maybe the commits may have some hints that may help you perhaps. 

https://salsa.debian.org/java-team/openjfx/commits/master

**Comment by mokun** [comment]
I notice in that debian repo, they are trying to customize openjfx 11 that works in debian. 

See https://salsa.debian.org/java-team/openjfx/blob/master/debian/README.source

I said the following : 

`OpenJFX for Debian ------------------ The build of OpenJFX has been modified to use the system libraries instead of downloading them from the Maven Central Repository.`

**Comment by shirishag75** [comment]
I wouldn't know if that is current or not, notice that README.source is 4 years old. I would however share that Debian does try not to deviate too much from upstream while at the same time try to have everything under its own roof which means not having users download packages from any third-party sources . The [Debian Policy Manual](https://www.debian.org/doc/debian-policy/) shares all this and more.

**Comment by mokun** [comment]
>  if that is current or not, notice that README.source is 4 years old. 

Yes that README file is old but the other files have just been updated a couple of weeks ago.

It sounds like the debian edition of mars-sim need not include openjfx 11 at all. 

All we need is to configure the pom.xml file correctly with the use of `maven-debian-helper` and the openjfx 11 package will be downloaded and setup automatically.

**Comment by shirishag75** [comment]
we do have openjfx binary package, see https://packages.debian.org/source/unstable/openjfx . Usually most Debian packages use depends and Recommends which makes it easier that much easier to use it. 

Just to share an example, see pdfsam which uses the new openjfx version 11. 

```
$ aptitude show pdfsam
Package: pdfsam                          
Version: 3.3.7-1
State: installed
Automatically installed: no
Priority: optional
Section: text
Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Architecture: all
Uncompressed Size: 1,257 k
Depends: default-jre (>= 2:1.9) | java9-runtime, libfontawesomefx-java (>= 9.1.2), libhibernate-validator-java (>= 4.3.3-2), liblogback-java, libsambox-java (>= 1.1.41), libsejda-java (>= 3.2.56), openjfx (>= 11), libatinject-jsr330-api-java, libbcmail-java (>= 1.58), libbcprov-java (>= 1.58), libcommons-io-java (>= 2.6), libcommons-lang3-java (>= 3.8), libgettext-commons-java, libjackson2-jr-java, libopenjfx-java, libsejda-eventstudio-java (>= 1.0.6), libsejda-injector-java (>= 1.0.2), libslf4j-java (>= 1.7.25)
Description: PDF Split and Merge
 PDF Split and Merge is a very simple, easy to use, free, open source utility to split and merge pdf files. It has a simple graphical interface to let the user choose pdf files, split or merge them.
Homepage: http://www.pdfsam.org

```
