### ISSUE TITLE
Implement detailed scoring for activity selection

### ISSUE THREAD

**Issue by bevans2000** [mars-sim/mars-sim#978]
**Is your feature request related to a problem? Please describe.**
Currently the simulation just return a single value when scoring potential new activities and one is chosen at a weighted random function. Often these selections can be difficult to understand.
The user has no idea what the various component scoring values are. 

**Describe the solution you desire to see**
A new ```Rating``` class can be implemented that holds the final score but also the contributing parts as name value pairs. Then this could be displayed to the end-user. In addition it could dumped to a file or in the console for detailed analysis/tuning.
The same could be applied to numerous places:

- Task probability
- Exploration Site scoring
- Mining Site scoring

Then we could deliver a common class to dump this to a diagnostic file. 

**Describe the rationale**
Clearer understanding of why activities are being chosen so configurations can be tuned more accurately.

**Comment by mokun** [comment]
> A new Rating class can be implemented that holds the final score but also the contributing parts as name value pairs. 

It can certainly be used in many other areas. 

That includes 

1. Why a settlement has a tendency or is good at producing certain parts
2. how a job and role are selected for a settler
3. Why a settlement is more accomplished in executing certain missions/activities/tasks
4. Why a good can be set, produced, or sold at a certain price

**Comment by bevans2000** [comment]
Yes I think this will be a common concept.

**Comment by mokun** [comment]
In terms of where we want to show the modifiers, it should not be difficult to find. 

By hovering over a composite score, a pop-up panel should show the breakdown of that score by each modifier as follows : 

![Screenshot 2023-07-24 at 8 28 21 PM](https://github.com/mars-sim/mars-sim/assets/1168584/895a2930-1096-444a-8c7c-49cc9669ae66)

We won't be able to create translucent panels until we switch over to JavaFX. But it's within our ability to build a custom pop-up panel for housing modifiers, right ?

**Comment by bevans2000** [comment]
Yes I was thinking that.

**Comment by mokun** [comment]
> do the groundworks to apply it to the other areas and a common approach.

Sure. Is it a hovering panel ?

**Comment by bevans2000** [comment]
I think so yes, will be a reusable Tooltip component.

**Comment by mokun** [comment]
> reusable Tooltip component

Sure. I was thinking of tooltip the other day.

In the past, we use weblaf that has some interesting customizations over the regular (ugly) swing tooltip.

Now that we have switched to flatlaf, I found the following two page regarding tooltip : 
1. https://www.formdev.com/flatlaf/components/tooltip/
2. https://github.com/JFormDesigner/FlatLaf/issues/164

I wonder if the timing of tooltip can be a potential issue. May be pop up panel is a better way ?!

**Comment by mokun** [comment]
btw, I can't help comparing [Radiance](https://github.com/kirill-grouchnikov/radiance) with flatlaf. 

Radiance has some built-in animation functions that would be neat for us to use. 

But I don't know how easy or difficult to implement. JavaFX for sure have much better support for animation and timeline, etc.

**Comment by bevans2000** [comment]
I have just finalised the new ```Rating``` framework and used it in how new Missions are selected. Seems to work well and I like it.
Key factor is that there is a dedicated diagnotics file that records the mission selections using JSONLines format. This is a good format for streaming JSON data and the website [JQ Play](https://jqplay.org/) can be used to apply lots of clever filters.
Here is an example below of the selection of a Mission to start.
I will move onto the scoring of Missions next which will lead to the sharable UI component. Then all the other similair areas can be replaced.
![Screenshot 2023-07-29 132927](https://github.com/mars-sim/mars-sim/assets/20720166/9b54cf3b-01f3-4c2c-bd02-d8a143f236e2)

**Comment by mokun** [comment]
That's awesome . How do I use JQPlay ?

**Comment by mokun** [comment]
I suppose what you mean is that once the Json string is output, use JQ Play to convert that into a readable format, right ?

**Comment by bevans2000** [comment]
Correct. If you look at https://jqlang.github.io/jq/ you  an see there are loads of clever filters it can perform. So we will be able to filter for a specific Person or module. 
Of course the file can just be loaded in a normal Editor as well. The JSON lines format is more suited to a stream kf events like this. Once we move onto 3.7.0 I will merge it in.

**Comment by mokun** [comment]
So are you waiting for publishing 3.6.0 first ?

**Comment by bevans2000** [comment]
> So are you waiting for publishing 3.6.0 first ?

Yes because we should apply the Rating pattern everywhere as part of the same release. It's too bit to delay 3.7.0 for as it has enough changes already. Its fine because its on a branch

**Comment by mokun** [comment]
In general, it's very interesting for us to create an *inspector* tool to take a brief look into how a final composite score is settled by breaking it down into many individual scores, one from each category of consideration.  

It really helps us resolve the inner mechanics.

**Comment by bevans2000** [comment]
> I'd love to apply Rating class for manufacturing and food production, in order to see under the hood in real time as to why a process is chosen. Is it possible ?

Yes , exactly. I think we can standardise on this class and then build supporting classes (e.g RatingLog) to make life easier. Also it is enabled by the existing 'diags' command line argument. I'm going to do Mission Planning score next but if you want to apply it to manufacturing then give it a try.
It might need expanding to support multiple base scores that are summed before applying the modifiers.

**Comment by bevans2000** [comment]
> In general, it's very interesting for us to create an _inspector_ tool to take a brief look into how a final composite score is settled by breaking it down into many individual scores, one from each category of consideration.
> 
> It really helps us resolve the inner mechanics.

Good idea. I've been using the jq tool online to look at the JSON Lines format but we could create a window in the sim to do the same things.

**Comment by mokun** [comment]
```
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Mission 'Ice Prospecting' score: Score:3.84 (base:1,settlementratio:1,minerals:4,leader:0.32,extrovert:1.5,goods:1,population:2)
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Mission 'Regolith Prospecting' score: Score:5.383 (base:1,settlementratio:1.4,minerals:4.005,leader:0.32,extrovert:1.5,goods:1,population:2)
01-Adir-01:000.518 (Info) Exploration : [Hong Tian] A site has an Exploration Value of 249.98.
01-Adir-01:000.518 (Info) MissionManager : [Hong Tian] Te Luo - Mission 'Mineral Exploration' score: Score:22.8 (base:1,settlementratio:1.9,minerals:10,leader:0.32,extrovert:1.5,goods:1.25,population:2)
01-Adir-01:000.518 (Info) AbstractMission : [Hong Tian] Te Luo - Began organizing a Mineral Exploration #5 mission.
...
01-Adir-01:063.056 (Info) AnalyzeMapData : [New Pompeii] Agastya Veena - Zoned up a ROI at 22.0000 N 82.8999 W.
01-Adir-01:071.952 (Info) MissionManager : [Hong Tian] Da Wei - Mission 'Ice Prospecting' score: Score:1.3 (base:1,settlementratio:1,minerals:4,leader:0.325,extrovert:1,goods:1,population:1)
01-Adir-01:071.952 (Info) MissionManager : [Hong Tian] Da Wei - Mission 'Regolith Prospecting' score: Score:1.866 (base:1,settlementratio:1.4,minerals:4.1,leader:0.325,extrovert:1,goods:1,population:1)
01-Adir-01:071.952 (Info) Exploration : [Hong Tian] A site has an Exploration Value of 50.6.
01-Adir-01:071.952 (Info) MissionManager : [Hong Tian] Da Wei - Mission 'Mineral Exploration' score: Score:0.965 (base:1,settlementratio:1.9,minerals:2.5,leader:0.325,extrovert:1,goods:1.25,population:0.5)
```

So I can see the breakdown on why a mission is selected now.

**Comment by mokun** [comment]
So far, how do I look at the rating score for a mission or meta mission ?

**Comment by bevans2000** [comment]
> So far, how do I look at the rating score for a mission or meta mission ?

Go to the Backlog tab in the MonitorWindow and the tooltip on the Score column will show you. The new Activity panel will have the same approach.
