### ISSUE TITLE
Job description and country values are off in 4501_headless_java9.jar

### ISSUE THREAD

**Issue by shirishag75** [mars-sim/mars-sim#98]
![wrong-country](https://user-images.githubusercontent.com/727626/47063788-5f8e7180-d1fa-11e8-9110-a7e703225813.png)

If you look at the job type and the country, both the values are off or wrong. 

Trader is not listed anywhere in the professions while the country India is listed as number 3. but when I select it, it takes number 4 i.e. Japan. 

Thinking on it, it probably would be a good idea to tell what choices has been chosen when you make the choice there itself. 

For e.g.  Job = 15 Technician  
              Country = 3 India 

Further down the line where we have the console menu pop up, we should have one more option to change the commander traits just in case s/he made wrong choices instead of just soldering on.

**Comment by mokun** [comment]
Fixed and closed.
