### ISSUE TITLE
Build bioreactor to grow Spirulina (Blue-Green Algae)

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#986]
**Is your feature request related to a problem?**
- Large Algae Greenhouse was commented out in previous version of buildings.xml and constructions.xml
- We had some [discussions](https://github.com/mars-sim/mars-sim/discussions/443) in the past on growing algae in a settlement.

**Describe the solution you desire to see**
- Design an algae pond farm or bioreactor, either as a building or as an add-on in a greenhouse
- Model lifecycle of spirulina
- Harvest spirulina as food source

**Describe the rationale**
- Algae such as Spirulina is a nutritional and functional food source (can be a good source of protein).
- Having spirulina has the advantage of further supplementing and diversifying diet of the settlers.

**Specifications  (please complete the following information):**
 - pre 3.6.0 build 8460

**Additional context**
- Once done, we may also consider growing fungi and utilizing them for practical uses
- After all, we have already been growing one species of mushroom in a mushroom containment box.

**Comment by mokun** [comment]
From this [ref](https://www.cambridge.org/core/journals/international-journal-of-astrobiology/article/sustainable-life-support-on-mars-the-potential-roles-of-cyanobacteria/F22A6C3C0016A98155F0EA78D91D0FB2), one may figure out how to calculate how much nutrients and oxygen is needed for growing algae or cyanobacteria : 

![image](https://github.com/mars-sim/mars-sim/assets/1168584/78000df7-989c-46b6-a42a-aebde521c84b)

**Comment by mokun** [comment]
@bevans2000 

While I'm still refining the algae farming, I notice a few things in Fishery that can be optimized.

Q1: do we need that much weed to feed those fish ? 

Q2: shall we track how much water in each tank and the amount of water needs to be replenished over time ?

Q3: Shall we add age to H? This way, those fish that have passed the age of maturity is recommended to be caught.

Q4: can we catch fish more frequently ?

**Comment by bevans2000** [comment]
> @bevans2000
> 
> While I'm still refining the algae farming, I notice a few things in Fishery that can be optimized.
> 
> Q1: do we need that much weed to feed those fish ?
Probably not. The original values were a guess so just adjust the constants in the calcs.
> 
> Q2: shall we track how much water in each tank and the amount of water needs to be replenished over time ?
Maybe, This would need an new phase of any maintenance task to top the water up. I won't create a new Task.
> 
> Q3: Shall we add age to H? This way, those fish that have passed the age of maturity is recommended to be caught.
> 
> Q4: can we catch fish more frequently ?
Again, the initial parameters was more of a guess. The Growth lifecycle of fish is obviously defined and we can't make them age quicker so the only option is to have more fish.
> 
> [EDIT] Sorry, we should talk about fishery at #320.

**Comment by mokun** [comment]
@bevans2000 

Were you going to comment on something ? Your post above didn't capture your words at all.

**Comment by bevans2000** [comment]
Hmmmmm don't remember doing that. Must have been a mistake.

**Comment by mokun** [comment]
@bevans2000 

I just added tracking water, grey water, O2 and CO2 usage/production in Algae Pond.

We could do something similar for Fish Farm in terms of constantly replenishing ponds with a fresh supply of water. 

Fish Farm won't need sunlight and be a lot easier than growing algae.

Also, it dawns on me that we can create new activity spots for visiting fish farm and greenhouses for Relax Task.

**Comment by mokun** [comment]
I'm done with this for now. 

For additional features, one may open a new thread asking for it.
