### ISSUE TITLE
Actual Yestersol's Sunrise and Sunrise not valid; Concurrent issue when reloaded

### ISSUE THREAD

**Issue by mokun** [mars-sim/mars-sim#999]
**Describe the bug**
- The Yestersol's Sunrise, Sunrise, Daylight, Zenith Time, Max Sunlights are ZERO in Settlement Map. They are not valid.

**Expected and unexpected behavior**
- They should not be zero on all settlements.
 
**Discuss any potential problems you have and have not ruled out**
- The data class may have failed to capture the SunData correctly.

**Java classes involved**
- SettlementTransparentPanel's displaySunData()
- Weather's getSunRecord() should return SunData

**Screenshots**
- On sol 1, it should look like the following :  
![image](https://github.com/mars-sim/mars-sim/assets/1168584/ad808d7c-8f61-490c-9cb2-bf2a4960aa62)

- However, on sol 2 and onward, it shows the following :  
![image](https://github.com/mars-sim/mars-sim/assets/1168584/4ed7a020-63d8-40dd-8341-9724a9f6a037)

- [EDIT] Interestingly, New Plymouth is the only exception that's different from the other 12 settlements.
![image](https://github.com/mars-sim/mars-sim/assets/1168584/2a4b653c-f09c-4e7b-858e-56faa11809a8)

**Specifications (please complete the following information)**
- pre 3.6.0 build 8534

**Comment by mokun** [comment]
@bevans2000 

I see at the minimum this should get fixed before releasing 3.6.0.

**Comment by bevans2000** [comment]
Ok, I will look at this today. There is no need to store a full history just what occurred yesterday. I assume the logic is the Zenith is the mid point  between sunrise and sunset. I see no reason why this can not be calculated on the fly and not stored as a history because it is all predictable.

**Comment by mokun** [comment]
>  I see no reason why this can not be calculated on the fly and not stored as a history because it is all predictable.

mars-sim can have both the theoretical and actual measurements when it comes to weather and sunlight.

Those theoretical values are primarily based on the orbit of Mars around the sun.

But when it comes to the actual daily measurements, which based upon each individual changes having taken place previously, I suppose local weather is supposed to be stochastic and somewhat unpredicted with ups and downs. One can say the variability of elements in the weather system make life more interesting :D

**Comment by mokun** [comment]
>  Zenith is the mid point between sunrise and sunset. 

I suppose zenith is the moment of time when sunlight is at max...

btw, can we switch to using your Datalogger class to store all elements in Weather, namely, all the sun data, also the outside temperature, pressure, wind speed and direction ?

**Comment by bevans2000** [comment]
I think I have found the problem. There is  mistake in the ```SurfaceFeatures::getSolarIrradiance``` method; it is only returning a value for one location because the caching is wrong.

**Comment by mokun** [comment]
I'm getting ConcurrentModificationException when loading from a saved sim.

```
01-Adir-09:214.720 (Severe) UnitManager : Problem with pulse on Starcity: null
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.mars_sim.msp.core.environment.SurfaceFeatures.getSolarIrradiance(SurfaceFeatures.java:294)
	at org.mars_sim.msp.core.structure.building.function.SolarPowerSource.getCurrentPower(SolarPowerSource.java:63)
	at org.mars_sim.msp.core.structure.PowerGrid.stepUpDownPower(PowerGrid.java:273)
	at org.mars_sim.msp.core.structure.PowerGrid.generateMorePower(PowerGrid.java:324)
	at org.mars_sim.msp.core.structure.PowerGrid.timePassing(PowerGrid.java:237)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:901)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:816)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It has issues with the line `currentIrradiance.computeIfAbsent()`

```java
	/**
	 * Calculates the solar irradiance at a particular location on Mars.
	 *
	 * @param location the coordinate location on Mars.
	 * @return solar irradiance (W/m2)
	 */
	public double getSolarIrradiance(Coordinates location) {
		return currentIrradiance.computeIfAbsent(location, this::calculateSolarIrradiance);
	}
```

**Comment by bevans2000** [comment]
Ok, I'll take a look

**Comment by mokun** [comment]
So what makes me loading from a saved aim different from starting from a new sim, in terms of accessing SurfaceFeatures.getSolarIrradiance() ?

**Comment by bevans2000** [comment]
This is a basic Thread safe issue because it is now calculated on demand to reduce wasting processing when not needed.
I have a fix and further optimisation in flight now

**Comment by bevans2000** [comment]
Should have fixed it now

**Comment by mokun** [comment]
@bevans2000 

I've just made the solar data panel collapsible (using SwingX) on the Settlement Map. Now it won't be on your way as you have expressed in the past.

<img width="867" height="632" alt="Image" src="https://github.com/user-attachments/assets/e42db9d1-b0ec-49d8-9a60-3e943b0fae0f" />

<img width="571" height="490" alt="Image" src="https://github.com/user-attachments/assets/e2c08c10-602e-4736-aae2-062dcae6f876" />

**Comment by bevans2000** [comment]
Nice. I would have just it as a layer but that works
